### ISSUE TITLE
Custom SSH Port

### ISSUE THREAD

**Issue by acrom18** [rancher/rke#100]
It would be great, if there was a possiblity to specify a custom ssh port in the cluster.yml file.

**Comment by galal-hussein** [comment]
@acrom18 Thanks for opening an issue, we are going to work on adding a custom ssh port, and it will be available in future releases soon

**Comment by acrom18** [comment]
@galal-hussein Great to hear.

**Comment by moelsayed** [comment]
Tested with latest master. Works as expected.

**Comment by gtirloni** [comment]
Thank you very much!
