### ISSUE TITLE
kubelet connet to 127.0.01:6443 is kube-apiserver not nginx-proxy

### ISSUE THREAD

**Issue by lcx102737** [rancher/rke#1000]
**RKE version:**
  v1.11.3

**Docker version: (`docker version`,`docker info` preferred)**
 1.13.1
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 3.10.0-693.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
  VM
**cluster.yml file:**
  nodes:
- address: "10.0.1.227"
  user: docker_user
  role: [controlplane,etcd,worker]
- address: "10.0.1.228"
  user: docker_user
  ssh_key_path: ~/.ssh/id_rsa
  role: [controlplane,etcd,worker]
- address: "10.0.1.229"
  user: docker_user
  ssh_key_path: ~/.ssh/id_rsa
  role: [controlplane,etcd,worker]
services:
  etcd:
    image: "quay.io/coreos/etcd:latest"
  kube-api:
    image: "rancher/k8s:v1.11.3-rancher2"
    service_cluster_ip_range: "10.233.0.0/18"
    pod_security_policy: false
  kube-controller:
    image: "rancher/k8s:v1.11.3-rancher2"
    cluster_cidr: "10.233.64.0/18"
  scheduler:
    image: "rancher/k8s:v1.11.3-rancher2"
  kubelet:
    image: "rancher/k8s:v1.11.3-rancher2"
    cluster_domain: "cluster.local"
    infra_container_image: "gcr.io/google_containers/pause-amd64:3.0"
    cluster_dns_server: "10.233.0.3"
  kubeproxy:
    image: "rancher/k8s:v1.11.3-rancher2"
network:
  plugin: "flannel"
authentication:
  strategy: "x509"
ignore_docker_version: true
system_images:
  kubedns: "rancher/k8s-dns-kube-dns-amd64:1.14.8"
  dnsmasq: "rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.8"
  kubedns_sidecar: "rancher/k8s-dns-sidecar-amd64:1.14.8"
  kubedns_autoscaler: "rancher/cluster-proportional-autoscaler-amd64:1.0.0"
  nginx_proxy: "rancher/rke-tools:v0.1.9"
  flannel: "rancher/coreos-flannel:v0.9.1"
  flannel_cni: "rancher/coreos-flannel-cni:v0.2.0"
**Steps to Reproduce:**
 ./rke up
**Results:**  
![image](https://user-images.githubusercontent.com/32888559/47973262-885da480-e0de-11e8-95a4-97b81b6201c2.png)

As the picture says, kubelect connect to 127.0.0.1:6443, but 6443 is apiserver's port not nginx-proxy,how  requests to all master nodes?  Is there a problem int cluster.yaml?
 
![image](https://user-images.githubusercontent.com/32888559/47973607-54837e80-e0e0-11e8-8cb5-9043cd2afd26.png)

**Comment by galal-hussein** [comment]
@lcx102737 @mmiller1 we have 3 node types:

etcd
controlplane
worker

each one of them has kubelet and each kubelet talks to the `127.0.0.1:6443` that means that kubelet on control nodes talks directly to the kubeapi on the same hosts, for worker and etcd we set up nginx proxy container which has in its proxy configuration all controlplane nodes, control nodes themselves don't contain nginx proxy, because its easier for kubelet to just talk to the localhost, and in case of the kubeapi on this node fails then it makes sense for kubelet on it to report a failure as well.

**Comment by mmiller1** [comment]
What I was trying to point out is that you have three nodes, and they *all* run the control-plane components, as well as etcd, and are scheduled for workloads:
`role: [controlplane,etcd,worker]`
because they're running the apiserver, I don't believe they are intended to run the nginx loadbalancer.

**Comment by lcx102737** [comment]
@galal-hussein

![image](https://user-images.githubusercontent.com/32888559/48106450-6dbe3380-e276-11e8-8d7a-edb0802c6931.png)
As the picture, I use RKE and helm deploy rancher,through domain name access rancher server.
I have two questions.

Question one ：
rancher's start command is ：
rancher --http-listen-port=80 --https-listen-port=443 --audit-log-path=/var/log/auditlog/rancher-api-audit.log --audit-level=0 --audit-log-maxage=10 --audit-log-maxbackup=10 --audit-log-maxsize=100 --http-listen-port=80 --https-listen-port=443
Parameter --kubeconfig is not used, how rancher server get kubeconfig info? Is it through environment variables($KUBECONFIG)? I did not find this environment variables in rancher server container.

Question two:
If one apiserver down, will the rancher server be accessible in the same node?

**Comment by superseb** [comment]
Let us know if there is anything else needed on this.
