### ISSUE TITLE
install another k8s cluster, how can setup a new etcd cluster

### ISSUE THREAD

**Issue by csbin1204** [rancher/rke#1001]
**RKE version:**
v0.1.8-rc5

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos 7.4.1708

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vmware virtual machine

**cluster.yml file:**
nodes:
- address: 10.12.1.97
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: docker
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
- address: 10.12.1.98
  port: "22"
  internal_address: ""
  role:
  - etcd
  hostname_override: ""
  user: docker
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
- address: 10.12.1.99
  port: "22"
  internal_address: ""
  role:
  - worker
  - etcd
  hostname_override: ""
  user: docker
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: false
    retention: ""
    creation: "true"

**Steps to Reproduce:**
when i want to setup another k8s cluster
./rke up

**Results:**
INFO[0015] [reconcile] Reconciling cluster state        
INFO[0015] [reconcile] Check etcd hosts to be deleted   
INFO[0015] [remove/etcd] Removing member [etcd-10.12.1.123] from etcd cluster 
WARN[0017] [reconcile] Failed to delete etcd member [etcd-10.12.1.123] from etcd cluster 
INFO[0017] [remove/etcd] Removing member [etcd-10.12.1.199] from etcd cluster 
WARN[0019] [reconcile] Failed to delete etcd member [etcd-10.12.1.199] from etcd cluster 
INFO[0019] [reconcile] Check etcd hosts to be added     
INFO[0019] [certificates] Regenerating new etcd-10.12.1.97 certificate and key 
INFO[0020] [certificates] Successfully generated new etcd-10.12.1.97 certificate and key 
INFO[0020] [certificates] Regenerating new etcd-10.12.1.98 certificate and key 
INFO[0020] [certificates] Successfully generated new etcd-10.12.1.98 certificate and key 
INFO[0020] [certificates] Regenerating new etcd-10.12.1.99 certificate and key 
INFO[0021] [certificates] Successfully generated new etcd-10.12.1.99 certificate and key 
FATA[0028] Failed to reconcile etcd plane: Failed to create etcd client for host [10.12.1.99]: client: etcd cluster is unavailable or misconfigured; error #0: Failed to dial to 10.12.1.99:2379: ssh: rejected: connect failed (Connection refused)

10.12.1.123, 10.12.1.199 are in previous k8s cluster
10.12.1.97~99 new k8s cluster

**Comment by galal-hussein** [comment]
@csbin1204 RKE treats the cluster.yml as a cluster, to create several clusters you can just create another cluster.yml and rename it to something different this way rke will create a different kubeconfig file with different name and will treat the cluster as a newly generated cluster instead of trying to reconcile

**Comment by superseb** [comment]
Let us know if you have any other questions on this.
