### ISSUE TITLE
SSH Certificate Authentication

### ISSUE THREAD

**Issue by bernard-wagner** [rancher/rke#1002]
Add the ability to use SSH certificates, in addition to SSH keys. This allows team members to manage a cluster without sharing private keys or maintaining a list of authorized_keys. Would also be useful when automating cluster deployment in CI/CD pipeline that uses Vault for secrets management. 

Additional background:
https://www.vaultproject.io/docs/secrets/ssh/index.html
https://man.openbsd.org/ssh-keygen.1#CERTIFICATES
https://man.openbsd.org/sshd_config#TrustedUserCAKeys

**Comment by cjellick** [comment]
@rmweir to validate (work with @galal-hussein to understand the issue)

**Comment by alena1108** [comment]
Can be tested on `v0.2.0-rc7`

**Comment by rmweir** [comment]
Validated that RKE now supports SSH certificates.

**Steps to validate:**

1. Provision CoreOS vm on Google cloud
2. On local: `ssh-keygen -t rsa -b 4096 -f demo-cert -q -P ""`
3. cat demo-cert.pub
4. On CoreOS: Created sshd_config with 0644 access:
`
UsePrivilegeSeparation sandbox
Subsystem sftp internal-sftp
UseDNS no

PermitRootLogin no
AllowUsers core
AuthenticationMethods publickey
TrustedUserCAKeys /etc/ssh/ssh_trusted_user_ca_keys
`
5. On CoreOS, created file /etc/ssh/ssh_trusted_user_ca_keys with content (output from step 3 on one line) with 0644 access:
`
ssh-rsa AAAAB3NzaC1yc2EA...
`
6. On CoreOs, restart sshd:
`sudo systemctl restart sshd`

7. On local, create new keys:
`ssh-keygen -f test-key -q -P ""`

8. On local, signed key:
`ssh-keygen -s demo-ca -I TEST -n core -V +2h test-key.pub`

9. On local, create cluster.yml with contents:
`
nodes:
  - address: 35.192.208.253
    port: 22
    user: core
    ssh_key_path: ~/.ssh/test-key
    ssh_cert_path: ~/.ssh/test-key-cert.pub
    role: [controlplane,worker,etcd]

ignore_docker_version: true
`

10. On local (in same folder as clutser.yml), use RKE binary made from master latest:
`rke up`

11. On local (in same folder as last step):
kubectl --kubeconfig kube_config_cluster.yml get nodes

**Results:**
Behaved as expected. Properly SSH'd into VM, and created nodes.
![image](https://user-images.githubusercontent.com/19376037/53603753-b70cf880-3b6f-11e9-932a-22263fa84236.png)

**Comment by cjellick** [comment]
Validation is good
