### ISSUE TITLE
rke --dind is leaving behind old configs. 

### ISSUE THREAD

**Issue by jgreat** [rancher/rke#1003]
https://github.com/rancher/rke/blob/deb3518d7824fc5a4002e48ec482e7473ea5235d/dind/dind.go#L48

Looks like its creating a shared bind mount on the host disk. 

Is there any reason to have this mount?

**Comment by alena1108** [comment]
@moelsayed @galal-hussein shall we cleanup the bind mounts when the cluster gets removed?
