### ISSUE TITLE
Unsupported Docker version found [18.06.1-ce]

### ISSUE THREAD

**Issue by devilankur18** [rancher/rke#1015]
**RKE version:**
v0.1.12-rc3

**Docker version: (`docker version`,`docker info` preferred)**
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Fri Oct 19 19:43:14 2018
 OS/Arch:           linux/amd64
 Experimental:      false

$ docker info
Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-23-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.24GiB
Name: whatsserver3
ID: JBGF:6UC3:EM7A:P3EA:7POJ:VAFD:MZOP:F54H:EO4N:PYD6:P4S7:ZV6A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$uname -r
4.15.0-23-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare Metal
**cluster.yml file:**
```
nodes:
  - address: abcd.exmaple.com
    user: root
    role:
      - controlplane
      - worker
      - etcd
    ssh_key_path: ~/.ssh/xyz_rsa

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
```

**Steps to Reproduce:**
rke up --config rancher-cluster.yml

**Results:**
```
WARN[0000] This is not an officially supported version (v0.1.12-rc3) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [abcd.example.com]
FATA[0005] Unsupported Docker version found [18.06.1-ce], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x]
```

**Comment by superseb** [comment]
That version of RKE (which is not officially released) still defaults to Kubernetes 1.11 as default, and `18.06` is not a supported version for that Kubernetes version (https://github.com/rancher/rke/blob/v0.1.12-rc3/docker/docker.go#L40)

You can ignore it (https://rancher.com/docs/rke/v0.1.x/en/config-options/#supported-docker-versions) or set a Kubernetes version that does support that Docker version (1.12): https://rancher.com/docs/rke/v0.1.x/en/config-options/#kubernetes-version
