### ISSUE TITLE
Please explain how rancher forwards requests to the correct k8s cluster

### ISSUE THREAD

**Issue by cristifalcas** [rancher/rke#1028]
Hi,

In debugging issues, I often wonder how my kubectl requests to rancher hostname are sent to the correct k8s cluster apiservers.

We have some connectivity issues and I would like to understand the path of a request. Is each connection sent randomly to a node and the nginx-proxy is forwarding that to an apiserver?

**Comment by superseb** [comment]
If the node is a `controlplane` it forwards to itself on port 6443, if another component needs to reach the `kube-apiserver` if also connects to `localhost:6443` but there is `nginx-proxy` running that dynamically generates its config based on an environment variable containing the nodes running `controlplane` and loadbalances the requests between them. You can run `docker exec nginx-proxy cat /etc/nginx/nginx.conf` to see the generated config.

**Comment by wobi-opsguru** [comment]
I was asking what is the path of the request from my computer, with kubectl and conf file, to a specific k8s cluster.

I'm pointing first to the rancher url, which sends the request to where? To masters of the cluster? To any node from the cluster?

**Comment by cristifalcas** [comment]
I was asking what is the path of the request from my computer, with kubectl and conf file, to a specific k8s cluster.

I'm pointing first to the rancher url, which sends the request to where? To a random master of theat specific cluster? To any node from the cluster?
