### ISSUE TITLE
Ability to configure weave environment variables 

### ISSUE THREAD

**Issue by willmao** [rancher/rke#1033]
**RKE version: v0.1.11

**Docker version: 17.03.2-ce

**Operating system and kernel: 4.4.0-117-generic

LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO): Bare-metal

We want to disable the checkpoints feature of the Weave plugin since our api server does not has internet access while the worker nodes have, and update the plugin automatically in production environment might make the cluster out of our control.

**Comment by willmao** [comment]
weave plugin support disable the feature by setting env variable named CHECKPOINT_DISABLE

https://github.com/rancher/rke/blob/b3249730818f6a919e87db6499e87eb517f60e03/templates/weave.go#L40

**Comment by EdanBrooke** [comment]
Still not implemented? Wow. :(
