### ISSUE TITLE
unbalanced kube-api load 

### ISSUE THREAD

**Issue by willmao** [rancher/rke#1035]
**RKE version:v0.1.11

rke starts a nginx reverse proxy on each worker node to proxy requests to api servers, my cluster has 2 api servers to escape SPOF, i have noticed that the load on the 2 servers differs greatly. when one server is down, requests are distributed to the other healthy server, that's ok, but when the down server comes back, the requests would not be rebalanced back to it.

Is there anyway to rebalance the requests to the api servers?

**Comment by willmao** [comment]
![apiserver-loads](https://user-images.githubusercontent.com/9989192/48680358-a98dbd00-ebd5-11e8-9f4f-1e38e9d16f44.png)

**Comment by sebastien-prudhomme** [comment]
Are you sure you have an Nginx proxy for this use case?

The Nginx proxy is theorically for ingress resource, not for the Kubernetes API.

You need an external load-balancer for the Kubernetes API.

**Comment by willmao** [comment]
sure! according to the doc below:

https://rancher.com/docs/rke/v0.1.x/en/installation/#high-availability

![image](https://user-images.githubusercontent.com/9989192/48759747-13de5480-ecdf-11e8-8b61-1f5a3fca071a.png)

**Comment by sebastien-prudhomme** [comment]
@willmao learn a new thing today, thanks :-)

**Comment by willmao** [comment]
i checked the apiserver metrics with prometheus expression `topk(20,apiserver_request_count)`

![image](https://user-images.githubusercontent.com/9989192/48812017-577ea000-ed6b-11e8-9346-2fbd29994c5d.png)

seems that the most frequent requests are made by kubelet process on the apiservers

**Comment by willmao** [comment]
after upgrade to k8s v1.12.3, issue disappears.
