### ISSUE TITLE
RKE - Deployment onto Linux VM's disconnected from Internet

### ISSUE THREAD

**Issue by dazdaz** [rancher/rke#1038]
Hi,

Can rancher be used to deploy Kubernetes onto Linux VM's which are permanently disconnected from the Internet and cannot even be temporarily connected for a few minutes.

If not, then this is a feature request, to be able to use RKE to deploy Kubernetes onto Linux VM's which are disconnected from the Internet.

**Comment by superseb** [comment]
Air gapped setups are described at https://rancher.com/docs/rke/v0.1.x/en/config-options/private-registries/#air-gapped-setups.
