### ISSUE TITLE
Command to just retrieve kube config to file or stdout

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke#1041]
Sometimes I just need to get the kubeconfig for a cluster I created using rke and don't need to run rke-up again.

**Comment by Oats87** [comment]
Although this doesn't solve this issue, there's a way to generate a new kube_config.yml file if you have SSH/shell access to an RKE control plane host: https://gist.github.com/Oats87/9b27310f5d2937adc87a03ee97675802

This doesn't work on RancherOS however.

**Comment by superseb** [comment]
This is done in https://github.com/rancher/rke/issues/2258
