### ISSUE TITLE
Ability to set iface or environment variables for calico network plugin 

### ISSUE THREAD

**Issue by lcx102737** [rancher/rke#1045]
**RKE version:**
 v0.1.11
**Docker version: (`docker version`,`docker info` preferred)**
 18.03.1-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
  centos7
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
   local host
**cluster.yml file:**
  network:
  plugin: "calico"
  options:
    calico_iface: eth0
**Steps to Reproduce:**
  rke up
**Results:**
  can't find iface: eth0 in calico yaml after rke up,how do i edit cluster.yml ? If I want to set environment 
  variables, How do I do?

gz#10946

**Comment by sigurdblueface** [comment]
bump!
