### ISSUE TITLE
Suggested change to config files

### ISSUE THREAD

**Issue by akara1189** [rancher/rke#1061]
This may have been covered and I may have missed it, but it seems that currently there's no way to 'template' a config file. You have to place a separate entry for each control plane, etcd and/or worker node. I can't just place a config for a node and give a number of nodes with a host list, so it's difficult to use for automating based on new environments. It would be nice to have something like:

nodes:
  - number_of_nodes: <some var that's injected at runtime, listing number of hosts>
    host_list: <some var showing a 'list' of hosts to asses with this configuration>
    user, key, port, etc...

That way, submitting to something like an Ansible play, you could template it and have different numbers depending on the environment or sending it to something like Jenkins and injecting variables to dictate how many hosts you're hitting, etc... The number and addresses wouldn't HAVE to be separated, either, if the parsing was smart enough. Just a thought!

**Comment by superseb** [comment]
See https://github.com/rancher/rke/issues/429

**Comment by spuder** [comment]
The linked issue does not appear to be related.
