### ISSUE TITLE
RKE should have a dry-run option

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#1063]
RKE should have a `dry-run` option that will analyze the state of the currently deployed cluster and determine what changes RKE will make when `rke up` is run.

This would allow much more fine-grained control over the management of RKE-managed kubernetes clusters and allow operators to gain more insight into potential "what went wrongs" if issues occur during an `rke up` rather than figuring this out during runtime.

The output of `rke dry-run` should likely be similar to what you would receive when doing a `terraform plan`

gz#8533
gz#8410

gz#11783

**Comment by stefanlasiewski** [comment]
I would really like to see this feature.

I'm running an upgrade right now. The procedure to upgrade a cluster using RKE is a little unclear, and if I get this wrong the impact will be quite large.

A dry-run feature would offer better assurance and confidence that my configuration is correct.

**Comment by erSitzt** [comment]
Just stumpled upon this... definitely a feature that should be added.
I'm a little afraid to just run rke to upgrade my cluster i created a year ago... and never touched again

**Comment by stefanlasiewski** [comment]
It would still be nice to see this.

I know that RKE's zero-downtime upgrade helps with some of the concerns.

However, the zero-downtime doesn't mitigate all major concerns here-- zero-downtime will happily push out a misconfigured, but functional change. Part of the reason for the `--dry-run` is that we don't always have visibility as to what RKE is going to do to the cluster. If you combine this with the complexity of Kubernetes, having confidence in the upgrade process becomes even more important.

**Comment by stefanlasiewski** [comment]
Was this closed by accident? I'm not sure how to re-open bugs with this repo (Via shortcode, etc).

It's still a good idea.

**Comment by dnoland1** [comment]
No, issue is still open.

**Comment by jostmart** [comment]
Bump: Any chance to get this prioritized?

**Comment by ghost** [comment]
bump

**Comment by user173193** [comment]
This would be incredibly useful. Please make it happen.

**Comment by gmanera** [comment]
This would be incredibly useful. Please make it happen.

**Comment by RP-TSB** [comment]
I'm just in need of the dry option now. I need to add cloud provider to my mainstream cluster running rancher and I don't know if I'm gonna blow it up.

**Comment by fmcwalters-edited** [comment]
this would be useful. Bumping this thread.

**Comment by colegatron** [comment]
this is old, but ... any news on this topic?

**Comment by christiang830** [comment]
not stale

**Comment by RP-TSB** [comment]
5 years later one would hope for at least an answer from the Dev Team.

**Comment by stefanlasiewski** [comment]
Not stale. Still relevant.

**Comment by son-la** [comment]
Very much it is still relevant

**Comment by iohenkies** [comment]
not stale

**Comment by iohenkies** [comment]
Cannot reopen this one, created a new issue https://github.com/rancher/rke/issues/3567
