### ISSUE TITLE
Node autoscaling

### ISSUE THREAD

**Issue by jaxxstorm** [rancher/rke#1067]
**RKE version:**
v0.1.14

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CoreOS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

Currently, it seems the only way to add nodes to a cluster is to update the `cluster.yml` and then reprovision.

Is there any way to add a single node at a time, for example, if an ASG scales up? I'd like to be able to just run RKE on a single node, and then connect it to an existing cluster, but there doesn't seem to be any way to do that.

**Comment by alena1108** [comment]
@jaxxstorm not in standalone RKE. But if you use Rancher (which uses rke internally) there is a host provisioning option called "Custom". When chose this option, Rancher generates the command that you can bake in to AWS cloud init script, so a new node added by ASG would get registered to the cluster automatically.

**Comment by jaxxstorm** [comment]
Can we have this added to RKE, or at least an example command?

**Comment by ajfriesen** [comment]
Would it be possible to do this on the basis of prometheus stats we get from the cluster?
When a value hits a certain threshold there will be an api to rancher so spawn a node in specific cluster in a specific AZ.

**Comment by vikas027** [comment]
Hey @alena1108 ,

This sounds like a chicken-egg problem. In order to host a rancher cluster, I still need a running k8s cluster. It would be great if RKE could handle some kind of autoscaling.

**Comment by jevin36** [comment]
> Hey @alena1108 ,
> 
> This sounds like a chicken-egg problem. In order to host a rancher cluster, I still need a running k8s cluster. It would be great if RKE could handle some kind of autoscaling.

indeed! If you develop a solution on how to (auto)scale your kubernetes cluster for running rancher e.g. with kops you already have a solution and don't really need rancher anymore for the scaling functionality

**Comment by aslafy-z** [comment]
Any news on this matter? We'd like to use RKE to provision our control planes nodes and then make the cluster-autoscaler component provision nodes (from a scale set) for us.

**Comment by aslafy-z** [comment]
Un-stale

**Comment by aslafy-z** [comment]
Un-stale.

**Comment by aslafy-z** [comment]
Un-stale.

**Comment by aslafy-z** [comment]
Un-stale.

**Comment by aslafy-z** [comment]
Nope!

**Comment by Birddude1230** [comment]
This feature would be very useful for our Kubernetes instance. Currently, if any node is in an unhealthy state, rke fails, preventing the node addition from completing. This is especially unfortunate when the core issue is overloaded nodes.

Could someone with relevant experience with the codebase (@deniseschannon ? @superseb ?) comment on the complexity of adding a single-node operation like this? If such a change is not too large/wide-ranging I can likely put together a PR.

Thanks!

**Comment by aslafy-z** [comment]
Not stale

**Comment by aslafy-z** [comment]
Not stale

**Comment by jaxxstorm** [comment]
Not stale

**Comment by aslafy-z** [comment]
Can a maintainer reopen this issue please? @jiaqiluo @kinarashah @superseb
