### ISSUE TITLE
Any ETA on v1.12.4  or v1.13?

### ISSUE THREAD

**Issue by robotica72** [rancher/rke#1069]
Sorry to ask this in the issues section but we have been trying to select a distro for some lab installs and we have looked at a few - using juju / etc - but we want to stay as close to the upstreak as possible, so kubeadm is an option but the HA support being experimental for now is a concern - so looking at RKE now.

Is there any "unofficial" timeframe for new release support?   1.13 has been out for some time now, and the 12.4 release is fairly important as well...  So just curious if there may be any ETAs on either release being added to RKE?

**Comment by hadifarnoud** [comment]
I'd like to know the ETA for 1.13 also

**Comment by Amos-85** [comment]
Hi @hadifarnoud  ,
it's already available
[https://github.com/rancher/hyperkube/tree/v1.13
](url)

**Comment by hadifarnoud** [comment]
@Amos-85 I guess it's not default version then. Is it fully supported? how can I use this version during installation?

**Comment by Amos-85** [comment]
review the hyperkube dockerfile to see the changes:
[https://github.com/rancher/hyperkube/blob/v1.13/Dockerfile](url)

check out how to control system images with rke:
[https://rancher.com/docs/rke/v0.1.x/en/config-options/system-images/](url)

**Comment by hadifarnoud** [comment]
thank you
btw, all the urls in your comments point to the wrong place

**Comment by robotica72** [comment]
Cool - I didnt see the update, I asked the question almost a month aog and the github for 1.13 is only 9 days old and I havent checked in 2 weeks, so great to see...

**Comment by superseb** [comment]
K8s 1.12.4 was released in RKE v0.1.15, 1.13 is coming in the next RKE release (v0.2.0). Changing the images manually is at your own risk.

**Comment by hadifarnoud** [comment]
I did create another cluster from scratch with [this](https://gist.github.com/hadifarnoud/7da2915700e7d132b6f7d8808112b600) config.

during installation I got `WARN[0169] Etcd rolling snapshot container failed to start correctly` and it throws this error later on:
```
FATA[0345] [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [116.202.31.106]: Get https://localhost:10250/healthz: Unable to access the service on localhost:10250. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: F0117 08:46:05.496665    7480 server.go:147] unknown flag: --cadvisor-port
```

**Comment by superseb** [comment]
See: `1.13 is coming in the next RKE release (v0.2.0)`

**Comment by sowmyav27** [comment]
verified on rke v0.2.0-rc6.
K8s v1.12.4 and v1.13.1 are available.

<img width="1060" alt="screen shot 2019-02-22 at 2 23 38 pm" src="https://user-images.githubusercontent.com/26032343/53277827-eed0f780-36ba-11e9-8b1c-80429ca952be.png">

<img width="1416" alt="screen shot 2019-02-22 at 3 58 34 pm" src="https://user-images.githubusercontent.com/26032343/53277828-f0022480-36ba-11e9-8f59-97f13747f745.png">
