### ISSUE TITLE
running rke up multiple times results with lots of orphaned container volumes

### ISSUE THREAD

**Issue by aemneina** [rancher/rke#1074]
**RKE version:**
rke version v0.1.11

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**

**Steps to Reproduce:**
just run rke up a couple times, didnt even need to change anything in the yaml and saw a growth of 10 new volumes.

**Workaround:**
`docker volume prune` should do the trick to reclaim some space

**Results:**
could run out of disk space if one has a smaller volume and runs rke up a few times.

**Comment by galal-hussein** [comment]
@aemneina I was able to find the root cause of this problem, the sidecar container is upgraded 5 times everytime rke runs, the sidecar container is used with k8s components to provide several helper scripts for cloud provider configuration, etc.

**Comment by sangeethah** [comment]
Reproduced this issue with v0.1.11

This issue does not happen when testing with v0.2.0-rc5.
