### ISSUE TITLE
Support for newer Docker version (17.03)

### ISSUE THREAD

**Issue by mmuruganandam** [rancher/rke#108]
Support for 17.03 version of Docker CE.

**Comment by superseb** [comment]
We are in the process of running test on versions other than the initially supported v1.12. There was some code blocking the use of newer versions, which should be fixed in v0.0.8-dev. You can try that for now, we will update docs as soon as we are done.

**Comment by HighwayofLife** [comment]
RKE isn't allowing docker version 17.10...

```
./rke up
INFO[0000] Building Kubernetes cluster                  
INFO[0000] [ssh] Setup tunnel for host [10.18.160.13]   
FATA[0001] Failed to set up SSH tunneling for Etcd host [10.18.160.13]: Unsupported Docker version found [17.11.0-ce], supported versions are [1.12.6 1.13.1 17.03.2] 
```

**Comment by moelsayed** [comment]
@HighwayofLife 17.10 is not supported by Kubernetes, yet. Support will be added when upstream Kubernetes adds support for this version.
