### ISSUE TITLE
0.1.15/aws "Failed to get kubernetes node" error after ""[sync] Syncing nodes Labels and Taints" step

### ISSUE THREAD

**Issue by hashedvalue** [rancher/rke#1098]
**RKE version:**
0.1.15
**Docker version: (`docker version`,`docker info` preferred)**
$ docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$ cat /etc/os-release; uname -r
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
4.15.0-1031-aws
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2
**cluster.yml file:**
[cluster.yml.txt](https://github.com/rancher/rke/files/2799309/cluster.yml.txt)
**Steps to Reproduce:**
Before reinstallation attempt: $ docker ps -qa | xargs docker rm -fv; docker images -q | xargs docker rmi;  sudo rm -rf /etc/kubernetes; rke remove --force
Reinstallation attempt: $ rke up
**Results:**
As visible in attached logfile after "[sync] Syncing nodes Labels and Taints" there is an error a fatal message ~ 'Failed to get kubernetes node [ELASTIC_IP]:  \"ELASTIC_IP\" not found' . Kubernetes cluster is unusable as a result.

Note: all occurences of real elastic IP used were changed to "ELASTIC_IP" string.
[log_20190126182858.txt](https://github.com/rancher/rke/files/2799298/log_20190126182858.txt)

**Comment by aschepp** [comment]
We run into the same issue. The important bit in the config is:
cloud_provider:
  name: aws

If it was set, it would not start with the above mentioned error.

After some trail and error, I found out, that the AWS Instances need DNS names. The first VPC we created had "DNS hostnames: disabled" so it would not automatically assign host names to instances. After enabling it and adding the default dhcp options to the VPC it worked.
