### ISSUE TITLE
make cloud-config permissions configurable

### ISSUE THREAD

**Issue by aemneina** [rancher/rke#1115]
**RKE version:**
v0.1.16
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
openstack
**cluster.yml file:**

**Use Case:**
1. seems permissions for cloud-config are wide open, and cloud config houses sensitive info
2. make a way to pass in desired file permissions
3. this shouldnt be impactful as kubelet, kubeapi, and kubecontroller are privileged containers that access cloud-config

**Comment by aemneina** [comment]
Can we do the same for `/opt/rke/etcd-snapshots/` as the snapshots have sensitive info of a cluster within them. currently they're fairly wide open with `-rw-r--r--`

**Comment by alena1108** [comment]
As a part of the fix, verify that the etcd permissions were hardened. Letting the user to configure the permissions is not in the issue/fix scope.

**Comment by sowmyav27** [comment]
verified using `rancher:master-head` (07/25/2019) - latest

The snapshots created have 600 permissions
```
-rw------- 1 root root 271358 Jul 25 21:19 c-g4sc8-rl-vnspp_2019-07-25T21:19:26Z.zip
```

**Comment by cjellick** [comment]
@superseb had some feedback on the PR, so I bumped it back to working.

**Comment by sowmyav27** [comment]
Verified on latest `master-head`

Snapshot file permissions on the etcd nodes:
```
/opt/rke/etcd-snapshots# ls -ltr
total 932
-rw------- 1 root root 467521 Aug 28 22:50 c-hn4qf-rl-ndghp_2019-08-28T22:50:37Z.zip
-rw------- 1 root root 481770 Aug 28 22:51 c-hn4qf-ml-ltsk4_2019-08-28T22:51:44Z.zip
```
- Able to take snapshots and restore successfully.
- On doing a restore, the snapshot is unzipped and the subsequently deleted from the etcd nodes.
