### ISSUE TITLE
Timeout waiting for kubernetes to be ready

### ISSUE THREAD

**Issue by kevwan** [rancher/rke#112]
**RKE version:**
rke version v0.0.8-dev

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-101-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare metal

**cluster.yml file:**
nodes:
- address: 172.20.27.160
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: six6
  docker_socket: /var/run/docker.sock
- address: 172.20.27.161
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: six6
  docker_socket: /var/run/docker.sock
- address: 172.20.27.162
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: six6
  docker_socket: /var/run/docker.sock
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    extra_args: {}
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
    service_cluster_ip_range: 10.233.0.0/18
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
    cluster_domain: cluster.local
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    cluster_dns_server: 10.233.0.3
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
network:
  plugin: flannel
  options: {}
auth:
  strategy: x509
  options: {}
addons: ""
ssh_key_path: /home/six6/.ssh/id_rsa

**Steps to Reproduce:**
# rke up

**Results:**
...
INFO[0054] [certificates] Save kubernetes certificates as secrets 
FATA[0084] [certificates] Failed to Save Kubernetes certificates: Failed to save certificate [kube-proxy] to kubernetes: [certificates] Timeout waiting for kubernetes to be ready 

After running rke remove, and rke up, I still got the same error.

Thanks!

**Comment by kevwan** [comment]
Add more logs that I found it's because:
ERRO[0043] Post https://172.20.27.160:6443/api/v1/namespaces/kube-system/secrets: dial tcp 172.20.27.160:6443: getsockopt: connection refused

**Comment by galal-hussein** [comment]
@kevwan It looks like kubernetes is not running correctly, can you check the docker container on this host and check all containers are running correctly, also it might help if you pasted all the output from the rke command

**Comment by kevwan** [comment]
@galal-hussein Thanks for your reply!

Eventually, I figured out it's because I was running rancher-server and rancher-agent on the server.

But after this issue fixed, I got another error:
INFO[0061] [certificates] Successfuly saved certificates as kubernetes secret [k8s-certs] 
INFO[0061] [state] Saving cluster state to Kubernetes   
INFO[0061] [state] Successfully Saved cluster state to Kubernetes ConfigMap: cluster-state 
INFO[0061] [network] Setting up network plugin: flannel 
INFO[0061] [addons] Saving addon ConfigMap to Kubernetes 
INFO[0061] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-network-plugin 
INFO[0061] [addons] Executing deploy job..              
DEBU[0061] [k8s] waiting for job rke-network-plugin-deploy-job to complete.. 
Failed to get job complete status: <nil>
FATA[0091] Failed to deploy addon execute job: Failed to get job complete status: <nil> 

BTW, should I close this issue? Because the original issue is my bad, sorry!

**Comment by galal-hussein** [comment]
No problem, glad you found the root cause, will close the issue.

**Comment by galal-hussein** [comment]
@kevwan well, this might be a problem with kubernetes nodes not getting into ready state, can you do `kubectl describe nodes` and print the output

**Comment by kevwan** [comment]
Sorry, I messed up with rancher-server and rke.

Close this issue.

Thanks for help!
