### ISSUE TITLE
Failed to check https://localhost:6443/healthz for service [kube-apiserver]

### ISSUE THREAD

**Issue by zawthanoo** [rancher/rke#1120]
`rke` cannot up successfully because of `healthcheck` failed. 

	INFO[0121] [remove/rke-log-linker] Successfully removed container on host [192.168.88.243]
	INFO[0121] [etcd] Saving snapshot [etcd-rolling-snapshots] on host [192.168.88.58]
	INFO[0127] [certificates] Successfully started [rke-bundle-cert] container on host [192.168.88.58]
	INFO[0127] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [192.168.88.58]
	INFO[0128] [etcd] Successfully started [rke-log-linker] container on host [192.168.88.58]
	INFO[0128] [remove/rke-log-linker] Successfully removed container on host [192.168.88.58]
	INFO[0128] [etcd] Successfully started etcd plane..
	INFO[0128] [controlplane] Building up Controller Plane..
	INFO[0128] [remove/service-sidekick] Successfully removed container on host [192.168.88.249]
	INFO[0128] [remove/service-sidekick] Successfully removed container on host [192.168.88.58]
	INFO[0128] [remove/service-sidekick] Successfully removed container on host [192.168.88.243]
	INFO[0128] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [192.168.88.243]
	INFO[0128] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [192.168.88.249]
	INFO[0128] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [192.168.88.58]
	FATA[0342] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: 
		Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [192.168.88.249]: 
		Get https://localhost:6443/healthz: EOF, log: I0207 07:59:15.858383       1 plugins.go:161] 
		Loaded 6 validating admission controller(s) successfully in the following order: 
		LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,ResourceQuota.

here rancher-cluster.yaml

	nodes:
	  - address: 192.168.88.249
		internal_address: 172.17.0.1
		user: dockeruser
		role: [controlplane,worker,etcd]
	  - address: 192.168.88.243
		internal_address: 172.17.0.1
		user: dockeruser
		role: [controlplane,worker,etcd]
	  - address: 192.168.88.58
		internal_address: 172.17.0.1
		user: dockeruser
		role: [controlplane,worker,etcd]

	services:
	  etcd:
		snapshot: true
		creation: 6h
		retention: 24h

**Comment by superseb** [comment]
Merging in https://github.com/rancher/rke/issues/1121

**Comment by smetal1** [comment]
HI am also stuck in provisioning K8s using RKE. Error:
INFO[0074] [healthcheck] Start Healthcheck on service [kube-apiserver]
