### ISSUE TITLE
Failed to bring up Control Plane: Failed to verify healthcheck: 

### ISSUE THREAD

**Issue by zawthanoo** [rancher/rke#1121]
**RKE version:** - v0.1.15

**Docker version: (`docker version`,`docker info` preferred)** -  17.03.2-ce

*Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** CentOS 7.5 -  64bit 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** - VirtualBox

**cluster.yml file:**

	nodes:
	  - address: 192.168.88.249
		internal_address: 172.17.0.1
		user: dockeruser
		role: [controlplane,worker,etcd]
	  - address: 192.168.88.243
		internal_address: 172.17.0.1
		user: dockeruser
		role: [controlplane,worker,etcd]
	  - address: 192.168.88.58
		internal_address: 172.17.0.1
		user: dockeruser
		role: [controlplane,worker,etcd]

	services:
	  etcd:
		snapshot: true
		creation: 6h
		retention: 24h

**Steps to Reproduce:**

    rke up --config rancher-cluster.yml

**Results:**

	INFO[0121] [remove/rke-log-linker] Successfully removed container on host [192.168.88.243]
	INFO[0121] [etcd] Saving snapshot [etcd-rolling-snapshots] on host [192.168.88.58]
	INFO[0127] [certificates] Successfully started [rke-bundle-cert] container on host [192.168.88.58]
	INFO[0127] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [192.168.88.58]
	INFO[0128] [etcd] Successfully started [rke-log-linker] container on host [192.168.88.58]
	INFO[0128] [remove/rke-log-linker] Successfully removed container on host [192.168.88.58]
	INFO[0128] [etcd] Successfully started etcd plane..
	INFO[0128] [controlplane] Building up Controller Plane..
	INFO[0128] [remove/service-sidekick] Successfully removed container on host [192.168.88.249]
	INFO[0128] [remove/service-sidekick] Successfully removed container on host [192.168.88.58]
	INFO[0128] [remove/service-sidekick] Successfully removed container on host [192.168.88.243]
	INFO[0128] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [192.168.88.243]
	INFO[0128] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [192.168.88.249]
	INFO[0128] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [192.168.88.58]
	FATA[0342] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: 
		Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [192.168.88.249]: 
		Get https://localhost:6443/healthz: EOF, log: I0207 07:59:15.858383       1 plugins.go:161] 
		Loaded 6 validating admission controller(s) successfully in the following order: 
		LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,ResourceQuota.

**Comment by superseb** [comment]
Why is `internal_address` for each node identical? Also seems to be the docker0 bridge (if not modified) If so, please remove the `internal_address` configuration for each node.

If you are reusing nodes, they should be cleaned properly before re-using, see https://rancher.com/docs/rancher/v2.x/en/admin-settings/removing-rancher/user-cluster-nodes/#cleaning-a-node-manually

**Comment by zawthanoo** [comment]
I cleaned up and remove `internal_address`. Now, It is OK. Thank your help
