### ISSUE TITLE
FATA[0143] Failed to get kubernetes node <ip> Error while doing rke up

### ISSUE THREAD

**Issue by pnkjtr** [rancher/rke#1129]
**RKE version:**
```
[67] [16:07:10] → rke --version
rke version v0.1.15
```
I am running  rke on Mac OS.  my nodes are ubuntu-16.04  linux VMs having docker Version:           18.06.1-ce

**Docker version: (`docker version`,`docker info` preferred)**
```
istiouser@kubemaster:~$ docker info
Containers: 9
 Running: 7
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-116-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 47.1GiB
Name: kubemaster
ID: BM3V:MSCA:AKI6:5XFL:FIOU:ZERY:XNUI:DPGO:KHCO:NP4N:RMC2:ZZ2M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://proxy.esl.cisco.com:8080/
No Proxy: localhost,127.0.0.1,registry.cn-dev.io,dockerhub.cisco.com
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

RKE is running on Mac OS.  rke version is v0.1.15
Mac OS version: Mojave (10.14.3 (18D109))

My nodes are ubuntu -16.04.
```
istiouser@kubemaster:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMs are on VMware ESXi 6.5 host.

**cluster.yml file:**
```
ssh_key_path: ~/.ssh/id_rsa
ignore_docker_version: true
cluster_name: IstioLearning
kubernetes_version: "v1.13.1-rancher1-1"

nodes:
- address: 10.106.139.101
  # hostname_override:
  role: [controlplane, worker, etcd]
  user: istiouser
  #hostname_override: kubemaster

  - address: 10.105.201.58
  role: [ worker]
  user: istiouser
  #hostname_override: kubenode02

- address: 10.105.201.59
  role: [ worker]
  user: istiouser
  #hostname_override: kubenode03

authorization:
  mode: rbac

network:
  plugin: calico

ingress:
  provider: nginx

authentication:
  strategy: x509
```

**Steps to Reproduce:**
Its reproduced every time. tried 10/10 and the issue came out.
I am simply doing "rke -d up", with current cluster.yml file.
every thing goes fine (as per the log), but I get this error at the end and rke exit out.

my nodes are configured correctly and I am having ssh setup to all my nodes from my RKE host.
I am able to do password less  ssh to all my node.  
The same issue happens when I give hostname_override filed.  then also it exits saying this hostname not found.

**Results:**
RKE exits out, after following error

```
NFO[0102] [healthcheck] service [kubelet] on host [10.105.201.59] is healthy
INFO[0102] [healthcheck] service [kubelet] on host [10.105.201.58] is healthy
INFO[0105] [worker] Successfully started [rke-log-linker] container on host [10.105.201.59]
INFO[0106] [worker] Successfully started [rke-log-linker] container on host [10.105.201.58]
INFO[0107] [remove/rke-log-linker] Successfully removed container on host [10.105.201.58]
INFO[0107] [healthcheck] Start Healthcheck on service [kube-proxy] on host [10.105.201.58]
INFO[0108] [remove/rke-log-linker] Successfully removed container on host [10.105.201.59]
INFO[0108] [healthcheck] Start Healthcheck on service [kube-proxy] on host [10.105.201.59]
INFO[0108] [healthcheck] service [kube-proxy] on host [10.105.201.58] is healthy
INFO[0108] [healthcheck] service [kube-proxy] on host [10.105.201.59] is healthy
INFO[0111] [worker] Successfully started [rke-log-linker] container on host [10.105.201.58]
INFO[0111] [worker] Successfully started [rke-log-linker] container on host [10.105.201.59]
INFO[0112] [remove/rke-log-linker] Successfully removed container on host [10.105.201.58]
INFO[0112] [remove/rke-log-linker] Successfully removed container on host [10.105.201.59]
INFO[0112] [worker] Successfully started Worker Plane..
INFO[0112] [sync] Syncing nodes Labels and Taints
FATA[0143] Failed to get kubernetes node [10.106.139.101]:  "10.106.139.101" not found
```

but this machine is reachable from my RKE host:
```
[72] [16:13:51] → ping 10.106.139.101
PING 10.106.139.101 (10.106.139.101): 56 data bytes
64 bytes from 10.106.139.101: icmp_seq=0 ttl=52 time=11.410 ms
64 bytes from 10.106.139.101: icmp_seq=1 ttl=52 time=9.746 ms
```

**Comment by superseb** [comment]
Kubernetest 1.13 is not a supported version with this version of RKE, but I guess it is defaulting to the default version of this RKE version anyway.

The node `10.106.139.101` isn't registered to Kubernetes, meaning the `kubelet` can't reach the `kube-apiserver`, which is itself. To retrieve why, can you share output of:

- `docker logs kube-apiserver`
- `docker logs kubelet`
- `netstat -plant | grep 6443`

**Comment by pnkjtr** [comment]
Thanks Sebastiaan for looking at it. 
I was following your blog at: https://rancher.com/an-introduction-to-rke/

Though I have specified Kubernetes_version as 1.13 but it defaults to 1.11.6
 
[21] [20:50:18] → rke version
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Even if I remove Kubernetes_version, I don't see any change in behaviour. I get same error as reported here.

Few logs/ output. that you have asked for:

1.  netstat -plant | grep 6443

istiouser@kubemaster:~$ netstat -plant | grep 6443
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:53148         127.0.0.1:6443          ESTABLISHED -
tcp        0      0 127.0.0.1:53154         127.0.0.1:6443          ESTABLISHED -
tcp        0      0 127.0.0.1:53098         127.0.0.1:6443          ESTABLISHED -
tcp        0      0 127.0.0.1:53142         127.0.0.1:6443          ESTABLISHED -
tcp        0      0 127.0.0.1:53182         127.0.0.1:6443          ESTABLISHED -
tcp6       0      0 :::6443                 :::*                    LISTEN      -
tcp6       0      0 127.0.0.1:6443          127.0.0.1:53154         ESTABLISHED -
tcp6       0      0 127.0.0.1:6443          127.0.0.1:53098         ESTABLISHED -
tcp6       0      0 10.106.139.101:6443     10.105.201.59:47494     ESTABLISHED -
tcp6       0      0 127.0.0.1:6443          127.0.0.1:53182         ESTABLISHED -
tcp6       0      0 10.106.139.101:6443     10.105.201.58:53950     ESTABLISHED -
tcp6       0      0 127.0.0.1:6443          127.0.0.1:53142         ESTABLISHED -
tcp6       0      0 127.0.0.1:6443          127.0.0.1:53148         ESTABLISHED -


once doubt I had,  on my hosts, I have Kubelet service already running. Is  this a requirement ? 
I did not find it mentioned in the above blog.
Shall I stop this and try again ?

Currently Kubelet is running on 10.106.139.101 which I am using as control plane node.

istiouser@kubemaster:~$ sudo systemctl status kubelet.service
[sudo] password for istiouser:
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-02-11 14:20:11 IST; 6h ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 23337 ExecStartPre=/bin/mkdir -p /var/lib/kubelet/volume-plugins (code=exited, status=0/S
 Main PID: 23342 (kubelet)
    Tasks: 67
   Memory: 152.2M
      CPU: 13min 2.787s
   CGroup: /system.slice/kubelet.service
           └─23342 /usr/local/bin/kubelet

**Comment by pnkjtr** [comment]
mistakenly I had Kubelet running on my host machines. which is not required by RKE. I stopped the service from host to avoid port collision.  now RKE is able to install the cluster with k8s 1.11.6 version

 [79]  [23:46:20] → rke version
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

[80]  [23:48:51] → kubectl --kubeconfig kube_config_cluster.yml get nodes
NAME         STATUS   ROLES                      AGE   VERSION
kubemaster   Ready    controlplane,etcd,worker   2h    v1.11.6
kubenode01   Ready    worker                     2h    v1.11.6
kubenode02   Ready    worker                     2h    v1.11.6
kubenode03   Ready    worker                     2h    v1.11.6

**Comment by gonzojive** [comment]
This seems to have resolved the issue for me, but I would not consider the issue closed since the error message is unhelpful. If the root cause is kubelet already running on a particular machine, please consider mentioning that in the error message or prompting the user to stop the process.
