### ISSUE TITLE
K8s cluster broken when trying to remove control plane node after it in not reachable.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rke#113]
RKE version: v0.0.8-dev,

Create a cluster with following configuration:
Node1 -> control , worker , Node2-> control and Node3-> etcd
Power down Node1.
changed cluster.yml  with following configuration to remove Node1 from cluster:
Node2-> control , worker and Node3-> etcd

Up command does not succeed with following error:

```
FATA[0088] [certificates] Failed to Save Kubernetes certificates: Failed to save certificate [kube-admin] to kubernetes: [certificates] Timeout waiting for kubernetes to be ready 
```

Not able to connect with updated config using kubectl:

```
$ ./kubectl get nodes
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-ca")
```

**Comment by soumyalj** [comment]
Tested with rke version v0.0.9-dev
Create a cluster with following configuration:
Node1 -> control , worker , Node2-> control and Node3-> etcd
Power down Node1.
Changed cluster.yml with following configuration to remove Node1 from cluster:
Node2-> control , worker and Node3-> etcd
./rke up command succeeded and the cluster was created successfully. Creation of pods was successful in the cluster
