### ISSUE TITLE
support for docker 18.09.2 - to address the runc issue

### ISSUE THREAD

**Issue by cola4u** [rancher/rke#1130]
**RKE version:** 1.15

**Docker version: (`docker version`,`docker info` preferred)**: 17.03.2 upgrade to 18.09.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**:  RHEL 7.5

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**: VM

**cluster.yml file:**

**Steps to Reproduce:**: upgrade one of the nodes to docker 18.09.2 and run ./rke up again

**Results:**: FATA[0004] Unsupported Docker version found [18.09.2], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x 17.06.x 17.09.x 18.06.x]

**Comment by estevao90** [comment]
Hi. 

You can ignore this verification.

https://rancher.com/docs/rke/v0.1.x/en/config-options/#supported-docker-versions

**Comment by cola4u** [comment]
Thank you @estevao90 !

**Comment by cola4u** [comment]
See @estevao90 reply
