### ISSUE TITLE
core-dns deployment is using "kube-dns" label

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rancher/rke#1135]
**RKE version:**

v0.2.0-rc5

**Docker version: (`docker version`,`docker info` preferred)**

Coredns deployment still use "kube-dns" for k8s-app label.

A chart like "prometheos-operator" is waiting by default for "coredns" value for this label.

Is this value "kube-dns" can be changed to  "coredns"?

**Comment by superseb** [comment]
This is by design, see https://github.com/coredns/deployment/issues/116

**Comment by sebastien-prudhomme** [comment]
Didn't found the reason. Thanks!
