### ISSUE TITLE
Calico inter-host connectivity problem on AWS.

### ISSUE THREAD

**Issue by moelsayed** [rancher/rke#115]
**RKE version:**
v0.0.8-dev
**Docker version: (`docker version`,`docker info` preferred)**
1.12
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aws
**cluster.yml file:**

**Steps to Reproduce:**
Configure a cluster of multiple hosts with calico network plugin.
Pods on different hosts can't reach each other 
**Results:**

**Comment by moelsayed** [comment]
Calico needs specific [configuration](https://docs.projectcalico.org/v2.6/reference/public-cloud/aws) to work on AWS, both on AWS side and on the cluster side. 

The fix implements the needed configuration on the cluster side. On AWS, you need to [disable src/dest checks](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_NAT_Instance.html#EIP_Disable_SrcDestCheck) on the cluster nodes.

**Comment by soumyalj** [comment]
Tested with rke version v0.0.9-dev. Disabled src/des checks on AWS hosts and used them to create a cluster successfully. The config file had the calico settings as below:
```
auth:
  strategy: x509
network:
  plugin: calico
  options:
    calico_cloudprovider : aws
```
Created user pods and verified inter-host communication by exec'ing to the pods. 
Ping between pods on different hosts was successful
```
root@k8testrc2-9xvt4:/# ping 10.233.127.67
PING 10.233.127.67 (10.233.127.67): 48 data bytes
56 bytes from 10.233.127.67: icmp_seq=0 ttl=62 time=0.535 ms
56 bytes from 10.233.127.67: icmp_seq=1 ttl=62 time=0.587 ms
56 bytes from 10.233.127.67: icmp_seq=2 ttl=62 time=0.524 ms
56 bytes from 10.233.127.67: icmp_seq=3 ttl=62 time=0.541 ms
56 bytes from 10.233.127.67: icmp_seq=4 ttl=62 time=0.475 ms
56 bytes from 10.233.127.67: icmp_seq=5 ttl=62 time=0.531 ms


```
