### ISSUE TITLE
Is there a full cluster.yml for AWS or vSphere

### ISSUE THREAD

**Issue by jessehu** [rancher/rke#1154]
Hello RKE,

I'm new to RKE. I googled a bit but didn't find anwsers for these questions:
1) Is there a full cluster.yml for AWS or vSphere
2) When using AWS or vSphere as the cloud provider, how to specify how many VMs to create and vCpu/Mem/Disk for the VM in the cluster.yml?
Or RKE CLI doesn't create the VMs?

Thanks a lot.

**Comment by superseb** [comment]
The Kubernetes cloud provider configuration for both AWS and vSphere are described on https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/.

RKE provisions existing machines, see https://rancher.com/docs/rke/v0.1.x/en/installation/#prepare-the-nodes-for-the-kubernetes-cluster. If you want to automatically create machines and add them to clusters, you can use Rancher.

**Comment by jessehu** [comment]
Thanks @superseb. I didn't find a full cluster.yml file on https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/vsphere either https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/aws.
So RKE (open sourced) deploys K8s on existing machines, and Rancher (an enterprise product) 
automatically create machines and run RKE to deploy K8s.
