### ISSUE TITLE
Sync flannel template with upstream

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1168]
Sync templates with https://github.com/coreos/flannel/blob/v0.10.0/Documentation/kube-flannel.yml and keep 0.9 and 0.10 separate using versioned templates.

**Comment by janeczku** [comment]
This is required so that Hairpin works for Kubernetes pods (a pod connecting to a service that its part of).

**Comment by alena1108** [comment]
Have to test upgrade from 1.13/1.14 to 1.15 as per @superseb there is some upgrade logic might be needed for flannel upgrade.

**Comment by alena1108** [comment]
Calico template was updated for k8s 1.15 - the default version for rke v0.3.0 and Rancher v2.3. Can be tested with rke v0.3.0-rc5 and latest rancher master build

**Comment by alena1108** [comment]
For flannel, there was no image update, but there was a template update. To verify template update, check kube-flannel-cfg config map (kube-system namespace) - it should have the following parameters set:

```
delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
```

**Comment by sangeethah** [comment]
For fresh install checks are tracked in  - https://github.com/rancher/rancher/issues/18721

**Comment by sangeethah** [comment]
Tested with rancher server build - `51769836`

Create clusters with K8s version - v1.14.4 and v1.13.8.
kube-flannel-cfg config map in kube-system namespace has the following parameters.

`delegate\":{\n        \"forceAddress\":true,\n        \"isDefaultGateway\":true\n      }`

Upgrade both the clusters to v1.15.0.
After cluster gets upgraded , kube-flannel-cfg config map in kube-system namespace has the following parameters as expected.

`delegate\": {\n        \"hairpinMode\": true,\n        \"isDefaultGateway\": true\n      }`
