### ISSUE TITLE
Document K8s version 

### ISSUE THREAD

**Issue by jpd-dds** [rancher/rke#1173]
**RKE version:** v0.1.16

**Docker version: (`docker version`,`docker info` preferred)** 18.09.3

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 18.04 LTS 4.15.0-45-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** VirtualBox

**cluster.yml file:**
This is an enhancement request. When attempting to install kubectl, the documentation states "You must use a kubectl version that is within one minor version difference of your cluster. For example, a v1.2 client should work with v1.1, v1.2, and v1.3 master. Using the latest version of kubectl helps avoid unforeseen issues." The documentation for rke needs to say what version of K8n is. I'm assuming its 1.11.3.

**Comment by superseb** [comment]
It's configurable and documented at https://rancher.com/docs/rke/v0.1.x/en/config-options/#kubernetes-version, it says v0.1.15 now, I just submitted a PR to say v0.1.16 but v0.1.16 only added more supported Docker versions.

**Comment by jpd-dds** [comment]
It would be nice to have the documented in the install guide. Even if its just pointer to it.
