### ISSUE TITLE
Vendoring with Go Modules

### ISSUE THREAD

**Issue by maestrofx** [rancher/rke#1180]
Hi,

Just curious to know how's this doing vendor in `vendor.conf`? Is there any of all Rancher's components plan to move using `go modules`?

Thank you.

**Comment by ibuildthecloud** [comment]
We are slowly moving to go modules.  It was quite difficult to do in the past because we depended on a lot of custom kubernetes code. We have slowly been cleaning that up and hope to switch soon.  A big help was that upstream k8s just switched to modules last week.

**Comment by superseb** [comment]
This is done in https://github.com/rancher/rke/pull/1573
