### ISSUE TITLE
Setting up network plugin flannel fails with FATA[0411] Failed to get job complete status: <nil>

### ISSUE THREAD

**Issue by spstratis** [rancher/rke#1181]
**RKE version:**
rke version v0.1.16

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 9
 Running: 7
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-46-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.853GiB
Name: kube-master-1
ID: BKDK:GHLV:7YRE:ZNI2:HAEL:CG5M:OP4O:T36L:QB6H:AP7Q:5Y3D:AXNL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere Private Cloud

**cluster.yml file:**
https://gist.github.com/spstratis/d53f8d337896339c6d282db8b4fe6bcc

**Steps to Reproduce:**
All nodes up and running with docker installed, run `rke up`.

**Results:**
Everything looks like it's working fine until it gets the last section where it needs to set up the network plugin. Below are the last few logs before it errors out. 
```
INFO[0379] [sync] Successfully synced nodes Labels and Taints 
INFO[0379] [network] Setting up network plugin: flannel 
INFO[0379] [addons] Saving addon ConfigMap to Kubernetes 
INFO[0380] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-network-plugin 
INFO[0380] [addons] Executing deploy job..              
FATA[0411] Failed to get job complete status: <nil>    
```

I'm getting the above mentioned error when trying to set up my cluster. When I log onto one of my master nodes (192.168.0.22) and check `docker logs kubelet` I can see some messages saying the following. 

```
W0307 22:24:05.568967   11165 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
E0307 22:24:05.569146   11165 kubelet.go:2106] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

when I check ls through /etc/cni/ net.d isn't even in there. I would assume though that it would be added automatically by RKE. 

More info from the `docker logs kubelet` can be found here 
https://gist.github.com/spstratis/57c414137abd23af56187ca4b6142f7e

Thanks!

**Comment by superseb** [comment]
The kubelet is reporting DiskPressure, can you check how much free space you have available?

**Comment by spstratis** [comment]
So it looks like what kube--node--vg-root is mounted to has very little space....which is weird since the total hard disk is 80GB
```
ubuntu@kube-master-1:~$ df -H
Filesystem                       Size  Used Avail Use% Mounted on
udev                             2.1G     0  2.1G   0% /dev
tmpfs                            414M  1.3M  413M   1% /run
/dev/mapper/kube--node--vg-root  7.2G  6.1G  712M  90% /
tmpfs                            2.1G     0  2.1G   0% /dev/shm
tmpfs                            5.3M     0  5.3M   0% /run/lock
tmpfs                            2.1G     0  2.1G   0% /sys/fs/cgroup
tmpfs                            414M     0  414M   0% /run/user/1000
```

If that's the cause of the issue am I able to adjust where I mount this, or just expand the partition? I know it's an LVM, not all that familiar working with those.

**Comment by superseb** [comment]
If you want to separate your filesystem in different mounts/LVs is up to you, you need to either move `/var/lib/docker` away to a separate LV (making room on root) or resize root. There are plenty of tutorials on LVM :)

**Comment by superseb** [comment]
I created https://github.com/rancher/rke/issues/1182 to give better guidance on this situation, let me know if solving the disk issue does not solve your deployment issue.

**Comment by spstratis** [comment]
Thanks for the help! I assume I need to do this on basically every node since they all have the same storage.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
