### ISSUE TITLE
Checked Step by Step After rke up

### ISSUE THREAD

**Issue by armanriazi** [rancher/rke#1198]
**RKE version:**
0.1.17
**Docker version: (`docker version`,`docker info` preferred)**
17.3.2
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware
**cluster.yml file:**
nodes:
- address: nik15.nik.com          # node air gap network IP
  internal_address: 172.18.3.15   # node intra-cluster IP
  user: ubuntu1604rone
  role: [ "worker" , "controlplane", "etcd"]
  ssh_key_path: ~/.ssh/id_rsa 
- address: nik16.nik.com           # node air gap network IP
  user: ubuntu1604rtwo
  role: [ "worker","controlplane", "etcd" ]
  ssh_key_path: ~/.ssh/id_rsa
- address: nik17.nik.com      # node air gap network IP
  internal_address: 172.18.3.17  # node intra-cluster IP
  user: ubuntu1604rthree
  role: [ "worker","controlplane", "etcd" ]
  ssh_key_path: ~/.ssh/id_rsa
private_registries:
- url: 172.18.3.9:5000 # private registry url
  is_default: true
cluster_name**: cluster_nik**

services:
    etcd:
      snapshot: true
      creation: 15m0s
      retention: 16h

**Steps to Reproduce:**
`root@nik9:/run/systemd# kubectl get pods --all-namespaces -o wide`
**Results:**

> NAMESPACE       NAME                                      READY   STATUS      RESTARTS   AGE     IP            NODE                     NOMINATED NODE   READINESS GATES
> default         dnstest-6n2gt                             1/1     Running     0          9m11s   10.42.2.6     nik15.nik.com   <none>           <none>
> default         dnstest-cb9sk                             1/1     Running     0          9m11s   10.42.1.7     nik16.nik.com   <none>           <none>
> default         dnstest-tpplw                             1/1     Running     0          9m11s   10.42.0.7     nik17.nik.com   <none>           <none>
> default         overlaytest-fj5gm                         1/1     Running     0          53m     10.42.2.3     nik15.nik.com   <none>           <none>
> default         overlaytest-p8gbx                         1/1     Running     0          53m     10.42.0.5     nik17.nik.com   <none>           <none>
> default         overlaytest-w59vk                         1/1     Running     0          53m     10.42.1.3     nik16.nik.com   <none>           <none>
> ingress-nginx   default-http-backend-5855f95cf7-xr2cl     1/1     Running     0          83m     10.42.1.2     nik16.nik.com   <none>           <none>
> ingress-nginx   nginx-ingress-controller-k7scn            1/1     Running     0          83m     172.18.3.16   nik16.nik.com   <none>           <none>
> ingress-nginx   nginx-ingress-controller-mtm9m            1/1     Running     0          83m     172.18.3.15   nik15.nik.com   <none>           <none>
> ingress-nginx   nginx-ingress-controller-mvvf7            1/1     Running     0          83m     172.18.3.17   nik17.nik.com   <none>           <none>
> kube-system     canal-jq27r                               2/2     Running     0          83m     172.18.3.15   nik15.nik.com   <none>           <none>
> kube-system     canal-mr7ft                               2/2     Running     0          83m     172.18.3.16   nik16.nik.com   <none>           <none>
> kube-system     canal-nhd7h                               2/2     Running     0          83m     172.18.3.17   nik17.nik.com   <none>           <none>
> kube-system     kube-dns-67bd8488d9-ll2hl                 3/3     Running     15         83m     10.42.0.4     nik17.nik.com   <none>           <none>
> kube-system     kube-dns-autoscaler-777b5d85b-g5n45       1/1     Running     0          83m     10.42.0.3     nik17.nik.com   <none>           <none>
> kube-system     metrics-server-75868df549-9m9hr           1/1     Running     0          83m     10.42.0.2     nik17.nik.com   <none>           <none>
> kube-system     rke-ingress-controller-deploy-job-hj97j   0/1     Completed   0          83m     172.18.3.15   nik15.nik.com   <none>           <none>
> kube-system     rke-kubedns-addon-deploy-job-7q95w        0/1     Completed   0          83m     172.18.3.15   nik15.nik.com   <none>           <none>
> kube-system     rke-metrics-addon-deploy-job-vxbfd        0/1     Completed   0          83m     172.18.3.15   nik15.nik.com   <none>           <none>
> kube-system     rke-network-plugin-deploy-job-gz647       0/1     Completed   0          83m     172.18.3.15   nik15.nik.com   <none>           <none>
> kube-system     tiller-deploy-598d476bb7-hwswj            1/1     Running     0          73m     10.42.2.2     nik15.nik.com
> 

It seams everythings is ok but when I debugging step by step Troubleshooting Doc it show some  particles:

`root@nik9:/run/systemd# export DOMAIN=www.google.com; echo "=> Start DNS resolve test"; kubectl get pods -l name=dnstest --no-headers -o custom-columns=NAME:.metadata.name,HOSTIP:.status.hostIP | while read pod host; do kubectl exec $pod -- /bin/sh -c "nslookup $DOMAIN > /dev/null 2>&1"; RC=$?; if [ $RC -ne 0 ]; then echo $host cannot resolve $DOMAIN; fi; done; echo "=> End DNS resolve test"

> `=> Start DNS resolve test
> command terminated with exit code 1
> 172.18.3.15 cannot resolve www.google.com
> command terminated with exit code 1
> 172.18.3.16 cannot resolve www.google.com
> command terminated with exit code 1
> 172.18.3.17 cannot resolve www.google.com
> => End DNS resolve test
> 
```
`root@nik9:/run/systemd# kubectl -n kube-system get pods -l k8s-app=kube-dns --no-headers -o custom-columns=NAME:.metadata.name,HOSTIP:.status.hostIP | while read pod host; do echo "Pod ${pod} on host ${host}"; kubectl -n kube-system exec $pod -c kubedns cat /etc/resolv.conf; done
`Pod kube-dns-67bd8488d9-ll2hl on host 172.18.3.17
```

> nameserver 127.0.1.1

And I dont't know why there isn't 8.8.8.8 , 1.1.1.1 .
Maybe I need to append 8.8.8.8 , 1.1.1.1 to /etc/hosts or /etc/resolv.conf
`echo nameserver 8.8.8.8 | sudo tee /etc/resolv.conf`
But I don't think that  is a suit case because of content file "# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
"

contents of file /etc/hosts 
> 127.0.0.1	localhost
> 127.0.1.1	nik9.nik.com nik9
> 172.18.3.10	nik10.nik.com
> 172.18.3.9	nik9.nik.com
> 172.18.3.15	nik15.nik.com
> 172.18.3.16	nik16.nik.com
> 172.18.3.17	nik17.nik.com
> 172.18.3.10     nik10.nik.com.
> 172.18.3.9      nik9.nik.com.
> 172.18.3.15     nik15.nik.com.
> 172.18.3.16     nik16.nik.com.
> 172.18.3.17     nik17.nik.com.
> ::1     ip6-localhost ip6-loopback
> fe00::0 ip6-localnet
> ff00::0 ip6-mcastprefix
> ff02::1 ip6-allnodes
> ff02::2 ip6-allrouters
> 

`kubectl run -it --rm --restart=Never busybox --image=busybox:1.28 -- nslookup kubernetes.default`

> If you don't see a command prompt, try pressing enter.
> Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local
> 
> nslookup: can't resolve 'kubernetes.default'
> pod "busybox" deleted
> pod default/busybox terminated (Error)
> 

After this command I get logs attached file 'Log2.txt' found some error
`kubectl cluster-info dump`

[log2.txt](https://github.com/rancher/rke/files/2960672/log2.txt)

**Comment by superseb** [comment]
The problem is indeed the configured local DNS nameserver on the host, if you resolve that issue, it will work fine. This is described at https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/#check-upstream-nameservers-in-kubedns-container.

Actions needed depend on the local DNS nameserver you are running, you should refer to your OS documentation or documentation on the software (usually dnsmasq).

Let me know if that doesn't resolve the issue.

**Comment by armanriazi** [comment]
@superseb  Not yet , please  switch to  open issue
[ https://github.com/rancher/rancher/issues/16454](url)
