### ISSUE TITLE
Update images for k8s 1.13

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1199]
From https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md:

* `Bumped cluster-proportional-autoscaler to 1.3.0 (#69338, @MrHohn)`
* `Updated defaultbackend to v1.5 (#69334, @bowei)`

**Comment by deniseschannon** [comment]
@superseb should this be closed or updated for k8s 1.15 to make sure it's the latest?

**Comment by superseb** [comment]
These were updated in 1.14 and 1.15+
