### ISSUE TITLE
Support for NSX-T plugin

### ISSUE THREAD

**Issue by randrewedwards** [rancher/rke#122]
We plan on implementing NSX-T across the board for our Openstack and vSphere platforms.

It'll be great if RKE had support to use NSX-T for a CNI.

Documentation can be found (No idea if up to date) here [https://docs.vmware.com/en/VMware-NSX-T/2.0/nsxt_20_ncp_kubernetes.pdf](https://docs.vmware.com/en/VMware-NSX-T/2.0/nsxt_20_ncp_kubernetes.pdf)

**Comment by CalvinHartwell** [comment]
Did you guys manage to find out anything about NSX-T? I can't find the plugin at all anywhere, doesn't seem to be opensource.

**Comment by dstoffel** [comment]
The plugin is available on the vmware portal (require associated licenses for download).
We setup a k8s cluster on NSX-T using PKS (nsx-t builtin), works pretty well but i hope to stop using PKS and use rancher 2.0 instead. 

+1 for nsx-t support

**Comment by nickperry** [comment]
We also want NSX-T support, providing a viable alternative to PKS.
