### ISSUE TITLE
[workerPlane] Failed to bring up Worker Plane: [Failed to start [kubelet] container on host [my.host.name]: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "setup user: no such file or directory": unknown]

### ISSUE THREAD

**Issue by segator** [rancher/rke#1227]
Rancher 2.2.0-RC11

Successful installed Custom cluster with 3 nodes.
then edit yaml and add extra mounts in kubelet
  kubelet: 
    extra_binds: 
      - "/custom/host/dir:/custom/host/dir"

then reapply config and got this error:

[workerPlane] Failed to bring up Worker Plane: [Failed to start [kubelet] container on host [my.host.name]: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "setup user: no such file or directory": unknown]

**Comment by deniseschannon** [comment]
@segator this looks like an issue with Rancher (not with RKE CLI).

Please file a new issue within rancher/rancher if you are still having issues.
