### ISSUE TITLE
rke 0.2.0 up cannot fetch cluster state from Kubernetes, cm cluster-state not available

### ISSUE THREAD

**Issue by surco1971** [rancher/rke#1228]
**RKE version:**
v0.2.0

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.0-ce, build 60ccb22

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Open Telekom Cloud (OpenStack)

**cluster.yml file:**
nodes:
  - address:          10.12.104.110
    user:             ubuntu
    ssh_key_path:     /home/ubuntu/.ssh/id_rsa
    role:             [controlplane,etcd,worker]
  - address:          10.12.104.111
    user:             ubuntu
    ssh_key_path:     /home/ubuntu/.ssh/id_rsa
    role:             [controlplane,etcd,worker]
  - address:          10.12.104.112
    user:             ubuntu
    ssh_key_path:     /home/ubuntu/.ssh/id_rsa
    role:             [controlplane,etcd,worker]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

network:
    plugin: flannel

cluster_name: rancher
kubernetes_version: v1.11.3-rancher1-1

**Steps to Reproduce:**
    In a 3 node cluster
    Remove one node by uncomment node in cluster.yml
    Run rke up

Log:
	rke up
	INFO[0000] Initiating Kubernetes cluster                
	INFO[0000] [state] Possible legacy cluster detected, trying to upgrade 
	INFO[0000] [reconcile] host [10.12.104.111] is active master on the cluster 
	INFO[0000] [state] Fetching cluster state from Kubernetes 
	INFO[0030] Timed out waiting for kubernetes cluster to get state 
	WARN[0030] Failed to fetch state from kubernetes: Timeout waiting for kubernetes cluster to get state 
	
**Results:**
	New CA is created and the new member is not joined to the cluster

**Analysis** 

During the initial rke up run with the 3 nodes, the state is saved:

	INFO[0103] [state] Saving full cluster state to Kubernetes 
	INFO[0103] [state] Successfully Saved full cluster state to Kubernetes ConfigMap: cluster-state 

But the configmap is named differently:

	KUBECONFIG=/var/lib/docker/cluster/raseed-test/kube_config_cluster.yml  kubectl get cm -n kube-system | grep state
	full-cluster-state                   1      4m31s

From the code cluster/state.go one can see, that in SaveFullStateToKubernetes()  the cm FullStateConfigMapName (full-cluster-state ) is updated, but the comment says StateConfigMapName (cluster-state). Within GetStateFromKubernetes() the cm StateConfigMapName (cluster-state) is requested, but not available. 

I checked another cluster (rke 0.1.12) and indeed there the cm is named cluster-state

**Comment by galal-hussein** [comment]
@surco1971 RKE tries to pull the old `cluster-state` configmap when it detect a legacy cluster (created by rke 0.1) it does that by checking if rkestate file exists or not, if not then it attempts to pull the cluster-state, is this cluster created by rke 0.1 or 0.2?

**Comment by hasonhai** [comment]
hi,
if the .rkestate file is deleted by incident, do we have anyway to do recovery?
Thanks

**Comment by 2easy** [comment]
+1
