### ISSUE TITLE
Addons definitions are not applied if cluster resources are manually edited (outside of RKE)

### ISSUE THREAD

**Issue by willmao** [rancher/rke#1245]
> RKE only adds additional add-ons when using rke up multiple times. RKE does not support removing of cluster add-ons when doing rke up with a different list of add-ons.

> As of v0.1.8, RKE will update an add-on if it is the same name.

will rke force update user add-ons every  time when run `rke up` command? i need to create a configmap for ingress-controller to enable `enable-underscores-in-headers` feature, but seems that when run `rke up` multiple times, the add-on configmap will not be updated if i have edited it manually.

**Comment by willmao** [comment]
below is my add-on configuration code:
```
addons: |-
  ---
  apiVersion: v1
  data:
    enable-underscores-in-headers: "true"
  kind: ConfigMap
  metadata:
    name: nginx-configuration
    namespace: ingress-nginx
    labels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx`

**Comment by deniseschannon** [comment]
It should redploy if there are changes to the spec for the add-ons based on this issue: 

https://github.com/rancher/rke/issues/1062

**Comment by superseb** [comment]
So the issue is:

RKE applies the given user addons if the `addons` section in `cluster.yml` is different from the stored configmap. So changing the addons section and applying it gets applied, as the stored configmap will differ from the `addons` section in `cluster.yml`. If you manually change the resources created by the `addons` section, the stored configmap for it won't change so running RKE won't find a difference. Only if you change the addons section again to make it different from the stored configmap, will it apply the changes.

**Comment by willmao** [comment]
Thank you for explaining the mechanism!

RKE compares the addons setting in cluster.yml with the configmap created by the previous deploy.

Close this issue since this is by design.

**Comment by tlvenn** [comment]
@superseb now that rke as some state, could it keep a crc of each addons yaml so that it could detect when they have changed and re apply ?

**Comment by superseb** [comment]
This still needs to be fixed, I'll be adding a write up on this soon. This will give more detail on deciding wether to put it in 2.2 or 2.3

**Comment by superseb** [comment]
Current behavior is not applying changes unless the stored configmap differs from the configured cluster. This means it won't apply when the resources are manually changed. Fixing this would be either:

- Compare actual state vs configured and then apply
- Always apply (will show unchanged if nothing changed, and apply changes if needed)

The decision wether to put this in a patch release is that it's different behavior until now, basically clusters that are configured manually and changed in the meantime, would not get their changes overwritten as it wouldn't be applied. Changing this can possibly revert manual changes which is not desirable (it is when fixed, but not in a patch release)

**Comment by alena1108** [comment]
@superseb the way we do cluster state management doesn't let us do any dynamic determinations about the cluster state. The current cluster state gets stored in the .state file, and all the comparisons are run against it. Ideally the state of the cluster should be determined dynamically, by fetching the actual cluster state. Addons state determination can be done along with that. But all this is a big effort, and can't be done as a part of the patch release. Moving the issue out
