### ISSUE TITLE
Re: WARNING: aws built-in cloud provider is now deprecated. What's the new alternative?

### ISSUE THREAD

**Issue by RAbraham** [rancher/rke#1250]
**RKE version:**
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Docker version: (`docker version`,`docker info` preferred)**
1.12

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

-----
Hi,
I'm excited to learn `rke`. Thanks for making it open source.  I've been following this [tutorial](https://rancher.com/blog/2018/2018-05-14-rke-on-aws/) and when I look at the logs on the master node. I see the following warning:

```
W0402 19:59:51.750947   15561 plugins.go:118] WARNING: aws built-in cloud provider is now deprecated. The AWS provider is deprecated and will be removed in a future release
```
If that is so, what is the new alternative? 

Thanks,
Rajiv

**Comment by superseb** [comment]
It's not removed yet but it's deprecated. It will be moved from in tree to out of tree, and is covered in https://github.com/rancher/rke/issues/1109
