### ISSUE TITLE
Weave 2.5.0 requires portmap

### ISSUE THREAD

**Issue by dbason** [rancher/rke#1258]
Version 2.5.0 of weave installs a conflist as follows in /etc/cni/net.d :
```
{
    "cniVersion": "0.3.0",
    "name": "weave",
    "plugins": [
        {
            "name": "weave",
            "type": "weave-net",
            "hairpinMode": true
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        }
    ]
}
```
To support weave 2.5.0 rke should place portmap in /opt/cni/bin/

**Comment by superseb** [comment]
Portmap was added in https://github.com/rancher/rke-tools/pull/41, what version are you using?

**Comment by dbason** [comment]
Yeah I see a manually created cluster with rke works, however a cluster created from the rancher UI (version 2.1.8) doesn't include portmap - I think this is 0.1.16?

**Comment by superseb** [comment]
Weave is supported in Rancher as of v2.2.0 as described on https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/. 

Can you file an issue in `rancher/rancher` if it doesn't work when using Rancher v2.2.1?

**Comment by ronny35** [comment]
Hello,

I have the same issue with these versions : 
    etcd: rancher/coreos-etcd:v3.3.10-rancher1
    alpine: rancher/rke-tools:v0.1.28
    nginx_proxy: rancher/rke-tools:v0.1.28
    cert_downloader: rancher/rke-tools:v0.1.28
    kubernetes_services_sidecar: rancher/rke-tools:v0.1.28
    kubedns: rancher/k8s-dns-kube-dns-amd64:1.15.0
    dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.15.0
    kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.15.0
    kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
    kubernetes: rancher/hyperkube:v1.14.1-rancher1
    flannel: rancher/coreos-flannel:v0.10.0
    flannel_cni: rancher/coreos-flannel-cni:v0.3.0-rancher1
    calico_node: rancher/calico-node:v3.4.0
    calico_cni: rancher/calico-cni:v3.4.0
    calico_controllers: ""
    calico_ctl: rancher/calico-ctl:v2.0.0
    canal_node: rancher/calico-node:v3.4.0
    canal_cni: rancher/calico-cni:v3.4.0
    canal_flannel: rancher/coreos-flannel:v0.10.0
    weave_node: weaveworks/weave-kube:2.5.0
    weave_cni: weaveworks/weave-npc:2.5.0
    pod_infra_container: rancher/pause-amd64:3.1
    ingress: rancher/nginx-ingress-controller:0.21.0-rancher3
    ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1
    metrics_server: rancher/metrics-server-amd64:v0.3.1


No config is present in the /opt/cni/bin and I have this message : 
rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"kube-dns-autoscaler-6f9fb5cd9f-mbjbb_kube-system\" network: failed to find plugin \"portmap\" in path [/opt/cni/bin]

And, to use weave plugin network with rke, I need to add the addon description yaml according to this url : https://www.weave.works/docs/net/latest/kubernetes/kube-addon/ whereas in the last version it was available without this.
