### ISSUE TITLE
[RFE] allow for rke to leverage S3 compatible object storage servers

### ISSUE THREAD

**Issue by aemneina** [rancher/rke#1264]
**Use case:**
Some users might want to leverage onsite s3 API compatible object stores, like [Minio](https://github.com/minio/minio) . This is particularly useful for air gapped setups.

**Comment by galal-hussein** [comment]
@aemneina this is already supported for etcd snapshots

**Comment by aemneina** [comment]
Thanks, should have checked the docs first.

**Comment by aemneina** [comment]
Looks like this should work but in the case of self signed certs is there a way to specify a CA certificate? If not we can use this ticket to track that. I'll adjust the subject on ack.

**Comment by deniseschannon** [comment]
Please file this in rancher/rancher. This repo is designated for RKE CLI issues.
