### ISSUE TITLE
Proper etcd image tags

### ISSUE THREAD

**Issue by carloscarnero** [rancher/rke#1272]
For several reasons I manage several air-gapped clusters, so I have to download and transfer all the needed images into an internal registry (a process that is properly [documented](https://rancher.com/docs/rke/latest/en/config-options/system-images/)).

In the specific case of the etcd image, I've seen that sometimes there's a suffix in the image tag; for instance, in version [`v1.13.5-rancher1-3`](https://github.com/rancher/types/blob/8b5b82f6ba79dad0cb01a025c14d216dbff4782d/apis/management.cattle.io/v3/k8s_defaults.go#L1058) the image tag is `quay.io/coreos/etcd:v3.2.24-rancher1`. Doing a `docker pull` with that value will result in a not found kind of error, while removing `-rancher1` will do the trick.

When opening [etcd's repository](https://quay.io/repository/coreos/etcd?tag=latest&tab=tags) with a browser, I can't seem to find the `v3.2.24-rancher1` tag, which tells me that maybe the `-rancher1` is superfluous.

**Comment by superseb** [comment]
I think those are changed due to multi arch support, I'm checking that currently.

Both the resulting file from `rke config` and the output `rke config --system-images --all` will provide you with the correct images to use.

**Comment by carloscarnero** [comment]
Understood. In fact, I never used that command despite [being documented](https://rancher.com/docs/rke/latest/en/config-options/#listing-supported-kubernetes-versions). Thank you, and sorry for the noise.
