### ISSUE TITLE
RKE using incorrect healthz port for kubelet causing erroneous healthcheck error message during up

### ISSUE THREAD

**Issue by jlamillan** [rancher/rke#1273]
[RKE is using the kubelet's default port](https://github.com/rancher/rke/blob/master/services/services.go#L46)  (`10250`) to construct the healthz URL for the kubelet.

The issue is that the kubelet's _healthz_ endpoint port [defaults to port 10248](https://k8smeetup.github.io/docs/reference/generated/kubelet/), which is different from the kubelet API port, which RKE is using.

This mismatch is causing an erroneous healthcheck error message in debug mode:

```
DEBU[0053] [healthcheck] Failed to check https://localhost:10250/healthz for service [kubelet] on host [redacted]: Get https://localhost:10250/healthz: Unable to access the service on localhost:10250. The service might be still starting up.
```

I suspect RKE either needs to differentiate between kubelet's API and healthz ports, or explicitly set them to be the same by default via the `--healthz-port` command option. The issue with using the same port is that the API port is HTTPs and requires authentication.  

**RKE version:**

rke version v0.2.1

**Comment by sowmyav27** [comment]
### Verified on v2.2.6
- Deployed an rke cluster - 1 node (all roles)
- in the rancher logs - 
`2019/08/09 00:40:48 [DEBUG] [healthcheck] Failed to check https://localhost:10250/healthz for service [kubelet] on host [<>]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: connect: connection refused`

### verified on master-head - commit id: `bc3700f8 `
- Deployed an rke cluster - 1 node (all roles)
- in the rancher logs - 
`2019/08/08 23:09:58 [DEBUG] [healthcheck] Failed to check http://localhost:10248/healthz for service [kubelet] on host [<ip-addr>]: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused`
