### ISSUE TITLE
RKE fails to correctly fetch cluster-state from a legacy cluster if it has prefix_path

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#1282]
**RKE version:**
0.2.1
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS

**Steps to Reproduce:**

- create ros machine
- run rke v0.1 up on it
- break the kubeconfig by changing the client-certificate-data or client-key-data
- download latest rke 0.2 and run rke up

**Results:**
RKE fails to fetch cluster state from nodes and ends up regenerating new certs/keys and fails

**Comment by galal-hussein** [comment]
After debugging the problem i found that the issue has two parts:

1- saving the state on nodes with prefix path

when saving the state on nodes with prefix path we added a prefix path to the file name which is unnecessary since we already bind mount the prefix path to /etc/kubernetes this caused cluster-state.yml file not being saved on nodes

2- fetching the state from nodes with prefix path

the same error happened here so rke will not be able to fetch the state from the node.

so if the user decided to upgrade to rke 0.2 and ran rke up, assuming the following scenario:

- rke up will try to communicate with k8s api to fetch state/certs
- if kubeconfig failed for any reason or cluster wasn't responsive it will try to fetch state from nodes
- if prefix path has different path or its rancher os system then it will fail to fetch the cluster-state.yml
- rke will attempt to generate new certs
- rke will create a (broken) rkestate and (broken) kubeconfig and rke up will fail

## Fix with the PR

including the PR, the fix steps should be as following:

- make sure that `cluster-state.yml` file exists on the nodes in <prefix_path>/etc/kubernetes/.tmp
- if not exist then create it with content of the same cluster.yml that you have
- remove the broken rkestate file in your local directory
- run rke up

**Comment by soumyalj** [comment]
Reproduced the issue with the steps mentioned above using Rancher OS 1.5.1 nodes using RKE CLI:

1. Create ros machine
2. Run rke v0.1.17 up on it
3. Break the kubeconfig by changing the client-certificate-data or client-key-data in the kubeconfig file
rke up fails as below:
```
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] [state] Possible legacy cluster detected, trying to upgrade 
INFO[0000] [reconcile] Rebuilding and updating local kube config 
INFO[0000] [state] Fetching cluster state from Kubernetes 
WARN[0000] Failed to fetch state from kubernetes: Failed to create Kubernetes Client: Error loading config file "./kube_config_cluster.yml": v1.Config: AuthInfos: []v1.NamedAuthInfo: v1.NamedAuthInfo: AuthInfo: v1.AuthInfo: ClientKeyData: ClientCertificateData: decode base64: illegal base64 data at input byte 1428, error found in #10 byte of ...|tLQo=ABCD","client-k|..., bigger context ...|veTJDZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=ABCD","client-key-data":"LS0tLS1CRUdJTiBSU0EgUFJJVkFURS|... 
```
There is no attempt to get the correct state from the nodes.
4. Download latest rke 0.2.2.-rc1
5. Ensure cluster-state.yml file exists on the nodes in /opt/rke/etc/kubernetes/.tmp
If it doesn't exist, then create it with content of the same cluster.yml that you have
7. remove the broken rkestate file in your local directory
8. run rke up

Cluster comes up correctly.
