### ISSUE TITLE
Ceph RBD support?

### ISSUE THREAD

**Issue by skarlsson** [rancher/rke#129]
Is there support for PersistentVolumes using ceph? If so - any hints on how to set it up?. I can never get the MountVolume.SetUp to succed. 

Ceph Luminius (on Ubuntu 16) - minimum client support kraken
K8s on ubuntu 16 (with ceph-common from ubuntu repo, and "modeprobe rbd" loaded.

**Comment by galal-hussein** [comment]
@skarlsson Currently RKE doesn't provide the support for cloud providers, so its not currently possible to use cloud providers with like AWS, Ceph, etc

**Comment by tobiajo** [comment]
@galal-hussein how come? Ceph RBD does have an internal provisioner, i.e. it is shipped alongside Kubernetes.

**Comment by galal-hussein** [comment]
@tobiajo @skarlsson Sorry for the confusion, i wasn't aware about the integration between ceph and kubernetes, were you able to run the ceph dynamic provisioner successfully? if not what are other requirements it needs before running on Kubernetes cluster?

**Comment by skarlsson** [comment]
Well,  I've managed to connect the ceph cluster to a rancher 1.x cluster and I think i did the same here. On ubuntu 16, in theory you need package ceph_common and modprobe rbd, possibly a  /etc/ceph/ceph.config since the lock code seems to check that file. I was asking to see if someone else had done this before. The claim gets bound both on dynamic provisioning and when you mount an image - but the container startup fails because it cannot mount the volume. I'll revert to jewel compability  and try some more... Any hints appreciated.

**Comment by skarlsson** [comment]
I got it to work by adding a volume mount "/etc/ceph:/etc/ceph" to the kubelet. Is it possible to add volume mounts as parameters or is it ok to always add this?

**Comment by galal-hussein** [comment]
@skarlsson thanks for providing the solution, we can consider adding `/etc/ceph` as volume mount to kubelet

**Comment by galal-hussein** [comment]
Reopening for testing

**Comment by deniseschannon** [comment]
@skarlsson Can you test if this is working with the latest release (`v0.0.9-dev`)?

**Comment by skarlsson** [comment]
sorry for not responding earlier. I confirmed that it's still working
rke:     v0.0.9-dev and v0.0.11-dev
ceph:  v12.2.2 Luminous 
os:      ubuntu 16.04

as a note:  I (still) have to set back ceph compability to hammer - don't know why

otherwise you get lots of messages like those...
Jan 14 14:58:43 f009-k8s kernel: [79208.496241] libceph: mon0 10.1.46.7:6789 feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000

**Comment by skarlsson** [comment]
forgot kubernetes version... both working
k8s_image: rancher/k8s:v1.8.5-rancher4
k8s_image: rancher/k8s:v1.9.1-rancher1-1

**Comment by soumyalj** [comment]
Tested with v0.0.9-dev and v0.0.12-dev. Verified that volume mount /etc/ceph is present on kubelet hosts.
