### ISSUE TITLE
Run more than 110 pods per node

### ISSUE THREAD

**Issue by megastallman** [rancher/rke#1298]
Hi RKE developers!

I like your approach to get a working highly-available cluster. It looks good!

All I'm asking for, is a possibility to run more than 110 pods per node. That involves the overlay network tuning and setting the --max-pods kubelet parameter. I s there any way to achieve that?

For instance, Openshift now provides 250 pods per node by default. It is fairly enough for our 320GB_RAM nodes. Wouldn't it be great for RKE to have such an option? I think, 500 pods per node would be enough to run "substandard" workloads on high-end 1TB servers.

**Comment by vincent99** [comment]
```
services:
  kubelet:
    extra_args:
      max-pods: 250
```

Going above that requires changing all the IP management config too, because the default is a /16 split into one /24 for each node.  So you can only have ~256 nodes with ~253 pods or node.

**Comment by megastallman** [comment]
Thanks!

**Comment by scottrobertson** [comment]
@vincent99 will changing this on an existing cluster cause any issues? Or should it just carry on working with the new limit?

**Comment by vincent99** [comment]
Changing max-pods to <=250 you should be able to just do; going higher requires changing how the address space is distributed and probably would not work or will without deleting all pods.

**Comment by scottrobertson** [comment]
@vincent99 worked. Thank you :)

**Comment by voarsh2** [comment]
This isn't working on RKE 2 and there's no documentation around this.........

**Comment by vtrenton** [comment]
This isn't for RKE2 - this is for RKE1
For RKE2 you can do this with a kubelet configuration file:
```
# kubelet-config.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 250
```

Then in the rke2 config.yaml

```
kubelet-arg:
- config: /my/path/to/kubelet-config.yaml
```

Also, note that this is not advised and strongly discouraged as a solution from upstream: https://kubernetes.io/docs/setup/best-practices/cluster-large/

**Comment by jeremyj563** [comment]
First of all this issue was helpful for me so thank you to everyone here.

Just want to point out that the above config.yaml from @vtrenton is partially incorrect. The value for `kubelet-arg` must be an array of strings (**not** an array of objects). Corrected example would be:

```
kubelet-arg:
- config=/my/path/to/kubelet-config.yaml
```

**Comment by tobiasmuehl** [comment]
In **RKE2** it's not required to make a separate config file, one can also just put

```yaml
kubelet-arg:
  - "max-pods=250"
```

directly in `/etc/rancher/rke2/config.yaml`. Verified this works under `v1.27.10+rke2r1`. [Source](https://www.suse.com/support/kb/doc/?id=000021093)

**Comment by andretocalivros** [comment]
I had the same problem in RKE2 with clusters created by Rancher. Finally solved editing de cluster config (yaml) and added the following:
```yaml
rkeConfig:
  machineGlobalConfig:
    kubelet-arg:
      - max-pods=250
```
