### ISSUE TITLE
Failed to deploy addon execute job: Failed to get job complete status: <nil>

### ISSUE THREAD

**Issue by DiamondYuan** [rancher/rke#130]
**RKE version:**
v0.0.8-dev

**Docker version: (`docker version`,`docker info` preferred)**

 Version:      17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

VirtualBox

**cluster.yml file:**

network:
  plugin: flannel

nodes:
  - address: 192.168.10.67
    user: root
    role: [controlplane, etcd, worker]
  - address: 192.168.10.68
    user: root
    role: [controlplane, etcd, worker]
  - address: 192.168.10.69
    user: root
    role: [controlplane, etcd, worker]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 10.233.0.0/18
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: registry.cn-hangzhou.aliyuncs.com/diamondyuan/pause-amd64
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2

**Steps to Reproduce:**

rke up

**Results:**

INFO[0079] [addons] Setting up KubeDNS
INFO[0079] [addons] Saving addon ConfigMap to Kubernetes
INFO[0079] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-kubedns-addon
INFO[0079] [addons] Executing deploy job..
DEBU[0079] [k8s] waiting for job rke-kubedns-addon-deploy-job to complete..
Failed to get job complete status: <nil>
FATA[0109] Failed to deploy addon execute job: Failed to get job complete status: <nil>

**Comment by galal-hussein** [comment]
@DiamondYuan Can you check kubelet on the hosts, and make sure that they are up and running, also it would be useful if you posted the logs of kubelet, and the result of following command:
```
kubectl describe nodes
```

**Comment by moelsayed** [comment]
@DiamondYuan Can you also provide the logs for the pod(s) name `rke-kubedns-addon-deploy-job-*` in the `kube-system` namespace.

**Comment by DiamondYuan** [comment]
@moelsayed @galal-hussein 

when I use 
```
kubectl describe nodes
```
return nothing

When I use `kubectl get all --all-namespaces` get
```
NAMESPACE     NAME                                 DESIRED   SUCCESSFUL   AGE
kube-system   jobs/rke-network-plugin-deploy-job   1         0            6m

NAMESPACE   NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
default     svc/kubernetes   ClusterIP   10.233.0.1   <none>        443/TCP   7m
```


when i use `kubectl logs jobs/rke-network-plugin-deploy-job -n="kube-system"` return
```
Found 3 pods, using pod/rke-network-plugin-deploy-job-g8k6g
Error from server (NotFound): nodes "192.168.10.67" not found
```

**Comment by galal-hussein** [comment]
@DiamondYuan since `kubectl describe nodes` returns nothing that means that kubeet is not starting correctly on the nodes, you need to grab kubelet logs: `docker logs kubelet` on the hosts

**Comment by DiamondYuan** [comment]
```
I1212 01:50:20.854849   19652 fs.go:139] Filesystem UUIDs: map[]
I1212 01:50:20.854870   19652 fs.go:140] Filesystem partitions: map[shm:{mountpoint:/dev/shm major:0 minor:103 fsType:tmpfs blockSize:0} /dev/sda1:{mountpoint:/var/lib/docker/aufs major:8 minor:1 fsType:ext4 blockSize:0} tmpfs:{mountpoint:/dev major:0 minor:105 fsType:tmpfs blockSize:0}]
I1212 01:50:20.856192   19652 manager.go:216] Machine: {NumCores:2 CpuFrequency:4000015 MemoryCapacity:2079182848 HugePages:[{PageSize:1048576 NumPages:0} {PageSize:2048 NumPages:0}] MachineID: SystemUUID:87024D56-E696-090D-431E-02D01B07ED87 BootID:15f3adba-8d48-4c0e-ba5f-fcc1b49908b4 Filesystems:[{Device:tmpfs DeviceMajor:0 DeviceMinor:105 Capacity:1039589376 Type:vfs Inodes:253806 HasInodes:true} {Device:shm DeviceMajor:0 DeviceMinor:103 Capacity:67108864 Type:vfs Inodes:253806 HasInodes:true} {Device:/dev/sda1 DeviceMajor:8 DeviceMinor:1 Capacity:19945680896 Type:vfs Inodes:1245184 HasInodes:true} {Device:none DeviceMajor:0 DeviceMinor:41 Capacity:19945680896 Type:vfs Inodes:1245184 HasInodes:true}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:21474836480 Scheduler:deadline}] NetworkDevices:[{Name:ens32 MacAddress:00:0c:29:07:ed:87 Speed:1000 Mtu:1500}] Topology:[{Id:0 Memory:2079182848 Cores:[{Id:0 Threads:[0] Caches:[]} {Id:1 Threads:[1] Caches:[]}] Caches:[{Size:8388608 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I1212 01:50:20.857051   19652 manager.go:222] Version: {KernelVersion:4.4.0-103-generic ContainerOsVersion:Ubuntu 16.04.1 LTS DockerVersion:17.03.2-ce DockerAPIVersion:1.27 CadvisorVersion: CadvisorRevision:}
I1212 01:50:20.857798   19652 server.go:422] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained: [Filename				Type		Size	Used	Priority /dev/sda5                               partition	1046524	2000	-1]
```


maybe i need to disable swap

**Comment by galal-hussein** [comment]
@DiamondYuan yes you can either disable swap or add this to kubelet service in cluster.yml file:
```
kubelet:
  image: rancher/k8s:v1.8.3-rancher2
  extra_args: {"fail-swap-on":"false"}
```

**Comment by DiamondYuan** [comment]
Can I replace ` rancher/k8s:v1.8.3-rancher2` to my own image ?
Where i can find the Dockerfile of rancher/k8s

**Comment by galal-hussein** [comment]
@DiamondYuan you can use hyperkube image or any kubernetes image that has the binary in $PATH

**Comment by DiamondYuan** [comment]
It's success on my server but i use `kubectl get all --all-namespaces` rerurn
```
NAMESPACE     NAME              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   ds/kube-flannel   3         3         0         3            0           <none>          3m

NAMESPACE     NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/kube-dns              1         1         1            0           3m
kube-system   deploy/kube-dns-autoscaler   1         1         1            0           3m

NAMESPACE     NAME                                DESIRED   CURRENT   READY     AGE
kube-system   rs/kube-dns-778977457c              1         1         0         3m
kube-system   rs/kube-dns-autoscaler-5cb4f55974   1         1         0         3m

NAMESPACE     NAME                         DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/kube-dns              1         1         1            0           3m
kube-system   deploy/kube-dns-autoscaler   1         1         1            0           3m

NAMESPACE     NAME              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   ds/kube-flannel   3         3         0         3            0           <none>          3m

NAMESPACE     NAME                                DESIRED   CURRENT   READY     AGE
kube-system   rs/kube-dns-778977457c              1         1         0         3m
kube-system   rs/kube-dns-autoscaler-5cb4f55974   1         1         0         3m

NAMESPACE     NAME                                 DESIRED   SUCCESSFUL   AGE
kube-system   jobs/rke-kubedns-addon-deploy-job    1         1            3m
kube-system   jobs/rke-network-plugin-deploy-job   1         1            3m

NAMESPACE     NAME                                      READY     STATUS              RESTARTS   AGE
kube-system   po/kube-dns-778977457c-bpjfn              0/3       Pending             0          3m
kube-system   po/kube-dns-autoscaler-5cb4f55974-95jhx   0/1       Pending             0          3m
kube-system   po/kube-flannel-89d9f                     0/2       ContainerCreating   0          3m
kube-system   po/kube-flannel-brkmk                     0/2       ContainerCreating   0          3m
kube-system   po/kube-flannel-crvdp                     0/2       ContainerCreating   0          3m

NAMESPACE     NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
default       svc/kubernetes   ClusterIP   10.233.0.1   <none>        443/TCP         4m
kube-system   svc/kube-dns     ClusterIP   10.233.0.3   <none>        53/UDP,53/TCP   3m
```

**Comment by galal-hussein** [comment]
can you check `kubectl describe nodes`

**Comment by DiamondYuan** [comment]
```
NAME            STATUS     ROLES                AGE       VERSION
192.168.10.67   NotReady   etcd,master,worker   8m        v1.8.3-rancher1
192.168.10.68   Ready      etcd,master,worker   8m        v1.8.3-rancher1
192.168.10.69   Ready      etcd,master,worker   8m        v1.8.3-rancher1
```

Status is all NotReady at first,and wait for few minutes.2 nodes get ready




Does rke support weave? Readme don't say,but i find i sourceCode;
```
	DefaultWeaveImage             = "weaveworks/weave-kube:2.1.2"
```

**Comment by DiamondYuan** [comment]
I kown the reason.Because GFW in china ,so i cant't pull imge from google

**Comment by galal-hussein** [comment]
@DiamondYuan rke supports weave but it will be available in the next release, do you still have a problem with the setup, if not can you please close the issue, thanks

**Comment by DiamondYuan** [comment]
close
