### ISSUE TITLE
etcdv3.3 reports ETCDCTL_ENDPOINT as unknown environment variable

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1312]
**RKE version:**
v0.2.2

**Steps to Reproduce:**
* Create cluster with one node and Kubernetes 1.14
* Login to the node and run

```
docker exec etcd etcdctl member list
```

**Results:**
```
2019-04-26 15:11:21.688907 W | pkg/flags: unrecognized environment variable ETCDCTL_ENDPOINT=https://0.0.0.0:2379
```

**Comment by alena1108** [comment]
Can be tested with rke `v0.3.0-rc2`

**Comment by sowmyav27** [comment]
verified with `v0.3.0-rc4`

with with cluster - k8s version: 1.13. - on executing command - docker exec etcd etcdctl member list, message - `unrecognized environment variable ETCDCTL_ENDPOINT` is NOT seen.

with with cluster - k8s version: `v1.14.3-rancher1-1`. - on executing command - docker exec etcd etcdctl member list, message - `unrecognized environment variable ETCDCTL_ENDPOINT` is NOT seen.
