### ISSUE TITLE
Etcd S3 backup: allow configuring a private CA to backup on a private Minio server

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rancher/rke#1316]
**RKE version:**

v0.2.2

**Steps to Reproduce:**

Try to backup Etcd on a private Minio server using an internal certificate authority

**Results:**

RKE backup fails with this error:

```
FATA[0002] Failed to take one-time snapshot, exit code [1]: time="2019-04-29T08:37:15Z" level=fatal msg="faield to set s3 server: failed to check s3 bucket:rke, err:Get https://minio.example.com/rke/?location=: x509: certificate signed by unknown authority" 
```

Features that would enable this use case:
- allow an "insecure" mode which disable SSL certificate verification
- allow configuring a certificate authority to connect to the S3 server

**Comment by sdelrio** [comment]
Even when copy  the ca certificate to `/usr/local/share/ca-certificates/` and making `update-ca-certificates` gives the error.

**Comment by dsargent3220** [comment]
We are also running into this with our on prem S3 store.  Is this going to get fixed in 2.2.5?

**Comment by ChrisHaPunkt** [comment]
Same here. We would really appreciate this to be functional.

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/19222

**Comment by sangeethah** [comment]
Closing this issue - https://github.com/rancher/rancher/issues/19222#issuecomment-506532526
