### ISSUE TITLE
RKE doesn't recognize docker image pull error

### ISSUE THREAD

**Issue by DaHoert-sO** [rancher/rke#1317]
**RKE version:**
v0.2.2

**Docker version: (`docker version`,`docker info` preferred)**
18.06.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
os-release:
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15"

uname -r:
4.12.14-25.25-default

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
[cluster.yml.txt](https://github.com/rancher/rke/files/3127422/cluster.yml.txt)

**Steps to Reproduce:**
trying to update a target-node which has too less disk space

**Results:**
rke does not fail when pulling new hyperkube images and says everything was successful:

```
INFO[0009] [pre-deploy] Pulling image [rancher/hyperkube:v1.13.5-rancher1] on host [XXXm02] 
INFO[0030] [pre-deploy] Successfully pulled image [rancher/hyperkube:v1.13.5-rancher1] on host [XXXm02] 
INFO[0030] Kubernetes images pulled successfully        
```
instead it fails later when it tries to bring up control plane:
```
FATA[0079] [controlPlane] Failed to bring up Control Plane: [Failed to create [kube-apiserver] container on host [XXXm02]: Error: No such image: rancher/hyperkube:v1.13.5-rancher1] 
```

while in reality the docker daemon on the target host failed to extract the image

```
2019-04-29T14:42:31.993475+02:00 XXXm02 dockerd[1717]: time="2019-04-29T14:42:31.993171751+02:00" level=info msg="Attempting next endpoint for pull after error: failed to registe
r layer: Error processing tar file(exit status 1): time=\"2019-04-29T14:42:23+02:00\" level=info msg=\"SUSE:secrets :: enabled\"\nopen /opt/az/lib/python3.6/site-packages/azure/mgmt/re
source/resources/v2017_05_10/__init__.py: no space left on device"
```

a manual docker pull would look like this:

```
XXXm02:/home/dahirt # docker pull rancher/hyperkube:v1.13.5-rancher1
v1.13.5-rancher1: Pulling from rancher/hyperkube
73e3e9d78c61: Pull complete 
26fd5cc874d4: Pull complete 
71154a383818: Pull complete 
dc72cda1a886: Pull complete 
fb2d9bd8c41e: Pull complete 
16c0e1b4fd78: Pull complete 
6987d95b1d79: Pull complete 
904ad0f3a448: Pull complete 
0bf584c7b164: Extracting [==================================================>]  84.81MB/84.81MB
failed to register layer: Error processing tar file(exit status 1): time="2019-04-29T14:44:43+02:00" level=info msg="SUSE:secrets :: enabled"
mkdir /opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2016_09_01/__pycache__: no space left on device
XXXm02:/home/dahirt # echo $?
1
```

**Comment by superseb** [comment]
Not sure why the other issue was closed, but I reopened https://github.com/rancher/rke/issues/1010
