### ISSUE TITLE
Backport: etcdv3.3 reports ETCDCTL_ENDPOINT as unknown environment variable

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#1325]
Backport https://github.com/rancher/rke/issues/1312

**Comment by alena1108** [comment]
Fix is available in v0.2.3-rc2

**Comment by sowmyav27** [comment]
verified with `v0.2.3-rc2`. 
with cluster - k8s version: 1.14. - on executing command - `docker exec etcd etcdctl member list`, message - `unrecognized environment variable ETCDCTL_ENDPOINT` is NOT seen.

with with cluster - k8s version: 1.13. - on executing command - `docker exec etcd etcdctl member list`, message - `unrecognized environment variable ETCDCTL_ENDPOINT` is NOT seen.

message - `unrecognized environment variable ETCDCTL_ENDPOINT` was seen for `v0.2.3-rc1`.
