### ISSUE TITLE
alter kube-controller params for a running cluster

### ISSUE THREAD

**Issue by aminebizid** [rancher/rke#1326]
**RKE version: 2.18

How to alter kube-controller params for a running cluster:

horizontal-pod-autoscaler-downscale-delay
horizontal-pod-autoscaler-sync-period
horizontal-pod-autoscaler-upscale-delay

**Comment by superseb** [comment]
See https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/ and https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/horitzontal-pod-autoscaler/
