### ISSUE TITLE
Add GCE cloud provider support

### ISSUE THREAD

**Issue by jnicholls** [rancher/rke#1329]
**RKE version:** 0.2.2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** GCE

I am unfamiliar with how to configure an RKE cluster so that the kube-controller-manager et al have their cloud provider set to GCE. Does RKE not support clusters on GCE, and Rancher favors everyone to use GKE? Forgive my ignorance in advance. I expected to be able to use RKE to establish a cluster on any cloud provider and have Kubernetes work with that cloud provider for service LoadBalancer, volumes, etc.

**Comment by deniseschannon** [comment]
We support any cloud provider supported by upstream Kubernetes. You would need to review the Kubernetes docs on how to set up cloud provider for GCE. 

https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/custom/

**Comment by jnicholls** [comment]
Can you give me an example of how this would work with GCE? Thanks.

**Comment by thxCode** [comment]
Following https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/cloudprovider/providers/gce/gce.go#L170-L201, you could confirm the GCE provider as below template:

```yaml
cloud_provider:
    name: gce
    # Note the pipe as this is what indicates a multiline string
    customCloudProvider: |-
      [Global]
      token-url = <token-url, optional>
      token-body = <token-body, optional>
      # project-id and network-project-id can either be the numeric or string-based unique identifier that starts with [a-z].
      project-id = <project-id, optional>
      ## network-project-id refers to the project which owns the network being used.
      network-project-id = <network-project-id, optional>
      network-name = <network-name, optional>
      subnetwork-name = <subnetwork-name, optional>
      ## secondary-range-name is the name of the secondary range to allocate IP aliases. The secondary range must be present on the subnetwork the cluster is attached to.
      secondary-range-name = <secondary-range-name, optional>
      node-tags = <node-tags, optional>
      node-instance-prefix = <node-instance-prefix, optional>
      regional = <regional, optional>
      multizone = <multizone, optional>
      ## api-endpoint is the GCE compute API endpoint to use. If this is blank, then the default endpoint is used.
      api-endpoint = <api-endpoint, optional>
      ## container-api-endpoint is the GCE container API endpoint to use. If this is blank, then the default endpoint is used.
      container-api-endpoint = <container-api-endpoint, optional>
      ## local-zone specifies the GCE zone that gce cloud client instance is located in (i.e. where the controller will be running). If this is blank, then the local zone will be discovered via the metadata server.
      local-zone = <local-zone, optional>
      ## alpha-features defaults to none, for example: MyFeatureFlag
      alpha-features = <alpha-features, optional>
```

**Comment by jnicholls** [comment]
@thxCode Thank you!

**Comment by jnicholls** [comment]
@deniseschannon I realize any custom provider is supported, but maybe it makes sense to keep this ticket open for first-class support in the interface like AWS and Azure have?

**Comment by anirudh-chhangani** [comment]
Any update on this?
