### ISSUE TITLE
Failed to reconcile etcd plane: Failed to create etcd client

### ISSUE THREAD

**Issue by tuxpeople** [rancher/rke#1333]
**RKE version:**

rke version v0.2.1

**Docker version: (`docker version`,`docker info` preferred)**

<pre>
[root@ran-mas3 ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64
 Experimental:    false
</pre>

<pre>
[root@ran-mas3 ~]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9c3c5f853ebf0ffac0d087e94daef462133b69c7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-957.12.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 1.795 GiB
Name: ran-mas3.lab.eighty-three.me
ID: LDPX:PEAZ:ULD7:NP3D:6CZ5:Q6CV:7EIM:GLCG:AEQR:PTOT:ZCZ5:5JRH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
</pre>

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

<pre>
[root@ran-mas3 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
</pre>

<pre>
[root@ran-mas3 ~]# uname -r
3.10.0-957.12.1.el7.x86_64
</pre>

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**cluster.yml file:**

<pre>
# cat rancher_cluster.yml
nodes:
  - address: 192.168.88.101
    user: rancher
    role: [controlplane,etcd]
  - address: 192.168.88.102
    user: rancher
    role: [controlplane,etcd]
  - address: 192.168.88.103
    user: rancher
    role: [controlplane,etcd]
  - address: 192.168.88.104
    user: rancher
    role: [worker]
    labels:
      physicalmachine: 1
  - address: 192.168.88.105
    user: rancher
    role: [worker]
    labels:
      physicalmachine: 1
  - address: 192.168.88.106
    user: rancher
    role: [worker]
    labels:
      physicalmachine: 2
  - address: 192.168.88.107
    user: rancher
    role: [worker]
    labels:
      physicalmachine: 2
  - address: 192.168.88.108
    user: rancher
    role: [worker]
    labels:
      physicalmachine: 3
  - address: 192.168.88.109
    user: rancher
    role: [worker]
    labels:
      physicalmachine: 3

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

cluster_name: cluster-A

private_registries:
    - url: registry.lab.**********
      user: *********
      password: ***********
</pre>

**Steps to Reproduce:**

`rke up --config ./rancher_cluster.yml`

**Results:**

<pre>
INFO[0000] Initiating Kubernetes cluster
INFO[0000] [certificates] Generating admin certificates and kubeconfig
INFO[0000] Successfully Deployed state file at [./rancher_cluster.rkestate]
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [192.168.88.108]
INFO[0000] [dialer] Setup tunnel for host [192.168.88.102]
INFO[0000] [dialer] Setup tunnel for host [192.168.88.109]
INFO[0000] [dialer] Setup tunnel for host [192.168.88.101]
INFO[0000] [dialer] Setup tunnel for host [192.168.88.105]
INFO[0000] [dialer] Setup tunnel for host [192.168.88.107]
INFO[0000] [dialer] Setup tunnel for host [192.168.88.106]
INFO[0000] [dialer] Setup tunnel for host [192.168.88.104]
INFO[0000] [dialer] Setup tunnel for host [192.168.88.103]
INFO[0000] [network] Deploying port listener containers
INFO[0000] [network] Pulling image [rancher/rke-tools:v0.1.27] on host [192.168.88.101]
INFO[0000] [network] Pulling image [rancher/rke-tools:v0.1.27] on host [192.168.88.102]
INFO[0000] [network] Pulling image [rancher/rke-tools:v0.1.27] on host [192.168.88.103]
INFO[0007] [network] Successfully pulled image [rancher/rke-tools:v0.1.27] on host [192.168.88.103]
INFO[0007] [network] Successfully pulled image [rancher/rke-tools:v0.1.27] on host [192.168.88.101]
INFO[0008] [network] Successfully started [rke-etcd-port-listener] container on host [192.168.88.101]
INFO[0009] [network] Successfully started [rke-etcd-port-listener] container on host [192.168.88.103]
INFO[0009] [network] Successfully pulled image [rancher/rke-tools:v0.1.27] on host [192.168.88.102]
INFO[0010] [network] Successfully started [rke-etcd-port-listener] container on host [192.168.88.102]
INFO[0011] [network] Successfully started [rke-cp-port-listener] container on host [192.168.88.101]
INFO[0011] [network] Successfully started [rke-cp-port-listener] container on host [192.168.88.102]
INFO[0011] [network] Successfully started [rke-cp-port-listener] container on host [192.168.88.103]
INFO[0011] [network] Pulling image [rancher/rke-tools:v0.1.27] on host [192.168.88.107]
INFO[0011] [network] Pulling image [rancher/rke-tools:v0.1.27] on host [192.168.88.109]
INFO[0011] [network] Pulling image [rancher/rke-tools:v0.1.27] on host [192.168.88.106]
INFO[0011] [network] Pulling image [rancher/rke-tools:v0.1.27] on host [192.168.88.105]
INFO[0011] [network] Pulling image [rancher/rke-tools:v0.1.27] on host [192.168.88.108]
INFO[0011] [network] Pulling image [rancher/rke-tools:v0.1.27] on host [192.168.88.104]
INFO[0023] [network] Successfully pulled image [rancher/rke-tools:v0.1.27] on host [192.168.88.109]
INFO[0025] [network] Successfully pulled image [rancher/rke-tools:v0.1.27] on host [192.168.88.107]
INFO[0026] [network] Successfully pulled image [rancher/rke-tools:v0.1.27] on host [192.168.88.108]
INFO[0026] [network] Successfully pulled image [rancher/rke-tools:v0.1.27] on host [192.168.88.106]
INFO[0026] [network] Successfully pulled image [rancher/rke-tools:v0.1.27] on host [192.168.88.105]
INFO[0026] [network] Successfully pulled image [rancher/rke-tools:v0.1.27] on host [192.168.88.104]
INFO[0028] [network] Successfully started [rke-worker-port-listener] container on host [192.168.88.107]
INFO[0028] [network] Successfully started [rke-worker-port-listener] container on host [192.168.88.109]
INFO[0029] [network] Successfully started [rke-worker-port-listener] container on host [192.168.88.105]
INFO[0029] [network] Successfully started [rke-worker-port-listener] container on host [192.168.88.108]
INFO[0030] [network] Successfully started [rke-worker-port-listener] container on host [192.168.88.106]
INFO[0031] [network] Successfully started [rke-worker-port-listener] container on host [192.168.88.104]
INFO[0031] [network] Port listener containers deployed successfully
INFO[0031] [network] Running etcd <-> etcd port checks
INFO[0033] [network] Successfully started [rke-port-checker] container on host [192.168.88.102]
INFO[0033] [network] Successfully started [rke-port-checker] container on host [192.168.88.103]
INFO[0033] [network] Successfully started [rke-port-checker] container on host [192.168.88.101]
INFO[0033] [network] Running control plane -> etcd port checks
INFO[0034] [network] Successfully started [rke-port-checker] container on host [192.168.88.101]
INFO[0034] [network] Successfully started [rke-port-checker] container on host [192.168.88.103]
INFO[0034] [network] Successfully started [rke-port-checker] container on host [192.168.88.102]
INFO[0034] [network] Running control plane -> worker port checks
INFO[0035] [network] Successfully started [rke-port-checker] container on host [192.168.88.103]
INFO[0035] [network] Successfully started [rke-port-checker] container on host [192.168.88.102]
INFO[0035] [network] Successfully started [rke-port-checker] container on host [192.168.88.101]
INFO[0035] [network] Running workers -> control plane port checks
INFO[0036] [network] Successfully started [rke-port-checker] container on host [192.168.88.106]
INFO[0036] [network] Successfully started [rke-port-checker] container on host [192.168.88.109]
INFO[0036] [network] Successfully started [rke-port-checker] container on host [192.168.88.107]
INFO[0036] [network] Successfully started [rke-port-checker] container on host [192.168.88.105]
INFO[0036] [network] Successfully started [rke-port-checker] container on host [192.168.88.104]
INFO[0036] [network] Successfully started [rke-port-checker] container on host [192.168.88.108]
INFO[0036] [network] Checking KubeAPI port Control Plane hosts
INFO[0036] [network] Removing port listener containers
INFO[0036] [remove/rke-etcd-port-listener] Successfully removed container on host [192.168.88.101]
INFO[0036] [remove/rke-etcd-port-listener] Successfully removed container on host [192.168.88.103]
INFO[0036] [remove/rke-etcd-port-listener] Successfully removed container on host [192.168.88.102]
INFO[0036] [remove/rke-cp-port-listener] Successfully removed container on host [192.168.88.102]
INFO[0036] [remove/rke-cp-port-listener] Successfully removed container on host [192.168.88.103]
INFO[0036] [remove/rke-cp-port-listener] Successfully removed container on host [192.168.88.101]
INFO[0037] [remove/rke-worker-port-listener] Successfully removed container on host [192.168.88.107]
INFO[0037] [remove/rke-worker-port-listener] Successfully removed container on host [192.168.88.108]
INFO[0037] [remove/rke-worker-port-listener] Successfully removed container on host [192.168.88.104]
INFO[0037] [remove/rke-worker-port-listener] Successfully removed container on host [192.168.88.109]
INFO[0037] [remove/rke-worker-port-listener] Successfully removed container on host [192.168.88.105]
INFO[0037] [remove/rke-worker-port-listener] Successfully removed container on host [192.168.88.106]
INFO[0037] [network] Port listener containers removed successfully
INFO[0037] [certificates] Deploying kubernetes certificates to Cluster nodes
INFO[0043] [reconcile] Rebuilding and updating local kube config
INFO[0043] Successfully Deployed local admin kubeconfig at [./kube_config_rancher_cluster.yml]
INFO[0043] Successfully Deployed local admin kubeconfig at [./kube_config_rancher_cluster.yml]
INFO[0043] Successfully Deployed local admin kubeconfig at [./kube_config_rancher_cluster.yml]
INFO[0043] [certificates] Successfully deployed kubernetes certificates to Cluster nodes
INFO[0043] [reconcile] Reconciling cluster state
INFO[0043] [reconcile] Check etcd hosts to be deleted
INFO[0043] [reconcile] Check etcd hosts to be added
FATA[0043] Failed to reconcile etcd plane: Failed to create etcd client for host [192.168.88.103]: client: etcd cluster is unavailable or misconfigured; error #0: Unable to access the service on 192.168.88.103:2379. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused)
</pre>

**Comment by ivan-gutierrez-mojix-com** [comment]
Hi Guys, I have the same problem here

`FATA[0050] Failed to reconcile etcd plane: Failed to create etcd client for host [10.100.153.70]: client: etcd cluster is unavailable or misconfigured; error #0: Unable to access the service on 10.100.153.70:2379. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused)`

running on CentOS 7.5

docker version
`Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8`

rke version
`rke version v0.1.18`

**Comment by tuxpeople** [comment]
Right now, it worked again for me. Not sure why, I didn't noting else as before. The only thing I can imagine is: as I always reinstall the CentOS on my nodes from scratch, it may be that they released an update which changed something. Oh, and I redownloaded RKE once again yesterday.
