### ISSUE TITLE
FATA[0006] Failed to delete controlplane node [172.16.1.15] from cluster: Get https://172.16.3.10:6443/api/v1/nodes?timeout=30s: x509: certificate is valid for 172.16.1.15, 172.16.2.15, 172.16.3.15, 127.0.0.1, 10.43.0.1, not 172.16.3.10 

### ISSUE THREAD

**Issue by ibayue** [rancher/rke#1334]
**RKE version:*0.2.1*

**Docker version: docker-ce 17.0.3.2**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: ubuntu 16 4.4.0-141-generic**

**cluster.yml file:*nodes:
    - address: 172.16.1.10
      hostname_override: k8s-etcd1
      user: app
      role:
        - etcd
        - controlplane
    - address: 172.16.2.10
      hostname_override: k8s-etcd2
      user: app
      role:
        - etcd
        - controlplane
    - address: 172.16.3.10
      hostname_override: k8s-etcd3
      user: app
      role:
        - etcd
        - controlplane
    - address: 172.16.1.15
      hostname_override: k8s-master1
      user: app
      role:
        - controlplane
    - address: 172.16.2.15
      hostname_override: k8s-master2
      user: app
      role:
        - controlplane
    - address: 172.16.3.15
      hostname_override: k8s-master3
      user: app
      role:
        - controlplane
    - address: 172.16.1.20
      hostname_override: k8s-node1
      user: app
      role:
        - worker*

**Steps to Reproduce:**

**Results:**

First ip is 172.16.1.15 172.16.2.15 172.16.3.15 node is control, then I added 172.16.1.10 172.16.2.10 172.16.3.10 node added control function

Now I want to delete the 172.16.1.15 172.16.2.15 172.16.3.15 node in order to upgrade these three nodes to ubuntu18, but the error is reported.

![image](https://user-images.githubusercontent.com/11729209/57387933-d23c5a00-71e9-11e9-8eae-039f4bf479e1.png)

![image](https://user-images.githubusercontent.com/11729209/57387960-df594900-71e9-11e9-9a25-2421934bc23e.png)

**Comment by superseb** [comment]
This should be fixed in 0.2.4: https://github.com/rancher/rancher/issues/16151
