### ISSUE TITLE
"Failed to get job complete status for job rke-user-includes-addons-deploy-job in namespace kube-system" when install user addons from multiple sources URL/file

### ISSUE THREAD

**Issue by NurFaizin** [rancher/rke#1337]
**RKE version: 0.2.2**

**Docker version: 18.09.5**

**Operating system and kernel: Ubuntu 18.04.2**

**Type/provider of hosts: Bare-metal**

**cluster.yml file:**
`addons_include:`
`- ./addons/dashboard/kubernetes-dashboard.yml`
`- ./addons/dashboard/dashboard-admin.yml`
`- ./addons/loadbalancer/metallb.yaml`

**Steps to Reproduce:**
When I include addons on multiple file resources, it getting WARN error:
`Failed to deploy addon execute job [rke-user-includes-addons]: Failed to get job complete status for job rke-user-includes-addons-deploy-job in namespace kube-system`

**Temporary Solutions**
I tried to use **RKE v0.2.1** and **its working well**.

**Comment by superseb** [comment]
I assume this is fixed by https://github.com/rancher/rke/issues/1149, let me know if you still run into issues
