### ISSUE TITLE
rke up should report what port connectivity it is testing

### ISSUE THREAD

**Issue by mjbright** [rancher/rke#1346]
RKE version:
v0.2.2

My issue is not OS / Docker version / config dependent.

Whilst the ports required are listed in the documentation, [here ](https://rancher.com/docs/rancher/v2.x/en/installation/requirements/) for example it would be useful that `rke up` report what connectivity, i.e. port number/ip address, it is currently testing
(at least in verbose/debug mode).

I had the case where no timeout was occurring.

Is this easy to do, or a bit complicated because of the containerized nature of the port tests?

**Comment by superseb** [comment]
Can you share the full log of a run where it got stuck and it was not clear, there is some debug logging on connectivity checks but we can improve it if needed
