### ISSUE TITLE
failed to run Kubelet: could not init cloud provider "aws": AWS cloud failed to find ClusterID

### ISSUE THREAD

**Issue by kumarselva007** [rancher/rke#1350]
[workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [ec2-54-255-207-15.ap-southeast-1.compute.amazonaws.com]: Get https://localhost:10250/healthz: Unable to access the service on localhost:10250. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: F0520 14:52:30.359874   32443 server.go:261] failed to run Kubelet: could not init cloud provider "aws": AWS cloud failed to find ClusterID

**Comment by jiaqiluo** [comment]
@kumarselva007  I met the same issue today when I am starting an RKE cluster for installing Rancher in HA mode. The RKE document says I need to tag my instances in AWS: https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/aws/#iam-requirements

 
<img width="739" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58919368-aa55ee80-86e2-11e9-8f86-ab8d68652781.png">

The issue is sovled after I adding the tag. Hope this will work for you, too.

**Comment by superseb** [comment]
Let us know if that doesn't solve your issue.

**Comment by th3lolipop** [comment]
all you need to do is adding the TAG in your EC2 instance or Launch Template/Configuration

> kubernetes.io/cluster/<your_cluster_name> : owned

Problem Solved :100:

**Comment by gp187** [comment]
I have the same problem, the tags have been correctly set by Rancher but it still doesn't work.

```

[controlPlane] Failed to upgrade Control Plane: [[[controlplane] Error getting node controlpane1: "controlpane1" not found]]
--
```

**Comment by rex** [comment]
I am having this issue as well, it occurred during an upgrade of the Kubernetes version of the cluster. SSHing into the failing node and tailing the `kubelet` log revealed this error message (indentation mine, for readability):

```
server.go:274] failed to run Kubelet: could not init cloud provider "aws": 
error finding instance i-0498a9ba1d28ead09: 
    "error listing AWS instances: 
        "AuthFailure: AWS was not able to validate the provided access credentials
    status code: 401,
    request id: 174ee5db-dfcc-4b1d-ace0-bd166d8cd401\""
```

What I find curious about this is that this cluster also fails to _read_ S3 snapshots it creates. It creates them just fine, I can see the etcd snapshot in S3. But the UI shows that authorization failed when trying to retrieve the snapshot information. I suspect the errors are related. 

I am going to reboot the node and see how it goes. Hopefully it doesn't hose the kube upgrade.

**Comment by debdeep-das** [comment]
I am having the same issue with v2.5.5. I have added the tags on all the resources used by the cluster
