### ISSUE TITLE
Consider putting local etcd as a first item of `etcd-servers` argument for k8s api 

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#1352]
For clusters with multiple etcd and control plane nodes, we always build etcd nodes list the same way for all api servers. With a config.yml example:
```
node1:
  role: all
node2:
  role: all
node3:
  role: all
```
you get the same list in `etcd-servers` for every api server: `etcd-servers=https://node1.ip:2379,https://node2.ip:2379,https://node3.ip:2379"`

We should think of putting etcd of a local node (if there is one) first in the list. So it will be like:

```
node1: "etcd-servers=https://node1.ip:2379,https://node2.ip:2379,https://node3.ip:2379"
node2: "etcd-servers=https://node2.ip:2379,https://node1.ip:2379,https://node3.ip:2379"
node3: "etcd-servers=https://node3.ip:2379,https://node1.ip:2379,https://node2.ip:2379"
```

**Comment by sangeethah** [comment]
Tested with master-head - 7f8c1191 

Create a 3 node cluster with all nodes having all 3 roles.

Etcd of the local node gets put first in the list  - `docker inspect kube-apiserver | grep etcd-server` 
node1: "etcd-servers=https://node1.ip:2379,https://node2.ip:2379,https://node3.ip:2379"
node2: "etcd-servers=https://node2.ip:2379,https://node1.ip:2379,https://node3.ip:2379"
node3: "etcd-servers=https://node3.ip:2379,https://node1.ip:2379,https://node2.ip:2379"
