### ISSUE TITLE
Question about nginx configuration

### ISSUE THREAD

**Issue by franck-mosse** [rancher/rke#1355]
**RKE version:**
v0.2.2

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

What is the best way to update the nginx configuration file of the nginx deploy on K8s nodes in order to add other upstreams ?

My concern is the following:
I have deployed an internal docker registry on each master. These registries contain all the docker images of my application. Nodes must be able to pull these images but for HA purposes i would like get access through a local proxy that load balances http requests (done by docker pull) to all my internal registries across masters nodes.
I would like to reuse the nginx deployed by RKE but does not know how to update easily its configuration.

what are your advices ?

**Comment by superseb** [comment]
I guess this is the best starting point: https://kubernetes.github.io/ingress-nginx/examples/docker-registry/

Let me know if you have more questions on this.
