### ISSUE TITLE
etcd snapshot-save to S3 does not support HTTP

### ISSUE THREAD

**Issue by litaxc** [rancher/rke#1359]
**RKE version:**
`v0.2.2`

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54266
 Built:             Wed Mar 27 18:35:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`4.15.0-45-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**

**Steps to Reproduce:**
1. deploy a standalone minio s3 server: `docker run -p 9000:9000 -v /mnt/data:/data -v /mnt/config:/root/.minio minio/minio server /data`  
2. make the necessary bucket
3. run `rke etcd snapshot-save --name *** --s3 --s3-endpoint http://10.41.75.77:9000 --access-key=*** --secret-key=*** --bucket-name=etcd-snapsho`

**Results:**
```
FATA[0005] Failed to take one-time snapshot, exit code [1]: time="2019-05-24T02:11:14Z" level=fatal msg="faield to set s3 server: failed to check s3 bucket:etcd-snapshot, err:Get https://10.41.75.77:9000/etcd-snapshot/?location=: http: server gave HTTP response to HTTPS client"
```

It seems like rke does not support saving snapshots to s3 that are using http. 

Is it possible to add an argument to `rke etcd snapshot-save` like `--s3-use-https=0` and perhaps also `--s3-verify-ssl=0`?

**Comment by maxisam** [comment]
Well, mine is weird. I used Valid SSL certificate and get the CA with 
```sh
openssl s_client -connect minio.xxx.com:443 2>/dev/null </dev/null |  sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
```
 And I got error like

Unable to validate S3 backup target configration: The request signature we calculated does not match the signature you provided. Check your key and signing method

How is this possible?

**Comment by abonillabeeche** [comment]
Any update on the possibility to support this?

**Comment by alerosso** [comment]
Hi, the problem still persist with v1.2.5 and doesn't allow a backup in a safe network with minio exposed in http.

There's any workaround at this time to avoid this nasty error where etcd-rolling-snapshots print "http: server gave HTTP response to HTTPS client" ?

**Comment by gknepper** [comment]
@superseb Hello, 

The issue still persist even in v1.2.6. Is rancher thinking in manage this issue ? 

**--s3-endpoint http://192.168.1.222:9000 \**

INFO[0010] Removing container [etcd-snapshot-once] on host [192.168.1.201], try #1 
FATA[0010] [etcd] Failed to take one-time snapshot on host [192.168.1.201], exit code [1]: time="2021-03-25T01:36:25Z" level=fatal msg="failed to set s3 server: failed to set s3 server: address http://192.168.1.222:9000: too many colons in address" 

**--s3-endpoint 192.168.1.222:9000**

INFO[0011] Removing container [etcd-snapshot-once] on host [192.168.1.201], try #1 
FATA[0011] [etcd] Failed to take one-time snapshot on host [192.168.1.201], exit code [1]: time="2021-03-25T01:24:21Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:s3-rke-backup-bucket, err:Get \"https://192.168.1.222:9000/s3-rke-backup-bucket/?location=\": remote error: tls: internal error"

Thank you.

**Comment by Nox-404** [comment]
Hi, I have the same problem, I have an unsecure s3 service in a secured networks. It would be great to be able to backup on http only s3 service!
Please reopen 🙏

**Comment by lomori** [comment]
Same problem. Is it something hard?

**Comment by gknepper** [comment]
> Same problem. Is it something hard?

Unfortunately rancher does not support etcd backups on a S3 server with plain HTTP. 

It's a matter of rancher's dev team to implement the etcd snapshot-save to S3 without SSL which I think will never gonna happen since this issue was opened in May 23, 2019 and closed by stale-bot in Oct 9, 2021.  :-(

**Comment by seab4ng** [comment]
is it solved already?
