### ISSUE TITLE
Backport Consider putting local etcd as a first item of `etcd-servers` argument for k8s api 

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#1368]
Backport https://github.com/rancher/rke/issues/1352

Can be tested with v0.2.3-rc4

**Comment by galal-hussein** [comment]
Rancher server: v0.2.3-rc4

Steps to validate:

- Start a DO cluster with 3 nodes all roles
- Download keys for each node
- SSH to each and write the following command:
```
docker inspect kube-apiserver | grep etcd-servers
```
Results:

each node has the local etcd server as the first item in the servers list

**Comment by galal-hussein** [comment]
Rancher server v2.2.4-rc15

Steps to validate:

Ran the test plan for the docker stop issue https://github.com/rancherlabs/the-ranch/issues/271

All tests passed correctly.
