### ISSUE TITLE
Errors occurred in the installation process. I couldn't find a solution without detailed instructions.

### ISSUE THREAD

**Issue by qingfengfenga** [rancher/rke#1375]
Errors occurred in the installation process. I couldn't find a solution without detailed instructions.
`INFO[0264] [controlplane] Successfully started [rke-log-linker] container on host [192.168.0.59] 
INFO[0268] [remove/rke-log-linker] Successfully removed container on host [192.168.0.59] 
INFO[0268] [controlplane] Successfully started Controller Plane.. 
INFO[0268] [authz] Creating rke-job-deployer ServiceAccount 
INFO[0269] [authz] rke-job-deployer ServiceAccount created successfully 
INFO[0269] [authz] Creating system:node ClusterRoleBinding 
INFO[0270] [authz] system:node ClusterRoleBinding created successfully 
INFO[0271] Successfully Deployed state file at [./rancher-cluster.rkestate] 
INFO[0271] [state] Saving full cluster state to Kubernetes 
INFO[0272] [state] Successfully Saved full cluster state to Kubernetes ConfigMap: cluster-state 
INFO[0272] [worker] Building up Worker Plane..          
INFO[0272] [sidekick] Sidekick container already created on host [192.168.0.37] 
INFO[0272] [healthcheck] Start Healthcheck on service [kubelet] on host [192.168.0.37] 
INFO[0272] [sidekick] Sidekick container already created on host [192.168.0.87] 
INFO[0272] [healthcheck] Start Healthcheck on service [kubelet] on host [192.168.0.87] 
INFO[0272] [healthcheck] service [kubelet] on host [192.168.0.37] is healthy 
INFO[0272] [healthcheck] service [kubelet] on host [192.168.0.87] is healthy 
INFO[0273] [worker] Successfully started [rke-log-linker] container on host [192.168.0.87] 
INFO[0273] [worker] Successfully started [rke-log-linker] container on host [192.168.0.37] 
INFO[0274] [remove/rke-log-linker] Successfully removed container on host [192.168.0.87] 
INFO[0274] [healthcheck] Start Healthcheck on service [kube-proxy] on host [192.168.0.87] 
INFO[0274] [healthcheck] service [kube-proxy] on host [192.168.0.87] is healthy 
INFO[0274] [remove/rke-log-linker] Successfully removed container on host [192.168.0.37] 
INFO[0274] [healthcheck] Start Healthcheck on service [kube-proxy] on host [192.168.0.37] 
INFO[0274] [healthcheck] service [kube-proxy] on host [192.168.0.37] is healthy 
INFO[0275] [worker] Successfully started [rke-log-linker] container on host [192.168.0.87] 
INFO[0275] [worker] Successfully started [rke-log-linker] container on host [192.168.0.37] 
INFO[0275] [remove/rke-log-linker] Successfully removed container on host [192.168.0.87] 
INFO[0275] [remove/rke-log-linker] Successfully removed container on host [192.168.0.37] 
INFO[0277] [sidekick] Sidekick container already created on host [192.168.0.59] 
INFO[0277] [healthcheck] Start Healthcheck on service [kubelet] on host [192.168.0.59] 
INFO[0277] [healthcheck] service [kubelet] on host [192.168.0.59] is healthy 
INFO[0292] [worker] Successfully started [rke-log-linker] container on host [192.168.0.59] 
INFO[0295] [remove/rke-log-linker] Successfully removed container on host [192.168.0.59] 
INFO[0295] [healthcheck] Start Healthcheck on service [kube-proxy] on host [192.168.0.59] 
INFO[0295] [healthcheck] service [kube-proxy] on host [192.168.0.59] is healthy 
INFO[0308] [worker] Successfully started [rke-log-linker] container on host [192.168.0.59] 
INFO[0312] [remove/rke-log-linker] Successfully removed container on host [192.168.0.59] 
INFO[0312] [worker] Successfully started Worker Plane.. 
INFO[0313] [cleanup] Successfully started [rke-log-cleaner] container on host [192.168.0.87] 
INFO[0314] [remove/rke-log-cleaner] Successfully removed container on host [192.168.0.87] 
INFO[0314] [cleanup] Successfully started [rke-log-cleaner] container on host [192.168.0.37] 
INFO[0315] [remove/rke-log-cleaner] Successfully removed container on host [192.168.0.37] 
INFO[0322] [cleanup] Successfully started [rke-log-cleaner] container on host [192.168.0.59] 
INFO[0327] [remove/rke-log-cleaner] Successfully removed container on host [192.168.0.59] 
INFO[0327] [sync] Syncing nodes Labels and Taints   
    
FATA[0339] [ "192.168.0.59" not found] `

Here is my rancher-cluster.yml file
`nodes:
  - address: 192.168.0.37 # hostname or IP to access nodes
    internal_address: 192.168.0.37
    user: rancher # rancher user (usually 'rancher')
    role: [controlplane,etcd,worker] # K8s roles for node
    ssh_key_path: /home/rancher/.ssh/id_rsa # path to PEM file
  - address: 192.168.0.87
    internal_address: 192.168.0.87
    user: rancher
    role: [controlplane,etcd,worker]
    ssh_key_path: /home/rancher/.ssh/id_rsa
  - address: 192.168.0.59
    internal_address: 192.168.0.59
    user: rancher
    role: [controlplane,etcd,worker]
    ssh_key_path: /home/rancher/.ssh/id_rsa

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
`
Thank you very much for your help.

**Comment by superseb** [comment]
`192.168.0.59` tries to register itself to Kubernetes using the kubelet and contacting kube-apiserver on the same host (`127.0.0.1:6443`). Logging from kubelet and kube-apiserver will help here to narrow down what could cause the issue. We also have some common troubleshooting steps documented at https://rancher.com/docs/rancher/v2.x/en/troubleshooting/
