### ISSUE TITLE
jobs still pending

### ISSUE THREAD

**Issue by saphoooo** [rancher/rke#138]
**RKE version:**

rke version v0.0.8-dev

**Docker version: (`docker version`,`docker info` preferred)**

Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 68
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: k8s-master1
ID: XJUS:U7Y6:RAH3:2EO4:TPJU:VJQ2:W22T:W2OH:FED5:NLWL:7IJH:MFMR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 68
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: k8s-master1
ID: XJUS:U7Y6:RAH3:2EO4:TPJU:VJQ2:W22T:W2OH:FED5:NLWL:7IJH:MFMR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

4.4.0-62-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

KVM

**cluster.yml file:**

nodes:
- address: "192.168.1.201"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
- address: "192.168.1.202"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
- address: "192.168.1.203"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
- address: "192.168.1.211"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
- address: "192.168.1.212"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
- address: "192.168.1.213"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    extra_args: {}
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
    service_cluster_ip_range: 10.233.0.0/18
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
    cluster_domain: cluster.local
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    cluster_dns_server: 10.233.0.3
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2
    extra_args: {}
network:
  plugin: flannel
  options: {}
auth:
  strategy: x509
  options: {}
addons: ""
ssh_key_path:

**Steps to Reproduce:**

**Results:**

$ kubectl get jobs -n kube-system
NAME                            DESIRED   SUCCESSFUL   AGE
rke-kubedns-addon-deploy-job    1         0            44m
rke-network-plugin-deploy-job   1         0            48m

**Comment by de13** [comment]
**kubectl describe nodes**

**kubectl describe pods -n kube-system**

Name:           rke-kubedns-addon-deploy-job-4qgtq
Namespace:      kube-system
Node:           192.168.1.201/
Labels:         controller-uid=774a9662-df93-11e7-9950-52540092739a
                job-name=rke-kubedns-addon-deploy-job
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"Job","namespace":"kube-system","name":"rke-kubedns-addon-deploy-job","uid":"774a9662-df93-11e7-9950-525400...
Status:         Pending
IP:
Created By:     Job/rke-kubedns-addon-deploy-job
Controlled By:  Job/rke-kubedns-addon-deploy-job
Containers:
  rke-kubedns-addon-pod:
    Image:  rancher/k8s:v1.8.3-rancher2
    Port:   <none>
    Command:
      kubectl
      apply
      -f
      /etc/config/rke-kubedns-addon.yaml
    Environment:  <none>
    Mounts:
      /etc/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hdnfc (ro)
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rke-kubedns-addon
    Optional:  false
  default-token-hdnfc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hdnfc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**docker logs kubelet**

Flag --require-kubeconfig has been deprecated, You no longer need to use --require-kubeconfig. This will be removed in a future version. Providing --kubeconfig enables API server mode, omitting --kubeconfig enables standalone mode unless --require-kubeconfig=true is also set. In the latter case, the legacy default kubeconfig path will be used until --require-kubeconfig is removed.
I1212 22:56:12.221443    2171 feature_gate.go:156] feature gates: map[]
I1212 22:56:12.221710    2171 controller.go:114] kubelet config controller: starting controller
I1212 22:56:12.221739    2171 controller.go:118] kubelet config controller: validating combination of defaults and flags
I1212 22:56:12.741973    2171 mount_linux.go:205] Detected OS with systemd
I1212 22:56:12.742022    2171 client.go:75] Connecting to docker on unix:///var/run/docker.sock
I1212 22:56:12.742044    2171 client.go:95] Start docker client with request timeout=2m0s
W1212 22:56:12.743865    2171 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
I1212 22:56:12.777228    2171 feature_gate.go:156] feature gates: map[]
W1212 22:56:12.777559    2171 server.go:276] --require-kubeconfig is deprecated. Set --kubeconfig without using --require-kubeconfig.
I1212 22:56:12.777606    2171 plugins.go:101] No cloud provider specified.
I1212 22:56:12.777639    2171 server.go:299] No cloud provider specified: "" from the config file: ""
I1212 22:56:12.799355    2171 manager.go:149] cAdvisor running in container: "/sys/fs/cgroup/cpu,cpuacct/docker/6f8a79f8243c232655c504a137d4bd51c8b071a1f291cd374cc14cae24d43822"
W1212 22:56:12.804789    2171 manager.go:157] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
W1212 22:56:12.804885    2171 manager.go:166] unable to connect to CRI-O api service: Get http://%2Fvar%2Frun%2Fcrio.sock/info: dial unix /var/run/crio.sock: connect: no such file or directory
I1212 22:56:12.811750    2171 fs.go:139] Filesystem UUIDs: map[]
I1212 22:56:12.811779    2171 fs.go:140] Filesystem partitions: map[shm:{mountpoint:/dev/shm major:0 minor:71 fsType:tmpfs blockSize:0} /dev/mapper/k8s--master1--vg-root:{mountpoint:/var/lib/docker/aufs major:252 minor:0 fsType:ext4 blockSize:0} tmpfs:{mountpoint:/dev major:0 minor:73 fsType:tmpfs blockSize:0}]
I1212 22:56:12.813707    2171 manager.go:216] Machine: {NumCores:1 CpuFrequency:2494332 MemoryCapacity:2097541120 HugePages:[{PageSize:2048 NumPages:0}] MachineID: SystemUUID:BE15C9C3-7C96-4D67-95F5-32B2F8E170F4 BootID:e86116df-5964-44ea-a3ce-762c70bd65ad Filesystems:[{Device:tmpfs DeviceMajor:0 DeviceMinor:73 Capacity:1048768512 Type:vfs Inodes:256047 HasInodes:true} {Device:shm DeviceMajor:0 DeviceMinor:71 Capacity:67108864 Type:vfs Inodes:256047 HasInodes:true} {Device:/dev/mapper/k8s--master1--vg-root DeviceMajor:252 DeviceMinor:0 Capacity:13097459712 Type:vfs Inodes:820928 HasInodes:true} {Device:none DeviceMajor:0 DeviceMinor:70 Capacity:13097459712 Type:vfs Inodes:820928 HasInodes:true}] DiskMap:map[252:0:{Name:dm-0 Major:252 Minor:0 Size:13442744320 Scheduler:none} 252:1:{Name:dm-1 Major:252 Minor:1 Size:2147483648 Scheduler:none} 253:0:{Name:vda Major:253 Minor:0 Size:16106127360 Scheduler:none}] NetworkDevices:[{Name:ens3 MacAddress:52:54:00:92:73:9a Speed:-1 Mtu:1500}] Topology:[{Id:0 Memory:2097541120 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I1212 22:56:12.824356    2171 manager.go:222] Version: {KernelVersion:4.4.0-62-generic ContainerOsVersion:Ubuntu 16.04.1 LTS DockerVersion:1.12.6 DockerAPIVersion:1.24 CadvisorVersion: CadvisorRevision:}
I1212 22:56:12.825090    2171 server.go:422] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained: [Filename				Type		Size	Used	Priority /dev/dm-1                               partition	2097148	120	-1]

**docker logs kube-api**

W1213 05:43:07.196514       1 controller.go:386] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default /api/v1/namespaces/default/endpoints/kubernetes 75e27e91-df8d-11e7-9950-52540092739a 38846 0 2017-12-12 22:40:31 +0000 UTC <nil> <nil> map[] map[] [] nil [] } [{[{192.168.1.201  <nil> <nil>}] [] [{https 6443 TCP}]}]}
W1213 05:43:17.255705       1 controller.go:386] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default /api/v1/namespaces/default/endpoints/kubernetes 75e27e91-df8d-11e7-9950-52540092739a 38859 0 2017-12-12 22:40:31 +0000 UTC <nil> <nil> map[] map[] [] nil [] } [{[{192.168.1.201  <nil> <nil>}] [] [{https 6443 TCP}]}]}
W1213 05:43:27.331310       1 controller.go:386] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default /api/v1/namespaces/default/endpoints/kubernetes 75e27e91-df8d-11e7-9950-52540092739a 38877 0 2017-12-12 22:40:31 +0000 UTC <nil> <nil> map[] map[] [] nil [] } [{[{192.168.1.201  <nil> <nil>}] [] [{https 6443 TCP}]}]}

**Comment by galal-hussein** [comment]
Kubelet is failing to start because of the swap, you need to either disable swap on the machines or start kubelet with extra_args:
```
kubelet:
      image: rancher/k8s:v1.8.3-rancher2
      extra_args: {"fail-swap-on":"false"}
```

**Comment by de13** [comment]
Indeed, that's it. You can close the issue. Thanks!
