### ISSUE TITLE
SSH error, tried all suggested steps tunnel fails

### ISSUE THREAD

**Issue by jjhatobjective** [rancher/rke#1380]
**RKE version:**
v0.2.0 (Also tried with 0.2.2)

**Docker version: (`docker version`,`docker info` preferred)**

**(from controlplane/etcd node)**

Client:
 Version:      17.03.3-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   e19b718
 Built:        Thu Aug 30 01:04:51 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.3-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   e19b718
 Built:        Thu Aug 30 01:04:51 2018
 OS/Arch:      linux/amd64
 Experimental: false

 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6c463891b1ad274d505ae3bb738e530d1df2b3c7
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1030-azure
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.361 GiB
Name: dev-kubedeploy-1
ID: Y7QE:VOWF:6Q6M:GXW4:TSAP:PHTK:3ZCE:5OUK:26BE:A5ID:MKCP:XM2R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.15.0-1030-azure

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Azure

**cluster.yml file:**

nodes:
  - address: 10.188.0.150 # hostname or IP to access nodes
    user: rkeuser # root user (usually 'root')
    role: [controlplane,etcd] # K8s roles for node
    ssh_key_path: /home/rkeuser/.ssh/ssh-kube-key
    hostname_override: dev-kubecore-1
  - address: 10.188.0.153
    user: rkeuser
    role: [worker]
    ssh_key_path: /home/rkeuser/.ssh/ssh-kube-key
    hostname_override: dev-kubenode-1
  - address: 10.188.0.154
    user: rkeuser
    role: [worker]
    ssh_key_path: /home/rkeuser/.ssh/ssh-kube-key
    hostname_override: dev-kubenode-2
  - address: 10.188.0.155
    user: rkeuser
    role: [worker]
    ssh_key_path: /home/rkeuser/.ssh/ssh-kube-key
    hostname_override: dev-kubenode-3

ssh_agent_auth: true

**Steps to Reproduce:**

rke --debug etcd snapshot-save  --config config.yml --name tstbackup

**Results:**

INFO[0000] Starting saving snapshot on etcd hosts
DEBU[0000] Host: 10.188.0.150 has role: controlplane
DEBU[0000] Host: 10.188.0.150 has role: etcd
DEBU[0000] Host: 10.188.0.153 has role: worker
DEBU[0000] Host: 10.188.0.154 has role: worker
DEBU[0000] Host: 10.188.0.155 has role: worker
INFO[0000] [dialer] Setup tunnel for host [10.188.0.155]
DEBU[0000] Connecting to Docker API for host [10.188.0.155]
WARN[0000] Failed to set up SSH tunneling for host [10.188.0.155]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [10.188.0.155:22] using SSH. Please check if the configured key or specified key file is a valid SSH Private Key. Error: Error configuring SSH: ssh: no key found
INFO[0000] [dialer] Setup tunnel for host [10.188.0.150]
DEBU[0000] Connecting to Docker API for host [10.188.0.150]
WARN[0000] Failed to set up SSH tunneling for host [10.188.0.150]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [10.188.0.150:22] using SSH. Please check if the configured key or specified key file is a valid SSH Private Key. Error: Error configuring SSH: ssh: no key found
INFO[0000] [dialer] Setup tunnel for host [10.188.0.153]
DEBU[0000] Connecting to Docker API for host [10.188.0.153]
WARN[0000] Failed to set up SSH tunneling for host [10.188.0.153]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [10.188.0.153:22] using SSH. Please check if the configured key or specified key file is a valid SSH Private Key. Error: Error configuring SSH: ssh: no key found

FATA[0000] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) []

**Steps taken so far** 

following https://rancher.com/docs/rke/latest/en/troubleshooting/ssh-connectivity-errors/#failed-to-dial-ssh-using-address-xxx-xxx-xxx-xxx-xx-error-configuring-ssh-ssh-no-key-found  

* I can manually ssh with the user and key to the hosts and run a docker ps successfully.

* running  OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016 . on all hosts. 

* ssh-keygen -y -e -f [file]  shows a valid key.

**Comment by jjhatobjective** [comment]
Also this config does work on RKE v0.1.9, the cluster was originally built on this version.

**Comment by superseb** [comment]
Can you share the output of:

`head -1 /home/rkeuser/.ssh/ssh-kube-key`
`env | grep -i ssh`

Also, if you use RKE 0.1.9 binary with the exact same config and on the same exact machine, it does work?

**Comment by jjhatobjective** [comment]
@superseb  I have resolved this by removing the line 

`ssh_agent_auth: true`

from my v0.1.9 config.yml, the deployment is now working.
