### ISSUE TITLE
failed to add openstack cloud provider when use rke

### ISSUE THREAD

**Issue by zhangj3** [rancher/rke#1381]
**RKE version:**
rke version
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
**Docker version: (`docker version`,`docker info` preferred)**
ubuntu@node-1:~$ docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
ubuntu@node-1:~$ docker info
Containers: 38
 Running: 25
 Paused: 0
 Stopped: 13
Images: 17
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-38-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.789GiB
Name: node-1
ID: UQUA:GMPT:UMKK:FLMY:DCGI:UVGO:2TTO:635M:XM5Z:X7IE:A5PW:HVGD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://xxxxx:xxxxx@xxx.xxx.xxx.xxx:8080
HTTPS Proxy: http://xxxxx:xxxxx@xxx.xxx.xxx.xxx:8080
No Proxy: localhost,127.0.0.1,10.43.0.0/16,10.246.16.0/24,10.246.17.0/24,192.168.0.0/24
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu@node-1:~ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
ubuntu@node-1:~$ uname -r
4.15.0-38-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Redhat OpenStack
**cluster.yml file:**
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 10.246.16.231
  port: "22"
  internal_address: 192.168.0.49
  role:
  - controlplane
  - etcd
  - worker
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
- address: 10.246.17.40
  port: "22"
  internal_address: 192.168.0.66
  role:
  - controlplane
  - etcd
  - worker
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
- address: 10.246.17.49
  port: "22"
  internal_address: 192.168.0.39
  role:
  - controlplane
  - etcd
  - worker
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: null
    retention: ""
    creation: ""
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: rancher/coreos-etcd:v3.2.24
  alpine: rancher/rke-tools:v0.1.16
  nginx_proxy: rancher/rke-tools:v0.1.16
  cert_downloader: rancher/rke-tools:v0.1.16
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.16
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.15.0
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.15.0
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.15.0
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  kubernetes: rancher/hyperkube:v1.13.5-rancher1
  flannel: rancher/coreos-flannel:v0.10.0
  flannel_cni: rancher/coreos-flannel-cni:v0.3.0
  calico_node: rancher/calico-node:v3.4.0
  calico_cni: rancher/calico-cni:v3.4.0
  calico_controllers: ""
  calico_ctl: rancher/calico-ctl:v2.0.0
  canal_node: rancher/calico-node:v3.4.0
  canal_cni: rancher/calico-cni:v3.4.0
  canal_flannel: rancher/coreos-flannel:v0.10.0
  wave_node: weaveworks/weave-kube:2.5.0
  weave_cni: weaveworks/weave-npc:2.5.0
  pod_infra_container: rancher/pause-amd64:3.1
  ingress: rancher/nginx-ingress-controller:0.21.0-rancher1
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.4
  metrics_server: rancher/metrics-server-amd64:v0.3.1
ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
monitoring:
  provider: ""
  options: {}
cloud_provider:
    name: openstack
    openstackCloudProvider:
      global:
        username: xxxx
        password: xxxx
        auth_url: https://xxxx.xxxx.com:13000/v3
        tenant-id: fd76ba186da941d88aba63f2a4e590a3
        domain-id: default
**Steps to Reproduce:**
before I add the openstack cloud provider, after rke up, it's successful
after I add openstack cloud provider configuration options into cluster.yml file, and then rke up, it failed
**Results:**
ubuntu@jian: rke up
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [10.246.16.231]
INFO[0002] [dialer] Setup tunnel for host [10.246.17.40]
INFO[0005] [dialer] Setup tunnel for host [10.246.17.49]
INFO[0006] [state] Found local kube config file, trying to get state from cluster
INFO[0006] [state] Fetching cluster state from Kubernetes
INFO[0006] [state] Successfully Fetched cluster state to Kubernetes ConfigMap: cluster-state
INFO[0006] [certificates] Getting Cluster certificates from Kubernetes
INFO[0007] [certificates] Successfully fetched Cluster certificates from Kubernetes
INFO[0007] [network] No hosts added existing cluster, skipping port check
INFO[0007] [reconcile] Reconciling cluster state
INFO[0007] [reconcile] Check etcd hosts to be deleted
INFO[0007] [reconcile] Check etcd hosts to be added
INFO[0007] [reconcile] Rebuilding and updating local kube config
INFO[0007] Successfully Deployed local admin kubeconfig at [./kube_config_cluster.yml]
INFO[0007] [reconcile] host [10.246.16.231] is active master on the cluster
INFO[0007] [reconcile] Reconciled cluster state successfully
INFO[0007] [certificates] Deploying kubernetes certificates to Cluster nodes
INFO[0014] Successfully Deployed local admin kubeconfig at [./kube_config_cluster.yml]
INFO[0014] [certificates] Successfully deployed kubernetes certificates to Cluster nodes
INFO[0014] [cloud] Deploying cloud config file to node [10.246.16.231]
INFO[0015] [cloud] Successfully started [cloud-config-deployer] container on host [10.246.16.231]
INFO[0016] [remove/cloud-config-deployer] Successfully removed container on host [10.246.16.231]
INFO[0016] [cloud] Deploying cloud config file to node [10.246.17.40]
INFO[0016] [cloud] Successfully started [cloud-config-deployer] container on host [10.246.17.40]
INFO[0017] [remove/cloud-config-deployer] Successfully removed container on host [10.246.17.40]
INFO[0017] [cloud] Deploying cloud config file to node [10.246.17.49]
INFO[0017] [cloud] Successfully started [cloud-config-deployer] container on host [10.246.17.49]
INFO[0018] [remove/cloud-config-deployer] Successfully removed container on host [10.246.17.49]
INFO[0018] [cloud] Successfully deployed kubernetes cloud config to Cluster nodes
INFO[0018] Pre-pulling kubernetes images
INFO[0018] Kubernetes images pulled successfully
INFO[0018] [etcd] Building up etcd plane..
INFO[0018] [etcd] Saving snapshot [etcd-rolling-snapshots] on host [10.246.16.231]
INFO[0024] [certificates] Successfully started [rke-bundle-cert] container on host [10.246.16.231]
INFO[0024] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [10.246.1
INFO[0025] [etcd] Successfully started [rke-log-linker] container on host [10.246.16.231]
INFO[0025] [remove/rke-log-linker] Successfully removed container on host [10.246.16.231]
INFO[0025] [etcd] Saving snapshot [etcd-rolling-snapshots] on host [10.246.17.40]
INFO[0031] [certificates] Successfully started [rke-bundle-cert] container on host [10.246.17.40]
INFO[0031] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [10.246.1
INFO[0032] [etcd] Successfully started [rke-log-linker] container on host [10.246.17.40]
INFO[0032] [remove/rke-log-linker] Successfully removed container on host [10.246.17.40]
INFO[0032] [etcd] Saving snapshot [etcd-rolling-snapshots] on host [10.246.17.49]
INFO[0038] [certificates] Successfully started [rke-bundle-cert] container on host [10.246.17.49]
INFO[0038] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [10.246.1
INFO[0039] [etcd] Successfully started [rke-log-linker] container on host [10.246.17.49]
INFO[0039] [remove/rke-log-linker] Successfully removed container on host [10.246.17.49]
INFO[0039] [etcd] Successfully started etcd plane..
INFO[0039] [controlplane] Building up Controller Plane..
INFO[0039] [remove/service-sidekick] Successfully removed container on host [10.246.17.49]
INFO[0039] [remove/service-sidekick] Successfully removed container on host [10.246.16.231]
INFO[0039] [remove/service-sidekick] Successfully removed container on host [10.246.17.40]
INFO[0041] [controlplane] Successfully updated [kube-apiserver] container on host [10.246.17.49]
INFO[0041] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [10.246.17.49]
INFO[0041] [controlplane] Successfully updated [kube-apiserver] container on host [10.246.17.40]
INFO[0041] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [10.246.17.40]
INFO[0041] [controlplane] Successfully updated [kube-apiserver] container on host [10.246.16.231]
INFO[0041] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [10.246.16.231]
INFO[0054] [healthcheck] service [kube-apiserver] on host [10.246.16.231] is healthy
INFO[0054] [healthcheck] service [kube-apiserver] on host [10.246.17.40] is healthy
INFO[0055] [controlplane] Successfully started [rke-log-linker] container on host [10.246.16.231]
INFO[0055] [remove/rke-log-linker] Successfully removed container on host [10.246.16.231]
INFO[0055] [controlplane] Successfully started [rke-log-linker] container on host [10.246.17.40]
INFO[0055] [remove/rke-log-linker] Successfully removed container on host [10.246.17.40]
INFO[0057] [healthcheck] service [kube-apiserver] on host [10.246.17.49] is healthy
INFO[0058] [controlplane] Successfully started [rke-log-linker] container on host [10.246.17.49]
INFO[0058] [remove/rke-log-linker] Successfully removed container on host [10.246.17.49]
INFO[0061] [controlplane] Successfully updated [kube-controller-manager] container on host [10.246.16.231]
INFO[0061] [healthcheck] Start Healthcheck on service [kube-controller-manager] on host [10.246.16.231]
INFO[0061] [controlplane] Successfully updated [kube-controller-manager] container on host [10.246.17.40]
INFO[0061] [healthcheck] Start Healthcheck on service [kube-controller-manager] on host [10.246.17.40]
INFO[0064] [controlplane] Successfully updated [kube-controller-manager] container on host [10.246.17.49]
INFO[0064] [healthcheck] Start Healthcheck on service [kube-controller-manager] on host [10.246.17.49]
INFO[0067] [healthcheck] service [kube-controller-manager] on host [10.246.16.231] is healthy
INFO[0068] [healthcheck] service [kube-controller-manager] on host [10.246.17.40] is healthy
INFO[0068] [controlplane] Successfully started [rke-log-linker] container on host [10.246.16.231]
INFO[0068] [controlplane] Successfully started [rke-log-linker] container on host [10.246.17.40]
INFO[0068] [remove/rke-log-linker] Successfully removed container on host [10.246.16.231]
INFO[0068] [healthcheck] Start Healthcheck on service [kube-scheduler] on host [10.246.16.231]
INFO[0069] [remove/rke-log-linker] Successfully removed container on host [10.246.17.40]
INFO[0069] [healthcheck] Start Healthcheck on service [kube-scheduler] on host [10.246.17.40]
INFO[0069] [healthcheck] service [kube-scheduler] on host [10.246.16.231] is healthy
INFO[0069] [healthcheck] service [kube-scheduler] on host [10.246.17.40] is healthy
INFO[0070] [controlplane] Successfully started [rke-log-linker] container on host [10.246.16.231]
INFO[0070] [controlplane] Successfully started [rke-log-linker] container on host [10.246.17.40]
INFO[0070] [remove/rke-log-linker] Successfully removed container on host [10.246.16.231]
INFO[0070] [healthcheck] service [kube-controller-manager] on host [10.246.17.49] is healthy
INFO[0071] [remove/rke-log-linker] Successfully removed container on host [10.246.17.40]
INFO[0071] [controlplane] Successfully started [rke-log-linker] container on host [10.246.17.49]
INFO[0071] [remove/rke-log-linker] Successfully removed container on host [10.246.17.49]
INFO[0071] [healthcheck] Start Healthcheck on service [kube-scheduler] on host [10.246.17.49]
INFO[0072] [healthcheck] service [kube-scheduler] on host [10.246.17.49] is healthy
INFO[0073] [controlplane] Successfully started [rke-log-linker] container on host [10.246.17.49]
INFO[0073] [remove/rke-log-linker] Successfully removed container on host [10.246.17.49]
INFO[0073] [controlplane] Successfully started Controller Plane..
INFO[0073] [authz] Creating rke-job-deployer ServiceAccount
INFO[0073] [authz] rke-job-deployer ServiceAccount created successfully
INFO[0073] [authz] Creating system:node ClusterRoleBinding
INFO[0073] [authz] system:node ClusterRoleBinding created successfully
INFO[0073] [certificates] Save kubernetes certificates as secrets
INFO[0076] [certificates] Successfully saved certificates as kubernetes secret [k8s-certs]
INFO[0076] [state] Saving cluster state to Kubernetes
INFO[0076] [state] Successfully Saved cluster state to Kubernetes ConfigMap: cluster-state
INFO[0076] [state] Saving cluster state to cluster nodes
INFO[0077] [state] Successfully started [cluster-state-deployer] container on host [10.246.16.231]
INFO[0077] [remove/cluster-state-deployer] Successfully removed container on host [10.246.16.231]
INFO[0078] [state] Successfully started [cluster-state-deployer] container on host [10.246.17.40]
INFO[0078] [remove/cluster-state-deployer] Successfully removed container on host [10.246.17.40]
INFO[0079] [state] Successfully started [cluster-state-deployer] container on host [10.246.17.49]
INFO[0079] [remove/cluster-state-deployer] Successfully removed container on host [10.246.17.49]
INFO[0079] [worker] Building up Worker Plane..
INFO[0079] [remove/service-sidekick] Successfully removed container on host [10.246.17.49]
INFO[0079] [remove/service-sidekick] Successfully removed container on host [10.246.17.40]
INFO[0079] [remove/service-sidekick] Successfully removed container on host [10.246.16.231]
INFO[0081] [worker] Successfully updated [kubelet] container on host [10.246.16.231]
INFO[0081] [worker] Successfully updated [kubelet] container on host [10.246.17.49]
INFO[0081] [healthcheck] Start Healthcheck on service [kubelet] on host [10.246.16.231]
INFO[0081] [worker] Successfully updated [kubelet] container on host [10.246.17.40]
INFO[0081] [healthcheck] Start Healthcheck on service [kubelet] on host [10.246.17.49]
INFO[0081] [healthcheck] Start Healthcheck on service [kubelet] on host [10.246.17.40]
FATA[0138] [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:1025on host [10.246.16.231]: Get https://localhost:10250/healthz: Unable to access the service on localhost:10250. The service migssh: rejected: connect failed (Connection refused), log: F0603 08:06:11.134579   32116 server.go:261] failed to run Kubelet: censtack": Get /: unsupported protocol scheme ""

**Comment by sebastien-prudhomme** [comment]
I think `auth_url` should be  `auth-url`. This is what i use in my cluster config.

**Comment by zhangj3** [comment]
> 
> 
> I think `auth_url` should be `auth-url`. This is what i use in my cluster config.

Hi  Thank you for your reply, after change `auth_url` to `auth-url`, I redeployment the cluster again, it shows another error
`INFO[0199] [healthcheck] Start Healthcheck on service [kubelet] on host [10.246.17.51]
FATA[0256] [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: 
Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.246.16.231]: 
Get https://localhost:10250/healthz: Unable to access the service on localhost:10250. 
The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), 
log: F0610 11:23:50.470828 11076 server.go:261] failed to run Kubelet: could not init cloud provider "openstack":
Post https://cloud-zelos.xxxx.net:13000/v3/auth/tokens: x509: certificate signed by unknown authority`

seems the rke or kubernetes doesn't support the openstack self-sign certificate

**Comment by sebastien-prudhomme** [comment]
You need to add your CA cert in your system cert store. RKE (Golang) will read it.

**Comment by patriziobassi** [comment]
i have a similar problem when using opestack as provider: VMs get created, docker installed, docker with rke tools launched but than complains about x509 and self signed certificate. How to inject custom CA?

**Comment by jrevillard** [comment]
Same issue here, please help...

**Comment by DavidSpek** [comment]
I was having some trouble with Rancher deploying to openstack. What worked for me was `juju ssh vault/0` and then `cat /etc/ssl/certs/ca-certificates.crt`. Specific to Rancher I copied the output of the `cat` command and placed it in the `cacert` field in the node template configuration. This solved the problem for me.
