### ISSUE TITLE
Unable to deploy cluster with weave plugin

### ISSUE THREAD

**Issue by ronny35** [rancher/rke#1383]
**RKE version:**
0.2.2

**Docker version: (`docker version`,`docker info` preferred)**
17.03.3-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-116-generic

**cluster.yml file:**
nodes:
- address: 192.168.61.61
  port: "22"
  internal_address: 192.168.61.61
  hostname_override: ""
  user: user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/ssh_cluster_test_key
  labels: {}
  role:
  - etcd
  - worker
  - controlplane
private_registries:
- url: registry.fr
  user: rancher
  password: blbalba
  is_default: true
# ----- PROVIDER PART -----
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: false
    retention: ""
    creation: ""
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: weave
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: "test"
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
monitoring:
  provider: ""
  options: {}

**Steps to Reproduce:**

**Results:**

W0603 17:39:53.508193    4296 docker_sandbox.go:384] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "metrics-server-675f7f6678-dgl2x_kube-system": CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "658566cadb02861c54a6961ee7453d38303826e4768f5d5b198e10cd01d1c32f"
W0603 17:39:53.534756    4296 cni.go:302] CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "5e25d5254927ee5187723c9b98f99c5e9b5b82e654b268fb5ccf194484945993"
W0603 17:39:53.552107    4296 docker_sandbox.go:384] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "kube-dns-autoscaler-5cc789c9-8bb6b_kube-system": CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "8444d9ef31fc3625d911d5ceac472a782ee3cc71315b5f457538dbe3221a6432"
weave-cni: unable to release IP address: 400 Bad Request: Delete: no addresses for 5e25d5254927ee5187723c9b98f99c5e9b5b82e654b268fb5ccf194484945993

**Comment by moelsayed** [comment]
@ronny35 I am unable to reproduce this issue. Can you please provide:
- Your rke run log.
- output of `kubectl get pods --all-namespaces`
