### ISSUE TITLE
How to migrate custom k8s cluster from one Rancher setup to another

### ISSUE THREAD

**Issue by MittalNitish** [rancher/rke#1403]
**RKE version:** rancher/hyperkube:v1.13.5-rancher1, rancher/rke-tools:v0.1.27

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal on Azure (VMs are imported to Rancher 2.2 after creating them and installing Docker on them)

Hi Team,

We have setup Ubuntu VMs in Azure and installed docker on them. We added these VMs to Rancher using custom cluster template. k8s setup was done by Rancher using RKE I suppose. Cluster is working fine and we can manage it using Rancher GUI.
There is a requirement to move the cluster to a different Rancher setup as the Rancher setup we are using now will be decommissioned. I don't see any documentation on this. Is there any manual or automated way of doing this? We do not want to recreate the VMs and add them to the new Rancher setup again.

**Comment by alena1108** [comment]
Rancher currently doesn't support this functionality.

**Comment by MittalNitish** [comment]
@alena1108 , will import existing cluster template also not work?

**Comment by superseb** [comment]
This is a Rancher feature and tracked in https://github.com/rancher/rancher/issues/16471
