### ISSUE TITLE
running rke from within the cluster

### ISSUE THREAD

**Issue by musabmirza** [rancher/rke#1415]
General question: 

Is it possible to run `rke up --config myconfig.yaml` from one of the nodes in the potential cluster? If thats possible, how to configure the `myconfig.yaml` file for localhost connection?

**Comment by superseb** [comment]
As long as the required files are present (https://rancher.com/docs/rke/latest/en/installation/#save-your-files) and the `cluster.yml` contains information how to reach the nodes, but the model of RKE doesn't change, you run `rke up` from a node with access to the nodes and provision it according to `cluster.yml` (and update if it is an existing cluster, using the required files)
