### ISSUE TITLE
rke cert rotate failed

### ISSUE THREAD

**Issue by taozix** [rancher/rke#1435]
**RKE version:**
v0.1.8-rc2 & v0.2.0

**Steps to Reproduce:**
1. rke-v0.1.8-rc2 init the cluster a year ago
2.certificate has expired now
3. using rke-v0.2.0 rotat cert

**Results:**
1../rke_linux-amd64.v0.2.0 up
...
INFO[0033] [etcd] Successfully started etcd plane.. Checking etcd cluster health 
FATA[0170] [etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy

2../rke_linux-amd64.v0.2.0 cert rotate
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] Rotating Kubernetes cluster certificates     
FATA[0000] Failed to rotate certificates: can't find old certificates

**Comment by azbpa** [comment]
Facing the same issue with Rancher Server v2.2.2:

```
This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready.
Failed to rotate certificates: can't find old certificates
```

Tried to rotate exired certificates like described here:
https://rancher.com/docs/rancher/v2.x/en/cluster-admin/certificate-rotation/

**Comment by Kanshiroron** [comment]
I don't know if this will be the same for you, but the issue I had was that my rke config file wasn't named `cluster.yml` but `onpremise.yml`, and my `rkestate` file was named `rancher-cluster.rkestate` instead of `onpremise.rkestate`.
I guess they have changed their naming convention since I never have created/modified/touched the `rkestate` file.
Hope this will help

**Comment by ccleouf66** [comment]
Hello,

Same issue as @azbpa after upgrading rancher server frome 2.2.2 to 2.2.5 I tried to upgrade a k8s cluster from 1.13.5 to 1.14.3 but the etcd health checking failed. I tried to rotate certs but I have this error:
```	
This cluster is currently Updating.

Failed to rotate certificates: can't find old certificates
```

**Comment by hyouhaku** [comment]
anyone found any workaround?
