### ISSUE TITLE
Unable to Install aws-ebs-csi-driver to dynamically mount AWS EBS volumes.

### ISSUE THREAD

**Issue by leonj1** [rancher/rke#1469]
**RKE version:**
rke version v0.2.4

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 62
 Running: 36
 Paused: 0
 Stopped: 26
Images: 82
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:
WARNING: No swap limit support
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-151-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42GiB
Name: ip-10-161-160-82
ID: CJCP:OOJG:244N:LMQN:MII3:LABY:UWQH:5ZAZ:KU37:DU2H:QEGE:QSTO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-151-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
---
cloud_provider:
  name: aws

nodes:
  - address: 10.161.160.8
    user: ubuntu
    role:
    - controlplane
    - etcd
  - address: 10.161.160.43
    user: ubuntu
    role:
    - controlplane
    - etcd
  - address: 10.161.160.60
    user: ubuntu
    role:
    - controlplane
    - etcd
  - address: 10.161.160.82
    user: ubuntu
    role:
    - worker
  - address: 10.161.160.34
    user: ubuntu
    role:
    - worker
  - address: 10.161.160.13
    user: ubuntu
    role:
    - worker
services:
  kubelet:
    extra_args:
       feature-gates: "CSINodeInfo=true,CSIDriverRegistry=true,CSIBlockVolume=true,MountPropagation=true"
  kube-api:
    extra_args:
      feature-gates: "CSINodeInfo=true,CSIDriverRegistry=true,CSIBlockVolume=true,VolumeSnapshotDataSource=true,MountPropagation=true"

**Steps to Reproduce:**
1. Create 6 ec2 instances (3 master, 3 nodes)
2. Apply this IAM policy to all 6 ec2 instances
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DenyPublicIngressCapabilities",
            "Effect": "Deny",
            "Action": [
                "ec2:AllocateAddress",
                "ec2:AssociateAddress",
                "ec2:AttachInternetGateway",
                "ec2:CreateEgressOnlyInternetGateway",
                "ec2:CreateInternetGateway",
                "ec2:CreateNatGateway",
                "ec2:CreateVpcPeeringConnection",
                "ec2:AcceptVpcPeeringConnection",
                "ec2:DeleteSecurityGroup",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:CreateSecurityGroup"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:CreateNetworkInterface",
                "ec2:AttachNetworkInterface",
                "ec2:DeleteNetworkInterface",
                "ec2:DetachNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DescribeInstances",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:AssignPrivateIpAddresses",
                "ec2:UnassignPrivateIpAddresses",
                "ec2:DescribeSubnets",
                "ec2:AttachVolume",
                "ec2:CreateSnapshot",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DeleteSnapshot",
                "ec2:DeleteTags",
                "ec2:DeleteVolume",
                "ec2:DescribeInstances",
                "ec2:DescribeSnapshots",
                "ec2:DescribeTags",
                "ec2:DescribeVolumes",
                "ec2:DetachVolume"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "ec2:CreateTags",
            "Resource": "arn:aws:ec2:*:*:network-interface/*"
        }
    ]
}
3. Once cluster is online, add AWS EBS volume support
Source: https://github.com/kubernetes-sigs/aws-ebs-csi-driver
a) kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/master/deploy/kubernetes/secret.yaml
b) kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-ebs-csi-driver/master/deploy/kubernetes/manifest.yaml
c) Verify running: kubectl get pods -n kube-system | grep ebs
In a cluster created by RKE 3c shows the PODs not running:

> ebs-csi-controller-0                      5/5     Running            0          2d7h
> ebs-csi-node-gdj8q                        2/3     CrashLoopBackOff   671        2d7h
> ebs-csi-node-h2wrj                        2/3     CrashLoopBackOff   671        2d7h
> ebs-csi-node-z5q65                        2/3     CrashLoopBackOff   671        2d7h

Yet, in a cluster started by kubeadm, the verification step shows all ebs nodes as Running.

**Results:**

>  kubectl logs ebs-csi-node-gdj8q -n kube-system -c node-driver-registrar
> I0714 22:36:08.672379       1 main.go:110] Version: v1.1.0-0-g80a94421
> I0714 22:36:08.672417       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
> I0714 22:36:08.672428       1 connection.go:151] Connecting to unix:///csi/csi.sock
> I0714 22:36:08.672985       1 main.go:127] Calling CSI driver to discover driver name
> I0714 22:36:08.673011       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
> I0714 22:36:08.673016       1 connection.go:181] GRPC request: {}
> I0714 22:36:08.674442       1 connection.go:183] GRPC response: {"name":"ebs.csi.aws.com","vendor_version":"0.4.0"}
> I0714 22:36:08.674965       1 connection.go:184] GRPC error: <nil>
> I0714 22:36:08.674971       1 main.go:137] CSI driver name: "ebs.csi.aws.com"
> I0714 22:36:08.675016       1 node_register.go:54] Starting Registration Server at: /registration/ebs.csi.aws.com-reg.sock
> I0714 22:36:08.675060       1 node_register.go:61] Registration Server started at: /registration/ebs.csi.aws.com-reg.sock
> I0714 22:36:08.995428       1 main.go:77] Received GetInfo call: &InfoRequest{}
> I0714 22:36:09.933610       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:plugin registration failed with err: error uninstalling CSI driver from CSINodeInfo object error updating CSINodeInfo: timed out waiting for the condition; caused by: [the server could not find the requested resource (get csinodeinfos.csi.storage.k8s.io ip-10-161-160-82.ec2.internal), the server could not find the requested resource (get csinodeinfos.csi.storage.k8s.io ip-10-161-160-82.ec2.internal), the server could not find the requested resource (get csinodeinfos.csi.storage.k8s.io ip-10-161-160-82.ec2.internal), the server could not find the requested resource (get csinodeinfos.csi.storage.k8s.io ip-10-161-160-82.ec2.internal)],}
> E0714 22:36:09.933670       1 main.go:89] Registration process failed with error: plugin registration failed with err: error uninstalling CSI driver from CSINodeInfo object error updating CSINodeInfo: timed out waiting for the condition; caused by: [the server could not find the requested resource (get csinodeinfos.csi.storage.k8s.io ip-10-161-160-82.ec2.internal), the server could not find the requested resource (get csinodeinfos.csi.storage.k8s.io ip-10-161-160-82.ec2.internal), the server could not find the requested resource (get csinodeinfos.csi.storage.k8s.io ip-10-161-160-82.ec2.internal), the server could not find the requested resource (get csinodeinfos.csi.storage.k8s.io ip-10-161-160-82.ec2.internal)], restarting registration container.
> 

Looking at the GitHub page for node-driver-registrar, I have verified the dependencies exist in the Docker container started by RKE. Not sure what else to check. https://github.com/kubernetes-csi/node-driver-registrar

**Comment by nagonzalez** [comment]
I think your `cluster.yml`  is slightly off.  You'll want to move the feature-flag stuff to the `services` block at the top level. Something like this:

```
# RKE node definitions
nodes:
  - address: 172.28.128.3
    role:
    - controlplane
    - etcd
    - worker
    user: vagrant

# RKE services
services:
  etcd:
    backup_config:
      enabled: true
      interval_hours: 24
      retention: 7
  kube-api:
    extra_args:
      feature-gates: CSINodeInfo=true,CSIDriverRegistry=true,CSIBlockVolume=true,VolumeSnapshotDataSource=true
  kubelet:
    extra_args:
      feature-gates: CSINodeInfo=true,CSIDriverRegistry=true,CSIBlockVolume=true
```

you can then validate that things are working with the following commands:
```
docker inspect kube-apiserver | grep feature
            "--feature-gates=CSINodeInfo=true,CSIDriverRegistry=true,CSIBlockVolume=true,VolumeSnapshotDataSource=true",
                "--feature-gates=CSINodeInfo=true,CSIDriverRegistry=true,CSIBlockVolume=true,VolumeSnapshotDataSource=true",
```

```
docker inspect kubelet | grep feature
            "--feature-gates=CSINodeInfo=true,CSIDriverRegistry=true,CSIBlockVolume=true"
                "--feature-gates=CSINodeInfo=true,CSIDriverRegistry=true,CSIBlockVolume=true"
```

**Comment by shaunc** [comment]
@leonj1 -- were you able to get this working? I'm about to try this out.

**Comment by nagonzalez** [comment]
@shaunc I got both the EBS & EFS CSI drivers working :)

**Comment by shaunc** [comment]
Great! ... is @nagonzalez on the right track? Hints welcome! :)

**Comment by nagonzalez** [comment]
At a high level, make sure you:
* enable the required feature flags in RKE
* make sure that your worker nodes have the appropriate IAM role & permissions
* if you're using kube2iam, ensure you set the proper annotations so the EBS csi driver pods have the right IAM role
