### ISSUE TITLE
rke log not seen

### ISSUE THREAD

**Issue by xuejipeng** [rancher/rke#1504]
**RKE version:**
rke version v0.2.4
**Docker version: (`docker version`,`docker info` preferred)**
18.09.7
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.15.0-55-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
I can't find kubernetes componentstatuses logs 
![image](https://user-images.githubusercontent.com/18901031/61873914-a3e13780-af19-11e9-9bde-245e917214f7.png)
![image](https://user-images.githubusercontent.com/18901031/61873940-afccf980-af19-11e9-9f2f-0f29925fe58b.png)

**Comment by xuejipeng** [comment]
Is there anyone?

**Comment by fpicot** [comment]
I've got the same issue on a cluster deployed with RKE. 
It seems that during cluster creation there is a call to rke-log-linker which creates the symlink but once the cluster is up rke-log-cleaner is removing every link. 

The whole logic was implemented in #412

It would be great to keep the links in place to be able to retrieve the logs afterwards.

**Comment by xuejipeng** [comment]
I think it's probably that I modified the docker's 'graph' to /data/docker  to cause this problem.

**Comment by galal-hussein** [comment]
I am not really able to reproduce the issue, I can see the logs normally in /var/lib/rancher/rke/logs
```
root@ip-172-31-47-141:/var/lib/rancher/rke/log# ls
etcd_03bda09494db07d67e751dd5d50bb4cbe5f9c266947fd348a16fae83184a7440.log
kube-apiserver_0824b79b8740e4f382b55b2db9edc43413792b09d47dd5a9573c56c3232c6d22.log
kube-controller-manager_a1f7b92b03192cd7faa3f81d8122ab0203b1e60b0076d34353ff6cd643ff6410.log
kubelet_dc9a1a1aad6184da78f2f079f2b44f22bb5a359517c35074ba8ee43630e6fb90.log
kube-proxy_a8077cab071aa802992c64d698191d81647503031490c870815ee732928d6c4f.log
kube-scheduler_5581753c474f3fcfa19a994993d925e1b6c49033a29afa0a2bd8bfc967e7aea1.log
```

**Comment by fpicot** [comment]
This is clearly an  issue related to docker data-root. 

I had also set ```"data-root": "/data/docker/"``` in /etc/docker/daemon.json, and couldn't get the logs. 
With data-root left to default value, but with a symlink from /var/lib/docker to /data/docker, it doesn't work either. 
However, with docker in default configuration, it works. 

I believe this is caused by https://github.com/rancher/rke/blob/bcb1d411144ae20bd97446f67940fa8cd234aeaf/hosts/hosts.go#L323 :
The image is run with a bind "/var/lib/:/var/lib/". If containers logs are not also inside /var/lib, the find command that is run inside rke-tools ("sh -c "find /var/lib/rancher/rke/ -type l ! -exec test -e {} \\; -print -delete") is seeing broken links and deleting them.

**Comment by alena1108** [comment]
Per @superseb the issue can be non-default root related.

**Comment by alena1108** [comment]
Can be tested with `v0.3.2-rc1`

**Comment by bmdepesa** [comment]
rke v0.3.2-rc1

* Changed docker data root to `/data/docker` on 3 nodes
* Created rke cluster from nodes
* Logs are present in `/var/lib/rancher/rke/log`
```
ubuntu@ip:/var/lib/rancher/rke/log$ docker info | grep "Docker Root Dir"
Docker Root Dir: /data/docker/

ubuntu@ip:/var/lib/rancher/rke/log$ ls
kube-apiserver_01fac31764d7d55434e1707097308d1fe51a9a2443b3ba77e27affdd0c15024f.log
kube-controller-manager_24153b5a4a458a5af7eba856db989611f9dab6780e1c5e1f0d1987f78fd32c7f.log
kubelet_0b135ed5aa2c6c1e2c41b9811b698d1894410db83651e35a84825587da97e038.log
kube-proxy_d15c06c20f478372d71432dc1c742527a2d6f9f3bf66f117a62ae6712fa2d775.log
kube-scheduler_e4ad9a4d9beff1423f0936d12666bf19ac3b4a68cb8f072115c3504166a6455a.log
```
