### ISSUE TITLE
snapshot-restore fails on new rancher-node because of missing kube-ca.pem

### ISSUE THREAD

**Issue by mfld** [rancher/rke#1507]
**RKE version:**
rke version v0.2.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

kernel
3.10.0-957.21.3.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
kvm/proxmox

**cluster.yml file:**
nodes:
  - address: 10.100.125.26
    user: rancher
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
  - address: 10.100.125.27
    user: rancher
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
  - address: 10.100.125.28
    user: rancher
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h # time increment between snapshots
    retention: 24h # time increment before snapshot purge

**Steps to Reproduce:**
Trying to restore RancherOS from a previous snapshot by following instructions
at https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/#4-restore-database.

1) install a new "restore-node" (10.100.125.35), which is not
associated with the cluster providing restore.db (snapshot-file).

2) copy restore.db over to /opt/rke/etcd-snapshots/ on the "restore-node"

3) copy cluster.yml to cluster-restore.yml, and change nodes-section to only
list the restore-node:

nodes:
  - address: 10.100.125.35
    user: rancher
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h # time increment between snapshots
    retention: 24h # time increment before snapshot purge

4) run snapshot-restore (using rke version v0.2.6, same version creating the running cluster)
at this point I also poweroff the origin-cluster just to be safe.

./rke etcd snapshot-restore --name restore.db --config cluster-restore.yml 

**Results:**
INFO[0000] Restoring etcd snapshot upgrade_from_2_2_5_to_2_2_6.db 
INFO[0000] Successfully Deployed state file at [./cluster-restore.rkestate] 
INFO[0000] [dialer] Setup tunnel for host [10.100.125.35] 
WARN[0006] failed to stop etcd container on host [10.100.125.35]: Can't stop Docker container [etcd] for host [10.100.125.35]: Error response from daemon: No such container: etcd 
INFO[0006] [etcd] starting backup server on host [10.100.125.35] 
INFO[0006] [etcd] Successfully started [etcd-Serve-backup] container on host [10.100.125.35] 
WARN[0011] failed to start backup server on host [10.100.125.35]: Failed to run backup server container, container logs: time="2019-07-26T06:32:38Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory" 
 
WARN[0011] failed to start etcd container on host [10.100.125.35]: Failed to start [etcd] container on host [10.100.125.35]: Error response from daemon: No such container: etcd 
FATA[0011] failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="2019-07-26T06:32:38Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory" 
] 

**Possible workaround**
Seems a successful restore requires the rkstate-file (the cluste-restore.rkstate remains empty).
I am able to restore the snapshot  by instead modifying/re-using cluster.yml directly (which will then use the original cluster.rkstate-file for ssl and kube-ca.pem -information).

clusters.yml file
nodes:
  - address: 10.100.125.35
    user: rancher
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h # time increment between snapshots
    retention: 24h # time increment before snapshot purge

./rke etcd snapshot-restore --name restore.db
...
INFO[0171] Finished building Kubernetes cluster successfully 
INFO[0171] Restarting network, ingress, and metrics pods 
INFO[0173] Finished restoring snapshot [restore.db] on all etcd hosts

The documentation does not mention a dependency on rkstate file being populated.
Feels like I am missing something :)

**Comment by joshu111** [comment]
facing same issue. @mfld 's workaround seems to be working

**Comment by andrii-litvinov** [comment]
Even more fun when trying to migrate single-node cluster to HA. I guess the solution is to use older RKE tools, like v0.1.20 and backup pki keys as well.

**Comment by aliabbasjaffri** [comment]
@andrii-litvinov were you able to make single-node-to-HA-cluster-migration work using the RKE tools v0.1.20? It fails on RKE v0.1.50 with the error, `/etc/kubernetes/ssl/kube-ca.pem: no such file or directory`. @superseb

**Comment by andrii-litvinov** [comment]
@aliabbasjaffri yes, I was. I had to manually create `pki.bundle.tar.gz` as described in this article https://rancher.com/blog/2019/2019-01-10-migrating-single-node-2-1-x-to-high-availability/. Then I was able to restore etcd and create k8s cluster with RKE v0.1.20 (sorry, I don't remember exactly what version of rke-tools it uses, maybe even 0.1.16). Afterwards I upgraded RKE to v0.3.2 and did `rke up` one more time. And then I followed the instructions in docs. I used own certificates, so I didn't have to install cert-manager and I didn't experience the issue with URL like in this video https://www.youtube.com/watch?v=F8G0HtI_Wbg&t=240.

**Comment by aliabbasjaffri** [comment]
Thanks for the super fast reply!
I am trying to upgrade as per the article and created the pki tarball. But when i am trying to setup single node HA to restore etcd, it is continuously giving me the same error on running the command, `./rke etcd snapshot-restore --name single-node-etcd-snapshot --config rancher-cluster.yaml`

```
WARN[0012] Can't start Docker container [etcd] on host [***]: Error response from daemon: No such container: etcd
WARN[0012] failed to start etcd container on host [***]: Error response from daemon: No such container: etcd
FATA[0012] failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="---" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory"
]
```
I am using RKE v0.3.2 which installs RKE tools v0.1.50; interesting that it worked with RKE v0.1.20..

**Comment by andrii-litvinov** [comment]
No problem, I know how frustrating it is and I am happy that I managed to finally complete the migration yesterday 🙂.

Yes, that's what I saw when tried with RKE v0.3.2. Just make sure that `pki.bundle.tar.gz` is there in `/opt/rke/etcd-snapshots` on the host, when restoring with RKE v0.1.20.

**Comment by aliabbasjaffri** [comment]
Thank you so much for your help!
Yes, it is there along with single-node-etcd-snapshot as suggested by the blog.
I think this is because the blog and the current rancher versions are way too out of sync and this is why this is creating an issue. Because even after manually extracting the pem files in the `/etc/kubernetes/ssl` folder, the restore proceeds but still runs into an issue described here, #1286
