### ISSUE TITLE
nodes ExternalIP are not set on bare metal

### ISSUE THREAD

**Issue by tlvenn** [rancher/rke#1508]
**RKE version: 0.2.6**
**Docker version:18.9.6**
**Operating system and kernel: Debian GNU/Linux 9**
**Type/provider of hosts: Bare-metal**

On a bare metal installation where each server has 2 networks (public & private) and when using canal with the following settings: `canal_iface: *priv_interface*`, the resulting nodes in the cluster dont have any ExternalIP set:

![image](https://user-images.githubusercontent.com/3340262/61934923-c08a7780-afcc-11e9-9edf-bedbe840d12e.png)

**Comment by tlvenn** [comment]
I should add that both the `address` and the `internal_address` are provided for each node.

**Comment by tlvenn** [comment]
@superseb can you comment on this issue, i remember seeing somewhere that RKE is not able to set the external ip of each node. Can you confirm that is the case and if so, quickly explain where the limitation is ?

Thanks a lot in advance.

**Comment by pasikarkkainen** [comment]
This issue might be related: https://github.com/rancher/rke/issues/900

**Comment by pasikarkkainen** [comment]
still a valid issue.

**Comment by cyvcloud** [comment]
I am currently faced with the same issue. Is there any kind of workaround to force set the external IP address on the nodes?

**Comment by XLordalX** [comment]
This is still an issue.
