### ISSUE TITLE
Feature request: Option to add additional admission controllers  

### ISSUE THREAD

**Issue by nmeisenzahl** [rancher/rke#1509]
**RKE version:** 0.2.6
**Docker version:** 18.09.8
**Operating system and kernel:** 4.15.0-54-generic
**Type/provider of hosts:** bare-metal

If you like to add additional admission controllers the only way to add them is to overwrite the default controller using the enable-admission-plugins parameter. Which then could lead to issues when updating to a new Kubernetes version (with new admission controllers). In my opinion, it would be good to also have a "add additional admission controllers to the default ones" parameter. This should be an additional parameter because there are also use-cases where it is needed to change the default ones.

**Comment by superseb** [comment]
Thanks for reporting, lets merge this into https://github.com/rancher/rke/issues/1322
