### ISSUE TITLE
Dashboard UI - Authorization Token

### ISSUE THREAD

**Issue by mmuruganandam** [rancher/rke#151]
What is the initial password/token for the dashboard?  Where do we get that info?

**Comment by de13** [comment]
Use the token of the dashboard:

`$ kubectl get secrets -n kube-system`

`$ kubectl -n kube-system describe secret dashboard-minimal-token`

Then in the UI, use authentication by token.

**Comment by galal-hussein** [comment]
@de13 thanks for your answer, closing this issue now, @mmuruganandam please feel free to open if you still experience a problem with the Dashboard.

**Comment by ababra** [comment]
Having the same issue. I don't see `dashboard-minimal-token` listed:
```
kubernetes-dashboard-certs                       Opaque                                0         16m
kubernetes-dashboard-key-holder                  Opaque                                2         16m
kubernetes-dashboard-token-x5ltm                 kubernetes.io/service-account-token   3         16m
```

Tried using `kubernetes-dashboard-token-x5ltm`, however when logging in  I receive numerous errors, i.e. 
```
configmaps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list configmaps in the namespace "default"
```
Which I assume means the token does not have any access to the cluster.

**Comment by ababra** [comment]
Followed the step [outlined here](https://github.com/kubernetes/dashboard/wiki/Creating-sample-user) to create a new service account, cluster role binding and generate a token that can be used to log in.
