### ISSUE TITLE
Node removed from an rke cluster does not get cleaned up, has containers running

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rke#1510]
**RKE version:**
Verified with rke: v0.3.0-rc5
**Steps taken:**
Create a three node rke cluster 
Remove one node from the cluster.yml then run rke up again.
The node is removed
```
Sowmyas-MBP:rke-import-cluster$ kubectl get nodes
NAME             STATUS   ROLES                      AGE   VERSION
x.x.x.x    Ready    controlplane,etcd,worker   45m   v1.15.0
y.y.y.y   Ready    controlplane,etcd,worker   45m   v1.15.0
```
But these containers are still running. 
<img width="1433" alt="Screen Shot 2019-07-25 at 1 48 10 PM" src="https://user-images.githubusercontent.com/26032343/61907808-18e54a80-aee3-11e9-88f9-b1d175daafab.png">

**Comment by moelsayed** [comment]
Those are kubernetes pods, not rke deployed containers. Rke will not attempt to removed those. Instead, when/if the node is reused, the new kubelet will replace them.

**Comment by sowmyav27** [comment]
Closing based on @moelsayed 's comments.
