### ISSUE TITLE
RKE should allow setting the DNS Policy for nginx-ingress controller to ClusterFirstWithHostNet (amongst others)

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#1531]
Currently, the nginx ingress controller gets deployed with the default DNS policy of `ClusterFirst` even though it operates on the host network.

It can be desirable to have the nginx-ingress-controller use the DNS policy `ClusterFirstWithHostNet` which will configure DNS queries to go to the cluster's DNS provider, rather than to the DNS servers of the node.

Note that this should not be a blind default, but rather an option to enable if necessary.

**Comment by Oats87** [comment]
Information on the DNS policies here: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

**Comment by sangeethah** [comment]
Tested with rancher server build from master - `d1718af7d` 

nginx-ingress-controller deployed in cluster any of the K8s versions - v1.13.10 , v1.14.6 and v1.15.3 have `dnsPolicy: ClusterFirst` set.

**Comment by sangeethah** [comment]
Tested with latest rancher server build from master `24e4bdfe4`

nginx-ingress-controller deployed in cluster with K8s versions - v1.15.3 still has  `dnsPolicy: ClusterFirst` set.

**Comment by mrajashree** [comment]
@sangeethah I do see dnsPolicy being set to `ClusterFirstWithHostNet` when I pass the following to ingress spec
`dns_policy:  ClusterFirstWithHostNet`

**Comment by sangeethah** [comment]
Tested with rancher build from master - `` 

By default `dnsPolicy: ClusterFirst` gets set for nginx-ingress-controller d. 
We have the ability now to set `dnsPolicy` cluster yml duiring cluster creation (using Edit as YAML option UI)
```
  ingress:
    dns_policy: ClusterFirstWithHostNet
    provider: nginx
```

nginx-ingress-controller  gets deployed with "ClusterFirstWithHostNet" as expected.
Existing automated ingress scenarios work as expected .
