### ISSUE TITLE
Specify labels to nodes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rke#1549]
Ability to specify labels to nodes in cluster.yml

**Comment by Oats87** [comment]
This is already supported: https://rancher.com/docs/rke/latest/en/config-options/nodes/#labels

**Comment by deniseschannon** [comment]
Already available, but not sure if it was explicitly tested. I originally spun this ticket out of #157.

Available to test with v0.3.0-rc6

**Comment by bmdepesa** [comment]
rke 0.3.0-rc6

* Created `cluster.yml` with labels section for node
```
labels:
      foo: bar
      foo2: bar2
```
* rke up brings up the cluster successfully. 
* Checking `kubectl get node <node>` shows all labels present
* Tested with single and multiple labels
* Also exercised as part of reproducing / validating fix for https://github.com/rancher/rke/issues/1437
