### ISSUE TITLE
Print version when RKE is run

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1560]
Just like in Rancher, we should print the version in the log so we know what version is being used as this is sometimes missed when logs are provided or just to make sure you are looking at the correct log and the expected version was used.

**Comment by jiaqiluo** [comment]
The enhancement is validated in rke version v0.3.0-rc9

Now it will print the rke cmd's version in the output 

```
➜  rke up
WARN[0000] This is not an officially supported version (v0.3.0-rc9) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest
INFO[0000] Running RKE version: v0.3.0-rc9

➜  rke version
WARN[0000] This is not an officially supported version (v0.3.0-rc9) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest
INFO[0000] Running RKE version: v0.3.0-rc9
```
