### ISSUE TITLE
rke .dms file cannnot open or use

### ISSUE THREAD

**Issue by hanlimo** [rancher/rke#1568]
**RKE version:**

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**

**Results:**

**Comment by xiaoluhong** [comment]
`sudo mv rke .dms rke `and `sudo chmod +x rke`

**Comment by hanlimo** [comment]
Thank you very much

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
发件人: Xiaolu Hong <notifications@github.com>
发送时间: Monday, August 19, 2019 7:03:30 PM
收件人: rancher/rke <rke@noreply.github.com>
抄送: hanlimo <hanlimo@outlook.com>; Author <author@noreply.github.com>
主题: Re: [rancher/rke] rke .dms file cannnot open or use (#1568)


sudo mv rke .dms rke and sudo chmod +x rke

―
