### ISSUE TITLE
RKE 0.2.7: unknown flag: --repair-malformed-updates

### ISSUE THREAD

**Issue by roycec** [rancher/rke#1570]
**RKE version:**
v0.2.7

**Docker version: (`docker version`,`docker info` preferred)**
RHEL7 docker 1.13.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

3.10.0-957.5.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**
``
kubernetes_version: v1.14.5-rancher1-1
services:
  etcd:
    snapshot: true
    retention: 24h 
    creation: 6h
  kube-api:
    service_cluster_ip_range: 10.22.0.0/16
    pod_security_policy: true
    extra_args:
      anonymous-auth: "false" 
      profiling: "false" 
      repair-malformed-updates: "false"
      service-account-lookup: "true" 
      enable-admission-plugins: "ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,AlwaysPullImages,DenyEscalatingExec,NodeRestriction,EventRateLimit,PodSecurityPolicy" 
      encryption-provider-config: /etc/kubernetes/encryption.yaml                                                                                                       
      admission-control-config-file: /etc/kubernetes/admission.yaml
  kube-controller:
    cluster_cidr: 10.23.0.0/16
    service_cluster_ip_range: 10.22.0.0/16
    extra_args:
      profiling: "false"    
      address: "127.0.0.1" 
      terminated-pod-gc-threshold: "1000"
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.22.0.10
    extra_args:
      streaming-connection-idle-timeout: "1800s" 
      protect-kernel-defaults: "true" 
      make-iptables-util-chains: "true" 
      event-qps: "0" 
  scheduler:
    extra_args:
      profiling: "false"
      address: "127.0.0.1"
network:
  plugin: canal
  options:
    canal_iface: eth0
private_registries: 
  - url: myregistry:5000
    is_default: true
addon_job_timeout: 0
addons: |-
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: default-psp-role
    namespace: ingress-nginx
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - default-psp
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: default-psp-rolebinding
    namespace: ingress-nginx
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: default-psp-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io 
    kind: Group 
    name: system:serviceaccounts 
  - apiGroup: rbac.authorization.k8s.io 
    kind: Group 
    name: system:authenticated 
  --- 
  apiVersion: v1 
  kind: Namespace 
  metadata: 
    name: cattle-system 
  --- 
  apiVersion: rbac.authorization.k8s.io/v1 
  kind: Role 
  metadata: 
    name: default-psp-role 
    namespace: cattle-system 
  rules: 
  - apiGroups: 
    - extensions 
    resourceNames: 
    - default-psp 
    resources: 
    - podsecuritypolicies                                                                                     
    verbs:
    - use
  --- 
  apiVersion: rbac.authorization.k8s.io/v1 
  kind: RoleBinding 
  metadata: 
    name: default-psp-rolebinding 
    namespace: cattle-system 
  roleRef: 
    apiGroup: rbac.authorization.k8s.io 
    kind: Role 
    name: default-psp-role 
  subjects: 
  - apiGroup: rbac.authorization.k8s.io 
    kind: Group 
    name: system:serviceaccounts 
  - apiGroup: rbac.authorization.k8s.io 
    kind: Group 
    name: system:authenticated 
 --- 
  apiVersion: extensions/v1beta1 
  kind: PodSecurityPolicy 
  metadata: 
    name: restricted 
  spec: 
    requiredDropCapabilities: 
    - NET_RAW 
    privileged: false 
    allowPrivilegeEscalation: false 
    defaultAllowPrivilegeEscalation: false 
    fsGroup: 
      rule: RunAsAny 
    runAsUser: 
      rule: MustRunAsNonRoot 
    seLinux: 
      rule: RunAsAny 
    supplementalGroups: 
      rule: RunAsAny 
    volumes: 
    - emptyDir 
    - secret 
    - persistentVolumeClaim 
    - downwardAPI 
    - configMap 
    - projected 
  --- 
  apiVersion: rbac.authorization.k8s.io/v1 
  kind: ClusterRole 
  metadata: 
    name: psp:restricted 
  rules: 
  - apiGroups: 
    - extensions 
    resourceNames: 
    - restricted 
    resources: 
    - podsecuritypolicies 
    verbs: 
    - use 
  --- 
  apiVersion: rbac.authorization.k8s.io/v1 
  kind: ClusterRoleBinding 
  metadata: 
    name: psp:restricted 
  roleRef: 
    apiGroup: rbac.authorization.k8s.io 
    kind: ClusterRole 
    name: psp:restricted 
  subjects: 
  - apiGroup: rbac.authorization.k8s.io 
    kind: Group 
    name: system:serviceaccounts 
  - apiGroup: rbac.authorization.k8s.io 
    kind: Group 
    name: system:authenticated                            

**Steps to Reproduce:**
Add repair-malformed-updates: "false" to kubeapi extra args section and run "rke up --config cluster.yml"

**Results:**

FATA[0079] [controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [xx.xx.xx.xx]: Get https://localhost:6443/healthz: Unable to access the service on localhost:6443. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: unknown flag: --repair-malformed-updates]

**Comment by superseb** [comment]
This was removed in K8s 1.14, you can't use that flag anymore. (See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md)

This flag is in our 2.1 Hardening but not in 2.2 Hardening Guide (https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.2/), as I guess you are using that.

**Comment by roycec** [comment]
ok, thanks for the quick answer. I'll check that.

**Comment by roycec** [comment]
Yes, the guide I was using was for Rancher 2.1.x
