### ISSUE TITLE
Provide instructions on how to upgrade cert-manager

### ISSUE THREAD

**Issue by giovannicandido** [rancher/rke#1581]
**RKE version:**
 v0.2.7
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**

`helm list`

**Results:**
cert-manager    2               Wed Aug 21 18:55:15 2019        DEPLOYED          cert-manager-v0.5.0     v0.5.0          kube-system

Letsencrypt send a email informing that cert-manager traffic from versions below 0.8.0 will be blocked because of optimizations in traffic.

I would like to know how to upgrade certmanager version.

I have tryed:

`helm repo add jetstack https://charts.jetstack.io`

helm upgrade cert-manager jetstack/cert-manager

But deployment failed

**Comment by deniseschannon** [comment]
The Rancher issue tracking how to upgrade cert-manager for HA installs is tracked here: https://github.com/rancher/rancher/issues/22235

We'll keep this open to specifically use to test the RKE CLI setup that is used for our Rancher HA installs.

**Comment by cjellick** [comment]
Assigned @dramich since he is working on the main issue

**Comment by bmdepesa** [comment]
Tracking fresh install and upgrades here #22235
