### ISSUE TITLE
Kubelet container should mount /var/lib/kubelet/device-plugins for device plugin discovery on ContainerOS

### ISSUE THREAD

**Issue by DenisKramer** [rancher/rke#1585]
This is a reposting of [rancher/rancher issue 20155](https://github.com/rancher/rancher/issues/20155) because nobody seems to be picking it up there.

Nividia device plugin does not work on ContainerOS because of inconsistent mount paths for the kubelet container.
 
**RKE version:**

**Docker version: (`docker version`,`docker info` preferred)**

Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.8
 Git commit:        d7080c1
 Built:             Tue Feb 19 23:07:53 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d7080c1
  Built:            Tue Feb 19 23:07:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

4.19.50-coreos-r1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-Metal

**Steps to reproduce (least amount of steps as possible):**
- Create cluster with rke using Kubernetes 1.13
- Create a device plugin via daemon-set
- Verify that device plugin creates sockets as per pluginwatcher API under `/var/lib/kubernetes/device-plugins` on nodes running the daemon-set
- Verify that resources are not declared on node with `kubectl decribe node <nodename>`

**Result:**
- Device plugin will create a socket in `/var/lib/kubelet/device-plugins`
- As of k8s 1.13, the new pluginwatcher API monitors folders under /var/lib/kubelet/device-plugins for new sockets as device discovery mechanism
- Kubelet running in docker container (spun up with rke) has no access to sockets under /var/lib/kubelet/device-plugins and does not discover new devices
- Nvidia GPUs declared by the [gke-accelerator](https://github.com/GoogleCloudPlatform/container-engine-accelerators) plugin fail to add nvidia.com/gpu resources to nodes. But I suspect  all types of device-plugins using the pluginwatcher beta API would fail.

**Other details that may be helpful:**
Output from `docker inspect -f "{{ .Mounts }}" kubelet` on host (omitting volume mounts): 

```
[
{bind  /var/lib/rancher /var/lib/rancher  shared,z true shared} 
{bind  /opt/rke/etc/ceph /etc/ceph   true rprivate} 
{bind  /etc/kubernetes /etc/kubernetes  z true rprivate} 
{bind  /etc /host/etc  ro false rprivate} 
{bind  /usr /host/usr  ro false rprivate} 
{bind  /opt/rke/var/lib/kubelet /opt/rke/var/lib/kubelet  shared,z true shared} 
{bind  /sbin/iscsiadm /sbin/iscsiadm   true rprivate} 
{bind  /usr/sbin/iscsid /usr/sbin/iscsid   true rprivate} 
{bind  /var/run /var/run  rw,rprivate true rprivate} 
{bind  /etc/iscsi /etc/iscsi   true rprivate} 
{bind  /dev /host/dev  rprivate true rprivate} 
{bind  /sys /sys  rprivate true rprivate} 
{bind  /var/lib/kubelet/volumeplugins /var/lib/kubelet/volumeplugins  shared,z true shared} 
{bind  /etc/cni /etc/cni  rw,z true rprivate} 
{bind  /opt/cni /opt/cni  rw,z true rprivate} 
{bind  /opt/rke/var/lib/cni /var/lib/cni  z true rprivate} 
{bind  /var/lib/docker /var/lib/docker  rw,rslave,z true rslave} 
{bind  /var/log/pods /var/log/pods  z true rprivate} 
{bind  /etc/resolv.conf /etc/resolv.conf   true rprivate} 
{bind  /run /run  rprivate true rprivate} 
{bind  /var/lib/calico /var/lib/calico  z true rprivate} 
{bind  /etc/iscsi /var/lib/iscsi   true rprivate} 
{bind  /var/log/containers /var/log/containers  z true rprivate}
]
```

Relevant [documentation in upstream kubelet code](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/util/pluginwatcher):

> The pluginwatcher service will discover plugins in the PluginDir when they place a socket in that directory or, at Kubelet start if the socket is already there.

The PluginDir directory is `/var/lib/kubelet/device-plugins` on the host. Folder content running the gke-accelorator plugin for Nvidia GPUs:

```bash
ls -la /var/lib/kubelet/device-plugins
total 20
drwxr-xr-x. 2 root root 4096 May 10 09:09 .
drwxr-xr-x. 4 root root 4096 May  9 14:54 ..
srwxr-xr-x. 1 root root    0 May 10 09:00 nvidiaGPU-1557478843.sock
```

Changes to the pluginwatcher API in k8s 1.13 are documented [here](https://www.cncf.io/wp-content/uploads/2019/01/CNCF-Webinar_-Kubernetes-1.13.pdf) on slide 10

The problem is similar to issue  [#13897](https://github.com/rancher/rancher/issues/13897) that dealt with volumeplugins.

After studying the rke code a bit more, I realised that kublet mounts `/opt/rke/var/lib/kubelet` because I run on CoreOS. Changing the `device-plugin` volume mount for the gke-accelerator daemonSet now creates sockets in the right place on the host that are also seen from within the kubelet container at `opt/rke/var/lib/kubelet/device-plugins`. However, the device-plugin directory in kubelet seems hard-coded to `/var/lib/kubelet/device-plugin` (see this [issue](https://github.com/kubernetes/kubernetes/issues/68567)). 

Simply sym-linking the created device-socket within the container from /opt/rke/var/lib/kubernetes/devices-plugin to /var/lib/kubernetes/devices-plugin does not work. Possibly because of this code

```go
if fi.Mode()&os.ModeSocket == 0 {
	klog.V(5).Infof("Ignoring non socket file %s", fi.Name())
	return nil
}
```

in [plugin_watcher.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/util/pluginwatcher/plugin_watcher.go#L61)

There is a `kubelet.sock` in /var/lib/kubelet/device-plugins within the kubelet container that would need to be linked outside to the host to fall back to the alpha API for registering the plugin (which also does not work because the host can't follow the symbolic link path and hard linking would be cross-device). 

I think the easiest would be to mount `/opt/rke/var/lib/kubernets/device-plugins:/var/lib/kubernetes/device-plugins` within the kubelet container, similar to the special case for volumedevices.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.7
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal - 16 core Intel / 64GB
- Kubernetes version (use `kubectl version`): 

```json
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by NaPs** [comment]
Hi @DenisKramer, I'm hit by this problem. Do you confirm that nothing has happened to fix it neither at the rancher or k8s side? :-/

**Comment by DenisKramer** [comment]
> Hi @DenisKramer, I'm hit by this problem. Do you confirm that nothing has happened to fix it neither at the rancher or k8s side? :-/

Hi @NaPs. I haven't followed this too closely lately given that ContainerOS is discontinued. We still operate a workaround utilising a little proxy that channels traffice between sockets. The code for the proxy can be found in this [gist](https://gist.github.com/DenisKramer/18d9e2a79d09ae25f3ba07ffb4586577). Hope that helps. That is very hacky. You need to restart the proxy with the correct socket every time the node restarts and kubelet give another randomn name to the nvidia socket.

**Comment by NaPs** [comment]
Actually I have this problem with RancherOS (which is maybe as discontinued as ContainerOS :grin:), but I understand that this is more a problem with RKE and Hyperkube (and the fact that Kubelet is running inside a container with /opt/rke as KubeletRootDir prefix)?

Anyway, thank you for your gist, I'll dig that way to try to find a viable workaround!

**Comment by danielhass** [comment]
Hi @DenisKramer, thanks for your excellent write-up of this issue! Helped a lot with finding a vaible workaround.

I wanted to provide the workaround we applied to get the Kubernetes device-plugin API to work. We are currently running the following setup:
```
Rancher: v2.6.3
RKE1: v1.3.3
Kubernetes: v1.21.9
```
Upstream docs on the device-plugin API can be found [here](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/).

To allow device plugins to communitcate via the required socket setup we mounted the `/var/lib/kubelet/device-plugins/` to the host filesystem to make it visible for other deployments running on the machine. This workaround was also suggested by @DenisKramer back in https://github.com/rancher/rancher/issues/20155 but how to implement it has never been documented.

The following RKE config allows to introduce an additional mount to the RKE kubelet container:
```
services:
    kubelet:
      # Optionally define additional volume binds to a service
      extra_binds:
        - "/var/lib/kubelet/device-plugins:/var/lib/kubelet/device-plugins"
```
This workaround is basically the same one RKE is already using for the volumeplugins.

Hope this helps folks (e.g. @NaPs) to work around the current limitations of the device-plugins API implementation in `kubelet` that doesn't respect the `KubeletRootDir` setting.
