### ISSUE TITLE
camelCase hostnames fails the etcd health check

### ISSUE THREAD

**Issue by metsuke0** [rancher/rke#1596]
**RKE version:** v0.2.8

**Docker version: (`docker version`,`docker info` preferred)** 
$ docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -r
4.15.0-1044-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Steps to Reproduce:**
Using nodes with an address like "k8sMaster0" will fail etcd health checks.
- address: k8s**M**aster0.asdf.local

**Results:**
```INFO[0175] [etcd] Successfully started etcd plane.. Checking etcd cluster health
DEBU[0175] [etcd] Check etcd cluster health
DEBU[0178] Failed to get /health for host [k8sMaster0.asdf.local]: Get https://k8sMaster0.asdf.local:2379/health: Unable to access the service on k8sMaster0.asdf.local:2379. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused)
...
FATA[0247] [etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy
```

Checking the log: /var/lib/rancher/rke/log/etcd_4a175d924cfca77bd4ca82779cd2865bb4f392a06a02b7cab76c04803d1599b3.log

```
{"log":"2019-08-27 20:41:42.765956 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-k8sMaster0-asdf-local.pem, key = /etc/kubernetes/ssl/kube-etcd-k8sMaster0-asdf-local-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true, crl-file = \n","stream":"stderr","time":"2019-08-27T20:41:
42.766125323Z"}
{"log":"2019-08-27 20:41:42.766043 C | etcdmain: open /etc/kubernetes/ssl/kube-etcd-k8sMaster0-asdf-local.pem: no such file or directory\n","stream":"stderr","time":"2019-08-27T20:41:42.766132114Z"}

```

The actual file name:
/etc/kubernetes/ssl/kube-etcd-k8smaster0-asdf-local.pem

**Workaround:**
Using non-camel cased hostnames proceeds with the rke configuration past the etcd phase.
- address: k8s**m**aster0.asdf.local

**Comment by deniseschannon** [comment]
Per our docs: 
https://rancher.com/docs/rke/latest/en/config-options/nodes/#overriding-the-hostname

This hostname doesn’t need to be a routable address, but it must be a valid [Kubernetes resource name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names)
