### ISSUE TITLE
RKE shouldn't pull kube-admin certs from nodes

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1622]
**RKE version:**
v0.3.0-rc9

Because of https://github.com/rancher/rke/pull/1608, we now return error if certificate is not found. Because kube-admin is not deployed to nodes, it will fail if fullstate is empty.

**Comment by deniseschannon** [comment]
Already in v0.3.0.

**Comment by superseb** [comment]
To reproduce:

* Use RKE v0.3.0-rc9
* Create a `cluster.yml` with defaults and one node with all roles
* Run `rke up`
* Remove `cluster.rkestate` (`rm -f cluster.rkestate`)
* Login to the node to copy certificates from `/etc/kubernetes/ssl` to `/etc/kubernetes/.tmp` (`cp -R /etc/kubernetes/ssl /etc/kubernetes/.tmp/`)
* Logout and run `rke up` again
* Error seen: `FATA[0035] Failed to fetch cluster certs from nodes, aborting upgrade: Certificate /etc/kubernetes/.tmp/kube-admin.pem is not found                                                                                                                                                                                          `

To validate, run the same sequence with RKE v0.3.1 and it should provision successfully.

**Comment by sowmyav27** [comment]
**Reproduced the issue using rke `v0.3.0-rc9`**

**Steps:**

- Create a cluster.yml with defaults and one node with all roles
- Run rke up
- Remove cluster.rkestate (rm -f cluster.rkestate)
- Login to the node to copy certificates from /etc/kubernetes/ssl to /etc/kubernetes/.tmp (cp -R /etc/kubernetes/ssl /etc/kubernetes/.tmp/)
- Run rke up again
- Error seen: `FATA[0035] Failed to fetch cluster certs from nodes, aborting upgrade: Certificate /etc/kubernetes/.tmp/kube-admin.pem is not found `

**Verified on rke `v0.3.1`**

**Steps:**

- Create a cluster.yml with defaults and one node with all roles
- Run rke up
- Remove cluster.rkestate (rm -f cluster.rkestate)
- Login to the node to copy certificates from /etc/kubernetes/ssl to /etc/kubernetes/.tmp (cp -R /etc/kubernetes/ssl /etc/kubernetes/.tmp/)
- Run rke up again
- The cluster is provisioned successfully.
