### ISSUE TITLE
Add preventSinglePointFailure to dns autoscaler

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1625]
Since v1.1.0 of `cluster-proportional-autoscaler` it is supported to use `preventSinglePointFailure: true` to the autoscaler configmap to make sure there are more than 1 DNS pod running when nodecount > 1.

**Comment by superseb** [comment]
To validate:

- Create a 1.16 custom cluster
- Add 2 or more nodes
- Check DNS pods (test coredns and kube-dns) count for higher than 1 if node count is higher than 1.

**Comment by deniseschannon** [comment]
Already available in v0.3.0.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.1

* Create 1.1.6.2 cluster
* 5 worker nodes
* autoscaler deployment contains `preventSinglePointFailure: true`
* `coredns` has 2 pods
* edit cluster to use `kube-dns`
* `kubedns` has 2 pods
