### ISSUE TITLE
RKE keeps storing backup in S3 storage even when --s3 is not enabled in the command

### ISSUE THREAD

**Issue by hasonhai** [rancher/rke#1627]
**RKE version:**
rke version v0.2.8

**Docker version: (`docker version`,`docker info` preferred)**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM

**cluster.yml file:**
```
...
    backup_config:
      interval_hours: 12
      retention: 6
      s3backupconfig:
        access_key: "FEGCB5OSXXXXXXXXX7R"
        secret_key: "IfLBWAWWXXXXXXXXXXvchFrHuaa6YGcM1fLqJ3"
        bucket_name: kubernetes-aaptest-cluster2-etcd-backups
        region: ""
        endpoint: rgw.example.com
...
```
**Steps to Reproduce:**
When s3backupconfig is set in cluster.yml, calling etcd one-time snapshot will not switch to local storage even if we do want to choose to store the snapshot locally only.
```
./rke-v0.2.8 --debug etcd snapshot-save --config cluster.yml --name etcd-backup-10092019.snapshot
```
**Results:**
```
INFO[0000] Starting saving snapshot on etcd hosts
INFO[0000] [dialer] Setup tunnel for host [defr4app506.example.com]
INFO[0000] [dialer] Setup tunnel for host [defr4app502.example.com]
INFO[0000] [dialer] Setup tunnel for host [defr4app505.example.com]
INFO[0000] [dialer] Setup tunnel for host [defr4app503.example.com]
INFO[0000] [dialer] Setup tunnel for host [defr4app504.example.com]
INFO[0002] [etcd] Saving snapshot [etcd-backup-10092019.snapshot] on host [defr4app502.example.com]
INFO[0003] [etcd] Successfully started [etcd-snapshot-once] container on host [defr4app502.example.com]
INFO[0003] Waiting for [etcd-snapshot-once] container to exit on host [defr4app502.example.com]
INFO[0003] Container [etcd-snapshot-once] is still running on host [defr4app502.example.com]
INFO[0004] Waiting for [etcd-snapshot-once] container to exit on host [defr4app502.example.com]
FATA[0004] Failed to take one-time snapshot, exit code [1]: time="2019-09-10T11:57:36Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:kubernetes-aaptest-cluster2-etcd-backups, err:Get https://rgw.example.com/kubernetes-aaptest-cluster2-etcd-backups/?location=: x509: certificate signed by unknown authority"
```
In my case, the error is about the certificate verification, but what I want to show is that: why does RKE connect to S3 storage even though I only chose to store the snapshot locally?

**Comment by alena1108** [comment]
@hasonhai in general, rke design is to treat cluster.yml as a source of truth. So if s3 config is defined in cluster.yml, all the rke cli commands for the snapshot will leverage the config. For both one time snapshots and recurring ones. This is done so you don't have to specify s3 options on every snapshot-save call.

We can introduce an extra flag --local to give command a directive to store to local only. 

Marking this issue as enhancement for the ^

**Comment by ThunderRush** [comment]
Hello @alena1108 
I have the same issues, but I do not have any S3 configured in either my cluster.yml, nor in the command.

This is my YML:

`cluster_name: "rancher-test"

nodes:
  - address: 10.80.148.1
    hostname_override: dhq-rancher-t01
    user: rancher
    role: [controlplane,worker,etcd]

  - address: 10.80.148.2
    hostname_override: dhq-rancher-t02
    user: rancher
    role: [controlplane,worker,etcd]

  - address: 10.80.148.3
    hostname_override: dhq-rancher-t03
    user: rancher
    role: [controlplane,worker,etcd]

services:
  etcd:
    backup_config:
      interval_hours: 6
      retention: 12
`

And this is the command I use to run backups with:

`rke etcd snapshot-save --name $dt.db --config test.yml`

I recently had to delete my nodes and tried to restore them out of a backup (thankfully it's just a test environment so nothing of value was lost), and received the following error when I tried to run this:

`INFO[0000] Restoring etcd snapshot 20191105084416.db
INFO[0000] Successfully Deployed state file at [./test-restore.rkestate]
INFO[0000] [dialer] Setup tunnel for host [10.80.148.1]
FATA[0005] failed to prepare backup: restoring S3 backups with no cluster level S3 configuration is not supported
1 :(`

**Comment by XavierMoon** [comment]
> Hello @alena1108
> I have the same issues, but I do not have any S3 configured in either my cluster.yml, nor in the command.
> 
> This is my YML:
> 
> ```
> cluster_name: "rancher-test"
> 
> nodes:
>   - address: 10.80.148.1
>     hostname_override: dhq-rancher-t01
>     user: rancher
>     role: [controlplane,worker,etcd]
> 
>   - address: 10.80.148.2
>     hostname_override: dhq-rancher-t02
>     user: rancher
>     role: [controlplane,worker,etcd]
> 
>   - address: 10.80.148.3
>     hostname_override: dhq-rancher-t03
>     user: rancher
>     role: [controlplane,worker,etcd]
> 
> services:
>   etcd:
>     backup_config:
>       interval_hours: 6
>       retention: 12
> ```
> 
> And this is the command I use to run backups with:
> 
> `rke etcd snapshot-save --name $dt.db --config test.yml`
> 
> I recently had to delete my nodes and tried to restore them out of a backup (thankfully it's just a test environment so nothing of value was lost), and received the following error when I tried to run this:
> 
> ```
> rkeuser@dhq-mgmt-t01 ~ $ rke etcd snapshot-restore --name "20191105084416.db" --config ./test-restore.yml
> INFO[0000] Restoring etcd snapshot 20191105084416.db
> INFO[0000] Successfully Deployed state file at [./test-restore.rkestate]
> INFO[0000] [dialer] Setup tunnel for host [10.80.148.1]
> FATA[0005] failed to prepare backup: restoring S3 backups with no cluster level S3 configuration is not supported
> 1 :(
> ```
> 
> e:
> Removed the services: section has worked, it seems. Is this intended behavior? Is backup_config: already S3?

@loganhz  have the same issues

**Comment by superseb** [comment]
Please see https://github.com/rancher/rke/issues/1538 for tracking the issue regarding the `failed to prepare backup: restoring S3 backups with no cluster level S3 configuration is not supported` error, there will be a fix for this soon.

**Comment by superseb** [comment]
This should be fixed.
