### ISSUE TITLE
rke up error 

### ISSUE THREAD

**Issue by magic-chenyang** [rancher/rke#1635]
**RKE version:**
0.2.8

**Docker version: (`docker version`,`docker info` preferred)**
18.09.9-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-957.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**
nodes:
- address: 192.168.1.103    
  user: rke
  role: [ "controlplane", "etcd", "worker" ]
  ssh_key_path: /home/rke/.ssh/id_rsa

private_registries:
- url: 192.168.1.103:808
  user: admin
  password: "*********"
  is_default: true

services:
  etcd:
    extra_args:
        auto-compaction-retention: 240 
        quota-backend-bytes: '6442450944'
    backup_config:
      enabled: true     # enables recurring etcd snapshots
      interval_hours: 6 # time increment between snapshots
      retention: 60     # time in days before snapshot purge
   
**Steps to Reproduce:**
useradd rke && chmod -aG docker rke
su rke && ssh-keygen
rke up --config ./rancher-cluster.yml

**Results:**
[root@localhost rke]# rke up --config ./rancher-cluster.yml 
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] [certificates] Generating etcd-192.168.1.103 certificate and key 
INFO[0000] [certificates] Generating Kubernetes API server certificates 
INFO[0000] [certificates] Generating admin certificates and kubeconfig 
INFO[0000] Successfully Deployed state file at [./rancher-cluster.rkestate] 
INFO[0000] Building Kubernetes cluster                  
INFO[0000] [dialer] Setup tunnel for host [192.168.1.103] 
WARN[0000] Failed to set up SSH tunneling for host [192.168.1.103]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [192.168.1.103:22] using SSH. Please check if you are able to SSH to the node using the specified SSH Private Key and if you have configured the correct SSH username. Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain 
WARN[0000] Removing host [192.168.1.103] from node lists 
FATA[0000] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [192.168.1.103]

I have made many changes, but the problem remains unsolved. I need help，thx

**Comment by willmao** [comment]
could you ssh to 192.168.1.103 with rke user manually ?

maybe you need to add the content of id_ras.pub to /home/rke/.ssh/authorized_keys

**Comment by magic-chenyang** [comment]
I've already done that, but it doesn't work.

**Comment by magic-chenyang** [comment]
Should be amendedssh_key_path: /root/.ssh/id_rsa 。
I solved the problem. thank you

**Comment by tpbrown** [comment]
For others that might see this.  Above issue was because  rke is running as root and it was looking for the private key in root's home.

If you're getting the same message, but the private key and user are correct, note that on the target nodes (e.g. cluster nodes) you need to populate the SSH user's ~/.ssh/authorized_keys file.
