### ISSUE TITLE
Reconsider what addons are critical

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1637]
As of today, only network add-ons are marked as critical as its needed to bring up the cluster. But without a DNS provider, there is not really much you can do in the cluster. In the current case, if any add-on other than network fails, we just log a warning and continue which leaves the cluster in a incomplete state. There is just a warning any indication that `rke up` should be run again. This also causes Rancher to think provisioning has completed and won't retry.

We should reconsider what we think is critical, I would say all default add-ons should be active before we mark the cluster as being built successfully.

**Comment by superseb** [comment]
To test this, normally provisioning using `rke up` would only stop if the network plugin failed to deploy. With this change, any error in the default addon deployment (ingress/metrics/dns) should stop provisioning with an error.

**Comment by sowmyav27** [comment]
**Using rke version `1.2.5-rc1`**

- Do an rke up (1 node all roles)
- Give an incorrect `system_images` for ingress, metrics_server and coredns in the cluster.yml
- Cluster was deployed successfully
- The the pods are in `ErrImagePull`. 

**Expected:**

**Comment by superseb** [comment]
Wrong image is not an error in add-on, this needs to be tested with a bad template or with nodes with disk pressure to simulate a failure. Unless a bad image for CNI in existing RKE releases causes `rke up` to fail?

**Comment by sowmyav27** [comment]
Bad image for CNI did not cause rke up to fail. Will validate with bad template or with nodes with disk pressure .

**Comment by sadiapoddar** [comment]
I tested the fix on  ./rke --version
rke version v1.2.5

1. Added an ingress add-ons with a bad key "- key: "node.kubernetes./unreachable".  which should be "- key: "node.kubernetes.io/unreachable"
2. ran >.rke up
3. and hit this error 
4. rke process exit with this error, 

INFO[0053] [addons] Executing deploy job rke-ingress-controller 
FATA[0104] Failed to get job complete status for job rke-ingress-controller-deploy-job in namespace kube-system 

@superseb Is this the fix you added

**Comment by sadiapoddar** [comment]
Reopening as I need to test the fix on rke 1.3.0-rc for master branch

**Comment by sadiapoddar** [comment]
Verified the fix on rke v1.3.0-rc1
I tested the fix on ./rke --version
rke version  v1.3.0-rc1

Added an ingress add-ons with a bad key "- key: "node.kubernetes./unreachable". which should be "- key: "node.kubernetes.io/unreachable"
ran >.rke up
and hit this error
rke process exit with this error,

INFO[0169] [addons] Executing deploy job rke-ingress-controller 
FATA[0215] F**ailed to get job complete status for job rke-ingress-controller-deploy-job in namespace kube-system**

**Comment by sadiapoddar** [comment]
Verified the fix on rke v1.3.0-rc1
I tested the fix on ./rke --version
Verified the rke version v1.2.6-rc2

Added an ingress add-ons with a bad key "- key: "node.kubernetes./unreachable". which should be "- key: "node.kubernetes.io/unreachable"
ran >.rke up
and hit this error
rke process exit with this error,

Repeated the same test for coredns-addon and matrics-addon
---------- ingress-addons------
NFO[0038] [addons] Executing deploy job rke-ingress-controller 
FATA[0084] Failed to get job complete status for job rke-ingress-controller-deploy-job in namespace kube-system 

---------- coredns-addons----------
INFO[0028] [addons] Successfully saved ConfigMap for addon rke-coredns-addon to Kubernetes 
INFO[0028] [addons] Executing deploy job rke-coredns-addon 
FATA[0079] Failed to get job complete status for job rke-coredns-addon-deploy-job in namespace kube-system 

--------- metrics-addons------
NFO[0139] [addons] Executing deploy job rke-metrics-addon 
FATA[0184] Failed to get job complete status for job rke-metrics-addon-deploy-job in namespace kube-system
