### ISSUE TITLE
"rke config --system-images" returns windows image 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke#1651]
rke  v0.3.0-rc10

`rke config --system-images` returns the list of images which includes this one:
```
rancher/kubelet-pause:v0.1.3
```
It is used for Windows worker node and is already included in the `rancher-windows-images.txt` in the release page.

But `rke config --system-images >> ./rancher-images.txt` will add it to `rancher-images.txt` which are all images for Linux OS.

**Comment by alena1108** [comment]
@jiaqiluo with this doc pr the rke cli images generation step will be relevant to rke cli (corresponding doc commit https://github.com/rancher/docs/pull/1761/commits/8442fb6cc11370f45193185b2fda79c27f5bd4f5) 

As windows images are also not relevant for standalone rke, we should just go ahead and exclude them from the list generated by `rke config --system-images`

**Comment by sangeethah** [comment]
Can be tested with `v0.3.0-rc11`

**Comment by jiaqiluo** [comment]
The bug fix is validated in v0.3.0-rc11

the image `rancher/kubelet-pause:v0.1.3` is removed from the output of `rke config --system-images`
