### ISSUE TITLE
FATA[0090] [etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy

### ISSUE THREAD

**Issue by psaini0212** [rancher/rke#1663]
**RKE version:** 
0.2.2/0.2.4/0.2.8

**Docker version: (`docker version`,`docker info` preferred)**
docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false

docker info
Containers: 61
 Running: 48
 Paused: 0
 Stopped: 13
Images: 189
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local pxd
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.21.3.el7.x86_64
Operating System: Red Hat
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.6GiB
Name: shared-p22-06.sandbox.local
ID: 3FIE:76UI:5XVB:IROS:AZOB:QRWD:6DNI:426D:67MM:VZNF:PKDW:U7NY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: bridge-nf-call-ip6tables is disabled

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

uname -r
3.10.0-957.21.3.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
nodes:
- address: abc.sandbox.local
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa.rke
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
- address: def.sandbox.local
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa.rke
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
- address: ghi.sandbox.local
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa.rke
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: true
    retention: "96h"
    creation: "2h"
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: flannel
  options: {}
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: |-
  apiVersion: v1
  kind: Namespace
  metadata:
    name: mobile
addons_include: []
system_images:
ssh_key_path: ~/.ssh/id_rsa.rke
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: "v1.13.5-rancher1-2"
private_registries:
  - url: myregistry.sbx.zone
    user: my_user
    password: xxxxxx
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: "mobile-build"
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
restore:
  restore: false
  snapshot_name: ""
dns:
  provider: coredns

**Steps to Reproduce:**

The cluster was initially provisioned with rke v0.2.1 with the default version of k8 at that time which was - v1.13.5; we would like to upgrade the k8 version now so tried rke v0.2.8 first with its k8 version of 1.13 series. Post that we tried with rke v0.2.4 and rke v0.2.2 with the equivalent k8 versions of 1.13 series but in all cases, we are getting the same error as below.

It reports etcd is not healthy however is I do below inside etcd container; it says it is healthy.

/ # etcdctl endpoint health --endpoints https://abc.sandbox.local:2379
https://abc.sandbox.local:2379 is healthy: successfully committed proposal: took = 1.836608ms
/ # etcdctl endpoint health --endpoints https://def.sandbox.local:2379
https://def.sandbox.local:2379 is healthy: successfully committed proposal: took = 1.822678ms
/ # etcdctl endpoint health --endpoints https://ghi.sandbox.local:2379
https://ghi.sandbox.local:2379 is healthy: successfully committed proposal: took = 1.249667ms

**Results:**
INFO[0039] [etcd] Successfully started etcd plane.. Checking etcd cluster health
FATA[0090] [etcd] Failed to bring up Etcd Plane: [etcd] Etcd Cluster is not healthy

Below are the etcd container logs -

2019-09-24 13:04:08.434827 I | mvcc: store.index: compact 42161071
2019-09-24 13:04:08.437381 I | mvcc: finished scheduled compaction at 42161071 (took 2.035754ms)
2019-09-24 13:06:54.876794 I | etcdmain: rejected connection from "10.112.207.45:45510" (error "EOF", ServerName "")
2019-09-24 13:06:54.914025 I | etcdmain: rejected connection from "10.112.207.48:35303" (error "EOF", ServerName "")
2019-09-24 13:06:54.914301 I | etcdmain: rejected connection from "10.112.207.35:39097" (error "EOF", ServerName "")
2019-09-24 13:09:08.439261 I | mvcc: store.index: compact 42161952
2019-09-24 13:09:08.441951 I | mvcc: finished scheduled compaction at 42161952 (took 2.173701ms)
2019-09-24 13:13:29.822282 I | etcdmain: rejected connection from "10.112.207.48:43995" (error "EOF", ServerName "")
2019-09-24 13:13:29.838360 I | etcdmain: rejected connection from "10.112.207.45:38531" (error "EOF", ServerName "")
2019-09-24 13:13:29.843050 I | etcdmain: rejected connection from "10.112.207.35:40356" (error "EOF", ServerName "")
2019-09-24 13:14:08.443098 I | mvcc: store.index: compact 42162789
2019-09-24 13:14:08.445271 I | mvcc: finished scheduled compaction at 42162789 (took 1.76412ms)
2019-09-24 13:19:08.447406 I | mvcc: store.index: compact 42163630
2019-09-24 13:19:08.449756 I | mvcc: finished scheduled compaction at 42163630 (took 1.887096ms)
2019-09-24 13:22:30.652521 I | etcdmain: rejected connection from "10.112.207.48:40804" (error "EOF", ServerName "")
2019-09-24 13:22:30.688664 I | etcdmain: rejected connection from "10.112.207.45:42917" (error "EOF", ServerName "")
2019-09-24 13:22:30.755835 I | etcdmain: rejected connection from "10.112.207.35:41136" (error "EOF", ServerName "")

**Comment by deniseschannon** [comment]
Implementing https://github.com/rancher/rke/issues/1300 would provide more info on why the cluster is broken.

**Comment by psaini0212** [comment]
Thanks @deniseschannon but Is there any plan to fix the actual bug? as the etcdctl command clearly reports that it is not unhealthy.

**Comment by willmao** [comment]
same issue and we can not update our cluster now, is there any workaround?

**Comment by Tsingshen** [comment]
有可能是rancher服务器与集群主机之间的网络问题，请检查rancher服务器的端口开放情况。

**Comment by Tsingshen** [comment]
May be the rancher host hadn't open the needed port for all of k8s-cluster-host, pleased check.
I had met this question before,  my rancher host and k8s-cluster-host were not in the same vpc and this question appeared.Finally, I use another host which have the save vpc with k8s-cluster-host, it's ok.
