### ISSUE TITLE
how to change root-dir of kubelet to /data/kubelet

### ISSUE THREAD

**Issue by myselfghost** [rancher/rke#1667]
I want to change root-dir of kubelet to /data/kubelet.

config.yml:
```
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 10.200.0.10
      fail_swap_on: false
      extra_args:
        root-dir: "/data/kubelet"
```

kubelet can not start container.
error log:
```
  Warning  Failed     1m    kubelet, 10.15.10.34  Error: failed to start container "app": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/data/kubelet/pods/f9ba27a0-e001-11e9-9aaa-005056805ec7/etc-hosts\\\" to rootfs \\\"/data/docker/overlay/849158ed089f2a9432d8eded1bc3789e2c4b4ee37b06db233bfab3a77443afb4/merged\\\" at \\\"/data/docker/overlay/849158ed089f2a9432d8eded1bc3789e2c4b4ee37b06db233bfab3a77443afb4/merged/etc/hosts\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  Failed  1m  kubelet, 10.15.10.34  Error: failed to start container "filebeat": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/data/kubelet/pods/f9ba27a0-e001-11e9-9aaa-005056805ec7/etc-hosts\\\" to rootfs \\\"/data/docker/overlay/d1b2ea6dff2fb830c0b36f45a4892134339384d4499b02a3a46730645fa9443c/merged\\\" at \\\"/data/docker/overlay/d1b2ea6dff2fb830c0b36f45a4892134339384d4499b02a3a46730645fa9443c/merged/etc/hosts\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  Failed  58s  kubelet, 10.15.10.34  Error: failed to start container "filebeat": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/data/kubelet/pods/f9ba27a0-e001-11e9-9aaa-005056805ec7/etc-hosts\\\" to rootfs \\\"/data/docker/overlay/07e71e800899b8ec43a01b32e73d40a9bb088c0a27d5afa42ee98b77e0b3e274/merged\\\" at \\\"/data/docker/overlay/07e71e800899b8ec43a01b32e73d40a9bb088c0a27d5afa42ee98b77e0b3e274/merged/etc/hosts\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**Comment by hasonhai** [comment]
First you need to create /data/kubelet on the hosts that run kubelet container.
Then mount it to `kubelet` container with `extra_binds`
```
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 10.200.0.10
      fail_swap_on: false
      extra_args:
        root-dir: "/data/kubelet"
      extra_binds:
        - "/data/kubelet:/data/kubelet"
```

**Comment by myselfghost** [comment]
> First you need to create /data/kubelet on the hosts that run kubelet container.
> Then mount it to `kubelet` container with `extra_binds`
> 
> ```
>     kubelet:
>       cluster_domain: cluster.local
>       cluster_dns_server: 10.200.0.10
>       fail_swap_on: false
>       extra_args:
>         root-dir: "/data/kubelet"
>       extra_binds:
>         - "/data/kubelet:/data/kubelet"
> ```

thanks, i will  try

**Comment by myselfghost** [comment]
> First you need to create /data/kubelet on the hosts that run kubelet container.
> Then mount it to `kubelet` container with `extra_binds`
> 
> ```
>     kubelet:
>       cluster_domain: cluster.local
>       cluster_dns_server: 10.200.0.10
>       fail_swap_on: false
>       extra_args:
>         root-dir: "/data/kubelet"
>       extra_binds:
>         - "/data/kubelet:/data/kubelet"
> ```

not work

**Comment by superseb** [comment]
Please try

```
services:
  kubelet:
    extra_args:
      root-dir: "/data/kubelet"
    extra_binds:
    - "/data/kubelet:/data/kubelet:shared,z"
```

Can you also share `docker info` from the host you are using for the cluster?

**Comment by myselfghost** [comment]
just need to :
`
prefix_path: /data/kubelet

`
do not need : 
`
services:
  kubelet:
    extra_args:
      root-dir: "/data/kubelet"
    extra_binds:
    - "/data/kubelet:/data/kubelet:shared,z"
`

**Comment by zaggash** [comment]
Not sure if `prefix_path` do exactly the same thing.

If you look at the documentation:
https://rancher.com/docs/rke/latest/en/config-options/#prefix-path
`prefix_path` changes the path for all the RKE config folders.

While the config specified [here](https://github.com/rancher/rke/issues/1667#issuecomment-601375513) only changes the location of the kubelet folder.
