### ISSUE TITLE
Support version for Docker

### ISSUE THREAD

**Issue by flemzord** [rancher/rke#168]
**RKE version:** v0.0.8-dev

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.4
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:24:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.4
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:24:58 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.4.0
VERSION_ID=1576.4.0
BUILD_ID=2017-12-06-0449
PRETTY_NAME="Container Linux by CoreOS 1576.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
BareMetal

**Results:**
NFO[0000] Building Kubernetes cluster
INFO[0000] [ssh] Setup tunnel for host []
FATA[0000] Failed to set up SSH tunneling for Etcd host []: Unsupported Docker version found [17.09.0-ce], supported versions are [1.12.6 1.13.1 17.03.2]

It's possible authorize CoreOS docker version for RKE ?

**Comment by superseb** [comment]
We made it possible to ignore supported Docker version (https://github.com/rancher/rke/issues/149). This is in `master`, not yet released.
