### ISSUE TITLE
system_images is empty when running `rke config`

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1685]
**RKE version:**
v0.3.0

**Steps to Reproduce:**
Run `./rke config` and hold Enter for only defaults

**Results:**
`system_images` will be empty.

Also, the Kubernetes Docker image which normally would show a default shows `none`:

```
[+] Kubernetes Docker image [none]: 
```

**Comment by alena1108** [comment]
The fix can be tested with `v0.3.2-rc1`

**Comment by bmdepesa** [comment]
rke v0.3.2-rc1

* Ran `rke config` using defaults
* System images are populated in resulting `cluster.yml`
* Kubernetes Docker image is populated in defaults
  * `[+] Kubernetes Docker image [rancher/hyperkube:v1.15.5-rancher1]`
