### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS after creating a HA cluster with rke 0.3.0

### ISSUE THREAD

**Issue by karltremblay** [rancher/rke#1689]
**RKE version:v0.3.0**

**Docker version: 18.09.8**

**Operating system and kernel: RancherOS v1.5.4 - 4.14.138-rancher**

**Type/provider of hosts: AWS - EC2**

**cluster.yml file:
---
nodes:
  -
    address: x.x.x.x
    role:
      - controlplane
      - worker
      - etcd
    ssh_key_path: ~/.ssh/key
    user: rancher
  -
    address: x.x.x.x
    role:
      - controlplane
      - worker
      - etcd
    ssh_key_path: ~/.ssh/key
    user: rancher
  -
    address: x.x.x.x
    role:
      - controlplane
      - worker
      - etcd
    ssh_key_path: ~/.ssh/key
    user: rancher
creation: 6h
etcd: ~
retention: 24h
services: ~
snapshot: true
**

**Steps to Reproduce:

- Textbook HA 3 nodes cluster install following the online documentation until you need to bring rancher up with helm.

- Note : The SSL is terminated at the application load balancer.  

- helm install rancher-stable/rancher --name rancher --namespace cattle-system  --set hostname=test.example.com  --set tls=external 

**

**Results:
When we try to reach https://test.example.com, we get an ERR_TOO_MANY_REDIRECTS error on the browser. 

The port 80 on the rke nodes redirect any request pointing to the set hostname to https://test.exemple.com.

The AWS application load balancer receive the https traffic which is offload to http to the node which redirect back to https which point to the load balancer causing a redirecting loop.

**

**Comment by superseb** [comment]
Please try https://github.com/rancher/rancher/issues/23341#issuecomment-540601760

Merging into https://github.com/rancher/rancher/issues/23341
