### ISSUE TITLE
`always_pull_images: true` doesn't get applied

### ISSUE THREAD

**Issue by fcuello-fudo** [rancher/rke#1690]
**RKE version:**
0.3.0
**Docker version: (`docker version`,`docker info` preferred)**
18.09.7
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 18.04.3 LTS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Othe cloud
**cluster.yml file:**
```
services:
  kube-api:
    always_pull_images: true
```

**Steps to Reproduce:**
Setting `always_pull_images: true` doesn't get applied
**Results:**
This change made `AlwaysPullImages` depend on having also `PodSecurityPolicy` enabled for some reason:
https://github.com/rancher/rke/commit/c191ed62023408e95d7c0ce348675268cfbe0e56#diff-2e9ef6d97acca90e8ed40f581b9f7264L207

**Comment by sowmyav27** [comment]
**Verified using `rke: v0.3.0`**

- Do an rke up with the following set in `cluster.yml` file.
- on `Docker inspect kube-apiserver`, `AlwaysPullImages` argument is NOT set in the args list
- docker logs kube-apiserver - does not show the `AlwaysPullImages` argument is set/passed


**Verified using `rke:v0.3.2-rc3`**

- Do an rke up with the following set in `cluster.yml` file.
- on `Docker inspect kube-apiserver`, `AlwaysPullImages` argument is set.
```
"Args": [
            "kube-apiserver",
            "--etcd-keyfile=/etc/kubernetes/ssl/kube-node-key.pem",
            "--etcd-prefix=/registry",
            "--storage-backend=etcd3",
            "--advertise-address=x.x.x.x.",
            "--service-cluster-ip-range=x.x.x.x./16",
            "--service-node-port-range=30000-32767",
            "--allow-privileged=true",
            "--kubelet-client-key=/etc/kubernetes/ssl/kube-apiserver-key.pem",
            "--authorization-mode=Node,RBAC",
            "--client-ca-file=/etc/kubernetes/ssl/kube-ca.pem",
            "--etcd-servers=https://x.x.x.x:2379",
            "--runtime-config=authorization.k8s.io/v1beta1=true",
            "--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,Priority,TaintNodesByCondition,PersistentVolumeClaimResize,AlwaysPullImages",
```
- docker logs kube-apiserver - `AlwaysPullImages` is being set
```
+ ........,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,Priority,TaintNodesByCondition,PersistentVolumeClaimResize,AlwaysPullImages....
```
