### ISSUE TITLE
Hostname override for a previously provisioned cluster

### ISSUE THREAD

**Issue by eroji** [rancher/rke#1693]
**RKE version:**
0.3.0

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:40:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:10:42 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-1062.1.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM

**cluster.yml file:**

    nodes:
    - address: rancher-01.example.com
      port: "22"
      internal_address: 10.0.0.11
      role:
      - controlplane
      - etcd
      - worker
      hostname_override: ""
      user: rancher
      docker_socket: /var/run/docker.sock
      ssh_key: ""
      ssh_key_path: ~/.ssh/id_rsa
      labels: {}
    - address: rancher-02.example.com
      port: "22"
      internal_address: 10.0.0.12
      role:
      - controlplane
      - etcd
      - worker
      hostname_override: ""
      user: rancher
      docker_socket: /var/run/docker.sock
      ssh_key: ""
      ssh_key_path: ~/.ssh/id_rsa
      labels: {}
    - address: rancher-03.example.com
      port: "22"
      internal_address: 10.0.0.13
      role:
      - controlplane
      - etcd
      - worker
      hostname_override: ""
      user: rancher
      docker_socket: /var/run/docker.sock
      ssh_key: ""
      ssh_key_path: ~/.ssh/id_rsa
      labels: {}
    services:
      etcd:
        image: ""
        extra_args: {}
        extra_binds: []
        extra_env: []
        external_urls: []
        ca_cert: ""
        cert: ""
        key: ""
        path: ""
        snapshot: true
        retention: "24h"
        creation: "6h0s"
      kube-api:
        image: ""
        extra_args: {}
        extra_binds: []
        extra_env: []
        service_cluster_ip_range: 10.43.0.0/16
        service_node_port_range: ""
        pod_security_policy: false
      kube-controller:
        image: ""
        extra_args: {}
        extra_binds: []
        extra_env: []
        cluster_cidr: 10.42.0.0/16
        service_cluster_ip_range: 10.43.0.0/16
      scheduler:
        image: ""
        extra_args: {}
        extra_binds: []
        extra_env: []
      kubelet:
        image: ""
        extra_args: {}
        extra_binds: []
        extra_env: []
        cluster_domain: cluster.local
        infra_container_image: ""
        cluster_dns_server: 10.43.0.10
        fail_swap_on: false
      kubeproxy:
        image: ""
        extra_args: {}
        extra_binds: []
        extra_env: []
    network:
      plugin: canal
      options: {}
    authentication:
      strategy: x509
      options: {}
      sans: []
    addons: ""
    addons_include: []
    system_images:
      etcd: ""
      alpine: ""
      nginx_proxy: ""
      cert_downloader: ""
      kubernetes_services_sidecar: ""
      kubedns: ""
      dnsmasq: ""
      kubedns_sidecar: ""
      kubedns_autoscaler: ""
      coredns: ""
      coredns_autoscaler: ""
      kubernetes: ""
      flannel: ""
      flannel_cni: ""
      calico_node: ""
      calico_cni: ""
      calico_controllers: ""
      calico_ctl: ""
      calico_flexvol: ""
      canal_node: ""
      canal_cni: ""
      canal_flannel: ""
      canal_flexvol: ""
      weave_node: ""
      weave_cni: ""
      pod_infra_container: ""
      ingress: ""
      ingress_backend: ""
      metrics_server: ""
      windows_pod_infra_container: ""
    ssh_key_path: ~/.ssh/id_rsa
    ssh_agent_auth: false
    authorization:
      mode: rbac
      options: {}
    ignore_docker_version: true
    kubernetes_version: ""
    private_registries: []
    ingress:
      provider: ""
      options: {}
      node_selector: {}
      extra_args: {}
    cluster_name: ""
    cloud_provider:
      name: ""
    prefix_path: ""
    addon_job_timeout: 0
    bastion_host:
      address: ""
      port: ""
      user: ""
      ssh_key: ""
      ssh_key_path: ""
    monitoring:
      provider: ""
      options: {}

**Steps to Reproduce:**
Create the cluster using the cluster.yaml then update the hostname_override value for each node then run `rke up` again.

**Results:**
RKE finishes running however cluster will become unavailable and kube-system pods will get stuck crash looping.

I am not sure if this is expected, however RKE provisioned cluster are identified with FQDN instead of short hostnames like ones provision by Rancher's custom cluster creation. This doesn't cause functional issue however, I'd expect RKE to be able to update the cluster with hostname override.

**Comment by superseb** [comment]
Is this covered by https://github.com/rancher/rke/issues/861#issuecomment-413279322?

**Comment by eroji** [comment]
It does appear to be related.

**Comment by eroji** [comment]
I tried adding hostname_override to just 1 of the 3 nodes and 'rke up'. The cluster came up with the FQDN node showing NotReady as expected. Removing the node however borks the cluster complete. Now 'kubectl' no longer responds.
