### ISSUE TITLE
addon_job_timeout is too low

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#1713]
**RKE version:** 0.2.x, 0.3.x

**Docker version: (`docker version`,`docker info` preferred)** N/A

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** N/A

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** N/A

**cluster.yml file:** N/A

**Steps to Reproduce:** Have slow system, run `rke up`

**Results:** Addon job deployment will fail the first time around if your internet connection is slow or your underlying hard disk for `/var/lib/docker` is slow (or whatever is hosting your images)

As far as I can tell the reason this takes longer these days is because the docker image pull time takes a while.

**Comment by pasikarkkainen** [comment]
Yes, indeed, addon_job_timeout default value of 30 seconds is too low (for example https://github.com/rancher/rke/issues/1652)

Maybe increase "addon_job_timeout" to 60 seconds as a default ?

**Comment by pasikarkkainen** [comment]
this is still a valid issue. the default rke addon job timeout should be increased.

**Comment by superseb** [comment]
This can be merged into https://github.com/rancher/rke/issues/2143
