### ISSUE TITLE
How to add transient worker(s) to cluster

### ISSUE THREAD

**Issue by tlvenn** [rancher/rke#1732]
Hi,

I am curious to understand how we can spin a worker node and have it join an existing cluster without adding that node to the inventory as this node is transient.

I believe reading somewhere that Rancher offers some kind of onboarding for a worker node using a token and a simple command to be run on that node.

Is there any plan to support something like this with RKE ?

My use case being in an hybrid cloud where most of the nodes are on baremetal (stable inventory) and using public cloud resources to add more resources when needed on demand with an autoscaler.

**Comment by InsOpDe** [comment]
@tlvenn did you found a solution for this?

**Comment by tlvenn** [comment]
I did not at the time but actually your question is pretty timely because it is something i want to investigate further as we now have a concrete need.

**Comment by tlvenn** [comment]
@superseb any chance you can share some insights on how this works with RKE please ?

**Comment by superseb** [comment]
There is currently no plan for RKE to provide a way to add a node to the cluster without using the RKE CLI. Other projects like k3s and RKE2 are providing this way.
