### ISSUE TITLE
Support for vSphere storage Container Storage Interface (CSI)

### ISSUE THREAD

**Issue by vjtm** [rancher/rke#1733]
This is an enhancement request for vsphere/vmware cloud provider storage layer.

Support for deploying vSphere storage Container Storage Interface (CSI).
It's GA already.
The in-tree cloud provider for vSphere is deprecated.
The CSI is the standard way to implement the Storage layer.
It would improve and evolve over time.

https://github.com/kubernetes-sigs/vsphere-csi-driver
https://cloud-provider-vsphere.sigs.k8s.io/

It requires vSphere 6.7u3

**Comment by janeczku** [comment]
see https://github.com/rancher/rancher/issues/23357

**Comment by lebenitza** [comment]
@janeczku the linked issue does not have much activity either. Do you have any info about the status of it?

Our RKE clusters would benefit a lot from https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/151 which allows expansion of PVCs over vSphere.
