### ISSUE TITLE
change upgrade flow for control plane nodes

### ISSUE THREAD

**Issue by kinarashah** [rancher/rke#1734]
Upgrades of the Kubernetes control plane should be handled such that, 

- Control plane nodes should be upgraded 1 node at a time.
- The control plane node should come completely back up before moving to the next. 

https://github.com/rancher/rancher/issues/23038

**Comment by Michaellaneous** [comment]
As a quick question, as I am not entirely sure:
Will this include rancher launched cluster on other infrastructure providers? Will you be able to to the same for worker nodes as well?

**Comment by soumyalj** [comment]
Tested  using RKE version v1.1.0-rc6. 

Some of the test cases executed:

1. Create a RKE cluster with K8s version v1.16.6 using 3 control nodes, 1 etcd and 3 workers. Upgrade k8s version to v1.17.2 in cluster.yml file and perform `./rke up --config cluster.yml` 
Verified that control plane nodes are upgraded one at a time and the node is completely up before moving to the next.
2. Log  in to the control plane nodes and verify that the control node components get upgraded to the correct version. The following components were verified for new version:
a. kube-controller-manager (rancher/hyperkube)
b. kube-apiserver(rancher/hyperkube)
c. kube-scheduler(rancher/hyperkube)

2. Add a new control node in the cluster.yml file and then initiate an upgrade. Upgrade succeeds
3. Remove a control node in the cluster.yml file and then initiate an upgrade. Upgrade succeeds
