### ISSUE TITLE
Volume Hostpath FileOrCreate -> file created as directory, not as file

### ISSUE THREAD

**Issue by joalmjoalm** [rancher/rke#1742]
Volume hostpath is created as directory even if FileOrCreate is in config.
[fileorcreate-test.yaml.txt](https://github.com/rancher/rke/files/3799657/fileorcreate-test.yaml.txt)

**RKE version:**
v0.3.0
Kubernetes version 1.15.4

**Docker version: (`docker version`,`docker info` preferred)**
On kubernetes nodes: Docker version 18.09.9, build 039a7df9ba

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)
kernel 4.15.0-65-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-Metal

**cluster.yml file:**
se attached file
[cluster.yml.txt](https://github.com/rancher/rke/files/3799683/cluster.yml.txt)

**Steps to Reproduce:**
I got the error when creating pods with hostpath w FileOrCreate like the attched example. 

**Results:**
It creates a directory instead of file /tmp/some.conf. 
See also related ticket at https://github.com/kvaps/kube-linstor/issues/4

**Comment by pawanpraka1** [comment]
I am also facing this issue. any plan to fix this?

**Comment by summed** [comment]
Any plan on fixing this?

**Comment by soriaj** [comment]
When creating a Volume with hostPath using the FileOrCreate if nothing exists at the given path, an empty file will be created there as needed with permission set to 0644, having the same group and ownership with Kubelet. In the provided file ```fileorcreate-test.yaml.txt``` the init container is echo'ing to a file in the /etc directory. Once complete the other Pod is running and has a file named some.conf mounted at /tmp within the container. On the host, /tmp/some.conf will be created, though the file will be empty as the init container was writing to a different location.
