### ISSUE TITLE
full-cluster-state configmap is not updated on certificate rotation

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1755]
**RKE version:**
v0.3.2

**Steps to Reproduce:**
Create a cluster with 3 nodes each with all roles, run `rke up`, and run `rke cert rotate`.

**Results:**

The cluster state which is stored in the local `cluster.rkestate` file and the one stored in the configmap `full-cluster-state` are not identical.

Check md5sum of local `cluster.rkestate` (tested on MacOS):

```
echo "$(cat cluster.rkestate)" | md5 
```

Check md5sum of configmap `full-cluster-state` (tested on controlplane node):

```
docker run --rm --net=host -v $(docker inspect kubelet --format '{{ range .Mounts }}{{ if eq .Destination "/etc/kubernetes" }}{{ .Source }}{{ end }}{{ end }}')/ssl:/etc/kubernetes/ssl:ro --entrypoint bash $(docker inspect $(docker images -q --filter=label=org.label-schema.vcs-url=https://github.com/rancher/hyperkube.git) --format='{{index .RepoTags 0}}' | tail -1) -c 'kubectl --kubeconfig /etc/kubernetes/ssl/kubecfg-kube-node.yaml -n kube-system get configmap full-cluster-state -o json | jq -r .data.\"full-cluster-state\" | jq -r .' | md5sum
```

After running `rke up`, the checksums match but it should be done as part of the certificate rotation.

**Comment by sangeethah** [comment]
can be tested with `v1.0.0-rc2`

**Comment by soumyalj** [comment]
Reproduced with rke version v1.0.0.
1. Created a 3 node cluster using `././rke_darwin-amd64-v1.00 up --config clusterdo.yml`
```
2. $ echo "$(cat clusterdo.rkestate)" | md5 
fd52c4e1bc6adf5e026041912f1cb9f6
```
3. Rotate certs using the command :
```./rke_darwin-amd64-v1.00 cert rotate --rotate-ca  --config clusterdo.yml ```

4. Check md5sum of configmap full-cluster-state (tested on controlplane node):

```
docker run --rm --net=host -v $(docker inspect kubelet --format '{{ range .Mounts }}{{ if eq .Destination "/etc/kubernetes" }}{{ .Source }}{{ end }}{{ end }}')/ssl:/etc/kubernetes/ssl:ro --entrypoint bash $(docker inspect $(docker images -q --filter=label=org.label-schema.vcs-url=https://github.com/rancher/hyperkube.git) --format='{{index .RepoTags 0}}' | tail -1) -c 'kubectl --kubeconfig /etc/kubernetes/ssl/kubecfg-kube-node.yaml -n kube-system get configmap full-cluster-state -o json | jq -r .data.\"full-cluster-state\" | jq -r .' | md5sum

```
This results in checksum ```7547f9fdd1652ade373710ba923231e7``` which is different than in the step 2. 

Only after running `rke up` again, the checksums match for step 2 and step 4.


Tested with v1.0.0-rc3. 
1. Created a 3 node cluster using `././rke_darwin-amd64-v1.00-rc3 up --config clusterdo.yml`

2. Rotate certs using the command :
```./rke_darwin-amd64-v1.00-rc3 cert rotate --rotate-ca  --config clusterdo.yml ```

3. Check md5sum of configmap full-cluster-state (tested on controlplane node):

```
docker run --rm --net=host -v $(docker inspect kubelet --format '{{ range .Mounts }}{{ if eq .Destination "/etc/kubernetes" }}{{ .Source }}{{ end }}{{ end }}')/ssl:/etc/kubernetes/ssl:ro --entrypoint bash $(docker inspect $(docker images -q --filter=label=org.label-schema.vcs-url=https://github.com/rancher/hyperkube.git) --format='{{index .RepoTags 0}}' | tail -1) -c 'kubectl --kubeconfig /etc/kubernetes/ssl/kubecfg-kube-node.yaml -n kube-system get configmap full-cluster-state -o json | jq -r .data.\"full-cluster-state\" | jq -r .' | md5sum

```
This results in checksum ```1bce0a03d609996c2e184ea14e6eb516``` which is same as in the step 4
4. echo "$(cat clusterdo.rkestate)" | md5 
1bce0a03d609996c2e184ea14e6eb516
