### ISSUE TITLE
[Feature] Airgap deployments - pull and push images to custom registry

### ISSUE THREAD

**Issue by Patazerty** [rancher/rke#1758]
To ease airgaped deployment, having an option to complement `rke config --system-images` that pulls all needed images and can push them to a custom registry would be a time-saver feature. 

I have implemented just that without adding any dependency and wanted to see if anyone is interested by a PR to add such feature (https://github.com/ObjectifLibre/rke).

Current implementation adds a few options:

`rke config --system-images  --pull` pulls images one by one using the local docker client . `--registry customregistry:5000` pushes the images one by one to the specified registry, tagging them as needed. A `--parallel` option launches all pull and push operation in parallel.

**Comment by pasikarkkainen** [comment]
This sounds like an useful improvement!

**Comment by superseb** [comment]
This is described at https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/populate-private-registry/, is there any benefit to have this in the CLI?
