### ISSUE TITLE
RKE: parallel image pull on all hosts. Parallel worker deployment

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#176]
Today we pull the images to all the nodes sequentially. We should consider doing it in parallel to save the time. Same for worker deployment - once control plane is set, all workers should be deployed in parallel.

**Comment by soumyalj** [comment]
Observed that with rke version 0.0.8-dev the images are being pulled sequentially. 
Tested with rke version 0.0.9-dev, the images are being pulled in parallel and hence cluster creation is faster. 
For a cluster with one node having [controlplane, etcd] and two worker nodes, the time taken to create a cluster for rke version 0.0.8-dev
```
INFO[0216] Finished building Kubernetes cluster successfully 

real	3m37.065s
user	0m2.782s
sys	0m0.421s
```


For rke version 0.0.9-dev
```
INFO[0139] Finished building Kubernetes cluster successfully 

real	2m19.976s
user	0m3.449s
sys	0m0.396s

```
