### ISSUE TITLE
Forwardport: full-cluster-state configmap is not updated on certificate rotation

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#1767]
Forwardport https://github.com/rancher/rke/issues/1755

**Comment by aaronRancher** [comment]
Verified in `v1.0.0`

Created a 3 node cluster each with all roles.
Run `rke up` and `rke cert rotate`.
Check md5sum of local `cluster.rkestate` (tested on MacOS):
```
echo "$(cat cluster.rkestate)" | md5 
```
Result:
`9b7e4ff3b7188b29ec73b349cf44e21f`

Check md5sum of configmap`full-cluster-state` (Tested on controlplane node):
```
docker run --rm --net=host -v $(docker inspect kubelet --format '{{ range .Mounts }}{{ if eq .Destination "/etc/kubernetes" }}{{ .Source }}{{ end }}{{ end }}')/ssl:/etc/kubernetes/ssl:ro --entrypoint bash $(docker inspect $(docker images -q --filter=label=org.label-schema.vcs-url=https://github.com/rancher/hyperkube.git) --format='{{index .RepoTags 0}}' | tail -1) -c 'kubectl --kubeconfig /etc/kubernetes/ssl/kubecfg-kube-node.yaml -n kube-system get configmap full-cluster-state -o json | jq -r .data.\"full-cluster-state\" | jq -r .' | md5sum
``` 
Result:
`9b7e4ff3b7188b29ec73b349cf44e21f`

The results are identical. The configmap is updated on certificate rotation.
