### ISSUE TITLE
RancherOS /etc/kubernetes deleted after restart.

### ISSUE THREAD

**Issue by zeppelinux** [rancher/rke#178]
**RKE version:**
v0.0.8-dev
**Docker version: (`docker version`,`docker info` preferred)**
Client:
Version: 17.03.2-ce
API version: 1.27
Go version: go1.7.5
Git commit: f5ec1e2
Built: Tue Jun 27 02:21:36 2017
OS/Arch: linux/amd64

Server:
Version: 17.03.2-ce
API version: 1.27 (minimum version 1.12)
Go version: go1.7.5
Git commit: f5ec1e2
Built: Tue Jun 27 02:21:36 2017
OS/Arch: linux/amd64
Experimental: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
RancherOS 1.1.1 on Bare-metal 
**cluster.yml file:**
nodes:

address: 192.168.2.208
user: rancher
role: [controlplane]
address: 192.168.2.216
user: rancher
role: [worker]
address: 192.168.2.7
user: rancher
role: [etcd]
services:
etcd:
image: quay.io/coreos/etcd:latest
kube-api:
image: rancher/k8s:v1.8.5-rancher2
kube-controller:
image: rancher/k8s:v1.8.5-rancher2
scheduler:
image: rancher/k8s:v1.8.5-rancher2
kubelet:
image: rancher/k8s:v1.8.5-rancher2
extra_args:
fail-swap-on: false
kubeproxy:
image: rancher/k8s:v1.8.5-rancher2
**Steps to Reproduce:**
Execute ./rke up for the set of hosts where one (or more) are RancherOS host.
Observe it joined the cluster. 
Reboot the RancherOS host.

**Results:**
Kubernetes configuration wiped out after RancherOS host reboot, i.e. the /etc/kubernetes directory is deleted. Kubelet fails with

error: failed to run Kubelet: invalid kubeconfig: stat /etc/kubernetes/ssl/kubecfg-kube-node.yaml: no such file or directory

**Comment by galal-hussein** [comment]
That's because rancherOS only persist user volumes (/home, /opt) during restarts, please refer to the documentation for more information http://rancher.com/docs/os/v1.1/en/system-services/system-docker-volumes/#user-volumes

**Comment by galal-hussein** [comment]
As a workaround you can still upgrade your version of ROS with the user volumes you specify:
ros os upgrade -i rancher/os:v1.1.1 --append "rancher.services.user-volumes.volumes=[/home:/home,/opt:/opt,/var/lib/kubelet:/var/lib/kubelet,/etc/kubernetes:/etc/kubernetes]

**Comment by zeppelinux** [comment]
Upgraded the ROS and restarted. 
/etc/kubernetes is there now but it's empty, so it is the same error.
Anything else i can try?

**Comment by galal-hussein** [comment]
@zeppelinux /etc/kubernetes now should be persisted, you can try redeploying kubernetes and check again.

**Comment by zeppelinux** [comment]
Redeployed kubernetes, this is what i see now:

$sudo ros config export
...
rancher:
  environment:
    EXTRA_CMDLINE: /init
  services:
    user-volumes:
      volumes:
      - /home:/home
      - /opt:/opt
      - /var/lib/kubelet:/var/lib/kubelet
      - /etc/kubernetes:/etc/kubernetes
...
$sudo reboot

/etc/kubernetes is empty

**Comment by zeppelinux** [comment]
Created issue for RancherOS https://github.com/rancher/os/issues/2188
