### ISSUE TITLE
CoreDNS deployment scale should be more than 1

### ISSUE THREAD

**Issue by shubb30** [rancher/rke#1821]
**RKE version:** 1.0

**Docker version: (`docker version`,`docker info` preferred)** 18.09.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 18.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**  ESXi VM

**Steps to Reproduce:**
Use RKE to deploy a 3-node cluster with all roles on all 3 nodes.
Once Kubernetes is running, find out which node the `coredns` pod is running on.
Shut down the node that is running coredns.

**Results:**
Kubernetes will not re-deploy the `coredns` pod to another node, and all DNS services for the cluster will stop working.

The default scale for the coredns deployment should be more than 1, so that DNS will keep working if the node running the service goes down.

**Comment by superseb** [comment]
Please specify what k8s cluster version you are using. This was validated in https://github.com/rancher/rke/issues/1625

**Comment by shubb30** [comment]
Our clusters are all 1.15.5.

**Comment by superseb** [comment]
Okay, the directive for avoid single point of failure in dns autoscaler was added in k8s v1.16 and higher. If you want to achieve the same result you can manually patch the autoscaler/deployment.
