### ISSUE TITLE
/lib/modules bind mount for kube-proxy incorrectly points to /opt/rke/lib/modules on RancherOS

### ISSUE THREAD

**Issue by bensallen** [rancher/rke#1823]
**RKE version:**
Testing with v1.0.0, but relevant code doesn't appear changed for v1.1.0 or master.

**Docker version: (`docker version`,`docker info` preferred)**
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:49:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:55:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
$ cat /etc/os-release
NAME="RancherOS"
VERSION=v1.5.4
ID=rancheros
ID_LIKE=
VERSION_ID=v1.5.4
PRETTY_NAME="RancherOS v1.5.4"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```

```
$ uname -r
4.14.138-rancher
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
```
...
services:
    kubeproxy:
      extra_args:
        proxy-mode: "ipvs"
...
```

**Steps to Reproduce:**

Provision a cluster on RancherOS with the cluster.yml enabling ipvs proxy-mode via extra_args.

**Results:**

RKE added the bind the mount of prefixPath + /lib/modules to /lib/modules inside of the kube-proxy container in #1724. For RancherOS hosts prefixPath resolves to /opt/rke, so this bind mount ends up being:

```
            {
                "Type": "bind",
                "Source": "/opt/rke/lib/modules",
                "Destination": "/lib/modules",
                "Mode": "z,ro",
                "RW": false,
                "Propagation": "rprivate"
            },
```

/opt/rke/lib/modules is an empty directory in RancherOS and thus the kube-proxy container cannot load the needed modules for IPVS, so it fails back to iptables:

```
E1211 22:34:18.242133   22707 server_others.go:339] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs_rr ip_vs_wrr ip_vs_sh ip_vs]
```

Possible workarounds:
- Load the needed kernel modules at boot via cloud-init file.
- Symlink or bind mount /usr/lib/modules to /opt/rke/lib/modules at boot time

Potential fix:
- At https://github.com/rancher/rke/blob/master/cluster/plan.go#L654, do not consider the prefix, always bind mount /lib/modules to /lib/modules. I'm unaware of any systems that store their modules at a different path or at least provide a symlink at /lib/modules.

cc @prachidamle, @alena1108

**Comment by deniseschannon** [comment]
Available in v1.0.1-rc3 and v1.1.0-rc3

**Comment by izaac** [comment]
I was able to reproduce in the latest 1.0 release. And I validated the `/lib/modules` is not empty in `v1.0.1-rc3`

I will check `v1.1.0-rc3` today too.

**Comment by izaac** [comment]
I checked `v1.0.1-rc3` and `v1.1.0-rc3` in RancherOS 1.5.4 both `kube-proxy` containers are able to access the kernel modules now which wasn't possible in `v1.1`

I also tested Ubuntu 18.04.3 in `v1.1`, `v1.0.1-rc3` and `v1.1.0-rc3` in all three the `kube-proxy` was able to access the modules via `/lib/modules`
