### ISSUE TITLE
ssh_cert_path does not work

### ISSUE THREAD

**Issue by patrick0057** [rancher/rke#1828]
**RKE version:**
v1.0.0
**Docker version: (`docker version`,`docker info` preferred)**
N/A
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
N/A
**cluster.yml file:**
```
nodes:
- address: 192.168.xxx.x
user: user
role: [controlplane,etcd,worker]
ssh_key_path: /home/user/.ssh/id_rsa
ssh_cert_path: /home/user/.ssh/id_rsa-cert.pub

services:
etcd:
snapshot: true
creation: 6h
retention: 24h
kube-api:
always_pull_images: true
```
**Steps to Reproduce:**
Attempt rke up using ssh_cert_path configuration outlined in the previous section.

**Results:**
Observe that it fails to login.
```
DEBU[0000] Host: 192.168.xxx.x has role: controlplane
DEBU[0000] Host: 192.168.xxx.x has role: etcd
DEBU[0000] Host: 192.168.xxx.x has role: worker
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [192.168.xxx.x]
DEBU[0000] Connecting to Docker API for host [192.168.xxx.x]
WARN[0000] Failed to set up SSH tunneling for host [192.168.xxx.x]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access the service on /var/run/docker.sock. The service might be still starting up. Error: ssh: rejected: connect failed (open failed)
WARN[0000] Removing host [192.168.xxx.x] from node lists
FATA[0000] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [192.168.xxx.x]
```

**Comment by superseb** [comment]
@patrick0057 Can you please provide steps to reproduce? If I break my SSH cert auth setup, I get the error: ```Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain```

The error `open failed` usually refers to Docker socket permissions or some sort (see https://rancher.com/docs/rke/latest/en/troubleshooting/ssh-connectivity-errors/#failed-to-dial-to-var-run-docker-sock-ssh-rejected-administratively-prohibited-open-failed)

I can run some more tests but if you have the setup or steps to reproduce, that speeds up the process.

**Comment by bravurasteve** [comment]
I get the same error on CentOS 7.7.1908 on bare metal with kernel 5.4.5-1.el7.elrepo.x86_64. My setup is below.
cluster.yml:
`
nodes:
    - address: 10.x.x.x
      user: rke
      role:
        - controlplane
        - etcd
        - worker
ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: true
`
ssh server version:  openssh-server 7.4p1-21.el7
ssh client version: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
/etc/ssh/sshd_config:
`
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
SyslogFacility AUTHPRIV
AuthorizedKeysFile      .ssh/authorized_keys
PasswordAuthentication yes
ChallengeResponseAuthentication no
GSSAPIAuthentication yes
GSSAPICleanupCredentials no
UsePAM yes
AllowAgentForwarding yes
AllowTcpForwarding yes
X11Forwarding yes
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
Subsystem       sftp    /usr/libexec/openssh/sftp-server
`
/home/rke/.ssh/known_hosts:
`10.x.x.x ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMui214UDHvSsuX48taqYnD6iz5nBZ66Q9FZooUDLjNf2gT9cVzDUF5rPDGyArhHeNETu49/CM+hlu1UUPD/j4c=
localhost ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMui214UDHvSsuX48taqYnD6iz5nBZ66Q9FZooUDLjNf2gT9cVzDUF5rPDGyArhHeNETu49/CM+hlu1UUPD/j4c=
127.0.0.1 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMui214UDHvSsuX48taqYnD6iz5nBZ66Q9FZooUDLjNf2gT9cVzDUF5rPDGyArhHeNETu49/CM+hlu1UUPD/j4c=
`
ssh -v rke@10.x.x.x:
`
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug1: Connecting to 10.x.x.x [10.x.x.x] port 22.
debug1: Connection established.
debug1: identity file /home/rke/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rke/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rke/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rke/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rke/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rke/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rke/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rke/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 10.x.x.x:22 as 'rke'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256 need=64 dh_need=64
debug1: kex: curve25519-sha256 need=64 dh_need=64
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:TbXXpDXmQ2zsWcH+cqQIkrgmqI4fz50sApYwEyqICdE
debug1: Host '10.x.x.x' is known and matches the ECDSA host key.
debug1: Found key in /home/rke/.ssh/known_hosts:1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Next authentication method: gssapi-keyex
debug1: No valid Key exchange context
debug1: Next authentication method: gssapi-with-mic
debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: KEYRING:persistent:1001)

debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: KEYRING:persistent:1001)

debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/rke/.ssh/id_rsa
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
Enter passphrase for key '/home/rke/.ssh/id_rsa':
debug1: Authentication succeeded (publickey).
Authenticated to 10.x.x.x ([10.x.x.x]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
Last login: Thu Jan  2 06:00:36 2020 from 10.x.x.x
Agent pid 6779
`

**Comment by superseb** [comment]
@bravurasteve This is regarding using `ssh_cert_path` which activates SSH CA certificates, it seems you do not have this configuration enabled. Please share more info on this or create a new issue with the RKE debug logging from `rke up`.

**Comment by bravurasteve** [comment]
@superseb I'm not sure what you mean by the configuration isn't enabled, since as you can see above the rke user can ssh using certs. Please advise.

**Comment by superseb** [comment]
If you want to use SSH CA certificates, you have to specify the certificate using the `ssh_cert_path` directive in the `cluster.yml` file.

Your `cluster.yml` only shows using `ssh_key_path`.

**Comment by bravurasteve** [comment]
@superseb I added `ssh_cert_path` but got the same error.  See below.

**_cluster.yml_**:
```nodes:
    - address: 10.x.x.x
      user: rke
      role:
        - controlplane
        - etcd
        - worker
ssh_cert_path: ~/.ssh/id_rsa.pub
ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: true```

```rke -d up
INFO[0000] Running RKE version: v1.0.0
DEBU[0000] Parsing cluster file [nodes:
    - address: 10.x.x.x
      user: rke
      role:
        - controlplane
        - etcd
        - worker
ssh_cert_path: ~/.ssh/id_rsa.pub
ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: true
]
DEBU[0000] audit log policy found in cluster.yml
INFO[0000] Initiating Kubernetes cluster
DEBU[0000] No DNS provider configured, setting default based on cluster version [1.16.3-rancher1-1]
DEBU[0000] DNS provider set to [coredns]
DEBU[0000] Host: 10.x.x.x has role: controlplane
DEBU[0000] Host: 10.x.x.x has role: etcd
DEBU[0000] Host: 10.x.x.x has role: worker
DEBU[0000] [state] previous state not found, possible legacy cluster
INFO[0000] [dialer] Setup tunnel for host [10.x.x.x]
DEBU[0000] Connecting to Docker API for host [10.x.x.x]
DEBU[0000] using "/tmp/ssh-NH3dnk8KmjgI/agent.36999" SSH_AUTH_SOCK
DEBU[0000] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
WARN[0000] Failed to set up SSH tunneling for host [10.x.x.x]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Unable to access node with address [10.x.x.x22] using SSH. Please check if you are able to SSH to the node using the specified SSH Private Key and if you have configured the correct SSH username. Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
WARN[0000] Removing host [10.x.x.x] from node lists
WARN[0000] [state] can't fetch legacy cluster state from Kubernetes: ```

So, how does the minimal clluster.yml work in the offiical docs, if certs are not used?

**Comment by superseb** [comment]
Please confirm you are actually using SSH CA Certificates, you can find how that should be configured on https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-creating_ssh_ca_certificate_signing-keys. From there, we can work on if you need the setting or not. Most of the settings needed for SSH CA Certificates don't seem to be present in your configuration.

Please also share the output of `echo ~` and `ssh-add -L` in the same shell you are running `rke up`.

**Comment by patrick0057** [comment]
@superseb 

**Steps to reproduce:**
Run rke up with posted cluster.yml in opening post.

**SSH Server Version:**
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n 7 Dec 2017

**SSH Client Version:**
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n 7 Dec 2017

**sshd_config file contents:**
```
# $OpenBSD: sshd_config,v 1.101 2017/03/14 07:19:07 djm Exp $

# This is the sshd server system-wide configuration file. See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented. Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
PermitRootLogin without-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# Expect .ssh/authorized_keys2 to be disregarded by default in future.
#AuthorizedKeysFile .ssh/authorized_keys .ssh/authorized_keys2

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication no
#PermitEmptyPasswords no

# Change to yes to enable challenge-response passwords (beware issues with
# some PAM modules and threads)
ChallengeResponseAuthentication no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication. Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
UsePAM yes

#AllowAgentForwarding yes
AllowTcpForwarding yes
#GatewayPorts no
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
PrintMotd no
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
PermitTunnel yes
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

# override default of no subsystems
Subsystem sftp /usr/lib/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
# X11Forwarding no
# AllowTcpForwarding no
# PermitTTY no
# ForceCommand cvs server

# Vault Trusted Public Keys
TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pem
```




**known_hosts file contents:**
```
...
|1|3hqpbwkJP0IgGnSiz2sFUn4SnRs=|l2zdPGp90FyQ/Lk6Dcpoa2MrPS0= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBML5jVDpDSjqLQoN6rbjEhjAaq/fg7h5wwWF9EUWo8F3vAi4KILwL5O60/VWE5nhDHOxo2HPG4YS5H7Qjy4h9Z4=
```

**output of ssh -v user@host of a successful connection with the same config as RKE**
```
<user id>@ubuntu:~$ ssh -v -i ~/.ssh/id_rsa -i ~/.ssh/id_rsa-cert.pub ubuntu@192.168.160.172
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n 7 Dec 2017
debug1: Reading configuration data /home/<user id>/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 192.168.160.172 [192.168.160.172] port 22.
debug1: Connection established.
debug1: identity file /home/<user id>/.ssh/id_rsa type 0
debug1: identity file /home/<user id>/.ssh/id_rsa-cert type 4
debug1: identity file /home/<user id>/.ssh/id_rsa-cert.pub type 4
debug1: key_load_public: No such file or directory
debug1: identity file /home/<user id>/.ssh/id_rsa-cert.pub-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.160.172:22 as 'ubuntu'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:4o2lcFWY8CGlQC7MLvkjo4BE3uMoGLIPRoSxrGzXIGk
debug1: Host '192.168.160.172' is known and matches the ECDSA host key.
debug1: Found key in /home/<user id>/.ssh/known_hosts:103
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:yFH8vO6jT4tZdq/T4x1vF2MjpN1yr8KL2cXHdx0xaDw /home/<user id>/.ssh/id_rsa
debug1: Authentications that can continue: publickey
debug1: Offering public key: RSA-CERT SHA256:yFH8vO6jT4tZdq/T4x1vF2MjpN1yr8KL2cXHdx0xaDw /home/<user id>/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa-cert-v01@openssh.com blen 1813
debug1: Authentication succeeded (publickey).
Authenticated to 192.168.160.172 ([192.168.160.172]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 5.0.0-25-generic x86_64)

* Documentation: https://help.ubuntu.com
* Management: https://landscape.canonical.com
* Support: https://ubuntu.com/advantage
Last login: Mon Jan 6 17:45:14 2020 from 192.168.160.219
$ exit
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Connection to 192.168.160.172 closed.
Transferred: sent 7124, received 4752 bytes, in 8.7 seconds
Bytes per second: sent 814.6, received 543.4
debug1: Exit status 0
```

**Comment by superseb** [comment]
@patrick0057 Can you please add the contents of `/var/log/auth.log` on the server that is being connected to, both when `ssh` manually succeeds and `rke up` fails.
