### ISSUE TITLE
OSX: make -> ./rke: cannot execute binary file

### ISSUE THREAD

**Issue by nseyvet** [rancher/rke#183]
**RKE version:**
From master

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: 2XAG:3PLF:IIPC:6GAE:6LVW:N42I:TOJS:KFLH:S2VP:RNQI:RYXL:3TQJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 31
 System Time: 2017-12-22T13:58:29.308608384Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
OSX 16.7.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
N/A
**cluster.yml file:**
Not required to reproduce.

**Steps to Reproduce:**
On OSX, try to build rke from source.
git clone https://github.com/rancher/rke.git
cd rke
./make

**Results:**
./.dapper ci
Sending build context to Docker daemon  26.91MB
Step 1/18 : FROM ubuntu:16.04
 ---> 00fd29ccc6f1
Step 2/18 : ARG DAPPER_HOST_ARCH
 ---> Using cache
 ---> 805645fcf9f3
Step 3/18 : ENV HOST_ARCH ${DAPPER_HOST_ARCH} ARCH ${DAPPER_HOST_ARCH}
 ---> Using cache
 ---> 5f87008e05c8
Step 4/18 : RUN apt-get update &&     apt-get install -y gcc ca-certificates git wget curl vim less file kmod iptables &&     rm -f /bin/sh && ln -s /bin/bash /bin/sh
 ---> Using cache
 ---> 8e696b6afdca
Step 5/18 : ENV GOLANG_ARCH_amd64 amd64 GOLANG_ARCH_arm armv6l GOLANG_ARCH GOLANG_ARCH_${ARCH} GOPATH /go PATH /go/bin:/usr/local/go/bin:${PATH} SHELL /bin/bash
 ---> Using cache
 ---> 76caef2f9079
Step 6/18 : RUN wget -O - https://storage.googleapis.com/golang/go1.8.3.linux-${!GOLANG_ARCH}.tar.gz | tar -xzf - -C /usr/local &&     go get github.com/rancher/trash && go get github.com/golang/lint/golint
 ---> Using cache
 ---> 46611d521af7
Step 7/18 : ENV DOCKER_URL_amd64 https://get.docker.com/builds/Linux/x86_64/docker-1.10.3 DOCKER_URL_arm https://github.com/rancher/docker/releases/download/v1.10.3-ros1/docker-1.10.3_arm DOCKER_URL DOCKER_URL_${ARCH}
 ---> Using cache
 ---> 0d16cc867a93
Step 8/18 : RUN wget -O - ${!DOCKER_URL} > /usr/bin/docker && chmod +x /usr/bin/docker
 ---> Using cache
 ---> c7ec7c6705b4
Step 9/18 : ENV DAPPER_SOURCE /go/src/github.com/rancher/rke/
 ---> Using cache
 ---> 7bcf61df6bc0
Step 10/18 : ENV DAPPER_RUN_ARGS --privileged -v /var/lib/docker
 ---> Using cache
 ---> 5be4a30ba974
Step 11/18 : ENV DAPPER_OUTPUT ./bin ./dist ./build/bin
 ---> Using cache
 ---> 923378b2ec08
Step 12/18 : ENV DAPPER_DOCKER_SOCKET true
 ---> Using cache
 ---> 2531f4ea9840
Step 13/18 : ENV DAPPER_ENV TAG REPO GOOS CROSS
 ---> Using cache
 ---> e46d8a1c0bee
Step 14/18 : ENV TRASH_CACHE ${DAPPER_SOURCE}/.trash-cache
 ---> Using cache
 ---> 8c513646e0ae
Step 15/18 : ENV HOME ${DAPPER_SOURCE}
 ---> Using cache
 ---> 9cc5adff53ac
Step 16/18 : WORKDIR ${DAPPER_SOURCE}
 ---> Using cache
 ---> cbe3d0c1f9de
Step 17/18 : ENTRYPOINT ./scripts/entry
 ---> Using cache
 ---> 7ce215ec4493
Step 18/18 : CMD ci
 ---> Using cache
 ---> 89b28ce9e63f
Successfully built 89b28ce9e63f
Successfully tagged rke:master
Sending build context to Docker daemon  26.91MB
Step 1/2 : FROM rke:master
 ---> 89b28ce9e63f
Step 2/2 : COPY . /go/src/github.com/rancher/rke/
 ---> bec9823bb66c
Successfully built bec9823bb66c
Successfully tagged rke:master
Running tests
?   	github.com/rancher/rke	[no test files]
ok  	github.com/rancher/rke/addons	1.682s	coverage: 50.0% of statements
?   	github.com/rancher/rke/authz	[no test files]
?   	github.com/rancher/rke/cluster	[no test files]
?   	github.com/rancher/rke/cmd	[no test files]
?   	github.com/rancher/rke/docker	[no test files]
?   	github.com/rancher/rke/hosts	[no test files]
?   	github.com/rancher/rke/k8s	[no test files]
?   	github.com/rancher/rke/network	[no test files]
ok  	github.com/rancher/rke/pki	9.994s	coverage: 48.4% of statements
ok  	github.com/rancher/rke/services	1.482s	coverage: 29.8% of statements
Running validation
Running: go vet
Running: golint
Running: go fmt
Sending build context to Docker daemon  23.4 MB
Step 1/3 : FROM ubuntu:16.04
 ---> 00fd29ccc6f1
Step 2/3 : COPY rke /usr/bin/
 ---> Using cache
 ---> 4438e671ee03
Step 3/3 : CMD rke
 ---> Using cache
 ---> 5830923586a4
Successfully built 5830923586a4
Successfully tagged rancher/rke:5ac6a22
Built rancher/rke:5ac6a22
INFO[0079] docker cp /go/src/github.com/rancher/rke/bin . 
INFO[0080] docker cp /go/src/github.com/rancher/rke/dist . 
INFO[0080] docker cp /go/src/github.com/rancher/rke/build/bin build

And when trying to run rke:
.$ /rke 
-bash: ./rke: cannot execute binary file

File is properly generated:
$ ls -la
total 45680
drwxr-xr-x   3 xx  staff   102B Dec 22 14:52 ./
drwxr-xr-x  31 xx  staff   1.0K Dec 22 14:52 ../
-rwxr-xr-x   1 xx     staff    22M Dec 22 14:52 rke*

$ docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
rke                                master              bec9823bb66c        9 minutes ago       771MB
<none>                             <none>              d33abb7c52a3        12 minutes ago      771MB
rancher/rke                        5ac6a22             5830923586a4        5 hours ago         134MB
<none>                             <none>              cdd8b1ceecd6        5 hours ago         771MB

**Comment by superseb** [comment]
Use `CROSS=true make` to cross compile for Darwin.

**Comment by nseyvet** [comment]
$ CROSS=true make
CROSS=true make
./.dapper ci
Sending build context to Docker daemon  78.68MB
Step 1/18 : FROM ubuntu:16.04
 ---> 00fd29ccc6f1
Step 2/18 : ARG DAPPER_HOST_ARCH
 ---> Using cache
 ---> 805645fcf9f3
Step 3/18 : ENV HOST_ARCH ${DAPPER_HOST_ARCH} ARCH ${DAPPER_HOST_ARCH}
 ---> Using cache
 ---> 5f87008e05c8
Step 4/18 : RUN apt-get update &&     apt-get install -y gcc ca-certificates git wget curl vim less file kmod iptables &&     rm -f /bin/sh && ln -s /bin/bash /bin/sh
 ---> Using cache
 ---> 8e696b6afdca
Step 5/18 : ENV GOLANG_ARCH_amd64 amd64 GOLANG_ARCH_arm armv6l GOLANG_ARCH GOLANG_ARCH_${ARCH} GOPATH /go PATH /go/bin:/usr/local/go/bin:${PATH} SHELL /bin/bash
 ---> Using cache
 ---> 76caef2f9079
Step 6/18 : RUN wget -O - https://storage.googleapis.com/golang/go1.8.3.linux-${!GOLANG_ARCH}.tar.gz | tar -xzf - -C /usr/local &&     go get github.com/rancher/trash && go get github.com/golang/lint/golint
 ---> Using cache
 ---> 46611d521af7
Step 7/18 : ENV DOCKER_URL_amd64 https://get.docker.com/builds/Linux/x86_64/docker-1.10.3 DOCKER_URL_arm https://github.com/rancher/docker/releases/download/v1.10.3-ros1/docker-1.10.3_arm DOCKER_URL DOCKER_URL_${ARCH}
 ---> Using cache
 ---> 0d16cc867a93
Step 8/18 : RUN wget -O - ${!DOCKER_URL} > /usr/bin/docker && chmod +x /usr/bin/docker
 ---> Using cache
 ---> c7ec7c6705b4
Step 9/18 : ENV DAPPER_SOURCE /go/src/github.com/rancher/rke/
 ---> Using cache
 ---> 7bcf61df6bc0
Step 10/18 : ENV DAPPER_RUN_ARGS --privileged -v /var/lib/docker
 ---> Using cache
 ---> 5be4a30ba974
Step 11/18 : ENV DAPPER_OUTPUT ./bin ./dist ./build/bin
 ---> Using cache
 ---> 923378b2ec08
Step 12/18 : ENV DAPPER_DOCKER_SOCKET true
 ---> Using cache
 ---> 2531f4ea9840
Step 13/18 : ENV DAPPER_ENV TAG REPO GOOS CROSS
 ---> Using cache
 ---> e46d8a1c0bee
Step 14/18 : ENV TRASH_CACHE ${DAPPER_SOURCE}/.trash-cache
 ---> Using cache
 ---> 8c513646e0ae
Step 15/18 : ENV HOME ${DAPPER_SOURCE}
 ---> Using cache
 ---> 9cc5adff53ac
Step 16/18 : WORKDIR ${DAPPER_SOURCE}
 ---> Using cache
 ---> cbe3d0c1f9de
Step 17/18 : ENTRYPOINT ./scripts/entry
 ---> Using cache
 ---> 7ce215ec4493
Step 18/18 : CMD ci
 ---> Using cache
 ---> 89b28ce9e63f
Successfully built 89b28ce9e63f
Successfully tagged rke:master
Sending build context to Docker daemon  78.68MB
Step 1/2 : FROM rke:master
 ---> 89b28ce9e63f
Step 2/2 : COPY . /go/src/github.com/rancher/rke/
 ---> 4812ddadff34
Successfully built 4812ddadff34
Successfully tagged rke:master
Building binary for linux/amd64...
Building binary for darwin/amd64...
Running tests
?   	github.com/rancher/rke	[no test files]
ok  	github.com/rancher/rke/addons	1.557s	coverage: 50.0% of statements
?   	github.com/rancher/rke/authz	[no test files]
?   	github.com/rancher/rke/cluster	[no test files]
?   	github.com/rancher/rke/cmd	[no test files]
?   	github.com/rancher/rke/docker	[no test files]
?   	github.com/rancher/rke/hosts	[no test files]
?   	github.com/rancher/rke/k8s	[no test files]
?   	github.com/rancher/rke/network	[no test files]
ok  	github.com/rancher/rke/pki	9.155s	coverage: 48.4% of statements
ok  	github.com/rancher/rke/services	1.481s	coverage: 29.8% of statements
Running validation
Running: go vet
Running: golint
Running: go fmt
Sending build context to Docker daemon  23.4 MB
Step 1/3 : FROM ubuntu:16.04
 ---> 00fd29ccc6f1
Step 2/3 : COPY rke /usr/bin/
 ---> Using cache
 ---> 4438e671ee03
Step 3/3 : CMD rke
 ---> Using cache
 ---> 5830923586a4
Successfully built 5830923586a4
Successfully tagged rancher/rke:dev
Built rancher/rke:dev
INFO[0149] docker cp /go/src/github.com/rancher/rke/bin . 
INFO[0149] docker cp /go/src/github.com/rancher/rke/dist . 
INFO[0149] docker cp /go/src/github.com/rancher/rke/build/bin build 

So I can see in the build logs:
Building binary for darwin/amd64...

And then:
$ ls -la bin/rke 
-rwxr-xr-x  1 xx  staff    22M Dec 22 15:21 bin/rke*

But same problem:
/github/rke$ ./bin/rke 
-bash: ./bin/rke: cannot execute binary file

**Comment by superseb** [comment]
That binary is used in the `rancher/rke:dev` container, you can look in `build/bin` for the produced binaries for all platforms.

**Comment by nseyvet** [comment]
That worked.

Thank you
