### ISSUE TITLE
kube-apiserver keeps restarting after cert rotation with "Error: enable-admission-plugins plugin "TaintNodesByCondition" is unknown"

### ISSUE THREAD

**Issue by frouzbeh** [rancher/rke#1832]
**RKE version:**
rke v0.1.12 to provision the cluster 
rke v1.0.0 to rotate the certs.

**Docker version: (`docker version`,`docker info` preferred)**
docker info:

```
Containers: 16
 Running: 9
 Paused: 0
 Stopped: 7
Images: 7
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 9c3c5f853ebf0ffac0d087e94daef462133b69c7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-957.21.3.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 40
Total Memory: 251.6 GiB
Name: ma02.hdp1.catalyzecare.org
ID: 4MKH:UIKO:PEOL:5TCU:KVKA:ABKU:4LAM:YIWI:MEBA:UZE3:FN4E:JYSS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), docker.io (secure), registry.fedoraproject.org (secure), quay.io (secure), registry.centos.org (secure), docker.io (secure)

```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
uname -r:
3.10.0-957.21.3.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**

**Steps to Reproduce:**
I provisioned my cluster one year ago using rke v0.1.12, and recently got certification error (which is expired), then based on [this](https://rancher.com/blog/2019/kubernetes-certificate-expiry-and-rotation-in-rancher-kubernetes-clusters/) I tried to rotate the certificates but after that kube-apiserver keeps restarting. This is the error that keeps happening in kube-apiserver:
Error: enable-admission-plugins plugin "TaintNodesByCondition" is unknown

Does anyone have a solution for this problem?

**Comment by Jetman80** [comment]
I have found a workaround.

1. Find full container id of `kube-apiserver`.
```
docker inspect --format="{{.Id}}" kube-apiserver
```
2. Stop docker service on the node.
```
service docker stop
```
3. Open file `/var/lib/docker/containers/xxxxxFULL_IDxxxx/config.v2.json`.
4. Remove all occurrences of `TaintNodesByCondition,`.
5. Save the config and start docker service.
```
service docker start
```
6. Continue with rancher update and [cert rotation](https://rancher.com/blog/2019/kubernetes-certificate-expiry-and-rotation-in-rancher-kubernetes-clusters/).

**Comment by frouzbeh** [comment]
@Jetman80 Thank you so so much, It's working now.
