### ISSUE TITLE
RKE fails to copy `kube-service-account-token-key.pem`

### ISSUE THREAD

**Issue by 2easy** [rancher/rke#1835]
**RKE version:**
1.0.0

When using rke with custom certs, RKE fails to copy kube-service-account-token-key.pem file when corresponding certificate is not present (despite documentation stating that it is not required!!). This results in apiserver HEALTHCHECK error:

`FATA[0159] [controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [10.XXX.XXX.XX]: Get https://localhost:6443/healthz: Unable to access the service on localhost:6443. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: ]`

The container keeps restarting because it cannot find the required file.

**Comment by satish2** [comment]
Yes. I am also hitting this issue.

---------------------------------------------------------------------
Cluster.yml file:
---------------------------------------------------------------------
[rancher@localhost scripts]$ cat cluster.yml
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 10.223.151.137
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
- address: 10.223.151.64
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: /home/rancher/rancher/worker_nodes/worker-node-1-ssh-priv-key

---------------------------------------------------------------------
Custom Certificates I need kubernetes components to use:
---------------------------------------------------------------------
[rancher@localhost scripts]$ ls -l ./cluster_certs/
total 124
-rw-r-----. 1 rancher rancher  976 Feb 20 05:53 kube-admin-csr.pem
-rw-r-----. 1 rancher rancher 1675 Feb 20 05:53 kube-admin-key.pem
-rw-rw-r--. 1 rancher rancher 3936 Feb 20 05:54 kube-admin.pem
-rw-r-----. 1 rancher rancher 1151 Feb 20 05:53 kube-apiserver-csr.pem
-rw-r-----. 1 rancher rancher 1675 Feb 20 05:53 kube-apiserver-key.pem
-rw-rw-r--. 1 rancher rancher 4380 Feb 20 05:54 kube-apiserver.pem
-rw-r-----. 1 rancher rancher  980 Feb 20 05:53 kube-apiserver-proxy-client-csr.pem
-rw-r-----. 1 rancher rancher 1675 Feb 20 05:53 kube-apiserver-proxy-client-key.pem
-rw-rw-r--. 1 rancher rancher 3967 Feb 20 05:54 kube-apiserver-proxy-client.pem
-rw-------. 1 rancher rancher 1704 Feb 20 06:25 kube-apiserver-requestheader-ca-key.pem
-rw-rw-r--. 1 rancher rancher 1298 Feb 20 06:25 kube-apiserver-requestheader-ca.pem
-rw-------. 1 rancher rancher 1704 Feb 20 05:55 kube-ca-key.pem
-rw-rw-r--. 1 rancher rancher 1298 Feb 20 05:55 kube-ca.pem
-rw-r-----. 1 rancher rancher  972 Feb 20 05:53 kube-controller-manager-csr.pem
-rw-r-----. 1 rancher rancher 1675 Feb 20 05:53 kube-controller-manager-key.pem
-rw-rw-r--. 1 rancher rancher 3930 Feb 20 05:54 kube-controller-manager.pem
-rw-r-----. 1 rancher rancher 1143 Feb 20 05:53 kube-etcd-10-223-151-137-csr.pem
-rw-r-----. 1 rancher rancher 1679 Feb 20 05:53 kube-etcd-10-223-151-137-key.pem
-rw-rw-r--. 1 rancher rancher 4368 Feb 20 05:54 kube-etcd-10-223-151-137.pem
-rw-r-----. 1 rancher rancher  976 Feb 20 05:53 kube-node-csr.pem
-rw-r-----. 1 rancher rancher 1679 Feb 20 05:53 kube-node-key.pem
-rw-rw-r--. 1 rancher rancher 3931 Feb 20 05:54 kube-node.pem
-rw-r-----. 1 rancher rancher  952 Feb 20 05:53 kube-proxy-csr.pem
-rw-r-----. 1 rancher rancher 1679 Feb 20 05:53 kube-proxy-key.pem
-rw-rw-r--. 1 rancher rancher 3901 Feb 20 05:54 kube-proxy.pem
-rw-r-----. 1 rancher rancher  960 Feb 20 05:53 kube-scheduler-csr.pem
-rw-r-----. 1 rancher rancher 1679 Feb 20 05:53 kube-scheduler-key.pem
-rw-rw-r--. 1 rancher rancher 3909 Feb 20 05:54 kube-scheduler.pem
-rw-rw-r--. 1 rancher rancher 1679 Feb 20 06:20 kube-service-account-token-key.pem
[rancher@localhost scripts]$

The workaround I found was to manually copy the files under ./cluster_certs to file to /etc/kubernetes/ssl/ and then run "rke up --custom-certs"

**Comment by cygmris** [comment]
+1

**Comment by dalvarin** [comment]
+1 The workaround worked for me. The documentation from https://rancher.com/docs/rke/latest/en/installation/certs/ is confusing since the Service Account Token certificate is required if you are using custom certs. Please, Rancher, could you review the doc?

**Comment by 2easy** [comment]
This is still an issue with v1.2.3
