### ISSUE TITLE
when trying to upgrade k8's with rke 1.0.0 seeing issues where docker container isn't starting up.

### ISSUE THREAD

**Issue by richyta** [rancher/rke#1836]
**RKE version:**
1.0.0

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
*Note: address and user info removed.

nodes:
  - address: 
    internal_address: 
    user: 
    ssh_key_path: ~/.ssh/dev/dev-rancher.pem
    role: [controlplane,worker,etcd]
  - address: 
    internal_address: 
    user: 
    ssh_key_path: ~/.ssh/dev/dev-rancher.pem
    role: [controlplane,worker,etcd]
  - address: 
    internal_address: 
    user: 
    ssh_key_path: ~/.ssh/dev/dev-rancher.pem
    role: [controlplane,worker,etcd]

kubernetes_version: "v1.16.3-rancher1-1"

services:
  etcd:
    snapshot: true
    creation: 4h
    retention: 48h

**Steps to Reproduce:**
rke up --config rancher-cluster.yml  

**Results:**
<img width="1273" alt="Screen Shot 2019-12-17 at 10 52 08 AM" src="https://user-images.githubusercontent.com/39923752/71027340-eae5ea00-20bf-11ea-9569-15760d50ff43.png">

<img width="1273" alt="Screen Shot 2019-12-17 at 10 52 08 AM" src="https://user-images.githubusercontent.com/39923752/71027427-1bc61f00-20c0-11ea-9900-872b558f6bd8.png">

<img width="1232" alt="Screen Shot 2019-12-17 at 10 54 26 AM" src="https://user-images.githubusercontent.com/39923752/71027457-2c769500-20c0-11ea-9a56-32bc799d0d8f.png">

**Comment by superseb** [comment]
See https://github.com/rancher/rke/issues/1760#issuecomment-552407765
