### ISSUE TITLE
Cluster.yml and user

### ISSUE THREAD

**Issue by CarlosEsco** [rancher/rke#1840]
Generic question about cluster.yml and users.

1.  user A setups a cluster.yml with his user id and then runs rke up
2.  user B modifies cluster.yml and puts his user id as user then runs rke up

Should this work?  Or does it require a system account and user cannot change?

I am getitng an error cluster must have at least once etcd plane host.  failed to connect ot following etcd hosts [myip].

**Comment by superseb** [comment]
The SSH connection is established to connect to the Docker socket, those are the only requirements. Personally I wouldn't depend on changing user IDs (and keys) I guess, but I dont see a technical issue for it not to work. Please post the exact error (or full log).

**Comment by CarlosEsco** [comment]
Switched to a system account.  So didnt have time to retry this.  On retry it seems to be working fine now.  Must have been some setup error on my side
