### ISSUE TITLE
Cluster with one worker has unschedulable CoreDNS pod

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1843]
**RKE version:**
seen in Rancher `master-head`

**Steps to Reproduce:**
Create a cluster with one worker

**Results:**
CoreDNS will scale to 2 because of `preventSinglePointFailure:true` but it counts all nodes and not just the schedulable nodes (workers), so in case of 1 worker, it scales to two but the other pod can't be scheduled due to anti affinity to itself.

**Comment by kinarashah** [comment]
Note for QA: This is not RKE CLI specific, it's related to a template change in CoreDNS for k8s 1.17, so applies to Rancher as well.

**Comment by sowmyav27** [comment]
**On rancher:v2.3.3**

- k8s version - 1.17.0-rancher1-1
- Cluster spec - 1 etcd/control plane, and 1 worker node
- Do rke cluster
- core DNS workload has 2 pods, and both are scheduled on the worker node. 

**On 2.3-head commit id: `ed6537bfa`**

- k8s version - 1.17.0-rancher1-2
- Cluster spec - 1 etcd/control plane, and 1 worker node
- Do rke cluster
- core DNS workload has 1 pod, on the worker node.

**Comment by sangeethah** [comment]
on master-head , commit id: `ded40b260`

k8s version - 1.17.0-rancher1-2
luster spec - 1 etcd/control plane, and 1 worker node
Do rke cluster
core DNS workload has 1 pod, on the worker node.
core dns autoscaler deployment has the following node labels set -

`"--nodelabels=node-role.kubernetes.io/worker=true,beta.kubernetes.io/os=linux"`
