### ISSUE TITLE
Has been pending since import 

### ISSUE THREAD

**Issue by huyifanstar** [rancher/rke#1859]
rke Version:  0.28
docker version: 18.09.2
kubernetes version:  v1.14.6-rancher1-1
ubuntu version:  18.04
==================================
Describe your issue here Kubernetes initialized by rke Docker Version: 18.09.2

pending for hours

![image](https://user-images.githubusercontent.com/15685376/71428552-61a46800-26fc-11ea-8dbe-707c7e0181ce.png)

![image](https://user-images.githubusercontent.com/15685376/71428554-6537ef00-26fc-11ea-90bd-47c322c2accf.png)

![image](https://user-images.githubusercontent.com/15685376/71428556-68cb7600-26fc-11ea-9644-c9d82723b6e5.png)

![image](https://user-images.githubusercontent.com/15685376/71428628-dc6d8300-26fc-11ea-85be-32101b412016.png)

**Comment by superseb** [comment]
Please provide the info requested in https://github.com/rancher/rancher/issues/24757

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/24757
