### ISSUE TITLE
Can i use different image for kube component

### ISSUE THREAD

**Issue by jamroks** [rancher/rke#187]
Hi,
 
 i was wondering if it's possible to kubernetes component image from other source than rancher repo docker image. 
for instance in example given in this repo this image is used  : 
  kube-api: 
    image: rancher/k8s:v1.8.3-rancher2

can i replace it with : 
  kube-api: 
    image: gcr.io/google_containers/kube-apiserver:v1.9.0

to be clear is that i absolutely need to replace rancher image, but i like the idea that it's do-able and everything in the cluster still work as expected . 

thanks

**Comment by galal-hussein** [comment]
@jamroks yes you can replace the rancher image with any kubernetes image as long as it has kubernetes binaries

**Comment by almorelle** [comment]
Hi,

Could you explain what differences there is between your image build and other's with kube binaries?

Thanks
