### ISSUE TITLE
Remote cluster state file

### ISSUE THREAD

**Issue by dje4om** [rancher/rke#1873]
Hi all,
The approach that RKE offers is really nice, and what would be really interesting would be to be able to store the rke cluster state file remotely to facilitate collaboration as terraform allows it on the same basis of state management.
Also, because it stores secrets, we would like to be able to store it on a secure storage space.
Does it make sense as a feature request ?

**Comment by rui-su-bnet** [comment]
Bump!

**Comment by tboerger** [comment]
Is there any chance to get this integrated? I would also volunteer to help on that.

**Comment by mitchellmaler** [comment]
If you use the Terraform RKE provider you can store the state with your terraform state
https://github.com/rancher/terraform-provider-rke

**Comment by tboerger** [comment]
I would like to store the state remotely without terraform. Terraform is building my infrastructure, but the rest is done by ansible.

**Comment by dje4om** [comment]
Like @tboerger , we moved to the terraform provider to resolve this, with benefits of terraform like secrets management with vault provider, etc ...
The disadvantage is rke release must be port to terraform rke provider, for example, rke 1.2.1 was release 14 days ago and still not available in terraform provider at this time, (previous drift was 3 days).
However, I must admit the terraform workflow is very nice with rke provider.
The native feature could be nice and not so painful to implement but i didn't have go skills for now, I probably can help in other ways
