### ISSUE TITLE
Add support for user addons as URLs to yaml manifests.

### ISSUE THREAD

**Issue by moelsayed** [rancher/rke#190]
We need to allow uses to define addons as URLs in addition to inline manifests, for example:
```
addons_include:
- https://example.com/my.yaml
- https://example.com/another.yaml
```

**Comment by rossedman** [comment]
@moelsayed Wanted to open another issue for local files as well. Could this be a similar feature?

```
addons_include:
- ./manifests/something.yaml
- ./manifests/another.yaml
```

**Comment by dahendel** [comment]
I am interested in working on this if work has not been done already but not sure the best way to proceed as we would need a new field in [rke_types](https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/rke_types.go#L13)  which appears to be generated.

**Comment by dahendel** [comment]
Here is my code to handle [urls and paths](https://github.com/dahendel/rke/blob/addons_include/cluster/addons.go#L57). I added AddonsInclude to rancher/types that will be another pull request. Built it locally by adding AddonsInclude []string to the RancherKubernetesEngineConfig in the vendor directory

**Comment by moelsayed** [comment]
@dahendel Thank you for the PR, can you also send a rancher/rke PR ? We will review and merge as soon as possible.

**Comment by rossedman** [comment]
@dahendel should json so be included in the types? Do we see a situation where someone is piping in machine generated manifests? Awesome start!

**Comment by dahendel** [comment]
I will get json added in the rke types in the morning.

**Comment by moelsayed** [comment]
Works as expected with a minor issue if the any of the included manifests after the first one doesn't start with `---`. 

#440 should fix this.
