### ISSUE TITLE
Recommended minimal OS (question)

### ISSUE THREAD

**Issue by ghost** [rancher/rke#1904]
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Currently CoreOS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
ESXi single instance with 3 VMs as RKE nodes

Since CoreOS has been working fine as RKE nodes for me so far, but the EOL is set to May 2020 https://twitter.com/ibuildthecloud/status/1225167982394888192?s=21 I was wondering which OSs besides Ubuntu you guys are recommending for BareMetal setups.

It feels to me like Ubuntu has a lot of overhead as a K8s node. I am wrong?
The development for RancherOS and PhotonOS looks a bit stale since a few weeks/months.
K3OS is not meant to be running as RKE nodes, right?
I had difficulties running Centos because of security restrictions of the OS (but that was over a year ago and I did not put too much work in figuring out the problems)
Has anybody already tested Fedoras CoreOS?
Any other distros that are lightweight and support RKE?

If it comes down to Ubuntu anyways, is 16.04 the recommended version or should I be fine with using 18.04 LTS?

If I would go do the path of K3s running on K3OS, is it possible and recommended to run a rancher/rancher cluster inside a K3s cluster?

Oh and: RKE is a nice peace of engineering! We are running an RKE dev cluster now for months and there where no major issues what so ever 🥰 Updates are ridiculously easy and fast! (Every time I update some settings for nodes I end up saying out loud “What? That’s it?”)

**Comment by mitchellmaler** [comment]
@Gregohr If you check our the [Rancher 2.4 wiki](https://github.com/rancher/rancher/wiki/Rancher-2.4) they will be supporting K3S clusters.

**Comment by superseb** [comment]
This information can be found on https://rancher.com/docs/rancher/v2.x/en/installation/requirements/
