### ISSUE TITLE
Getting a 'Can't access KubeAPI port [6443] on Control Plane host' error

### ISSUE THREAD

**Issue by john-morsley** [rancher/rke#1905]
RKE version: v1.0.4

Docker version: Docker version 19.03.5, build 633a0ea838

Operating system and kernel:

4.15.0-1057-aws

AME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Type/provider of hosts: AWS

Steps to Reproduce:

Hi,
After trying to follow Adrian Goins' video 'How Long Does Rancher Really Take?', I get the following error when I try and 'rke up'.
Can anyone cast any light on this?
Many thanks,
John 

Results:

FATA[0014] [network] Can't access KubeAPI port [6443] on Control Plane host

cluster.yml:

[cluster.yml.txt](https://github.com/rancher/rke/files/4171624/cluster.yml.txt)

docker-info:

[docker-info.txt](https://github.com/rancher/rke/files/4171642/docker-info.txt)

**Comment by superseb** [comment]
The required ports are described on https://rancher.com/docs/rke/latest/en/os/#ports, are these opened on the network/host firewall?

**Comment by superseb** [comment]
Let us know if this needs more help

**Comment by john-morsley** [comment]
Thank @superseb, work was blocking this port!

**Comment by mostafaghadimi** [comment]
Adding this argument does not resolve the problem but can skip it: `--disable-port-check`
