### ISSUE TITLE
Zero Down: Add label to ignore nodes

### ISSUE THREAD

**Issue by maggieliu** [rancher/rke#1906]
RKE should allow users to label certain nodes so that they're not included in the upgrade process

**Comment by mrajashree** [comment]
Available with v1.1.0-rc7

**Comment by mrajashree** [comment]
RKE up should accept label on v1.Node so that it ignores that node during upgrade.
The nodes which should be left out of upgrade should have the following label:
```
rke.cattle.io/ignore-during-upgrade=true
```
Users can label the v1.Node using following command:
```
k label node  nodename "rke.cattle.io/ignore-during-upgrade=true"
```

**Comment by mrajashree** [comment]
The updated label we'll use is `user.cattle.io/upgrade-policy=prevent`

**Comment by mrajashree** [comment]
available with rc10

**Comment by soumyalj** [comment]
Tested with rke version: v1.1.0-rc11. Feature to add  a label to ignore nodes is functional. 
Tested the below scenarios:
**Use case 1:**
**Setup:
3 control nodes(C1, C2, C3), 1 etcd, 2 workers             
max_Unavailable_controlplane = 1**  
1. Create a rke cluster using  “./rke up --config  cluster.yml”  command. Specify k8s version as v1.15.5 for example
2. Power off C3
3. Update the cluster by specifying a newer k8s version in the cluster.yml file . Cluster update fails as expected.
4. Label control node C3 with "user.cattle.io/upgrade-policy=prevent"
5. Run command “./rke up --config cluster.yml”  with new K8s version 
After labeling the control node C3, cluster upgrade proceeds. The labeled node will be ignored during upgrade. Cluster should upgraded successfully with new K8s version

**Use case 2:**
**Setup:
3 control nodes(C1, C2, C3), 1 etcd, 4 workers             
max_Unavailable_worker = 1** 
1. Create a rke cluster using  “./rke up --config  cluster.yml”  command. Specify k8s version as v1.15.5 for example
2. Power off W3
3. Update the cluster by specifying a newer k8s version in the cluster.yml file . Cluster update fails as expected.
4. Label control node W3 with "user.cattle.io/upgrade-policy=prevent"
5. Run command “./rke up --config cluster.yml”  with new K8s version 
After labeling the worker node C3, cluster upgrade proceeds. The labeled node will be ignored during upgrade. Cluster gets upgraded successfully with new K8s version

**Use case 3:**
**Setup:
3 control nodes(C1, C2, C3), 1 etcd, 4 workers             
max_Unavailable_worker = 2** 
1. Create a rke cluster using  “./rke up --config  cluster.yml”  command. Specify k8s version as v1.15.5 for example
2. Power off W2, W3
3. Update the cluster by specifying a newer k8s version in the cluster.yml file . Cluster update fails as expected.
4. Label control node W3 with "user.cattle.io/upgrade-policy=prevent"
5. Run command “./rke up --config cluster.yml”  with new K8s version 
After labeling the worker node C3, cluster upgrade proceeds. The labeled node will be ignored during upgrade. Cluster gets upgraded successfully with new K8s version

**Comment by nbisson** [comment]
Hello,

I have a similar issue and I would like to use a label to exclude certain nodes in the upgrade process.
I have tried `rke.cattle.io/ignore-during-upgrade=true` and `user.cattle.io/upgrade-policy=prevent` but it doesn't seem to work.
Is the use of these labels still valid ?
