### ISSUE TITLE
RKE should detect duplicate mount points

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1920]
**RKE version:**
v1.0.4

**Steps to Reproduce:**
- Create a cluster and create extra_binds with a duplicate mount

```
nodes:
- address: x
  internal_address: x
  user: root
  role: [controlplane,worker,etcd]

services:
  kubeproxy:
    extra_binds:
    - "/lib/modules:/lib/modules"
```
**Results:**

```
WARN[0085] Failed to create Docker container [kube-proxy] on host [54.194.135.20]: Error response from daemon: Duplicate mount point: /lib/modules 
WARN[0085] Failed to create Docker container [kube-proxy] on host [54.194.135.20]: Error response from daemon: Duplicate mount point: /lib/modules 
WARN[0085] Failed to create Docker container [kube-proxy] on host [54.194.135.20]: Error response from daemon: Duplicate mount point: /lib/modules 
FATA[0085] [workerPlane] Failed to bring up Worker Plane: [Failed to create [kube-proxy] container on host [34.253.208.147]: Failed to create Docker container [kube-proxy] on host [34.253.208.147]: <nil>] 
```

gz#11900

**Comment by boomshadow** [comment]
I experience this same problem on RKE 1.0.2, and 1.0.0

**Comment by bmnave** [comment]
Hi @superseb!

Any updates on this issue? We're experiencing a similar problem trying to upgrade from RKE v1.0.6 to v1.2.4 and upgrade K8S from 1.17.4 to 1.19.3.  But the rke up fails with an error like Failed to bring up Control Plane: [Failed to create [kube-apiserver] container on host [<ip>]: Failed to create Docker container [kube-apiserver] on host [<ip>]: Error response from daemon: Duplicate mount point: /var/log/kube-audit] 

Thanks!
-b

**Comment by superseb** [comment]
There is no fix to handle this automatically, the current workaround is to remove the duplicate bind in `extra_binds:` to make it pass.

**Comment by bmnave** [comment]
Ahh. I didn't understand that we had added additional binds in extra_binds and this was not a default setting.  We'll give that a shot.  Thanks!
