### ISSUE TITLE
Revisit default backup image behavior

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1937]
**RKE version:**
Since v0.3.0

Based on https://github.com/rancher/rke/pull/1484, we added a function to get the default backup image. As I guess we never anticipated a new Rancher k8s release without new k8s version, running `rke up` will always use the backup image for the default k8s version for the RKE version used. That means that for an earlier release (`v1.16.7-rancher1-1`), you will see `rancher/rke-tools:v0.1.52` used for sidekick etc, but `rancher/rke-tools:v0.1.53` as the image for backups (etcd-snapshot).

We should revisit and just use the backup image for the `kubernetes_version` the cluster is being provisioned with, and possibly have a fallback if we can't find that one.

**Comment by aiyengar2** [comment]
Quick point of clarification re:

> running rke up will always use the backup image for the default k8s version for the RKE version used

To figure out which version of RKE will be used for the S3 backups, find the vendored version of RKE in Rancher, locate the corresponding RKE version on rancher/rke, get the data.json, and check the default version.

e.g. for [rancher/rancher@v2.4.16](https://github.com/rancher/rancher/tree/v2.4.16), the [go.mod entry for rke](https://github.com/rancher/rancher/blob/c29a771063e6926df6916990f1730e0574042ba8/go.mod#L87) points to v1.1.18.

Therefore, if you get [the corresponding tag on rancher/rke](https://github.com/rancher/rke/tree/v1.1.18) and access [data/data.json](https://github.com/rancher/rke/blob/v1.1.18/data/data.json) you will see:

```
"RKEDefaultK8sVersions": {
  "0.3": "v1.16.3-rancher1-1",
  "default": "v1.18.20-rancher1-1"
 }
```

From this version, you can identify the version of rke-tools used by going to the corresponding KDM branch for your Rancher release (e.g. v2.4.16 -> [dev-v2.4 on rancher/kontainer-driver-metadata](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.4)) and finding the entry for rke-tools under [rke/k8s_rke_system_images.go](https://github.com/rancher/kontainer-driver-metadata/blob/56d4ebd4adcde4f0a939cb61ff19fc22e9638b16/rke/k8s_rke_system_images.go#L4377).

Therefore, Rancher v2.4.16 will be using `rancher/rke-tools:v0.1.75` for S3 backups today.
