### ISSUE TITLE
Add host to Docker log lines to identify host

### ISSUE THREAD

**Issue by superseb** [rancher/rke#1940]
**RKE version:**
v1.0.4

When running `rke --debug up`, we print `Docker Info found` and dump the results. Although you can probably identify the host based on the output of `docker info`, we don't log for what host we print the docker info which makes it more easy to relate the logging to the host. And when a mixup happens, at least we log what RKE thinks it is.

This also applies to `Unsupported Docker version found`

**Comment by deniseschannon** [comment]
Available with v1.1.0-rc12

**Comment by rancher-max** [comment]
#### Reproduced with rke v1.0.4:
`DEBU[0031] Docker Info found:`

#### Validated fix with rke v1.1.0-rc13
`DEBU[0003] Docker Info found for host [18.144.32.146]:`
