### ISSUE TITLE
Pods keep getting invalid IP addresses

### ISSUE THREAD

**Issue by pbecotte** [rancher/rke#1950]
**Docker version: (`docker version`,`docker info` preferred)**
18.9.9

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
4.4.0-173-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Digital Ocean

**cluster.yml file:**
The cluster was deployed using terraform. The code can be seen at https://gitlab.com/devblog/infrastructure/-/blob/master/modules/rancher/cluster/main.tf. 

(this is a side-project cluster, so does not get paid attention to nearly enough...but the code is public.)

Issue:

I have a cluster that I _believe_ to be completely standard from a networking point of view. It is using 10.42.x.x for the pod CIDR, and 10.43.x.x as the service CIDR. A couple weeks ago, I noticed that some of my webapp containers and some of my elastic stack pods were failing. It appeared to be a dns issue. I eventually noticed that while one of my coredns pods had a 10.42.xxx IP address, the other had a 172.17.x.x address. Deleting that pod caused it to be recreated in the 10.42 range, and fixed the cluster.

Today, noticed my site was down again. Looked, and have lots of pods with 172 IP addresses again. I was especially interested to note that one of the coredns pods had the SAME 172.x.x.x ip address as one of the cert-manager pods.I deleted the important pods with bad ip addresses and the site came up. I was then going through with some other pods that didn't matter but that had the wrong IP. Argocd in this case runs four pods and they all had bad ips. I deleted the first two. Then, I lost connectivity to my cluster for a minute, deleted the third, lost connectivity for a minute, and deleted the fourth. (rancher is running on a single server external to the k8s cluster). At the end, I noticed that the first argocd pod I terminated, which I saw get a good 10.42 IP address, now once again had 172.17. It had not been restarted or recreated since I saw it with the other address (I still had that `get -A pods -o wide` open in another terminal...). There was nothing interesting in its logs. The cluster has actually been up for a couple months, and I have had ongoing issues with stuff crashing and having to be manually recovered where I didn't spend any time troubleshooting...my guess is this has been going on for a while.

I am honestly out of my league here with the networking- was wondering if anyone had ideas as to what could cause something like this?

**Comment by superseb** [comment]
This is a Rancher issue and tracked in https://github.com/rancher/rancher/issues/23284
