### ISSUE TITLE
creating new cluster using existing etcd snapshot

### ISSUE THREAD

**Issue by resamaraschi** [rancher/rke#1955]
Hi,
I have the following situation:
We have a HA rancher server and a RKE k8s user cluster where we run productive application.
Recently Our 3 VMs (1 VMs with roles etcd, control plane, and 2 VMs each one only with worker role), where the user cluster were running on , have been removed by mistake.

Fortunately we have backups from the etcd. However from what I understand from this [Documentation](https://rancher.com/docs/rke/latest/en/etcd-snapshots/restoring-from-backup/), the restore is only possible when you have at least one node running with etcd role. 

In my case, I have 3 new VMs and a recent etcd snapshot and the cluster.yaml and .rkestate files and the existing rancher server.

Is there a way to restore the user cluster and connect it to our rancher server from those files?

What I tried:
1. rke up --config same-cluster.yaml
2. put the etcd snapshot under /opt/rke/etcd-snapshots/ in  etcd,controlplane node (VM)
Fresh cluster was up and running and all pods were in running state
3. rke etcd snapshot-restore --config ame-cluster.yaml --name my-snapshot
The new cluster looks unhealthy: among other logs :
 `Pod: coredns:
│ [ERROR] plugin/errors: 2 8180231364052493872.7249118155641617033. HINFO: read udp 10.42.3.3:57664->10.195.2.1:53: i/o timeout                                                                                                                              │
│ I0312 10:49:08.144897       1 trace.go:82] Trace[557959622]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2020-03-12 10:48:38.144284492 +0000 UTC m=+0.016086977) (total tim │
│ Trace[557959622]: [30.000504161s] [30.000504161s] END                                                                                                                                                                                                      │
│ E0312 10:49:08.144926       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.43.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.43 │
│ E0312 10:49:08.144926       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.43.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.43 │
│  `

I think the issue here is that we restoring a fresh etcd node with a snapshot of an etcd of the old cluster.

would appreciate any help :) 

**RKE version:Running RKE version: v1.0.4 , Server Version: version.Info{Major:"1", Minor:"17 **

**Docker version: 19.03.6**

**Operating system and kernel:4.15.0-88-generic**

**Type/provider of hosts: Own Infrastructure**

**Comment by xiaoluhong** [comment]
The log looks like a network access exception，you can check the logs of the network driver pod.

**Comment by resamaraschi** [comment]
kube-flannel: `I0312 12:48:05.295331       1 main.go:514] Determining IP address of default interface   
 I0312 12:48:05.295860       1 main.go:527] Using interface with name ens192 and address 10.195.2.x 
E0312 12:48:05.303430       1 main.go:241] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/canal-xmx5k': Unauthorized  
`

calico-node: `2020-03-12 12:48:04.897 [INFO][8] k8s.go 219: Using host-local IPAM                                                                                                                                                                                        
│ 2020-03-12 12:48:04.897 [INFO][8] startup.go 319: Checking datastore connection                                                                                                                                                                           
│ 2020-03-12 12:48:04.906 [WARNING][8] startup.go 331: Connection to the datastore is unauthorized                                                                                                                                                           
│ 2020-03-12 12:48:04.906 [WARNING][8] startup.go 1122: Terminating    `

**Comment by resamaraschi** [comment]
@xiaoluhong Thanks for your response. Is it possible to start up a brand new cluster with an existing etcd snapshot and .rkestate file ? Isn't it required to have at least one etcd node from the cluster which has suffered a disaster?

**Comment by rakeshk121** [comment]
@resamaraschi what was the fix for this?
