### ISSUE TITLE
[Bug] RKE doesn't clean all containers or configs after run rke remove

### ISSUE THREAD

**Issue by fengzixu** [rancher/rke#1961]
**RKE version:** 

1.0.4

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack VM

**cluster.yml file:**

**Steps to Reproduce:**

1. rke up
2. rke remove
3. rke up

**Results:**
Some containers remain on the host
![image](https://user-images.githubusercontent.com/9636615/76582277-1d657e80-6519-11ea-8aa7-27912bec189f.png)

And if you perform the `ip link`, you will see the cni0 and flannel.1. I think they should be removed after I performed the `rke remove`.

If you don't cleanup all containers or network devices,  the core dns won't start successfully. Because of the cni errors.

**Comment by fengzixu** [comment]
Please verify this issue. If the maintainer agree, I will handle it.

**Comment by fengzixu** [comment]
And lots of devices weren't be cleaned up
```
rm: cannot remove ‘kubelet/pods/802550ff-8f6b-42b1-8c28-a1e96f04bf36/volumes/kubernetes.io~secret/flannel-token-lldrb’: Device or resource busy
rm: cannot remove ‘kubelet/pods/f1a4c5be-6f83-4237-8afc-0c7dc28cb7af/volumes/kubernetes.io~secret/coredns-token-fqzpg’: Device or resource busy
rm: cannot remove ‘kubelet/pods/7c4991d1-c3a8-469b-abf5-564fa4fc66b6/volumes/kubernetes.io~secret/nginx-ingress-serviceaccount-token-kmh68’: Device or resource busy
rm: cannot remove ‘kubelet/pods/a4d12714-49d4-4700-b0fc-f6976de80471/volumes/kubernetes.io~secret/prometheus-server-token-qtq74’: Device or resource busy
rm: cannot remove ‘kubelet/pods/77be0a7c-5306-4031-8e1b-d12b2689bb0a/volumes/kubernetes.io~secret/prometheus-node-exporter-token-7wvcz’: Device or resource busy
rm: cannot remove ‘kubelet/pods/4c8ac683-af7d-486f-8b57-bfeb030673b9/volumes/kubernetes.io~secret/flannel-token-qplrr’: Device or resource busy
rm: cannot remove ‘kubelet/pods/f9059360-96cf-42c3-a18c-2406cef4ddca/volumes/kubernetes.io~secret/coredns-token-z2hl8’: Device or resource busy
rm: cannot remove ‘kubelet/pods/52893b50-bbb0-4dba-bdd0-24b38d0bd963/volumes/kubernetes.io~secret/nginx-ingress-serviceaccount-token-x6jwl’: Device or resource busy
```

**Comment by superseb** [comment]
Containers that are used for Kubernetes components should be removed, containers belonging to pods are not removed but will be automatically cleaned by the new kubelet when it is started. I just ran `rke up`, `rke remove`, `rke up` with RKE v1.0.4 and didn't see any issues in the cluster.

Please provide any specifics in your setup/`cluster.yml` that might cause to reproduce, also the outputs requested in the issue template.
