### ISSUE TITLE
rke up with selinux enabled not work

### ISSUE THREAD

**Issue by pdhung** [rancher/rke#1966]
**RKE version:** 1.0.4

** Kubernetes version:** 1.16.6 

**Docker version: (`docker version`,`docker info` preferred)** 
 Server Version: 19.03.8
 Storage Driver: devicemapper
 Security Options:
  seccomp
   Profile: default
  selinux

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 7.7 - 3.10.0-1062.12.1.el7.x86_64
(but upgraded from RHEL 7.2 gradually to 7.7)
**Results:**
on host with SElinux enabled in docker daemon.json, there is error:
```
level=debug msg="Found selinux in DockerInfo.SecurityOptions on host [worker2]"
level=debug msg="Found [io.rancher.rke.container.name=service-sidekick] in Labels on host [worker2], applying MCSLabel [label=level:s0:c1000,c1001]"
level=fatal msg="[workerPlane] Failed to bring up Worker Plane: [Failed to start [kubelet] container on host [worker2]: Error response from daemon: error setting label on mount source '/var/lib/docker': failed to set file label on /var/lib/docker/containers/239041eeca9c7f19d722373fd3f80d75700e2a68f10c4ec60fd5a155f715e281/mounts/shm: operation not supported]"
```

If SElinux is disabled for docker, rke run fine.

**More info:**
```
sudo ls -lsahZ /var/lib/docker/containers/239041eeca9c7f19d722373fd3f80d75700e2a68f10c4ec60fd5a155f715e281/mounts/shm
total 8.0K
drwx------. root root system_u:object_r:container_file_t:s0 .
drwx------. root root system_u:object_r:container_file_t:s0 ..
```
```
sudo docker inspect kubelet | grep MountLabel
        "MountLabel": "system_u:object_r:svirt_sandbox_file_t:s0:c457,c994"
```
```
sudo docker inspect kubelet | grep SecurityOpt -A5
"SecurityOpt": [
                "label=disable"
            ],
```

**Comment by pdhung** [comment]
```
sudo ls -lsahZ /var/lib/docker/containers/239041eeca9c7f19d722373fd3f80d75700e2a68f10c4ec60fd5a155f715e281/mounts/shm
total 8.0K
drwx------. root root system_u:object_r:container_file_t:s0 .
drwx------. root root system_u:object_r:container_file_t:s0 ..
```
```
sudo docker inspect kubelet | grep MountLabel
        "MountLabel": "system_u:object_r:svirt_sandbox_file_t:s0:c457,c994"
```

**Comment by pdhung** [comment]
so somehow the kubelet is ran with type svirt_sandbox_file_t

**Comment by pdhung** [comment]
It seems that RKE had disabled selinux for kubelet.

**Comment by carloscarnero** [comment]
I believe rancher/rancher#23662 is the same situation? At least I'm waiting for the release that supports both 1.16.8 and 1.17.4 in order to upgrade.

**Comment by pdhung** [comment]
I think it may be different.

#23662 reports a job cannot be run since it cannot read the SA token, because kubelet was not setting the appropriate label. This is a bug of k8s. But it means kubelet was up and running.

In my situation, kubelet was not able to start, since there is a MountLabel but there is no ProcessLabel that was set for kubelet when rke deploys the kubelet as a Docker Container, i.e. --security-opt="label=disable". This makes me think that this is the problem of rke deployment code.

**Comment by pdhung** [comment]
I have manually edited the configv2.json for kubelet and here are the results:

- "MountLabel": "system_u:object_r:svirt_sandbox_file_t:s0:c457,c994" 
  "ProcessLabel": "system_u:object_r:svirt_lxc_net_t:s0:c457,c994" 
  This does not work, kubelet cannot start.
- "MountLabel": "system_u:object_r:container_file_t:s0:c457,c994" 
  "ProcessLabel": "system_u:object_r:container_t:s0:c457,c994"
  This works. Kubelet starts.

**Comment by pdhung** [comment]
just tried with RKE 1.1.0-rc16 that supports 1.16.8 and still the same problem.

**Comment by The-Loeki** [comment]
Downgrading docker-ce to 19.03.6 seems to help

**Comment by pdhung** [comment]
@The-Loeki : 19.03.6 does not work on my side

**Comment by The-Loeki** [comment]
> 
> 
> @The-Loeki : 19.03.6 does not work on my side

we're also still running on 2.3.2 because of another selinux issue?

**Comment by xeor** [comment]
Is rke still broken when using selinux? I'm trying to do a fedora-coreos cluster with rke, but I'm getting this during `rke up`

```
WARN[0180] Can't start Docker container [kube-proxy] on host [d1.lan]: Error response from daemon: error setting label on mount source '/usr/lib/modules': relabeling content in /usr is not allowed 
FATA[0180] [workerPlane] Failed to bring up Worker Plane: [Failed to start [kube-proxy] container on host [d1.lan]: Error response from daemon: error setting label on mount source '/usr/lib/modules': relabeling content in /usr is not allowed] 
```

**Comment by tailtwo** [comment]
> Is rke still broken when using selinux? I'm trying to do a fedora-coreos cluster with rke, but I'm getting this during `rke up`
> 
> ```
> WARN[0180] Can't start Docker container [kube-proxy] on host [d1.lan]: Error response from daemon: error setting label on mount source '/usr/lib/modules': relabeling content in /usr is not allowed 
> FATA[0180] [workerPlane] Failed to bring up Worker Plane: [Failed to start [kube-proxy] container on host [d1.lan]: Error response from daemon: error setting label on mount source '/usr/lib/modules': relabeling content in /usr is not allowed] 
> ```

Can confirm, got the same issue on latest FCOS stable.

**Comment by kschamplin** [comment]
I have replicated the above errors mentioned by @tailtwo and @xeor on FCOS. Perhaps it is due to the fact that `/usr` is mounted read-only.

**Comment by frjaraur** [comment]
Hi all, this problem persist on SUSE SLES15 SP2. RKE will fail running kubelet because it can not mount /var/lib/docker in read-write mode. SUSE customized docker engine injects credentials, which are read-only secrets.
kubelet will always fail to start:
```
secure-sles:~ # docker start kubelet
Error response from daemon: error setting label on mount source '/var/lib/docker': failed to set file label on /var/lib/docker/containers/14ef33515a09d1258e436f1561350a0b668fd2f1c2ce64f9ba9f1fc2650ec46e/mounts/secrets: read-only file system
Error: failed to start containers: kubelet


secure-sles:~ # ls -l /var/lib/docker/containers/14ef33515a09d1258e436f1561350a0b668fd2f1c2ce64f9ba9f1fc2650ec46e/mounts/secrets/suse_392a03a2e1ec765d08844b4665e36e372487aee361b58b7d3fe30eda103dc9c3_credential
s.d/
total 20
-rw-------. 1 root root 72 Jun 21 09:37 Basesystem_Module_15_SP2_x86_64
-rw-------. 1 root root 72 Jun 21 12:27 Containers_Module_15_SP2_x86_64
-rw-------. 1 root root 72 Jun 21 09:36 SCCcredentials
-rw-------. 1 root root 72 Jun 21 09:37 Server_Applications_Module_15_SP2_x86_64
-rw-------. 1 root root 72 Jun 21 09:37 SUSE_Linux_Enterprise_Server_15_SP2_x86_64
```

I reviewed SELinux labels applied to RKE containers and I found that kubelet does not include any:

```
secure-sles:~ # docker inspect kubelet | grep SecurityOpt -A2
            "SecurityOpt": [
                "label=disable"
            ],
secure-sles:~ # docker inspect kube-apiserver | grep SecurityOpt -A2
            "SecurityOpt": [
                "label=level:s0:c1000,c1001"
            ],
secure-sles:~ # docker inspect kube-scheduler | grep SecurityOpt -A2
            "SecurityOpt": [
                "label=level:s0:c1000,c1001"
            ],
secure-sles:~ # docker inspect kube-controller-manager | grep SecurityOpt -A2
            "SecurityOpt": [
                "label=level:s0:c1000,c1001"
            ],
```

All containers using volumes are labelled using "level:s0:c1000,c1001". 

Should I open a new issue with this information?.

Many Thanks in Advanced,
Javier R.
