### ISSUE TITLE
cloud_provider AWS prevents Kubelet from starting

### ISSUE THREAD

**Issue by treaves** [rancher/rke#1982]
I am using the [QuickStart](https://github.com/rancher/quickstart) to try and deploy an example Helm Chart.  If I clone the referenced repo and set aws_access_key & aws_secret_key and run terraform, the rancher & rke cluster start fine.  My Helm Chart fails when provisioning persistent storage.  Investigating that issue, I was pointed to the [AWS provider](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/aws/) and told the `rke.tf` file in the QuickStart repo needed the block:
```
  cloud_provider {
    name = "aws"
  }
```

When I add this and run `terraform apply`, it fails with the following:
`
Failed running cluster err:[workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [3.134.105.157]: Get http://localhost:10248/healthz: Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: F0324 17:50:02.794803   10431 server.go:273] failed to run Kubelet: could not init cloud provider "aws": error finding instance i-0087d4dd52749371e: "error listing AWS instances: \"NoCredentialProviders: no valid providers in chain. Deprecated.\\n\\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\""]
`

I've tried everything I can find related to this, but nothing works.  The account credentials I'm using have admin level access.  

I'd greatly appreciate any help in understanding and fixing what is wrong.

**Comment by superseb** [comment]
The error points out that the nodes do not have an instance profile with the requirements described in https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/aws/#iam-requirements. Can you elaborate more on what account credentials are and how you configured them?
