### ISSUE TITLE
RKE needs comprehensive help or manpage

### ISSUE THREAD

**Issue by Tejeev** [rancher/rke#2023]
**RKE version:**
v1.0.4

When working with RKE it is difficult to find a complete list of RKE options and commands.  Instead of a quick `--help` with a `grep` or a `man` page to find the appropriate option and example commands, we have to spend time hunting through the ever changing docs.  

It would be very helpful if RKE had a comprehensive man page or if  `--help` at least had a list of all the options available and the basic snapshot commands.  Even once the docs stabilize, it will always be very helpful to have a cli reference to quickly correct your commands when troubleshooting or managing an environment.  Time saved during an outage is gold.

**Comment by superseb** [comment]
@Tejeev Please be more specific on what the expectation on this is, this is the current output:

```
$ ./rke_darwin-amd64 etcd snapshot-save --help
WARN[0000] This is not an officially supported version (v1.3.0-rc10) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases 
NAME:
   rke etcd snapshot-save - Take snapshot on all etcd hosts

USAGE:
   rke etcd snapshot-save [command options] [arguments...]

OPTIONS:
   --name value             Specify snapshot name
   --config value           Specify an alternate cluster YAML file (default: "cluster.yml") [$RKE_CONFIG]
   --s3                     Enabled backup to s3
   --s3-endpoint value      Specify s3 endpoint url (default: "s3.amazonaws.com")
   --s3-endpoint-ca value   Specify a custom CA cert to connect to S3 endpoint
   --access-key value       Specify s3 accessKey
   --secret-key value       Specify s3 secretKey
   --bucket-name value      Specify s3 bucket name
   --region value           Specify the s3 bucket location (optional)
   --folder value           Specify s3 folder name
   --ssh-agent-auth         Use SSH Agent Auth defined by SSH_AUTH_SOCK
   --ignore-docker-version  Disable Docker version check
```

**Comment by Tejeev** [comment]
huh... I just downloaded binary locally and it works fine... Must have been some environmental issue or some bug... I see other folks liked this.  Is anyone else seeing that `--help` fails?  If so could you provide some environmental and version information?  Otherwise we can probably close this
