### ISSUE TITLE
RKE latest releases includes RC versions

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rke#2036]
**RKE version:**
Any RC version of rke

**Steps to Reproduce:**
Run an RC version of RKE, which will log the following warning:
```
WARN[0000] This is not an officially supported version (v1.0.7-rc3) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest
```

**Results:**
Navigate to url mentioned, which links to the latest release, which includes RC versions and thus the top link is typically not the latest stable/supported release.

gz#9727

**Comment by superseb** [comment]
This is solved as part of https://github.com/rancher/rke/issues/2350
