### ISSUE TITLE
Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system

### ISSUE THREAD

**Issue by RaberShef** [rancher/rke#2039]
**RKE version:**
rke v0.2.10

**Docker version: (`docker version`,`docker info` preferred)**
docker version:

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

docker info:
Client:
 Debug Mode: false

Server:
 Containers: 18
  Running: 7
  Paused: 0
  Stopped: 11
 Images: 4
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.138-rancher
 Operating System: RancherOS v1.5.5
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.855GiB
 Name: rancher
 ID: VAU2:2GCV:FD65:LQVN:F2S3:SFRJ:DKKW:MHH5:G7FJ:6YU5:XRTZ:NSDM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="RancherOS"
VERSION=v1.5.5
ID=rancheros
ID_LIKE=
VERSION_ID=v1.5.5
PRETTY_NAME="RancherOS v1.5.5"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

4.14.138-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM, Proxmox, VM

**cluster.yml file:**
nodes:
  - address: 192.168.100.101 # node air gap network IP
    user: rancher
    role: ['controlplane', 'etcd', 'worker']
    ssh_key_path: /home/rancher/.ssh/id_rsa
  - address: 192.168.100.102 # node air gap network IP
    user: rancher
    role: ['controlplane', 'etcd', 'worker']
    ssh_key_path: /home/rancher/.ssh/id_rsa
  - address: 192.168.100.103 # node air gap network IP
    user: rancher
    role: ['controlplane', 'etcd', 'worker']
    ssh_key_path: /home/rancher/.ssh/id_rsa

private_registries:
  - url: nexus.example.com:18001 # private registry url
    user: admin
    password: *******
    is_default: true

**Steps to Reproduce:**
rke up

**Results:**
rke up log:
INFO[0045] [network] Setting up network plugin: canal
INFO[0045] [addons] Saving ConfigMap for addon rke-network-plugin to Kubernetes
INFO[0045] [addons] Successfully saved ConfigMap for addon rke-network-plugin to Kubernetes
INFO[0045] [addons] Executing deploy job rke-network-plugin
FATA[0080] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system

failing job pod's log:
unable to recognize "/etc/config/rke-network-plugin.yaml": Get https://10.43.0.1:443/api?timeout=32s: dial tcp 10.43.0.1:443: connect: network is unreachable
unable to recognize "/etc/config/rke-network-plugin.yaml": Get https://10.43.0.1:443/api?timeout=32s: dial tcp 10.43.0.1:443: connect: network is unreachable
unable to recognize "/etc/config/rke-network-plugin.yaml": Get https://10.43.0.1:443/api?timeout=32s: dial tcp 10.43.0.1:443: connect: network is unreachable
unable to recognize "/etc/config/rke-network-plugin.yaml": Get https://10.43.0.1:443/api?timeout=32s: dial tcp 10.43.0.1:443: connect: network is unreachable
unable to recognize "/etc/config/rke-network-plugin.yaml": Get https://10.43.0.1:443/api?timeout=32s: dial tcp 10.43.0.1:443: connect: network is unreachable

**Comment by pasikarkkainen** [comment]
For similar symptoms it helped for me to set higher rke config "addon_job_timeout" value ( https://github.com/rancher/rke/issues/1652 ).

**Comment by RaberShef** [comment]
> For similar symptoms it helped for me to set higher rke config "addon_job_timeout" value ( #1652 ).

I already tried it, even setting it to 3000 did not help.
