### ISSUE TITLE
Kubernetes 1.9 as a default image version

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#205]
@moelsayed @galal-hussein once we validate k8s 1.9, if there are no issues, we should make it a default k8s image version for rke.

**Comment by alena1108** [comment]
Before switching, lets confirm with the rest of the team. I know some api stuff got promoted from v1beta to v1 in k8s 1.9, that can cause some conflicts that need to be resolved.

**Comment by mimizone** [comment]
wondering where we stand on this. Any update on support of 1.9.x?

**Comment by HighwayofLife** [comment]
Just FYI, we've been running RKE with K8s 1.9 for 3 months now. I haven't found any issues so far.

**Comment by moelsayed** [comment]
@mimizone It's possible to override the default images and use 1.9. We have not seen any issues related to using 1.9 so far, or got any bug reports. However, we didn't run it through our certification process yet, that's why it's not promoted as a default.

**Comment by mimizone** [comment]
thanks. may I ask where this configuration is done? can additional parameters be given, for instance to enable GPU support? and is there a way to do it via rancher 2.0, even in a "hackie" way, by changing that config in the rancher master node?

**Comment by moelsayed** [comment]
For rke standalone, you can configure the images used in the [cluster.yml](https://github.com/moelsayed/rke/blob/master/cluster.yml#L103-L115) file. You can also pass additional options parameters to k8s components using [extra_args](https://github.com/moelsayed/rke/blob/master/cluster.yml#L48)

I am not sure about rancher 2.0, you probably should open a separate [issue](https://github.com/rancher/rancher/issues) here for that.

**Comment by deniseschannon** [comment]
k8s 1.10 is the default with Rancher CLI

**Comment by deniseschannon** [comment]
k8s 1.10 is the default with RKE CLI

**Comment by adingilloRancher** [comment]
Master 4/23/18 
Verified 1.10.1 is default version
