### ISSUE TITLE
WARN[0020] [etcd] etcd rolling snapshot container failed to start correctly

### ISSUE THREAD

**Issue by Rancheroo** [rancher/rke#2077]
**RKE version:** 1.1.1

**Docker version: (`docker version`,`docker info` preferred)**
docker info
Client:
 Debug Mode: false

Server:
 Containers: 75
  Running: 53
  Paused: 0
  Stopped: 22
 Images: 81
 Server Version: 18.09.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-66-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.79GiB
 Name: bj-single-all
 ID: HXWR:7ZEK:XSJE:XIRA:OGSL:7OKJ:QXXZ:4SFJ:TUUK:P4MJ:3T7N:GIT5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

4.15.0-66-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Digital Ocean

**cluster.yml file:**

nodes:
- address: redacted
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  - worker
  hostname_override: single-all 
  user: root
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/dokey
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: true
    retention: "24"
    creation: "1h"
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
  node_selector: {}
authentication:
  strategy: x509
  sans: []
  webhook: null
kubernetes_version: v1.15.11-rancher1-2

**Steps to Reproduce:**
modify cluster.yml to retain 24 snapshots instead of 24h

services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: true
    retention: "24"
    creation: "1h"
    backup_config: null

**Results:**
INFO[0000] Running RKE version: v1.1.1                  
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates 
INFO[0000] [certificates] Generating admin certificates and kubeconfig 
INFO[0000] Successfully Deployed state file at [./cluster.rkestate] 
INFO[0000] Building Kubernetes cluster                  
INFO[0000] [dialer] Setup tunnel for host [REDACTED-IP] 
INFO[0002] [network] No hosts added existing cluster, skipping port check 
INFO[0002] [certificates] Deploying kubernetes certificates to Cluster nodes 
INFO[0002] Checking if container [cert-deployer] is running on host [REDACTED-IP], try #1   
INFO[0003] Image [rancher/rke-tools:v0.1.50] exists on host [REDACTED-IP] 
INFO[0003] Starting container [cert-deployer] on host [REDACTED-IP], try #1   
INFO[0004] Checking if container [cert-deployer] is running on host [REDACTED-IP], try #1   
INFO[0010] Checking if container [cert-deployer] is running on host [REDACTED-IP], try #1   
INFO[0010] Removing container [cert-deployer] on host [REDACTED-IP], try #1   
INFO[0010] [reconcile] Rebuilding and updating local kube config 
INFO[0010] Successfully Deployed local admin kubeconfig at [./kube_config_cluster.yml] 
INFO[0011] [reconcile] host [REDACTED-IP] is active master on the cluster 
INFO[0011] [certificates] Successfully deployed kubernetes certificates to Cluster nodes 
INFO[0011] [reconcile] Reconciling cluster state        
INFO[0011] [reconcile] Check etcd hosts to be deleted   
INFO[0011] [reconcile] Check etcd hosts to be added     
INFO[0011] [reconcile] Rebuilding and updating local kube config 
INFO[0011] Successfully Deployed local admin kubeconfig at [./kube_config_cluster.yml] 
INFO[0011] [reconcile] host [REDACTED-IP] is active master on the cluster 
INFO[0011] [reconcile] Reconciled cluster state successfully 
INFO[0011] max_unavailable_worker got rounded down to 0, resetting to 1 
INFO[0011] Setting maxUnavailable for worker nodes to: 1 
INFO[0011] Setting maxUnavailable for controlplane nodes to: 1 
INFO[0011] Pre-pulling kubernetes images                
INFO[0011] Image [rancher/hyperkube:v1.15.5-rancher1] exists on host [REDACTED-IP] 
INFO[0011] Kubernetes images pulled successfully        
INFO[0011] [etcd] Building up etcd plane..              
INFO[0011] Image [rancher/rke-tools:v0.1.50] exists on host [REDACTED-IP] 
INFO[0011] Starting container [etcd-fix-perm] on host [REDACTED-IP], try #1   
INFO[0012] Successfully started [etcd-fix-perm] container on host [REDACTED-IP] 
INFO[0012] Waiting for [etcd-fix-perm] container to exit on host [REDACTED-IP] 
INFO[0012] Waiting for [etcd-fix-perm] container to exit on host [REDACTED-IP] 
INFO[0013] Removing container [etcd-fix-perm] on host [REDACTED-IP], try #1   
INFO[0013] [remove/etcd-fix-perm] Successfully removed container on host [REDACTED-IP] 
INFO[0013] [etcd] Running rolling snapshot container [etcd-snapshot-once] on host [REDACTED-IP] 
INFO[0014] Removing container [etcd-rolling-snapshots] on host [REDACTED-IP], try #1   
INFO[0014] [remove/etcd-rolling-snapshots] Successfully removed container on host [REDACTED-IP] 
INFO[0014] Image [rancher/rke-tools:v0.1.56] exists on host [REDACTED-IP] 
INFO[0014] Starting container [etcd-rolling-snapshots] on host [REDACTED-IP], try #1   
INFO[0015] [etcd] Successfully started [etcd-rolling-snapshots] container on host [REDACTED-IP] 
**WARN[0020] [etcd] etcd rolling snapshot container failed to start correctly** 
INFO[0020] Removing container [etcd-rolling-snapshots] on host [REDACTED-IP], try #1   
INFO[0021] Image [rancher/rke-tools:v0.1.56] exists on host [REDACTED-IP] 
INFO[0021] Starting container [rke-bundle-cert] on host [REDACTED-IP], try #1   
INFO[0022] [certificates] Successfully started [rke-bundle-cert] container on host [REDACTED-IP] 
INFO[0022] Waiting for [rke-bundle-cert] container to exit on host [REDACTED-IP] 
INFO[0022] Container [rke-bundle-cert] is still running on host [REDACTED-IP] 
INFO[0023] Waiting for [rke-bundle-cert] container to exit on host [REDACTED-IP] 
INFO[0023] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [REDACTED-IP] 
INFO[0023] Removing container [rke-bundle-cert] on host [REDACTED-IP], try #1   
INFO[0024] Image [rancher/rke-tools:v0.1.50] exists on host [REDACTED-IP] 
INFO[0024] Starting container [rke-log-linker] on host [REDACTED-IP], try #1   
INFO[0025] [etcd] Successfully started [rke-log-linker] container on host [REDACTED-IP] 
INFO[0025] Removing container [rke-log-linker] on host [REDACTED-IP], try #1   
INFO[0025] [remove/rke-log-linker] Successfully removed container on host [REDACTED-IP] 
INFO[0025] [etcd] Successfully started etcd plane.. Checking etcd cluster health 
INFO[0028] [controlplane] Now checking status of node bj-single-all, try #1   
INFO[0028] [controlplane] Processing controlplane hosts for upgrade 1 at a time 
INFO[0028] Processing controlplane host bj-single-all   
INFO[0028] [controlplane] Now checking status of node bj-single-all, try #1   
INFO[0028] [controlplane] Getting list of nodes for upgrade 
INFO[0030] Upgrade not required for controlplane and worker components of host bj-single-all 
INFO[0030] [controlplane] Successfully upgraded Controller Plane.. 
INFO[0030] [authz] Creating rke-job-deployer ServiceAccount 
INFO[0030] [authz] rke-job-deployer ServiceAccount created successfully 
INFO[0030] [authz] Creating system:node ClusterRoleBinding 
INFO[0031] [authz] system:node ClusterRoleBinding created successfully 
INFO[0031] [authz] Creating kube-apiserver proxy ClusterRole and ClusterRoleBinding 
INFO[0031] [authz] kube-apiserver proxy ClusterRole and ClusterRoleBinding created successfully 
INFO[0031] Successfully Deployed state file at [./cluster.rkestate] 
INFO[0031] [state] Saving full cluster state to Kubernetes 
INFO[0032] [state] Successfully Saved full cluster state to Kubernetes ConfigMap: full-cluster-state 
INFO[0032] [worker] Upgrading Worker Plane..            
INFO[0032] [worker] Successfully upgraded Worker Plane.. 
INFO[0032] Image [rancher/rke-tools:v0.1.50] exists on host [REDACTED-IP] 
INFO[0033] Starting container [rke-log-cleaner] on host [REDACTED-IP], try #1   
INFO[0033] [cleanup] Successfully started [rke-log-cleaner] container on host [REDACTED-IP] 
INFO[0034] Removing container [rke-log-cleaner] on host [REDACTED-IP], try rancher/rke#1 
INFO[0034] [remove/rke-log-cleaner] Successfully removed container on host [REDACTED-IP] 
INFO[0034] [sync] Syncing nodes Labels and Taints       
INFO[0034] [sync] Successfully synced nodes Labels and Taints 
INFO[0034] [network] Setting up network plugin: canal   
INFO[0034] [addons] Saving ConfigMap for addon rke-network-plugin to Kubernetes 
INFO[0034] [addons] Successfully saved ConfigMap for addon rke-network-plugin to Kubernetes 
INFO[0034] [addons] Executing deploy job rke-network-plugin 
INFO[0035] [addons] Setting up coredns                  
INFO[0035] [addons] Saving ConfigMap for addon rke-coredns-addon to Kubernetes 
INFO[0035] [addons] Successfully saved ConfigMap for addon rke-coredns-addon to Kubernetes 
INFO[0035] [addons] Executing deploy job rke-coredns-addon 
INFO[0035] [addons] CoreDNS deployed successfully       
INFO[0035] [dns] DNS provider coredns deployed successfully 
INFO[0035] [addons] Setting up Metrics Server           
INFO[0035] [addons] Saving ConfigMap for addon rke-metrics-addon to Kubernetes 
INFO[0035] [addons] Successfully saved ConfigMap for addon rke-metrics-addon to Kubernetes 
INFO[0035] [addons] Executing deploy job rke-metrics-addon 
INFO[0036] [addons] Metrics Server deployed successfully 
INFO[0036] [ingress] Setting up nginx ingress controller 
INFO[0036] [addons] Saving ConfigMap for addon rke-ingress-controller to Kubernetes 
INFO[0036] [addons] Successfully saved ConfigMap for addon rke-ingress-controller to Kubernetes 
INFO[0036] [addons] Executing deploy job rke-ingress-controller 
INFO[0036] [ingress] ingress controller nginx deployed successfully 
INFO[0036] [addons] Setting up user addons              
INFO[0036] [addons] no user addons defined              
INFO[0036] Finished building Kubernetes cluster successfully 

gz#10287

**Comment by izaac** [comment]
I was able to reproduce this using rke `v1.1.1`, `v1.1.3` and `v1.0.10`

I've noticed in the documentation that there are two `retention` keys in different levels of the `etcd` configuration:

https://rancher.com/docs/rancher/v2.x/en/backups/backups/ha-backups/

```yaml
services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge
```

That retention value uses a string format to specify time with suffixes like `h` but under `etcd` there's also `backup_config` which has it's own `retention` key that gets integer format (without char suffixes) to specify hours:

```yaml
services:
  etcd:
    backup_config:
      enabled: true     # enables recurring etcd snapshots
      interval_hours: 6 # time increment between snapshots
      retention: 60     # time in days before snapshot purge
```

So i think this warning could be due because the `etcd` -> `retention` key is using an unexpected format?

**Comment by Rancheroo** [comment]
Thanks Izac, this is correct.

I was still using the old etcd rke definition. Thank you
