### ISSUE TITLE
/var/lib/kubelet is mounted on / but it is not a shared mount

### ISSUE THREAD

**Issue by Cloud-Mak** [rancher/rke#2108]
**RKE version:**
rke version v1.1.0

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 19.03.6, build 369ce74a3c

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux ubu1 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
LXD container

**cluster.yml file:**
https://raw.githubusercontent.com/Cloud-Mak/paste-logs/master/rke-cluster.yaml

Hi All,
I am playing around with Rancher rke. Preparing for Rancher operator online course. I am New to Rancher. Trying to deploy a single node RKE cluster. This single node is LXD container (ubuntu 18.04). 

After doing "rke up" I ran into below error - 

```
INFO[0242] [authz] kube-apiserver proxy ClusterRole and ClusterRoleBinding created successfully 
INFO[0242] Successfully Deployed state file at [./cluster.rkestate] 
INFO[0242] [state] Saving full cluster state to Kubernetes 
INFO[0242] [state] Successfully Saved full cluster state to Kubernetes ConfigMap: full-cluster-state 
INFO[0242] [worker] Building up Worker Plane..          
INFO[0242] Checking if container [service-sidekick] is running on host [10.70.241.23], try #1 
INFO[0242] [sidekick] Sidekick container already created on host [10.70.241.23] 
INFO[0242] Image [rancher/hyperkube:v1.16.8-rancher1] exists on host [10.70.241.23] 
INFO[0242] Starting container [kubelet] on host [10.70.241.23], try #1 
WARN[0242] Can't start Docker container [kubelet] on host [10.70.241.23]: Error response from daemon: path /var/lib/kubelet is mounted on / but it is not a shared mount 
INFO[0242] Starting container [kubelet] on host [10.70.241.23], try #2 
WARN[0242] Can't start Docker container [kubelet] on host [10.70.241.23]: Error response from daemon: path /var/lib/rancher is mounted on / but it is not a shared mount 
INFO[0242] Starting container [kubelet] on host [10.70.241.23], try #3 
WARN[0242] Can't start Docker container [kubelet] on host [10.70.241.23]: Error response from daemon: path /var/lib/rancher is mounted on / but it is not a shared mount 
FATA[0242] [workerPlane] Failed to bring up Worker Plane: [Failed to start [kubelet] container on host [10.70.241.23]: Error response from daemon: path /var/lib/rancher is mounted on / but it is not a shared mount] 

```
Any idea what can be done now?

**Comment by Cloud-Mak** [comment]
Hello,

Just bouncing this to undrestand if anyone here has any luck at all to get RKE cluster setup over LXC machine containrs. 
 (Personally, I was able to setup upstream K8 cluster using kubeadm on set of LXC/LXD containers)

**Comment by superseb** [comment]
`mount --make-shared /` has been used in all other occurrences of this issue, does that not work?
