### ISSUE TITLE
Can't change VNI and PORT for network provider in cluster yaml

### ISSUE THREAD

**Issue by tfedyanin** [rancher/rke#2109]
**RKE version:**
v1.1.1

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 45
 Running: 20
 Paused: 0
 Stopped: 25
Images: 18
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-1127.8.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 15.49 GiB
Name: gismu2-bi-k8s-01
ID: 4KFG:OML3:QQRN:QJOK:LPC6:6NIS:3NLQ:JRVB:LBUK:J6ZX:O36G:W6JK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
[rke@gismu2-bi-k8s-01 ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
```
uname -r
3.10.0-1127.8.2.el7.x86_64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
[cluster.yml.txt](https://github.com/rancher/rke/files/4745579/kubernetes_rke_at_cluster.yml.txt)

**Steps to Reproduce:**
Change default vni and port for network provider and `rke up` 
```
network:
  plugin: canal
  options:
    canal_iface: ens192
    canal_flannel_backend_type: vxlan
    canal_flannel_backend_vni: 4097
    canal_flannel_backend_port: 8274
    flannel_backend_type: vxlan
    flannel_backend_vni: 4097
    flannel_backend_port: 8274
```

**Results:**
`kubectl -n kube-system get configmaps canal-config -o json` returns default values for port and interface identifier.

**Comment by scottatron** [comment]
I hit this problem too and did some digging. Seems like the templates used for the canal ConfigMap are missing the placeholder values for the `canal_flannel_backed_vni` and `canal_flannel_backend_port` settings.

I've opened a [PR in rancher/kontainer-driver-metadata](https://github.com/rancher/kontainer-driver-metadata/pull/330) to add these missing placeholders, but also found that I could use my changes locally by running `go generate` and getting RKE to load the resulting data.json with `RANCHER_METADATA_URL=data/data.json rke ...`.

**Comment by niusmallnan** [comment]
The support to config Flannel backend was first introduced by https://github.com/rancher/rke/pull/1290 .

This feature is described in the documentation via this PR https://github.com/rancher/docs/pull/2824 . However, this commit appears to have been removed as it was not available in the online documentation.

Although the code about Flannel Backend is still reserved in RKE, the configuration of Flannel Backend cannot take effect due to the canal template in kdm.

Here is a workaround. Modify net-conf.json in configmap canal-config under kube-system ns, and then redeploy canal daemonset.
```
{
  "Network": "10.42.0.0/16",
  "Backend": {
    "Type": "vxlan",
    "Port": 7777    
  }
}
```
