### ISSUE TITLE
Inter-host communication is lost when re-using GCE/AWS hosts with flannel network plugin

### ISSUE THREAD

**Issue by soumyalj** [rancher/rke#211]
**RKE version:**rke version v0.0.9-dev

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**AWS/GCE

**Steps to Reproduce:**
1. Create a cluster using GCE/AWS hosts with flannel network plugin
2. Create user pods. 
3. Verify inter-host communication by  exec'ing into the pods on the hosts. Interhost communication was functional
4. Remove the cluster by using "./rke remove" command
5. Recreate the cluster using the same hosts.

Interhost communication was lost. DNS resolution from one the user pods also failed.

**Comment by moelsayed** [comment]
Host reboot is required in this case as a part of clean up.
