### ISSUE TITLE
Link etcd-rolling-snapshot logs to RKELogsPath

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rke#2111]
Currently the etcd-rolling-snapshot container logs are not in a directory that is collected by Rancher-logging, so any issues creating snapshots can go undetected.
Creating a link to the RKELogsPath would resolve this.

**Comment by izaac** [comment]
RKE version: `1.2.0-rc14`
Validated this issue with RKE version `1.1.7` to compare.

In 1.1.7 when setting the cluster for recurring etcd backups I see the `etcd-rolling-snapshots` running but the logs are not stored in the node's filesystem.

```
 sudo ls /var/lib/rancher/rke/log
etcd_d0bb3e2ed45ec063b64a54c0031cc11189627c0867ccba5a99770f544bb093f7.log		      kube-proxy_b5d5a1fcc54cf0a76861ddf35326aa617faa4034b68a459d1fbf4319200384c1.log
kube-apiserver_5e7fa9f1943eb0b4af8bdd4f5d82bef31c588c5a2b0737a3836c2994cf1a816c.log	      kube-scheduler_8ed259533e039f77432d5c3c25879c0c68cd973bcced5df1dfd00a3576b4b646.log
kube-controller-manager_847fbc75333b821604af883d74d032513d6ffb80ae118faf43b73ffe13c720c3.log  kubelet_abb0255ae84290bac31b434497744ca85910018e987d6da718ed92c83df05320.log
```


In RKE `1.2.0-rc14` the `etcd-rolling-snapshots` is running and the logs are stored in the node's filesystem.

```
sudo ls /var/lib/rancher/rke/log
etcd-rolling-snapshots_aceb8d4c386e021a5f9a66ba3d481fba34dcbad874847bb341d7a3e7b62ee35a.log  kubelet_5cf86b2f2cea804ee7bab0ba08953f2bc7209ba6103a022ab08cf2dab220270e.log
etcd_c995b36c5493c12aee385f5d72cd24028007c338273e1af333beec0e845f86e4.log		     nginx-proxy_7c60dcb708336bbd19e7759dd55d332301de26d5faff2a7eed3224f3688c6eb6.log
kube-proxy_5d6622cc84ddba74ae6709b8b760a670481cb8d5b90c813fdcef5a67a30b2949.log
```

I validated this using a cluster with an all roles node and other cluster with dedicated etcd nodes.

This path is one of the two of what logging v2 (`rancher-logging`) will be collecting logs with the control plane logs option enabled in v2.5

**Comment by izaac** [comment]
Logging v1 includes this path in the secret `rancher-logging-fluentd -> cluster.conf`
