### ISSUE TITLE
Option in cluster.yml to enable nginx-ingress-controller validating webhook

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#2116]
**Description**
This is an RFE to add an option in the RKE cluster.yml file for enabling the nginx-ingress-controller validating webhook. The purpose of this webhook is to prevent a user from either intentionally or unintentionally misconfiguring nginx through incorrect ingress settings. See https://kubernetes.github.io/ingress-nginx/how-it-works/#avoiding-outage-from-wrong-configuration

Enabling this option currently involves several steps which could be automated during an RKE deployment. These steps are:
1. passing three flags to the ingress controller: `--validating-webhook`, `--validating-webhook-certificate`, and `--validating-webhook-key` (see also https://kubernetes.github.io/ingress-nginx/user-guide/cli-arguments/ ) 
2. The last two arguments require keys. Generate these keys and add them to the cluster (maybe as Secrets)
3. When deploying the ingress controller, mount the keys/secrets to the container.
4. Create a ClusterIP Service that routes traffic to the nginx admission webhook port
5. Create a ValidatingWebhookConfiguration resource to route CREATE and UPDATE verbs on Ingress resources to the Service

The option could look something like this in the RKE cluster.yml:
```
ingress:
  provider: nginx
  options:
    ...
  extra_args:
    ...
  validating_webhook: true
```

gz#6326

**Comment by dnoland1** [comment]
Thanks @skaven81, I've cut and pasted steps 4 and 5 into the above description.

**Comment by superseb** [comment]
@dnoland1 This will be enabled by default in NGINX 0.48.x in 2.5 and 2.6, is that sufficient for your request?

**Comment by dnoland1** [comment]
@superseb I believe so. @leodotcloud has taken ownership of this RFE.

**Comment by leodotcloud** [comment]
@superseb Thanks for the update. Having the validating webhook enabled by default addresses the original request.

**Comment by Sartigan** [comment]
Any options to disable this? It is not something we want by default. Very often the secret isn't created right away so the pod has the restart a few times before being in a ready status. We have to add a sleep to deploy an ingress after the creation of RKE...
