### ISSUE TITLE
RKE Removing node fails

### ISSUE THREAD

**Issue by cadditon** [rancher/rke#2122]
**RKE version:**
v1.1.2

**Docker version: (`docker version`,`docker info` preferred)**
19..03.11

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-1127.10.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VSphere
**cluster.yml file:**
nodes:
- address: 10.167.6.25
  role:
  - controlplane
  - etcd
  - worker
- address: 10.167.6.26
  role:
  - controlplane
  - etcd
  - worker
- address: 10.167.6.27
  role:
  - controlplane
  - etcd
  - worker
- address: 10.167.6.28
  role:
  - worker

**Steps to Reproduce:**
rke up with this 4 node cluster.  Remove last node from config, then run rke up again.

**Results:**
According to documentation, would expect the last node to successfully be removed from the cluster, instead it fails

```INFO[0018] [reconcile] Reconciling cluster state
INFO[0018] [reconcile] Check etcd hosts to be deleted
INFO[0018] [reconcile] Check etcd hosts to be added
INFO[0018] [hosts] Cordoning host [10.167.6.28]
INFO[0018] [hosts] Deleting host [10.167.6.28] from the cluster
FATA[0018] Failed to delete worker node [10.167.6.28] from cluster: nodes "10.167.6.28" not found```

**Comment by superseb** [comment]
Can you share `kubectl get nodes` after the initial `rke up` has completed? Also, can you share the output of the 2nd `rke up` with `--debug` added?

**Comment by cadditon** [comment]
The get nodes is below.  RKE v1.1.2 doesn't appear to have a --debug flag
```
kubectl get nodes
NAME                            STATUS   ROLES                      AGE   VERSION
rdctestappk8s01.lab-app.rdc.l   Ready    controlplane,etcd          87s   v1.17.6
rdctestappk8s02.lab-app.rdc.l   Ready    controlplane,etcd          89s   v1.17.6
rdctestappk8s03.lab-app.rdc.l   Ready    controlplane,etcd,worker   88s   v1.17.6
rdctestappk8s04.lab-app.rdc.l   Ready    worker                     83s   v1.17.6
```

**Comment by superseb** [comment]
Is that the full `cluster.yml`? Are you using the Kubernetes cloud provider and if so, is the configuration deployed manually n the nodes? Can you share the redacted output of `/etc/kubernetes/cloud-config`?

**Comment by cadditon** [comment]
I am using the VSphere cloud provider, the configuration is not manually deployed to the nodes.

/etc/kubernetes/cloud-config:
```
[Global]
user = "<User>"
password = "<Password>"
insecure-flag = "true"
datacenters = "<Datacenter>"
soap-roundtrip-count = "0"


[VirtualCenter "<Server>"]
        user = ""
        password = ""
        soap-roundtrip-count = "0"

[Workspace]
        server = "<Server>"
        datacenter = "<Datacenter>"
        folder = "RDC-ILAB-D"
        default-datastore = "RDC_ILAB_C01N1_NFS1"
        resourcepool-path = "/RDC/host/RDC/Resources/RDC-ILAB-RG"

[Disk]

[Network]
        public-network = "v1603-nw010-167-006-000-23_iLab_App"
```

**Comment by superseb** [comment]
Ok thanks, sorry for the back and forth, last question, can you share the output of:

```
kubectl get nodes -o jsonpath="{ .items[*]['metadata.name', 'metadata.labels.kubernetes\.io\/hostname']}"
```

**Comment by cadditon** [comment]
```
kubectl get nodes -o jsonpath="{ .items[*]['metadata.name', 'metadata.labels.kubernetes\.io\/hostname']}"
rdctestappk8s01.lab-app.rdc.l rdctestappk8s02.lab-app.rdc.l rdctestappk8s03.lab-app.rdc.l rdctestappk8s04.lab-app.rdc.l 10.167.6.25 10.167.6.26 10.167.6.27 10.167.6.28
```

**Comment by superseb** [comment]
Thanks for the info, this looks like a bug and I'm working on a fix but needs some more testing.

**Comment by cadditon** [comment]
In the meantime, can you outline the manual steps needed to perform a removal of a node from a cluster?

**Comment by sangeethah** [comment]
@bmdepesa We can test this with  Vsphere and cloudprovider enabled.

**Comment by bmdepesa** [comment]
Reproduced with RKE v1.1.2
* vsphere nodes w/ cloud provider
```
nodes:
- address: 172.16.132.23
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: 172.16.132.17
  user: ubuntu
  role: [worker]
cloud_provider:
  name: "vsphere"
  vsphereCloudProvider:
    global:
      ...
```
* `rke up`
* Remove the worker node from the cluster yml
* `rke up` fails
```
INFO[0024] [hosts] Deleting host [172.16.132.17] from the cluster
FATA[0024] Failed to delete worker node [172.16.132.17] from cluster: nodes "172.16.132.17" not found
```
* v1.2.0-rc15
* `rke up` with the same config
* The node is removed successfully
```
INFO[0044] [hosts] Deleting host [172.16.132.17] from the cluster
INFO[0044] [hosts] Successfully deleted host [172.16.132.17] from the cluster
```
* Afterwards, added 2 more nodes, then removed 2 nodes - all succeeded
