### ISSUE TITLE
RKE Segmentation Fault

### ISSUE THREAD

**Issue by kcalmond** [rancher/rke#2126]
User is experiencing similar seg fault behavior to this previously closed issue:
Centos 7 Segmentation fault https://github.com/rancher/rke/issues/313

They are following **air-gapped** installation process documented here: https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/

As a first step they were able to successfully run Rancher in docker (air-gapped setup). Hitting this problem when trying RKE based air-gapped configuration as next step.

Note the **System Config notes** section below. Steps copied from Dell manual for configuring ESX host for Nvidia GPU usage. Some steps in the config process of note:
* an NVidia Grid ViB is installed into the ESXi hypervisor
* BIOS MMIO settings adjusted

**RKE version:**
1.12

**Operating system and kernel:**

> **[root@rancher ~]# uname -a**
> Linux rancher 3.10.0-957.el7.x86_64 rancher/rke#1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> 
> **[root@rancher ~]# cat /etc/redhat-release**
> CentOS Linux release 7.6.1810 (Core)
> 
> **[root@rancher ~]# md5sum rke_linux-amd64-latest**
> 2d509f6c713d6fbc0e3ad70f3f5693f8  rke_linux-amd64-latest

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
* vSphere 6.5/ESX host: Dell R740 server with Nvidia P40 GPU
* problem reproducible on two different identically configured hosts

**cluster.yml file:**
not available: segmentation fault occurs on running rke command irrespective of what arguments are provided

**Steps to Reproduce:**

> **[root@rancher ~]# strace -f ./rke_linux-amd64-latest**
> execve("./rke_linux-amd64-latest", ["./rke_linux-amd64-latest"], [/* 25 vars */]) = 0
> --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0} ---
> +++ killed by SIGSEGV +++
> Segmentation fault
>

> **[root@rancher ~]# env**
> XDG_SESSION_ID=131
> HOSTNAME=rancher
> SELINUX_ROLE_REQUESTED=
> TERM=xterm
> SHELL=/bin/bash
> HISTSIZE=1000
> SSH_CLIENT=10.1.100.10 45442 22
> SELINUX_USE_CURRENT_RANGE=
> SSH_TTY=/dev/pts/0
> USER=root
> MAIL=/var/spool/mail/root
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
> PWD=/root
> LANG=en_US.UTF-8
> SELINUX_LEVEL_REQUESTED=
> HISTCONTROL=ignoredups
> SHLVL=1
> HOME=/root
> LOGNAME=root
> SSH_CONNECTION=10.1.100.10 45442 192.168.58.40 22
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> XDG_RUNTIME_DIR=/run/user/0
> _=/usr/bin/env
> OLDPWD=/mnt/cdrom
> 

**System Config notes** (provided by Dell)

> Config notes for the GPU install:
> 
> vGPU Install Manual https://images.nvidia.com/content/pdf/vgpu/guides/vgpu-deployment-guide-horizon-on-vsphere-final.pdf
> https://blogs.vmware.com/apps/2018/09/using-gpus-with-virtual-machines-on-vsphere-part-3-installing-the-nvidia-grid-technology.html
> https://docs.nvidia.com/grid/latest/grid-software-quick-start-guide/index.html
> 
> 1. Create NVIDIA Enterprise account https://www.nvidia.com/object/nvidia-enterprise-account.html
>         a. Use your corporate email address to register.
>         b. Use this to generate an Eval key, you will need this in the next step.
> 2. Setup your Nvidia Licensing Portal Account at https://nvidia.flexnetoperations.com
>         a. Download the NVIDIA vGPU for vSphere 6.x and place a copy on the /tmp directory on each host using WinSCP.
>         b. Download the License Manager for OS
> 3. Setup a guest VM setup that will become the license server. (minimum 2 vCPU and 4GB RAM)
>         a. Ensure that the 32 bit Java runtime is installed on it, and that there is no 64 bit runtime installed.
>         b. Copy the MAC address from the license server
>         c. Go back to the Nvidia Licensing Portal Account > Register License Server
>             i. Map Add-Ons > Add the number of units you’d like to use
>             ii. Download License File
>         d. Install the License Manager
>             i. License Management > Upload License
> 4. Set the GPU Device to vGPU Mode (Shared Passthru) Using the vSphere Host Graphics Setting
>         a. Configure > Hardware > Graphics > Host Graphics tab > Edit (Shared Direct, Spread VMs across GPUs)
>         b. esxcli graphics host set --default-type SharedPassthru
>                 esxcli graphics host get
> 5. Install the NVIDIA GRID VIB into the ESXi Hypervisor
>         a. esxcli system maintenanceMode set --enable true
>            lspci | grep -i nvidia
>            esxcli software vib install -v /tmp/NVIDIA-VMware_ESXi_6.7_Host_Driver_390.42-1OEM.670.0.0.7535516.vib
>            reboot
>            esxcli software vib list |grep -i nvidia
>            nvidia-smi  -For issues -  https://www.dell.com/support/article/at/en/atbsdt1/sln308065/dell-poweredge-14g-esxi-returns-failed-to-initialize-nvml-unknown-error-with-nvidia-gpu?lang=en
>            nvidia-smi -q | grep -i virtualization
>            esxcli system maintenanceMode set --enable false
> 6. Disable ECC (The Pascal architecture supports ECC memory but the NVIDIA GRID vGPU software does not. Newer cards will have this enabled by default.)
>         a. nvidia-smi -e 0
>            nvidia-smi -q
> 7. Verify GPU Installed
>         a. vCenter > Configure > Hardware > PCI Devices
>         b. nvidia-smi
> 8. Verify BIOS Settings
>         a. Set Power Supply to Non-Redundant
>         b. Only applies to M10 card in R740
>             i. Integrated Devices
>                  1. Memory Mapped I/O above 4GB: Enabled
>                  2. Memory Mapped I/O Base: 12TB - 512GB in labs
> 9. Setup guest VM setup that we can install guest drivers on and test licensing
>         a. Edit Settings > New Device > Shared PCI Device
>             i. Click Reserve All Guest Memory (Can verify in the Memory tab)
>             ii. GPU Profile: Number is the GB frame buffer, letter is the license type
>         b. Install GRID video drivers
> 10. Troubleshooting
>         a. If nvidia-smi command doesn’t not work you might have the wrong VIB installed for the ESXi version. We had to downgrade the VIB version for this to work.

**Comment by kcalmond** [comment]
@jiaqiluo Customer confirms that `rke up` also segfaults, returning "Illegal Instruction"
![rkesegfault](https://user-images.githubusercontent.com/12177199/85877048-6ae5be80-b78b-11ea-9f51-8af5c795c19f.jpg)

**Comment by jiaqiluo** [comment]
I tried RKE `v1.1.2`  on the following setup but cannot reproduce the bug

```

> uname -a
Linux rancher 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

> cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```

```

>  ./rke_linux-amd64
NAME:
   rke - Rancher Kubernetes Engine, an extremely simple, lightning fast Kubernetes installer that works everywhere

USAGE:
   rke_linux-amd64 [global options] command [command options] [arguments...]

VERSION:
   v1.1.2

AUTHOR:
   Rancher Labs, Inc.

COMMANDS:
     up       Bring the cluster up
     remove   Teardown the cluster and clean cluster nodes
     version  Show cluster Kubernetes version
     config   Setup cluster configuration
     etcd     etcd snapshot save/restore operations in k8s cluster
     cert     Certificates management for RKE cluster
     encrypt  Manage cluster encryption provider keys
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug, -d    Debug logging
   --quiet, -q    Quiet mode, disables logging and only critical output will be printed
   --trace        Trace logging
   --help, -h     show help
   --version, -v  print the version

```

**Comment by kcalmond** [comment]
The RKE was corrupt. SHA256 checksum mismatch vs https://github.com/rancher/rke/releases/download/v1.1.2/sha256sum.txt.  New copy of same version downloaded, checks ummed correctly, works in their env.
