### ISSUE TITLE
RKE Network Addon Job regularly times out

### ISSUE THREAD

**Issue by leflambeur** [rancher/rke#2143]
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare

**Steps to Reproduce:**
Start VMWare cluster and run rke up to provision it - 1/5 times it works fine but often it's unsuccessful for various customers

The job seems to time out just as it reaches the point of succeeding (around 31-32s)

**Results:**
Increasing the addon job timeout seems to resolve this so it should be increased by default

For the customers who don't see a delay it won't affect them and for those who do it will mean a better success of provisioning in the future

Example Error Message:

```
Initial provisioning fails with this error-message: 
time="2020-06-16T14:20:25+02:00" level=fatal msg="Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
```

gz#10699

gz#9105

**Comment by pasikarkkainen** [comment]
Yep, I'm seeing the same problem, and increasing the timeout fixes it for me aswell.
My previous related issue about the same problem: https://github.com/rancher/rke/issues/1652

**Comment by pasikarkkainen** [comment]
this is still a valid issue, and can be fixed by increasing the default rke addon job timeout.

**Comment by bmdepesa** [comment]
Reproduced in RKE v1.1.2 with nodes in vSphere
```
FATA[0240] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
```

With RKE v1.2.2-rc3 and another node with the same config
```
...
INFO[0128] [addons] Executing deploy job rke-network-plugin
INFO[0129] [addons] Setting up coredns
...
INFO[0320] Finished building Kubernetes cluster successfully
```
