### ISSUE TITLE
Allow calico with native VXLAN networking without flannel

### ISSUE THREAD

**Issue by elmariofredo** [rancher/rke#2148]
Calico allows to create own overlay with flexible IPAM please see https://www.projectcalico.org/live-migration-from-flannel-to-calico/ according to documentation https://rancher.com/docs/rke/latest/en/config-options/add-ons/network-plugins/#calico-network-plug-in-options there is no support for that in RKE. 

Change should be quite simple according to this documentation https://docs.projectcalico.org/getting-started/kubernetes/installation/config-options#switching-from-ip-in-ip-to-vxlan we could add that environment variable when provider like 'none' or 'vxlan' is set in config.

**Comment by chaudhryfaisal** [comment]
requesting to re open this issue
