### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by possani** [rancher/rke#2163]
**RKE version:**
```
v2.4.3
```
**Docker version: (`docker version`,`docker info` preferred)**
```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
4.14.138-rancher
```
**Steps to Reproduce:**
Add a [configuration snippet](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#configuration-snippet) to Nginx:
```
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_header Access-Control-Allow-Origin $http_origin;
```
**Results:**
```
Error: exit status 1
2020/07/16 08:20:44 [emerg] 3585#3585: unknown directive "more_set_header" in /tmp/nginx-cfg686709319:4691
nginx: [emerg] unknown directive "more_set_header" in /tmp/nginx-cfg686709319:4691
nginx: configuration file /tmp/nginx-cfg686709319 test failed
```
**Additional Information:**
Container image:
```
rancher/nginx-ingress-controller:nginx-0.32.0-rancher1
```
It might be related to Kubernetes issue [2535](https://github.com/kubernetes/ingress-nginx/issues/2535)

**Comment by superseb** [comment]
The directive is `more_set_headers` as described on https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#configuration-snippet. Let me know if that doesn't solve the issue.

**Comment by possani** [comment]
It still does not set the header (Access-Control-Allow-Origin) but the error is gone. Thank you for pointing that out.
