### ISSUE TITLE
Unable to use ipv6 addresses in cluster.yml

### ISSUE THREAD

**Issue by boxboatmatt** [rancher/rke#2165]
RKE version: 1.1.3

Steps to Reproduce:
Use ipv6 addresses in `cluster.yml`; however using hostname that resolves to ipv6 address will work. `cluster.yml` should probably support ipv6 addresses.

Results:
```
 ./rke up
INFO[0000] Running RKE version: v1.1.3
INFO[0000] Initiating Kubernetes cluster
FATA[0000] Failed to validate cluster: Hostname_override [2600:1f18:199c:200:7625:48ac:5635:3252] for host (1) is not valid: [a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

**Comment by boxboatmatt** [comment]
Anyone take a look at this?

**Comment by steve-bitdotio** [comment]
@boxboatmatt looks like this issue is still relevant today. Can we re-open this issue?

Note that this is related to https://github.com/rancher/rke/issues/2819.

**Comment by sgreene570** [comment]
@gucki looks like this issue is still relevant today. Can we re-open this issue?

Also, note that this is related to https://github.com/rancher/rke/issues/2819

**Comment by gucki** [comment]
@sgreene570 Unfortunately, I'm a regular user and thus don't have any rights to reopen issues on this project.
