### ISSUE TITLE
Upstream modifications

### ISSUE THREAD

**Issue by orbatschow** [rancher/rke#2175]
As discussed with @dramich I would like to know whether 
there is any modification involved when deploying Kubernetes with rke, or if it is plain upstream Kubernetes.

This is relevant for my bachelor thesis regarding citation concerns.

**Comment by ibuildthecloud** [comment]
RKE runs unmodified Kubernetes using upstream binaries.  The binaries are currently copied from the upstream hyperkube image. The Dockerfiles here show how we build the images that contain Kubernetes https://github.com/rancher/hyperkube/tree/v1.18.

Going forward RKE2 (https://github.com/rancher/rke2), the next major iteration of RKE, will use unmodified Kubernetes source but will be compiling the binaries ourselves to ensure that Kubernetes is FIPS 120-2 compliant.

**Comment by ibuildthecloud** [comment]
FYI, I'm the Rancher Labs CTO. So if you are looking for an authoritative source, I am it.

**Comment by orbatschow** [comment]
Thank you very much for taking the time to answer this question!

This is more than enough for my needs. 👍
