### ISSUE TITLE
rke failed to reconcile etcd plane after public IP address changed when private IP address is configured/used

### ISSUE THREAD

**Issue by Amos-85** [rancher/rke#2187]
**RKE version:** 1.1.4

**Docker version:** 19.03.11

**Operating system and kernel:** Rancher OS 1.5.6

**Type/provider of hosts:** AWS

**cluster.yml file:** created through rke terraform provider`

**Steps to Reproduce:**

- Install rke cluster on ec2 with 3 etcd instances and fill in `internal address` in every node field in cluster.yml.

- shut down all instances.
- start all instances.

- check `kubectl get cs`:

`scheduler                Healthy   ok
controller-manager   Healthy   ok  
etcd-0                       Healthy   {"health":"true"}`

- run rke up.

**Results:**
`Failed running cluster err:Failed to reconcile etcd plane: Etcd plane nodes are replaced. Stopping provisioning. Please restore your cluster from backup.`

**Expected Behavior:**

- rke won't exit with reconcile exception while using `internal_address` and only the public addresses of etcd nodes has been changed.

**Comment by superseb** [comment]
Although technically this should be possible (I don't think we do anything with `address` that we need to preserve when reconciling), we don't support changing IPs of nodes.

The diff of nodes is done on `Address` here: https://github.com/rancher/rke/blob/v1.1.4/hosts/hosts.go#L377. We can change that, the only thing I can think of is the node object name that will be wrong and possibly get a new node leaving the old one behind.
