### ISSUE TITLE
rke up on airgap cluster w rancher-save-images.sh

### ISSUE THREAD

**Issue by Crazyscorpio88** [rancher/rke#2189]
**RKE version:** 
1.1.4
**Docker version: (`docker version`,`docker info` preferred)**
Docker version 19.03.5, build 633a0ea838f1
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
SLES15 SP1
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare Metal
**cluster.yml file:**
cluster_name: cluster-dev

authentication:
    strategy: x509
    sans:
      - "rancher.cluster.lan"

nodes:
- address: 172.16.255.250
  user: root
  role: [ "controlplane", "etcd", "worker" ]
- address: 172.16.255.251
  user: root
  role: [ "controlplane", "etcd", "worker" ]
- address: 172.16.255.252
  user: root
  role: [ "controlplane", "etcd", "worker" ]

private_registries:
- url: 172.16.255.1:5000
  is_default: true
**Steps to Reproduce:**
rke up --config cluster.yml
**Results:**
Error rke-tools manifest unknown

Also another problem with Rancher/hyperkube:v1.18.6-rancher1
**Solution**
Rancher-images.txt need to add those 2 images:
- rancher/rke-tools:v0.1.59
- rancher/hyperkube:v1.18.6-rancher1

Thanks

**Comment by superseb** [comment]
This will be handled in https://github.com/rancher/rancher/issues/28026
