### ISSUE TITLE
Update Ingress version to the latest

### ISSUE THREAD

**Issue by maggieliu** [rancher/rke#2207]
There is a need to get Ingress controller that supports TLSv1.3 by default, which is 0.33.0+

gz#11809

**Comment by maggieliu** [comment]
Ingress controller is updated to 0.35 in 1.16.15, 1.17.12, 1.18.9 and 1.19.2

**Comment by sangeethah** [comment]
Validated as part of https://github.com/rancher/rancher/issues/28838#issuecomment-695152397
