### ISSUE TITLE
docker install script

### ISSUE THREAD

**Issue by maxisam** [rancher/rke#2210]
Just a suggestion. I think it would be a good idea to have 

log size limitation setup like official doc in the docker installation script https://github.com/rancher/install-docker
https://kubernetes.io/docs/setup/production-environment/container-runtimes/

It can be a problem without it. The log size can grow to 10+G in a few days.

**Comment by superseb** [comment]
Hi @maxisam , thanks for the suggestion. Our docker-install is a mirror of upstream but with a fixed version to make it possible to install that exact version (and not latest). Any modifications/configuration needed, needs to be applied by the user/operator.

**Comment by maxisam** [comment]
well, do you think it is possible to let RKE take care of this?
