### ISSUE TITLE
kube-apiserver is not restarted after changing audit log configuration

### ISSUE THREAD

**Issue by soon-leong** [rancher/rke#2217]
**RKE version:** 
1.1.4

**Docker version: (`docker version`,`docker info` preferred)**
19.03.12

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian GNU/Linux 9 (stretch)
Kernel Version: 4.14.132

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware ESXi Server

**cluster.yml file:**
cluster_name: test
nodes:
- address: x.x.x.x
  user: root
  role:
    - controlplane
    - etcd
    - worker
  ssh_key: |-
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
services:
  kube-api:
    audit_log:
      enabled: true
      configuration:
        path: /var/log/kube-audit/audit-log.json
        format: json
        policy:
          apiVersion: audit.k8s.io/v1
          kind: Policy
          rules:
            - level: Metadata
              resources:
                - group: "" # core
                  resources: ["secrets", "configmaps"]
                - group: authentication.k8s.io
                  resources: ["tokenreviews"]
              omitStages:
                - "RequestReceived"

**Steps to Reproduce:**
1. Run rke up to create the cluster.
2. Run tail -f /var/log/kube-audit/audit-log.json to view the events in the audit log
3. Edit cluster.yml. Change the audit level from Metadata to None.
4. Run rke up.

**Results:**
When the audit level is changed to None, the audit events should not be written to the audit log but they continued to appear in the audit log.

**Comment by soon-leong** [comment]
@superseb any estimate when the bug fix can be available? Thanks!

**Comment by soon-leong** [comment]
Which version will the bug fix be available? Thanks!

**Comment by Ellenqs** [comment]
My test can reproduce this issue. details as below

**RKE version:**
v1.2.3

**Docker version:** (docker version,docker info preferred)
19.03

**Type/provider of hosts:** (VirtualBox/Bare-metal/AWS/GCE/DO)
AWS EC2

**YAML file used to test:**
//
nodes:
  - address: xxxxxxxx
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: ~/path/to/key
services:
    kube-api:
      audit_log:
        enabled: true
        configuration:
          path: /var/log/kube-audit/audit-log.json
          format: json
          policy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
              - level: Metadata
                resources:
                - group: "" # core
                  resources: ["secrets", "configmaps"]
                - group: authentication.k8s.io
                  resources: ["tokenreviews"]
                omitStages:
                - "RequestReceived"
 //
**Steps:**
1.Run rke up to create the cluster.
2.Run tail -f /var/log/kube-audit/audit-log.json to view the events in the audit log
3.Edit cluster.yml. Change the audit level from Metadata to None.
4.Run rke up.  

      **Results:**
When the audit level is changed to None, the audit events should not be written to the audit log but they continued to appear in the audit log.

**Comment by Ellenqs** [comment]
Validated on RKE `v1.2.6-rc3` and `v1.3.0-rc1`.

Docker version: 19.03

**Type/provider of hosts**: AWS ec2

Use the same YAML file^^^.

**Steps:**

1.Run `rke up` to create the cluster.
2.Run tail -f /var/log/kube-audit/audit-log.json to view the events in the audit log
3.Edit cluster.yml. Change the audit level from Metadata to None.
4.Run `rke up` again.

**Results:**
After changing the audit level from Metadata to None. There are only old logs, no new audit event showing up in audit log.
