### ISSUE TITLE
Add stubdomains to CoreDNS provider

### ISSUE THREAD

**Issue by m4ce** [rancher/rke#2236]
Just like kubedns, can we have support for stubdomains in the CoreDNS provider? At the moment, there's no way to manage them unless manually editing the coredns configmap.

I am also looking to automate this using the terraform rancher2 provider (https://github.com/rancher/terraform-provider-rancher2/issues/454).

**Comment by Hitesh-Agrawal** [comment]
We need this functionality to automate our Rancher workflow end to end.

**Comment by m4ce** [comment]
Any chance this could be evaluated? I can see rke has stub-domains support for kube-dns but not for coredns. The issue is that we currently have to edit the configmap and we cannot quite manage that via terraform unless we adopt the resource (import). It'd be nice to be able to drive the coredns configuration directly from rke.

**Comment by m4ce** [comment]
We also have a reoccurring issue due to the fact that the stubdomains are not managed by the rke workflow. Whenever we perform an upgrade to the cluster, e.g. kubernetes version, the coredns configmap gets wiped out. This obviously leads to a production issue..

**Comment by m4ce** [comment]
@superseb - do you think this is something that RKE can support soon?

**Comment by jasonhancock** [comment]
I'd also like the knobs in the codedns configmap exposed and configurable from the rancher2 terraform provider.

**Comment by jdambly** [comment]
I would also like to be able to update the configmap for coreDNS. I have a need to update the cache plugin config, and would also like to use autopath.

**Comment by Blackclaws** [comment]
I've also run into this problem. The reason being that we're running a server away from the central network connected via wireguard. We want only certain domains to dns resolve via the vpn dns server.
