### ISSUE TITLE
Handling etcd Add/Remove

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#225]
RKE should be able to handle add and remove for etcd nodes, rke also should be able to handle adding and removing simultaneously.

**Comment by galal-hussein** [comment]
Can be tested with v0.0.10-dev

**Comment by soumyalj** [comment]
Tested with rke version 0.0.12-dev. Addition and removal of etcd nodes is functional. Tested the below use cases. After each addition/removal of etcd node, ensure cluster is functional by adding new pods and verify etcd cluster health by exec'ing into etcd container[etcdctl cluster-health]
1. Add a new etcd node
2. Remove an etcd node
3. Add and remove etcd node at the same time
4. Start with a single node cluster. Add another node to make it a two node cluster. Add another node and make it a 3 node cluster
5. Start with a 3 node cluster, keep removing one node each time to make it single node cluster
6. Add/remove etcd role along with other roles to the nodes.
