### ISSUE TITLE
Add util subcommand for admin tasks

### ISSUE THREAD

**Issue by superseb** [rancher/rke#2258]
Add `rke util` subcommand with admin tasks, initially with these commands:

- `get-state-file`: attempts to retrieve state file using kubeconfig, else connects to the nodes and retrieves it using Docker and local files in `/etc/kubernetes`
- `get-kubeconfig`: as kubeconfig is not a separate resource in the cluster, this option will extract it from the state file

**Comment by superseb** [comment]
To test this, the commands should be available in `rke util` and you should be able to retrieve the rkestate and kubeconfig file. If they exist, they should me moved to a filename mentioned in the log. If they dont exist, they should just be retrieved and placed. If there is anything unclear from the log and/or where the files are placed, or it breaks something, its a bug.

**Comment by Ellenqs** [comment]
Tested on v1.2.5-rc1

Steps:
1. Launch 3 ec2 machine, bring up a rke cluster of three nodes with cluster.yml file on my local machine. The kube_config_cluster.yml and cluster.rkestate files are created. 
2. run `./rke util get-state-file`, it will create another rkestate file, run `./rke util get-kubeconfig`  , can move/copy the state file and config file to new files(rkestate003954000, kube_config473552893)

>  % ls
cluster.rkestate	kube_config473552893				rke_darwin-amd64	rkestate003954000
cluster.yml		kube_config_cluster.yml	rke			rke_linux-amd64		test.yml


3. On remote ec2 instance, install the same rke, move cluster.yml on to the instance. Do not need to do rke up. There is no kube_config_cluster.yml and cluster.rkestate at all.
4. run `./rke util get-state-file`, it will create another rkestate file, run `./rke util get-kubeconfig`  ,  kube_config_cluster.yml and cluster.rkestate are created.

> $ ls
cluster.rkestate  cluster.yml  kube_config_cluster.yml  rke


Also, the logs can show which file it created and saved. 

> INFO[0002] Successfully Deployed local admin kubeconfig at [./kube_config_cluster.yml] 
INFO[0000] Copied file [./kube_config_cluster.yml] to new location [kube_config763765289] as back-up
INFO[0000] Successfully Deployed state file at [./cluster.rkestate] 
INFO[0000] Moved file [./cluster.rkestate] to new location [rkestate356585241] as back-up

**Comment by Ellenqs** [comment]
Validated the two subcommands of RKE v1.3.0-rc1, the steps and cases are the same as previous tests on v1.2.5-rc1 , all tests passed.
