### ISSUE TITLE
RKE: The container name "/cert-deployer" is already in use by container

### ISSUE THREAD

**Issue by JessedeJonge** [rancher/rke#2264]
**RKE version:**
1.2.0

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 19.03.13, build 4484c46d9d

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare Metal

**Steps to Reproduce:**
When trying to add new nodes to my bare metal cluster and running either (rke up or rke up --update only) I get a fatal error: The container name "/cert-deployer" is already in use by container xxx. Manualy stopping (docker stop) and removing (docker rm) that container does not work. This does not happen on the same node all the time.

Sometimes it also returns Error: No such container: cert-deployer. This makes it look like RKE is not properly waiting for removals/starts of the container.

**Comment by JessedeJonge** [comment]
This seems to be resolved by scaling down the amount of pods of a certain high amount of pods deployment (700). This probably makes container spawning and killing faster. RKE needs better timeouts to resolve this.

**Comment by superseb** [comment]
Please include full logging using `--debug` to have an indication of what is attempted and where it fails. There are already retries done by most Docker interactions, possibly one or more actions are missed when we applied that logic. Also please describe what the error is when you manually try to stop or remove it, and if possible, the output of `docker inspect cert-deployer` when the error occurred.

**Comment by seanlees** [comment]
> 这似乎可以通过在一定数量的Pod部署中缩减Pod的数量来解决（700）。这可能会使容器产生和杀死更快。RKE需要更好的超时来解决此问题。

I think you're right .   I have the same problem. Restart docker to solve it
