### ISSUE TITLE
can't build rke binary from my Mac(High Sierra 10.13.1)

### ISSUE THREAD

**Issue by xiaohui-zhangxh** [rancher/rke#227]
When exectuting `make` from this project, it will fetch dapper from `https://releases.rancher.com/dapper/latest/dapper-Darwin-x86_64`, this binary is crashed with this error message:

```
➜  rke-src git:(master) ✗ ./dapper-Darwin-x86_64.dms -v
[1]    83670 segmentation fault  ./dapper-Darwin-x86_64.dms -v
```

I need to build my own rke binary ASAP since current version doesn't support customized Docker graph DIR, see #226

**Comment by galal-hussein** [comment]
@xiaohui-zhangxh This is probably a dapper issue, can you open issue with rancher/dapper repo, in the mean time you can build using `go build` normally
