### ISSUE TITLE
Cisco ACI CNI plugin

### ISSUE THREAD

**Issue by superseb** [rancher/rke#2271]
Add code for enabling Cisco ACI CNI plugin

Todo:

- RKE types to support new CNI (`rancher/rke`)
- RKE code to add new CNI (`rancher/rke`)
- KDM code to add k8s template and addon deploy templates (`rancher/kontainer-driver-metadata`), this is planned to go into the next k8s releases but we can create a new `rancher1-X` release for the currently released versions to test

**Comment by bmdepesa** [comment]
@superseb can you provide some details on how we can test this?

**Comment by bmdepesa** [comment]
@izaac We only need to perform a regression test via our automated tests when this is available to-test.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-rc4
rancher/rancher:master-head 495f7a1

* Performed regression testing on RKE through Rancher automation runs (provisioning clusters & automation)
