### ISSUE TITLE
Per node K8S service configuration

### ISSUE THREAD

**Issue by caiconkhicon** [rancher/rke#2276]
**RKE version:**
1.1.9

**Docker version: (`docker version`,`docker info` preferred)**
19.3.12

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.5

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VSphere/OpenNebula

**Description**
Each node (in fact, better to say "node group") has a different role in the K8S cluster (worker, controlplane, etcd), and maybe different resource specification (CPU, RAM). Thus, it should be able to run K8S services with different parameters on each node. 

In my specific case, I have 2 node groups: master (controlplane + etcd) and worker. Because the master nodes run more K8S required processes (e.g. etcd, kube-api), I want to set a higher resource reservation for these nodes over `kubelet`. With the config file `cluster.yml` of RKE, I only can set `kubelet` configuration for all nodes. I don't want to waste resource on the Worker nodes, since the resource reservation is applied to all nodes.

Thus, having a per-node K8S service configuration is an important feature.

**Comment by caiconkhicon** [comment]
The issue !2063 seems to require a same feature as this one.

**Comment by pasikarkkainen** [comment]
Yes please, there's multiple scenarios where one needs to tweak for example kubelet parameters *per node*, for example node-ip parameter.. existing rke issue: "add ability to force set node-ip argument on kubelet": https://github.com/rancher/rke/issues/900 . there are multiple such request in rke issues list.

**Comment by slavniyteo** [comment]
I vote for this feature. 

Single kubelet config for all nodes stops me from configuring [static cpu-manager-policy](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/) as it requires specifying `--reserved-cpus` for each node.

**Comment by slavniyteo** [comment]
still issue

пт, 8 янв. 2021 г., 10:51 stale[bot] <notifications@github.com>:

**Comment by caiconkhicon** [comment]
This feature is still required

**Comment by slavniyteo** [comment]
still issue

**Comment by DeamonMV** [comment]
This feature is still required

**Comment by ntqp97** [comment]
This feature is still required
