### ISSUE TITLE
rke-ingress-controller deployment problem

### ISSUE THREAD

**Issue by Med-All** [rancher/rke#2288]
I'm going over the Rancher Training at the point to start the cluster got that warning:

```
Failed to deploy addon execute job [rke-ingress-controller]: Failed to get job complete status for job rke-ingress-controller-deploy-job in namespace kube-system
```

Any thoughts on that?

**Comment by superseb** [comment]
You can use `kubectl -n kube-system logs -l job-name=rke-ingress-controller-deploy-job` to get the logs from the jobs that are responsible for deploying nginx ingress. Can you share your `cluster.yml` file?

Can you also check if the nodes do not have a condition that could prevent deployment:
```
kubectl get nodes -o go-template='{{range .items}}{{$node := .}}{{range .status.conditions}}{{$node.metadata.name}}{{": "}}{{.type}}{{":"}}{{.status}}{{"\n"}}{{end}}{{end}}'
```

**Comment by Med-All** [comment]
Well, now I can't even get to that point. It errors out on TLS:

```
WARN[0033] [etcd] host [10.105.1.xxx] failed to check etcd health: failed to get /health for host [10.105.1.xxx]: Get "https://10.105.1.xxx:2379/health": remote error: tls: bad certificate
FATA[0033] [etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [10.105.1.xxx] failed to report healthy. Check etcd container logs on each host for more information
```

I thought TLS cert is autogenerated.

**Comment by superseb** [comment]
This usually happens when nodes are re-used and they are not cleaned properly causing certificates or other files to conflict. This can be done using `rke remove` or manually, see https://rancher.com/docs/rke/latest/en/managing-clusters/#removing-kubernetes-components-from-nodes
