### ISSUE TITLE
Failed to create SubnetManager

### ISSUE THREAD

**Issue by zhangwj-HS** [rancher/rke#229]
**RKE version:*0.0.9*

**Docker version: (Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 17.03.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.702 GiB
Name: rancher-server-180
ID: V6DR:2OFG:G43S:3KVT:B467:N4TE:TAUR:T3UO:QLAW:HSYJ:DX45:IIGR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com
Live Restore Enabled: false
)**

**Operating system and kernel: (`NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7")**

**Type/provider of hosts: VirtualBox**

**Steps to Reproduce:**

**Results:**
I0115 04:14:29.903857       1 main.go:487] Using interface with name enp0s8 and address 192.168.1.183
I0115 04:14:29.903901       1 main.go:504] Defaulting external address to interface address (192.168.1.183)
E0115 04:14:29.904961       1 main.go:231] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-49f5z': Get https://10.233.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-49f5z: dial tcp 10.233.0.1:443: getsockopt: connection refused

**Comment by superseb** [comment]
Can you show the output of `docker logs kube-api` and `docker logs kubelet` from the `controlplane` node?

**Comment by superseb** [comment]
If you can share your `cluster.yml` and the box you are using in VirtualBox, we can try to reproduce.

**Comment by hemanthavs** [comment]
@superseb Occasionally  we are seeing this error but eventually cluster is stabilized after a while

Created another issue for it https://github.com/rancher/rke/issues/329

Here are the logs requested

[kube-api.log](https://github.com/rancher/rke/files/1701910/kube-api.log)
[kubelet.log](https://github.com/rancher/rke/files/1701911/kubelet.log)

**Comment by hemanthavs** [comment]
These issues are happening because cluster_cidr is conflicting with my vm's private networking on 10.x networking in my case.

No longer facing the issue when using 172.x addresses for cluster_cidr
