### ISSUE TITLE
SSH Bastion connection reset by peer

### ISSUE THREAD

**Issue by XciD** [rancher/rke#2290]
**RKE version:**
v1.2.0
**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-118-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.643GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
4.15.0-118-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

```
Openstack VM
```

**cluster.yml file:**

Generated with rke terraform provider 

**Steps to Reproduce:**

Create a cluster with more than 20 nodes with a ssh bastion

**Results:**

Crash randomly with error like:
```
cannot proceed with upgrade of worker since 2 host(s) cannot be reached prior to upgrade
time="2020-10-21T11:09:58+02:00" level=warning msg="Failed to set up SSH tunneling for host [10.250.0.23]: Can't retrieve Docker Info: error during connect: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info\": Failed to dial ssh using address [10.250.0.23:22]: Failed to connect to the bastion host [51.210.38.174:22]: ssh: handshake failed: read tcp 10.46.16.47:61110->51.210.38.174:22: read: connection reset by peer"
time="2020-10-21T11:09:58+02:00" level=warning msg="Failed to set up SSH tunneling for host [10.250.0.9]: Can't retrieve Docker Info: error during connect: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info\": Failed to dial ssh using address [10.250.0.9:22]: Failed to connect to the bastion host [51.210.38.174:22]: ssh: handshake failed: read tcp 10.46.16.47:61108->51.210.38.174:22: read: connection reset by peer"
```

Seems like the rke tools don't re-use the ssh connexion, so sometime the bastion refuse the connexion ( to much open ?)
When I spawn a cluster with 22 nodes for example, I have 126 connexion open when I do a rke up
```
netstat -natp | grep :22 | wc -l
126
```

**Comment by superseb** [comment]
Does the SSH server log anything extra in this case?

**Comment by XciD** [comment]
Seems like the SSH server don't receive the connection.

I work trough a VPN, so maybe it's related.

Could we adapt the code to re-use a connection ? or a least retry ?

**Comment by BarthV** [comment]
Same issue here.
I think RKE is spamming hard sshd daemon and tries to create too many connection at once during RKE startup.

@XciD  have you tried increasing sshd limits :
/etc/ssh/sshd_config

MaxAuthTries 15
MaxSessions 250
MaxStartups 450
It seems working on my side.

for RKE teams I think adding a short (configurable ?) delay to allow sshd bastion host to cool down its counters should be an option to consider :)

thanks

**Comment by aledegano** [comment]
Hello, I have been hit by this issue myself which had me scratching my head for 3 days.
Luckily the solution proposed above by @BarthV works and fixed my issue.
I am writing because I still believe that the situation could be improved by either:

1. Document clearly in the requirements that when using a bastion host the SSHd parameters need to be changed to allow a connection per node to work as intended
2. a built-in system to connect to the nodes in batches avoiding the flood of connections to the bastion (might still be useful for very large clusters)

**Comment by mickael-carl** [comment]
A good alternative is to use [SSH's ControlMaster configuration option](https://man.openbsd.org/ssh_config.5#ControlMaster) to allow reusing connections. This means that no changes is required server-side (since that might not always be possible). For instance, in `~/.ssh/config`:
```
ControlMaster auto
ControlPath ~/.ssh/sockets/%r@%h-%p
ControlPersist 120
```
