### ISSUE TITLE
Failed to create an rke cluster on rhel 7.8 

### ISSUE THREAD

**Issue by nlalchandani** [rancher/rke#2294]
**RKE version:**
latest
**Docker version: (`docker version`,`docker info` preferred)**
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 7.8
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hosted On Premise 
[rke.zip](https://github.com/rancher/rke/files/5426020/rke.zip)
VM
**cluster.yml file:**
attached
**Steps to Reproduce:**
We installed docker as root on 3 nodes
Then we used non root id to setup ssh between the 3 nodes with the id
See cluster.yml used
Installed using rke up fails – see log attached as well other logs
**Results:**
160] [workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [lwtd104.wdclab.net]: Get http://localhost:10248/healthz: Unable to access the service on localhost:10248. The service might be still starting up. Error: ssh: rejected: connect failed (Connection refused), log: E1022 15:25:58.971627 102219 kubelet.go:2188] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized]
[rke.zip](https://github.com/rancher/rke/files/5426024/rke.zip)

**Comment by superseb** [comment]
Is there a host firewall configured? Does it work when you disable it? If that's not possible, can you check if TCP/10248 is getting blocked? I assume `/etc/hosts` is properly setup with `127.0.0.1 localhost`.

**Comment by superseb** [comment]
Let me know if we need to investigate.
