### ISSUE TITLE
Difference between 1.1 code line and 1.2 code line.

### ISSUE THREAD

**Issue by joeburke30** [rancher/rke#2311]
**RKE version:**
1.1.10 vs 1.2.1

What is the fundamental differences in the minor versions being released?...   
The 1.1 family seems to still be under active development as well as the 1.2 family.
Is there any collateral / website that highlights why to choose one over the other?

Thanks,
Joe

**Comment by superseb** [comment]
There is no specific definition of the branches. The RKE minor version aligns with the Rancher minor version, e.g. RKE 1.1 is Rancher 2.4 and RKE 1.2 is used in Rancher 2.5. The latest available minor release versions will contain the newest/latest features which are may or may not be backported to the earlier release. If you look at the current state, RKE 1.1 does not provide Kubernetes 1.19 while this available in RKE 1.2. The source for new features is the changelog included for each release. Also, features/enhancements that are only available in a certain minor version should be called out in the docs of this feature/enhancement.

Let me know if you have any other questions.
