### ISSUE TITLE
How to move a RKE deployed K8s 3-node cluster to a new subnet

### ISSUE THREAD

**Issue by joalmjoalm** [rancher/rke#2332]
Running a 3-node K8s cluster w Calico networking. Cant find in docs how to move an existing cluster to a new subnet.
Currently: 3 nodes on 192.168.1.0 subnet ( 192.168.1.10, 192.168.1.20, 192.168.1.30)
Target: move these same 3 nodes to 192.168.2.0 subnet  ( 192.168.2.10, 192.168.2.20, 192.168.2.30)

Can this be achieved with the deployment yaml as an upgrade?

/J

**Comment by superseb** [comment]
The nodes already have the new IPs or are you planning this? Basically removing a node, cleaning and adding should be possible (if they can talk to each other on different subnets), else you can restore a snapshot to cleaned nodes with the updated `cluster.yml`. Changing the IPs in `cluster.yml` and `rke up` does not support this action, at least not for etcd.
