### ISSUE TITLE
Update README to say what the stable and latest versions are

### ISSUE THREAD

**Issue by catherineluse** [rancher/rke#2350]
We've had a recurring issue where customers accidentally downgrade their RKE version because github.com/rancher/rke/releases/latest often redirects to a version that's not the true latest version.

Craig said an automated solution is possible:

> For k3s/rke2, we actually built a little service that handles this so that the get.k3s.io install script will by default install what we deem as “stable” not the latest-by-date release (which is what it used to do) and so that you can specify a channel such as stable, latest, 1.18, or 1.19 and get the appropriate most-recent release for each. Would be pretty simple to stand the same thing up for RKE1 and point the readme docs at it.

But until an automated solution exists, we should update the RKE README to say what the stable and latest versions are.

**Comment by superseb** [comment]
After discussing with @maggieliu , we only list the latest version in the README. We will check out if we can utilize channelserver to return the latest semver version.

**Comment by superseb** [comment]
This is now available via https://github.com/rancher/rke/#latest-release
