### ISSUE TITLE
Docker deprecated in K8s

### ISSUE THREAD

**Issue by mscbpi** [rancher/rke#2364]
With docker, as a container engine, being deprecated in future versions of Kubernetes, what does it mean for RKE1 which not only uses docker as container engine for K8s but also to launch core components of K8s ?

**Comment by mscbpi** [comment]
I guess the answer is RKE2, using containerd as runtime, kubelet as service and other components as pods.

Hopefully the promised migration path works well, that's a challenge !

Thanks !

**Comment by immanuelfodor** [comment]
I feel this issue is duplicate of https://github.com/rancher/rke/issues/94

**Comment by mscbpi** [comment]
right, let's close this issue.
