### ISSUE TITLE
Adding new nodes to existing cluster fails

### ISSUE THREAD

**Issue by donkeyx** [rancher/rke#2366]
**RKE version:**
`rke version v1.0.14`

**Docker version: (`docker version`,`docker info` preferred)**
```shell
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```shell
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`proxmox vm`

**cluster.yml file:**
https://gist.github.com/donkeyx/efa8ef2297df801c00948ebf44656dad

**Steps to Reproduce:**
Create a cluster without nodes .40/.41 then add to cluster.yml and run the UP with update-only.  
`rke up --update-only`

New nodes 40/41 are not added to the cluster and if fails with a fatal error. 

**Results:**

When updating, it will output these errors and the two new nodes are not available in the kubes cluster. From the logs it does seem to be interacting with the new nodes 40/41 but does not end up working. I have previously added a node with no problems. 

```shell
...
INFO[0075] [worker] Now checking status of node 10.172.10.40, try #1
ERRO[0101] Host 10.172.10.40 failed to report Ready status with error: [worker] Error getting node 10.172.10.40:  "10.172.10.40" not found
INFO[0101] [worker] Now checking status of node 10.172.10.41, try #1
ERRO[0126] Host 10.172.10.41 failed to report Ready status with error: [worker] Error getting node 10.172.10.41:  "10.172.10.41" not found
...
INFO[0184] Image [rancher/rke-tools:v0.1.66] exists on host [10.172.10.34]
INFO[0184] Image [rancher/rke-tools:v0.1.66] exists on host [10.172.10.40]
INFO[0184] Image [rancher/rke-tools:v0.1.66] exists on host [10.172.10.41]
INFO[0184] Image [rancher/rke-tools:v0.1.66] exists on host [10.172.10.32]
INFO[0186] Starting container [rke-log-cleaner] on host [10.172.10.40], try #1
INFO[0186] Starting container [rke-log-cleaner] on host [10.172.10.31], try #1
INFO[0186] Starting container [rke-log-cleaner] on host [10.172.10.41], try #1
...
INFO[0191] [remove/rke-log-cleaner] Successfully removed container on host [10.172.10.34]
INFO[0191] [sync] Syncing nodes Labels and Taints
FATA[0356] [ "10.172.10.40" not found]
...
```

**Comment by superseb** [comment]
Please supply the output of the commands described on https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/nginx-proxy/, if this component is not present on the node, please supply the output of `docker ps -a` and the full log of `rke up`.

**Comment by donkeyx** [comment]
I have attached the full log from rke up, and below is the `ps -a` for the two nodes which are not joining.

So the docker ps show nothing on the two nodes: 
▶ ssh -i ~/.ssh/sine-root-adl-01  root@10.172.10.40 docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES                                                                                                                                                                                      
▶ ssh -i ~/.ssh/sine-root-adl-01  root@10.172.10.41 docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES`

log <<<
[rke-up.log](https://github.com/rancher/rke/files/5655583/rke-up.log)

**Comment by superseb** [comment]
The log shows that there are no new nodes to be added, so based on this, the nodes seem to be wiped Docker wise and now the Kubernetes cluster can't find them anymore. As rke only removes Docker containers and not pods, I don't think the Docker wipe came from RKE. It's probably worth while to investigate what happened on the node (command history/logs) and probably the ctime/mtime of the Docker root directories to see when they were created/modified.

**Comment by donkeyx** [comment]
I have resolved by just deleting and re-creating the node. it strange though why it did not work the first time.
