### ISSUE TITLE
Ingress Controller Returns 404 / 502 / 504 with Rancher Kubernetes

### ISSUE THREAD

**Issue by mvutapla-cs** [rancher/rke#2367]
**RKE version:**
v0.1.66

**Docker version: (`docker version`,`docker info` preferred)**
20.10.0-rc1, build 5cc2396

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"

Kernel 
4.18.0-240.1.1.el8_3.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
[cluster.yaml.zip](https://github.com/rancher/rke/files/5653045/cluster.yaml.zip)

**Steps to Reproduce:**
Follow installation steps from https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests for the above specified versions.
Install a Web ingress and a web service in same/or another namespace.
curl the hostname mentioned in the Ingress. (Results in 404 / 504 / 502 errors)
View logs of Ingress controller pod - Returns 404 / 504 / 502

**Results:**
curl curl https://mydomain.com returns - 404 Not Found

**Comment by superseb** [comment]
There are a few things missing here, can you please elaborate on this:

- RKE version is incorrect, please share the output of `rke --version`
- Please do not use unverified Docker versions (latest tested is 19.03.x)
- RHEL/CentOS 8 is tested in k8s 1.19 with firewalld disabled, but the `cluster.yaml` is specified as 1.18.12
- RKE installs an Ingress Controller by default, it doesnt seem that it is disabled. I am unsure why your are installing it manually.
- The supplied `cluster.yaml` has Rancher specific configuration, are you creating the cluster using Rancher or using the RKE CLI (this repository is for issues using the RKE CLI)

If all of above is clarified/fixed, then please use https://rancher.com/docs/rancher/v2.x/en/troubleshooting/ to troubleshoot the cluster and supply logging from the commands so we can continue investigating.
