### ISSUE TITLE
[Question] [Architecture] with RKE, how is the API server reached without any LB ?

### ISSUE THREAD

**Issue by mscbpi** [rancher/rke#2368]
HA deployment of several solutions, including [kubeadm ](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/) and [rke2](https://docs.rke2.io/install/ha/) expect to have a single IP that will make the API servers of master nodes available to worker nodes - and other clients.

Having used RKE for a while now, we do not have this component, how does RKE1 manage ?

**Comment by superseb** [comment]
The diagram on this page should show how this works internally: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/production/nodes-and-roles/ (Also described on https://rancher.com/docs/rke/latest/en/installation/#high-availability)

Externally it is relied upon the user to have a load balancer configured to load balance between the control plane nodes.

Let me know if anything is unclear.

**Comment by mscbpi** [comment]
Thanks for the quick answer ! I'll dig into it. Also this article seems insghtful: https://rancher.com/learning-paths/building-a-highly-available-kubernetes-cluster/
