### ISSUE TITLE
Proxy for helm?

### ISSUE THREAD

**Issue by myhellone** [rancher/rke#2383]
Hi!

I want to know how to setup in rancher 2.5 https_proxy for heml_v3? 
In my network, serwers are behinde corpo proxy.  Docker work with env variables (HTTPS_PROXY...)

**Comment by bacongobbler** [comment]
for others: this same question was asked over at https://github.com/helm/helm/issues/9133.

**Comment by myhellone** [comment]
@bacongobbler 
I want answer form helm devs and rke devs.
