### ISSUE TITLE
RKE cli should generate kube config with 0600 permissions

### ISSUE THREAD

**Issue by jamesongithub** [rancher/rke#2395]
Currently the rke cli generate the kube config with 0640 permission. helm and kubectl warn that this config should not be group readable. 

`
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: kube_config_cluster.yml
`

**RKE version:**
rke --version
rke version v1.2.3

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**
1) rke up
2) Inspect kube_config_cluster.yml

**Results:**
kube_config_cluster.yml is generated with 0640 permissions.

**Comment by jamesongithub** [comment]
bump

**Comment by slickwarren** [comment]
using the latest release (rke v1.2.8) the generated kube_config.yaml has only -rw------- (0600) permissions 
```
-rw-------   1 calebwarren  staff    5383 May  5 17:09 kube_config_y.yaml
```
