### ISSUE TITLE
[Forwardport] RKE Network Addon Job regularly times out

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rke#2439]
Forwardport of https://github.com/rancher/rke/issues/2143
Can be tested with `v1.3.0-rc1`

**Comment by bmdepesa** [comment]
RKE v1.3.0-rc1 

Reproduced in RKE v1.1.2 with nodes in vSphere
```
FATA[0240] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
```

With RKE v1.3.0-rc1 and another node with the same config, the rke-network-plugin installs successfully on every attempt. 
```
[addons] Successfully saved ConfigMap for addon rke-network-plugin to Kubernetes
INFO[0159] [addons] Executing deploy job rke-network-plugin
INFO[0181] [addons] Setting up coredns
```

The cluster did fail to come up successfully as other add-on jobs failed to complete over several retries. These are tracked in https://github.com/rancher/rke/issues/2535
