### ISSUE TITLE
[FEATURE] Upgrade included version of Weave

### ISSUE THREAD

**Issue by thecrazyrussian** [rancher/rke#2442]
This might be arguably considered a bug but the current version of weave integrated does not support Centos 8.

They fixed it in 2.8.1 but trying to specify it manually throws an error: 
Fatal: can't open lock file /run/xtables.lock: Is a directory

The request is to upgrade to 2.8.1.

thank you

**Comment by thecrazyrussian** [comment]
Here is the fix itself. Thanks, Dmytro!
https://github.com/weaveworks/weave/pull/3882/commits/3ef97f0c7c697cf80076f5f0e520bd12ae0593d5

**Comment by superseb** [comment]
Weave 2.8.1 will be included for k8s 1.20, see https://github.com/rancher/kontainer-driver-metadata/pull/481
