### ISSUE TITLE
 Cluster must have at least one etcd plane host

### ISSUE THREAD

**Issue by paulofrazao** [rancher/rke#2448]
##Just trying to setup a 1 node cluster and can't get passed the error below##

**RKE 1.2.5:**

**Docker version: 
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1039-azure
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.352GiB
 Name: RKE01
 ID: E653:SWCK:HMK2:3ZL7:LQCL:XQVD:CLAR:FWUU:2ZUT:SEIR:L5CN:55OY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: 5.4.0-1039-azure (Ubuntu 18.04)**

**Type/provider of hosts: (AZURE)**

**cluster.yml file:*nodes:
    - address: 192.168.0.11
      user: root
      role:
        - controlplane
        - etcd
        - worker*

**Steps to Reproduce:* rke up*

**Results:*INFO[0000] [certificates] Generating CA kubernetes certificates
INFO[0000] [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
INFO[0000] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
INFO[0000] [certificates] Generating Kubernetes API server certificates
INFO[0000] [certificates] Generating Service account token key
INFO[0000] [certificates] Generating Kube Controller certificates
INFO[0000] [certificates] Generating Kube Scheduler certificates
INFO[0001] [certificates] Generating Kube Proxy certificates
INFO[0001] [certificates] Generating Node certificate
INFO[0001] [certificates] Generating admin certificates and kubeconfig
INFO[0001] [certificates] Generating Kubernetes API server proxy client certificates
INFO[0001] Successfully Deployed state file at [./cluster.rkestate]
INFO[0001] Building Kubernetes cluster
FATA[0001] Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config
*

**Comment by superseb** [comment]
Please share full log as that contains the error when trying to connect to the host (`192.168.0.11`)

**Comment by paulofrazao** [comment]
I am executing this locally on the server. I first create the config.yaml file, then executed rke up.

root@RKE01:/home/user1# ./rke config --name cluster.yml
[+] Cluster Level SSH Private Key Path [~/.ssh/id_rsa]:
[+] Number of Hosts [1]:
[+] SSH Address of host (1) [none]: 192.168.0.11
[+] SSH Port of host (1) [22]:
[+] SSH Private Key Path of host (192.168.0.11) [none]:
[-] You have entered empty SSH key path, trying fetch from SSH key parameter
[+] SSH Private Key of host (192.168.0.11) [none]:
[-] You have entered empty SSH key, defaulting to cluster level SSH key: ~/.ssh/id_rsa
[+] SSH User of host (192.168.0.11) [ubuntu]:
[+] Is host (192.168.0.11) a Control Plane host (y/n)? [y]:
[+] Is host (192.168.0.11) a Worker host (y/n)? [n]: y
[+] Is host (192.168.0.11) an etcd host (y/n)? [n]: y
[+] Override Hostname of host (192.168.0.11) [none]:
[+] Internal IP of host (192.168.0.11) [none]:
[+] Docker socket path on host (192.168.0.11) [/var/run/docker.sock]:
[+] Network Plugin Type (flannel, calico, weave, canal, aci) [canal]:
[+] Authentication Strategy [x509]:
[+] Authorization Mode (rbac, none) [rbac]:
[+] Kubernetes Docker image [rancher/hyperkube:v1.19.7-rancher1]:
[+] Cluster domain [cluster.local]:
[+] Service Cluster IP Range [10.43.0.0/16]:
[+] Enable PodSecurityPolicy [n]:
[+] Cluster Network CIDR [10.42.0.0/16]:
[+] Cluster DNS Service IP [10.43.0.10]:
[+] Add addon manifest URLs or YAML files [no]:
root@RKE01:/home/paulo#
root@RKE01:/home/paulo# ./rke up
INFO[0000] Running RKE version: v1.2.5
INFO[0000] Initiating Kubernetes cluster
INFO[0000] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
INFO[0000] [certificates] Generating Kubernetes API server certificates
INFO[0000] [certificates] Generating admin certificates and kubeconfig
INFO[0000] [certificates] Generating kube-etcd-192-168-0-11 certificate and key
INFO[0000] Successfully Deployed state file at [./cluster.rkestate]
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [192.168.0.11]
WARN[0000] Failed to set up SSH tunneling for host [192.168.0.11]: Can't establish dialer connection: Error while reading SSH key file: open /root/.ssh/id_rsa: no such file or directory
WARN[0000] Removing host [192.168.0.11] from node lists
FATA[0000] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [192.168.0.11]
root@RKE01:/home/user1#

**Comment by superseb** [comment]
It needs a private key to connect to the server (which should have the public key configured), it is trying to read it from `/root/.ssh/id_rsa` but it is not there/readable.

**Comment by paulofrazao** [comment]
That was it, Thanks.

I created a new RSA keypair using ssh-keygen and was able to continue.

If there is a recommendation I can give, is to update the RKE documentation mentioning this is a pre-requisite. I went through the docs one more time and I couldn't find any mention of this being a requirement.

Thank you
-PF
