### ISSUE TITLE
Is it possible for "etcd-rolling-snapshots" to write the snapshot to other directories rather than "/opt/rke/etcd-snapshots" 

### ISSUE THREAD

**Issue by pjamenaja** [rancher/rke#2460]
Hi,

Currently, I'm using CoreOs on GoogleCloud Compute Engine (GCE) to deploy the RKE. Unfortunately that the CoreOS by default does not allow us to write anything to "/opt" directory. I read the document and see that there is a directive "prefix_path" that I could use to customize this. I tried using it but seemed like it does not work, it still trying to write the snapshot into "/opt/rke/etcd-snapshots".

The log snippet is shown below.

> time="2021-02-14T10:15:30Z" level=warning msg="Can't start Docker container [etcd-rolling-snapshots] on host [10.148.15.208]: Error response from daemon: error while creating mount source path '/opt/rke/etcd-snapshots': mkdir /opt/rke: read-only file system"
time="2021-02-14T10:15:30Z" level=info msg="Starting container [etcd-rolling-snapshots] on host [10.148.15.208], try #2"
time="2021-02-14T10:15:30Z" level=warning msg="Can't start Docker container [etcd-rolling-snapshots] on host [10.148.15.208]: Error response from daemon: error while creating mount source path '/opt/rke/etcd-snapshots': mkdir /opt/rke: read-only file system"
time="2021-02-14T10:15:30Z" level=info msg="Starting container [etcd-rolling-snapshots] on host [10.148.15.208], try #3"
time="2021-02-14T10:15:30Z" level=warning msg="Can't start Docker container [etcd-rolling-snapshots] on host [10.148.15.208]: Error response from daemon: error while creating mount source path '/opt/rke/etcd-snapshots': mkdir /opt/rke: read-only file system"

Thanks,
Seub

**Comment by luthermonson** [comment]
so prefix_path unfortunately doesn't apply to etcd snapshots apparently. I had to look at code to confirm but track this const https://github.com/rancher/rke/blob/8a4535050697d75d2fda5c079ead08a6c90c2f08/services/etcd.go#L26 and see things like this https://github.com/rancher/rke/blob/c1d14447ff11a288aef1fcb71cab3e501ea36531/pki/pki.go#L115-L116 where we use the prefix in the k8s path but not the backup.

are you turning on rolling snapshots? looks like this is only an issue in snapshotting so maybe turn off all snapshotting and see if things will fire up?

**Comment by pjamenaja** [comment]
> are you turning on rolling snapshots? looks like this is only an issue in snapshotting so maybe turn off all snapshotting and see if things will fire up?

Actually, I got the error above when using RKE terraform (https://registry.terraform.io/providers/rancher/rke/latest/docs/resources/cluster) to provision the brand new RKE cluster, I believe that is equivalent to the running of "rke up" command.

I also configured the terraform to disable the etcd backup equivalent to the YAML snippet below but still get that error. I'm not sure if this is the right way to disable to etcd backup or not?
```
services:
  etcd:
    backup_config:
      enabled: false
```


Thanks,
Seub

**Comment by pjamenaja** [comment]
Just realized that I can set "snapshot" to disable it. And yes this workaround can solve my issue. Is it possible to have a feature to configure the prefix path for the snapshot?

```
services:
  etcd:
    backup_config:
      interval_hours: 6
      retention: 30
    snapshot: false
```

Thanks,
Seub

**Comment by superseb** [comment]
Mounting a disk/lv on `/opt/rke` would also be a workaround but I can imagine having another disk is a heavy workaround. We can take a look at making this configurable.
