### ISSUE TITLE
full-cluster-state config map contains private key information

### ISSUE THREAD

**Issue by raesene** [rancher/rke#2464]
**RKE version:**
rke version v1.2.5

**Issue**
Looking at the configmaps created as part of an RKE 1.2.5 installation I noticed that the `full-cluster-state` configmap in the `kube-system` namespace contains the private keys for the cluster, including the cluster certificate authority private key.

This could have negative security consequences, as any user with read rights to that configmap would be able to generate new valid cluster credentials with cluster-admin privileges.

The configmap also contains the kube-admin kubeconfig file which provides cluster-admin level access to the cluster.

**Recommendation**

Ideally, from a security standpoint, key information and credentials wouldn't be stored in the Kubernetes API. If they do need to be, for operational purposes, it would be worth considering using `secret` objects instead of `configmaps`. Whilst there's not a lot of technical difference between the two, it is generally clearer to users that secrets should be protected, whereas a config maps may be assumed to just be configuration data.

**Comment by superseb** [comment]
This was also discussed/considered in https://github.com/rancher/rke/issues/1024, please emoji +1 there for visibility
