### ISSUE TITLE
Update PrefixPath for Fedora CoreOS to "/" since /var and /etc should hold state and config

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke#2468]
RKE version: 1.2.5
Docker version: 19.03.13
Operating system and kernel: Fedore CoreOS 33.20210117.3.2
Type/provider of hosts: VMware

Today using RKE and FCOS it will automatically set the prefix path to /opt/rke since the docker os type has the string "coreos" in it https://github.com/rancher/rke/blob/master/hosts/hosts.go#L60. Reading FCOS documentation(https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_configuration_in_etc_and_state_in_var) it says to hold config and state in the /var and /etc since those directories are persisted (/opt is already a link to /var).

I would like to use the standard /etc/kubernetes, /var/lib/kubelet, /var/lib/etcd, etc. paths using rke and fcos but since it is hardcoded to /opt/rke and ignores prefix_path="" or prefix_path="/" I am unable to change this. FCOS should be considered at a separate OS and use the default / path or providing the path "/" should be a way to bypass the switch that decides based on the OS https://github.com/rancher/rke/blob/master/hosts/hosts.go#L362.

**Comment by Raboo** [comment]
Please reopen, it is a valid issue
