### ISSUE TITLE
Possible to update rke documentation with latest version?

### ISSUE THREAD

**Issue by RHudsonH** [rancher/rke#2479]
**RKE all**
Following the RKE documentation at https://rancher.com/docs/rke/latest/en/ there's no way to tell what the current latest stable version of RKE is. It is only stated that one should "...navigate to our RKE Releases page. Download the latest RKE v1.x installer...". However, at the time I'm writing this that would lead someone to download v1.0.16 where as v1.2.5 seems like it should be the correct one.

Is there a way to have the documentation automatically update to point to the correct version?

**Comment by superseb** [comment]
This is merged in https://github.com/rancher/docs/pull/3084
