### ISSUE TITLE
Port check fails if when adding a control plan role to a worker node during update.

### ISSUE THREAD

**Issue by moelsayed** [rancher/rke#248]
If `rke up` was run to add a control plan tole to an existing worker node, the port listener will fail due to the nginx-proxy component holding the kube-api port

**Comment by galal-hussein** [comment]
reopen for testing

**Comment by galal-hussein** [comment]
rke version: v0.1.1-rc1

Adding control role to worker node doesn't create any problem anymore with ports checks
