### ISSUE TITLE
Bad TLS Cert when trying to redeploy

### ISSUE THREAD

**Issue by icsy7867** [rancher/rke#2487]
I am at a loss.  Any suggestions/help would be much appreciated.

**RKE version:**
`1.2.6`

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 101
  Running: 52
  Paused: 0
  Stopped: 49
 Images: 66
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.15.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.636GiB
 Name: centosMaster
 ID: AUU2:SP73:X5T7:QP4K:IZJQ:BPIZ:VIPA:3YI7:MDGW:K4CS:OTW5:LFJH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`Centos 7`
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`KVM/QEMU on oVirt`
**cluster.yml file:**
```
nodes:
  - address: 172.181.30.25
    user: rancher
    role:
      - controlplane
      - etcd
      - worker

  - address: 172.181.30.26
    user: rancher
    role:
      - controlplane
      - etcd
      - worker

  - address: 172.181.30.27
    user: rancher
    role:
      - etcd
```
**Steps to Reproduce:**
run ./rke up

So I notice third ETCD server (172.181.30.27) was throwing up errors and was not communicating on port 2379 for the health check.  I had been having weird results with this server, so I destroyed it (It was running flatcar).  I tried to replace it with a Centos7 vm but recieved "BAD TLS" certificate errors.  So I tried to remove this server from my cluster.yml and just redploy with the .25 and .26 servers.

This had similar SSL/TLS errors.  So I tried to rebuild a VM again with RHEL7 this time.  I tried to add a controlplane to the new VM which also had similar SSL/TLS errors.  I have reverted back to my original cluster.yml listed above and tried to redeploy, but I am getting:

`FATA[0055] [[network] Host [172.181.30.26] is not able to connect to the following ports: [172.181.30.25:2379]. Please check network policies and firewall rules]`
Firewall is open for 2379

I am quite convinced this is a stale SSL error.  But
```
rke cert rotate
INFO[0000] Running RKE version: v1.2.6
INFO[0000] Initiating Kubernetes cluster
INFO[0000] Rotating Kubernetes cluster certificates
FATA[0000] Failed to rotate certificates: can't find old certificates
```

I have tried moving the /etc/kubernetes/ssl folder on all the hosts to regenerate, but same error.  I also tried making a copy of the certs in /etc/kubernetes/ssl into /etc/kubernetes/.tmp as I read in some rancher documentation with no luck.
**Results:**

`FATA[0055] [[network] Host [17.181.30.26] is not able to connect to the following ports: [17.181.30.25:2379]. Please check network policies and firewall rules]`

```
kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                                                                            ERROR
scheduler            Healthy     ok
controller-manager   Healthy     ok
etcd-2               Unhealthy   Get "https://17.181.30.27:2379/health": read tcp 17.181.30.26:38402->17.181.30.27:2379: read: connection reset by peer
etcd-1               Unhealthy   Get "https://17.181.30.25:2379/health": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
etcd-0               Unhealthy   Get "https://17.181.30.26:2379/health": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by superseb** [comment]
The port check is not (or should not be) related to certificates. Are your running firewalld/NetworkManager on the server? Does disabling help getting past the port check? `rke remove` will remove everything from the servers to make sure you start with a clean state, a reboot is also recommended after running `rke remove`. (`rke remove` deletes all data)

Please also share the output of `ls -la` from the working directory when you are running `rke up`.
