### ISSUE TITLE
How to add baremetal workers to cluster

### ISSUE THREAD

**Issue by InsOpDe** [rancher/rke#2494]
**RKE version:**
`v1.19.4`

**Docker version: (`docker version`,`docker info` preferred)**
`Docker version 19.03.14, build 5eb3275d40`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
root@hcloud-ubuntu-20-4gb-internal-master-1:/etc/kubernetes# uname -r
5.4.0-56-generic
root@hcloud-ubuntu-20-4gb-internal-master-1:/etc/kubernetes# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
* Hetzner-Cloud
* Bare-Metal

**Issue**
I am managing a cluster on hetzner with Rancher. It set up a RKE Cluster running rancher/hyperkube and I can add nodes via the GUI. The question is: How can I add nodes without the GUI?

Is there a possibility to utilize something like:
* `kubeadm join`
* `curl -sfL https://get.k3s.io | K3S_URL=https://myserver:6443 K3S_TOKEN=mynodetoken sh -`

**Comment by superseb** [comment]
There is no method in RKE like that. RKE CLI can only be run to perform actions on/with the cluster. Rancher enhances that with providing a `docker run` command to join nodes, but RKE CLI has no such "central" component to orchestrate that.

Other projects like k3s/RKE2 do have this option like you already mentioned.
