### ISSUE TITLE
[URGENTLY NEED HELPS - Kubernetes]Cannot join worker nodes: dockershim.sock error & docker version error

### ISSUE THREAD

**Issue by foxonspace** [rancher/rke#2501]
This is the result I got after create master node:

[k5user@control .kube]$ kubectl get nodes
NAME        STATUS   ROLES      AGE   VERSION
k8smaster   Ready      <none>   2h    v1.10.12

Then I created a token and tried to join the worker node to it:

kubeadm token create --print-join-command
kubeadm join 171.27.0.21:6443 --token   c08xkc.yp44qdtuwgxnkpel --discovery-token-ca-cert-hash   sha256:53874c36384efbb54be38bb5bb4630e8501aa7641a3f1c7a6753aaf027d1915f
 
The errors below appeared:

[root@k8snode01 run]# kubeadm join   171.27.0.21:6443 --token c08xkc.yp44qdtuwgxnkpel   --discovery-token-ca-cert-hash   sha256:53874c36384efbb54be38bb5bb4630e8501aa7641a3f1c7a6753aaf027d1915f
[preflight] Running pre-flight checks.
[WARNING SystemVerification]: docker version is greater than the most   recently validated version. Docker version: 18.03.0-ce. Max validated   version: 17.03
[preflight] Some fatal errors occurred:
[ERROR CRI]: unable to check if the container runtime at   "/var/run/dockershim.sock" is running: exit status 1
[preflight] If you know what you are   doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

I looked for /var/run/dockershim.sock but it not existed on my worker node but it does exit on my master node.
I am totally new to this. Do I have to set anything on any config file?
Do I need to downgrade my docker?

Any suggestions? Really urgently must be solved.

I tried "kubeadm reset" on worker node, but it does not work. Same errors shown.

**Comment by superseb** [comment]
Not really sure what the request is here, this repo is for clusters using RKE, not kubeadm. `v1.10.12` is heavily outdated too so even filing it at https://github.com/kubernetes/kubeadm might not get much response.
