### ISSUE TITLE
kubelet "config.yaml no such file" after installation via RKE

### ISSUE THREAD

**Issue by aracloud** [rancher/rke#2513]
**RKE version:**
rke version v1.2.4

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 19.03.15, build 99e3ed8919

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

Linux uk8s-rke 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
ESXi

**cluster.yml file:**
nodes:
  address: rancher-ip
    user: root
    role: [controlplane, worker, etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"

**Steps to Reproduce:**
Fresh installation

**Results:**
(/var/log/syslog)
Apr 13 13:48:54 uk8s-rke systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 814.
Apr 13 13:48:54 uk8s-rke systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Apr 13 13:48:54 uk8s-rke systemd[1]: Started kubelet: The Kubernetes Node Agent.
Apr 13 13:48:54 uk8s-rke kubelet[148641]: E0413 13:48:54.572252  148641 server.go:204] "Failed to load kubelet config file" err="failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file \"/var/lib/kubelet/config.yaml\", error: open /var/lib/kubelet/config.yaml: no such file or directory" path="/var/lib/kubelet/config.yaml"
Apr 13 13:48:54 uk8s-rke systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Apr 13 13:48:54 uk8s-rke systemd[1]: kubelet.service: Failed with result 'exit-code'.

ll /var/lib/kubelet/
total 40
drwxr-xr-x  9 root root 4096 Apr 13 11:33 ./
drwxr-xr-x 48 root root 4096 Apr 13 11:33 ../
-rw-------  1 root root   62 Apr 13 11:33 cpu_manager_state
drwxr-xr-x  2 root root 4096 Apr 13 11:52 device-plugins/
drwxr-xr-x  2 root root 4096 Apr 13 11:33 pki/
drwxr-x---  2 root root 4096 Apr 13 11:33 plugins/
drwxr-x---  2 root root 4096 Apr 13 11:33 plugins_registry/
drwxr-x---  2 root root 4096 Apr 13 11:33 pod-resources/
drwxr-x--- 22 root root 4096 Apr 13 12:52 pods/
drwxr-xr-x  2 root root 4096 Apr 13 11:33 volumeplugins/

**Comment by superseb** [comment]
This is the pre-installed `kubelet` (kubeadm) from Ubuntu, you should at least disable (or remove) it before running `rke up` against these nodes. RKE1 doesn't use systemd units, but Docker containers.
