### ISSUE TITLE
TCP/UDP Layer 4 Loab Balancer failed to work for the Rancher UI 

### ISSUE THREAD

**Issue by michaelkasede** [rancher/rke#2526]
`NAME      STATUS   ROLES               AGE   VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
master1   Ready    controlplane,etcd   25h   v1.18.17   172.17.17.30   <none>        Ubuntu 20.04.1 LTS   5.4.0-72-generic   docker://19.3.15
worker1   Ready    worker              25h   v1.18.17   172.17.17.20   <none>        Ubuntu 20.04.1 LTS   5.4.0-72-generic   docker://19.3.15
worker2   Ready    worker              25h   v1.18.17   172.17.17.21   <none>        Ubuntu 20.04.1 LTS   5.4.0-72-generic   docker://19.3.15
`
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware ESXi
**cluster.yml file:**
`# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 172.17.17.30
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: master1
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 172.17.17.20
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: worker1
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 172.17.17.21
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: worker2
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: true
    retention: 24h
    creation: 6h
    backup_config:
      interval_hours: 12
      retention: 6
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
network:
  plugin: flannel
  options:
    canal_flannel_backend_type: vxlan
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: rancher/coreos-etcd:v3.4.3-rancher1
  alpine: rancher/rke-tools:v0.1.72
  nginx_proxy: rancher/rke-tools:v0.1.72
  cert_downloader: rancher/rke-tools:v0.1.72
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.72
  kubedns: rancher/k8s-dns-kube-dns:1.15.2
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny:1.15.2
  kubedns_sidecar: rancher/k8s-dns-sidecar:1.15.2
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler:1.7.1
  coredns: rancher/coredns-coredns:1.6.9
  coredns_autoscaler: rancher/cluster-proportional-autoscaler:1.7.1
  nodelocal: rancher/k8s-dns-node-cache:1.15.7
  kubernetes: rancher/hyperkube:v1.18.17-rancher1
  flannel: rancher/coreos-flannel:v0.12.0
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/calico-node:v3.13.4
  calico_cni: rancher/calico-cni:v3.13.4
  calico_controllers: rancher/calico-kube-controllers:v3.13.4
  calico_ctl: rancher/calico-ctl:v3.13.4
  calico_flexvol: rancher/calico-pod2daemon-flexvol:v3.13.4
  canal_node: rancher/calico-node:v3.13.4
  canal_cni: rancher/calico-cni:v3.13.4
  canal_flannel: rancher/coreos-flannel:v0.12.0
  canal_flexvol: rancher/calico-pod2daemon-flexvol:v3.13.4
  weave_node: weaveworks/weave-kube:2.6.4
  weave_cni: weaveworks/weave-npc:2.6.4
  pod_infra_container: rancher/pause:3.1
  ingress: rancher/nginx-ingress-controller:nginx-0.35.0-rancher2
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1
  metrics_server: rancher/metrics-server:v0.3.6
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.6
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
kubernetes_version: ""
private_registries: []
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"
  
cluster_name: webcluster
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
dns: null`
**Steps to Reproduce:**
Created cluster, setup cert manager and setup racher. Then configured load balancer with nginx and created DNS entry of rancher hostname with load balancer IP
**Results:**
When I try to access the Rancher UI with the IP I get 
Status: Failure
Message: Unauthorized
**Nginx Config**

load_module /usr/lib/nginx/modules/ngx_stream_module.so;

worker_processes 4;
worker_rlimit_nofile 40000;

events {
    worker_connections 8192;
}
stream {
    upstream rancher_http {
        server 172.17.17.30:80 max_fails=3 fail_timeout=5s;
        server 172.17.17.20:80 max_fails=3 fail_timeout=5s;
        server 172.17.17.21:80 max_fails=3 fail_timeout=5s;
    }
     server {
        listen 80;
        proxy_pass rancher_http;
   }
    upstream rancher_https {
        server 172.17.17.30:443 max_fails=3 fail_timeout=5s;
        server 172.17.17.20:443 max_fails=3 fail_timeout=5s;
        server 172.17.17.21:443 max_fails=3 fail_timeout=5s;
    }
    server {
        listen 443;
        proxy_pass rancher_https;
    }
}

**Comment by superseb** [comment]
This is the part in the docs where we show the NGINX config for Layer 4: https://rancher.com/docs/rancher/v2.x/en/installation/resources/k8s-tutorials/infrastructure-tutorials/nginx/

I don't really get this part `When I try to access the Rancher UI with the IP I get`, what happens when you access the Rancher UI using the configured hostname? Can you add the output of `curl -v https://rancher.yourdomain.com` as well? What is in the logging of NGINX when that request comes in? What NGINX version are you using? If possible, please use markup in your issue so the config/logging is correctly formatted (mostly using backticks \`aa\`)
