### ISSUE TITLE
Full cluster.yml spec or how to pass a "profile flag" via cluster.yml / Misuderstanding around rke2

### ISSUE THREAD

**Issue by rlewkowicz** [rancher/rke#2529]
https://docs.rke2.io/security/hardening_guide/

> To help ensure these above requirements are met, RKE2 can be started with the profile flag set to cis-1.5

Now the permissive profile with clusters generated via the rancher 2 ui passes automatically, the hardened one does not. How do I pass "profile flags" to the rancher ui?

The docs continue:

> Certain CIS policy controls for PodSecurityPolicies and NetworkPolicies will restrict the functionality of this cluster. You must opt into having RKE2 configuring these out of the box.

These are some of the things that are not passing. How do I get this configuration to clusters generated via the ui? You can export rke templates but I'm not sure what to put in there since I can't find a full spec. 

I'm familiar with the api, and am more than happy to use that, it doesn't have to be a button, I just need a way to opt gui templates into these harder CIS policies. 

I'm on:

Rancher | v2.5.5
User Interface | v2.5.4

So I guess I figured that I was using rke2 but maybe it's not under the hood.

**Comment by superseb** [comment]
Let me know if this needs more information
