### ISSUE TITLE
RKE Roadmap

### ISSUE THREAD

**Issue by just1689** [rancher/rke#2544]
Good day

I'm curious if Rancher has a document speaking to the roadmap concerns around RKE?

Will RKE be replaced by RKE 2? If so, is there a timeline for that?

Will RKE drop Docker support? If so, is there a version from which it will do so?

Will RKE have an upgrade path to RKE 2? Or will environments be rebuilt from scratch to move to RKE 2?

Kind regards
Justin

**Comment by just1689** [comment]
Hi,

Is there any news on this?

**Comment by oonashvili** [comment]
Hello, 
I'm pretty new in this world and need your advice. Should I continue learning and testing of RKE or it's wise to start from something diff, rke2 maybe ? 

I dont want to invest in RKE and found out in 3-6 Month that I need to migrate . 
Please suggest which engine should I choose.

**Comment by oonashvili** [comment]
@just1689 Thank for your comment. 

Will add more details , I have some apps running in SWARM and want to migrate them into the kubernetes , I choose Rancher and started playing with RKE cluster , started course in Ranchers Site , but find out about Kubernetes dropping Docker runtime and as we know RKE is working with it.  So i was stuck here.

**Comment by just1689** [comment]
@oonashvili Let's move the conversation off this Github Issue. I don't want to create problems for the Rancher folks. Checkout the Kubernetes @ Home Discord: https://discord.gg/XJdVTCFR

**Comment by superseb** [comment]
Let me know if anything else is needed on this.
