### ISSUE TITLE
RKE fails to deploy with some use cases of custom certs

### ISSUE THREAD

**Issue by alexander-hughes** [rancher/rke#2546]
**RKE version:** v1.2.6 or higher

**Docker version: (`docker version`,`docker info` preferred)** all

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** all

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** all

**cluster.yml file:** all

**Steps to Reproduce:**

- Create a custom certs directory containing files that are either not *.pem (e.g., files used in automation relating to certs) or a key that does not end in -key.pem
- (Optional): Deploy a cluster with RKE v1.2.5 or lower to any Kubernetes version
- Attempt a deployment (optional: or an upgrade) with RKE v1.2.6 or higher to any Kubernetes version

**Results:**
Observed error:
`stdout:time="2021-05-18T15:35:25-04:00" level=fatal msg="Failed to read certificates from dir [certs]: failed to read certificate [cfssl_ca_key.pem]: data does not contain any valid RSA or ECDSA certificates"
Exception: 	CMD Failed! [['rke', '--debug', 'up', '--config', 'rke.yml', '--custom-certs', '--cert-dir', 'certs']]`

Code change that introduced this behavior: https://github.com/rancher/rke/commit/4a531591129d966c89d6bb152fd6c03a5f8d67b0

**Comment by kravciak** [comment]
Reproduced with 1.2.7 (`echo xx > cluster_certs/my_key_file.notpem`). Can't be reproduced with empty file.

```
cluster-rke ε rke_1.2.7 up --ssh-agent-auth --config cluster.yml --custom-certs --cert-dir=cluster_certs
INFO[0000] Running RKE version: v1.2.7                  
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] [dialer] Setup tunnel for host [rke.hopto.org] 
INFO[0001] Checking if container [cluster-state-deployer] is running on host [rke.hopto.org], try #1 
FATA[0002] Failed to read certificates from dir [cluster_certs]: failed to read certificate [my_key_file.notpem]: data does not contain any valid RSA or ECDSA certificates 
```

Works fine in 1.3.0-rc3
```
cluster-rke ε rke_1.3.0-rc3 up --ssh-agent-auth --config cluster.yml --custom-certs --cert-dir=cluster_certs
WARN[0000] This is not an officially supported version (v1.3.0-rc3) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases 
INFO[0000] Running RKE version: v1.3.0-rc3              
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] [dialer] Setup tunnel for host [rke.hopto.org] 
INFO[0001] Checking if container [cluster-state-deployer] is running on host [rke.hopto.org], try #1 
INFO[0002] Successfully Deployed state file at [./cluster.rkestate] 
INFO[0002] Building Kubernetes cluster
...
```
