### ISSUE TITLE
Unable to rotate kubelet certificate

### ISSUE THREAD

**Issue by kingsd041** [rancher/rke#2566]
**RKE version:**
v1.2.8
**Docker version: (`docker version`,`docker info` preferred)**
20.10.7
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`Ubuntu 18.04.2 LTS` `4.15.0-1044-aws`
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**cluster.yml file:**
```
nodes:
  - address: 172.31.31.10
    user: ubuntu
    role: [controlplane, worker, etcd]
```
**Steps to Reproduce:**
1. Query the expiration time of the kubelet certificate
```
root@ip-172-31-31-10:~# openssl s_client -connect 172.31.31.10:10250 | openssl x509 -text | grep -E "Before|After"
depth=1 CN = 172.31.31.10-ca@1623070697
verify error:num=19:self signed certificate in certificate chain
            Not Before: Jun  7 11:58:16 2021 GMT
            Not After : Jun  7 11:58:16 2022 GMT
```
2. Rotate the kubelet certificate by `rke cert rotate --service kubelet`
**Results:**
The kubelet certificate has not been rotate, and it is still the original certificate expiration time。

**Comment by superseb** [comment]
Sounds the same as https://github.com/rancher/rke/issues/2538

**Comment by superseb** [comment]
@kingsd041 Is this something we need to look into or is it working by activating the serving certificate?
