### ISSUE TITLE
rke up fails with "Host [XXX.XXX.XXX.XXX] is not able to connect to the following ports: [XXX.XXX.XXX.XXX:2379]. Please check network policies and firewall rules]"

### ISSUE THREAD

**Issue by pbran** [rancher/rke#2569]
**RKE version:** v1.2.8

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.12.14-197.78-default
 Operating System: SUSE Linux Enterprise Server 15 SP1
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.907GiB
 Name: 5a2e1eda9a1c
 ID: NJ5T:WVNJ:TAPF:KN3Q:PEXS:MGTB:KSSS:TVJ5:5IAW:ILIB:AT2J:PBIQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"

4.12.14-197.78-default

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**. 
AWS

**cluster.yml file:**
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 54.171.244.128
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  - worker
  hostname_override: ""
  user: cloud_user
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa-nopass
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: canal
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.4.15-rancher1
  alpine: rancher/rke-tools:v0.1.74
  nginx_proxy: rancher/rke-tools:v0.1.74
  cert_downloader: rancher/rke-tools:v0.1.74
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.74
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.15.10
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.15.10
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.15.10
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.1
  coredns: rancher/mirrored-coredns-coredns:1.8.0
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.1
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.15.13
  kubernetes: rancher/hyperkube:v1.20.6-rancher1
  flannel: rancher/coreos-flannel:v0.13.0-rancher1
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/mirrored-calico-node:v3.17.2
  calico_cni: rancher/mirrored-calico-cni:v3.17.2
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.17.2
  calico_ctl: rancher/mirrored-calico-ctl:v3.17.2
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.17.2
  canal_node: rancher/mirrored-calico-node:v3.17.2
  canal_cni: rancher/mirrored-calico-cni:v3.17.2
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.17.2
  canal_flannel: rancher/coreos-flannel:v0.13.0-rancher1
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.17.2
  weave_node: weaveworks/weave-kube:2.8.1
  weave_cni: weaveworks/weave-npc:2.8.1
  pod_infra_container: rancher/mirrored-pause:3.2
  ingress: rancher/nginx-ingress-controller:nginx-0.43.0-rancher3
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  metrics_server: rancher/mirrored-metrics-server:v0.4.1
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.6
  aci_cni_deploy_container: noiro/cnideploy:5.1.1.0.1ae238a
  aci_host_container: noiro/aci-containers-host:5.1.1.0.1ae238a
  aci_opflex_container: noiro/opflex:5.1.1.0.1ae238a
  aci_mcast_container: noiro/opflex:5.1.1.0.1ae238a
  aci_ovs_container: noiro/openvswitch:5.1.1.0.1ae238a
  aci_controller_container: noiro/aci-containers-controller:5.1.1.0.1ae238a
  aci_gbp_server_container: noiro/gbp-server:5.1.1.0.1ae238a
  aci_opflex_server_container: noiro/opflex-server:5.1.1.0.1ae238a
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_backend: null
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: ""
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
dns: null

**Steps to Reproduce:**
Run 'rke up'

**Results:**
INFO[0000] Running RKE version: v1.2.8                  
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates 
INFO[0000] [certificates] Generating Kubernetes API server certificates 
INFO[0000] [certificates] Generating admin certificates and kubeconfig 
INFO[0000] [certificates] Generating kube-etcd-54-171-244-128 certificate and key 
INFO[0000] [certificates] Deleting unused certificate: kube-etcd-34-242-1-62 
INFO[0000] Successfully Deployed state file at [./cluster.rkestate] 
INFO[0000] Building Kubernetes cluster                  
INFO[0000] [dialer] Setup tunnel for host [54.171.244.128] 
INFO[0000] [network] Deploying port listener containers 
INFO[0000] Pulling image [rancher/rke-tools:v0.1.74] on host [54.171.244.128], try #1 
INFO[0006] Image [rancher/rke-tools:v0.1.74] exists on host [54.171.244.128] 
INFO[0010] Starting container [rke-etcd-port-listener] on host [54.171.244.128], try #1 
INFO[0012] [network] Successfully started [rke-etcd-port-listener] container on host [54.171.244.128] 
INFO[0013] Image [rancher/rke-tools:v0.1.74] exists on host [54.171.244.128] 
INFO[0013] Starting container [rke-cp-port-listener] on host [54.171.244.128], try #1 
INFO[0014] [network] Successfully started [rke-cp-port-listener] container on host [54.171.244.128] 
INFO[0014] Image [rancher/rke-tools:v0.1.74] exists on host [54.171.244.128] 
INFO[0015] Starting container [rke-worker-port-listener] on host [54.171.244.128], try #1 
INFO[0016] [network] Successfully started [rke-worker-port-listener] container on host [54.171.244.128] 
INFO[0016] [network] Port listener containers deployed successfully 
INFO[0016] [network] Running control plane -> etcd port checks 
INFO[0016] [network] Checking if host [54.171.244.128] can connect to host(s) [54.171.244.128] on port(s) [2379], try #1 
INFO[0016] Image [rancher/rke-tools:v0.1.74] exists on host [54.171.244.128] 
INFO[0017] Starting container [rke-port-checker] on host [54.171.244.128], try #1 
INFO[0018] [network] Successfully started [rke-port-checker] container on host [54.171.244.128] 
INFO[0023] Removing container [rke-port-checker] on host [54.171.244.128], try #1 
INFO[0028] [network] Checking if host [54.171.244.128] can connect to host(s) [54.171.244.128] on port(s) [2379], try #2 
INFO[0028] Image [rancher/rke-tools:v0.1.74] exists on host [54.171.244.128] 
INFO[0031] Starting container [rke-port-checker] on host [54.171.244.128], try #1 
INFO[0031] [network] Successfully started [rke-port-checker] container on host [54.171.244.128] 
INFO[0036] Removing container [rke-port-checker] on host [54.171.244.128], try #1 
INFO[0042] [network] Checking if host [54.171.244.128] can connect to host(s) [54.171.244.128] on port(s) [2379], try #3 
INFO[0042] Image [rancher/rke-tools:v0.1.74] exists on host [54.171.244.128] 
INFO[0044] Starting container [rke-port-checker] on host [54.171.244.128], try #1 
INFO[0045] [network] Successfully started [rke-port-checker] container on host [54.171.244.128] 
INFO[0050] Removing container [rke-port-checker] on host [54.171.244.128], try #1 
FATA[0055] [[network] Host [54.171.244.128] is not able to connect to the following ports: [54.171.244.128:2379]. Please check network policies and firewall rules] 

I have tried it 4 or 5 times on Ubuntu and SUSE with the same results.

**Comment by superseb** [comment]
Did you check network policies/restrictions and/or (host) firewall rules? Can you share output of commands that show host firewall is disabled? If so, something in the network is causing it as we haven't had any reports on that this core functionality is broken.

If you can share AMI used we can use that to look into it.

**Comment by pbran** [comment]
Solved. It is an AWS instance and I had not specified the internal address in the cluster.yml so it tries to contact itself on the external address.  Editing the cluster.yml to have the internal address on line 6 appears to have fixed it.
