### ISSUE TITLE
DNSConfigForming event on Fedora CoreOS with hostNetwork

### ISSUE THREAD

**Issue by mecseid** [rancher/rke#2570]
The resolv.conf of nginx-ingress-controller (and every other pod which has hostNetwork enabled) is not generated as expected, and I get a lot of events about DNSConfigForming. It only happens on Fedora CoreOS.
(We have some nodes with "old" CoreOS, and this problem not happens on that nodes.)

It's strange to me that the kubelet generated DNS server list contains the host's resolv.conf entries multiple times (as you can see in the Result section).

**RKE version:**
Installed with Rancher, Kubernetes version is v1.19.9 (I think it's RKE v1.2.7)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ cat /etc/os-release
NAME=Fedora
VERSION="34.20210518.3.0 (CoreOS)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora CoreOS 34.20210518.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='34.20210518.3.0'
DEFAULT_HOSTNAME=localhost
```

**Steps to Reproduce:**
* Install Kubernetes version v1.19.9 with Rancher on a Single node
* Create a deployment with hostNetwork: true

**Results:**
Got event about DNSConfigForming with message:
`Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.8.8.8 8.8.4.4 8.8.8.8`

In kubelet logs:
`E0610 10:21:06.145444    2528 dns.go:135] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.8.8.8 8.8.4.4 8.8.8.8`

**Comment by superseb** [comment]
Please share the example Deployment so we are talking about the same thing when we are trying to reproduce/investigate. Is any or both of the systems running `systemd-resolved`? What is the hosts `/etc/resolv.conf` (and/or another location if it's running a local caching nameserver)?

**Comment by mecseid** [comment]
Example Pod definition:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: resolver-example
spec:
  hostNetwork: true
  containers:
    - name: resolver-example
      image: debian:latest
```

## Fedora CoreOS (latest stable version)
As the configuration mention, it's managed by NetworkManager
resolv.conf in the host:
```
$ cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 8.8.4.4
```

resolv.conf inside the container:
```
# cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 8.8.8.8
```

## CoreOS (latest available version)
As the configuration mention, it's managed by systemd-resolved
resolv.conf in the host:
```
$ cat /etc/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 8.8.8.8
nameserver 8.8.4.4
```

resolv.conf inside the container:
```
# cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Comment by mecseid** [comment]
@superseb Any update or blocker for this issue?
Can I help somehow to figure it out this problem?

**Comment by superseb** [comment]
What is the output of `pgrep -f systemd-resolved` from both systems?

**Comment by mecseid** [comment]
Both system running systemd-resolved.
CoreOS:
```
$ sudo pgrep -f systemd-resolved
634
20875
```

Fedora CoreOS:
```
$ sudo pgrep -f systemd-resolved
652
4165303
```

SystemD versions:
CoreOS:
```
$ systemctl --version
systemd 241 (241-30-gf0da8f7+)
```

Fedora CoreOS:
```
$ systemctl --version
systemd 248 (v248.3-1.fc34)
```

**Comment by superseb** [comment]
Is `/etc/resolv.conf` on both systems a symlink and to what/where?

**Comment by mecseid** [comment]
On CoreOS, it's a symlink to `/run/systemd/resolve/resolv.conf`, but on Fedora CoreOS, it's a simple file (not hardlink) with contents from https://github.com/rancher/rke/issues/2570#issuecomment-860036219 (which mentions that the file managed by NetworkManager)

**Comment by superseb** [comment]
Does `/run/systemd/resolve/resolv.conf` exist on Fedora CoreOS and what is its content? I will run the config and see what's going on.

**Comment by mecseid** [comment]
Seems interesting.
Thank you in advance for your help.

```
$ cat /run/systemd/resolve/resolv.conf
# This is /run/systemd/resolve/resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 8.8.8.8
# Too many DNS servers configured, the following entries may be ignored.
nameserver 8.8.4.4
search .
```

**Comment by superseb** [comment]
This file is used when the process `systemd-resolved` is detected, so either disabling `systemd-resolved` or changing the config to change this file should solve the issue. Why the files are different on both OS's should be a case of comparing versions/configs.

**Comment by mecseid** [comment]
I think disabling the `systemd-resolved` is not an options, because the Fedora Team wants to use it with NetworkManager:
https://github.com/coreos/fedora-coreos-tracker/issues/646
https://github.com/coreos/fedora-coreos-tracker/issues/834

So I will check the `systemd-resolved` configuration, why contains the same nameserver multiple times.
