### ISSUE TITLE
Stuck on a RKE tutorial blog due to broken link

### ISSUE THREAD

**Issue by jchariot** [rancher/rke#2576]
I am new to RKE and is following https://rancher.com/blog/2018/2018-09-26-setup-basic-kubernetes-cluster-with-ease-using-rke/ , and all is well until the part that I need to input https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

This Kubernetes Dashboard link returns 404: Not Found, and because of this, I couldn’t proceed further. So is there a newer link to be used for this case?

Please assist. Thank you.

**Comment by superseb** [comment]
There is probably a lot more changed than just the URL, you can follow the regular install steps here https://github.com/kubernetes/dashboard#install . I will check if we can easily update the steps described (which will also be pointing to the dashboard project)

**Comment by sondnpt00343** [comment]
I saw a similar article: https://itnext.io/setup-a-basic-kubernetes-cluster-with-ease-using-rke-a5f3cc44f26f
