### ISSUE TITLE
Make RKE more precise about the fact that swap has to be disabled

### ISSUE THREAD

**Issue by tychota** [rancher/rke#260]
Hi,

was about to open a bug for:

```
FATA[0115] [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check /healthz for service [kubelet] on host [redacted_ip]: Get https://localhost/healthz: Failed to dial to Healthcheck Port [10250] on host [redacted_ip]: ssh: rejected: connect failed (Connection refused)
```

I did find the answer here https://github.com/kubernetes/kubernetes/issues/53333#issuecomment-333587943

It would be nice of rke to check for swap:
https://github.com/kubernetes/kubernetes/blob/a5c46303a2ed2c252c69855b3e650103f08a5703/pkg/kubelet/cm/container_manager_linux.go#L204-L215

and fail with a nice error.

I would say, those lines can be copy pasted here: https://github.com/rancher/rke/blob/523f3ce778d2b060f9956583ee7bbf4ff7f631c7/services/kubelet.go#L15

I'm open to contribute if it is ok for you.

**Comment by moelsayed** [comment]
Tested with latest master. RKE Would fail to start kubelet with `fail_swap_on: true`. Otherwise swap is ignored and kubelet is started normally.

**Comment by zedtux** [comment]
@tychota I tried to disable the swap on my machines (`swapoff -a`) but `rke` is still failing with the same error.

Anything you did else ?
