### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#261]
RKE is great, but some things need improvements in terms of speed.

1. Image pull should be done in parallel on all the nodes; perhaps during control plane coming up. So by the time the workers are ready to deploy, we have to make sure that the images are pulled. It means in that in the code we should separate image pull from component deployment.

2. Certificate deployment is being done on per role (component). If node has more than one role, the deployer will run 3 times. We have to run it only once, per node. 

3. Port checks in parallel

4. Saving certificates and the states in parallel.

**Comment by moelsayed** [comment]
Note: Port checking is already running in parallel.

**Comment by galal-hussein** [comment]
version v0.1.1-rc1

I can verify all 4 points with rke:

- k8s image is being pulled on all nodes before deployment in parallel:
```
INFO[0031] Pre-pulling kubernetes images                
DEBU[0031] [pre-deploy] Checking image [docker.io/rancher/k8s:v1.9.2-rancher1-1] on host [x.x.x.x] 
DEBU[0031] [pre-deploy] Checking image [docker.io/rancher/k8s:v1.9.2-rancher1-1] on host [y.y.y.y] 
DEBU[0031] Checking if image [docker.io/rancher/k8s:v1.9.2-rancher1-1] exists on host [z.z.z.z] 
```
- Certificate deployment has been refactored to only run cert deployer once per node
- Port checks is being executed in parallel
- Saving certificate has been verified #293
