### ISSUE TITLE
RKE 1.2.10: v1.20.9-rancher1 is an unsupported Kubernetes version

### ISSUE THREAD

**Issue by cmmarslender** [rancher/rke#2619]
**RKE version:**
1.2.10

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
`5.4.0-80-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
one cluster is bare metal
other is ESXi hosts

**cluster.yml file:**
`kubernetes_version: "v1.20.9-rancher1"`

**Steps to Reproduce:**

Update kubernetes_version to the new version specified in the release on github

**Results:**

```
time="2021-07-26T19:35:22Z" level=info msg="Running RKE version: v1.2.10"
time="2021-07-26T19:35:22Z" level=info msg="Initiating Kubernetes cluster"
time="2021-07-26T19:35:23Z" level=fatal msg="Failed to validate cluster: v1.20.9-rancher1 is an unsupported Kubernetes version and system images are not populated: etcd image is not populated"
```

**Comment by carloscarnero** [comment]
Also:

```console
$ rke config -l -a
v1.19.13-rancher1-1
v1.18.20-rancher1-2
v1.17.17-rancher2-3
v1.20.9-rancher1-1
```

but:

```console
$ rke config -l
v1.20.8-rancher1-1
```

This is all under Linux 64 bits.

**Comment by superseb** [comment]
Does it work with `kubernetes_version: "v1.20.9-rancher1-1"` ?

**Comment by difrost** [comment]
@superseb Forcing version will of course work. The default is still on 1.20.8: https://github.com/rancher/kontainer-driver-metadata/blob/dec698a902187638c00955d77c4cab635c9029e6/rke/k8s_version_info.go#L40

**Comment by superseb** [comment]
Yeah we are looking at it

**Comment by anupama2501** [comment]
Verified as part of https://github.com/rancher/rancher/issues/33780

**Comment by carloscarnero** [comment]
Using `1.2.11` as released I could successfully upgrade four different clusters, because:

```console
$ rke config -l -a
v1.17.17-rancher2-3
v1.18.20-rancher1-2
v1.19.13-rancher1-1
v1.20.9-rancher1-1
$ rke config -l
v1.20.9-rancher1-1
```

So, it looks alright?
