### ISSUE TITLE
Flannel pods do not come active on SELinux enabled nodes

### ISSUE THREAD

**Issue by izaac** [rancher/rke#2620]
**RKE version:**
v1.3.0-rc9

**Docker version:**
19.03.15

**Operating system and kernel:**

CentOS 7.9 `3.10.0-1160.el7.x86_64`
Oracle Linux 7.9

**Type/provider of hosts:**
AWS pre-configured AMI with `rancher-selinux` from the `rancher-testing` RPM repository

```
rpm -qa | grep rancher-selinux
rancher-selinux-0.2~rc2-1.el7.noarch
```

**cluster.yml file:**

```yaml
kubernetes_version: v1.20.8-rancher1-1
nodes:
  - address: <EXTERNAL>
    internal_address: <INTERNAL>
    user: centos
    # role: [etcd, controlplane,worker]
    hostname_override: izrket1
    role: [etcd]
  - address: <EXTERNAL>
    internal_address: <INTERNAL>
    user: centos
    hostname_override: izrket2
    role: [controlplane]
  - address: <EXTERNAL>
    internal_address: <INTERNAL>
    user: centos
    hostname_override: izrket3
    role: [worker]

services:
  etcd:
    backup_config:
      timeout: 30
      interval_hours: 1
      retention: 6
      safe_timestamp: true
      enabled: true
    snapshot: true
    creation: 1h
    retention: 24h
network:
  mtu: 0
  options:
    flannel_backend_type: vxlan
  plugin: flannel
```

**Steps to Reproduce:**

- `rke up`
- `kubectl get all -n kube-system`

**Results:**
```
k get all -n kube-system                                
NAME                                          READY   STATUS              RESTARTS   AGE
pod/coredns-55b58f978-mh29z                   0/1     ContainerCreating   0          25m
pod/coredns-autoscaler-76f8869cc9-84x9k       0/1     ContainerCreating   0          25m
pod/kube-flannel-8fzp2                        1/2     CrashLoopBackOff    9          25m
pod/kube-flannel-smhck                        1/2     CrashLoopBackOff    9          25m
pod/kube-flannel-zhq5g                        1/2     CrashLoopBackOff    9          25m
pod/metrics-server-55fdd84cd4-fq49l           0/1     ContainerCreating   0          25m
pod/rke-coredns-addon-deploy-job-b66t6        0/1     Completed           0          25m
pod/rke-ingress-controller-deploy-job-d7rkz   0/1     Completed           0          25m
pod/rke-metrics-addon-deploy-job-7jtqg        0/1     Completed           0          25m
pod/rke-network-plugin-deploy-job-8hhlp       0/1     Completed           0          25m
```
Log from a `kube-flannel` pod:

```
I0726 20:36:15.975831       1 main.go:518] Determining IP address of default interface
I0726 20:36:15.976715       1 main.go:531] Using interface with name eth0 and address 172.31.5.100
I0726 20:36:15.976737       1 main.go:548] Defaulting external address to interface address (172.31.5.100)
W0726 20:36:15.976754       1 client_config.go:517] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0726 20:36:16.102182       1 kube.go:119] Waiting 10m0s for node controller to sync
I0726 20:36:16.102798       1 kube.go:306] Starting kube subnet manager
I0726 20:36:17.102865       1 kube.go:126] Node controller sync successful
I0726 20:36:17.102926       1 main.go:246] Created subnet manager: Kubernetes Subnet Manager - izrket3
I0726 20:36:17.102934       1 main.go:249] Installing signal handlers
I0726 20:36:17.103017       1 main.go:390] Found network config - Backend type: vxlan
I0726 20:36:17.103114       1 vxlan.go:121] VXLAN config: VNI=1 Port=8472 GBP=false Learning=false DirectRouting=false
E0726 20:36:17.104243       1 main.go:291] Error registering network: operation not supported
I0726 20:36:17.104315       1 main.go:370] Stopping shutdownHandler...
```

**Flannel come up fine without SELinux enabled docker.**

**Comment by superseb** [comment]
The generated policy based on the AVC denied errors:

```
#============= container_t ==============                                      
allow container_t iptables_var_run_t:file read;                                

#!!!! This avc can be allowed using the boolean 'domain_kernel_load_modules'   
allow container_t kernel_t:system module_request;                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                              
#!!!! WARNING: 'var_run_t' is a base type.                                                                                                                                                                                                                                                                                    
allow container_t var_run_t:dir write;   
```

Besides the boolean change (which still needs a manual action), this would require the `rancher-selinux` RPM to add rules to generic types (`container_t`, `iptables_var_run_t` and even the base type `var_run_t`) which I don't think we should do.

Two options that come to mind:

- Run flannel as privileged, this would be in line with how calico and canal (calico+flannel) are running today (also explains why it works when using those)
- Change the flannel SELinux context to run as `rke_container_t` and now we can influence behavior of this in the `rancher-selinux` RPM
- Change the context on the files flannel creates using the `rancher-selinux` RPM so `container_t` can access them.

Any thoughts @cmurphy @dweomer on this?

**Comment by cmurphy** [comment]
> Run flannel as privileged, this would be in line with how calico and canal (calico+flannel) are running today (also explains why it works when using those)

I think this, or running as `spc_t`, would be okay. I think any CNI is going to need a high degree of access to the system. I suspect the generated policy you found is just the beginning of the full set of policies that would be needed. I can't find many other suggestions online for how to use Flannel on an SELinux-enforcing system, this is the best that I've found: https://bugzilla.redhat.com/show_bug.cgi?id=1546160

> Change the flannel SELinux context to run as rke_container_t and now we can influence behavior of this in the rancher-selinux RPM

This might be okay if it ends up not being too many rules, but maybe it would be good to create a new process type like `rke_flannel_t` or something just for this?

> Change the context on the files flannel creates using the rancher-selinux RPM so container_t can access them.

This was also suggested in the redhat bug above. My thinking on this is that it would be better to run one application as privileged so that it can do its job, rather than grant all applications the right to write to sensitive files when most of them don't need to. What do you think?

**Comment by superseb** [comment]
I think, given that the canal template also runs flannel as privileged, we can do that for now. Thanks for taking a look.

**Comment by superseb** [comment]
Can be tested in combination with https://github.com/rancher/rancher-selinux/releases/tag/v0.2-rc4.testing.1

**Comment by izaac** [comment]
Rancher version: `2.6-head (08/02/2021)` _6c14c33_

CentOS 8.4 and 7.9 are working with SELinux and Flannel with the RPM (`rancher-selinux-0.2~rc4`) 

On the other hand Cluster with Oracle Linux nodes still have the `kube-flannel` pods failing with the same error.

**Comment by superseb** [comment]
@izaac Please share the setup/nodes, I can't reproduce on OEL 7.9 and 8.4.

**Comment by izaac** [comment]
@superseb I will get a new setup and ping you once I get it ready

**Comment by izaac** [comment]
Rancher version: `2.6-head (08/03/2021)` _10588ab_

After further testing this seems to be happening on clusters with Kubernetes version 1.19 and 1.20 on this Rancher 2.6 build.
It's just not only Oracle Linux, CentOS too.
On clusters using Kubernetes 1.21 the flannel pods come up active.

**Comment by superseb** [comment]
Yeah, we only changed the template for 1.21. Do we want to backport this template change to 1.20 and 1.19 @cbron ? It never worked for any version but the fix was only applied to the new template we introduced for 1.21.

**Comment by cbron** [comment]
Given how close we are to the release, let's stick with 1.21 for 2.6.0 and add more later as needed.

**Comment by superseb** [comment]
Created https://github.com/rancher/rke/issues/2636 for follow up.

**Comment by izaac** [comment]
Closing in favor of the follow up https://github.com/rancher/rke/issues/2636 Now that:

- RKE v1.3.0-rc10 (HA local)
- RHEL 8.4, 7.9 
- CentOS 8.3, 7.9
- Oracle Linux 8.3, 7.9
- SELinux RPM `rancher-selinux-0.2~rc4`
- Rancher version: `2.6-head (08/03/2021)` _10588ab_
- Docker 19.03.15, 20.10.7

These work with Kubernetes 1.21 and Flannel as Network Provider.
