### ISSUE TITLE
Why is the cluster only active after adding the worker nodes?

### ISSUE THREAD

**Issue by rgl** [rancher/rke#2622]
Can you please help me understand why is the cluster only active after adding the worker nodes?

Why isn't it sufficient to wait for the nodes that have the etcd and controlplane roles?

Please note that I'm not sure if this is a rke or rancher question. I'm observing this in rancher 2.5.9.

**RKE version:**

1.2.10

**Docker version: (`docker version`,`docker info` preferred)**

20.10.7

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Ubuntu 20.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

KVM

**cluster.yml file:**

N/A

**Steps to Reproduce:**

N/A

**Results:**

N/A

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/31244#issuecomment-790274280
