### ISSUE TITLE
Timeout with 2x instances EC2

### ISSUE THREAD

**Issue by jsilvavertigo** [rancher/rke#2631]

**Comment by superseb** [comment]
What EC2 instance types are you using? Does it work 100% when you try to contact the nodes directly for testing? Does the network on the instances perform correctly? Does the overlay network work correctly?

**Comment by jsilvavertigo** [comment]
> What EC2 instance types are you using? Does it work 100% when you try to contact the nodes directly for testing? Does the network on the instances perform correctly? Does the overlay network work correctly?

Srry Superseb.
It work!
Thx!
