### ISSUE TITLE
Release Tags

### ISSUE THREAD

**Issue by eminalemdar** [rancher/rke#2658]
When there is any merge to the master branch I believe it automatically labels that merge as the latest release. When we want to download the latest release we wouldn't be able to download the latest and stable release actually. For example, right now **v1.1.19** is labeled as latest but actually, there is **v.1.2.11** release and it is verified.

Can you please fix this?

**Comment by superseb** [comment]
This is based on the creation of the tag, not actual latest (or controllable by us). We added https://github.com/rancher/rke#latest-release to make sure the latest release is known to everyone.

**Comment by eminalemdar** [comment]
When we use `curl -s https://api.github.com/repos/rancher/rke/releases/latest` to get the latest release's download URL we still get older versions actually.

We have this Ansible role:

- name: Get latest RKE download URL
  command : curl -s https://api.github.com/repos/rancher/rke/releases/latest
  register: rke_json

- name: Set rke_object variable
  set_fact:
    rke_object: "{{ rke_json.stdout | from_json }}"


- name: Set rke_download_url variable
  set_fact:
    rke_download_url: "{{ (rke_object.assets|selectattr('browser_download_url','contains','linux-amd64')|first).browser_download_url }}"
  loop_control:
    label: "{{ rke_object.tag_name }}"

- name: Get RKE
  become: true
  get_url:
    url: "{{ rke_download_url }}"
    dest: /usr/local/bin/rke
    mode: a+x

**Comment by superseb** [comment]
Yes, I explained it's based on timestamp so when we release another version from a release branch, it can get marked as latest based on timestamp but its not actually latest. Also see https://github.community/t/latest-release-isnt-the-real-latest/2244 and other topics on this.

There are other online services that serve you GitHub releases with filters or you can use the README link.
