### ISSUE TITLE
 where to set RKE used container image names inside rancher image?

### ISSUE THREAD

**Issue by wonleing** [rancher/rke#2665]
I am using Rancher UI to create k8s cluster with rke.
By default it will try to load rancher/rke-tools:v0.1.75. I have a strong reason to modify all image names needed.
The question is where to set these container image names? I tried /var/lib/rancher-data/driver-metadata/data.json inside rancher image. (and then commit the image and rerun) But seems not work.
Any idea?

**Comment by superseb** [comment]
This is actually a `rancher/rancher` issue, but the `data.json` gets embedded in the image and we set an external URL to fetch data from. We've used this for testing and if you define your version with your set of images, it should pick that up (as that is how we "officially" make versions). If it doesn't work, please provide the way you are doing things so we can check what is not working.

**Comment by wonleing** [comment]
1. I changed  "K8sVersionServiceOptions" section of data.json. Removed useless versions, (I just need 1 version, and just flannel support). like below. (other parts not touched):
 "K8sVersionServiceOptions": {
  "v1.18.20-rancher1-1": {
   "etcd": "myharboraddress/etcd:v3.5.0",
   "alpine": "myharboraddress/rke-tools:v0.1.28",
   "nginxProxy": "myharboraddress/rke-tools:v0.1.28",
   "certDownloader": "myharboraddress/rke-tools:v0.1.28",
   "kubernetesServicesSidecar": "myharboraddress/rke-tools:v0.1.28",
   "kubedns": "myharboraddress/k8s-dns-kube-dns:84b583e-dirty",
   "dnsmasq": "myharboraddress/k8s-dns-dnsmasq:84b583e-dirty",
   "kubednsSidecar": "myharboraddress/k8s-dns-sidecar:84b583e-dirty",
   "kubednsAutoscaler": "myharboraddress/cluster-proportional-autoscaler:1.8.1",
   "coredns": "myharboraddress/coredns:v1.18.5",
   "corednsAutoscaler": "myharboraddress/cluster-proportional-autoscaler:1.8.1",
   "nodelocal": "myharboraddress/k8s-dns-node-cache:84b583e-dirty",
   "kubernetes": "myharboraddress/hyperkube:v1.18.5",
   "flannel": "myharboraddress/flannel:v1.18.5",
   "flannelCni": "myharboraddress/flannel-cni:v0.3.0",
   "podInfraContainer": "myharboraddress/pause:v1.18.5",
   "ingress": "myharboraddress/k8s-staging-ingress-nginx/controller:v0.34.1",
   "ingressBackend": "myharboraddress/defaultbackend:1.4",
   "metricsServer": "myharboraddress/metrics-server:0.4.1",
   "windowsPodInfraContainer": "myharboraddress/pause:v1.18.5"
  }
 }
2. I know the 'external URL' you mentioned in rke/codegen/codegen.go, I changed defaultURL to my URL, and upload  changed  data.json to my URL. and recomipled rke binary
3. I copid changed data.json into Rancher containerd image and commit it. *But I don't know where my  recomipled rke binary copy to*
4. sudo docker run -d --restart=unless-stopped -v /var/lib/rancher/:/var/lib/rancher/ -p 81:80 -p 4443:443 <my rancher image>
5. open rancherUI and create cluster, paste and run "sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run <my rancher image> --server https://<myIP>:4443 --token xxx --ca-checksum xxx --etcd --controlplane --worker" in the terminal.
6. Then see the error it tries to find and download rancher/rke-tools:v0.1.75 (there's no suite image for my arch)

So I guess my stuck is 'where my  recomipled rke binary and  cluster.yml should copy to'? and how to let rancher call it? (I already have tested my  recomipled rke binary, and ./rke up --config cluster.yml works fine)

**Comment by superseb** [comment]
`K8sVersionServiceOptions` is not where the images are specified. Also, half editing stuff and then copying it is not the way to go. Create a new Rancher k8s version (`v1.18.20-rancher1-2` or something) and change the images you need, thats the proper way to do it. If you want shortcuts, you will run into issues. Rancher creates CRs for the version (`kubectl  get crd | grep ^rke`). Also, the rke binary is not used in Rancher, its vendored in as Go module.

Registry addresses also don't belong in the data.json as they are set in Rancher and the images are prefixed with that configuration.

What arch are you looking for, are you compiling everything yourself?

**Comment by wonleing** [comment]
>K8sVersionServiceOptions is not where the images are specified
So which section I need to edit?
>Create a new Rancher k8s version
It is not an option for me. I need to delete upsupported versions. I would like to use v1.18.5 as the name, but seems illeagle.
>rke binary is not used in Rancher, its vendored in as Go module.
Thanks for the hint. I guess I need to edit rancher/vendor/github.com/rancher/rke/data/data.json. Again, which section?
Or better, is there any tool or command to generate data.json for my situation?
>What arch are you looking for, are you compiling everything yourself?
Alpha. Yes I compiled everything myself. So you know why I have only 1 supported version...

**Comment by superseb** [comment]
I have to test it but I would say, generate a `data.json` which is to your liking (Which is done using `rancher/kontainer-driver-metadata` and then `go generate` to generate), embed that into your custom build of Rancher instead of the default one, change the URL where the external `data.json` is retrieved from to a dummy so you don't get any other versions.

**Comment by wonleing** [comment]
I have generated data.json. I have changed the external URL of data.json in the code, and upload the generated data.json onto that URL.
When I run scripts/build scripts/package inside rancher project, I can see bin/data.json and package/data.json is right.
But After I run rancher with this new rancher image, the dropdown list still has many fault versions, and creating cluster still report 'can not find rancher/rke-tools:v0.1.75' (I changed the image name in my data.json)
Seems the newly generated data.json is not used...

**Comment by wonleing** [comment]
Also , I confirmed /var/lib/rancher-data/driver-metadata/data.json inside rancher image is my newly generated one.
So what makes rancher keep tring to find rancher/rke-tools:v0.1.75?

**Comment by superseb** [comment]
Can you share the `data.json` file? I can look up where its getting it from.

**Comment by wonleing** [comment]
[data-json.txt](https://github.com/rancher/rke/files/7064980/data-json.txt)

And I found there's a process like this:
channelserver --config-key=k3s --url https://releases.rancher.com/kontainer-driver-metadata/release-v2.4/data.json --url=/var/lib/rancher-data/driver-metadata/data.json --refresh-interval 24h0m0s --listen-address=0.0.0.0:8115 --channel-server-version v2.4.7 v2.4.7

Is this why my data.json not effected? How to change it?

**Comment by wonleing** [comment]
channelserver --config-key=k3s --url http://myreposerver/dependence/rke/data.json --url=/var/lib/rancher-data/driver-metadata/data.json --refresh-interval 24h0m0s --listen-address=0.0.0.0:8115 --channel-server-version v2.4.7 v2.4.7

I double checked http://myreposerver/dependence/rke/data.json and /var/lib/rancher-data/driver-metadata/data.json inside rancher container are all updated. But the non-exist version still shows in Kubernetes version dropdown list
