### ISSUE TITLE
rke ignores ~/.ssh/config

### ISSUE THREAD

**Issue by joshuacox** [rancher/rke#267]
**RKE version:** 0.0.12-dev

**Docker version: (`docker version`,`docker info` preferred)**

Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 7
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-31-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.65GiB
Name: stealth
ID: YEBZ:JD64:52HI:IRA6:LSUG:MRUD:ZKOI:TDQN:2YJH:MH6I:GCR7:2QLT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

ubuntu 17.10
4.13.0-31-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

bare-metal

**cluster.yml file:**

nodes:
  - address: host1
    user: rancher
    role: [controlplane,worker,etcd]
  - address: host2
    user: rancher
    role: [controlplane,worker,etcd]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2

**Steps to Reproduce:**

configure proxied hosts

```
cat ~/.ssh/config

Host host1
  ForwardAgent yes
  Hostname 10.0.0.21
  Port 22
  User rancher
  ProxyCommand ssh -q -W  %h:%p -p22 rancher@myexternalhost.example.com
Host host2
  ForwardAgent yes
  Hostname 10.0.0.22
  Port 22
  User rancher
  ProxyCommand ssh -q -W  %h:%p -p22 rancher@myexternalhost.example.com
```

**Results:**

rke ignores ssh config:

```
INFO[0000] Building Kubernetes cluster                  
INFO[0000] [dialer] Setup tunnel for host [host1]    
FATA[0010] Failed to set up SSH tunneling for Etcd host [host1]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial ssh using address [host1:22]: dial tcp: lookup host1 on 127.0.0.53:53: read udp 127.0.0.1:52857->127.0.0.53:53: i/o timeout 
```

**Comment by vincent99** [comment]
RKE uses the golang [SSH client](https://godoc.org/golang.org/x/crypto/ssh), which doesn't know anything about OpenSSH's config files.

**Comment by joshuacox** [comment]
any way I can tell RKE to use a proxy/jumpbox to implement my cluster that is in a private network?

I guess I can just have the provisioning host (where rke runs) inside the network, but I'd like to be able to provision many clusters from a single host

**Comment by superseb** [comment]
We have https://github.com/rancher/rke/issues/103 open for this

**Comment by joshuacox** [comment]
closing here, and watching #103
