### ISSUE TITLE
Too many open files kube-apiserver

### ISSUE THREAD

**Issue by aendi123** [rancher/rke#2692]
**RKE version:** 
`v1.21.4`

**Docker version:**
```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.5
 Git commit:        f0df350
 Built:             Fri Jul 16 12:30:15 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.5
  Git commit:       b0f5bc3
  Built:            Fri Jul 16 00:00:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.3
  GitCommit:
 runc:
  Version:          1.0.1
  GitCommit:        06fb178
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Operating system and kernel:***
```
OS: Fedore CoreOS 34.20210821.3.0
Kernel: 5.13.12-200.fc34.x86_64 Kernel
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** 
Bare-metal

**Steps to Reproduce:**

I'm running a three-node RKE Cluster on bare-metal, every node has the etcd, controlplane and worker role. The cluster was running fine, but since some days (not after an upgrade) I'm getting the following logs all the time only on one node from the kube-apiserver:

```
W0916 15:43:36.497754       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://10.0.2.32:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.0.2.32:2379: socket: too many open files". Reconnecting...
http: Accept error: accept tcp [::]:6443: accept4: too many open files; retrying in 1s
http: Accept error: accept tcp [::]:6443: accept4: too many open files; retrying in 1s
```

I tried 3 things to fix that, none was successful:
1. Added these lines in sysctl.conf:

`fs.file-max=999999`

2. Set global ulimits in /etc/security/limits.conf:

```
* soft nofile 999999
* hard nofile 999999
```

```
$ reboot
$ ulimit -n 
999999
```

3. Set Docker limits in /etc/sysconfig/docker:

`--default-ulimit nofile=4096:4096`

```
$ systemctl restart docker
$ docker exec -it kube-apiserver sh
$ ulimit -n
4096
```

The same logs are still getting generated and the API Server isn't working. I get a lot of timeouts on kubectl and the applications in the cluster. Does anyone have an idea? Thank you.

**Comment by superseb** [comment]
What is causing the open files, can you share `lsof` output? Even with raising the limits, the root cause of why it is happening is better than just raising limits. How long does it take before you hit this error when you restart the container?

**Comment by aendi123** [comment]
Unfortuantely I deleted the environment and cannot provide more info.

**Comment by superseb** [comment]
OK let me know if you (or someone else) encounter(s) it again
