### ISSUE TITLE
Failed to validate cluster: v1.19.15-rancher1 is an unsupported Kubernetes version and system images are not populated: etcd image is not populated

### ISSUE THREAD

**Issue by paradxum** [rancher/rke#2700]
**RKE version:**
v1.2.13

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 28
  Running: 9
  Paused: 0
  Stopped: 19
 Images: 36
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 72cec4be58a9eb6b2910f5d10f1c01ca47d231c0
 runc version: 52b36a2dd837e8462de8e01458bf02cf9eea47dd
 init version: 
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.61-0-virt
 Operating System: Alpine Linux v3.14
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 19.56GiB
 Name: n72
 ID: ZIOA:FUEO:CY3D:A3JY:EHOJ:NBRR:XJRQ:RU27:6UM7:N6UX:CWZZ:IAV3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Alpine 5.10.61-0-virt

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware guests

**cluster.yml file:**
#kubernetes_version: v1.19.8-rancher1-1
kubernetes_version: v1.19.15-rancher1

**Steps to Reproduce:**
Update rke from 1.2.9 to 1.2.13
Update Cluster.yml from kube version:  v1.19.8-rancher1-1 to v1.19.15-rancher1

**Results:**
INFO[0000] Running RKE version: v1.2.13                 
INFO[0000] Initiating Kubernetes cluster                
FATA[0000] Failed to validate cluster: v1.19.15-rancher1 is an unsupported Kubernetes version and system images are not populated: etcd image is not populated 

Rollback to kubernetes_version: v1.19.8-rancher1-1 works fine (except for older version)

**Comment by superseb** [comment]
You can list supported versions using `rke config -l -a`, can you try using `v1.19.15-rancher1-1`?

**Comment by paradxum** [comment]
Thank you.... That fixed it.

In that case it's a doc error here:
https://github.com/rancher/rke/releases/tag/v1.2.13

**Comment by superseb** [comment]
Edited, thanks
