### ISSUE TITLE
rke up error - The container name "/etcd-fix-perm" is already in use

### ISSUE THREAD

**Issue by fafarun** [rancher/rke#2707]
**RKE version:**
1.2.9
**Docker version: (`docker version`,`docker info` preferred)**
20.10
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-1160.31.1.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vsphere 7.0
**cluster.yml file:**
nodes:
- address: 10.10.130.2
  role:
  - controlplane
  - etcd
  - worker
  user: rkedeploy
- address: 10.10.130.4
  role:
  - controlplane
  - etcd
  - worker
  user: rkedeploy
- address: 10.10.130.3
  role:
  - controlplane
  - etcd
  - worker
  user: rkedeploy
kubernetes_version: "v1.20.8-rancher1-1"
ingress:
  provider: nginx

private_registries:
  - url: harbor.val.internal
    is_default: true
~                    
**Steps to Reproduce:**
I create 3 VM with 

a specific disk for /var/lib/docker

I'm working on airgap environment. 
**Results:**
[bug-rke.log](https://github.com/rancher/rke/files/7226100/bug-rke.log)
DEBU[0250] Found regURL harbor.val.internal             
DEBU[0250] Version [3.4.15-rancher1] is equal or higher than version [3.2.99] 
INFO[0250] [etcd] Building up etcd plane..              
DEBU[0250] Checking if image [harbor.val.internal/rancher/rke-tools:v0.1.75] exists on host [10.10.130.2], try rancher/rke#1 
INFO[0250] Image [harbor.val.internal/rancher/rke-tools:v0.1.75] exists on host [10.10.130.2] 
DEBU[0300] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
WARN[0300] Failed to create Docker container [etcd-fix-perm] on host [10.10.130.2]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 
WARN[0300] Failed to create Docker container [etcd-fix-perm] on host [10.10.130.2]: Error response from daemon: Conflict. The container name "/etcd-fix-perm" is already in use by container "66cca55d58739f4895c101a935a23e2be6232afe4321e81dd2781960fd4fbeff". You have to remove (or rename) that container to be able to reuse that name. 
WARN[0300] Failed to create Docker container [etcd-fix-perm] on host [10.10.130.2]: Error response from daemon: Conflict. The container name "/etcd-fix-perm" is already in use by container "66cca55d58739f4895c101a935a23e2be6232afe4321e81dd2781960fd4fbeff". You have to remove (or rename) that container to be able to reuse that name. 
FATA[0300] [etcd] Failed to bring up Etcd Plane: Failed to create [etcd-fix-perm] container on host [10.10.130.2]: Failed to create Docker container [etcd-fix-perm] on host [10.10.130.2]: Error response from daemon: Conflict. The container name "/etcd-fix-perm" is already in use by container "66cca55d58739f4895c101a935a23e2be6232afe4321e81dd2781960fd4fbeff". You have to remove (or rename) that container to be able to reuse that name. 

I need to restart rke up multi time to resolve the problem.

**Comment by superseb** [comment]
This will be fixed via https://github.com/rancher/rke/issues/2632
