### ISSUE TITLE
Networking problem on Debian 11

### ISSUE THREAD

**Issue by andreas-p** [rancher/rke#2708]
**RKE version:**
1.2.8 to 1.3.1
**Docker version:**
docker-ce 5:20.10.8~3-0  
**Operating system and kernel**
Debian11 with 5.10.0-8-amd64 and nftables (default)

RKE is deployed to a cluster of three hosts, with [controlplane,etcd,worker] roles on each.

Performing `kubectl get ns` shows the minimal namespaces as expected, but dependent on which controlplane server is addressed, the result is delivered very fast, or needs about 15 seconds to return.

Running `kubectl -v9` with cleared .kube/cache, I found out that access to "/apis/metrics.k8s.io/v1beta1" on the slow controlplane servers will time out with HTTP status 503 after 5 seconds 3 times, before the result is delivered. 

The fast server is the one who runs the metrics server directly, so apparently the networking between controlplanes and other nodes is broken somehow.

The very same cluster.yml applied to Debian10 hosts works as expected.

**Comment by superseb** [comment]
What k8s version are you using? Please share `cluster.yml` used. Debian 11 is not one of our tested OS's but I can try it.

**Comment by andreas-p** [comment]
Various versions (default from RKE), currently v1.21.5 from RKE 1.3.1, no settings in cluster.yml.

I switched back to debian10 for production purposes, but have system_images: canal_flannel: rancher/mirrored-coreos-flannel:v0.15 to fix segfaults from iptables.

I wonder if that flannel version might help as well. (Can't check myself at the moment)

**Comment by ttk** [comment]
I experienced the same problem.  Using RKE `v1.2.9` with k8s `v1.20.8`.  In another test, it showed that networking between nodes was also broken - I wasn't able to connect to the container's cluster IP from a different (worker) node.   I switched back to debian 10.11 and everything is working fine.

**Comment by quadeare** [comment]
Same here. I try to add a new node under `debian 11` without success.
Using RKE `v1.3.1` with k8s `1.21.5` with `Canal` as cni.

Calico probe fail every minutes without any error from containers.

Here, `calico` pod probe fail :
```
Readiness probe failed: Get "http://localhost:9099/readiness": dial tcp [::1]:9099: connect: connection refused
```

**Comment by ttk** [comment]
Has anyone tested [RKE v1.3.6](https://github.com/rancher/rke/releases/tag/v1.3.6) with Debian 11 (bullseye) yet?  The release notes mention support for iptables > 1.8.5, which look promising considering debian 11 contains iptables v1.8.7.

**Comment by andreas-p** [comment]
Problems appear to be resolved on a fresh 2-node cluster.
rke 1.3.6 on docker-ce 5:20.10.12~3-0 with debian11.
