### ISSUE TITLE
Future plans for RKE

### ISSUE THREAD

**Issue by dren-dk** [rancher/rke#2721]
We've tried to use RKE2, but got stuck on the lack of feature-parity with RKE, so we're building our new clusters on RKE for now and we'd like to continue until RKE2 becomes usable.

I've tried to track down some sort of statement about the future of RKE, but I have not been sucessful.

What are the plans for the future of RKE?

When will a kubernetes 1.22 release of RKE be made?

**Comment by superseb** [comment]
K8s v1.22 is tracked in https://github.com/rancher/rancher/issues/33114, RKE also supports configuring cri-dockerd when dockershim gets removed in kubelet, see https://rancher.com/docs/rke/latest/en/config-options/#cri-dockerd.

Let me know if you have any other questions

**Comment by immanuelfodor** [comment]
@dren-dk could you please elaborate on the part of "lack of feature-parity with RKE"? What features are missing for you that makes it unusable?
