### ISSUE TITLE
Pods dont start when host is offline

### ISSUE THREAD

**Issue by mkl262** [rancher/rke#2724]
Hi,
I installed a cluster on a single node and run an application on it.
Sometimes the node has to start up without internet access, but when it happens, none of the pods start, and many appear with error status.
**RKE version:**
rke version v1.3.1

**Docker version: (`docker version`,`docker info` preferred)**
# docker info
Client:
 Debug Mode: false

Server:
 Containers: 134
  Running: 56
  Paused: 0
  Stopped: 78
 Images: 51
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-38-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.05GiB
 Name: **NODE_NAME**
 ID: 6XSB:HBHI:APVU:GJBI:TQLJ:K72Y:IX56:MXNC:XNMI:CJFQ:V56X:GYVR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

# docker version
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8919
 Built:             Sat Jan 30 03:17:01 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:15:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

5.11.0-38-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**
nodes:
- address: **ip_address**
  user: root
  role: [controlplane,etcd,worker]
  ssh_key_path: /root/.ssh/id_rsa

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 120h
  kubelet:
    extra_binds:
      - "/lib/modules:/lib/modules"
      - "/opt/datapath:/opt/datapath"

authentication:
  sans:
    - "localhost"
    - "127.0.0.1"
    - "**CLUSTER_NAME**"

cluster_name: **CLUSTER_NAME**

network:
  plugin: flannel

ingress:
  provider: nginx

**Steps to Reproduce:**
Create the cluster while connected to internet. disconnect from internet and restart host.

**Results:**
None of the pods start untill internet is connected.

**Comment by superseb** [comment]
Please describe what k8s version you are using and what pods with what error fail to start (`kubectl describe pod` and `docker logs kubelet 2>&1`) to get an idea what is failing.

**Comment by mkl262** [comment]
[kublet.log](https://github.com/rancher/rke/files/7425134/kublet.log)
# kubectl describe pod nginx-ingress-controller-wgkd6 -n ingress-nginx
Name:           nginx-ingress-controller-wgkd6
Namespace:      ingress-nginx
Priority:       0
Node:           192.168.1.240/192.168.1.240
Start Time:     Tue, 26 Oct 2021 10:46:47 +0100
Labels:         app=ingress-nginx
                app.kubernetes.io/component=controller
                app.kubernetes.io/instance=ingress-nginx
                app.kubernetes.io/name=ingress-nginx
                app.kubernetes.io/version=0.48.1
                controller-revision-hash=c5575d6d5
                pod-template-generation=1
Annotations:    k8s.v1.cni.cncf.io/network-status:
                  [{
                      "name": "cbr0",
                      "interface": "eth0",
                      "ips": [
                          "10.42.0.232"
                      ],
                      "mac": "b2:b7:d7:c7:62:4e",
                      "default": true,
                      "dns": {}
                  }]
                k8s.v1.cni.cncf.io/networks-status:
                  [{
                      "name": "cbr0",
                      "interface": "eth0",
                      "ips": [
                          "10.42.0.232"
                      ],
                      "mac": "b2:b7:d7:c7:62:4e",
                      "default": true,
                      "dns": {}
                  }]
Status:         Running
IP:             
IPs:            <none>
Controlled By:  DaemonSet/nginx-ingress-controller
Containers:
  nginx-ingress-controller:
    Container ID:  docker://8f1ee26f977e2cdd75d2213cf18334f351b4b4bd3c4b7b1c72de78dcc7659c49
    Image:         rancher/nginx-ingress-controller:nginx-0.48.1-rancher1
    Image ID:      docker-pullable://rancher/nginx-ingress-controller@sha256:b34ba096ab65cc410e4967477326ce4178ce8c37a7bebdb2e262630665a24d52
    Ports:         8443/TCP, 80/TCP, 443/TCP
    Host Ports:    0/TCP, 80/TCP, 443/TCP
    Args:
      /nginx-ingress-controller
      --election-id=ingress-controller-leader
      --ingress-class=nginx
      --configmap=$(POD_NAMESPACE)/nginx-configuration
      --validating-webhook=:8443
      --validating-webhook-certificate=/usr/local/certificates/cert
      --validating-webhook-key=/usr/local/certificates/key
    State:          Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Wed, 27 Oct 2021 10:39:56 +0100
      Finished:     Wed, 27 Oct 2021 10:42:23 +0100
    Ready:          False
    Restart Count:  7
    Liveness:       http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=5
    Readiness:      http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:       nginx-ingress-controller-wgkd6 (v1:metadata.name)
      POD_NAMESPACE:  ingress-nginx (v1:metadata.namespace)
      LD_PRELOAD:     /usr/local/lib/libmimalloc.so
    Mounts:
      /usr/local/certificates/ from webhook-cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dw86m (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  webhook-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-nginx-admission
    Optional:    false
  kube-api-access-dw86m:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 :NoExecute op=Exists
                             :NoSchedule op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason                  Age                   From                      Message
  ----     ------                  ----                  ----                      -------
  Warning  FailedCreatePodSandBox  10m                   kubelet                   Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "4f30e0587de6a42ab89ced653c18d0b1ab05b70ee386b96d79fae79a46abd52c" network for pod "nginx-ingress-controller-wgkd6": networkPlugin cni failed to set up pod "nginx-ingress-controller-wgkd6_ingress-nginx" network: [ingress-nginx/nginx-ingress-controller-wgkd6:cbr0]: error adding container to network "cbr0": open /run/flannel/subnet.env: no such file or directory
  Normal   SandboxChanged          10m (x2 over 10m)     kubelet                   Pod sandbox changed, it will be killed and re-created.
  Normal   AddedInterface          10m                   multus                    Add eth0 [10.42.0.232/24] from cbr0
  Normal   Pulled                  10m                   kubelet                   Container image "rancher/nginx-ingress-controller:nginx-0.48.1-rancher1" already present on machine
  Normal   Created                 10m                   kubelet                   Created container nginx-ingress-controller
  Normal   Started                 10m                   kubelet                   Started container nginx-ingress-controller
  Normal   RELOAD                  10m                   nginx-ingress-controller  NGINX reload triggered due to a change in configuration
  Normal   SandboxChanged          106s (x26 over 7m5s)  kubelet                   Pod sandbox changed, it will be killed and re-created.

**Comment by superseb** [comment]
@mkl262 Can you share in more detail what `Sometimes the node has to start up without internet access` means and what I can do to reproduce? Is this the same host/machine with the same network config but some link can't route to the internet or is the network on the host/machine changed in anyway to accomplish this?

**Comment by mkl262** [comment]
I installed RKE on my laptop, and I sometimes work without internet access.

**Comment by superseb** [comment]
@mkl262 Not completely following still, RKE binary is run from a computer to a remote machine where the components are deployed. There is no dependency on internet connectivity on the computer running RKE, but I am unsure what your setup looks like. Are you using a remote machine for the cluster or a VM on the laptop that does not have internet connectivity?

**Comment by mkl262** [comment]
Sorry for being unclear, I installed the cluster on my laptop, which runs Ubuntu 20.04, and when I work offline, none of the pods start until I connect to the internet.

**Comment by mkl262** [comment]
I figured it out, flannel network fails to start without default gateway.
I manually added 127.0.0.1 as the gateway and all pods were created successfully.
