### ISSUE TITLE
Respect cluster.Version field

### ISSUE THREAD

**Issue by alena1108** [rancher/rke#274]
cluster object has a top level field Version which defines k8s version for the main image. RKE should respect this field

**Comment by galal-hussein** [comment]
rke version: v0.1.1-rc1
I was able to verify this feature by adding:
```
kubernetes_version: v1.9.2-rancher1-1
```
to the cluster config and i can see this tag is used with rancher/k8s image and can verify the version using `rke version`
```
./rke version

Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-rancher1", GitCommit:"18c4cd80d8f548e68414724f2f2a25e9bb9eab77", GitTreeState:"clean", BuildDate:"2018-01-25T17:50:22Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
