### ISSUE TITLE
Run Conformance Testing for k8s 1.22

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rke#2747]
k8s 1.22 is available starting at rancher 2.6.3. We need to run Conformance Testing for RKE

**Comment by vivek-shilimkar** [comment]
**Rancher Server Setup**

- RKE version:v1.3.3-rc6

**Information about the Cluster** 

- Kubernetes version: v1.22.4-rancher1-1
- Cluster Type: RKE1 - 1-Master, 1-ETCD, 1-Worker 

**Result**
```
Ran 346 of 6433 Specs in 5268.249 seconds
SUCCESS! -- 346 Passed | 0 Failed | 0 Pending | 6087 Skipped
PASS

Ginkgo ran 1 suite in 1h27m50.334026899s
Test Suite Passed
```

**Comment by vivek-shilimkar** [comment]
RKE Conformance test results PR raised on cncf --> https://github.com/cncf/k8s-conformance/pull/1730
