### ISSUE TITLE
The ingress_controller didn't deploy even I have setting in cluster.yml

### ISSUE THREAD

**Issue by vupv** [rancher/rke#2752]
**RKE version:**
rke version v1.3.2

**Docker version: (`docker version`,`docker info` preferred)**
root@master01:~# docker version
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:06 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
root@master01:~#

root@master01:~# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 24
  Running: 12
  Paused: 0
  Stopped: 12
 Images: 8
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-90-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: master01.fe.me
 ID: GU56:QOCX:VMXX:BDXD:6PG7:LQAB:RBQB:LW35:QM2E:5BWG:6TG2:TDSY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
root@master01:~#

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
root@master01:~# uname -r
5.4.0-90-generic

root@master01:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@master01:~#

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**cluster.yml file:**
# If you intended to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 192.168.1.201
  port: "22"
  internal_address: 192.168.1.201
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 192.168.1.202
  port: "22"
  internal_address: 192.168.1.202
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 192.168.1.203
  port: "22"
  internal_address: 192.168.1.203
  role:
  - worker
  hostname_override: ""
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels:
    app: ingress
  taints: []
- address: 192.168.1.204
  port: "22"
  internal_address: 192.168.1.204
  role:
  - worker
  hostname_override: ""
  user: rke
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: canal
  options:
    canal_flannel_backend_type: vxlan
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
authentication:
  strategy: x509
  sans:
    - "k8s.fe.me"
    - "192.169.1.200"
    - "192.169.1.201"
    - "192.169.1.202"
    - "192.169.1.203"
    - "192.169.1.204"
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.4.16-rancher1
  alpine: rancher/rke-tools:v0.1.78
  nginx_proxy: rancher/rke-tools:v0.1.78
  cert_downloader: rancher/rke-tools:v0.1.78
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.78
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.17.4
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.17.4
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.17.4
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.3
  coredns: rancher/mirrored-coredns-coredns:1.8.4
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.3
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.18.0
  kubernetes: rancher/hyperkube:v1.21.6-rancher1
  flannel: rancher/mirrored-coreos-flannel:v0.14.0
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher6
  calico_node: rancher/mirrored-calico-node:v3.19.2
  calico_cni: rancher/mirrored-calico-cni:v3.19.2
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.19.2
  calico_ctl: rancher/mirrored-calico-ctl:v3.19.2
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.19.2
  canal_node: rancher/mirrored-calico-node:v3.19.2
  canal_cni: rancher/mirrored-calico-cni:v3.19.2
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.19.2
  canal_flannel: rancher/mirrored-coreos-flannel:v0.14.0
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.19.2
  weave_node: weaveworks/weave-kube:2.8.1
  weave_cni: weaveworks/weave-npc:2.8.1
  pod_infra_container: rancher/mirrored-pause:3.4.1
  ingress: rancher/nginx-ingress-controller:nginx-0.49.3-rancher1
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
  ingress_webhook: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.1.1
  metrics_server: rancher/mirrored-metrics-server:v0.5.0
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.6
  aci_cni_deploy_container: noiro/cnideploy:5.1.1.0.1ae238a
  aci_host_container: noiro/aci-containers-host:5.1.1.0.1ae238a
  aci_opflex_container: noiro/opflex:5.1.1.0.1ae238a
  aci_mcast_container: noiro/opflex:5.1.1.0.1ae238a
  aci_ovs_container: noiro/openvswitch:5.1.1.0.1ae238a
  aci_controller_container: noiro/aci-containers-controller:5.1.1.0.1ae238a
  aci_gbp_server_container: noiro/gbp-server:5.1.1.0.1ae238a
  aci_opflex_server_container: noiro/opflex-server:5.1.1.0.1ae238a
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
enable_cri_dockerd: null
kubernetes_version: ""
private_registries: []
ingress:
  provider: "nginx"
  node_selector:
    app: ingress
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy:
    strategy: RollingUpdate
    rollingUpdate:
      maxUnavailable: 5
  http_port: 8080
  https_port: 8443
  network_mode: none
  tolerations: []
  default_backend: null
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
cluster_name: "rke"
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  ignore_proxy_env_vars: false
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: ""
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
dns:
  provider: coredns

**Steps to Reproduce:**
rke up
**Results:**
FATA[0417] Failed to get job complete status for job rke-metrics-addon-deploy-job in namespace kube-system

**Comment by superseb** [comment]
Please use proper formatting for `cluster.yml` and provide the full log of `rke up`. Can you use `kubernetes_version` to specify the cluster version and remove `system_images`, this is no longer advised. The versions for `kubernetes_version` can be listed using `rke config -l -a`.

**Comment by vupv** [comment]
Dear @superseb,
Thank you so much for your reply. I have used kubernetes_version and removed system_images as your advice.
Can you check my attached files
[rke.log](https://github.com/rancher/rke/files/7588803/rke.log)
[cluster.txt](https://github.com/rancher/rke/files/7588806/cluster.txt)

**Comment by vupv** [comment]
Full RKE log when executing RKE up the second time with the same cluster.yaml
[rke2.log](https://github.com/rancher/rke/files/7588967/rke2.log)

**Comment by vupv** [comment]
rke@client01:~/k8s$ kubectl get node
NAME            STATUS   ROLES               AGE     VERSION
192.168.1.201   Ready    controlplane,etcd   9m22s   v1.21.6
192.168.1.202   Ready    controlplane,etcd   9m22s   v1.21.6
192.168.1.203   Ready    worker              8m20s   v1.21.6
192.168.1.204   Ready    worker              8m34s   v1.21.6
rke@client01:~/k8s$ kubectl get all --all-namespaces
NAMESPACE     NAME                                           READY   STATUS      RESTARTS   AGE
kube-system   pod/calico-kube-controllers-6c977d77bc-b6sbr   1/1     Running     0          4m11s
kube-system   pod/canal-s65x2                                2/2     Running     3          4m12s
kube-system   pod/canal-shbww                                2/2     Running     1          4m13s
kube-system   pod/canal-vh4fl                                2/2     Running     2          4m11s
kube-system   pod/canal-xslsm                                2/2     Running     0          4m12s
kube-system   pod/rke-network-plugin-deploy-job-r7rrb        0/1     Completed   0          5m22s

NAMESPACE   NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
default     service/kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   31m

NAMESPACE     NAME                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/canal   4         4         4       4            4           kubernetes.io/os=linux   4m16s

NAMESPACE     NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/calico-kube-controllers   1/1     1            1           4m15s

NAMESPACE     NAME                                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/calico-kube-controllers-6c977d77bc   1         1         1       4m14s

NAMESPACE     NAME                                      COMPLETIONS   DURATION   AGE
kube-system   job.batch/rke-network-plugin-deploy-job   1/1           4m22s      5m49s
rke@client01:~/k8s$

**Comment by superseb** [comment]
Both outputs show a different error than the one you reported, can you also share the output of `docker logs kube-apiserver 2>&1`, `docker logs kubelet 2>&1` and `docker logs etcd 2>&1`.

How is the system health during cluster creation (CPU/memory/disk IO/network)? 

Probably the easiest way to rule a lot of stuff out is to just use one node with all roles and make sure that works.

**Comment by vupv** [comment]
Hi superseb 
[kube-apiserver.log](https://github.com/rancher/rke/files/7591740/kube-apiserver.log)
[kubelet.log](https://github.com/rancher/rke/files/7591743/kubelet.log)
[etcd.log](https://github.com/rancher/rke/files/7591744/etcd.log)

How is the system health during cluster creation (CPU/memory/disk IO/network)?
--> all of the boxes is using very small resource 

Because I would like to set up a multi-master and work node. In case we got a problem I may set up one box with all roles.

And can you double-check mine have any wrong in cluster.yaml file?  That file was generated by the command rke config.

**Comment by vupv** [comment]
[cluster.txt](https://github.com/rancher/rke/files/7591831/cluster.txt)

**Comment by superseb** [comment]
Are you using cloud instances/VMs or something else? How many IOPS do you get on the storage on those machines?

**Comment by vupv** [comment]
I am using Virtual Box. Did your see the error related to IOPS

**Comment by vupv** [comment]
I also set up all roles in one node but got the same error.

[rke.log](https://github.com/rancher/rke/files/7594693/rke.log)
[cluster.txt](https://github.com/rancher/rke/files/7594694/cluster.txt)

**Comment by superseb** [comment]
You can check the logs using the commands here: https://rancher.com/docs/rke/latest/en/troubleshooting/provisioning-errors/#failed-to-get-job-complete-status

You can also try raising `addon_job_timeout` to something way bigger than the default (45), and see if it completes but it sounds like a resource issue to me.

**Comment by vupv** [comment]
Which resource got issued

 kubectl -n kube-system get pods -l job-name=rke-network-plugin-deploy-job --no-headers -o custom-columns=NAME:.metadata.name | xargs -L1 kubectl -n kube-system logs

configmap/canal-config created
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org created
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrole.rbac.authorization.k8s.io/calico created
clusterrole.rbac.authorization.k8s.io/flannel created
clusterrolebinding.rbac.authorization.k8s.io/canal-flannel created
clusterrolebinding.rbac.authorization.k8s.io/canal-calico created
daemonset.apps/canal created
serviceaccount/canal created
deployment.apps/calico-kube-controllers created
serviceaccount/calico-kube-controllers created
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
poddisruptionbudget.policy/calico-kube-controllers created

**Comment by superseb** [comment]
OK that looks good, its either on the node(s) or in the pods:

Node:
```
kubectl get nodes -o go-template='{{range .items}}{{$node := .}}{{range .status.conditions}}{{$node.metadata.name}}{{": "}}{{.type}}{{":"}}{{.status}}{{"\n"}}{{end}}{{end}}'
```

Pods:
```
kubectl -n kube-system get pods -l k8s-app=canal
kubectl -n kube-system logs -l k8s-app=canal
```

**Comment by vupv** [comment]
kubectl get nodes -o go-template='{{range .items}}{{$node := .}}{{range .status.conditions}}{{$node.metadata.name}}{{": "}}{{.type}}{{":"}}{{.status}}{{"\n"}}{{end}}{{end}}'

192.168.1.200: NetworkUnavailable:False
192.168.1.200: MemoryPressure:False
192.168.1.200: DiskPressure:False
192.168.1.200: PIDPressure:False
192.168.1.200: Ready:True

kubectl -n kube-system get pods -l k8s-app=canal
NAME          READY   STATUS    RESTARTS   AGE
canal-4d6c6   2/2     Running   0          176m

kubectl -n kube-system logs -l k8s-app=canal -c calico-node
2021-11-24 09:55:37.617 [INFO][10] startup/startup.go 1063: Created default IPv4 pool (172.16.0.0/16) with NAT outgoing true. IPIP mode: Never, VXLAN mode: Never
2021-11-24 09:55:37.617 [INFO][10] startup/startup.go 706: FELIX_IPV6SUPPORT is false through environment variable
2021-11-24 09:55:38.336 [INFO][10] startup/startup.go 228: Using node name: 192.168.1.200
CALICO_NETWORKING_BACKEND is none - no BGP daemon running
Calico node started successfully
2021-11-24 09:55:40.030 [INFO][44] monitor-addresses/startup.go 390: Early log level set to info
2021-11-24 09:55:40.031 [INFO][44] monitor-addresses/startup.go 406: Using NODENAME environment for node name 192.168.1.200
2021-11-24 09:55:40.031 [INFO][44] monitor-addresses/startup.go 418: Determined node name: 192.168.1.200
2021-11-24 09:56:21.581 [WARNING][45] felix/table.go 652: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"wUHhoiAYhphO9Mso", "", "", "", "", "", "", "", "", "", "S93hcgKJrXEqnTfs", "mp77cMpurHhyjLrM", "", ""} chainName="FORWARD" expectedRuleIDs=[]string{"wUHhoiAYhphO9Mso", "", "", "", "", "", "", "", "", "", "", "", "S93hcgKJrXEqnTfs", "mp77cMpurHhyjLrM"} ipVersion=0x4 table="filter"
2021-11-24 10:39:51.354 [WARNING][45] felix/table.go 652: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "O3lYWMrLQYEMJtB5", "", "", "", "", "", ""} chainName="POSTROUTING" expectedRuleIDs=[]string{"O3lYWMrLQYEMJtB5", "", "", "", "", "", "", ""} ipVersion=0x4 table="nat"

 kubectl -n kube-system logs -l k8s-app=canal -c kube-flannel
I1124 09:56:13.684633       1 iptables.go:172] Deleting iptables rule: -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
I1124 09:56:13.685686       1 iptables.go:172] Deleting iptables rule: -d 10.42.0.0/16 -j ACCEPT
I1124 09:56:13.685879       1 iptables.go:172] Deleting iptables rule: ! -s 10.42.0.0/16 -d 10.42.0.0/24 -j RETURN
I1124 09:56:13.687068       1 iptables.go:172] Deleting iptables rule: ! -s 10.42.0.0/16 -d 10.42.0.0/16 -j MASQUERADE --random-fully
I1124 09:56:13.688719       1 iptables.go:160] Adding iptables rule: -s 10.42.0.0/16 -j ACCEPT
I1124 09:56:13.689091       1 iptables.go:160] Adding iptables rule: -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
I1124 09:56:13.691472       1 iptables.go:160] Adding iptables rule: -d 10.42.0.0/16 -j ACCEPT
I1124 09:56:13.691942       1 iptables.go:160] Adding iptables rule: -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
I1124 09:56:13.694446       1 iptables.go:160] Adding iptables rule: ! -s 10.42.0.0/16 -d 10.42.0.0/24 -j RETURN
I1124 09:56:13.696881       1 iptables.go:160] Adding iptables rule: ! -s 10.42.0.0/16 -d 10.42.0.0/16 -j MASQUERADE --random-fully

**Comment by vupv** [comment]
After increasing addon_job_timeout the setup successfully 

[rke3.log](https://github.com/rancher/rke/files/7595735/rke3.log)

**Comment by vupv** [comment]
Let me try with multi-node again

**Comment by vupv** [comment]
The k8s cluster with multi-node setup successfully as well. I didn't see the cert-manager. Is it included when we setup rke

[rke4.log](https://github.com/rancher/rke/files/7596385/rke4.log)

**Comment by superseb** [comment]
cert-manager is not part of RKE, you can deploy it manually if you want. Everything in the logs look fine, so it is just a resource issue. If you have better machine performance, you don't need to increase addon_job_timeout. Also overall I would monitor the performance as it might cause issues (etcd shows a lot of `took too long` messages for example).
