### ISSUE TITLE
RKE snapshot restore in windows node is broken

### ISSUE THREAD

**Issue by sirredbeard** [rancher/rke#2758]
```
rke restore from  the windows node is failing with  file not found error. Customer uploaded the file in S3  and trying to restore from s3 location.

"fatal msg="Failed to download etcd snapshot from s3, exit code [1]: time=\"2021-10-04T12:26:53Z\" level=fatal msg=\"Unable to decompress [/backup/2021-10-04T10_14_40Z_etcd.zip] to [/backup/2021-10-04T10_14_40Z_etcd]: File [/backup/2021-10-04T10_14_40Z_etcd] not found in file [/backup/2021-10-04T10_14_40Z_etcd.zip]\"\n"
```

**Repro steps:**

Configure  the S3 credentials and bucket details to backup on S3
Perform backup and try to restore from windows node
rke etcd snapshot-restore --config rke/rancher-cluster.yml --name "2021-10-04T10_14_40Z_etcd" --use-local-state --s3 --bucket-name "227835638586-rancher-test-etcd-backup" --s3-endpoint "s3.eu-central-1.amazonaws.com"

**Actual behavior:**
rke etcd snapshot-restore is failing with "fail to download the  etcd snapshot from s3"  due to windows is fail to identify the file name with ":"  due to this restore is failing.

The backup code adds the timestamp with the backup snapshot (eg: 2021-10-07T10:12:56Z_etcd.zip). windows is converting the ":" to "_"  due to this , it fail to restore. 

**Expected behavior:**
It would be nice (in a future version) if the backup process uses valid filenames for Windows and Linux.
For example: 2021-10-08T040734Z_etcd.zip (without `:`)

SURE-3598

**Comment by SheilaghM** [comment]
This does look like an RKE problem. @snasovich you should probably take this through the refinement process.  Not sure whether you want Seb assigned or not - I'll leave that to you.

**Comment by HarrisonWAffel** [comment]
RKE1 on windows is [EOL in 2.6.6](https://github.com/rancher/windows/issues/182), so this improvement is no longer actionable
