### ISSUE TITLE
unable to form ec2 infrastructure provider cluster using calico CNI

### ISSUE THREAD

**Issue by dominicpg** [rancher/rke#2773]
ec2 instances failed to form rke downstream infrastructure provider cluster when calico CNI selected. However, works well with Canal CNI.

Steps to reproduce - always
1) deploy downstream cluster using aws node template
2) add cluster -> deploy EC2 cluster using node template
3) forms a broken cluster.

rke - v1.21.6
event logs from Rancher v2.5 GUI

Namespace 	Type 	Reason 	Object 	Message 	Last Seen 
cattle-system	Warning	Unhealthy	cattle-cluster-agent-78f4fbdccf-z245w	Readiness probe failed: Get "http://10.42.36.195:8080/health": dial tcp 10.42.36.195:8080: connect: connection refused	a few seconds ago
cattle-system	Warning	BackOff	cattle-cluster-agent-78f4fbdccf-z245w	Back-off restarting failed container	4 minutes ago
cattle-system	Warning	BackOff	cattle-cluster-agent-78d8578457-2tksw	Back-off restarting failed container	4 minutes ago
cattle-system	Normal	Pulled	cattle-cluster-agent-78d8578457-2tksw	Container image "rancher/rancher-agent:v2.5.8" already present on machine	14 minutes ago
cattle-system	Warning	Unhealthy	cattle-cluster-agent-78d8578457-2tksw	Readiness probe failed: Get "http://10.42.10.129:8080/health": dial tcp 10.42.10.129:8080: connect: connection refused	20 minutes ago
cattle-system	Warning	Unhealthy	cattle-cluster-agent-78f4fbdccf-z245w	Readiness probe failed: Get "http://10.42.36.195:8080/health": dial tcp 10.42.36.195:8080: connect: connection refused	34 minutes ago
kube-system	Warning	Unhealthy	calico-node-b552k	Liveness probe failed:	44 minutes ago
kube-system	Warning	FailedScheduling	coredns-55b58f978-z6b8x	0/3 nodes are available: 3 node(s) didn't match Pod's node affinity.	Invalid date
kube-system	Warning	FailedScheduling	coredns-autoscaler-76f8869cc9-r76gr	0/3 nodes are available: 3 node(s) didn't match Pod's node affinity.	Invalid date
kube-system	Warning	FailedScheduling	metrics-server-55fdd84cd4-b9dwk	0/3 nodes are available: 3 node(s) didn't match Pod's node affinity.	Invalid date

**Comment by superseb** [comment]
This should probably be in `rancher/rancher` as this is tracking RKE CLI issues, please create it via https://github.com/rancher/rancher/issues/new?assignees=&labels=&template=bug_report.md&title= and supply exact versions used (Rancher, I assume v2.5.8 and k8s (full version)), since when it started happening (did it ever work or never), does an older k8s version or also not, and the container logs from the node(s), especially the calico ones that apparently have trouble. And instance AMI would help too (and/or `docker info`)
