### ISSUE TITLE
RKE2 with Rancher UI ?

### ISSUE THREAD

**Issue by atefibra** [rancher/rke#2793]
so I have installed in my home lab a cluster with 3 nodes of RKE2 
They are all working fine. 
NAME     STATUS   ROLES                       AGE   VERSION
master   Ready    control-plane,etcd,master   37h   v1.22.5+rke2r1
node1    Ready    <none>                      37h   v1.22.5+rke2r1
node2    Ready    <none>                      36h   v1.22.5+rke2r1

I have chosen to go for RKE2 because I want to get rid of docker. 
Containerd is the best solution ( for now )

**### My problem is that I cant add Rancher UI without docker !!** 
I want to monitor and visualize the whole cluster using Rancher UI. 
is there a solution ? 
Thanks.

**Comment by atsai1220** [comment]
You would install **rancher** as a Helm chart after instantiating your cluster with rke2.
https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/#install-the-rancher-helm-chart

**Comment by Raamo026** [comment]
> You would install **rancher** as a Helm chart after instantiating your cluster with rke2. https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/#install-the-rancher-helm-chart

Hello. Thank you for your comment, but the link is no more working

**Comment by dustin-groh-dev** [comment]
@Raamo026 try this one.
https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster#5-install-rancher-with-helm-and-your-chosen-certificate-option
