### ISSUE TITLE
rke_v1.22.5-rancher-1-1 vulnarabilities - Remediation 

### ISSUE THREAD

**Issue by mshilamk8s** [rancher/rke#2815]
**RKE version: 1.3.4 ; rke_v1.22.5-rancher-1-1

Reg: Critical and high vulnarabilites

There are around 312 vulnarabilities found out of which 20 are critical and 109 are high vulnarabilities. is there any remediation offered to address the critical and high CVE's in next releases or any active development going on to fix these.

```
 --- 16 unique container images in rke_v1.22.5-rancher1-1 scanned by xray as of 2022-0124-1857 ---
```

| SOURCE | IMAGE | TAG | SCANNED | V3SCORE | TOTAL | CRITICAL | HIGH | MEDIUM |
| - | - | - | - | - | - | - | - | - |
| TOTALS: | | | | | 312 | 20 | 109 | 106 |
| rke_v1.22.5-rancher1-1 | rancher/hyperkube                                        |   v1.22.5-rancher1   |   True  |   9.8   |    66 |        1 |   15 |     19 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-calico-cni                              |       v3.21.1        |   True  |   9.8   |    21 |        1 |   11 |      9 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-calico-ctl                              |       v3.21.1        |   True  |    0    |     0 |        0 |    0 |      0 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-calico-kube-controllers                 |       v3.21.1        |   True  |   8.8   |    12 |        0 |    4 |      8 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-calico-node                             |       v3.21.1        |   True  |   8.5   |    14 |        0 |    0 |     10 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-calico-pod2daemon-flexvol               |       v3.21.1        |   True  |    0    |     0 |        0 |    0 |      0 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-cluster-proportional-autoscaler         |        1.8.3         |   True  |   9.8   |    21 |        2 |   10 |      9 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-cluster-proportional-autoscaler         |        1.8.5         |   True  |   9.8   |    25 |        2 |   13 |     10 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-coredns-coredns                         |        1.8.6         |   True  |    0    |     0 |        0 |    0 |      0 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-coreos-etcd                             |        v3.5.0        |   True  |   9.8   |    68 |        5 |   12 |      9 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-ingress-nginx-kube-webhook-certgen      |        v1.1.1        |   True  |   7.5   |     3 |        0 |    2 |      1 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-metrics-server                          |        v0.5.1        |   True  |   9.8   |    16 |        1 |    6 |      9 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-nginx-ingress-controller-defaultbackend |     1.5-rancher1     |   True  |   9.8   |    22 |        2 |   12 |      8 |
| rke_v1.22.5-rancher1-1 | rancher/mirrored-pause                                   |         3.5          |   True  |    0    |     0 |        0 |    0 |      0 |
| rke_v1.22.5-rancher1-1 | rancher/nginx-ingress-controller                         | nginx-1.1.0-rancher1 |  False  |    0    |     0 |        0 |    0 |      0 |
| rke_v1.22.5-rancher1-1 | rancher/rke-tools                                        |       v0.1.78        |   True  |   9.8   |    44 |        6 |   24 |     14 

Note: @macedogm updated the table format to make it readable.

**Comment by snasovich** [comment]
@mshilamk8s , thank you for your report.
We're not seeing much fewer CVEs in our internal trivy-based scanning. Would you mind sharing the full report showing CVE numbers with their severity levels so we can take a closer look? Thank you in advance.

**Comment by snasovich** [comment]
Closing this one as we have not heard back. @mshilamk8s , if you provide additional information we can reopen it and look deeper.
