### ISSUE TITLE
How to enable GracefullNodeShutdown on rke ?

### ISSUE THREAD

**Issue by brainkiller** [rancher/rke#2818]
How can I enable the featuregate gracefullnodeshutdown on rke ?
I've been trying to get this to work for some time now but I cannot get it working

$ rke --version
rke version v1.3.6

**Docker version: (`docker version`,`docker info` preferred)**
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:22 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.9.0)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
# uname -r
5.15.0-2-amd64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare-metal

**cluster.yml file:**
nodes:
    - address: xxxx
      user: root
      role:
        - etcd
        - controlplane
        - worker
    - address: xxxx
      user: root
      role:
        - worker
    - address: xxxxx
      user: root
      role:
        - worker
        - controlplane
        - etcd
    - address: xxxxx
      user: root
      role:
        - worker
        - controlplane
        - etcd

ignore_docker_version: false

kubernetes_version: v1.22.5-rancher2-1

authentication:
    strategy: x509
    sans:
      - "kube-api"
      - "kube-api.xxx.yyyy"

authorization:
    mode: rbac

network:
    plugin: flannel

dns:
    provider: coredns

addon_job_timeout: 180

ingress:
    provider: nginx
    update_strategy:
      strategy: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 48h
  kube-api:
    extra_args:
      enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction"
  kubelet:
    extra_args:
      feature-gates: "GracefulNodeShutdown=true"
  kube-api:
    always_pull_images: true
    pod_security_policy: false

**Steps to Reproduce:**
Running rke up with the configuration above doesn´t install the systemd inhibitors

**Results:**
# systemd-inhibit --list
No inhibitors.

**Comment by sleepy-manul** [comment]
I think this happens because in Rancher / RKE, all Kubernetes components, including kubelet, run inside docker containers, i.e. they are shielded from the host (unless connected by specific volume mounts, sockets etc.). My suspicion is that due to this, kubelet cannot get contact to the host's systemd. I am not sure if this problem can be fixed.

It would match the following line I find on my system (RHEL7) when kubelet is starting (docker logs):
I0219 13:42:08.034132   18246 mount_linux.go:207] Detected OS without systemd
