### ISSUE TITLE
Unable to use rke with ipv6-only hosts

### ISSUE THREAD

**Issue by gucki** [rancher/rke#2819]
**RKE version:**
v1.3.6

**Docker version: (`docker version`,`docker info` preferred)**
20.10.12

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
debian 11

The hosts are ipv6 only, but can reach ipv4 addresses through nat64. The problem seems to be that rke binds to 0.0.0.0 (ipv4 only).

INFO[0023] [network] Successfully started [rke-port-checker] container on host [k8s01-c03] 
INFO[0023] [network] Successfully started [rke-port-checker] container on host [k8s01-c01] 
INFO[0023] [network] Successfully started [rke-port-checker] container on host [k8s01-c02] 
INFO[0023] Removing container [rke-port-checker] on host [k8s01-c03], try rancher/rke#1 
INFO[0023] Removing container [rke-port-checker] on host [k8s01-c02], try rancher/rke#1 
INFO[0023] Removing container [rke-port-checker] on host [k8s01-c01], try rancher/rke#1 
FATA[0028] [[network] Host [k8s01-c02] is not able to connect to the following ports: [k8s01-c01:2379, k8s01-c01:2380, k8s01-c02:2379, k8s01-c02:2380, k8s01-c03:2379, k8s01-c03:2380]. Please check network policies and firewall rules] 

CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS          PORTS                                                    NAMES
1d15bfdec1b8   rancher/rke-tools:v0.1.78   "/docker-entrypoint.…"   52 minutes ago   Up 52 minutes   80/tcp, 0.0.0.0:6443->1337/tcp                           rke-cp-port-listener
031c136befa9   rancher/rke-tools:v0.1.78   "/docker-entrypoint.…"   52 minutes ago   Up 52 minutes   80/tcp, 0.0.0.0:2379->1337/tcp, 0.0.0.0:2380->1337/tcp   rke-etcd-port-listener

~# telnet 127.0.0.1 2379
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

~# telnet ::1 2379
Trying ::1...
telnet: Unable to connect to remote host: Connection refused

**Comment by gucki** [comment]
As a workaround, I tried to add an ipv4 address to each host (10.11.1.0/24) and specify it as `internal_address` in the cluster.yml. Unfortunately, it didn't help in any way.

**Comment by gucki** [comment]
Adding an ipv4 from the private subnet (10.11.1.0/24) to the local machine (where rke is executed) and specifying the ipv4 addresses using `address` made everything work.

However, I'd be great to have ipv6-only hosts support.

**Comment by sgreene570** [comment]
@gucki looks like this issue is still relevant today. Can we re-open this issue? 

Also, note that this is related to https://github.com/rancher/rke/issues/2165
