### ISSUE TITLE
rke_v1.21.8-rancher-2-1 vulnarabilities - Remediation 

### ISSUE THREAD

**Issue by mshilamk8s** [rancher/rke#2827]
**RKE version: 1.3.6 ; 
rke_v1.21.8-rancher-2-1

Reg: vulnarabilites - Xray report
1145 (CRITICAL: 48, HIGH:584, MEDIUM:394, LOW:110, UNKNOWN: 9)

is there any remediation offered to address the CVE's in next releases and publish new images or any active development going on to fix the CVE's.

**Comment by vasanthkg** [comment]
+1
