### ISSUE TITLE
rke 1.3.7 uses the experimental Kubernetes version v1.22.6-rancher1-1 by default

### ISSUE THREAD

**Issue by harridu** [rancher/rke#2833]
Even though https://github.com/rancher/rke/releases/tag/v1.3.7 lists Kubernetes version v1.22.6-rancher1-1 under "experimental" it is used by default. I didn't ask for an experimental version for the upgrade from rke 1.3.4 to 1.3.7. Now I am stuck with a bricked Rancher installation and all managed clusters are inaccessible.

**Comment by immanuelfodor** [comment]
I successfully upgraded with the new binary from rancher/hyperkube:v1.21.8-rancher2 to rancher/hyperkube:v1.22.6-rancher1 and the cluster is working fine. However I get `FATA[0340] [k8s] Job [rke-network-plugin-deploy-job] deletion timed out. Consider increasing addon_job_timeout value` even with addon_job_timeout=300. Canal pods stayed on the previous v3.19.2 tags instead of v3.21.1 because of this.

**Comment by immanuelfodor** [comment]
Rebooted the nodes, then all nginx ingress pods are in a crash loop due to not being updated from rancher/nginx-ingress-controller:nginx-0.49.3-rancher1 to rancher/nginx-ingress-controller:nginx-1.1.0-rancher1. v0.49.X is not compatible with k8s v1.22 according to https://github.com/rancher/ingress-nginx/tree/nginx-0.49.x-fix#support-versions-table I suppose their update should run after the `rke-network-plugin-deploy-job`. Now my cluster is also broken, achievement unlocked :sob:

**Comment by immanuelfodor** [comment]
`rke --debug up` showed `DEBU[0240] [k8s] waiting for job rke-network-plugin-deploy-job to delete..` so I listed all jobs in the cluster, and found the matching one in kube-system. Then I said YOLO and ran `k delete job rke-network-plugin-deploy-job -n kube-system` which resulted in `rke up` progressing to coredns setup. Now it got stuck again. This time I ran `k delete job rke-coredns-addon-deploy-job -n kube-system` to make it progress to metrics addon. That got stuck again at ingress controller but a quick `k delete job rke-ingress-controller-deploy-job -n kube-system` solved that again. Includes addon made it stuck again, it was solved by `k delete job rke-user-includes-addons-deploy-job -n kube-system`. Then `rke up` finished nicely, all stuff got updated well, and the cluster is working again. I hope you can make your cluster work again, too, @harridu 

![image](https://user-images.githubusercontent.com/21174107/153727339-141ac0a2-86c5-4e49-978d-ef7d34d51bcc.png)

![image](https://user-images.githubusercontent.com/21174107/153727362-bc863e38-15db-4ecf-9a9b-5cd2dadb598e.png)

**Comment by immanuelfodor** [comment]
So maybe these are the ~~droids~~ jobs you're looking for: 

```bash
# k get job -n kube-system
NAME                                  COMPLETIONS   DURATION   AGE
rke-coredns-addon-deploy-job          1/1           2s         9m23s
rke-ingress-controller-deploy-job     1/1           3s         7m43s
rke-metrics-addon-deploy-job          1/1           2s         8m18s
rke-network-plugin-deploy-job         1/1           2s         13m
rke-user-includes-addons-deploy-job   1/1           3s         6m58s
```

**Comment by harridu** [comment]
Hi @immanuelfodor, thank you very much for your investigation and helpful hints, but to make things work again I had restored my rancher cluster from backup yesterday. I cannot risk another update and stall all clusters again. Hopefully this problem gets fixed (and tested !!!) by the developers.

**Comment by patrikbeno** [comment]
I personally started fresh 1.3.7 install and I don't seem to have any issues for now, but I certainly didn't expect that I get experimental version by default.

Not sure if it's safe to stay on this version and hope for the best or go through all the pain of rebuilding the cluster from scratch.

**Comment by ghost** [comment]
I did a big upgrade yesterday (RKE 1.2.8 to 1.3.7), in this order:
`cert-manager -> Rancher -> RKE (K8s) -> Docker Engine`

1. cert-manager from 0.15 to 1.4.0
```
# since I have cert-manager installed without `--set installCRDs=true` helm flag, have to manually upgrade crds
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.4.0/cert-manager.crds.yaml

helm upgrade \
  -n cert-manager \
  cert-manager jetstack/cert-manager \
  --version v1.4.0
```

2. Rancher UI from 2.5.8 to 2.6.3
```
helm upgrade \
  -n cattle-system \
  --set hostname=<REDACTED> \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=<REDACTED> \
  --version=2.6.3 \
  rancher \
  rancher-stable/rancher
```

3. RKE from 1.2.8 to 1.3.7
```
rke config
rke up
```

4. cert-manager from 1.4.0 to 1.6.2
```
helm upgrade \
  -n cert-manager \
  cert-manager jetstack/cert-manager \
  --version v1.6.2
```

5. migrate cert-manager API to unlock cert-manager upgrade to 1.7.1 (latest)
```
cmctl upgrade migrate-api-version --qps 5 --burst 10
```

6. cert-manager from 1.6.2 to 1.7.1
```
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml

helm upgrade \
  -n cert-manager \
  cert-manager jetstack/cert-manager \
  --version v1.7.1
```

7. Docker Engine from 19 to 20
```
wget https://releases.rancher.com/install-docker/20.10.sh
sh 20.10.sh
```

8. (optional) making sure CoreDNS can also run on control plane nodes

> CoreDNS already tolerates running there thanks to `NoExecute`, `NoSchedule` tolerations in its manifest, so just needed to remove nodeAffinity which wants it to only run on `node-role.kubernetes.io/worker` node by default.

```
$ kubectl -n kube-system patch deployment coredns-autoscaler --type json -p '[{"op": "remove", "path": "/spec/template/spec/affinity/nodeAffinity" }]'

$ kubectl -n kube-system patch deployment coredns --type json -p '[{"op": "remove", "path": "/spec/template/spec/affinity/nodeAffinity" }]'
```

Everything went without any issues.

@harridu what output are you getting for these commands?

```
helm list -A
kubectl get pods -A
```

Most of issues I had were because of a stuck `cert-manager` which Rancher relies upon. If that's the case, then reinstall cert-manager in this way:

```
helm -n cert-manager uninstall cert-manager
kubectl delete ns cert-manager

# and re-install cert-manager of either 1.6.2 or 1.7.1 version (to allow 1.7.1 upgrade, you need to run `cmctl upgrade migrate-api-version --qps 5 --burst 10` first)
```

Sometimes I had `cert-manager` namespace stuck in Terminating state, to fix that I had to approach it this way:

1. save namespace as json

```
$ kubectl get namespace cert-manager -o json > cert-manager.json
```

2. remove whatever you see in "finalizers"
```
$ vim cert-manager.json
```

before:
```
        "finalizers": [
            "controller.cattle.io/namespace-auth"
        ],
```

after:
```
        "finalizers": [],
```

3. push the change
```
$ kubectl replace --raw "/api/v1/namespaces/cert-manager/finalize" -f ./cert-manager.json 
```

If that won't work because of permission issue, then this should help:
```
$ kubectl proxy
$ curl -k -H "Content-Type: application/json" -X PUT --data-binary @cert-manager.json http(s)://[IP]:[PORT]/api/v1/namespaces/[NAMESPACE]/finalize
```

Another set of issues I had, in the test-lab, were when I upgraded the RKE **before** I would upgrade Rancher UI (via Helm Charts).

**Comment by ghost** [comment]
I am seeing these warnings / errors in Rancher `kubectl -n cattle-system logs rancher-<REDACTED>`, likely due to the experimental rancher v1.22.6 slipping through with the RKE 1.3.7 upgrade :/
They aren't really breaking the usability for me, but they aren't really nice.
Hoping the new Rancher helm chart will address them.

```
W0220 22:25:31.193758      32 warnings.go:80] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0220 22:26:12.926200      32 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

```
2022/02/20 22:28:45 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2022/02/20 22:28:50 [ERROR] error syncing 'local/p-rwfhb': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2022/02/20 22:28:50 [ERROR] error syncing 'local/p-ngzf5': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing
```

**Comment by harridu** [comment]
HI @arno01, I have restored my rancher cluster from a file system backup. (The backup tar files created by the backup operator every hour couldn't be restored. Not important here.) Currently I have
```
% helm list -A
NAME                    NAMESPACE                       REVISION        UPDATED                                 STATUS          CHART                                                                                           APP VERSION
fleet                   cattle-fleet-system             1               2021-12-25 07:23:21.479195424 +0000 UTC deployed        fleet-100.0.2+up0.3.8                                                                           0.3.8      
fleet-agent-local       fleet-system                    3               2021-12-25 07:22:46.267102309 +0000 UTC deployed        fleet-agent-local-v0.0.0+s-91a55acfe99a994f6da0fa635627028cabbec9a9917862308d064057c6ba3                   
fleet-agent-local       cattle-fleet-local-system       526             2022-02-21 08:18:57.83658665 +0000 UTC  deployed        fleet-agent-local-v0.0.0+s-efe11d4d0d1572f8ada5d979371da69d080e475a34bc377690947d2978745                   
fleet-crd               fleet-system                    6               2021-07-03 13:14:23.276501342 +0000 UTC deployed        fleet-crd-0.3.500                                                                               0.3.5      
fleet-crd               cattle-fleet-system             1               2021-12-25 07:23:07.827469624 +0000 UTC deployed        fleet-crd-100.0.2+up0.3.8                                                                       0.3.8      
rancher                 cattle-system                   16              2022-01-30 21:42:47.117170463 +0100 CET deployed        rancher-2.6.3                                                                                   v2.6.3     
rancher-backup          cattle-resources-system         2               2021-11-15 12:46:44.597202692 +0000 UTC deployed        rancher-backup-1.2.0                                                                            1.2.0      
rancher-backup-crd      cattle-resources-system         3               2021-11-15 12:46:40.077785576 +0000 UTC deployed        rancher-backup-crd-1.2.0                                                                        1.2.0      
rancher-logging         cattle-logging-system           1               2021-09-15 11:35:50.32914889 +0000 UTC  deployed        rancher-logging-3.9.400                                                                         3.9.4      
rancher-logging-crd     cattle-logging-system           1               2021-09-15 11:35:42.086065877 +0000 UTC deployed        rancher-logging-crd-3.9.400                                                                                
rancher-webhook         cattle-system                   7               2022-01-30 20:45:46.130609772 +0000 UTC deployed        rancher-webhook-1.0.3+up0.2.4                                                                   0.2.4      

% kubectl get pods -A
NAMESPACE                   NAME                                       READY   STATUS      RESTARTS   AGE
cattle-fleet-local-system   fleet-agent-78f694664b-s7jvb               1/1     Running     3          55d
cattle-fleet-system         fleet-controller-6666887949-lhz98          1/1     Running     3          55d
cattle-fleet-system         gitjob-7b97c9c7fd-zgpzm                    1/1     Running     3          55d
cattle-logging-system       rancher-logging-574575c468-c8lgp           1/1     Running     3          55d
cattle-logging-system       rancher-logging-fluentbit-5z6w6            1/1     Running     8          159d
cattle-logging-system       rancher-logging-fluentbit-jqsmq            1/1     Running     8          159d
cattle-logging-system       rancher-logging-fluentbit-m2xjm            1/1     Running     8          159d
cattle-logging-system       rancher-logging-fluentd-0                  2/2     Running     16         159d
cattle-logging-system       rancher-logging-rke-aggregator-ckmp6       1/1     Running     8          159d
cattle-logging-system       rancher-logging-rke-aggregator-t9jnh       1/1     Running     8          159d
cattle-logging-system       rancher-logging-rke-aggregator-vzd6t       1/1     Running     8          159d
cattle-resources-system     rancher-backup-5c66ccb575-dwtjz            1/1     Running     3          55d
cattle-system               rancher-5cc579c68d-6gqr2                   1/1     Running     1          21d
cattle-system               rancher-5cc579c68d-6qqrb                   1/1     Running     3          21d
cattle-system               rancher-5cc579c68d-7jccr                   1/1     Running     1          21d
cattle-system               rancher-webhook-5444f77b78-8ldsf           1/1     Running     1          21d
ingress-nginx               nginx-ingress-controller-99xf7             1/1     Running     4          78d
ingress-nginx               nginx-ingress-controller-pjl2l             1/1     Running     4          78d
ingress-nginx               nginx-ingress-controller-rns5k             1/1     Running     4          78d
kube-system                 calico-kube-controllers-6c977d77bc-ntnck   1/1     Running     5          78d
kube-system                 canal-fb7vt                                2/2     Running     8          58d
kube-system                 canal-v9jrn                                2/2     Running     8          58d
kube-system                 canal-zrghn                                2/2     Running     8          58d
kube-system                 coredns-685d6d555d-5glgd                   1/1     Running     4          78d
kube-system                 coredns-685d6d555d-rnvwg                   1/1     Running     4          78d
kube-system                 coredns-autoscaler-57fd5c9bd5-9zxl2        1/1     Running     4          78d
kube-system                 metrics-server-7bf4b68b78-sp7r6            1/1     Running     4          78d
kube-system                 rke-coredns-addon-deploy-job-xfhsd         0/1     Completed   0          78d
kube-system                 rke-ingress-controller-deploy-job-4xsrx    0/1     Completed   0          78d
kube-system                 rke-metrics-addon-deploy-job-tjvp8         0/1     Completed   0          78d
kube-system                 rke-network-plugin-deploy-job-scbl2        0/1     Completed   0          58d
```
This is the *old* rke 1.21.7 and rancher v2.6.3-patch1.

I noticed if I setup a full node (etcd, control plane, worker) in the old rancher and upgrade it to 1.22, then it seems to be working. I can not add further worker nodes to it, though. The new node starts the agent container, next kube-proxy and nginx, thats all. It doesn't become a worker node, but it gets stuck somewhere.

**Comment by ghost** [comment]
@harridu I think the best would be to check the logs of those containers you get running, to see some hints.

Comparing your `helm list -A` vs mine, I do not have `rancher-backup-*`, `rancher-logging-*` charts at all.
And you have `rancher-webhook-1.0.3+up0.2.4`, slightly higher than mine (`rancher-webhook-1.0.2+up0.2.2`).

I also have `cert-manager-v1.7.1`.
I am not 100% sure if `cert-manager` is mandatory or not, but I think I've read somewhere that it was. So you can probably try installing it to see if it fixes anything.

**Comment by harridu** [comment]
@arno01 Sorry, but no experiments with the production Rancher environment. This problem is a regression of rke 1.22, see my previous post.

**Comment by Tejeev** [comment]
@harridu as a best practice in the future, please pin the k8s version in your cluster yaml.  RKE version and kubernetes version are not hard linked, and instead, RKE just allows for the running of several versions with the newest tested being set to default. K8s should be upgraded with intent per https://rancher.com/docs/rke/latest/en/upgrades/#upgrading-kubernetes

**Comment by Tejeev** [comment]
(that's not to say I endorse using an experimental version but that to follow k8s best upgrade practices and maintain an environment with optimum uptime, I encourage you to use the best practice of upgrading 1 minor version at a time via pinned k8s version in your cluster yaml.)

**Comment by immanuelfodor** [comment]
FYI, with RKE v1.3.9 and k8s v1.22.7 I experienced the job deletion issue again, so I needed to run some (but not all) commands mentioned in https://github.com/rancher/rke/issues/2833#issuecomment-1037457764 to make the `rke --debug up` command progress from the stucked job states:

```
k delete job rke-network-plugin-deploy-job -n kube-system
k delete job rke-coredns-addon-deploy-job -n kube-system
k delete job rke-user-includes-addons-deploy-job -n kube-system
```

**Comment by immanuelfodor** [comment]
I can also see the "incompatible version" error logs in https://github.com/rancher/rke/issues/2833#issuecomment-1046335489

**Comment by immanuelfodor** [comment]
^ latest Rancher v2.6.4

**Comment by harridu** [comment]
Is anybody actually working on this?

**Comment by wangfeng-1** [comment]
same question
