### ISSUE TITLE
NGINX Ingress Controller options are not applied to the `ingress-nginx-controller` ConfigMap

### ISSUE THREAD

**Issue by oncipriani** [rancher/rke#2834]
**RKE version:** 1.3.7

**cluster.yml file:**
```yaml
ingress:
  provider: nginx
  options:
    ssl-protocols: "TLSv1.2"
```

**Steps to Reproduce:**
1. Create a `cluster.yml` file with Ingress options like above and run `rke up`;
2. ~~Notice the settings are applied to the `nginx-configuration` ConfigMap in the `ingress-nginx` namespace.~~
3. Notice the `ingress-nginx-controller` ConfigMap in the `ingress-nginx` namespace is created empty.

**Results:**
The Ingress Controller ignore those settings, since it expects them to be in the `ingress-nginx-controller` ConfigMap. The `ingress-nginx-controller` ConfigMap exists but it is empty.

**Workaround:**
Add the `configmap` command line parameter to the Ingress Controller pointing to a ConfigMap you control. In the following example I pointed to the `nginx-configuration` ConfigMap that was created by previous RKE versions:
```yaml
ingress:
  provider: nginx
  extra_args:
    configmap: '$(POD_NAMESPACE)/nginx-configuration'
  options:
    ssl-protocols: 'TLSv1.2'
```

**Edit:**
Apparently the settings are not applied at all. The settings in the `nginx-configuration` ConfigMap were applied in our clusters because they were created by previous RKE versions. The `ingress-nginx-controller` ConfigMap is configured, but it is empty.

Here is the output from the `rke-ingress-controller-deploy-job` Job:
```namespace/ingress-nginx unchanged
serviceaccount/ingress-nginx unchanged
configmap/ingress-nginx-controller configured
configmap/tcp-services unchanged
configmap/udp-services unchanged
clusterrole.rbac.authorization.k8s.io/ingress-nginx unchanged
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx unchanged
role.rbac.authorization.k8s.io/ingress-nginx unchanged
rolebinding.rbac.authorization.k8s.io/ingress-nginx unchanged
service/ingress-nginx-controller-admission unchanged
daemonset.apps/nginx-ingress-controller configured
ingressclass.networking.k8s.io/nginx unchanged
validatingwebhookconfiguration.admissionregistration.k8s.io/ingress-nginx-admission configured
serviceaccount/ingress-nginx-admission unchanged
clusterrole.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
role.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
rolebinding.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
job.batch/ingress-nginx-admission-create created
job.batch/ingress-nginx-admission-patch created
```

**Comment by lumachan** [comment]
I can confirm the issue. And thanks for the workaround :)

**Comment by junkiebev** [comment]
Can confirm this is an issue on `rancher/hyperkube:v1.20.15-rancher1`

**Comment by alainandre** [comment]
I confimed the issue on **RKE version:** `v1.3.7`
**k8s versions**: `v1.20.15-rancher1-1` and `v1.21.9-rancher1-1`

@oncipriani thanks for the workaroud. It worked on my cluster upgrading from k8s `v1.20.9-rancher1-1` rke `v1.2.10` to k8s `v1.21.9-rancher1-1` rke `v1.3.7`. As you commented the nginx-configuration ConfigMap  created by a previous RKE was already there.

**Comment by sevenval-admins** [comment]
I can also confirm that in all our clusters we had the problem with the last update that the options from the Ingress controller were not noticed because the new ConfigMap was empty. The workaround only works for existing clusters and if you don't want to change any options.

Therefore, I ask for a quick fix of the bug.

Version rke: v1.3.7
Old version Kubernetes: v1.18.20-rancher1-2
New version Kubernetes: v1.21.9-rancher1-1

**Comment by rchench** [comment]
My workaround is just to manually update the configmap/ingress-nginx-controller after `rke up`, the daemonset/nginx-ingress-controller pod will be reloaded.

**Comment by svenluzar** [comment]
Thanks, the workaround also works for me. After `rke up` I used the following lines to fix the problem:

```
kubectl get configmap -n ingress-nginx nginx-configuration -o json --show-managed-fields=false > backup-nginx-configuration-cm.json
kubectl get configmap -n ingress-nginx ingress-nginx-controller -o json --show-managed-fields=false > backup-ingress-nginx-controller-cm.json
jq -s '.[0] * .[1]' backup-nginx-configuration-cm.json backup-ingress-nginx-controller-cm.json > new-ingress-nginx-controller-cm.json 
kubectl apply -f new-ingress-nginx-controller-cm.json
```

But it is only a workaround, the problem should be fixed directly in rke. ;-)

**Comment by svenluzar** [comment]
Thank you very much, with rke version 1.3.8 the problem was fixed.

**Comment by lopf** [comment]
Are we sure? We just hit this bug with Rancher v2.6.4 which, according to the release notes, uses RKE v1.3.8.
