### ISSUE TITLE
rke crashes if rotate_encryption_key is set when creating a new cluster

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke#2840]
**RKE version:**
v1.3.7
**Docker version: (`docker version`,`docker info` preferred)**
n/a
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
n/a
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
n/a
**cluster.yml file:**
```
nodes:
  - address:  xxx
    internal_address: xxx
    user: ubuntu
    role: [controlplane,worker,etcd]
    ssh_key_path: xxx
rotate_encryption_key: true
```

**Steps to Reproduce:**
run `rke up`

**Results:**

RKE crashes with the following error
```
INFO[0016] Rotating cluster secrets encryption key
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2780c9e]

goroutine 1 [running]:
github.com/rancher/rke/cluster.InitClusterObject(0x300a758, 0xc0000440a0, 0x0, 0x0, 0x0, 0x7ff7bfeffa52, 0x15, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rke/cluster/cluster.go:705 +0xde
github.com/rancher/rke/cmd.RotateEncryptionKey(0x300a758, 0xc0000440a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ff7bfeffa52, 0x15, ...)
	/go/src/github.com/rancher/rke/cmd/encryption.go:85 +0x185
github.com/rancher/rke/cmd.ClusterUp(0x300a758, 0xc0000440a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ff7bfeffa52, 0x15, 0x0, ...)
	/go/src/github.com/rancher/rke/cmd/up.go:107 +0x35b
github.com/rancher/rke/cmd.clusterUpFromCli(0xc00015de40, 0x0, 0xc00015de40)
	/go/src/github.com/rancher/rke/cmd/up.go:309 +0x645
github.com/urfave/cli.HandleAction(0x29493e0, 0x2d8e618, 0xc00015de40, 0xc00047d300, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0x82
github.com/urfave/cli.Command.Run(0x2c9cb4a, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2cb5639, 0x14, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x9bb
github.com/urfave/cli.(*App).Run(0xc0001ee1a0, 0xc00003a080, 0x4, 0x4, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x768
main.mainErr(0xc0003f9e30, 0x2fcc8a0)
	/go/src/github.com/rancher/rke/main.go:81 +0x17ce
main.main()
	/go/src/github.com/rancher/rke/main.go:25 +0x4e
```

Related issue: https://github.com/rancher/rancher/issues/36333

**Comment by jiaqiluo** [comment]
### Root cause
  RKE will panic if we enable rotate_encryption_key but disable secrets_encryption_config when creating a cluster. The panic happens because RKE tries to use the rkeConfig, which does not exist. The rkeConfig will be made after the rke up command succeeds.
### What was fixed, or what changes have occurred
  Skip the rotateEncryptionKey operation when creating a new cluster. Also, In this case, keys are just made for the first time, so there is no need to rotate them.

### Areas or cases that should be tested
Test 1:
  run `rke up` with the following cluster.yml
```
nodes:
  - address:  xxx
    internal_address: xxx
    user: ubuntu
    role: [controlplane,worker,etcd]
    ssh_key_path: xxx
rotate_encryption_key: true
```
Test 2:

- provision an RKE cluster with secrets Encryption disabled, which is the default behavior
- wait for the cluster to be available
- edit the cluster.yaml to enable rotateEncryptionKey and secretsEncryptionConfig
- run `rke up` again  

### What areas could experience regressions?
none
### Are the repro steps accurate/minimal?
yes

**Comment by jiaqiluo** [comment]
can be tested in [v1.3.8-rc4](https://github.com/rancher/rke/releases/tag/v1.3.8-rc4)

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
**rke version**: 1.3.8-rc4

----------

### Testing: ###

Tested this issue with the following steps:
1. run rke up with the following field added in cluster.yml
`rotate_encryption_key: true`

**Result** - Pass

The cluster is built successfully

![Screen Shot 2022-03-17 at 3.28.20 PM.png](https://zube.io/files/rancher/4308020a3c108ba02dd5e7cecac5b680-screen-shot-2022-03-17-at-3-28-20-pm.png)
