### ISSUE TITLE
Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config

### ISSUE THREAD

**Issue by n30gupta** [rancher/rke#2849]
Hi

I am trying to setup a 1 node cluster but getting error below of etcd.

root@ubuntu:~/rke# rke config --name cluster.yml
[+] Cluster Level SSH Private Key Path [~/.ssh/id_rsa]:
[+] Number of Hosts [1]: 1
[+] SSH Address of host (1) [none]: 192.168.27.148
[+] SSH Port of host (1) [22]:
[+] SSH Private Key Path of host (192.168.27.148) [none]:
[-] You have entered empty SSH key path, trying fetch from SSH key parameter
[+] SSH Private Key of host (192.168.27.148) [none]:
[-] You have entered empty SSH key, defaulting to cluster level SSH key: ~/.ssh/id_rsa
[+] SSH User of host (192.168.27.148) [ubuntu]:
[+] Is host (192.168.27.148) a Control Plane host (y/n)? [y]: y
[+] Is host (192.168.27.148) a Worker host (y/n)? [n]: y
[+] Is host (192.168.27.148) an etcd host (y/n)? [n]: y
[+] Override Hostname of host (192.168.27.148) [none]:
[+] Internal IP of host (192.168.27.148) [none]:
[+] Docker socket path on host (192.168.27.148) [/var/run/docker.sock]:
[+] Network Plugin Type (flannel, calico, weave, canal, aci) [canal]:
[+] Authentication Strategy [x509]:
[+] Authorization Mode (rbac, none) [rbac]:
[+] Kubernetes Docker image [rancher/hyperkube:v1.22.6-rancher1]:
[+] Cluster domain [cluster.local]:
[+] Service Cluster IP Range [10.43.0.0/16]:
[+] Enable PodSecurityPolicy [n]:
[+] Cluster Network CIDR [10.42.0.0/16]:
[+] Cluster DNS Service IP [10.43.0.10]:
[+] Add addon manifest URLs or YAML files [no]:

root@ubuntu:~/rke# rke up
INFO[0000] Running RKE version: v1.3.7
INFO[0000] Initiating Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [192.168.27.148]
WARN[0000] Failed to set up SSH tunneling for host [192.168.27.148]: Can't retrieve Docker Info: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": Unable to access node with address [192.168.27.148:22] using SSH. Please check if you are able to SSH to the node using the specified SSH Private Key and if you have configured the correct SSH username. Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
WARN[0000] Removing host [192.168.27.148] from node lists
WARN[0000] [state] can't fetch legacy cluster state from Kubernetes: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [192.168.27.148]
INFO[0000] [certificates] Generating CA kubernetes certificates
INFO[0000] [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
INFO[0000] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
INFO[0000] [certificates] Generating Kubernetes API server certificates
INFO[0001] [certificates] Generating Service account token key
INFO[0001] [certificates] Generating Kube Controller certificates
INFO[0001] [certificates] Generating Kube Scheduler certificates
INFO[0001] [certificates] Generating Kube Proxy certificates
INFO[0002] [certificates] Generating Node certificate
INFO[0002] [certificates] Generating admin certificates and kubeconfig
INFO[0002] [certificates] Generating Kubernetes API server proxy client certificates
INFO[0002] Successfully Deployed state file at [./cluster.rkestate]
INFO[0002] Building Kubernetes cluster
FATA[0002] Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config
root@ubuntu:~/rke#

Please suggest me the way how to resolve this error.

**Comment by Aramorth** [comment]
https://github.com/rancher/rke/issues/2848I' m not quite as far as where does the error occu

**Comment by n30gupta** [comment]
@Aramorth The link you have shared it is of different issue I think 
could you please suggest me any idea to resolve this error.

**Comment by Khanh-197** [comment]
Check permission in docker for user remote throught ssh , sudo usermod -aG docker $USER
