### ISSUE TITLE
Upgrade k8s 1.21.5 to 1.21.9 not finalized after rke1.3.7 up

### ISSUE THREAD

**Issue by andreas-p** [rancher/rke#2857]
I have a cluster on Debian Buster with Docker 20.10.8, running v1.21.5-rancher1 installed with rke 1.3.1. In addition, system_images contained canal_flannel: rancher/mirrored-coreos-flannel:v0.15.0.

The system_images override was removed, kubernetes_version: "v1.21.9-rancher1-1" and I tried to update k8s with rke1.3.6 and then rke1.3.7. As a result, coreos-flannel is running v0.15.1 now, but the k8s version is still at 1.21.15. 

Checking with docker images, I see the new hyperkube  v1.21.9-rancher, and cluster.rkestate has v1.21.9 as well, but the kube* containers are still running 1.21.5.
I patched cluster.rkestate to indicate 1.21.5 instead of 1.21.9 present and repeated rke up. cluster.rkestate went up to 1.21.9, but no effect on the containers.

What can I do to make RKE actually upgrade the k8s containers?

**Comment by luis13byte** [comment]
It would be nice to see the logs of your `rke up` command, to better help you with your problem.

**Comment by andreas-p** [comment]
Ok, found it...
I actually didn't run `rke up`, but `rke up --update-only` which should `Skip idempotent deployment of control and etcd plane` according to help. I wouldn't consider 1.21.5 to 1.21.9 idempotent, but apparently rke does.
After running without update-only, control plane is up with expected versions.

**Comment by luis13byte** [comment]
I believe that even if it were major versions, the `--update-only` parameter only applies node configurations and little else, as indicated in the [documentation](https://rancher.com/docs/rke/latest/en/managing-clusters/#adding-removing-worker-nodes).

You can mark this problem as closed.

**Comment by andreas-p** [comment]
Apparently the documentation is misleading as well: `--update-only` did apply new canal pods.
