### ISSUE TITLE
RKE RHEL-7.4 with weave: "Failed to deploy addon execute job: Failed to get job complete status"

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rke#286]
**RKE version:**
v0.1.0
**Docker version: (`docker version`,`docker info` preferred)**
native docker version for RHEL (1.12.6)
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
3.10.0-693.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**cluster.yml file:**
ignore_docker_version: true
ssh_key_path: {{ master_ssh_key_path }}
network:
plugin: canal
nodes:

address: {{ ip_address_0 }}
user: ubuntu
role: [controlplane]
address: {{ ip_address_1 }}
user: ubuntu
role: [etcd]
address: {{ ip_address_2 }}
user: ubuntu
role: [worker]
services:
etcd:
image: quay.io/coreos/etcd:latest
kube-api:
image: rancher/k8s:v1.8.3-rancher2
kube-controller:
image: rancher/k8s:v1.8.3-rancher2
scheduler:
image: rancher/k8s:v1.8.3-rancher2
kubelet:
image: rancher/k8s:v1.8.3-rancher2
kubeproxy:
image: rancher/k8s:v1.8.3-rancher2

Note there is no addons in the yaml

**Steps to Reproduce:**
once the three nodes are provision on AWS with key pair
rke up

**Results:**
time="2018-01-29T23:56:25Z" level=info msg="Building Kubernetes cluster"
time="2018-01-29T23:56:25Z" level=info msg="[dialer] Setup tunnel for host [18.218.246.149]"
time="2018-01-29T23:56:26Z" level=info msg="[network] Deploying port listener containers"
time="2018-01-29T23:56:27Z" level=info msg="[network] Successfully pulled image [alpine:latest] on host [18.218.246.149]"
time="2018-01-29T23:56:29Z" level=info msg="[network] Successfully started [rke-etcd-port-listener] container on host [18.218.246.149]"
time="2018-01-29T23:56:29Z" level=info msg="[network] Successfully started [rke-cp-port-listener] container on host [18.218.246.149]"
time="2018-01-29T23:56:30Z" level=info msg="[network] Successfully started [rke-worker-port-listener] container on host [18.218.246.149]"
time="2018-01-29T23:56:30Z" level=info msg="[network] Port listener containers deployed successfully"
time="2018-01-29T23:56:30Z" level=info msg="[network] Running all -> etcd port checks"
time="2018-01-29T23:56:31Z" level=info msg="[network] Successfully started [rke-port-checker] container on host [18.218.246.149]"
time="2018-01-29T23:56:33Z" level=info msg="[network] Successfully started [rke-port-checker] container on host [18.218.246.149]"
time="2018-01-29T23:56:33Z" level=info msg="[network] Running control plane -> etcd port checks"
time="2018-01-29T23:56:34Z" level=info msg="[network] Successfully started [rke-port-checker] container on host [18.218.246.149]"
time="2018-01-29T23:56:34Z" level=info msg="[network] Running workers -> control plane port checks"
time="2018-01-29T23:56:35Z" level=info msg="[network] Successfully started [rke-port-checker] container on host [18.218.246.149]"
time="2018-01-29T23:56:35Z" level=info msg="[network] Checking KubeAPI port Control Plane hosts"
time="2018-01-29T23:56:35Z" level=info msg="[network] Removing port listener containers"
time="2018-01-29T23:56:36Z" level=info msg="[remove/rke-etcd-port-listener] Successfully removed container on host [18.218.246.149]"
time="2018-01-29T23:56:36Z" level=info msg="[remove/rke-cp-port-listener] Successfully removed container on host [18.218.246.149]"
time="2018-01-29T23:56:36Z" level=info msg="[remove/rke-worker-port-listener] Successfully removed container on host [18.218.246.149]"
time="2018-01-29T23:56:36Z" level=info msg="[network] Port listener containers removed successfully"
time="2018-01-29T23:56:36Z" level=info msg="[certificates] Attempting to recover certificates from backup on host [18.218.246.149]"
time="2018-01-29T23:56:37Z" level=info msg="[certificates] Successfully started [cert-fetcher] container on host [18.218.246.149]"
time="2018-01-29T23:56:37Z" level=info msg="[certificates] No Certificate backup found on host [18.218.246.149]"
time="2018-01-29T23:56:37Z" level=info msg="[certificates] Generating kubernetes certificates"
time="2018-01-29T23:56:37Z" level=info msg="[certificates] Generating CA kubernetes certificates"
time="2018-01-29T23:56:37Z" level=info msg="[certificates] Generating Kubernetes API server certificates"
time="2018-01-29T23:56:38Z" level=info msg="[certificates] Generating Kube Controller certificates"
time="2018-01-29T23:56:38Z" level=info msg="[certificates] Generating Kube Scheduler certificates"
time="2018-01-29T23:56:38Z" level=info msg="[certificates] Generating Kube Proxy certificates"
time="2018-01-29T23:56:38Z" level=info msg="[certificates] Generating Node certificate"
time="2018-01-29T23:56:39Z" level=info msg="[certificates] Generating admin certificates and kubeconfig"
time="2018-01-29T23:56:39Z" level=info msg="[certificates] Temporarily saving certs to etcd host [18.218.246.149]"
time="2018-01-29T23:56:41Z" level=info msg="[certificates] Successfully pulled image [rancher/rke-cert-deployer:v0.1.1] on host [18.218.246.149]"
time="2018-01-29T23:56:47Z" level=info msg="[certificates] Saved certs to etcd host [18.218.246.149]"
time="2018-01-29T23:56:47Z" level=info msg="[reconcile] Reconciling cluster state"
time="2018-01-29T23:56:47Z" level=info msg="[reconcile] This is newly generated cluster"
time="2018-01-29T23:56:47Z" level=info msg="[certificates] Deploying kubernetes certificates to Cluster nodes"
time="2018-01-29T23:56:55Z" level=info msg="Successfully Deployed local admin kubeconfig at [./.kube_config_cluster.yml]"
time="2018-01-29T23:56:55Z" level=info msg="[certificates] Successfully deployed kubernetes certificates to Cluster nodes"
time="2018-01-29T23:56:55Z" level=info msg="[etcd] Building up Etcd Plane.."
time="2018-01-29T23:56:58Z" level=info msg="[etcd] Successfully pulled image [quay.io/coreos/etcd:latest] on host [18.218.246.149]"
time="2018-01-29T23:56:58Z" level=info msg="[etcd] Successfully started [etcd] container on host [18.218.246.149]"
time="2018-01-29T23:56:58Z" level=info msg="[etcd] Successfully started Etcd Plane.."
time="2018-01-29T23:56:58Z" level=info msg="[controlplane] Building up Controller Plane.."
time="2018-01-29T23:56:59Z" level=info msg="[sidekick] Successfully pulled image [rancher/rke-service-sidekick:v0.1.0] on host [18.218.246.149]"
time="2018-01-29T23:58:02Z" level=info msg="[controlplane] Successfully pulled image [rancher/k8s:v1.8.3-rancher2] on host [18.218.246.149]"
time="2018-01-29T23:58:03Z" level=info msg="[controlplane] Successfully started [kube-api] container on host [18.218.246.149]"
time="2018-01-29T23:58:03Z" level=info msg="[healthcheck] Start Healthcheck on service [kube-api] on host [18.218.246.149]"
time="2018-01-29T23:58:11Z" level=info msg="[healthcheck] service [kube-api] on host [18.218.246.149] is healthy"
time="2018-01-29T23:58:12Z" level=info msg="[controlplane] Successfully started [kube-controller] container on host [18.218.246.149]"
time="2018-01-29T23:58:12Z" level=info msg="[healthcheck] Start Healthcheck on service [kube-controller] on host [18.218.246.149]"
time="2018-01-29T23:58:13Z" level=info msg="[healthcheck] service [kube-controller] on host [18.218.246.149] is healthy"
time="2018-01-29T23:58:14Z" level=info msg="[controlplane] Successfully started [scheduler] container on host [18.218.246.149]"
time="2018-01-29T23:58:14Z" level=info msg="[healthcheck] Start Healthcheck on service [scheduler] on host [18.218.246.149]"
time="2018-01-29T23:58:15Z" level=info msg="[healthcheck] service [scheduler] on host [18.218.246.149] is healthy"
time="2018-01-29T23:58:15Z" level=info msg="[controlplane] Successfully started Controller Plane.."
time="2018-01-29T23:58:15Z" level=info msg="[authz] Creating rke-job-deployer ServiceAccount"
time="2018-01-29T23:58:15Z" level=info msg="[authz] rke-job-deployer ServiceAccount created successfully"
time="2018-01-29T23:58:15Z" level=info msg="[authz] Creating system:node ClusterRoleBinding"
time="2018-01-29T23:58:15Z" level=info msg="[authz] system:node ClusterRoleBinding created successfully"
time="2018-01-29T23:58:15Z" level=info msg="[certificates] Save kubernetes certificates as secrets"
time="2018-01-29T23:58:34Z" level=info msg="[certificates] Successfully saved certificates as kubernetes secret [k8s-certs]"
time="2018-01-29T23:58:34Z" level=info msg="[state] Saving cluster state to Kubernetes"
time="2018-01-29T23:58:34Z" level=info msg="[state] Successfully Saved cluster state to Kubernetes ConfigMap: cluster-state"
time="2018-01-29T23:58:34Z" level=info msg="[worker] Building up Worker Plane.."
time="2018-01-29T23:58:34Z" level=info msg="[worker] Host [18.218.246.149] is already worker host, skipping deploying unschedulable kubelet"
time="2018-01-29T23:58:34Z" level=info msg="[sidekick] Sidekick container already created on host [18.218.246.149]"
time="2018-01-29T23:58:34Z" level=info msg="[worker] Successfully started [kubelet] container on host [18.218.246.149]"
time="2018-01-29T23:58:34Z" level=info msg="[healthcheck] Start Healthcheck on service [kubelet] on host [18.218.246.149]"
time="2018-01-29T23:58:42Z" level=info msg="[healthcheck] service [kubelet] on host [18.218.246.149] is healthy"
time="2018-01-29T23:58:43Z" level=info msg="[worker] Successfully started [kube-proxy] container on host [18.218.246.149]"
time="2018-01-29T23:58:43Z" level=info msg="[healthcheck] Start Healthcheck on service [kube-proxy] on host [18.218.246.149]"
time="2018-01-29T23:58:44Z" level=info msg="[healthcheck] service [kube-proxy] on host [18.218.246.149] is healthy"
time="2018-01-29T23:58:44Z" level=info msg="[sidekick] Sidekick container already created on host [18.218.246.149]"
time="2018-01-29T23:58:44Z" level=info msg="[healthcheck] Start Healthcheck on service [kubelet] on host [18.218.246.149]"
time="2018-01-29T23:58:45Z" level=info msg="[healthcheck] service [kubelet] on host [18.218.246.149] is healthy"
time="2018-01-29T23:58:45Z" level=info msg="[healthcheck] Start Healthcheck on service [kube-proxy] on host [18.218.246.149]"
time="2018-01-29T23:58:46Z" level=info msg="[healthcheck] service [kube-proxy] on host [18.218.246.149] is healthy"
time="2018-01-29T23:58:46Z" level=info msg="[worker] Successfully started Worker Plane.."
time="2018-01-29T23:58:46Z" level=info msg="[network] Setting up network plugin: weave"
time="2018-01-29T23:58:46Z" level=info msg="[addons] Saving addon ConfigMap to Kubernetes"
time="2018-01-29T23:58:46Z" level=info msg="[addons] Successfully Saved addon to Kubernetes ConfigMap: rke-network-plugin"
time="2018-01-29T23:58:46Z" level=info msg="[addons] Executing deploy job.."
Running command: rke up 
Failed to get job complete status: <nil>
time="2018-01-29T23:59:17Z" level=fatal msg="Failed to deploy addon execute job: Failed to get job complete status: <nil>"

**Comment by sabiodelhielo** [comment]
[root@ip-172-31-14-91 ~]# docker logs e6b9bd9c309a
DEBU: 2018/01/30 20:35:35.284395 [kube-peers] Checking peer "42:42:78:d5:fb:19" against list &{[{42:42:78:d5:fb:19 18.218.223.142}]}
INFO: 2018/01/30 20:35:37.796297 Command line options: map[ipalloc-range:10.233.64.0/18 name:42:42:78:d5:fb:19 host-root:/host http-addr:127.0.0.1:6784 ipalloc-init:consensus=1 db-prefix:/weavedb/weave-net expect-npc:true no-dns:true port:6783 conn-limit:30 docker-api: nickname:18.218.223.142 datapath:datapath status-addr:0.0.0.0:6782]
INFO: 2018/01/30 20:35:37.990400 weave  2.1.2
INFO: 2018/01/30 20:35:37.990585 Bridge type is bridged_fastdp
INFO: 2018/01/30 20:35:37.990594 Communication between peers is unencrypted.
INFO: 2018/01/30 20:35:38.026082 Our name is 42:42:78:d5:fb:19(18.218.223.142)
INFO: 2018/01/30 20:35:38.026118 Launch detected - using supplied peer list: [18.218.223.142]
INFO: 2018/01/30 20:35:38.026137 Checking for pre-existing addresses on weave bridge
INFO: 2018/01/30 20:35:38.026293 weave bridge has address 10.233.64.1/18
INFO: 2018/01/30 20:35:38.076870 [allocator 42:42:78:d5:fb:19] Initialising with persisted data
INFO: 2018/01/30 20:35:38.076919 Sniffing traffic on datapath (via ODP)
INFO: 2018/01/30 20:35:38.086296 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2018/01/30 20:35:38.086571 Listening for metrics requests on 0.0.0.0:6782
INFO: 2018/01/30 20:35:38.236381 ->[18.218.223.142:6783] attempting connection
INFO: 2018/01/30 20:35:38.237345 ->[18.218.223.142:40313] connection accepted
INFO: 2018/01/30 20:35:38.238577 ->[18.218.223.142:40313|42:42:78:d5:fb:19(18.218.223.142)]: connection shutting down due to error: cannot connect to ourself
INFO: 2018/01/30 20:35:38.238758 ->[18.218.223.142:6783|42:42:78:d5:fb:19(18.218.223.142)]: connection shutting down due to error: cannot connect to ourself
INFO: 2018/01/30 20:35:41.100927 Weave version 2.2.0 is available; please update at https://github.com/weaveworks/weave/releases/download/v2.2.0/weave
FATA: 2018/01/30 20:35:53.272290 [kube-peers] Could not get peers: Get https://10.233.0.1:443/api/v1/nodes: net/http: TLS handshake timeout
INFO: 2018/01/30 20:35:59.048290 Discovered local MAC 42:42:78:d5:fb:19
10.233.64.1

**Comment by HighwayofLife** [comment]
This is related to issues: #303, #342, #329, #318

**Comment by adingilloRancher** [comment]
Version v0.1.8-rc1

Able to successfully provision cluster with weave
