### ISSUE TITLE
Change from CNI initially specified in cluster.yml. Migrate from Weave to Calico.

### ISSUE THREAD

**Issue by luis13byte** [rancher/rke#2860]
**RKE version:** 
v1.3.4

**Type/provider of hosts:**
Bare Metal

### Problem:
I hope someone can help me with this problem, I've a Kubernetes cluster (v1.22), initially deployed with RKE's cluster.yml.

My intention was to change the CNI, since I currently use Weave, which is the one I configured in cluster.yml when I created the cluster and now I would like to migrate to Calico, according to [the official documentation](https://rancher.com/docs/rke/latest/en/config-options/add-ons/network-plugins/) I understand that I cannot do this, I would need to create a new cluster from scratch. In fact, I've tried to modify the cluster.yml and apply this:

~~~
network:
  plugin: calico
~~~

This, however, has only deployed the Calico pods without removing the Weave pods from the cluster. Therefore it didn't go as expected and I reverted these changes.

### Alternative proposed:
I understand that there is a tool for RKE to RKE2 migration, the documentation here is minimalistic. https://docs.rke2.io/migration/

#### My question is: 
**would it be possible to take advantage of this migration process to finally switch the CNI?**

I've enough nodes and workload, Im interested in a fast and progressive upgrade method, instead of creating a new cluster, with a different CNI.

**Comment by cocampbe** [comment]
Maybe it's just me. But the docs clearly state you cannot change the CNI after the fact. I feel your only option is to deploy a new cluster and redeploy there. I know it's not likely what you want to hear, but I think it's the only option.
