### ISSUE TITLE
PodSelector for NodeDrainInput

### ISSUE THREAD

**Issue by jehof** [rancher/rke#2867]
I am using rke to provision kubernetes cluster. As storage engine I use longhorn on each worker node. According to longhorn it is required/preferred to pass a podSelector (`--pod-selector='app!=csi-attacher,app!=csi-provisioner'`) to the kubectl drain command, so that longhorn volumes are properly detached.

Is it somehow possible to pass this `podSelector` to the `rke up` ( as `NodeDrainInput` or other parameter) command, so that nodes properly drained.

**RKE version:**
- 1.2.16

**Kubernetes version:**
- 1.20.14

**Docker version: (`docker version`,`docker info` preferred)**
- 20.10.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
- 5.13.0-1017-azure

**Comment by volford-bence** [comment]
Hi, I have the same issue. We are transforming our infrastructure from rancher1.6 to kubernetes/rke, and we want to use longhorn. I did an rke update (only for test purposes at the moment), but during the update the longhorn engine had some problem, and even got some corrupted volume unfortunately. I read that it is recommended to drain the nodes except the daemonset and use this podselector (based on the documentation: https://longhorn.io/docs/1.2.2/volumes-and-nodes/maintenance/#updating-the-node-os-or-container-runtime), but unfortunately this is not possible to set in the cluster.yml.
As I look into the code, this drainhelper is used from kubernetes package:
https://pkg.go.dev/k8s.io/kubectl/pkg/drain#Helper
This supports the PodSelector input, and as I see, this is called at this function:
https://github.com/rancher/rke/blob/54dc689ac040076881a5b4af50326d5d15efb2c6/services/node_util.go#L51
Is it possible just to add this PodSelector to the cluster.yml as upgrade_strategy.node_drain_input.pod_selector?
