### ISSUE TITLE
External Etcd

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#288]
RKE should be able to create cluster and attach it to already created external etcd cluster, user will pass the following config to rke:

- etcd connection string
- etcd ca cert
- etcd tls cert
- etcd path

**Comment by moelsayed** [comment]
@galal-hussein I am unable to get this working. I get the following error:
```
INFO[0048] [controlplane] Building up Controller Plane.. 
INFO[0050] [controlplane] Successfully started [kube-apiserver] container on host [34.210.70.181] 
INFO[0050] [healthcheck] Start Healthcheck on service [kube-apiserver] on host [34.210.70.181] 
FATA[0163] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: service [kube-apiserver] is not healthy response code: [403], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:anonymous\" cannot get path \"/healthz\"","reason":"Forbidden","details":{},"code":403}
 
```

**Comment by galal-hussein** [comment]
@moelsayed i am unable to reproduce the problem with latest rke, my steps are:

1- generate a self signed certificate:
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout etcd.key -out etcd.crt
```
2- Add common name `etcd.rancher.com`
3- start etcd with client auth and https:
```
ocker run -d -v /root:/tmp -p 2379:2379 quay.io/coreos/etcd:v3.0.17  etcd --name infra0 --data-dir infra0 --client-cert-auth --trusted-ca-file=/tmp/etcd.crt --cert-file=/tmp/etcd.crt --key-file=/tmp/etcd.key --advertise-client-urls https://127.0.0.1:2379 --listen-client-urls https://0.0.0.0:2379
```
4- add `etcd.rancher.com` on the /etc/hosts of all other nodes that kube-api will be deployed on (alternative can be using IP SAN or valid fqdn for etcd)

5- start rke with this config:
```
---
nodes:
  - address: REDACTED
    user: ubuntu
    role:
    - controlplane
    - worker
  - address: REDACTED
    user: ubuntu
    role:
    - controlplane
    - worker

services:
  etcd:
    # if external etcd is used
    path: /etcdcluster
    external_urls:
      - https://etcd.rancher.com:2379
    ca_cert: |-
      -----BEGIN CERTIFICATE-----
      xxxx
      -----END CERTIFICATE-----
    cert: |-
      -----BEGIN CERTIFICATE-----
      xxxx
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN PRIVATE KEY-----
     xxxxx
      -----END PRIVATE KEY-----
```

Results:

I can see rke started and finished building kubernetes correctly with etcd:
```
....
INFO[0052] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-kubedns-addon 
INFO[0052] [addons] Executing deploy job..              
INFO[0058] [addons] KubeDNS deployed successfully..     
INFO[0058] [ingress] Setting up nginx ingress controller 
INFO[0058] [addons] Saving addon ConfigMap to Kubernetes 
INFO[0058] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-ingress-controller 
INFO[0058] [addons] Executing deploy job..              
INFO[0063] [ingress] ingress controller nginx is successfully deployed 
INFO[0063] [addons] Setting up user addons              
INFO[0063] [addons] no user addons defined              
INFO[0063] Finished building Kubernetes cluster successfully
```

**Comment by galal-hussein** [comment]
@soumyalj can you share your cluster.yml file and your setup details

**Comment by galal-hussein** [comment]
after debugging with @soumyalj it turned out that the above error was because the wrong format was used in the cluster.yml, after using the right certificate external etcd worked okay, reassigning the issue to soumya for further testing

**Comment by soumyalj** [comment]
Created a cluster with external etcd using the steps above. 
./rke up --config cluster.yml

Few points  to remember: 
1. If self signed certs are used, ca_cert should be same as the cert
2. For every new cluster created, we need to ensure that old Kubernetes data stored in etcd is cleaned up by:
    a. use different etcd path prefix in the cluster yml
    b. Create fresh data.
3. Create pods in the cluster using the config generated by rke up command
