### ISSUE TITLE
RKE fails to ssh connect on Ubuntu Jammy (22.04 LTS preview)

### ISSUE THREAD

**Issue by sixtus** [rancher/rke#2881]
I just gave up on trying to make RKE work with Ubuntu Jammy. The initial ssh handshake fails. My installation is scripted, so I rerun the same with Ubuntu Focal and it works just fine.

Didn't find anything obvious, that may cause this, likely it's an ssh config change in Ubuntu.

**Comment by FelicianoTech** [comment]
I don't use RKE but I'm having this same issue bringing up a machine on GCE. Definitely something changes in Ubuntu Jammy that broke this process. I did a build at the beginning of February and it was fine so for me, it's a change within the last 40 days or so.

**Comment by FelicianoTech** [comment]
In case it helps...

Ubuntu 22.04 has updated OpenSSH from v8.2 (in 20.04) to v8.9. In v8.8, RSA pubkey support was removed for servers and RSA signatures were removed from clients. This causes some SSH clients to be unable to connect to an Ubuntu 22.04 machine.

**Comment by sixtus** [comment]
The problem went away, when I switched the client to a non-rsa key, I used ssh-ed25519 instead.

**Comment by sharky98** [comment]
I can confirm this issue. Almost all help out there says to try to connect manually with the same private key using `ssh -i {pathToPrivateKey} user@host`. However, it does work without issues when doing so. However, when using `rke up` it doesn't work.

**Comment by infroger** [comment]
I had the same symptom as @sharky98 . The solution was:

https://unix.stackexchange.com/a/725731/65230

Add this line in /etc/ssh/sshd_config.

PubkeyAcceptedAlgorithms +ssh-rsa

And restart sshd.
