### ISSUE TITLE
Unable to add Fedora CoreOS node to RKE cluster

### ISSUE THREAD

**Issue by admun** [rancher/rke#2893]
**RKE version:**

RKE cluster created and managed by rancher v2.6.2

**Docker version: (`docker version`,`docker info` preferred)**

[core@fcos-1 ~]$ sudo docker version
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        485636f
 Built:             Wed Jan 12 03:29:50 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       e2f740d
  Built:            Tue Jan 11 00:00:00 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.0
  GitCommit:        
 runc:
  Version:          1.1.0
  GitCommit:        9ac869a-dirty
 docker-init:
  Version:          0.19.0
  GitCommit:        
[core@fcos-1 ~]$ sudo docker info   
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 132
  Running: 18
  Paused: 0
  Stopped: 114
 Images: 10
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 
 runc version: 9ac869a-dirty
 init version: 
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.16.13-200.fc35.x86_64
 Operating System: Fedora CoreOS 35.20220227.3.0
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.753GiB
 Name: fcos-1.kkhome.net
 ID: G5DU:A2WS:SLSN:6UDS:C3CE:XPT5:DHDM:BVFC:Y3EX:UWEF:IYU6:ALGB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Fedora CoreOS 35

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

libvirtd+qemu/kvm

**cluster.yml file:**

apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQzU7DMBCEXwXtOSn9oaG1xIkDB668wMYet6bOOrI34VD13VECEpUQP7ddaWb0zZypg7JjZTJnYpGkrCFJmd7UvsJqgS5ySAvLqhGLkG6DI0N9TmMoIUmQQ23jUBS5thmsoOpHa3oT5PownshQx8IHdBC9Eoyb6uY5iHt4/Ij8M0u4AxmydVmr9/+Sl57t5KFLRTNxSPISOhTlricjQ4wVRW4Rf53hyOVIhvy9a5vVsl23G17BbZebdWN37q7ZobFs/bbd7fd+O60yb+aQv0LIUD5hAvnW45rUR0BrB89D1Eldelgy5+lS1uGTsyCPcE8Q5LkUmeXl8h4AAP//De0ImuMBAAA
    objectset.rio.cattle.io/id: provisioning-cluster-create
    objectset.rio.cattle.io/owner-gvk: management.cattle.io/v3, Kind=Cluster
    objectset.rio.cattle.io/owner-name: c-s2tff
    objectset.rio.cattle.io/owner-namespace: ""
  creationTimestamp: "2022-01-19T22:59:07Z"
  finalizers:
  - wrangler.cattle.io/provisioning-cluster-remove
  generation: 1
  labels:
    objectset.rio.cattle.io/hash: f7db610b2b3a1ed50326c8d468e6cacf5b899f5e
    provider.cattle.io: rke
  managedFields:
  - apiVersion: provisioning.cattle.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:objectset.rio.cattle.io/applied: {}
          f:objectset.rio.cattle.io/id: {}
          f:objectset.rio.cattle.io/owner-gvk: {}
          f:objectset.rio.cattle.io/owner-name: {}
          f:objectset.rio.cattle.io/owner-namespace: {}
        f:finalizers:
          .: {}
          v:"wrangler.cattle.io/provisioning-cluster-remove": {}
        f:labels:
          .: {}
          f:objectset.rio.cattle.io/hash: {}
          f:provider.cattle.io: {}
      f:spec: {}
      f:status:
        .: {}
        f:clientSecretName: {}
        f:clusterName: {}
        f:conditions: {}
        f:observedGeneration: {}
        f:ready: {}
    manager: rancher
    operation: Update
    time: "2022-01-19T23:02:30Z"
  name: c-s2tff
  namespace: fleet-default
  resourceVersion: "19594845"
  uid: 48c84e9a-7406-4823-a8c0-40e80028c551
spec: {}
status:
  clientSecretName: c-s2tff-kubeconfig
  clusterName: c-s2tff
  conditions:
  - status: "True"
    type: Pending
  - lastUpdateTime: "2022-01-19T23:02:00Z"
    status: "True"
    type: Provisioned
  - lastUpdateTime: "2022-01-19T23:02:15Z"
    status: "True"
    type: Waiting
  - lastUpdateTime: "2022-01-19T22:59:07Z"
    status: "True"
    type: BackingNamespaceCreated
  - lastUpdateTime: "2022-01-19T22:59:07Z"
    status: "True"
    type: DefaultProjectCreated
  - lastUpdateTime: "2022-01-19T22:59:07Z"
    status: "True"
    type: SystemProjectCreated
  - lastUpdateTime: "2022-01-19T22:59:07Z"
    status: "True"
    type: InitialRolesPopulated
  - lastUpdateTime: "2022-01-19T22:59:07Z"
    status: "True"
    type: CreatorMadeOwner
  - lastUpdateTime: "2022-01-19T22:59:07Z"
    status: "True"
    type: NoDiskPressure
  - lastUpdateTime: "2022-01-19T22:59:07Z"
    status: "True"
    type: NoMemoryPressure
  - lastUpdateTime: "2022-01-19T23:02:15Z"
    status: "False"
    type: Reconciling
  - lastUpdateTime: "2022-01-19T22:59:07Z"
    status: "False"
    type: Stalled
  - lastUpdateTime: "2022-03-31T02:05:27Z"
    status: "True"
    type: Created
  - lastUpdateTime: "2022-01-19T22:59:08Z"
    status: "True"
    type: RKECluster
  - lastUpdateTime: "2022-03-31T02:05:27Z"
    status: "True"
    type: Connected
  - lastUpdateTime: "2022-01-19T23:02:01Z"
    status: "False"
    type: AlertingEnabled
  - lastUpdateTime: "2022-01-19T23:02:04Z"
    status: "True"
    type: SystemAccountCreated
  - lastUpdateTime: "2022-01-19T23:02:04Z"
    status: "True"
    type: AgentDeployed
  - lastUpdateTime: "2022-01-19T23:02:04Z"
    status: "False"
    type: PrometheusOperatorDeployed
  - lastUpdateTime: "2022-03-30T20:26:57Z"
    status: "True"
    type: Ready
  - lastUpdateTime: "2022-03-28T04:30:32Z"
    status: "True"
    type: Updated
  - lastUpdateTime: "2022-01-19T23:02:20Z"
    status: "True"
    type: ServiceAccountMigrated
  - lastUpdateTime: "2022-01-19T23:02:30Z"
    status: "True"
    type: GlobalAdminsSynced
  - lastUpdateTime: "2022-03-31T00:30:32Z"
    status: "True"
    type: Upgraded
  observedGeneration: 1
  ready: true

**Steps to Reproduce:**

- created a FCOS 35 node
- run the docker command to add it as worker node to the rancher cluster
- watch the node spin up

**Results:**
canal pod failed to come up, failed into crashloopbackoff. Somehow it marked up and running so pod are scheduled, but blocked.

[ContainersNotReady] containers with unready status: [calico-node kube-flannel]
[ContainersNotInitialized] containers with incomplete status: [flexvol-driver]
[ContainersNotReady] containers with unready status: [calico-node kube-flannel]

containers in pod
- rancher/mirrored-calico-node:v3.19.2
- rancher/mirrored-calico-pod2daemon-flexvol:v3.19.2
- rancher/mirrored-calico-cni:v3.19.2
- rancher/mirrored-coreos-flannel:v0.15.1

nginx-ingress-controller also blocked as a result of canal not coming up

pushprox-kube-proxy-client, rancher-monitoring-prometheus-node-exporter, cattle-node-agent are up and running.

I am also running metallb, its speaker is coming up

**Comment by linkafsar** [comment]
I think the issue is with flexvol-dir, can you check the path of flexvol dir. Coreos /usr is readonly filesystem which are unable to create.

**Comment by admun** [comment]
@linkafsar 

confirmed /usr is not writable...

[root@fcos-1 ~]# echo "aa" > /usr/aa
-bash: /usr/aa: Read-only file system

How can I get around this?

**Comment by linkafsar** [comment]
> @linkafsar
> 
> confirmed /usr is not writable...
> 
> [root@fcos-1 ~]# echo "aa" > /usr/aa -bash: /usr/aa: Read-only file system
> 
> How can I get around this?

You can change the path via rancher cluster edit yaml file to /opt instead of /usr

**Comment by linkafsar** [comment]
network:
  plugin: calico
  options: 
   - canal_flex_volume_plugin_dir: "/opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds"

**Comment by linkafsar** [comment]
> > @linkafsar
> > confirmed /usr is not writable...
> > [root@fcos-1 ~]# echo "aa" > /usr/aa -bash: /usr/aa: Read-only file system
> > How can I get around this?
> 
> You can change the path via rancher cluster edit yaml file to /opt instead of /usr
