### ISSUE TITLE
After adding a controlplane node to an existing RKE cluster nginx.conf is missing the new nodes IP

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rke#292]
**RKE version:**
v0.1.0

**Docker version: (`docker version`,`docker info` preferred)**
docker 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu-16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**

**Steps to Reproduce:**
    Update cluster adding a controlplane node
    First cluster config, Create three node cluster, each node with a single role
    node0 - controlplane
    node1 - etcd
    node2 - worker
    Update cluster by adding a controlplane node
    node0 - controlplane
    node1 - etcd
    node2 - worker
    node3 - controlplane

**Results:**
nginx-proxy container is missing the new IP for added controlplane node:
```
E                       AssertionError: Expected to find all controlplane node addresses ['18.217.210.58', '18.221.1.86']in nginx.conf: error_log stderr notice;
E                       
E                       worker_processes auto;
E                       events {
E                         multi_accept on;
E                         use epoll;
E                         worker_connections 1024;
E                       }
E                       
E                       stream {
E                               upstream kube_apiserver {
E                                   least_conn;
E                                   
E                                   server 18.217.210.58:6443;
E                                   
E                               }
E                       
E                               server {
E                                   listen        6443;
E                                   proxy_pass    kube_apiserver;
E                                   proxy_timeout 10m;
E                                   proxy_connect_timeout 1s;
E                       
E                               }
E                       
E                       }

rke_tests/common.py:130: AssertionError
```

**Comment by galal-hussein** [comment]
after debugging with @sabiodelhielo, the controlplane list is not being updated on etcd nodes but being updated on worker nodes, i will put a fix for this.

**Comment by sabiodelhielo** [comment]
Verified with v0.1.1-rc1
