### ISSUE TITLE
[Rancher 2.6.5] [RKE 1.3] Default k8s version switch to 1.23

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke#2924]
For the Rancher 2.6.5 release, we want to switch the default k8s version to 1.23.  See https://github.com/rancher/rancher/issues/37432
So does the REK CLI which will be released along with Rancher 2.6.5

**Comment by jiaqiluo** [comment]
can be tested with RKE CLI v1.3.11-rc2 

### to test

1. run `rke config -l` to print the default version 
2. run `rke up` to provision a cluster with the default version

**Comment by Josh-Diamond** [comment]
Ticket #2924 - Test Results

WIth RKE CLI `v1.3.11-rc2`:
1. Run `rke config -l` to verify default version
2. Verified - Default with `v1.3.11-rc2` is k8s `v1.23.6-rancher1-1`
3. Run `rke up` to provision a downstream rke1 cluster with k8s `v1.23.6`
4. Verified - Cluster successfully provisions

Screenshot:

`Step 2`
<img width="571" alt="Screen Shot 2022-05-06 at 9 37 44 AM" src="https://user-images.githubusercontent.com/46494969/167175495-f9231e2a-5ab0-41eb-adfa-bb77b199e8b6.png">

`Step 4`
<img width="573" alt="Screen Shot 2022-05-06 at 9 50 21 AM" src="https://user-images.githubusercontent.com/46494969/167177156-c3c3d13c-8441-486e-b435-364b59038f6e.png">
