### ISSUE TITLE
azureDisk CSIMigration set in v1.23.6

### ISSUE THREAD

**Issue by chfrank-cgn** [rancher/rke#2937]
**RKE version:** 
v1.23.6

**Docker version: (`docker version`,`docker info` preferred)** 
20.10

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 
Ubuntu 20.04 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**cluster.yml file:**
```
    cloud_provider {
      name = "azure"
      azure_cloud_provider {
        aad_client_id = var.az-client-id
        aad_client_secret = var.az-client-secret
        subscription_id = var.az-subscription-id
        tenant_id = var.az-tenant-id
        resource_group = var.az-resource-group
        subnet_name = var.az-subnet
        vnet_name = var.az-vnet
        security_group_name= var.az-sec-group
      }
```

**Steps to Reproduce:**
Create an azureDisk storage class with `provisioner: kubernetes.io/azure-disk`

**Results:**
The cluster event log will show:
Waiting for a volume to be created, either by external provisioner "[disk.csi.azure.com](http://disk.csi.azure.com/)" or manually created by system administrator

**Remedy**
We should test and document the installation of the [Azure Disk CSI driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver) and mention it in the release notes

**Comment by chfrank-cgn** [comment]
Following the Azure File CSI Driver Readme, creating a config map `azure-cred-file` pointing to the RKE cloud-config file `/etc/kubernetes/cloud-config` will enable the CSI drivers to run on v1.23.6

```
kubectl create configmap azure-cred-file --from-literal=path="/etc/kubernetes/cloud-config" -n kube-system
```

**Comment by chfrank-cgn** [comment]
I do believe we should test and document the installation of the [Azure Disk CSI driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver) and mention it in the RKE release notes

**Comment by chfrank-cgn** [comment]
I do believe we should test and document the installation of the [Azure Disk CSI driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver) and mention it in the RKE release notes

**Comment by chfrank-cgn** [comment]
I still do believe we should test and document the installation of the [Azure Disk CSI driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver) and mention it in the RKE release notes

**Comment by triburtius** [comment]
@chfrank-cgn This would be really useful to us!

**Comment by RP-TSB** [comment]
I invested lots of time trying to figure why my underlying storage wasn't created after deploying an RKE cluster on Azure through Rancher. If this was automated or even mentioned in the documentation I would have saved all of that time.

So in short, please prioritize this.

**Comment by RP-TSB** [comment]
I too do believe, same as @chfrank-cgn , that we should test and document the installation of the [Azure Disk CSI driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver) and mention it in the RKE release notes
