### ISSUE TITLE
upgrade the RKE version

### ISSUE THREAD

**Issue by litao812** [rancher/rke#2985]
If I have deployed the k8s cluster and want to upgrade the cluster version, but the maximum version of k8s supported by RKE cannot meet my requirements, can I upgrade the RKE version to a higher version without reinstalling the k8s cluster to facilitate upgrading the k8s version?

**Comment by oxr463** [comment]
Yes, you can upgrade the RKE version and then upgrade your cluster without reinstalling from scratch.
