### ISSUE TITLE
RKE - Bump the default version to 1.24 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke#2989]
Bump the default version to 1.24

**Comment by jiaqiluo** [comment]
can be validated on rke v1.3.13-rc5

**Comment by sowmyav27** [comment]
Command to use `rke config -l`

**Comment by Josh-Diamond** [comment]
Ticket #2989 - Test Results

Verified on rke `v1.3.13-rc5`:
1. With rke `v1.3.13-rc5`, run `rke config -l` via terminal
2. Verified - Default k8s version is `v1.24.2-rancher1-1`

Screenshot:

`Step 2`
<img width="841" alt="Screen Shot 2022-07-21 at 6 40 56 PM" src="https://user-images.githubusercontent.com/46494969/180349252-2a0e977d-baf4-4502-a98d-6c1ae15d4f48.png">
