### ISSUE TITLE
Upgrades to Kubernetes >= v1.22.x leave duplicate iptables rules for hostport pods on pod termination with Calico or Canal

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#2999]
**RKE version:** v1.3.x

On Kubernetes versions >= v1.22.x, the `portmap` plugin was updated from `v0.8.6` to `v1.0.0`. This update was a result of upgrading the version of Calico/Canal from `v3.19.x` to `v3.21.x`. The newer version of portmap included a change that `noop`s when `portMappings` are not provided. Traditionally, this doesn't matter; however, when using hostPort, portMappings are used and the `portmap` binary is responsible for making changes on the system.

RKE1 uses dockershim/cri-dockerd to manage containers/pods. These components store pod metadata on disk in the directory `/var/lib/dockershim` or `/var/lib/cri-dockerd`. Due to the containerized nature of RKE1, the `kubelet` container treats the directory as ephemeral (as it is not bind mounted/persisted using volumes), and on upgrades of K8s versions, the sandbox metadata gets deleted.

Traditionally, this is OK, as the kubelet will still attempt to tear down pods to the best of its ability; however, when using hostPort and the newer portmap plugin, the pod teardown doesn't happen for the portmap iptables rules as the `portmap` binary is invoked with an empty `portMappings` list. This is because the dockershim/cri-dockerd are unaware of the metadata originally used to create the pod.

The solution that we are implementing for RKE1 is to fork and maintain a modified version of `portmap` which reverts the `noop` change. We are then distributing our own version of `calico-cni` which contains all upstream binaries except for `portmap`.

This issue ties into: https://github.com/rancher/rke/issues/2993 ; however, it is primarily focused on upgrade testing.

This issue is evident with the following scenario.

* Have a single node, all-in-one, K8s `v1.22.9-rancher1-1` cluster. Observe the `nginx-ingress-controller` is accessible.
* Upgrade to K8s `v1.22.10-rancher1-1`, and observe that the `nginx-ingress-controller` pod is restarted but is no longer accessible. 
* This can also happen with the following known scenarios:
* `v1.21.10-rancher1-1` to `v1.22.7-rancher1-2`
* `v1.21.13-rancher1-1` to `v1.22.10-rancher1-1`

In multi-node, Rancher-provisioned environments, it is possible that the issue does not immediately manifest itself. This is due to order of operations. In these environments, the nginx ingress controller pod may be recreated before the CNI plugins are updated, which will leave the cluster in a semi-usable state.

**Comment by Oats87** [comment]
## Issue:
https://github.com/rancher/rke/issues/2993
https://github.com/rancher/rke/issues/2999

## Problem
Please see both of the issues.

## Solution
Please see both of the issues.

## Testing
Please follow the issue in #2999

The duplicate iptables rule can be seen using `iptables-save | grep "HOSTPORT"`

## Engineering Testing
### Manual Testing
I ran the upgrade scenarios and observed no duplicate iptables rules
### Automated Testing


## QA Testing Considerations
N/A
### Regressions Considerations

**Comment by markusewalker** [comment]
Verified that this is addressed in `v1.3.13-rc6`.

**ENVIRONMENT DETAILS**
- Client Machine: Ubuntu 20.04
- RKE version
     - Reproduced version: `v1.3.12`
     - Verified version: `v1.3.13-rc6`
	
**TEST RESULT**
PASS

**REPRODUCTION STEPS**
(NOTE: Similar issue where I have reproduced the ingress behavior is here: https://github.com/rancher/rancher/issues/38270#issuecomment-1201356642)
1. On a client machine, downloaded RKE `v1.3.12` and set it up.
2. Provisioned a downstream RKE1 cluster at version `v1.21.13-rancher1-1`; verify this was successful.
3. Copied the kubeconfig over to the `$HOME/.kube` location.
4. Once done, verified that the `nginx-ingress-controller` pod is up and running with `kubectl get pods -A`.
5. Upgraded to `v1.22.10-rancher1-1`; verified that the upgrade is successful.
6. Copied the new kubeconfig over to the `$HOME/.kube` location.
7. Verified if the `nginx-ingress-controller` pod was restarted, but was no longer accessible.
8. Ran command `iptables-save | grep "HOSTPORT"; verified that I am seeing duplicate entries:
9. Repeated steps 5-8, but upgraded to `v1.23.7-rancher1-1`; verified that I am still seeing duplicate entries.


**VERIFICATION STEPS**
1. On a client machine, downloaded RKE `v1.3.13-rc6` and set it up.
2. Provisioned a downstream RKE1 cluster at version `v1.21.14-rancher1-1`; verify this was successful.
3. Copied the kubeconfig over to the `$HOME/.kube` location.
4. Once done, verified that the `nginx-ingress-controller` pod is up and running with `kubectl get pods -A`.
5. Upgraded to `v1.22.11-rancher1-1`; verified that the upgrade is successful.
6. Copied the new kubeconfig over to the `$HOME/.kube` location.
7. Verified if the `nginx-ingress-controller` pod was restarted, but was no longer accessible.
8. Ran command `iptables-save | grep "HOSTPORT"; verified that I no longer am seeing duplicate entries.
9. Repeated steps 5-8, but upgraded to `v1.24.2-rancher1-1`; verified that I still DO NOT see any duplicate entries.

**Comment by sowmyav27** [comment]
**On 2.6-head**

- `v1.22.11-rancher1-1` to `1.23.8-rancher1-1` --> And verify ingress is functional
- `v1.22.11-rancher1-1` to `1.23.8-rancher1-1` + a redeploy of ingress daemonset from Rancher UI --> Verify ingress is functional
- `1.23.8-rancher1-1` to  `v1.24.2-rancher1-1` --> And verify ingress is functional
- `1.23.8-rancher1-1` to  `v1.24.2-rancher1-1` + a redeploy of ingress daemonset from Rancher UI --> Verify ingress is functional

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6.7-rc7

Steps followed:

Case 1:
- Provisioned node driver k8s `v1.22.11-rancher1-1` clusters with canal and calico network provider -> 1cp, 1etcd, 1w
- Ran pre-upgrade checks. All checks passed
- Upgraded the cluster to `1.23.8-rancher1-1`
- Ran post upgrade checks. All the checks passed

Case 2:
- Provisioned node driver k8s `v1.22.11-rancher1-1` clusters with canal and calico network provider -> 1cp, 1etcd, 1w
- Ran pre-upgrade checks. All checks passed
- Upgraded the cluster to `1.23.8-rancher1-1`
- Redeployed `nginx-ingress-controller` daemonset from UI, it came up Active
- Ran post upgrade checks. All the checks passed.

Case 3:
- Provisioned node driver k8s `1.23.8-rancher1-1` clusters with canal and calico network provider -> 1cp, 1etcd, 1w
- Ran pre-upgrade checks. All checks passed
- Upgraded the cluster to `v1.24.2-rancher1-1`
- Ran post upgrade checks. All the checks passed.

Case 4:
- Provisioned node driver k8s `1.23.8-rancher1-1` clusters with canal and calico network provider -> 1cp, 1etcd, 1w
- Ran pre-upgrade checks. All checks passed
- Upgraded the cluster to `v1.24.2-rancher1-1`
- Redeployed `nginx-ingress-controller` daemonset from UI, it came up Active
- Ran post upgrade checks. All the checks passed.

Result:
- Ingress functionality is working and all the pre and post upgrade checks passed.
