### ISSUE TITLE
use comma-separated dual-stack IP addresses to internal_address  lead to rke up fail

### ISSUE THREAD

**Issue by chilli13** [rancher/rke#3010]
**RKE version:**
v1.3.4

**Docker version: (`docker version`,`docker info` preferred)**
 docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 25
  Running: 10
  Paused: 0
  Stopped: 15
 Images: 8
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 4.684GiB
 Name: zhm-m1
 ID: 2AKL:JZV6:56SS:LH7C:MVFL:TLS4:BS2G:UND4:VYGT:PNL3:3KUK:VJX4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  zhm-m1:5000
  127.0.0.0/8
 Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
#cat /etc/centos-release
CentOS Linux release 7.8.2003 (Core)
# uname -a
Linux zhm-m1 3.10.0-1127.el7.x86_64 rancher/rke#1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**
# cat tc-cluster.yml 
addon_job_timeout: 300
cluster_name: tc_cluster
dns:
  provider: coredns
kubernetes_version: v1.22.5-rancher1-1
network:
  plugin: calico
nodes:
- address: m1
  internal_address: 192.168.88.132
  role:
  - controlplane
  - etcd
  ssh_key_path: /root/.ssh/id_rsa
  user: rke
- address: m2
  internal_address: 192.168.88.133
  role:
  - controlplane
  - etcd
  ssh_key_path: /root/.ssh/id_rsa
  user: rke
- address: w1
  internal_address: 192.168.88.134
  role:
  - controlplane
  - worker
  - etcd
  ssh_key_path: /root/.ssh/id_rsa
  user: rke
- address: w2
  internal_address: 192.168.88.135
  role:
  - worker
  ssh_key_path: /root/.ssh/id_rsa
  user: rke
nvidia_gpu_enable: false
private_registries:
- is_default: true
  password:
  url: m1:5000
  user: docker
services:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16,fd98::/108
  kube-controller:
    cluster_cidr: 10.42.0.0/16,fd01::/64
    node_cidr_mask_size_ipv4: 24
    node_cidr_mask_size_ipv6: 108
    service_cluster_ip_range: 10.43.0.0/16,fd98::/108
  kubeproxy:
    cluster_cidr: 10.42.0.0/16,fd01::/64
    extra_args:
      proxy-mode: ipvs

**Steps to Reproduce:**
use comma-separated dual-stack IP addresses to internal_address  lead to rke up fail
can rke support nodes internal_address: 192.168.88.132,000::5 to support node dual-stack 
kubelet already support --node-ip  use dual-stack ip address
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
--node-ip string
IP address (or comma-separated dual-stack IP addresses) of the node. If unset, kubelet will use the node's default IPv4 address, if any, or its default IPv6 address if it has no IPv4 addresses. You can pass '::' to make it prefer the default IPv6 address rather than the default IPv4 address.

**Results:**
use comma-separated dual-stack IP addresses to internal_address  lead to rke up fail

**Comment by shaopenghan** [comment]
我也遇到了这个问题，是否有计划将在最新版本修复

**Comment by chilli13** [comment]
Does RKR have any plans to support on latest release version?

**Comment by chilli13** [comment]
Does RKR have any plans to support on latest release version?
