### ISSUE TITLE
Incorrect images list for RKE version

### ISSUE THREAD

**Issue by afrozk** [rancher/rke#3030]
**RKE version:**
v1.18.20-rancher1-3

**Steps to Reproduce:**
When running `./rke_linux-amd64-123 config --system-images --version=v1.18.20-rancher1-3`. 

List of images shows as 

INFO[0000] Generating images list for version [v1.18.20-rancher1-3]:
rancher/mirrored-coreos-etcd:v3.4.15-rancher1
rancher/rke-tools:v0.1.75
rancher/mirrored-k8s-dns-kube-dns:1.15.2
rancher/mirrored-k8s-dns-dnsmasq-nanny:1.15.2
rancher/mirrored-k8s-dns-sidecar:1.15.2
rancher/mirrored-cluster-proportional-autoscaler:1.7.1
rancher/mirrored-coredns-coredns:1.6.9
rancher/mirrored-k8s-dns-node-cache:1.15.7
rancher/hyperkube:v1.18.20-rancher1
rancher/mirrored-coreos-flannel:v0.15.1
rancher/flannel-cni:v0.3.0-rancher6
rancher/mirrored-calico-node:v3.13.4
rancher/mirrored-calico-cni:v3.13.4
rancher/mirrored-calico-kube-controllers:v3.13.4
rancher/mirrored-calico-ctl:v3.13.4
rancher/mirrored-calico-pod2daemon-flexvol:v3.13.4
weaveworks/weave-kube:2.6.4
weaveworks/weave-npc:2.6.4
rancher/mirrored-pause:3.1
rancher/nginx-ingress-controller:nginx-0.35.0-rancher2
rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
rancher/mirrored-metrics-server:v0.3.6
noiro/cnideploy:5.1.1.0.1ae238a
noiro/aci-containers-host:5.1.1.0.1ae238a
noiro/opflex:5.1.1.0.1ae238a
noiro/openvswitch:5.1.1.0.1ae238a
noiro/aci-containers-controller:5.1.1.0.1ae238a
noiro/gbp-server:5.1.1.0.1ae238a
noiro/opflex-server:5.1.1.0.1ae238a

After i push the list of images as above to my private registry, RKE upgrade complains about one image missing that is rancher/rke-tools:v0.1.87.
**Results:**
./rke_linux-amd64-123 config --system-images --version=v1.18.20-rancher1-3 should show correct list of images for the version

**Comment by samene** [comment]
Same as #3029 
The version of rke-tools is not mapped to the kubernetes version, rather to the rke version.
