### ISSUE TITLE
Update cri-dockerd  to v0.2.6

### ISSUE THREAD

**Issue by y1ka** [rancher/rke#3051]
**RKE version: 1.3.15**

Please update:
https://github.com/Mirantis/cri-dockerd/commits/v0.2.6

Reason:
https://github.com/Mirantis/cri-dockerd/issues/91

**Comment by horihel** [comment]
This is actually quite important, as it fixes _any_ interaction with docker that take longer than 2 minutes.
* ImagePulls with large images fail (and im some cases are not retried properly, causing helm timeouts or prolonged incomplete deployments)
* `kubectl logs` fails after 2 minutes with docker socket errors

these are just the problems we observed with rke 1.3.15, there might be more interactions with cri-dockerd that stay alive for longer than 2 minutes.

**Comment by vinibodruch** [comment]
Any update of this?

**Comment by jiaqiluo** [comment]
This will fix https://github.com/rancher/rke/issues/3084

**Comment by snasovich** [comment]
Closing in favor of https://github.com/rancher/rke/issues/3084, the work to bump `cri-dockerd` will be tracked there.
