### ISSUE TITLE
RKE v1.4.0 - Hide k8s 1.22 and below from the version list 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke#3074]
Hide k8s 1.22 and below from the version list 

This request is derived from https://github.com/rancher/rancher/issues/39239 where you can find more information

**Comment by jiaqiluo** [comment]
can be validated on RKE `v1.4.0-rc4`

**Comment by jiaqiluo** [comment]
@sowmyav27  can you help assign the issue to your team?

**Comment by Josh-Diamond** [comment]
Ticket #3074 - Test Results
---

Verified - RKE1 - [standalone w/ rke `v1.4.0-rc4`]:

1. Attempt to provision clusters, with the following k8s versions:
- `1.23` - [expected to be available]
- `1.24` - [expected to be available]
2. Run `rke config --system-images --version -`
3. Verified - K8s `v1.23.12-rancher1-1` + `v1.24.6-rancher1-1` available
4. Verified - K8s `v1.24.6-rancher1-1` is default version
5. Verified - `v1.23` + `v1.24` clusters successfully provision w/ all nodes accurately reflecting k8s versions

**Comment by HectorB-2020** [comment]
Hello @jiaqiluo and @Josh-Diamond! I hope you can help me understand what versioning means.
In particular I've been trying to understand what last digit means:
v1.23.12-rancher1-**1**
v1.23.12-rancher**2**-**3**
Frankly speaking I'm looking for a document explaining all of this to understand which version of we need. When saying about container images there are not images with "dash something". Therefore I'm confused.

**Comment by jiaqiluo** [comment]
hi @HectorB-2020, 
 
Taking the RKE version `v1.23.12-rancher1-1` as an example,   `v1.23.12` matches the upstream k8s version, `v1.23.12-rancher1` matches the tag of the `rancher/hyperkube` image used when provisioning the cluster, the ending `-1`  means it is the 1st version we released for this k8s version. 

If we have to bump the tag of the hyperkube image, the new version will be `v1.23.12-rancher2-1`;  If we have to fix something in the addons or other components, the new version will be `v1.23.12-rancher1-2`. 


We recommend using the latest RKE version for the corresponding k8s version, and in your examples, `v1.23.12-rancher2-3` is a newer version than `v1.23.12-rancher1-1`. 


I hope the above can answer your questions.

**Comment by HectorB-2020** [comment]
Fantastic answer, thanks very much, @jiaqiluo!

Still one more question remains. When running `rke config` we are to provide k8s version in reduced form e.g. `v1.24.15-rancher1`. The last digit is not specified. Which version will `rke` use? 
I raised some other concerns about k8s versions in #3295.

**Comment by jiaqiluo** [comment]
@HectorB-2020, in this case, the default version will be used. 
https://github.com/rancher/rke/blob/5a8cacb962809382906100bcb8e797e9c8144f68/cmd/config.go#L296-L310

To check the default version, run `rke config -l`
```
> rke config -l   
v1.26.6-rancher1-1
```
