### ISSUE TITLE
[v1.4] Support certificate chains when using custom certs 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rke#3083]
This issue is to forward port https://github.com/rancher/rke/issues/1834. PR for this has been merged to `release/v1.3` branch - https://github.com/rancher/rke/pull/2742. Need to forward port it.

**Comment by TheSp1der** [comment]
Can we re-open this? Having the ability to include intermediate certificates would be a huge benefit when using internal company issued certificates.

**Comment by TheSp1der** [comment]
This is still relivant and would be resolved by merging [PR#3213](https://github.com/rancher/rke/pull/3213).

**Comment by TheSp1der** [comment]
This is still relevant and would be resolved by merging https://github.com/rancher/rke/pull/3213.

**Comment by TheSp1der** [comment]
This is still relevant and would be resolved by merging https://github.com/rancher/rke/pull/3213.

**Comment by TheSp1der** [comment]
@kinarashah Thank you, I had given up hope for this PR.
