### ISSUE TITLE
Image label metrics not found 

### ISSUE THREAD

**Issue by jehutyy** [rancher/rke#3123]
I have a kube-prometheus install (latest) which doesn't work for certain metrics (I get No Data on some dashboard).

I figured the following prometheus rule returns no result on rke cluster :
`container_cpu_usage_seconds_total{image!="",job="kubelet",metrics_path="/metrics/cadvisor"}`

On the contrary it does work fine when I get rid of `image` label.

I tested on minikube and k3d and it works fine with or without image label.

**RKE version:**
v1.3.15

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 20.10.21

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.18.0-425.3.1.el8.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox

**Comment by hugodopradofernandes** [comment]
Removing it from the prometheus queries solved for me:
**image!="",name=~"^k8s_.*",**
