### ISSUE TITLE
rke etcd snapshot-save - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gmanera** [rancher/rke#3135]
**RKE version:**
[rancher@anchieta ~]$ rke --version
rke version v1.4.1

**Docker version: (`docker version`,`docker info` preferred)**
[rancher@anchieta ~]$ docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:58:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:02:38 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[rancher@anchieta ~]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 20
  Running: 20
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.76.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.58GiB
 Name: anchieta
 ID: OZNJ:RKES:NTOH:G37X:4NYO:IJ3U:SKHO:FFG3:RJ7B:GCCJ:XOZN:NRHE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

[rancher@anchieta ~]$

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
[rancher@anchieta ~]$ uname -r
3.10.0-1160.76.1.el7.x86_64

[rancher@anchieta ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware
**cluster.yml file:**
[rancher@anchieta ~]$ cat /home/rancher/rancher-ouze-cluster/cluster.yaml
#Arquivo RKE de configuração do Rancher-Ouze-PRD RKE1.
#Conferir os nomes no https://rancher-ouze.calcard.com.br/dashboard/c/local/explorer/node. Nomes devem estar iguais dos hosts já existentes
nodes:
- address: anchieta.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: aracruz.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: piuma.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: vilavelha.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: saomateus.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: marataizes.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: saovicente.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: praiadasdunas.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: praiadoespelho.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: praiadocalhau.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: praiadacosta.sol.gabriela.br
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: rancher
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    retention: ""
    creation: ""
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args:
      runtime-request-timeout: 30m
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: canal
  options: {}
  mtu: 0
  node_selector: {}
  tolerations: []
authentication:
  strategy: x509
  sans: []
addons: ""
addons_include: []
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
kubernetes_version: "v1.24.8-rancher1-1"
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  ignore_proxy_env_vars: false
restore:
  restore: false
  snapshot_name: ""

**Steps to Reproduce:**
rke etcd snapshot-save --config /home/rancher/rancher-ouze-cluster/cluster.yaml --name backup-cluster-ansible-worker-upgrade --folder /opt/rke/etcd-snapshots

**Results:**
[rancher@anchieta ~]$ rke etcd snapshot-save --config /home/rancher/rancher-ouze-cluster/cluster.yaml --name backup-cluster-ansible-worker-upgrade --folder /opt/rke/etcd-snapshots
INFO[0000] Running RKE version: v1.4.1
INFO[0000] Starting saving snapshot on etcd hosts
INFO[0000] [dialer] Setup tunnel for host [vilavelha.sol.gabriela.br]
INFO[0000] [dialer] Setup tunnel for host [praiadacosta.sol.gabriela.br]
INFO[0000] [dialer] Setup tunnel for host [saomateus.sol.gabriela.br]
INFO[0000] [dialer] Setup tunnel for host [marataizes.sol.gabriela.br]
INFO[0000] [dialer] Setup tunnel for host [saovicente.sol.gabriela.br]
INFO[0000] [dialer] Setup tunnel for host [anchieta.sol.gabriela.br]
INFO[0000] [dialer] Setup tunnel for host [praiadoespelho.sol.gabriela.br]
INFO[0000] [dialer] Setup tunnel for host [aracruz.sol.gabriela.br]
INFO[0000] [dialer] Setup tunnel for host [praiadasdunas.sol.gabriela.br]
INFO[0000] [dialer] Setup tunnel for host [praiadocalhau.sol.gabriela.br]
INFO[0000] [dialer] Setup tunnel for host [piuma.sol.gabriela.br]
INFO[0000] [state] Deploying state file to [/etc/kubernetes/backup-cluster-ansible-worker-upgrade.rkestate] on host [anchieta.sol.gabriela.br]
INFO[0000] [state] Deploying state file to [/etc/kubernetes/backup-cluster-ansible-worker-upgrade.rkestate] on host [aracruz.sol.gabriela.br]
INFO[0000] [state] Deploying state file to [/etc/kubernetes/backup-cluster-ansible-worker-upgrade.rkestate] on host [piuma.sol.gabriela.br]
INFO[0000] Image [rancher/rke-tools:v0.1.88] exists on host [aracruz.sol.gabriela.br]
INFO[0000] Image [rancher/rke-tools:v0.1.88] exists on host [piuma.sol.gabriela.br]
INFO[0000] Image [rancher/rke-tools:v0.1.88] exists on host [anchieta.sol.gabriela.br]
INFO[0000] Starting container [cluster-state-deployer] on host [piuma.sol.gabriela.br], try rancher/rke#1
INFO[0000] Starting container [cluster-state-deployer] on host [aracruz.sol.gabriela.br], try rancher/rke#1
INFO[0000] Starting container [cluster-state-deployer] on host [anchieta.sol.gabriela.br], try rancher/rke#1
INFO[0000] [state] Successfully started [cluster-state-deployer] container on host [piuma.sol.gabriela.br]
INFO[0000] [state] Successfully started [cluster-state-deployer] container on host [aracruz.sol.gabriela.br]
INFO[0000] [state] Successfully started [cluster-state-deployer] container on host [anchieta.sol.gabriela.br]
INFO[0000] Waiting for [cluster-state-deployer] container to exit on host [piuma.sol.gabriela.br]
INFO[0000] Waiting for [cluster-state-deployer] container to exit on host [aracruz.sol.gabriela.br]
INFO[0000] Waiting for [cluster-state-deployer] container to exit on host [anchieta.sol.gabriela.br]
INFO[0000] Removing container [cluster-state-deployer] on host [piuma.sol.gabriela.br], try rancher/rke#1
INFO[0000] Removing container [cluster-state-deployer] on host [aracruz.sol.gabriela.br], try rancher/rke#1
INFO[0000] [remove/cluster-state-deployer] Successfully removed container on host [piuma.sol.gabriela.br]
INFO[0000] [remove/cluster-state-deployer] Successfully removed container on host [aracruz.sol.gabriela.br]
INFO[0000] Removing container [cluster-state-deployer] on host [anchieta.sol.gabriela.br], try rancher/rke#1
INFO[0000] [remove/cluster-state-deployer] Successfully removed container on host [anchieta.sol.gabriela.br]
INFO[0000] [etcd] Running snapshot save once on host [anchieta.sol.gabriela.br]
INFO[0000] Finding container [etcd] on host [anchieta.sol.gabriela.br], try rancher/rke#1
INFO[0000] Image [rancher/rke-tools:v0.1.88] exists on host [anchieta.sol.gabriela.br]
INFO[0001] Starting container [etcd-snapshot-once] on host [anchieta.sol.gabriela.br], try rancher/rke#1
INFO[0001] [etcd] Successfully started [etcd-snapshot-once] container on host [anchieta.sol.gabriela.br]
INFO[0001] Waiting for [etcd-snapshot-once] container to exit on host [anchieta.sol.gabriela.br]
INFO[0001] Container [etcd-snapshot-once] is still running on host [anchieta.sol.gabriela.br]: stderr: [time="2023-01-05T18:05:28Z" level=info msg="Initializing Onetime Backup" name=backup-cluster-ansible-worker-upgrade
], stdout: []
INFO[0005] Removing container [etcd-snapshot-once] on host [anchieta.sol.gabriela.br], try rancher/rke#1
INFO[0005] [etcd] Running snapshot save once on host [aracruz.sol.gabriela.br]
INFO[0005] Finding container [etcd] on host [aracruz.sol.gabriela.br], try rancher/rke#1
INFO[0005] Image [rancher/rke-tools:v0.1.88] exists on host [aracruz.sol.gabriela.br]
INFO[0005] Starting container [etcd-snapshot-once] on host [aracruz.sol.gabriela.br], try rancher/rke#1
INFO[0005] [etcd] Successfully started [etcd-snapshot-once] container on host [aracruz.sol.gabriela.br]
INFO[0005] Waiting for [etcd-snapshot-once] container to exit on host [aracruz.sol.gabriela.br]
INFO[0006] Container [etcd-snapshot-once] is still running on host [aracruz.sol.gabriela.br]: stderr: [time="2023-01-05T18:05:32Z" level=info msg="Initializing Onetime Backup" name=backup-cluster-ansible-worker-upgrade
], stdout: []
INFO[0009] Removing container [etcd-snapshot-once] on host [aracruz.sol.gabriela.br], try rancher/rke#1
INFO[0009] [etcd] Running snapshot save once on host [piuma.sol.gabriela.br]
INFO[0009] Finding container [etcd] on host [piuma.sol.gabriela.br], try rancher/rke#1
INFO[0009] Image [rancher/rke-tools:v0.1.88] exists on host [piuma.sol.gabriela.br]
INFO[0009] Starting container [etcd-snapshot-once] on host [piuma.sol.gabriela.br], try rancher/rke#1
INFO[0009] [etcd] Successfully started [etcd-snapshot-once] container on host [piuma.sol.gabriela.br]
INFO[0009] Waiting for [etcd-snapshot-once] container to exit on host [piuma.sol.gabriela.br]
INFO[0009] Container [etcd-snapshot-once] is still running on host [piuma.sol.gabriela.br]: stderr: [time="2023-01-05T18:05:36Z" level=info msg="Initializing Onetime Backup" name=backup-cluster-ansible-worker-upgrade
], stdout: []
INFO[0013] Removing container [etcd-snapshot-once] on host [piuma.sol.gabriela.br], try rancher/rke#1
INFO[0013] [etcd] Finished saving snapshot [backup-cluster-ansible-worker-upgrade] on all etcd hosts
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1984175]

goroutine 1 [running]:
github.com/rancher/rke/cluster.(*Cluster).SnapshotEtcd(0xc000812000, {0x2218e38, 0xc000052078}, {0x7ffe4231182b, 0x25})
        /go/src/github.com/rancher/rke/cluster/etcd.go:54 +0x415
github.com/rancher/rke/cmd.SnapshotSaveEtcdHosts({0x2218e38, 0xc000052078}, 0x0, {0x0, 0x0, 0x0}, {{0x0, 0x0}, {0x7ffe423117f4, 0x2f}, ...}, ...)
        /go/src/github.com/rancher/rke/cmd/etcd.go:133 +0x226
github.com/rancher/rke/cmd.SnapshotSaveEtcdHostsFromCli(0xc00002f8c0)
        /go/src/github.com/rancher/rke/cmd/etcd.go:321 +0x333
github.com/urfave/cli.HandleAction({0x1b34e00, 0x1f901c0}, 0xd)
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:523 +0xa8
github.com/urfave/cli.Command.Run({{0x1e9fe89, 0xd}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1ec19d8, 0x1f}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:174 +0x63a
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0007caa80, 0xc00002f600)
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:404 +0x9ec
github.com/urfave/cli.Command.startApp({{0x1e8ecf0, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1efbbaa, 0x34}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:373 +0x6e9
github.com/urfave/cli.Command.Run({{0x1e8ecf0, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1efbbaa, 0x34}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:102 +0x825
github.com/urfave/cli.(*App).Run(0xc0007ca8c0, {0xc00004c090, 0x9, 0x9})
        /go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:276 +0x80c
main.mainErr()
        /go/src/github.com/rancher/rke/main.go:81 +0x1825
main.main()
        /go/src/github.com/rancher/rke/main.go:25 +0x33

**Comment by gmanera** [comment]
Workaround: 
Use other version instead like this one:

[rancher@server~]$ rke --version
rke version v1.3.17

**Comment by superseb** [comment]
Probably the same as https://github.com/rancher/rke/issues/3099

**Comment by mostafaghadimi** [comment]
I'm experiencing the same problem in version `1.4.2` of RKE.

**Comment by evertton** [comment]
It's working in version `1.3.18`.
I too was experiencing the same problem in version `1.4.2`.

**Comment by superseb** [comment]
Should be fixed in v1.4.3, let us know if you still run into issues.
