### ISSUE TITLE
RKE upgrade to v1.4.2 is failing at rke-network-plugin-deploy-job-whzjm  with The CustomResourceDefinition "felixconfigurations.crd.projectcalico.org" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema

### ISSUE THREAD

**Issue by Nayanabvreddy** [rancher/rke#3152]
**RKE version:**

1.4.2

**Docker version: (`docker version`,`docker info` preferred)**

 19.03.13

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

uname -r
4.9.206-36.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM on Vmware infrastruce on praxis

**cluster.yml file:**

nodes:
  - address: 10.24.10.194
    user: maa
    role: [controlplane, worker, etcd]
  - address: 10.24.10.193
    user: maa
    role: [controlplane, worker, etcd]
  - address: 10.24.10.185
    user: maa
    role: [controlplane, worker, etcd]
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ingress:
  provider: nginx
options:
    use-forwarded-headers: "true"
kubernetes_version: "v1.24.9-rancher1-1"

**Steps to Reproduce:**
Download rke 1.4.2
rke up --config cluster.yml

**Results:**
$ rke up --config cluster.yml
INFO[0000] Running RKE version: v1.4.2                  
INFO[0000] Initiating Kubernetes cluster                
INFO[0000] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates 
INFO[0000] [certificates] Generating admin certificates and kubeconfig 
INFO[0000] Successfully Deployed state file at [./rancher-cluster.rkestate] 
INFO[0000] Building Kubernetes cluster                  
INFO[0000] [dialer] Setup tunnel for host [10.24.10.194] 
INFO[0000] [dialer] Setup tunnel for host [10.24.10.193] 
INFO[0000] [dialer] Setup tunnel for host [10.24.10.185] 
INFO[0000] [network] No hosts added existing cluster, skipping port check 
INFO[0000] [certificates] Deploying kubernetes certificates to Cluster nodes 
INFO[0000] Finding container [cert-deployer] on host [10.24.10.194], try rancher/rke#1 
INFO[0000] Finding container [cert-deployer] on host [10.24.10.193], try rancher/rke#1 
INFO[0000] Finding container [cert-deployer] on host [10.24.10.185], try rancher/rke#1 
INFO[0000] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.185] 
INFO[0001] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.193] 
INFO[0001] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.194] 
INFO[0001] Starting container [cert-deployer] on host [10.24.10.185], try rancher/rke#1 
INFO[0002] Finding container [cert-deployer] on host [10.24.10.185], try rancher/rke#1 
INFO[0003] Starting container [cert-deployer] on host [10.24.10.194], try rancher/rke#1 
INFO[0004] Starting container [cert-deployer] on host [10.24.10.193], try rancher/rke#1 
INFO[0005] Finding container [cert-deployer] on host [10.24.10.193], try rancher/rke#1 
INFO[0006] Finding container [cert-deployer] on host [10.24.10.194], try rancher/rke#1 
INFO[0007] Finding container [cert-deployer] on host [10.24.10.185], try rancher/rke#1 
INFO[0007] Removing container [cert-deployer] on host [10.24.10.185], try rancher/rke#1 
INFO[0010] Finding container [cert-deployer] on host [10.24.10.193], try rancher/rke#1 
INFO[0010] Removing container [cert-deployer] on host [10.24.10.193], try rancher/rke#1 
INFO[0011] Finding container [cert-deployer] on host [10.24.10.194], try rancher/rke#1 
INFO[0011] Removing container [cert-deployer] on host [10.24.10.194], try rancher/rke#1 
INFO[0011] [reconcile] Rebuilding and updating local kube config 
INFO[0011] Successfully Deployed local admin kubeconfig at [./kube_config_rancher-cluster.yml] 
INFO[0011] [reconcile] host [10.24.10.194] is a control plane node with reachable Kubernetes API endpoint in the cluster 
INFO[0011] [certificates] Successfully deployed kubernetes certificates to Cluster nodes 
INFO[0011] [file-deploy] Deploying file [/etc/kubernetes/audit-policy.yaml] to node [10.24.10.194] 
INFO[0012] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.194] 
INFO[0014] Starting container [file-deployer] on host [10.24.10.194], try rancher/rke#1 
INFO[0017] Successfully started [file-deployer] container on host [10.24.10.194] 
INFO[0017] Waiting for [file-deployer] container to exit on host [10.24.10.194] 
INFO[0017] Waiting for [file-deployer] container to exit on host [10.24.10.194] 
INFO[0017] Container [file-deployer] is still running on host [10.24.10.194]: stderr: [], stdout: [] 
INFO[0019] Removing container [file-deployer] on host [10.24.10.194], try rancher/rke#1 
INFO[0019] [remove/file-deployer] Successfully removed container on host [10.24.10.194] 
INFO[0019] [file-deploy] Deploying file [/etc/kubernetes/audit-policy.yaml] to node [10.24.10.193] 
INFO[0019] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.193] 
INFO[0021] Starting container [file-deployer] on host [10.24.10.193], try rancher/rke#1 
INFO[0022] Successfully started [file-deployer] container on host [10.24.10.193] 
INFO[0022] Waiting for [file-deployer] container to exit on host [10.24.10.193] 
INFO[0022] Waiting for [file-deployer] container to exit on host [10.24.10.193] 
INFO[0022] Container [file-deployer] is still running on host [10.24.10.193]: stderr: [], stdout: [] 
INFO[0023] Removing container [file-deployer] on host [10.24.10.193], try rancher/rke#1 
INFO[0023] [remove/file-deployer] Successfully removed container on host [10.24.10.193] 
INFO[0023] [file-deploy] Deploying file [/etc/kubernetes/audit-policy.yaml] to node [10.24.10.185] 
INFO[0023] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.185] 
INFO[0025] Starting container [file-deployer] on host [10.24.10.185], try rancher/rke#1 
INFO[0025] Successfully started [file-deployer] container on host [10.24.10.185] 
INFO[0025] Waiting for [file-deployer] container to exit on host [10.24.10.185] 
INFO[0025] Waiting for [file-deployer] container to exit on host [10.24.10.185] 
INFO[0026] Container [file-deployer] is still running on host [10.24.10.185]: stderr: [], stdout: [] 
INFO[0027] Removing container [file-deployer] on host [10.24.10.185], try rancher/rke#1 
INFO[0028] [remove/file-deployer] Successfully removed container on host [10.24.10.185] 
INFO[0028] [/etc/kubernetes/audit-policy.yaml] Successfully deployed audit policy file to Cluster control nodes 
INFO[0028] [reconcile] Reconciling cluster state        
INFO[0028] [reconcile] Check etcd hosts to be deleted   
INFO[0028] [reconcile] Check etcd hosts to be added     
INFO[0028] [reconcile] Rebuilding and updating local kube config 
INFO[0028] Successfully Deployed local admin kubeconfig at [./kube_config_rancher-cluster.yml] 
INFO[0028] [reconcile] host [10.24.10.194] is a control plane node with reachable Kubernetes API endpoint in the cluster 
INFO[0028] [reconcile] Reconciled cluster state successfully 
INFO[0028] max_unavailable_worker got rounded down to 0, resetting to 1 
INFO[0028] Setting maxUnavailable for worker nodes to: 1 
INFO[0028] Setting maxUnavailable for controlplane nodes to: 1 
INFO[0028] Pre-pulling kubernetes images                
INFO[0028] Image [rancher/hyperkube:v1.24.9-rancher1] exists on host [10.24.10.193] 
INFO[0028] Image [rancher/hyperkube:v1.24.9-rancher1] exists on host [10.24.10.185] 
INFO[0031] Image [rancher/hyperkube:v1.24.9-rancher1] exists on host [10.24.10.194] 
INFO[0031] Kubernetes images pulled successfully        
INFO[0031] [etcd] Building up etcd plane..              
INFO[0034] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.194] 
INFO[0039] Starting container [etcd-fix-perm] on host [10.24.10.194], try rancher/rke#1 
INFO[0041] Successfully started [etcd-fix-perm] container on host [10.24.10.194] 
INFO[0041] Waiting for [etcd-fix-perm] container to exit on host [10.24.10.194] 
INFO[0041] Waiting for [etcd-fix-perm] container to exit on host [10.24.10.194] 
INFO[0042] Removing container [etcd-fix-perm] on host [10.24.10.194], try rancher/rke#1 
INFO[0042] [remove/etcd-fix-perm] Successfully removed container on host [10.24.10.194] 
INFO[0042] [etcd] Running rolling snapshot container [etcd-snapshot-once] on host [10.24.10.194] 
INFO[0042] Removing container [etcd-rolling-snapshots] on host [10.24.10.194], try rancher/rke#1 
INFO[0044] [remove/etcd-rolling-snapshots] Successfully removed container on host [10.24.10.194] 
INFO[0045] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.194] 
INFO[0048] Starting container [etcd-rolling-snapshots] on host [10.24.10.194], try rancher/rke#1 
INFO[0050] [etcd] Successfully started [etcd-rolling-snapshots] container on host [10.24.10.194] 
INFO[0055] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.194] 
INFO[0058] Starting container [rke-bundle-cert] on host [10.24.10.194], try rancher/rke#1 
INFO[0062] [certificates] Successfully started [rke-bundle-cert] container on host [10.24.10.194] 
INFO[0062] Waiting for [rke-bundle-cert] container to exit on host [10.24.10.194] 
INFO[0063] Container [rke-bundle-cert] is still running on host [10.24.10.194]: stderr: [], stdout: [] 
INFO[0065] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [10.24.10.194] 
INFO[0065] Removing container [rke-bundle-cert] on host [10.24.10.194], try rancher/rke#1 
INFO[0066] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.194] 
INFO[0068] Starting container [rke-log-linker] on host [10.24.10.194], try rancher/rke#1 
INFO[0069] [etcd] Successfully started [rke-log-linker] container on host [10.24.10.194] 
INFO[0069] Removing container [rke-log-linker] on host [10.24.10.194], try rancher/rke#1 
INFO[0071] [remove/rke-log-linker] Successfully removed container on host [10.24.10.194] 
INFO[0072] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.194] 
INFO[0074] Starting container [rke-log-linker] on host [10.24.10.194], try rancher/rke#1 
INFO[0078] [etcd] Successfully started [rke-log-linker] container on host [10.24.10.194] 
INFO[0078] Removing container [rke-log-linker] on host [10.24.10.194], try rancher/rke#1 
INFO[0079] [remove/rke-log-linker] Successfully removed container on host [10.24.10.194] 
INFO[0079] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.193] 
INFO[0079] Starting container [etcd-fix-perm] on host [10.24.10.193], try rancher/rke#1 
INFO[0080] Successfully started [etcd-fix-perm] container on host [10.24.10.193] 
INFO[0080] Waiting for [etcd-fix-perm] container to exit on host [10.24.10.193] 
INFO[0080] Waiting for [etcd-fix-perm] container to exit on host [10.24.10.193] 
INFO[0080] Container [etcd-fix-perm] is still running on host [10.24.10.193]: stderr: [], stdout: [] 
INFO[0081] Removing container [etcd-fix-perm] on host [10.24.10.193], try rancher/rke#1 
INFO[0081] [remove/etcd-fix-perm] Successfully removed container on host [10.24.10.193] 
INFO[0081] [etcd] Running rolling snapshot container [etcd-snapshot-once] on host [10.24.10.193] 
INFO[0081] Removing container [etcd-rolling-snapshots] on host [10.24.10.193], try rancher/rke#1 
INFO[0082] [remove/etcd-rolling-snapshots] Successfully removed container on host [10.24.10.193] 
INFO[0082] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.193] 
INFO[0082] Starting container [etcd-rolling-snapshots] on host [10.24.10.193], try rancher/rke#1 
INFO[0082] [etcd] Successfully started [etcd-rolling-snapshots] container on host [10.24.10.193] 
INFO[0088] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.193] 
INFO[0089] Starting container [rke-bundle-cert] on host [10.24.10.193], try rancher/rke#1 
INFO[0089] [certificates] Successfully started [rke-bundle-cert] container on host [10.24.10.193] 
INFO[0089] Waiting for [rke-bundle-cert] container to exit on host [10.24.10.193] 
INFO[0089] Container [rke-bundle-cert] is still running on host [10.24.10.193]: stderr: [], stdout: [] 
INFO[0090] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [10.24.10.193] 
INFO[0090] Removing container [rke-bundle-cert] on host [10.24.10.193], try rancher/rke#1 
INFO[0091] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.193] 
INFO[0092] Starting container [rke-log-linker] on host [10.24.10.193], try rancher/rke#1 
INFO[0093] [etcd] Successfully started [rke-log-linker] container on host [10.24.10.193] 
INFO[0094] Removing container [rke-log-linker] on host [10.24.10.193], try rancher/rke#1 
INFO[0095] [remove/rke-log-linker] Successfully removed container on host [10.24.10.193] 
INFO[0095] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.193] 
INFO[0095] Starting container [rke-log-linker] on host [10.24.10.193], try rancher/rke#1 
INFO[0096] [etcd] Successfully started [rke-log-linker] container on host [10.24.10.193] 
INFO[0096] Removing container [rke-log-linker] on host [10.24.10.193], try rancher/rke#1 
INFO[0096] [remove/rke-log-linker] Successfully removed container on host [10.24.10.193] 
INFO[0097] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.185] 
INFO[0097] Starting container [etcd-fix-perm] on host [10.24.10.185], try rancher/rke#1 
INFO[0097] Successfully started [etcd-fix-perm] container on host [10.24.10.185] 
INFO[0097] Waiting for [etcd-fix-perm] container to exit on host [10.24.10.185] 
INFO[0097] Waiting for [etcd-fix-perm] container to exit on host [10.24.10.185] 
INFO[0097] Container [etcd-fix-perm] is still running on host [10.24.10.185]: stderr: [], stdout: [] 
INFO[0098] Removing container [etcd-fix-perm] on host [10.24.10.185], try rancher/rke#1 
INFO[0098] [remove/etcd-fix-perm] Successfully removed container on host [10.24.10.185] 
INFO[0098] [etcd] Running rolling snapshot container [etcd-snapshot-once] on host [10.24.10.185] 
INFO[0098] Removing container [etcd-rolling-snapshots] on host [10.24.10.185], try rancher/rke#1 
INFO[0099] [remove/etcd-rolling-snapshots] Successfully removed container on host [10.24.10.185] 
INFO[0099] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.185] 
INFO[0099] Starting container [etcd-rolling-snapshots] on host [10.24.10.185], try rancher/rke#1 
INFO[0099] [etcd] Successfully started [etcd-rolling-snapshots] container on host [10.24.10.185] 
INFO[0104] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.185] 
INFO[0105] Starting container [rke-bundle-cert] on host [10.24.10.185], try rancher/rke#1 
INFO[0106] [certificates] Successfully started [rke-bundle-cert] container on host [10.24.10.185] 
INFO[0106] Waiting for [rke-bundle-cert] container to exit on host [10.24.10.185] 
INFO[0106] Container [rke-bundle-cert] is still running on host [10.24.10.185]: stderr: [], stdout: [] 
INFO[0107] [certificates] successfully saved certificate bundle [/opt/rke/etcd-snapshots//pki.bundle.tar.gz] on host [10.24.10.185] 
INFO[0107] Removing container [rke-bundle-cert] on host [10.24.10.185], try rancher/rke#1 
INFO[0108] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.185] 
INFO[0110] Starting container [rke-log-linker] on host [10.24.10.185], try rancher/rke#1 
INFO[0111] [etcd] Successfully started [rke-log-linker] container on host [10.24.10.185] 
INFO[0111] Removing container [rke-log-linker] on host [10.24.10.185], try rancher/rke#1 
INFO[0111] [remove/rke-log-linker] Successfully removed container on host [10.24.10.185] 
INFO[0111] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.185] 
INFO[0112] Starting container [rke-log-linker] on host [10.24.10.185], try rancher/rke#1 
INFO[0112] [etcd] Successfully started [rke-log-linker] container on host [10.24.10.185] 
INFO[0112] Removing container [rke-log-linker] on host [10.24.10.185], try rancher/rke#1 
INFO[0113] [remove/rke-log-linker] Successfully removed container on host [10.24.10.185] 
INFO[0113] [etcd] Successfully started etcd plane.. Checking etcd cluster health 
INFO[0113] [etcd] etcd host [10.24.10.194] reported healthy=true 
INFO[0113] [controlplane] Now checking status of node 10.24.10.194, try rancher/rke#1 
INFO[0113] [controlplane] Now checking status of node 10.24.10.193, try rancher/rke#1 
INFO[0113] [controlplane] Now checking status of node 10.24.10.185, try rancher/rke#1 
INFO[0113] [controlplane] Processing controlplane hosts for upgrade 1 at a time 
INFO[0113] Processing controlplane host 10.24.10.194    
INFO[0113] [controlplane] Now checking status of node 10.24.10.194, try rancher/rke#1 
INFO[0113] [controlplane] Getting list of nodes for upgrade 
INFO[0116] Upgrade not required for controlplane and worker components of host 10.24.10.194 
INFO[0116] Processing controlplane host 10.24.10.193    
INFO[0116] [controlplane] Now checking status of node 10.24.10.193, try rancher/rke#1 
INFO[0116] [controlplane] Getting list of nodes for upgrade 
INFO[0119] Upgrade not required for controlplane and worker components of host 10.24.10.193 
INFO[0119] Processing controlplane host 10.24.10.185    
INFO[0119] [controlplane] Now checking status of node 10.24.10.185, try rancher/rke#1 
INFO[0119] [controlplane] Getting list of nodes for upgrade 
INFO[0119] Upgrade not required for controlplane and worker components of host 10.24.10.185 
INFO[0119] [controlplane] Successfully upgraded Controller Plane.. 
INFO[0119] [authz] Creating rke-job-deployer ServiceAccount 
INFO[0119] [authz] rke-job-deployer ServiceAccount created successfully 
INFO[0119] [authz] Creating system:node ClusterRoleBinding 
INFO[0119] [authz] system:node ClusterRoleBinding created successfully 
INFO[0119] [authz] Creating kube-apiserver proxy ClusterRole and ClusterRoleBinding 
INFO[0119] [authz] kube-apiserver proxy ClusterRole and ClusterRoleBinding created successfully 
INFO[0119] Successfully Deployed state file at [./rancher-cluster.rkestate] 
INFO[0119] [state] Saving full cluster state to Kubernetes 
INFO[0120] [state] Successfully Saved full cluster state to Kubernetes ConfigMap: full-cluster-state 
INFO[0120] [worker] Upgrading Worker Plane..            
INFO[0120] [worker] Successfully upgraded Worker Plane.. 
INFO[0120] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.193] 
INFO[0120] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.185] 
INFO[0120] Image [rancher/rke-tools:v0.1.88] exists on host [10.24.10.194] 
INFO[0120] Starting container [rke-log-cleaner] on host [10.24.10.185], try rancher/rke#1 
INFO[0120] Starting container [rke-log-cleaner] on host [10.24.10.193], try rancher/rke#1 
INFO[0121] [cleanup] Successfully started [rke-log-cleaner] container on host [10.24.10.185] 
INFO[0121] Removing container [rke-log-cleaner] on host [10.24.10.185], try rancher/rke#1 
INFO[0121] [cleanup] Successfully started [rke-log-cleaner] container on host [10.24.10.193] 
INFO[0121] Removing container [rke-log-cleaner] on host [10.24.10.193], try rancher/rke#1 
INFO[0121] [remove/rke-log-cleaner] Successfully removed container on host [10.24.10.185] 
INFO[0121] [remove/rke-log-cleaner] Successfully removed container on host [10.24.10.193] 
INFO[0124] Starting container [rke-log-cleaner] on host [10.24.10.194], try rancher/rke#1 
INFO[0127] [cleanup] Successfully started [rke-log-cleaner] container on host [10.24.10.194] 
INFO[0127] Removing container [rke-log-cleaner] on host [10.24.10.194], try rancher/rke#1 
INFO[0128] [remove/rke-log-cleaner] Successfully removed container on host [10.24.10.194] 
INFO[0128] [sync] Syncing nodes Labels and Taints       
INFO[0128] [sync] Successfully synced nodes Labels and Taints 
INFO[0128] [network] Setting up network plugin: canal   
INFO[0128] [addons] Saving ConfigMap for addon rke-network-plugin to Kubernetes 
INFO[0128] [addons] Successfully saved ConfigMap for addon rke-network-plugin to Kubernetes 
INFO[0128] [addons] Executing deploy job rke-network-plugin 
FATA[0178] Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system

**Comment by Nayanabvreddy** [comment]
Any updates on this??

**Comment by proligde** [comment]
I just hit an error on rancher 2.6.9, upgrade of a downstream k8s cluster from 1.21 to 1.22 where the upgrade ultimately fails with `Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system`.  The corresponding container died with `for: "/etc/config/rke-network-plugin.yaml": CustomResourceDefinition.apiextensions.k8s.io "ipamblocks.crd.projectcalico.org" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema`

Is my assumption correct, that this is the same problem as pointed out in the mentioned issues and is there a workaround? Patching the CRD doesn't help, as from my limited understanding, the issue originates from the template that rancher brings. Thanks a lot in advance for any hint into the right direction.

**Comment by rayandas** [comment]
Hi @proligde that's correct. The fix is already merged and it’ll be live in next release. 
There is a workaround provided by an user https://github.com/rancher/rancher/issues/40280#issuecomment-1412234569 you can try it out.

**Comment by proligde** [comment]
@rayandas awesome! that did the trick and saved my day - thanks so much!

**Comment by rishabhmsra** [comment]
Validated using rke `v1.4.3-rc7`

- Provisioned k8s v1.24.10-rancher3-1 cluster - 3 nodes all role.
- Cluster provisioned successfully with `rke-network-plugin-job` completing successfully.

Same issue with rancher is also tested and closed : https://github.com/rancher/rancher/issues/40485
