### ISSUE TITLE
Docker 1.12.6 doesn't work on LXC with rke

### ISSUE THREAD

**Issue by de13** [rancher/rke#317]
**RKE version:**

rke version v0.1.1-rc1

**Docker version: (`docker version`,`docker info` preferred)**

1.12.6-0~ubuntu-xenial

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

VERSION="16.04.3 LTS (Xenial Xerus)"
4.4.0-62-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

LXC

**cluster.yml file:**

**Steps to Reproduce:**

**Results:**

FATA[2585] [workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [u3]: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:89: jailing process inside rootfs caused \\\\\\\"pivot_root invalid argument\\\\\\\"\\\"\"\n"

**Comment by moelsayed** [comment]
LXC is not a virtualized environment. You can't directly run docker inside it.

**Comment by de13** [comment]
Are you serious? :) Of course yes, you can.

**Comment by moelsayed** [comment]
Not saying you can't period. :)

**Comment by superseb** [comment]
Please provide `docker info` output so we can investigate, as this seems to be related to the storage backend.
