### ISSUE TITLE
`rke remove` does not remove network pods

### ISSUE THREAD

**Issue by gtirloni** [rancher/rke#319]
**RKE version:**
0.1.0 and 0.1.1-rc1

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
libvirt/KVM VM

**cluster.yml file:**
```
nodes:
- address: 10.10.10.11
  role: [controlplane,etcd]
  user: deploy
- address: 10.10.10.12
  role: [controlplane,etcd]
  user: deploy
- address: 10.10.10.13
  role: [controlplane,etcd]
  user: deploy
- address: 10.10.10.14
  role: [worker]
  user: deploy
- address: 10.10.10.15
  role: [worker]
  user: deploy
- address: 10.10.10.16
  role: [worker]
  user: deploy
network:
  plugin: calico
```

**Steps to Reproduce:**
1. Run `rke remove`
2. Verify that calico pod still exists on the nodes

**Results:**
```
# docker ps | grep calico
6ddc67774ddc        quay.io/calico/cni@sha256:67df306d5f34ce44474ef2d24c9de884954aaf2e74c0a730b2e7fb6898522b72    "/install-cni.sh"        3 days ago          Up 3 days                               k8s_install-cni_calico-node-tqb8z_kube-system_1a41c31f-085f-11e8-94ba-020000000447_0
d137964e6dac        quay.io/calico/node@sha256:99bce1d4b4d02e0f3a0ab1c9383654f07ef0fe2dab950c59f6cad4fbbc63291c   "start_runit"            3 days ago          Up 3 days                               k8s_calico-node_calico-node-tqb8z_kube-system_1a41c31f-085f-11e8-94ba-020000000447_0
e5e05b60d3bb        gcr.io/google_containers/pause-amd64:3.0                                                      "/pause"                 3 days ago          Up 3 days                               k8s_POD_calico-node-tqb8z_kube-system_1a41c31f-085f-11e8-94ba-020000000447_0
```

**Comment by galal-hussein** [comment]
@gtirloni Yes rke doesn't remove pods at all, it just removes the k8s building blocks like kube-api, kubelet, etc. rke remove will also clean the dirs including network, etcd, certificate, which will lead to new kubernetes cluster whenever you decide to create new cluster using `rke up`

**Comment by gtirloni** [comment]
@galal-hussein thanks for the info. So it's not a problem, right? I have removed and recreated clusters with RKE many times so it seems to be fine.

**Comment by galal-hussein** [comment]
@gtirloni yes it shouldn't be a problem, kubernetes will automatically remove these old pods, closing this issue for now, please reopen if you have any questions, thanks!

**Comment by expelledboy** [comment]
How would one remove the pods created from `rke up`, given that I am using a docker engine with other deployments on it?
