### ISSUE TITLE
How does rke achieve high availability ?

### ISSUE THREAD

**Issue by misteruly** [rancher/rke#3199]
**RKE version:**
RKE version: v1.4.3

**Docker version: (`docker version`,`docker info` preferred)**
Version:          20.10.0
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"

How do you configure it ??

**Comment by MarUoneB** [comment]
RKE does nothing by itself , its the installer for kubernetes
