### ISSUE TITLE
Building RKE from sources

### ISSUE THREAD

**Issue by Shaggy-Fox** [rancher/rke#3245]
**RKE version:**
1.4

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~22.04.2
 Built:             Thu Mar  2 18:26:04 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~22.04.2
  Built:            Wed Feb 15 15:26:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12-0ubuntu1~22.04.1
  GitCommit:        
 runc:
  Version:          1.1.4-0ubuntu1~22.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy

5.15.0-69-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**cluster.yml file:**

**Steps to Reproduce:**
I'm trying to build RKE from sources. I've cloned RKE repo and followed readme instructions and run "make" command. CI pipe went ok till integration step. During integration step I've faced DNS problem with DinD containers and got a lot of output like 

time="2023-05-12T10:09:11Z" level=info msg="Initiating Kubernetes cluster"
time="2023-05-12T10:09:11Z" level=info msg="[dialer] Setup tunnel for host [172.17.0.3]"
time="2023-05-12T10:09:11Z" level=info msg="Finding container [cluster-state-deployer] on host [172.17.0.3], try rancher/rke#1"
time="2023-05-12T10:09:11Z" level=info msg="Pulling image [rancher/rke-tools:v0.1.89] on host [172.17.0.3], try rancher/rke#1"
time="2023-05-12T10:09:11Z" level=warning msg="Can't pull Docker image [rancher/rke-tools:v0.1.89] on host [172.17.0.3]: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:34402->127.0.0.53:53: read: connection refused"
time="2023-05-12T10:09:11Z" level=info msg="Pulling image [rancher/rke-tools:v0.1.89] on host [172.17.0.3], try rancher/rke#2"
time="2023-05-12T10:09:11Z" level=warning msg="Can't pull Docker image [rancher/rke-tools:v0.1.89] on host [172.17.0.3]: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:41344->127.0.0.53:53: read: connection refused"
time="2023-05-12T10:09:11Z" level=info msg="Pulling image [rancher/rke-tools:v0.1.89] on host [172.17.0.3], try rancher/rke#3"
time="2023-05-12T10:09:11Z" level=warning msg="Can't pull Docker image [rancher/rke-tools:v0.1.89] on host [172.17.0.3]: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:33362->127.0.0.53:53: read: connection refused"

**Results:**

2023-05-12T10:09:50Z ---- TEST RESULTS ----
2023-05-12T10:09:50Z [FAIL] v1.26.4-rancher2-1 (rke up)
2023-05-12T10:09:50Z [FAIL] v1.24.13-rancher2-1 (rke up)
2023-05-12T10:09:50Z [FAIL] v1.25.9-rancher2-1 (rke up)
2023-05-12T10:09:50Z [FAIL] v1.23.16-rancher2-2 (rke up)
2023-05-12T10:09:50Z [FAIL] One or more clusters failed to provision

2023-05-12T10:09:50Z ---- Clean Up RKE ----
FATA[0168] exit status 1                                
make: *** [Makefile:11: ci] Ошибка 1

What am I doing wrong and how is to be supposed to build RKE from sources?

**Comment by kinarashah** [comment]
@Shaggy-Fox Do you want to run these dind tests? A simpler way to build only RKE binary for developmental/debugging purposes would be to run `go generate; go build`.

**Comment by Shaggy-Fox** [comment]
Hi, thanks a lot for your answer!

You see, it's not what I want or not :) 

I had a task to build rke from sources, and I assumed that those dind tests step is mandatory part of CI pipeline. And this mandatory part simply doesn't work on my machine, and there's nothing in readme about it.

The readme states "run make and you'll be fine", which is not the case. And it's completely unclear to me how to make it work.

**Comment by superseb** [comment]
@Shaggy-Fox Can you share the contents of `/etc/resolv.conf`? It is probably running a DNS daemon like `systemd-resolved` or some other that points to a port on localhost which can be reached by the DinD containers. After changing that it should work.

I can look into fixing it in the code but I need the know what setup you have regarding the OS and DNS.
