### ISSUE TITLE
How to change kubelet path from '/var/lib/kubelet' to '/data/kubelet' ?

### ISSUE THREAD

**Issue by Nathan7512** [rancher/rke#3248]
**RKE version:**
v1.3.4
**Docker version: (`docker version`,`docker info` preferred)**
20.10.0
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 22.04.2
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**cluster.yml file:**

Can I change kubelet default path in the cluster.yaml?

**Comment by yangzinan** [comment]
I use the mount method to solve this problem
![image](https://github.com/rancher/rke/assets/12201941/4f8a00be-d929-4083-a549-38795780c720)

**Comment by superseb** [comment]
The path is currently hardcoded, see https://github.com/rancher/rke/blob/release/v1.4/cluster/plan.go#L474 and https://github.com/rancher/rke/blob/release/v1.4/cluster/plan.go#L570. This will require new code to allow for a different path to be configured and set at the right place(s)

We might be able to add another volume mount to the kubelet and override root-dir using `extra_args`

**Comment by Nathan7512** [comment]
Are there plans to support modification of the default /var/lib/kubelet path? Or we use an independent partition to mount the path to avoid the influence of other files on it.
