### ISSUE TITLE
Use v1.8.7-rancher1-1 as default version

### ISSUE THREAD

**Issue by moelsayed** [rancher/rke#325]

**Comment by HighwayofLife** [comment]
Out of curiosity, why use 1.8.x as the default rancher/k8s image instead of the 1.9.x line?

**Comment by deniseschannon** [comment]
@HighwayofLife Neither 1.6 or 2.0 are using k8s 1.9 yet. The impact of bumping from k8s 1.8 to 1.9 has some decent API changes that will impact 2.0. We plan on updating to the k8s 1.9 after 2.0 beta.

**Comment by deniseschannon** [comment]
@HighwayofLife We do have a k8s 1.9.x image available. But it hasn't been tested in RKE.  You're welcome to test it out if you dare:`k8s:v1.9.2-rancher1-1`

**Comment by HighwayofLife** [comment]
@deniseschannon 1.6 and 2.0 of what product?

FYI, I've been using the 1.9.x series of k8s images for the last few weeks.

**Comment by deniseschannon** [comment]
@HighwayofLife v1.6 and v2.0 of Rancher.

**Comment by moelsayed** [comment]
Tested with latest master. Without setting any version or image options RKE will default to use `rancher/k8s:v1.8.7-rancher1-1` as expected.
