### ISSUE TITLE
add support for docker 24.0.x to rke

### ISSUE THREAD

**Issue by konvergence** [rancher/rke#3259]
**RKE version:**
1.4 4

**Docker version: (`docker version`,`docker info` preferred)**
https://docs.docker.com/engine/release-notes/24.0/

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 20.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Vmware

**cluster.yml file:**

**Steps to Reproduce:**

**Results:**

**Comment by konvergence** [comment]
Please could you add support for docker 24.0.x ?


The first release 24.0.0 was released on 2023-05-16.
And there is ever to new patches . The last is 24.0.2 released on 2023-05-26

**Comment by immanuelfodor** [comment]
In the meantime, it works fine with `--ignore-docker-version`.

**Comment by kinarashah** [comment]
Tracking here https://github.com/rancher/rancher/issues/41851

**Comment by Sahota1225** [comment]
since the duplicate issue https://github.com/rancher/rancher/issues/41851 is closed, i m closing this issue.
