### ISSUE TITLE
[Question] Right way to deploy Calico in RKE

### ISSUE THREAD

**Issue by HectorB-2020** [rancher/rke#3290]
**RKE version**: `rke version v1.4.6`
**Docker version**: 20.10.24
**Operating system and kernel**: CentOS 7.9, 3.10.0-1160.el7.x86_64
**Type/provider of hosts**: QEMU/KVM on kernel 5.10.152
**Question:**
I've been studying documentation and stuck at the point where Calico is to be properly configured.
[Official Rancher documentation](https://rke.docs.rancher.com/config-options/add-ons/network-plugins) says that Calico has to be explicitly mentioned in `cluster.yml`. Such question is asked while running `rke config`.
```yaml
network:
  plugin: calico
```
Surprisingly Tigera's point of view in [their dedicated article "Rancher Kubernetes Engine (RKE)"](https://docs.tigera.io/calico/latest/getting-started/kubernetes/rancher) is different, they say literally:
_Configure your cluster with a [Cluster Config File](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#cluster-config-file) and specify [no network plugin](https://rancher.com/docs/rke/latest/en/config-options/add-ons/network-plugins/) by setting `plugin: none` under `network` in your configuration file._
Then they suggest installing Calico separately with a manifest:
```bash
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
```
Hence I'm wondering if any of these approaches have certain advantages and drawbacks.

**Comment by HectorB-2020** [comment]
Forgot to include a couple of issues found here. Who knows is this helps:
* https://github.com/rancher/rke/issues/2679
* https://github.com/rancher/rke/issues/1606
* https://github.com/rancher/rke/issues/2149

**Comment by manuelbuil** [comment]
Hey @HectorB-2020 sorry for the late reply. Both options are fine and most of the code is the same, however:
* We are only testing the former (using cluster.yml)
* The manifests related to that option include rke variables which make the installation of calico less manual and thus less error-prone. For example, things such as cluster-cidr

Therefore, I'd always select that option. Unless you want to use Calico Enterprise, the paying version from Tigera. In that case, you should use their manifests (but be careful with some paramters such as cluster-cidr)

**Comment by HectorB-2020** [comment]
Excellent, thanks very much!
