### ISSUE TITLE
kubernetes upgrade [Failed to start [kube-controller-manager] Error response from daemon: no such volume]

### ISSUE THREAD

**Issue by samene** [rancher/rke#3304]
**RKE version:** 1.4.3

**Docker version: (`docker version`,`docker info` preferred)** 20.10.14

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** RedHat Enterprise Linux 8.6

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**cluster.yml file:** NA (cluster created by terraform provider)

**Steps to Reproduce:**

1. Create RKE cluster either cli or terraform provider 1.23.6-rancher1-1
2. Upgrade the cluster to 1.23.10-rancher1-1
3. Erorr observed: 
```shell
"Can't start Docker container [kube-controller-manager] on host [10.148.20.209]: Error response from daemon: get 5c876d375046f4aad9745a621ab5b38b6b78141b79baeff1c23af472d95a2848: no such volume"

"Failed to upgrade hosts: 10.148.20.209 with error [Failed to start [kube-controller-manager] container on host [10.148.20.209]: Error response from daemon: get 5c876d375046f4aad9745a621ab5b38b6b78141b79baeff1c23af472d95a2848: no such volume]"
```

**Root cause:**
In this method - https://github.com/rancher/rke/blob/v1.4.3/services/controlplane.go#L321
```go
if err := runSidekick(ctx, host, prsMap, processMap[SidekickContainerName], k8sVersion); err != nil {
	return err
}
// run kubeapi
if err := runKubeAPI(ctx, host, localConnDialerFactory, prsMap, processMap[KubeAPIContainerName], alpineImage, certMap, k8sVersion); err != nil {
	return err
}
// run kubecontroller
if err := runKubeController(ctx, host, localConnDialerFactory, prsMap, processMap[KubeControllerContainerName], alpineImage, k8sVersion); err != nil {
	return err
}
// run scheduler
return runScheduler(ctx, host, localConnDialerFactory, prsMap, processMap[SchedulerContainerName], alpineImage, k8sVersion)
```
The Sidekick container is deleted and re-created with new rke-tools version. This deletes the existing volume shared by `kubelet`, `kube-controller-manager`, `kube-proxy` and `kube-scheduler`

https://github.com/rancher/rke/blob/release/v1.4.3/docker/docker.go#L370

After this the `kube-apiserver` is upgraded. But before the `kube-controller-manager` is upgraded it goes in error state (probably because of `kube-apiserver`) and tries to restart. However it fails to restart since the volume from the earlier sidekick container is gone.

Seeing the container stopped, this code - https://github.com/rancher/rke/blob/v1.4.3/docker/docker.go#L99

bypasses all conditions for upgrade

```go
// Check for upgrades
if container.State.Running {
	// check if container is in a restarting loop
	if container.State.Restarting {
		logrus.Debugf("[%s] Container [%s] is in a restarting loop [%s]", plane, containerName, hostname)
		err = RestartContainer(ctx, dClient, hostname, containerName)
		if err != nil {
			return err
		}
	}
	logrus.Debugf("[%s] Container [%s] is already running on host [%s]", plane, containerName, hostname)
	isUpgradable, err := IsContainerUpgradable(ctx, dClient, imageCfg, hostCfg, containerName, hostname, plane)
	if err != nil {
		return err
	}
	if isUpgradable {
		return DoRollingUpdateContainer(ctx, dClient, imageCfg, hostCfg, containerName, hostname, plane, prsMap)
	}
	return nil
}

// start if not running
logrus.Infof("[%s] Starting stopped container [%s] on host [%s]", plane, containerName, hostname)
if err := StartContainer(ctx, dClient, hostname, containerName); err != nil {
	return fmt.Errorf("Failed to start [%s] container on host [%s]: %v", containerName, hostname, err)
}
```

 and simply tries to start the stopped container (old version) giving this error since the volume is gone.

**Possible solutions:**

The container should upgrade even if it is stopped.
Not force delete the sidekick container's volume

**Comment by raelix** [comment]
I also hit this issue...Anyone is looking for a resolution?

**Comment by manuelbuil** [comment]
I'll try to have a look

**Comment by manuelbuil** [comment]
Could you provide the logs of `kube-controller-manager` when it goes into error state? I would like to verify that failing its connection to kube-apiserver is the problem

**Comment by manuelbuil** [comment]
@samene According to my investigations, the old volume is still around until all containers that are using it get removed. If I increase the [docker logs](https://docs.docker.com/config/daemon/logs/#enable-debugging), when removing kube-api, I can see the following:
```
26034-Aug 02 15:34:43 mbuil-vm0 dockerd[182188]: time="2023-08-02T15:34:43.581707808Z" level=debug msg="Calling GET /v1.41/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%7D%7D&limit=0"
26035-Aug 02 15:34:43 mbuil-vm0 dockerd[182188]: time="2023-08-02T15:34:43.594266154Z" level=debug msg="Calling GET /v1.41/containers/d9b301acb02a36de62f77af810fada75a4d999caced687e0aa2a5f5408420673/json"
26036:Aug 02 15:34:43 mbuil-vm0 dockerd[182188]: time="2023-08-02T15:34:43.629949984Z" level=debug msg="Calling DELETE /v1.41/containers/old-kube-apiserver?force=1&v=1"
26041-Aug 02 15:34:44 mbuil-vm0 dockerd[182188]: time="2023-08-02T15:34:44.585318959Z" level=debug msg="Calling GET /v1.41/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dpodsandbox%22%3Atrue%7D%7D&limit=0"
```
So even if the DELETE includes `v=1`, the volume does not get deleted. In fact, while doing the upgrade, I can see both volumes (old and new) being around when executing `docker volume ls`.

This changes for the last container using that volume which is kube-proxy:
```
27407-Aug 02 15:35:38 mbuil-vm0 dockerd[182188]: time="2023-08-02T15:35:38.963427561Z" level=debug msg="Calling GET /v1.41/containers/0b9112788e7e7963e6afcb6841f493f98343851cafa1e077c6e13c6d3552f676/json"
27408-Aug 02 15:35:39 mbuil-vm0 dockerd[182188]: time="2023-08-02T15:35:39.000879498Z" level=debug msg="Calling DELETE /v1.41/containers/old-kube-proxy?force=1&v=1"
27409:Aug 02 15:35:39 mbuil-vm0 dockerd[182188]: time="2023-08-02T15:35:39.068053544Z" level=debug msg="Removing volume reference: driver local, name dd585f9913dac808a2f9ab3219cff7d6bd5e89e5e098ab932987469c6840ac96"
```
There is a `DELETE` message for the volume. After that, the volume is removed and I can't see it anymore when executing `docker volume ls`.

We should check `kube-controller-manager` because maybe the error is related to something else. Could you please provide those logs?

**Comment by samene** [comment]
@manuelbuil Sure.. I can get the logs in a couple of days. But the volume belongs to the sidekick container. The other's only mount it. So the volume is deleted when the sidekick is upgraded, which happens when there is a newer rke-tools version.

https://github.com/rancher/rke/blob/release/v1.4/services/services.go#L85C2-L85C2

Do you have a rke-tools upgrade happening? Only then the volume will be deleted.

**Comment by manuelbuil** [comment]
> @manuelbuil Sure.. I can get the logs in a couple of days. But the volume belongs to the sidekick container. The other's only mount it. So the volume is deleted when the sidekick is upgraded, which happens when there is a newer rke-tools version.
> 
> https://github.com/rancher/rke/blob/release/v1.4/services/services.go#L85C2-L85C2
> 
> Do you have a rke-tools upgrade happening? Only then the volume will be deleted.

Yes, in my env rke-tools is changing versions. And the old volume is deleted at the end, when the last container using it gets deleted. 

Let me add more output, hopefully you could run the same commands.
If you check at the bottom (my output) you can see  `service-sidekick` is using volume `d660bfe6e1cd37d47b6e726a3e167777b50dc4c00a7c4579668380aa7ca2b940/`

That volume is shared with `kube-apiserver` and `kube-controller-manager` among others. Then, I start the upgrade by changing ` kubernetes_version` in cluster.yml and then run `rke up`.

As you can see, `service-sidekick` now uses another volume: `db4f24a54222d376806cbd14b4483f3197c09381b494d6979bd322a961725a95` but, as you can observe, if I execute `docker volume ls` I can see both volumes, the old and the new.

In fact, for a while, kube-controller-manager is still using the old one. As soon as it updates, it starts using the new one. When the upgrade is complete, I can see that the old volume disappeared from the list.

```
azureuser@mbuil-vm0:~$ docker inspect service-sidekick | grep volume
                "Type": "volume",
                "Source": "/var/lib/docker/volumes/d660bfe6e1cd37d47b6e726a3e167777b50dc4c00a7c4579668380aa7ca2b940/_data",
azureuser@mbuil-vm0:~$ docker inspect kube-controller-manager | grep volume
                "Type": "volume",
                "Source": "/var/lib/docker/volumes/d660bfe6e1cd37d47b6e726a3e167777b50dc4c00a7c4579668380aa7ca2b940/_data",
azureuser@mbuil-vm0:~$ docker inspect kube-apiserver | grep volume
                "Type": "volume",
                "Source": "/var/lib/docker/volumes/d660bfe6e1cd37d47b6e726a3e167777b50dc4c00a7c4579668380aa7ca2b940/_data",
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ #UPDATE HAPPENING#
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ docker inspect service-sidekick | grep volume
                "Type": "volume",
                "Source": "/var/lib/docker/volumes/db4f24a54222d376806cbd14b4483f3197c09381b494d6979bd322a961725a95/_data",
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ docker volume ls
DRIVER    VOLUME NAME
local     3605aa100aa14639eb49009a1ba42b2ff79dfc2b7024418842a5d987e1769416
local     d660bfe6e1cd37d47b6e726a3e167777b50dc4c00a7c4579668380aa7ca2b940
local     db4f24a54222d376806cbd14b4483f3197c09381b494d6979bd322a961725a95
local     ec3a3bab31d36baf444326c8f6071c912c1fef3a04a720b3a7b980776767bdb0
azureuser@mbuil-vm0:~$ docker volume ls
DRIVER    VOLUME NAME
local     3605aa100aa14639eb49009a1ba42b2ff79dfc2b7024418842a5d987e1769416
local     4526c14b66d0465a8b632ea8c7d9c7f11b0a1743e4801471dbdfaab060852b1a
local     d660bfe6e1cd37d47b6e726a3e167777b50dc4c00a7c4579668380aa7ca2b940
local     db4f24a54222d376806cbd14b4483f3197c09381b494d6979bd322a961725a95
local     ec3a3bab31d36baf444326c8f6071c912c1fef3a04a720b3a7b980776767bdb0
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ docker inspect kube-controller-manager | grep volume
                "Type": "volume",
                "Source": "/var/lib/docker/volumes/d660bfe6e1cd37d47b6e726a3e167777b50dc4c00a7c4579668380aa7ca2b940/_data",
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ docker inspect kube-controller-manager | grep volume
                "Type": "volume",
                "Source": "/var/lib/docker/volumes/db4f24a54222d376806cbd14b4483f3197c09381b494d6979bd322a961725a95/_data",
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ docker volume ls
DRIVER    VOLUME NAME
local     3605aa100aa14639eb49009a1ba42b2ff79dfc2b7024418842a5d987e1769416
local     d660bfe6e1cd37d47b6e726a3e167777b50dc4c00a7c4579668380aa7ca2b940
local     db4f24a54222d376806cbd14b4483f3197c09381b494d6979bd322a961725a95
local     ec3a3bab31d36baf444326c8f6071c912c1fef3a04a720b3a7b980776767bdb0
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ 
azureuser@mbuil-vm0:~$ docker volume ls
DRIVER    VOLUME NAME
local     3605aa100aa14639eb49009a1ba42b2ff79dfc2b7024418842a5d987e1769416
local     c393235fbf23a77012da9fea86208ca3025a19d4866febcff8b7d554e3bb959d
local     db4f24a54222d376806cbd14b4483f3197c09381b494d6979bd322a961725a95
local     ec3a3bab31d36baf444326c8f6071c912c1fef3a04a720b3a7b980776767bdb0
azureuser@mbuil-vm0:~$ 
```

**Comment by samene** [comment]
@manuelbuil , You're right. I checked the docker code too and it doesn't delete named volumes even if v=1 and f=1 (and its been like this since 5 years). I wonder what went wrong here. Let me try to reproduce this again with all the relevant logs. Thanks for your time though!
