### ISSUE TITLE
Question: How will RKE[1] support k8s >= 1.28

### ISSUE THREAD

**Issue by jhoblitt** [rancher/rke#3309]
k8s 1.27.x is the planned "end of the road" for canal.  See  https://kops.sigs.k8s.io/networking/canal/

Is rancher/rke planning to change the default cni? If so, what will be the new default cni and what is the planned migration procedure? Per the current k8s release cadence, 1.28 will be the oldest supported minor release is a bit less than a year.

**Comment by manuelbuil** [comment]
That's an announcement from k0ps, which is a k8s distribution. I haven't seen such announcement from Tigera, which is the company that maintains canal. There are no current plans in RKE to stop supporting canal

**Comment by manuelbuil** [comment]
I'll close the issue unless you have more questions, you can reopen it
