### ISSUE TITLE
Feature Request : Add a configuration parameter to override verbose logging level

### ISSUE THREAD

**Issue by hemanthavs** [rancher/rke#333]
Currently Verbose level is hard coded to --v=2.

During rke up, I come across a scenario some times kube-proxy failing to apply ip tables rules and logs of pods are not sufficient to identify the root cause.

Ticket Reference: https://github.com/rancher/rke/issues/329

Since no option to override, I will need to create the binary with required level 

It will be help during trouble shooting if rke provide a configuration parameter to cluster.yaml to override default verbose level 2..

**Comment by moelsayed** [comment]
You probably can use `extra_args` to do that:
```
kubeproxy:
  extra_args:
     v: 4
```
