### ISSUE TITLE
Kubernetes Dashboard CrashLoopBackOff

### ISSUE THREAD

**Issue by adalga** [rancher/rke#334]
**RKE version: 0.1.1

**Docker version: 

> Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

**Operating system:

> NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

kernel: 

> 3.10.0-693.17.1.el7.x86_64

**Type/provider of hosts: VMWare WorkStation

**cluster.yml file:**
[cluster.yml.txt](https://github.com/rancher/rke/files/1705939/cluster.yml.txt)

**Steps to Reproduce:

> ./rke up
cp kube_config_cluster.yml ~/.kube/config
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

**Results:

> Kubernetes dashboard container results in CrashLoopBackOff state. rke 0.1.0 works but all of the 0.1.1 versions cause this situation.

**Comment by adalga** [comment]
The logs of the dashboard pod is like below.

**kubectl logs kubernetes-dashboard-747d579ff5-h2mc5 --namespace=kube-system**
> 2018/02/09 06:19:03 Using in-cluster config to connect to apiserver
2018/02/09 06:19:03 Using service account token for csrf signing
2018/02/09 06:19:03 No request provided. Skipping authorization
2018/02/09 06:19:03 Starting overwatch
2018/02/09 06:19:04 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.233.0.1:443/version: dial tcp 10.233.0.1:443: getsockopt: no route to host
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ

**Comment by galal-hussein** [comment]
@adalga I am not able to reproduce with 0.1.1 or master, can you check the networking between pods to make sure that pods can ping each other on the different nodes, also can you post the logs of the following:
```
docker logs kube-api
docker logs kubelet
kubectl get nodes
kubectl get pods --all-namespaces
```

**Comment by adalga** [comment]
I tried 1 controlplane instead of 3 and it worked well. For HA I want to use 3 controlplane and I think there is a scheduler issue. Both 3 master try to schedule deployment and 2 of them fail and 1 of them succeeds. Should I create a new issue for this?

**Comment by HighwayofLife** [comment]
Yes, please create a new issue.
