### ISSUE TITLE
Failed to apply the ServiceAccount needed for job execution issue

### ISSUE THREAD

**Issue by MatheusDemoner** [rancher/rke#3341]
**RKE version:** 2.6.13

**Docker version:** curl https://releases.rancher.com/install-docker/20.10.sh | sh

**Operating system and kernel:** 
`
>        $OpenBSD: sshd_config,v 1.103 2018/04/09 20:41:22 tj Exp $
> 
>  This is the sshd server system-wide configuration file.  See
>  sshd_config(5) for more information.
> 
>  This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin
> 
>  The strategy used for options in the default sshd_config shipped with
>  OpenSSH is to specify options with their default value where
>  possible, but leave them commented.  Uncommented options override the
>  default value.
> 
> Include /etc/ssh/sshd_config.d/*.conf
> 
> Port 22
> AddressFamily any
> ListenAddress 0.0.0.0
> ListenAddress ::
> 
> HostKey /etc/ssh/ssh_host_rsa_key
> HostKey /etc/ssh/ssh_host_ecdsa_key
> HostKey /etc/ssh/ssh_host_ed25519_key
> 
>  Ciphers and keying
> RekeyLimit default none
> 
>  Logging
> SyslogFacility AUTH
> LogLevel INFO
> 
>  Authentication:
> 
> LoginGraceTime 2m
> PermitRootLogin yes
> StrictModes yes
> MaxAuthTries 6
> MaxSessions 10
> 
> PubkeyAuthentication yes
> 
>  Expect .ssh/authorized_keys2 to be disregarded by default in future.
> AuthorizedKeysFile     .ssh/authorized_keys .ssh/authorized_keys2
> 
> AuthorizedPrincipalsFile none
> 
> AuthorizedKeysCommand none
> AuthorizedKeysCommandUser nobody
> 
>  For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
> HostbasedAuthentication no
>  Change to yes if you don't trust ~/.ssh/known_hosts for
>  HostbasedAuthentication
> IgnoreUserKnownHosts no
>  Don't read the user's ~/.rhosts and ~/.shosts files
> IgnoreRhosts yes
> 
>  To disable tunneled clear text passwords, change to no here!
> PasswordAuthentication no
> PermitEmptyPasswords no
> 
>  Change to yes to enable challenge-response passwords (beware issues with
>  some PAM modules and threads)
> ChallengeResponseAuthentication no
> 
>  Kerberos options
> KerberosAuthentication no
> KerberosOrLocalPasswd yes
> KerberosTicketCleanup yes
> KerberosGetAFSToken no
> 
>  GSSAPI options
> GSSAPIAuthentication no
> GSSAPICleanupCredentials yes
> GSSAPIStrictAcceptorCheck yes
> GSSAPIKeyExchange no
> 
>  Set this to 'yes' to enable PAM authentication, account processing,
>  and session processing. If this is enabled, PAM authentication will
>  be allowed through the ChallengeResponseAuthentication and
>  PasswordAuthentication.  Depending on your PAM configuration,
>  PAM authentication via ChallengeResponseAuthentication may bypass
>  the setting of "PermitRootLogin without-password".
>  If you just want the PAM account and session checks to run without
>  PAM authentication, then enable this but set PasswordAuthentication
>  and ChallengeResponseAuthentication to 'no'.
> UsePAM yes
> 
> AllowAgentForwarding yes
> AllowTcpForwarding yes
> GatewayPorts no
> X11Forwarding yes
> X11DisplayOffset 10
> X11UseLocalhost yes
> PermitTTY yes
> PrintMotd no
> PrintLastLog yes
> TCPKeepAlive yes
> PermitUserEnvironment no
> Compression delayed
> ClientAliveInterval 0
> ClientAliveCountMax 3
> UseDNS no
> PidFile /var/run/sshd.pid
> MaxStartups 10:30:100
> PermitTunnel no
> ChrootDirectory none
> VersionAddendum none
> 
>  no default banner path
> Banner none
> 
>  Allow client to pass locale environment variables
> AcceptEnv LANG LC_*
> 
>  override default of no subsystems
> Subsystem       sftp    /usr/lib/openssh/sftp-server
> 
>  Example of overriding settings on a per-user basis
> Match User anoncvs
>        X11Forwarding no
>        AllowTcpForwarding yes
>        PermitTTY no
>        ForceCommand cvs server

`
**Type/provider of hosts:** Azure VM

cluster.yml file: 

>  If you intended to deploy Kubernetes in an air-gapped environment,
>  please consult the documentation on how to configure custom RKE images.
> nodes:
>   - address: 172.190.237.80
>     port: "22"
>     internal_address: 10.1.0.4
>     role: [controlplane, worker, etcd]
>     hostname_override: kube
>     user: aignosi
>     docker_socket: /var/run/docker.sock
>     ssh_key: ""
>     ssh_key_path: C:\Users\mathe\Downloads\key.pem
>     ssh_cert: ""
>     ssh_cert_path: ""
>     labels: {}
>     taints: []
> services:
>   etcd:
>     image: ""
>     extra_args: {}
>     extra_args_array: {}
>     extra_binds: []
>     extra_env: []
>     win_extra_args: {}
>     win_extra_args_array: {}
>     win_extra_binds: []
>     win_extra_env: []
>     external_urls: []
>     ca_cert: ""
>     cert: ""
>     key: ""
>     path: ""
>     uid: 0
>     gid: 0
>     snapshot: null
>     retention: ""
>     creation: ""
>     backup_config: null
>   kube-api:
>     image: ""
>     extra_args: {}
>     extra_args_array: {}
>     extra_binds: []
>     extra_env: []
>     win_extra_args: {}
>     win_extra_args_array: {}
>     win_extra_binds: []
>     win_extra_env: []
>     service_cluster_ip_range: 10.43.0.0/16
>     service_node_port_range: ""
>     pod_security_policy: false
>     pod_security_configuration: ""
>     always_pull_images: false
>     secrets_encryption_config: null
>     audit_log: null
>     admission_configuration: null
>     event_rate_limit: null
>   kube-controller:
>     image: ""
>     extra_args: {}
>     extra_args_array: {}
>     extra_binds: []
>     extra_env: []
>     win_extra_args: {}
>     win_extra_args_array: {}
>     win_extra_binds: []
>     win_extra_env: []
>     cluster_cidr: 10.42.0.0/16
>     service_cluster_ip_range: 10.43.0.0/16
>   scheduler:
>     image: ""
>     extra_args: {}
>     extra_args_array: {}
>     extra_binds: []
>     extra_env: []
>     win_extra_args: {}
>     win_extra_args_array: {}
>     win_extra_binds: []
>     win_extra_env: []
>   kubelet:
>     image: ""
>     extra_args: {}
>     extra_args_array: {}
>     extra_binds: []
>     extra_env: []
>     win_extra_args: {}
>     win_extra_args_array: {}
>     win_extra_binds: []
>     win_extra_env: []
>     cluster_domain: cluster.local
>     infra_container_image: ""
>     cluster_dns_server: 10.43.0.10
>     fail_swap_on: false
>     generate_serving_certificate: false
>   kubeproxy:
>     image: ""
>     extra_args: {}
>     extra_args_array: {}
>     extra_binds: []
>     extra_env: []
>     win_extra_args: {}
>     win_extra_args_array: {}
>     win_extra_binds: []
>     win_extra_env: []
> network:
>   plugin: calico
>   options: {}
>   mtu: 0
>   node_selector: {}
>   update_strategy: null
>   tolerations: []
> authentication:
>   strategy: x509
>   sans: []
>   webhook: null
> addons: ""
> addons_include: []
> system_images:
>   etcd: rancher/mirrored-coreos-etcd:v3.5.6
>   alpine: rancher/rke-tools:v0.1.89
>   nginx_proxy: rancher/rke-tools:v0.1.89
>   cert_downloader: rancher/rke-tools:v0.1.89
>   kubernetes_services_sidecar: rancher/rke-tools:v0.1.89
>   kubedns: rancher/mirrored-k8s-dns-kube-dns:1.22.20
>   dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.22.20
>   kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.22.20
>   kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.6
>   coredns: rancher/mirrored-coredns-coredns:1.9.4
>   coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:1.8.6
>   nodelocal: rancher/mirrored-k8s-dns-node-cache:1.22.20
>   kubernetes: rancher/hyperkube:v1.26.6-rancher1
>   flannel: rancher/mirrored-flannel-flannel:v0.21.4
>   flannel_cni: rancher/flannel-cni:v0.3.0-rancher8
>   calico_node: rancher/mirrored-calico-node:v3.25.0
>   calico_cni: rancher/calico-cni:v3.25.0-rancher1
>   calico_controllers: rancher/mirrored-calico-kube-controllers:v3.25.0
>   calico_ctl: rancher/mirrored-calico-ctl:v3.25.0
>   calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.25.0
>   canal_node: rancher/mirrored-calico-node:v3.25.0
>   canal_cni: rancher/calico-cni:v3.25.0-rancher1
>   canal_controllers: rancher/mirrored-calico-kube-controllers:v3.25.0
>   canal_flannel: rancher/mirrored-flannel-flannel:v0.21.4
>   canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.25.0
>   weave_node: weaveworks/weave-kube:2.8.1
>   weave_cni: weaveworks/weave-npc:2.8.1
>   pod_infra_container: rancher/mirrored-pause:3.7
>   ingress: rancher/nginx-ingress-controller:nginx-1.7.0-rancher1
>   ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
>   ingress_webhook: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
>   metrics_server: rancher/mirrored-metrics-server:v0.6.3
>   windows_pod_infra_container: rancher/mirrored-pause:3.7
>   aci_cni_deploy_container: noiro/cnideploy:5.2.7.1.81c2369
>   aci_host_container: noiro/aci-containers-host:5.2.7.1.81c2369
>   aci_opflex_container: noiro/opflex:5.2.7.1.81c2369
>   aci_mcast_container: noiro/opflex:5.2.7.1.81c2369
>   aci_ovs_container: noiro/openvswitch:5.2.7.1.81c2369
>   aci_controller_container: noiro/aci-containers-controller:5.2.7.1.81c2369
>   aci_gbp_server_container: noiro/gbp-server:5.2.7.1.81c2369
>   aci_opflex_server_container: noiro/opflex-server:5.2.7.1.81c2369
> ssh_key_path: ~/.ssh/id_rsa
> ssh_cert_path: ""
> ssh_agent_auth: false
> authorization:
>   mode: rbac
>   options: {}
> ignore_docker_version: null
> enable_cri_dockerd: null
> kubernetes_version: ""
> private_registries: []
> ingress:
>   provider: ""
>   options: {}
>   node_selector: {}
>   extra_args: {}
>   dns_policy: ""
>   extra_envs: []
>   extra_volumes: []
>   extra_volume_mounts: []
>   update_strategy: null
>   http_port: 0
>   https_port: 0
>   network_mode: ""
>   tolerations: []
>   default_backend: null
>   default_http_backend_priority_class_name: ""
>   nginx_ingress_controller_priority_class_name: ""
>   default_ingress_class: null
> cluster_name: ""
> cloud_provider:
>   name: ""
> prefix_path: ""
> win_prefix_path: ""
> addon_job_timeout: 0
> bastion_host:
>   address: ""
>   port: ""
>   user: ""
>   ssh_key: ""
>   ssh_key_path: ""
>   ssh_cert: ""
>   ssh_cert_path: ""
>   ignore_proxy_env_vars: false
> monitoring:
>   provider: ""
>   options: {}
>   node_selector: {}
>   update_strategy: null
>   replicas: null
>   tolerations: []
>   metrics_server_priority_class_name: ""
> restore:
>   restore: false
>   snapshot_name: ""
> rotate_encryption_key: false
> dns: null
> 

**Steps to Reproduce:** rke up

**Results:**

> time="2023-08-22T11:46:10-03:00" level=info msg="[controlplane] Successfully started Controller Plane.."
> time="2023-08-22T11:46:10-03:00" level=info msg="[authz] Creating rke-job-deployer ServiceAccount"
> time="2023-08-22T11:48:20-03:00" level=fatal msg="Failed to apply the ServiceAccount needed for job execution: Post \"https://xxx.xxx.237.80:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?timeout=30s\": dial tcp xxx.xxx.237.80:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

**Comment by superseb** [comment]
Are you using RKE CLI or Rancher? Did you verify that the host running `rke up` or the container running Rancher can reach that address? How does the logging look on the `kube-apiserver` container on that node?

**Comment by Venture200** [comment]
msg="[authz] Creating rke-job-deployer ServiceAccount"
│
│ Failed running cluster err:Failed to apply the ServiceAccount needed for job execution: Post "https://x.x.x.x:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs instead


@superseb could you please have a look for this too ? Terraform rke_cluster provider is used.

**Comment by superseb** [comment]
@Venture200 Although this is the same error as in `Failed to apply the ServiceAccount needed for job execution`, the actual error is different. Can you file a new issue with environment details/steps to reproduce etc?

**Comment by Venture200** [comment]
@superseb I am using terraform rke_cluster provider to build up, is it relevant to file this issue in rancher community or I should direct it to terraform ?

**Comment by superseb** [comment]
File it here please https://github.com/rancher/rke/issues/new, I can always transfer it if it is a Terraform provider specific issue but this comes from RKE itself. Please specify the versions used so we know what you are using.
