### ISSUE TITLE
[QA] Test `rancher/rke-tools:v0.1.91`

### ISSUE THREAD

**Issue by pjbgf** [rancher/rke#3367]
Issue to track the testing of recent changes originating from https://github.com/rancher/rke-tools/pull/161.

**Comment by snasovich** [comment]
Closing the issue as the testing for these bumps is part of testing k8s versions introduced in September 2023 patches, see https://github.com/rancher/rancher/issues/42813. If any regressions attributed to version bumps are found, they will be filed separately.
