### ISSUE TITLE
Pods getting the same ip address

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rke#338]
**RKE version:**
v0.1.1

**Docker version: (`docker version`,`docker info` preferred)**
docker 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu-16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**cluster.yml file:**
three node cluster,each node with a single role. so one node -controlplane, node - worker, node -etcd

**Steps to Reproduce:**
Create a cluster and then update the rancher service k8s service image

**Results:**
The kubedns and test pods can get the same ip:

```
kubectl get pods --all-namespaces -o wide | grep 10.233.66.4
kube-system                   kube-dns-6f7666d48c-6bwxn               3/3       Running   0          10h       10.233.66.4      18.219.114.84
nsone-afterupgrade            pod-test-util-xb2f6                     1/1       Running   0          10h       10.233.66.4      18.219.114.84
```

```
AssertionError: Service ClusterIP does not reach pods k8test1.nsone-afterupgrade.svc.cluster.local:
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
curl: (7) Failed to connect to k8test1.nsone-afterupgrade.svc.cluster.local port 80: Connection refused
command terminated with exit code 7
```

https://github.com/kubernetes/kubernetes/issues/43910#issuecomment-290777514

**Comment by moelsayed** [comment]
Confirmed fix with latest master:
- created 3 node cluster, 1 role each, with `rancher/k8s:v1.8.5-rancher3`
- updated the cluster to `rancher/k8s:v1.8.7-rancher1-1`
- checked pod IPs
- repeated several times.
