### ISSUE TITLE
[Forward-port] On cgroup v2 systems, a restart of kubelet container triggers a restart of all pods on the node

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke#3391]
This is the forward-port issue for https://github.com/rancher/rke/issues/3280

**Comment by jiaqiluo** [comment]
The fix is available since `rke-tools` v0.1.92, so any k8s version that uses the `rke-tools` image whose tag is v0.1.92 and higher should have the fix.

**Comment by jiaqiluo** [comment]
We will need to update the KDM data after https://github.com/rancher/kontainer-driver-metadata/pull/1235 is merged.

**Comment by jiaqiluo** [comment]
can be validated in RKE v1.5.0-rc8 https://github.com/rancher/rke/releases/tag/v1.5.0-rc8

**Comment by Josh-Diamond** [comment]
Ticket #3391 - Test Results - ✅ 
---

Reproduced w/ RKE `v1.4.8` and k8s `v1.24.8-rancher1-1`:
1. Using RKE `v1.4.8`, spin up a single-node cluster using k8s `v1.24.8-rancher1-1`
2. Once `active`, ssh into the node and run `docker restart kubelet`
3. Reproduced - containers w/ prefix `k8s_POD_` are restarted; unexpected behavior

---

Verifed w/ RKE `v1.5.0-rc8` and k8s `v1.27.6-rancher1-1`:
1. Using RKE `v1.5.0-rc8`, spin up a single-node cluster using k8s `v1.27.6-rancher1-1`
2. Once `active`, ssh into the node and run `docker restart kubelet`
3. Verified - only kubelet is restarted; as expected
