### ISSUE TITLE
Reduce Drone CI time/resources

### ISSUE THREAD

**Issue by superseb** [rancher/rke#3396]
We need to optimize Drone CI for this repository as it takes too long to do certain things:

- When there are no code changes or anything changes that Drone needs to check, we need to skip/complete the run immediately.
- On release, we don't need to run the full CI suite as it should already have been checked after the last merge/RC. This should speed up making releases.

**Comment by cwayne18** [comment]
We have some prior art that we can re-use here from `rancher/rke2`:
https://github.com/rancher/rke2/blob/0f71c9a47b030bf152d541db52e85f05e2473ced/.drone.yml#L14
https://github.com/rancher/rke2/blob/master/.droneignore

**Comment by jiaqiluo** [comment]
The linked issue PR has been merged, and a few releases have been done since then, so it is safe to call it done and close the issue.
