### ISSUE TITLE
QUESTION: Will rke support k8s 1.27.x and above?

### ISSUE THREAD

**Issue by danielehq** [rancher/rke#3419]
**RKE version:**
1.27.x, 1.28.x

Will rke support k8s 1.27.x and above?
and is there any ETA ? 

Thank you.

**Comment by superseb** [comment]
See the supported k8s versions in the latest RC: https://github.com/rancher/rke/releases/tag/v1.5.0-rc9

You can follow the issue in `rancher/rancher` to see progress https://github.com/rancher/rancher/issues/41840 && https://github.com/rancher/rancher/issues/43109
