### ISSUE TITLE
Rancher 2.7.6 with downstream cluster RKE 1.24.17 need to update rke-tools to v0.1.92

### ISSUE THREAD

**Issue by cstisa** [rancher/rke#3426]
Dear all,

I have deployed a cluster RKE1 downstream cluster with 3 nodes using v1.24.17-rancher1-1 kubernetes version
since this version it use the cri-dockerd in replacement of the traditional dockershim support , but since i have issues with IPv4 /IPv6 DualStack, the system image used rke-tools by the cluster is the version 0.1.90 (rancher/rke-tools:v0.1.90), which is not including the fix 
https://github.com/rancher/rke-tools/pull/163 to cri-dockerd on the bubelet container 

How can i get this fix ? 
Do i have to ovveride system images to include rancher/rke-tools:v0.1.92 or is there any other best practice ?

Sorry to bother you about this is there some documentation i missed or if this is not the place to raise this kind od demands.

**RKE version:**
RKE1

**Docker version: (`docker version`,`docker info` preferred)**

Client: Docker Engine - Community
 Version:    24.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 296
  Running: 230
  Paused: 0
  Stopped: 66
 Images: 177
 Server Version: 24.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-148-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 251.3GiB
 Name: node1
 ID: c1101712-adfe-4399-a48d-df13238037db
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**cluster.yml file:**

answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
fleet_workspace_name: fleet-default
local_cluster_auth_endpoint:
  enabled: true
name: sh1
rancher_kubernetes_engine_config:
  addon_job_timeout: 45
  authentication:
    strategy: x509|webhook
  authorization: {}
  bastion_host:
    ignore_proxy_env_vars: false
    ssh_agent_auth: false
  cloud_provider: {}
  dns:
    linear_autoscaler_params:
      cores_per_replica: 128
      max: 0
      min: 1
      nodes_per_replica: 4
      prevent_single_point_failure: true
    node_selector: null
    nodelocal:
      node_selector: null
      update_strategy:
        rolling_update: {}
    options: null
    provider: coredns
    reversecidrs: null
    stubdomains: null
    tolerations: null
    update_strategy:
      rolling_update: {}
    upstreamnameservers:
      - xxx.xxx.xxx.171
      - xxx.xxx.xxx.172
      - '2a02:xxxx:0:1::171'
      - '2a02:xxxx:0:1::172'
  enable_cri_dockerd: true
  ignore_docker_version: true
  ingress:
    default_backend: false
    default_ingress_class: true
    http_port: 0
    https_port: 0
    provider: none
  kubernetes_version: v1.24.17-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1
  network:
    mtu: 0
    plugin: calico
  restore:
    restore: false
  rotate_encryption_key: false
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
        timeout: 300
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      extra_args:
        feature-gates: IPv6DualStack=true
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_cluster_ip_range: '10.21.0.0/16,2a0b:xxxx:0:8::/108'
      service_node_port_range: 30000-32767
    kube-controller:
      cluster_cidr: '10.20.0.0/16,2a0b:xxxx:0:7::/64'
      extra_args:
        feature-gates: IPv6DualStack=true
      service_cluster_ip_range: '10.21.0.0/16,2a0b:xxxx:0:8::/108'
    kubelet:
      cluster_dns_server: 10.21.0.10
      cluster_domain: cluster.local
      extra_args:
        feature-gates: IPv6DualStack=true
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy:
      extra_args:
        feature-gates: IPv6DualStack=true
    scheduler: {}
  ssh_agent_auth: false
  upgrade_strategy:
    drain: true
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: true
      force: true
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 300

Thank a lot for the support.

Best Regards,

**Comment by manuelbuil** [comment]
rke-tools was updated to v0.1.96 in RKE release `v1.4.11`: https://github.com/rancher/rke/releases/tag/v1.4.11. Which means versions:
```
v1.26.9-rancher1-1 (Default)
v1.25.14-rancher1-1
v1.24.17-rancher1-1
v1.23.16-rancher2-3
```
Rancher 2.7.6 does not include that yet. You should move to a newer rancher version
