### ISSUE TITLE
etcd-rolling-snapshots container image does not match the k8s version being installed

### ISSUE THREAD

**Issue by samene** [rancher/rke#3431]
**RKE version:** 1.4.10 (but affects all versions)

**Setup:**

We have Rancher 2.7.8 installed, using which we are creating RKE1 cluster with k8s version v1.23.10-rancher1-1

Rancher 2.7.8 embeds rke 1.4.10, which has its `data.json` entry for 1.23.10-rancher1-1 as below

```
  "v1.23.10-rancher1-1": {
   "etcd": "rancher/mirrored-coreos-etcd:v3.5.3",
   "alpine": "rancher/rke-tools:v0.1.87",
   "nginxProxy": "rancher/rke-tools:v0.1.87",
   . . .
   . . .
  }
```

Note the alpine version here is `rancher/rke-tools:v0.1.87`

**Observation**: When creating the cluster (with 3 control plane, etcd nodes), the etcd-rolling-snapshot container starts and it tries to use `rancher/rke-tools:v0.1.90`

This is because the rolling snapshot container uses the image from the `RKEDefaultK8sVersions` and not the one from the version being installed.

in `etcd.go` https://github.com/rancher/rke/blob/v1.4.10/cluster/etcd.go#L276

```go
func (c *Cluster) getBackupImage() string {
	rkeToolsImage, err := util.GetDefaultRKETools(c.SystemImages.Alpine)
	if err != nil {
		logrus.Errorf("[etcd] error getting backup image %v", err)
		return ""
	}
	logrus.Debugf("[etcd] Image used for etcd snapshot is: [%s]", rkeToolsImage)
	return rkeToolsImage
}
```

and the defaultVersion in rke 1.4.10 is 
```
 "RKEDefaultK8sVersions": {
  "0.3": "v1.16.3-rancher1-1",
  "default": "v1.26.8-rancher1-1"
 },
```

and so it ends up with `rancher/rke-tools:v0.1.90` which is the alpine image for 1.26.8-rancher1-1

```
  "v1.26.8-rancher1-1": {
   "etcd": "rancher/mirrored-coreos-etcd:v3.5.6",
   "alpine": "rancher/rke-tools:v0.1.90",
   "nginxProxy": "rancher/rke-tools:v0.1.90",
   "certDownloader": "rancher/rke-tools:v0.1.90",
  . . .
  . . .
```

**Expected:**:

The etcd-rolling-snapshot container should use the image that matches the kubernetes version being installed and not the default kubernetes version for that rke.

**Comment by superseb** [comment]
Currently this is intentional, see https://github.com/rancher/rke/issues/3029 and referenced commit https://github.com/rancher/rke/commit/217e1b41b8fe0ffc362f75ab7bfd71e644d101f3.

Is there an issue with this logic, do snapshots not get create/not able to restart or are there errors seen?
