### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by a-blender** [rancher/rke#3442]
Per discussion with @manuelbuil https://github.com/rancher/rke/pull/3415#discussion_r1401770879, we'd like to add a PR Template to rancher/rke repo for devs and other contributors.

**RKE version:**

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**

**Results:**

**Comment by manuelbuil** [comment]
Being part of https://github.com/rancher/rke/pull/3415
