### ISSUE TITLE
[BUG] etcd snapshot-save --s3 is not working

### ISSUE THREAD

**Issue by bitfisher** [rancher/rke#3452]
**RKE version:**
`rke version v1.4.11` and `rke version v1.5.0`

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 211
  Running: 152
  Paused: 0
  Stopped: 59
 Images: 276
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: builtin
  selinux
  cgroupns
 Kernel Version: 6.5.11-300.fc39.x86_64
 Operating System: Fedora CoreOS 39.20231119.3.0
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.65GiB
 Name: node-01
 ID: cdbbfe3c-85ce-47ef-acdb-804680d5f863
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`6.5.11-300.fc39.x86_64`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`Bare-metal`

**cluster.yml file:**

**Steps to Reproduce:**
`rke --debug etcd snapshot-save --ignore-docker-version --s3 --s3-endpoint minio-fqdn --bucket-name rke-backup --folder etcd --access-key XXX --secret-key XXX --name test`

**Results:**
```
WARN[0038] [etcd] Failed to take snapshot on all etcd hosts: failed to take one-time snapshot on host [x.x.x.x], exit code [1]: time="2023-12-11T14:39:39Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:rke-backup, err:Access Denied." 
FATA[0038] [etcd] Failed to take snapshot on all etcd hosts: failed to take one-time snapshot on host [x.x.x.x], exit code [1]: time="2023-12-11T14:39:39Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:rke-backup, err:Access Denied." 
```

---

same with rke v1.5.0!

---

testing backup using `rke-etcd-backup` inside `etcd-rolling-snapshots` container gives some more insights ...
`/opt/rke-tools/rke-etcd-backup etcd-backup save --cacert /etc/kubernetes/ssl/kube-ca.pem --cert /etc/kubernetes/ssl/kube-node.pem --key /etc/kubernetes/ssl/kube-node-key.pem --name test --endpoints=x.x.x.x:2379 --once --creation=6h --retention=72h --s3-backup=true --s3-endpoint=minio-fqdn --s3-bucketName=rke-backup --s3-folder=etcd --s3-accessKey XXX --s3-secretKey XXX
`

results in 

```
INFO[0000] Initializing Onetime Backup                   name="test"
INFO[0011] Created local backup                          name="test" runtime=5.405814866s
INFO[0011] invoking set s3 service client                s3-accessKey="XXX" s3-bucketName=rke-backup s3-endpoint=minio-fqdn s3-endpoint-ca= s3-folder=etcd s3-region=
ERRO[0011] failed to set s3 server: failed to check s3 bucket:rke-backup, err:Get "https://minio-fqdn/rke-backup/?location=": net/http: invalid header field value for "Authorization"  s3-accessKey="XXX" s3-bucketName=rke-backup s3-endpoint=minio-fqdn s3-endpoint-ca= s3-folder=etcd s3-region=
FATA[0011] failed to set s3 server: failed to check s3 bucket:rke-backup, err:Get "https://minio-fqdn/rke-backup/?location=": net/http: invalid header field value for "Authorization" 
```

---

taking local snapshot and push it manually to s3 using s3cmd/s5cmd with same endpoint, folder and credentials works as expected!

**Comment by jakefhyde** [comment]
@bitfisher Thank you for filing, is this an s3 bucket, minio bucket, or some other s3 compatible endpoint? This will potentially help us reproduce, as we usually verify both s3 and minio buckets for validation.

**Comment by bitfisher** [comment]
It's a minio bucket. 
minio (2023-02-10T18:48:39Z) is running on a NAS.
The bucket (with same credentials) is used by other systems as well (different folders) without any problems.

**Comment by bitfisher** [comment]
Sorry, seems like our admin messed things up here :(
