### ISSUE TITLE
ACI CNI 6.0.3.1 changes for RKE1 v1.5.x

### ISSUE THREAD

**Issue by snasovich** [rancher/rke#3465]
**RKE version:** v1.5.1

**Docker version: (`docker version`,`docker info` preferred)** N/A

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** N/A

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** N/A

**cluster.yml file:** N/A

ACI CNI changes for version 6.0.3.1 are missing from v1.5.0/v1.5.1 RKE1 releases due to timing of when `release/v1.5` branch was created and https://github.com/rancher/rancher/issues/42568 merged.

This issue is to track properly forwardporting these changes to `release/v1.5` branch.

Note: Per checks done by @kinarashah these are the only relevant v1.4.x changes that didn't make it into 1.5.x release.

**Comment by jiaqiluo** [comment]
The fix can be validated in [RKE v1.5.2-rc1](https://github.com/rancher/rke/releases/tag/v1.5.2-rc1)

**Comment by Josh-Diamond** [comment]
Validated by Cisco team -- closing this out now
