### ISSUE TITLE
Deployment is already assigned to node

### ISSUE THREAD

**Issue by adalga** [rancher/rke#350]
**RKE version: 0.1.1

**Docker version: 17.03.2-ce

**Operating system and kernel: Ubuntu 16.04 - 4.10.0-28-generic

**Type/provider of hosts: VMWare

**cluster.yml file:** 

> [cluster.yml.txt](https://github.com/rancher/rke/files/1722771/cluster.yml.txt)

**Steps to Reproduce: 

> ./rke up
Create any deployment. I tried below.
[deployment.yaml.txt](https://github.com/rancher/rke/files/1722775/deployment.yaml.txt)

**Results:**

> Binding rejected: Operation cannot be fulfilled on pods/binding "nginx-deployment-569477d6d8-2zr7l": pod nginx-deployment-569477d6d8-2zr7l is already assigned to node "192.168.112.152"

I think both 3 of master tries to schedule deployment on same node and one of them succeeds. The other ones cause these error.

**Comment by galal-hussein** [comment]
@adalga I am not able to reproduce this problem, where do you see this error exactly?

**Comment by adalga** [comment]
I tried to create a basic deployment via this yaml below.

> [nginx-deployment.yaml.txt](https://github.com/rancher/rke/files/1750774/nginx-deployment.yaml.txt)

Thne there is an error logged like below. 

![capture](https://user-images.githubusercontent.com/13197483/36583017-d9ef3566-1884-11e8-885b-84d130ec12c1.JPG)

**Comment by moelsayed** [comment]
@adalga This might be related to resources on the nodes.If you can still reproduce this, can you please share the output of `kubectl describe pod` for this pod.
