### ISSUE TITLE
with latest kernel version the worker node DNS is not working

### ISSUE THREAD

**Issue by Gopi876** [rancher/rke#3518]
I am am using the rhel 8.8 with older kernel 4.18.0-193.6.3.el8_2.x86_64.As part of patching when i upgrade the kernel in one of the worker node the DNS is not working and all pods are in that node getting the BackOff restarting failing container

**Comment by nikos445** [comment]
Any solution?
Same problem here. Rhel8.9 and 4.18.0-513.24.1.el8_9.x86_64
