### ISSUE TITLE
Calico versions and other CNI version info? Where?

### ISSUE THREAD

**Issue by BloodyIron** [rancher/rke#3555]
I can't for the life of me figure out where RKE1 documentation exists that outlines which versions of CNIs, such as Calico, are used by which versions of RKE1. And I can't seem to figure it out from the code really.

Where is this information kept? I really need to reference it. Thanks!

**Comment by BloodyIron** [comment]
Seriously there's no resources on this information? This seems like a pretty substantial oversight for Documentation...

**Comment by manuelbuil** [comment]
I'm an RKE2 developer, so maybe I'm wrong, but if I remember correctly, I normally check versions with `rke config --list-version --all`

**Comment by pgonin** [comment]
Have you considered RKE2 instead of RKE?
https://docs.rke2.io/networking/basic_network_options

**Comment by BloodyIron** [comment]
> Have you considered RKE2 instead of RKE? https://docs.rke2.io/networking/basic_network_options

I would rather have documentation for the tech I'm using instead of just switching tech. I tried RKE2 previously and had issues with it, I don't recall this moment what they were. But my ask is completely reasonable. RKE2 has this aspect documented, where's the same for RKE1?

**Comment by BloodyIron** [comment]
> I'm an RKE2 developer, so maybe I'm wrong, but if I remember correctly, I normally check versions with `rke config --list-version --all`

I want to know the versions _before_ I switch so that I know what targets to aim for. I can't check for a version _I'm not running_. I can check the versions of the running calico pods just fine, that's not what I'm asking for. I'm asking for documentation that outlines the expected CNI versions (in my case Calico) that are used by the different RKE1 versions. Asking for documentation of this (which is present for RKE2, but I'm using RKE1 and am not interested in switching at this time) is perfectly reasonable.

**Comment by xcezz** [comment]
Are you looking for https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.8/pkg/rke/k8s_rke_system_images.go?

Source: https://rke.docs.rancher.com/config-options/system-images

**Comment by BloodyIron** [comment]
> Are you looking for https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.8/pkg/rke/k8s_rke_system_images.go?
> 
> Source: https://rke.docs.rancher.com/config-options/system-images

Neither of those sources of information are updated, accurate, or even easy to find. While that is topically relevant, that's really not a proper solution to the absence that exists.

**Comment by BloodyIron** [comment]
THIS IS NOT COMPLETED.
