### ISSUE TITLE
RKE should have a dry-run option

### ISSUE THREAD

**Issue by iohenkies** [rancher/rke#3567]
RKE should have a dry-run option that will analyze the state of the currently deployed cluster and determine what changes RKE will make when rke up is run.

This would allow much more fine-grained control over the management of RKE-managed kubernetes clusters and allow operators to gain more insight into potential "what went wrongs" if issues occur during an rke up rather than figuring this out during runtime.

The output of rke dry-run should likely be similar to what you would receive when doing a terraform plan.

See https://github.com/rancher/rke/issues/1063

**Comment by fmcwalters-edited** [comment]
bump

**Comment by son-la** [comment]
I doubt that it will ever happen. It has been 6 years...
