### ISSUE TITLE
Errors while removing an etcd member can cause RKE to try to remove the member indefinitely

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rke#3570]
**RKE version:** v1.4.10

**Steps to Reproduce:**
- Provision a cluster with 3 etcd members
- Using `etcdctl`, remove a member and then attempt to remove the etcd node from RKE

**Results:**
RKE will continuously attempt to remove the etcd member with the following errors:

```
{"level":"warn","ts":"2024-02-07T09:42:15.024Z","logger":"etcd-client","caller":"v3@v3.5.4/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x<hex>/<ip>:2379","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: member not found"}

[ERROR] cluster [c-xxxxx] provisioning: [reconcile] Failed to delete etcd member [hostname] from etcd cluster
```

This can also happen if when an etcd member remove is issued via RKE, which succeeds however an error may be returned if the request is not completed in time, the connection is dropped, or some other issue occurs.

RKE1 should confirm the etcd member exists before aatempting to delete it.

SURE-7601

**Comment by jakefhyde** [comment]
Blocked, waiting for RKE1 1.6 rc.

**Comment by snasovich** [comment]
Closing as tracking `rancher/rancher` issue got validated - https://github.com/rancher/rancher/issues/45309#issuecomment-2181502432
