### ISSUE TITLE
[Backport] Provisionning fails with RKE 1.5.9 when extra_env is used for kube-api service 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rke#3596]
This issue is the backport of https://github.com/rancher/rke/issues/3587
Please check the original issue for details 

The corresponding Rancher issue: https://github.com/rancher/rancher/issues/45656

**Comment by jiaqiluo** [comment]
Waiting for cutting a new RC from the release/v1.5 branch, which will happen after releasing v1.5.10 if my understanding is correct.

**Comment by jiaqiluo** [comment]
The fix can be validated at https://github.com/rancher/rke/releases/tag/v1.5.11-rc1 

Please check https://github.com/rancher/rke/issues/3587#issuecomment-2155219068 for steps.

**Comment by slickwarren** [comment]
tested the following on v1.5.11-rc4:
* provision an rke1 cluster with no extra_env -- pass
* provision an rke1 cluster with extra_env -- pass
* upgrade an rke1 cluster with no extra_env -> with extra_env -- pass
* upgrade an rke1 cluster with extra_env -> update extra_env -- pass
* upgrade an rke1 cluster with extra_env -> remove extra_env -- pass

tested with default versions of k8s (1.28.11)
