### ISSUE TITLE
Ceph rbd volume mount problem

### ISSUE THREAD

**Issue by adalga** [rancher/rke#362]
**RKE version: 0.1.1

**Docker version: 17.03.2-ce

**Operating system and kernel: Ubuntu 16.04 - 4.10.0-28-generic

**Type/provider of hosts: VMWare

**cluster.yml file:
> [cluster.yml.txt](https://github.com/rancher/rke/files/1735781/cluster.yml.txt)

**Steps to Reproduce:**

> ./rke up
Create a ceph cluster. (I created by following this guide http://docs.ceph.com/docs/master/start/quick-ceph-deploy/)
Create a persistent storage class and claim then try it in a sample pod. (I followed this tutorial https://crondev.com/kubernetes-persistent-storage-ceph/ )

**Results:
I got an error like below:
> MountVolume.SetUp failed for volume "pvc-0cb70641-153e-11e8-981e-000c29169fa6" : rbd: map failed exit status 2 libkmod: ERROR ../libkmod/libkmod.c:586 kmod_search_moddep: could not open moddep file '/lib/modules/4.10.0-28-generic/modules.dep.bin' modinfo: ERROR: Module alias rbd not found. modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.10.0-28-generic/modules.dep.bin' modprobe: FATAL: Module rbd not found in directory /lib/modules/4.10.0-28-generic rbd: failed to load rbd kernel module (1) rbd: sysfs write failed In some cases useful info is found in syslog - try "dmesg | tail" or so. rbd: map failed: (2) No such file or directory

**Comment by galal-hussein** [comment]
@adalga it seems like /lib/modules should be added to kubelet mounts for ceph rbd to work https://github.com/rancher/rke/blob/master/cluster/plan.go#L212-L227

**Comment by adalga** [comment]
Yeah. That was my solution too and I applied and tested on master branch. It works.

**Comment by gucki** [comment]
@galal-hussein What about making this a default just like with `/etc/ceph` in https://github.com/rancher/rke/issues/129? I also created a ticket upstream to workaround this issue by first checking if the module is already loaded.
