### ISSUE TITLE
Failed to dial to Docker socket while deploy etcd

### ISSUE THREAD

**Issue by qianxiaoming** [rancher/rke#364]
**RKE version:**
v0.1.1

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

kernel version: 3.10.0-693.11.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
private cloud envirment

**cluster.yml file:**
---
nodes:
  - address: a4
    user: root
    role: [worker]
  - address: a5
    user: root
    role: [worker]
  - address: a6
    user: root
    role: [worker]
  - address: a7
    user: root
    role: [etcd]
  - address: a8
    user: root
    role: [controlplane]

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2

**Steps to Reproduce:**
./rke up

**Results:**
INFO[0000] Building Kubernetes cluster                  
INFO[0000] [dialer] Setup tunnel for host [a7]          
FATA[0000] Failed to set up SSH tunneling for Etcd host [a7]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial to Docker socket: ssh: rejected: administratively prohibited (open failed)

by the way: selinux is enforcing

**Comment by moelsayed** [comment]
Please check https://github.com/rancher/rke/issues/93

**Comment by qianxiaoming** [comment]
Thanks! It works for CentOS 7.4.
