### ISSUE TITLE
Missing sha256sum.txt

### ISSUE THREAD

**Issue by brentkoch142** [rancher/rke#3652]
**RKE version:**

**Docker version: (`docker version`,`docker info` preferred)**
Not important for this
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Not important for this
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Not important for this
**cluster.yml file:**
Not important for this
**Steps to Reproduce:**
Check recent releases since approx July 1 and there is no longer a sha256sum.txt
**Results:**
sha256sum.txt is not present

**Comment by jiaqiluo** [comment]
The issue will be tracked on https://github.com/rancher/rancher/issues/46677
