### ISSUE TITLE
use fixed stream server bind address for cri-dockerd

### ISSUE THREAD

**Issue by kinarashah** [rancher/rke#3656]
Currently RKE doesn't set `streaming-bind-addr` when starting cri-dockerd: 
https://github.com/rancher/rke-tools/blob/f90a8996c5f2143b7b62a07444eb47f962354bad/entrypoint.sh#L118 

Fix it to set it to a known address, preferably to the same address `127.0.0.1:10010` as other runtimes do (for reference: https://github.com/k3s-io/k3s/pull/9975) 

Will need a change in RKE too if users can configure `streaming-bind-addr`, else the fix in rke-tools will suffice. Note that the change would be applied on kubelet restarts. 

SURE-8866

**Comment by vardhaman22** [comment]
testing scenarios:
1. Creation from rancher and rke should set the default port (10010)
2. Upgrading (from july to august) on rancher should also set the default port(10010)
3. And setting the custom host port on an installed version should update them in the cluster
@kinarashah please suggest if anything else needs to be tested for this.

**Comment by vivek-shilimkar** [comment]
Tested the scenario 1 and 3 with rancher v2.9-head and rke version 1.6.2-rc1. Both the scenarios set the port as expected.

**Comment by rishabhmsra** [comment]
Validation is completed as part of below issues, hence closing it.
- https://github.com/rancher/rancher/issues/46918
- https://github.com/rancher/rancher/issues/46871
