### ISSUE TITLE
Update rke v1.5.12 to v1.6.1 coredns service error

### ISSUE THREAD

**Issue by liuxin638507** [rancher/rke#3666]
**RKE version:**
v1.6.1
**Docker version: (`docker version`,`docker info` preferred)**
docker://20.10.18
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Operating system: CentOS Linux release 7.9.2009 (Core
kernel: 3.10.0-1160.76.1.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**
Update rke v1.5.12 to v1.6.1 coredns service error, use rke v1.6.0 version is the same error, back to v1.5.12 coredns returned to norma
**Results:**
![image](https://github.com/user-attachments/assets/02ba7f21-3754-4f1e-85b8-88b02a1212ee)

**Comment by chiukapoor** [comment]
* Deployed `v1.27.6` k8s cluster on ubuntu 22.04 with Docker 25.x using standalone RKE `v1.5.12`
```
kubectl get all -A --kubeconfig kube_config_cluster.yml| grep coredns
kube-system     pod/coredns-75885c777c-xr8lf                   1/1     Running     0          22m
kube-system     pod/coredns-autoscaler-8687f86b76-zth2s        1/1     Running     0          22m
kube-system     pod/rke-coredns-addon-deploy-job-thrkp         0/1     Completed   0          22m
kube-system   deployment.apps/coredns                   1/1     1            1           22m
kube-system   deployment.apps/coredns-autoscaler        1/1     1            1           22m
kube-system   replicaset.apps/coredns-75885c777c                   1         1         1       22m
kube-system   replicaset.apps/coredns-autoscaler-8687f86b76        1         1         1       22m
kube-system     job.batch/rke-coredns-addon-deploy-job        1/1           17s        22m
```

* Successfully upgraded rke to `v1.6.1`
```
❯ ./rke -v
rke version v1.6.1
❯ kubectl get all -A --kubeconfig kube_config_cluster.yml| grep coredns
kube-system     pod/coredns-75885c777c-xr8lf                   1/1     Running     0          34m
kube-system     pod/coredns-autoscaler-8687f86b76-zth2s        1/1     Running     0          34m
kube-system     pod/rke-coredns-addon-deploy-job-thrkp         0/1     Completed   0          34m
kube-system   deployment.apps/coredns                   1/1     1            1           34m
kube-system   deployment.apps/coredns-autoscaler        1/1     1            1           34m
kube-system   replicaset.apps/coredns-75885c777c                   1         1         1       34m
kube-system   replicaset.apps/coredns-autoscaler-8687f86b76        1         1         1       34m
kube-system   job.batch/rke-coredns-addon-deploy-job        1/1           17s        34m
```
* Issue not reproduced on supported OS and Docker version. [Rancher Support Matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-6/)

**Comment by paddy-hack** [comment]
Upgrading RKE from v1.5.12 to v1.6.1, pinning kubernetes at `v1.28.12-rancher1`.  Nodes run RancherOS v1.5.8 with Docker 19.03.15.  Yes I know I need to ~~upgrade~~ replace my nodes :weary:

The `coredns` deployment in the `kube-system` namespace failed to upgrade.
```
kube-system      coredns-55f58ff64b-pnnln   0/1     CrashLoopBackOff   12 (59s ago)   37m     10.42.1.54     10.11.55.226   <none>           <none>
kube-system      coredns-55f58ff64b-z87mr   0/1     CrashLoopBackOff   2 (27s ago)    60s     10.42.2.21     10.11.55.228   <none>           <none>
```
Checking the pod logs gave
```
Listen: listen tcp :53: bind: permission denied
```
For now, I've rolled the deployment back
``` console
$ kubectl -n kube-system rollout undo deployment coredns
Warning: spec.template.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: non-functional in v1.27+; use the "seccompProfile" field instead
deployment.apps/coredns rolled back
```

The log message led me to [this CoreDNS issue](https://github.com/coredns/coredns/issues/6716) that says that a [recent change](https://github.com/coredns/coredns/pull/5969) started running coredns as non-root.  Obviously, that prevents binding to privileged ports (ports in the 0-123 range).

**Comment by paddy-hack** [comment]
BTW, the difference between the replicaset specs is in the `rancher/mirrored-coredns-coredns` image's version.  That was changed from 1.10.1 to 1.11.1 as part of the upgrade.  Guess I should have pinned that as well.

**Comment by liuxin638507** [comment]
> * Deployed `v1.27.6` k8s cluster on ubuntu 22.04 with Docker 25.x using standalone RKE `v1.5.12`
> 
> ```
> kubectl get all -A --kubeconfig kube_config_cluster.yml| grep coredns
> kube-system     pod/coredns-75885c777c-xr8lf                   1/1     Running     0          22m
> kube-system     pod/coredns-autoscaler-8687f86b76-zth2s        1/1     Running     0          22m
> kube-system     pod/rke-coredns-addon-deploy-job-thrkp         0/1     Completed   0          22m
> kube-system   deployment.apps/coredns                   1/1     1            1           22m
> kube-system   deployment.apps/coredns-autoscaler        1/1     1            1           22m
> kube-system   replicaset.apps/coredns-75885c777c                   1         1         1       22m
> kube-system   replicaset.apps/coredns-autoscaler-8687f86b76        1         1         1       22m
> kube-system     job.batch/rke-coredns-addon-deploy-job        1/1           17s        22m
> ```
> 
> * Successfully upgraded rke to `v1.6.1`
> 
> ```
> ❯ ./rke -v
> rke version v1.6.1
> ❯ kubectl get all -A --kubeconfig kube_config_cluster.yml| grep coredns
> kube-system     pod/coredns-75885c777c-xr8lf                   1/1     Running     0          34m
> kube-system     pod/coredns-autoscaler-8687f86b76-zth2s        1/1     Running     0          34m
> kube-system     pod/rke-coredns-addon-deploy-job-thrkp         0/1     Completed   0          34m
> kube-system   deployment.apps/coredns                   1/1     1            1           34m
> kube-system   deployment.apps/coredns-autoscaler        1/1     1            1           34m
> kube-system   replicaset.apps/coredns-75885c777c                   1         1         1       34m
> kube-system   replicaset.apps/coredns-autoscaler-8687f86b76        1         1         1       34m
> kube-system   job.batch/rke-coredns-addon-deploy-job        1/1           17s        34m
> ```
> 
> * Issue not reproduced on supported OS and Docker version. [Rancher Support Matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-6/)

Thank you very much!
I have tested 2 methods that work properly:
1、update kernel version to 5.11+
2、update docker-ce version to 24.x+
