### ISSUE TITLE
Is there a plan to support kubernetes 1.9.x?

### ISSUE THREAD

**Issue by qianxiaoming** [rancher/rke#371]
If there is, can someone tell me the estimated time?

**Comment by HighwayofLife** [comment]
I've been using rke with Kubernetes 1.9.x successfully for nearly 2 months.

**Comment by aemneina** [comment]
@qianxiaoming the next rancher 1.6 release should make it available. That’s due out next month.

**Comment by qianxiaoming** [comment]
so what 's  the name of k8s 1.9.x image? I found that 'rancher/k8s:latest' not works. what should I write in my cluster yml file?

**Comment by qianxiaoming** [comment]
OK, I find it in docker hub: v1.9.3-rancher1-1

**Comment by HighwayofLife** [comment]
https://hub.docker.com/r/rancher/k8s/tags/

Latest is: v1.9.3-rancher1-1
