### ISSUE TITLE
Document RKE cluster.yml properties

### ISSUE THREAD

**Issue by scriptjs** [rancher/rke#372]
Its really important that cluster.yml properties are clearly documented. To use RKE, one only gains some insight from the blog post and Darren's presentation but this is insufficient. Neither covers all properties and its quite important to make use of the tool. RKE is likely to be one of the first experiences folks have with the Rancher org to stand a Kubernetes cluster. I think it would be best that it was a good one that did not leave basic questions that consume eveyone's time.

**Comment by HighwayofLife** [comment]
I'll work on creating a PR for this next.

**Comment by scriptjs** [comment]
@HighwayofLife Cool! I am also willing to help. I've been gradually getting things in line for automating my Rancher 2 dev cluster. One thing that going to be important to a number of organizations doing private cloud and on premise is not duplicating their etcd cluster for multiple kubernetes clusters.

I fall in to this camp. I want to maintain a single etcd and consul cluster for discovery and management so that I am making the best use of k8 clusters for app workloads while also keeping management tooling isolated. Currently Rancher 2 is maintaining its own state in its own etcd for the preview but you will be able to eventually pass your etcd cluster membership as part of running on the host in Docker, hopefully when it gets to beta, and certainly by GA.

**Comment by deniseschannon** [comment]
In this PR https://github.com/rancher/rke/pull/706, we will be moving all docs to the Rancher docs repo. https://github.com/rancher/docs. 

There are several PRs that are updating it so that it will be made available at rancher.com/docs.

**Comment by deniseschannon** [comment]
https://rancher.com/docs/rke/v0.1.x/en/config-options/
