### ISSUE TITLE
Control plane hosts are marked as schedulable

### ISSUE THREAD

**Issue by Overv** [rancher/rke#379]
Why are control plane hosts also schedulable even when they are not marked as worker nodes?

https://github.com/rancher/rke/blob/9601ddd5a6c7c98e0c3c10e89d2fd3fb1d94e85f/services/workerplane.go#L20

**Comment by moelsayed** [comment]
We do this to allow for single node deployment.

**Comment by Overv** [comment]
Yes, but then the control plane mode would simply also be marked as worker, right?

**Comment by galal-hussein** [comment]
@Overv not really, the controlplane node marked as `master` and workers are marked as `worker`, the control plane are schedulable but they include the master components include:
- kubeapi
- scheduler
- controller-manager
and also it contains the worker's compnents:
- kubelet
- kubeproxy

you can have a minimum cluster with just one node that has `controlplane` and `etcd` roles only

**Comment by Overv** [comment]
Is there no way to have a `controlplane` and `etcd` without `kubelet`?

**Comment by galal-hussein** [comment]
@Overv not really, the current implementation adds kubelet to each node type

**Comment by pdhung** [comment]
@galal-hussein the current implementation is great for a single node deployment, but is bad for production. I would like to have no "worker" pods running on the same node with the api-server, or any other controlplane components. How should I do it? Right now the only way seems to be k8s cordon
