### ISSUE TITLE
Can not reach nodes after restart

### ISSUE THREAD

**Issue by adalga** [rancher/rke#380]
**RKE version: Master branch

**Docker version: 17.03.2-ce

**Operating system and kernel: Ubuntu 16.04 - 4.10.0-28-generic

**Type/provider of hosts: Bare metal

**cluster.yml file:
[cluster.yml.txt](https://github.com/rancher/rke/files/1758850/cluster.yml.txt)

**Steps to Reproduce:

> rke up
Restart all nodes
Try to get nodes via kubectl get nodes

**Results:**
I can't reach the nodes after I restart all of the nodes. kubectl get nodes gives an error like :
> Unable to connect to the server: unexpected EOF

kubelet gives a log like below:
> E0226 14:01:54.018650    1845 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:422: Failed to list *v1.Node: nodes is forbidden: User "system:node" cannot list nodes at the cluster scope

**Comment by moelsayed** [comment]
Can you provide logs from kubelet and kube-api containers on your setup? I can't reproduce your issue.

**Comment by moelsayed** [comment]
Sorry, my bad. I am able to reproduce now. Fix pushed.

**Comment by adalga** [comment]
Master branch is working now. Thanks.

**Comment by galal-hussein** [comment]
rke version: v0.1.2
I was able to verify that all components works after restart
