### ISSUE TITLE
High availability does not work

### ISSUE THREAD

**Issue by adalga** [rancher/rke#381]
**RKE version: 0.1.1

**Docker version: 17.03.2-ce

**Operating system and kernel: Ubuntu 16.04 - 4.10.0-28-generic

**Type/provider of hosts: Bare metal

**cluster.yml file:

> [cluster.yml.txt](https://github.com/rancher/rke/files/1758860/cluster.yml.txt)

**Steps to Reproduce:

> rke up
shut down the first controlplane node

**Results:**

> Cluster is not available after I shut down the first master node. Your documentation says "to start an HA cluster, just specify more than one host with role controlplane, and start the cluster normally." However, it does not work. It tries the reach kube api through first controlplane node.

**Comment by moelsayed** [comment]
You will need to update your kubeconfig file with the address of another (working) control plan host. 

You can also remove the host from your `cluster.yml` file and run `rke up`. RKE will remove the host from the cluster and update the kubeconfig file.

**Comment by adalga** [comment]
Thanks for reply. I got your point. I am closing the issue.

**Comment by mayconfsbrito** [comment]
So, If I understand. If another control plane node crash, I need to update my cluster removing that node to maintain my cluster running?

**Comment by moelsayed** [comment]
@mayconfsbrito No. As long you a working control plane node, your cluster will be operational. You just need to connect kubectl to the working control node to manage it. Worker and etcd nodes have a reverse-proxy service to loadbalance traffic over working control plane nodes.

**Comment by mayconfsbrito** [comment]
@moelsayed Understood. I have just two nodes in my cluster. Both are etcd, controlplane and worker. I will add one more node just to be worker in the future. But now I'm trying to simulate a crash cenario between these two master nodes. But when any of them gone, the another freezes waiting.

**Comment by moelsayed** [comment]
@mayconfsbrito 2 etcd nodes don't provide a fault tolerant cluster. You need at least 3. Etcd quorum is (n/2)+1 nodes. Checkout [this](https://coreos.com/etcd/docs/latest/faq.html#deployment) for more information.

**Comment by mayconfsbrito** [comment]
@moelsayed Very relevant information!

I will read this doc too. Thank you!
