### ISSUE TITLE
Failed to get job complete status when using Calico network plugin

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rke#39]
Using the Calico network plugin, I got the message that rke cluster up failed:

INFO[0280] [addons] Successfully Saved addon to Kubernetes ConfigMap: rke-netwok-plugin
INFO[0280] [addons] Executing deploy job..
Failed to get job complete status: <nil>
FATA[0286] Failed to deploy addon execute job: Failed to get job complete status: <nil>

The calico pods were up and running though

Traviss-MacBook-Pro:Downloads tcordingly$ kubectl --kubeconfig .kube_config_cluster.yaml get pods -n kube-system
NAME                                       READY     STATUS    RESTARTS   AGE
calico-kube-controllers-6f455dcc5b-nrsx4   1/1       Running   0          17m
calico-node-2lwdb                          2/2       Running   0          17m
calico-node-l8tt9                          2/2       Running   0          17m
calico-node-lbvw8                          2/2       Running   0          17m

**Comment by galal-hussein** [comment]
this looks like a race condition, where rke doesn't wait enough for the k8s job to finish and report success, the code only wait for 5 seconds, i will put a fix for that

**Comment by galal-hussein** [comment]
The fix can be tested with v0.0.5-dev

**Comment by sabiodelhielo** [comment]
Verified this on v0.0.5-dev
