### ISSUE TITLE
Unable to Communicate With Kube Api

### ISSUE THREAD

**Issue by adalga** [rancher/rke#396]
**RKE version: Master Branch

**Docker version:  17.03.2-ce

**Operating system and kernel: Centos7 -  3.10.0-693.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO) BareMetal

**cluster.yml file: 
[cluster.yml.txt](https://github.com/rancher/rke/files/1775245/cluster.yml.txt)

**Steps to Reproduce: rke up

**Results:**
kubectl get pods -n kube-system
> NAME                                   READY     STATUS    RESTARTS   AGE
kube-dns-6f7666d48c-jn76g              3/3       Running   0          0s
kube-dns-autoscaler-6bbfff8c44-6f7hx   1/1       Running   0          0s
weave-net-7phps                        2/2       Running   0          15s
weave-net-ffggk                        2/2       Running   0          15s
weave-net-g2qgk                        2/2       Running   0          15s

kubectl logs -n kube-system kubernetes-dashboard-5569448c6d-r8557

> 2018/03/02 13:53:44 Using in-cluster config to connect to apiserver
> 2018/03/02 13:53:44 Using service account token for csrf signing
> 2018/03/02 13:53:44 No request provided. Skipping authorization
> 2018/03/02 13:53:44 Starting overwatch
> 2018/03/02 13:53:45 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.233.0.1:443/version: dial tcp 10.233.0.1:443: getsockopt: no route to host
> Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ

kubectl logs -n kube-system weave-net-7phps weave

> DEBU:2018/03/02 13:51:08.976700 [kube-peers] Checking peer "ce:43:3c:d9:d1:32" against list &{[]}
Peer not in list; removing persisted data
INFO: 2018/03/02 13:51:09.046356 Command line options: map[status-addr:0.0.0.0:6782 datapath:datapath db-prefix:/weavedb/weave-net no-dns:true nickname:192.168.254.129 expect-npc:true host-root:/host http-addr:127.0.0.1:6784 ipalloc-init:consensus=3 ipalloc-range:10.233.64.0/18 conn-limit:30 docker-api: name:ce:43:3c:d9:d1:32 port:6783]
INFO: 2018/03/02 13:51:09.046423 weave  2.1.2
INFO: 2018/03/02 13:51:09.343601 Bridge type is bridged_fastdp
INFO: 2018/03/02 13:51:09.343619 Communication between peers is unencrypted.
INFO: 2018/03/02 13:51:09.357929 Our name is ce:43:3c:d9:d1:32(192.168.254.129)
INFO: 2018/03/02 13:51:09.357976 Launch detected - using supplied peer list: [192.168.254.129 192.168.254.130 192.168.254.131]
INFO: 2018/03/02 13:51:09.358009 Checking for pre-existing addresses on weave bridge
INFO: 2018/03/02 13:51:09.439221 [allocator ce:43:3c:d9:d1:32] No valid persisted data
INFO: 2018/03/02 13:51:09.469367 [allocator ce:43:3c:d9:d1:32] Initialising via deferred consensus
INFO: 2018/03/02 13:51:09.469430 Sniffing traffic on datapath (via ODP)
INFO: 2018/03/02 13:51:09.479952 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2018/03/02 13:51:09.480397 Listening for metrics requests on 0.0.0.0:6782
INFO: 2018/03/02 13:51:09.484019 Discovered local MAC 86:4f:30:cd:10:8c
INFO: 2018/03/02 13:51:09.500161 ->[192.168.254.129:6783] attempting connection
INFO: 2018/03/02 13:51:09.500308 ->[192.168.254.130:6783] attempting connection
INFO: 2018/03/02 13:51:09.500440 ->[192.168.254.131:6783] attempting connection
INFO: 2018/03/02 13:51:09.501311 ->[192.168.254.129:49919] connection accepted
INFO: 2018/03/02 13:51:09.502128 ->[192.168.254.130:6783|da:a6:93:fb:62:81(192.168.254.130)]: connection ready; using protocol version 2
INFO: 2018/03/02 13:51:09.502268 overlay_switch ->[da:a6:93:fb:62:81(192.168.254.130)] using fastdp
INFO: 2018/03/02 13:51:09.502289 ->[192.168.254.130:6783|da:a6:93:fb:62:81(192.168.254.130)]: connection added (new peer)
INFO: 2018/03/02 13:51:09.512809 ->[192.168.254.131:6783|fe:65:4f:35:44:5d(192.168.254.131)]: connection ready; using protocol version 2
INFO: 2018/03/02 13:51:09.512906 overlay_switch ->[fe:65:4f:35:44:5d(192.168.254.131)] using fastdp
INFO: 2018/03/02 13:51:09.512923 ->[192.168.254.131:6783|fe:65:4f:35:44:5d(192.168.254.131)]: connection added (new peer)
INFO: 2018/03/02 13:51:09.513816 ->[192.168.254.129:49919|ce:43:3c:d9:d1:32(192.168.254.129)]: connection shutting down due to error: cannot connect to ourself
INFO: 2018/03/02 13:51:09.514033 ->[192.168.254.129:6783|ce:43:3c:d9:d1:32(192.168.254.129)]: connection shutting down due to error: cannot connect to ourself
INFO: 2018/03/02 13:51:09.521204 EMSGSIZE on send, expecting PMTU update (IP packet was 60028 bytes, payload was 60020 bytes)
INFO: 2018/03/02 13:51:09.521295 overlay_switch ->[da:a6:93:fb:62:81(192.168.254.130)] using sleeve
INFO: 2018/03/02 13:51:09.521312 ->[192.168.254.130:6783|da:a6:93:fb:62:81(192.168.254.130)]: connection fully established
INFO: 2018/03/02 13:51:09.522614 EMSGSIZE on send, expecting PMTU update (IP packet was 60028 bytes, payload was 60020 bytes)
INFO: 2018/03/02 13:51:09.522687 overlay_switch ->[fe:65:4f:35:44:5d(192.168.254.131)] using sleeve
INFO: 2018/03/02 13:51:09.522701 ->[192.168.254.131:6783|fe:65:4f:35:44:5d(192.168.254.131)]: connection fully established
INFO: 2018/03/02 13:51:09.523031 sleeve ->[192.168.254.130:6783|da:a6:93:fb:62:81(192.168.254.130)]: Effective MTU verified at 1438
INFO: 2018/03/02 13:51:09.523064 sleeve ->[192.168.254.131:6783|fe:65:4f:35:44:5d(192.168.254.131)]: Effective MTU verified at 1438
INFO: 2018/03/02 13:51:09.552705 Discovered remote MAC de:4a:f7:4c:94:c6 at fe:65:4f:35:44:5d(192.168.254.131)
INFO: 2018/03/02 13:51:09.690248 Discovered remote MAC fe:65:4f:35:44:5d at fe:65:4f:35:44:5d(192.168.254.131)
INFO: 2018/03/02 13:51:09.748066 Discovered remote MAC da:a6:93:fb:62:81 at da:a6:93:fb:62:81(192.168.254.130)
INFO: 2018/03/02 13:51:09.890315 Discovered local MAC ce:43:3c:d9:d1:32
INFO: 2018/03/02 13:51:09.936131 Discovered local MAC a2:44:1d:59:14:95
INFO: 2018/03/02 13:51:10.101767 Weave version 2.2.0 is available; please update at https://github.com/weaveworks/weave/releases/download/v2.2.0/weave
INFO: 2018/03/02 13:51:10.227755 [kube-peers] Added myself to peer list &{[{fe:65:4f:35:44:5d 192.168.254.131} {da:a6:93:fb:62:81 192.168.254.130} {ce:43:3c:d9:d1:32 192.168.254.129}]}
DEBU: 2018/03/02 13:51:10.227816 [kube-peers] Nodes that have disappeared: map[]
INFO: 2018/03/02 13:51:10.241303 Discovered remote MAC a6:4f:30:a8:a7:d2 at da:a6:93:fb:62:81(192.168.254.130)
10.233.120.0
INFO: 2018/03/02 13:51:10.355742 Discovered remote MAC aa:7b:a9:50:22:8a at da:a6:93:fb:62:81(192.168.254.130)
INFO: 2018/03/02 13:51:13.422790 Discovered remote MAC ce:2b:82:eb:43:bf at fe:65:4f:35:44:5d(192.168.254.131)
INFO: 2018/03/02 13:51:22.833253 Discovered local MAC be:0f:6a:5a:d4:87
INFO: 2018/03/02 13:51:22.851769 Discovered remote MAC 32:4f:6a:9f:c1:60 at fe:65:4f:35:44:5d(192.168.254.131)
INFO: 2018/03/02 13:51:25.000189 Discovered local MAC 22:24:ee:cc:10:28
WARN: 2018/03/02 13:51:26.977124 [allocator]: Delete: no addresses for a85eb6578778bf79386ed45384d46171e3b1cf317648753d228f38e8c3395106
INFO: 2018/03/02 13:51:36.651099 Discovered remote MAC 56:4a:5b:c1:6d:91 at fe:65:4f:35:44:5d(192.168.254.131)
WARN: 2018/03/02 13:51:54.477635 [allocator]: Delete: no addresses for a85eb6578778bf79386ed45384d46171e3b1cf317648753d228f38e8c3395106
INFO: 2018/03/02 13:52:09.503064 overlay_switch ->[da:a6:93:fb:62:81(192.168.254.130)] fastdp timed out waiting for vxlan heartbeat
INFO: 2018/03/02 13:52:09.513546 overlay_switch ->[fe:65:4f:35:44:5d(192.168.254.131)] fastdp timed out waiting for vxlan heartbeat
INFO: 2018/03/02 13:53:21.236068 Discovered remote MAC 6a:15:c6:cc:f6:14 at da:a6:93:fb:62:81(192.168.254.130)

kubectl logs -n kube-system kube-dns-6f7666d48c-jn76g kubedns

> I0302 13:51:24.750555       1 dns.go:48] version: 1.14.4-2-g5584e04
I0302 13:51:24.751865       1 server.go:70] Using configuration read from directory: /kube-dns-config with period 10s
I0302 13:51:24.751919       1 server.go:113] FLAG: --alsologtostderr="false"
I0302 13:51:24.751927       1 server.go:113] FLAG: --config-dir="/kube-dns-config"
I0302 13:51:24.751932       1 server.go:113] FLAG: --config-map=""
I0302 13:51:24.751935       1 server.go:113] FLAG: --config-map-namespace="kube-system"
I0302 13:51:24.751939       1 server.go:113] FLAG: --config-period="10s"
I0302 13:51:24.751952       1 server.go:113] FLAG: --dns-bind-address="0.0.0.0"
I0302 13:51:24.751956       1 server.go:113] FLAG: --dns-port="10053"
I0302 13:51:24.751961       1 server.go:113] FLAG: --domain="cluster.local."
I0302 13:51:24.751966       1 server.go:113] FLAG: --federations=""
I0302 13:51:24.751971       1 server.go:113] FLAG: --healthz-port="8081"
I0302 13:51:24.751975       1 server.go:113] FLAG: --initial-sync-timeout="1m0s"
I0302 13:51:24.751978       1 server.go:113] FLAG: --kube-master-url=""
I0302 13:51:24.751983       1 server.go:113] FLAG: --kubecfg-file=""
I0302 13:51:24.751986       1 server.go:113] FLAG: --log-backtrace-at=":0"
I0302 13:51:24.751993       1 server.go:113] FLAG: --log-dir=""
I0302 13:51:24.751996       1 server.go:113] FLAG: --log-flush-frequency="5s"
I0302 13:51:24.752000       1 server.go:113] FLAG: --logtostderr="true"
I0302 13:51:24.752003       1 server.go:113] FLAG: --nameservers=""
I0302 13:51:24.752007       1 server.go:113] FLAG: --stderrthreshold="2"
I0302 13:51:24.752010       1 server.go:113] FLAG: --v="2"
I0302 13:51:24.752013       1 server.go:113] FLAG: --version="false"
I0302 13:51:24.752019       1 server.go:113] FLAG: --vmodule=""
I0302 13:51:24.757546       1 server.go:176] Starting SkyDNS server (0.0.0.0:10053)
I0302 13:51:24.757823       1 server.go:198] Skydns metrics enabled (/metrics:10055)
I0302 13:51:24.757832       1 dns.go:147] Starting endpointsController
I0302 13:51:24.757834       1 dns.go:150] Starting serviceController
I0302 13:51:24.758059       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0302 13:51:24.758065       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0302 13:51:25.258324       1 dns.go:171] Initialized services and endpoints from apiserver
I0302 13:51:25.258343       1 server.go:129] Setting up Healthz Handler (/readiness)
I0302 13:51:25.258350       1 server.go:134] Setting up cache handler (/cache)
I0302 13:51:25.258356       1 server.go:120] Status HTTP port 8081

**Comment by galal-hussein** [comment]
@adalga can you post the following logs:
```
docker logs kubelet
docker logs kube-api
kubectl describe nodes
```

**Comment by superseb** [comment]
Please report back with the needed info so we can investigate.
