### ISSUE TITLE
How to debug rke

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rke#406]
Question: How can you debug issues when building rke?

Build, and test succeed, but the changes are failing on validation and merely print as:

```
...
Running validation
Running: go vet
Running: golint
Running: go fmt
cluster/plan.go
FATA[0071] exit status 1                                
make: *** [ci] Error 1
```

I cannot determine what is causing validation to fail, other than the file the validation is failing against.

**Comment by superseb** [comment]
It's failing on `go fmt`, the changes in `cluster/plan.go` or not properly formatted (according to https://golang.org/cmd/gofmt/)

If you run `go fmt cluster/plan.go`, it will be automatically formatted correctly and this will succeed.
