### ISSUE TITLE
Ceph RBD  Could not map image: Timeout after 10s

### ISSUE THREAD

**Issue by adalga** [rancher/rke#408]
**RKE version: Master Branch

**Docker version: 17.03.2-ce

**Operating system and kernel: Ubuntu 16.04 - 4.13.0-36-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO) BareMetal

**cluster.yml file:**

> [cluster.yml.txt](https://github.com/rancher/rke/files/1792930/cluster.yml.txt)

**Steps to Reproduce:**

> add  "/lib/modules:/lib/modules:ro,z", line to cluster/plan.go -> BuildKubeletProcess -> Binds 
build rke
rke up
Create a ceph cluster. (I created by following this guide http://docs.ceph.com/docs/master/start/quick-ceph-deploy/)
kubectl create secret generic ceph-secret --type="kubernetes.io/rbd" --from-literal=key='<ceph admin key>'
kubectl create -f [ceph-storage-rbd.yml.txt](https://github.com/rancher/rke/files/1792941/ceph-storage-rbd.yml.txt)
kubectl create -f [ceph-vc.yaml.txt](https://github.com/rancher/rke/files/1792942/ceph-vc.yaml.txt)
kubect- create -f [test-rbd.yaml.txt](https://github.com/rancher/rke/files/1792943/test-rbd.yaml.txt)

**Results:**

> MountVolume.SetUp failed for volume "pvc-1424170c-a577-11e6-8b62-7427ea3303cf": Could not map image: Timeout after 10s

**Comment by adalga** [comment]
It is about https://github.com/rancher/rke/commit/0d1b4597421bb985f79092886172d507e81ba492 . When I revert this it works.

**Comment by deniseschannon** [comment]
@adalga Are you still having this issue? Have you tried with later versions of RKE?

**Comment by adalga** [comment]
No. I have not tried with later versions.

**Comment by deniseschannon** [comment]
If you have a chance to try with a later version, please let me know. Were you able to get it working on other versions of k8s? 

I'll close the issue for now
