### ISSUE TITLE
Support Cluster Name for Kube Config

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rke#415]
The kube_config file is saved with the cluster name as "local" hard-coded. There is no parameter to change this. The problem with that configuration is that you can't merge it with your normal `~/.kube/config` as if you have multiple rke clusters (as I do), they all conflict.

The resolution would be to add cluster name support to the `cluster.yml` file.

Pull Request Submitted: #413

**Comment by galal-hussein** [comment]
I can test this feature with `cluster_name` option in the cluster config, and i can see the result in kube config, thanks!
