### ISSUE TITLE
RKE upgrade does not take care of renamed containers

### ISSUE THREAD

**Issue by Overv** [rancher/rke#418]
Recently, the names of the Kubernetes containers were changed to match the binaries:

https://github.com/rancher/rke/commit/a90b672fe472e215ceca52c992f58f1653577484

However, this results in `rke up` on a cluster that existed before this change to run duplicate copies of all containers. My cluster ended up running `kube-api`, `kube-apiserver`, `kube-controller`, `kube-controller-manager`, `scheduler` and `kube-scheduler` all at the same time, which triggered many weird problems.

RKE should clean up all containers that are associated with it as part of upgrades or at least check for legacy names like this.

**Comment by moelsayed** [comment]
Unfortunately, at this point we will not handle backwards compatibility for similar changes, since we are still in development. Once we reach GA, any similar changes, if any, will be handled gracefully.
