### ISSUE TITLE
hi, having problems with cropcoin masternode set up.    i sync up both wallets local and vps. i make all the changes to the config files and then restart the wallets but  as soon as start all i get a runtime error.it happems every time. plent of ram on the pc and just restored. dont know what else to do. HELP

### ISSUE THREAD

**Issue by jam2205** [rancher/rke#419]
**RKE version:**

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**

**Results:**

**Comment by HighwayofLife** [comment]
There is no information in this ticket.

**Comment by jam2205** [comment]
I hi, having problems with cropcoin masternode set up. to hi, having problems with cropcoin masternode set up. i sync up both wallets local and vps. i make all the changes to the config files and then restart the wallets but as soon as start all i get a runtime error.it happems every time. plent of ram on the pc and just restored. dont know what else to do.

**Comment by jam2205** [comment]
sorry this is my first time

**Comment by HighwayofLife** [comment]
This is not the right place to ask for support for that.
