### ISSUE TITLE
RUNTIME ERROR HELP

### ISSUE THREAD

**Issue by jam2205** [rancher/rke#420]
**RKE version:**

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**

**Results:**

**Comment by jam2205** [comment]
hi, having problems with cropcoin masternode set up. to hi, having problems with cropcoin masternode set up. i sync up both wallets local and vps. i make all the changes to the config files and then restart the wallets but as soon as start all i get a runtime error.it happems every time. plent of ram on the pc and just restored. dont know what else to do.

**Comment by HighwayofLife** [comment]
I think you're looking in the wrong place for help for that.
