### ISSUE TITLE
Add support for AWS cloud provider

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#434]
Adding support for AWS cloud provider can be done by passing cloud provider options to:
- kubelet
- controller-manager
- kubeapi
There is no need for deploying cloud-config file to nodes like other providers

**Comment by moelsayed** [comment]
Tested using latest master. I was able to deploy a cluster on existing aws instances configured with a proper IAM role. I was also able to create a simple web deployment with an ELB based service.

**Comment by risayew** [comment]
I have an issue using EBS Storage Class: Failed to provision volume with StorageClass “my-storage”: Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead. I think, it's related to this ticket. I imported already existing rke cluster to rancher. Any help appreciated.
