### ISSUE TITLE
Lint fails on cluster/addons - redundant if

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rke#447]
Attempting to build binaries results in the following build error from golint:

```
Running: golint
cluster/addons.go:115:2: redundant if ...; err != nil check, just return error instead.
FATA[0131] exit status 1 
```

Relevant commit ID: 7875c0996645b1b0f3d5a4d55960068b238e8779

**Comment by dahendel** [comment]
That should be fixed in [master](https://github.com/rancher/rke/blob/master/cluster/addons.go#L110) already

**Comment by HighwayofLife** [comment]
@dahendel The problem exists in master.
I built off of master ( 19eb46332ef0f960a78a9fec42924b992284f3f9 )
