### ISSUE TITLE
RFE - Ease certificate rotation in kubernetes

### ISSUE THREAD

**Issue by aemneina** [rancher/rke#450]
Add the ability to rotate certificates out within kubernetes:
- user should be able to rotate the certificates using rke command `rke cert rotate` or similar

- user should be able to provide certificates as an option - Removed this request to a different issue: https://github.com/rancher/rke/issues/1037

**Comment by zedtux** [comment]
Any progress on this?

**Comment by techninja1008** [comment]
Any Progress?

**Comment by matthax** [comment]
Hey I've got a cluster with a bad SSL certificate and I'm not able to update the cert using `rke up`. Is there a short term workaround that I can use until this is solved?

**Comment by cjellick** [comment]
Possible ui copoments for showing and managing certs for rke:
- upload on create
- renew and/or auto rotate

**Comment by alena1108** [comment]
@galal-hussein also explore the possibility of using a different key for service account vs k8s components

**Comment by deniseschannon** [comment]
@galal-hussein we should make sure this works for air gapped setups

**Comment by mtchuyen** [comment]
my certificate cluster will expire soon. Hurry up pls!

**Comment by bmdepesa** [comment]
First pass of testing has been completed.
