### ISSUE TITLE
typo bind-propagation

### ISSUE THREAD

**Issue by kyamazawa** [rancher/rke#459]
https://github.com/rancher/rke/blob/228423358a575d0b99c23aefeaa98fc666f5f06c/cluster/plan.go#L281

<img width="316" alt="2018-03-31 0 55 57" src="https://user-images.githubusercontent.com/26079331/38145823-33e8199e-3486-11e8-9e92-4e122c02b256.png">

**Comment by vincent99** [comment]
That's not a typo.  The mount propagation options are `private`, `shared`, and `slave`, and the `r` prefix means recursive.

**Comment by kyamazawa** [comment]
Sorry, but I think “/dev:/host/dev:rprivate” is right...

**Comment by moelsayed** [comment]
@kyamazawa You are right, thank you for reporting this!
