### ISSUE TITLE
Azure Cloud Provider Cloud Config Not Passed Through

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rke#464]
The [Azure Cloud Config](https://github.com/rancher/types/commit/9d34b8b8a4b16bfada13370ed52874924293d7af) is defined in the types list, which is fine until that list changes on the Kubernetes side, which would require maintenance to follow the updates. What if, instead, we just allow a pass through of the parameters to the json file rather than defining a static list?

**Comment by vincent99** [comment]
Everything requires maintenance.  Static typing allows useful options to show up in the CLI/API/UI and be validated instead of map[things]stuffs.

**Comment by HighwayofLife** [comment]
We allow pass through currently for most parameters in services, we don't define those parameters. Or perhaps we should add the ability to define anything extra to add to the cloud config.

**Comment by galal-hussein** [comment]
@HighwayofLife actually that's available now for users to add different parameters for the cloud config, the static types are not being directly used in rke cli you can still pass a map of strings to config directly:
```
cloud_provider:
  name: azure
  cloud_config:
    foo: bar
```
This will actually write a cloud-config.json:
```
{
"foo": "bar"
}
```

**Comment by HighwayofLife** [comment]
Cool! Thanks for the update! -- The reason for this is that you can add some additional flags to be used by other resources.
