### ISSUE TITLE
Renew an expired certificate

### ISSUE THREAD

**Issue by nmlabs** [rancher/rke#482]
Hi,

The question is in the title : how do I renew expired certificates generated during rke up ?
I prefer ask the question now, rather than in one year when they will expire. :)

All the best

EDIT:

I propose:
````
# rm -fr /etc/kubernetes/ssl/* (on all nodes)
# rke up
# systemctl restart docker (on all master nodes)
````

**Comment by galal-hussein** [comment]
Duplicate of https://github.com/rancher/rke/issues/450

**Comment by galal-hussein** [comment]
@PSEDrone Renewing certificates can be done using the latest rke rc:
```
./rke cert rotate --config cluster.yml
```

**Comment by alena1108** [comment]
@PSEDrone there is an open issue for cert rotation we are currently looking at: https://github.com/rancher/rke/issues/1208. Once fixed, the command mentioned by @galal-hussein should be used to rotate the certs on the latest rke rc.
