### ISSUE TITLE
Customize /etc/kubernetes path

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#484]
currently /etc/kubernetes is the default path for `ssl`, `cloud-config` and `tmp certs`, this path is hardcoded as a volume for all containers components and for certificate deployment, this path should be customized and be provided as an option to the cluster config

**Comment by galal-hussein** [comment]
@sangeethah rke should be tested against ROS and B2D hosts:
- for RancherOS path prefix will be automatically added for /opt/rke
- for B2D path prefix will be automatically added for /mnt/sda1/rke

**Comment by galal-hussein** [comment]
@sangeethah you can also test that in a regular setup by providing this option in the cluster.yml
```
prefix_path: /foo/bar
```
then you will find the prefix added to your paths for example:

/etc/kubernetes/ssl will be /foo/bar/etc/kubernetes/ssl
....

**Comment by adingilloRancher** [comment]
@galal-hussein Unable to customize default path for RancherOS.  Still set to /opt/rke after updating prefix_path: /foo/bar

**Comment by adingilloRancher** [comment]
Validated default path and custom path for RancherOS, B2D, CoreOS, and Ubuntu
