### ISSUE TITLE
thinpool not monitored for image garbage collection

### ISSUE THREAD

**Issue by gregath** [rancher/rke#491]
**RKE version:**

v0.1.5

**Docker version: (`docker version`,`docker info` preferred)**

Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Wed Dec 13 12:18:58 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Wed Dec 13 12:18:58 2017
 OS/Arch:         linux/amd64

Containers: 117
 Running: 56
 Paused: 0
 Stopped: 61
Images: 45
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 15.31 GB
 Data Space Total: 61.2 GB
 Data Space Available: 45.88 GB
 Metadata Space Used: 6.103 MB
 Metadata Space Total: 67.11 MB
 Metadata Space Available: 61.01 MB
 Thin Pool Minimum Free Space: 6.119 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local pxd
 Network: bridge null host overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Atomic Host 7.4.4
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 8
Total Memory: 31.26 GiB
Name: cs1-1-1
ID: LRZP:NVUT:TOPN:66AK:WMJP:LIMZ:ETQ6:LGAW:P3LL:5IY5:GAV7:FNYO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="Red Hat Enterprise Linux Atomic Host"
VERSION="7.4.4"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Atomic Host"
VARIANT_ID=atomic.host
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Atomic Host 7.4.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:atomic-host"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.4
OSTREE_VERSION=7.4.4
3.10.0-693.17.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

VMWare ESXi

**cluster.yml file:**

---
auth:
  strategy: x509

network:
  plugin: flannel
  options:
    flannel_iface: ens192
    flannel_image: rancher/coreos-flannel:v0.9.1
    flannel_cni_image: rancher/coreos-flannel-cni:v0.2.0

ssh_key_path: /deployment/secrets/cmo_key
enforce_docker_version: false
authorization:
   mode: rbac

ingress: 
  provider: none

nodes:
  - address: 172.28.148.15
    user: cmo
    hostname_override: cs1-1-1
    role: 
      - controlplane
      - worker
      - etcd
    labels:
      msi/k8s-master: true
      msi/k8s-etcd-master: true
      msi/edv-server: true
      msi/k8s-worker: true
      msi/k8s-app-ingress-ctrl: true
      msi/mgmt-worker: true
      msi/app-worker: true
      msi/dw-kafka: true
      msi/dw-couch: true
      msi/vmId: 1
      msi/serverId: 1
      msi/datacenterId: 1
  - address: 172.28.148.16
    user: cmo
    hostname_override: worker1-1-1
    role: 
      - controlplane
      - worker
      - etcd
    labels:
      msi/k8s-master: true
      msi/k8s-etcd-master: true
      msi/edv-server: true
      msi/k8s-worker: true
      msi/k8s-app-ingress-ctrl: true
      msi/mgmt-worker: true
      msi/app-worker: true
      msi/dw-kafka: true
      msi/dw-couch: true
      msi/vmId: 2
      msi/serverId: 2
      msi/datacenterId: 1
  - address: 172.28.148.17
    user: cmo
    hostname_override: worker2-1-1
    role: 
      - controlplane
      - worker
      - etcd
    labels:
      msi/k8s-master: true
      msi/k8s-etcd-master: true
      msi/edv-server: true
      msi/k8s-worker: true
      msi/k8s-app-ingress-ctrl: true
      msi/mgmt-worker: true
      msi/app-worker: true
      msi/dw-kafka: true
      msi/dw-couch: true
      msi/vmId: 3
      msi/serverId: 3
      msi/datacenterId: 1

services:
  etcd:
    image: rancher/etcd:v3.0.17
  kube-api:
    image: rancher/k8s:v1.8.7-rancher1-1
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.7-rancher1-1
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.7-rancher1-1
  kubelet:
    image: rancher/k8s:v1.8.7-rancher1-1
    cluster_domain: service.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    extra_args: 
      cgroup-driver: systemd
      fail-swap-on: false
      eviction-hard: "nodefs.available<1%,imagefs.available<1%"
      eviction-soft-grace-period: "nodefs.available=30s,imagefs.available=30s"
      eviction-soft: "nodefs.available<1%,imagefs.available<1%"
  kubeproxy:
    image: rancher/k8s:v1.8.7-rancher1-1

system_images:
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:v0.1.1
  cert_downloader: rancher/rke-cert-deployer:v0.1.1
  service_sidekick_image: rancher/rke-service-sidekick:v0.1.0
  kubedns_image: rancher/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: rancher/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: rancher/cluster-proportional-autoscaler-amd64:1.0.0

**Steps to Reproduce:**

1. Deploy kubernetes with rke using docker thinpool
1. Pull docker images until the thinpool is full

**Results:**

Images are not garbage collected. In addition, if /var/lib/docker/tmp fills up, docker images are removed 
despite not being stored in /var/lib/docker. From the logs:
`
Could not get Docker devicemapper device: exec: "dmsetup": executable file not found in $PATH
devicemapper filesystem stats will not be reported: unable to find thin_ls binary
`
This issues was also logged against kubernetes: https://github.com/kubernetes/kubernetes/issues/60662

**Comment by chestack** [comment]
Try to reproduce:
1. cd /var/lib/docker/tmp
2. fallocate -l 20G gentoo_root.img

**monitor the kubelet.log, did not find images garbage collection**(did not find following log)
```
Sep 27 14:18:27 node-1 kubelet: I0927 14:18:27.782540   20623 image_gc_manager.go:285] [imageGCManager]: Disk usage on image filesystem is at 88% which is over the high threshold (85%). Trying to free 6092960563 bytes
Sep 27 14:18:28 node-1 kubelet: I0927 14:18:28.164463   20623 image_gc_manager.go:350] [imageGCManager]: Removing image "sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2" to free 746888 bytes
Sep 27 14:18:28 node-1 dockerd-current: time="2018-09-27T14:18:28.167383571+08:00" level=error msg="Handler for DELETE /v1.26/images/sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2 returned error: conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container 9dda9c96dfb7"
```

**Comment by deniseschannon** [comment]
@gregath 

let me know if you still face this issue with the latest release, v0.2.0.
