### ISSUE TITLE
Can't access DASHBOARD through API SERVER

### ISSUE THREAD

**Issue by Luke035** [rancher/rke#521]
**RKE version:**
0.1.5

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-693.21.1.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS/EC2

**cluster.yml file:**
`nodes:
  - address: <ADDR1>
    user: centos
    role: [controlplane,worker,etcd]
    ssh_key_path: /home/kuber/invariant-orobix-us.pem
  - address: <ADDR2>
    user: centos
    role: [worker]
    ssh_key_path: /home/kuber/invariant-orobix-us.pem

ignore_docker_version: false

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2`

**Steps to Reproduce:**

1. kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
2. Install /etc/kubernetes/ssl/kube-apiserver.pem on remote browser
3. Accessing from remote browser to https://<API-SERVER-HOST>:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/ 

**Results:**
Page always shows 
`{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"https:kubernetes-dashboard:\" is forbidden: User \"system:anonymous\" cannot get services/proxy in the namespace \"kube-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "https:kubernetes-dashboard:",
    "kind": "services"
  },
  "code": 403
}`

Probably it's just a problem on x509 authentication, can you please help me in understand how to proper configure a remote browser to authenticate through the generated certificates?
Thanks

**Comment by Luke035** [comment]
I tried to install the key in my browser, without success. 
Anyway I managed to find a solution, I posted it on stackoverflow https://stackoverflow.com/questions/49918894/kubernetes-client-certificate-rke-managed

**Comment by HighwayofLife** [comment]
Thanks for sharing your solution!
