### ISSUE TITLE
Remove cluster from the cli command

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#54]
Remove the `cluster` from cli command, and just use:
```
rke up/down/upgrade
```

**Comment by sangeethah** [comment]
rke version v0.0.6-dev
command to do up and remove does not include cluster anymore.

```
./rke_darwin-amd64 up
./rke_darwin-amd64 remove
```

**Comment by alarmdev** [comment]
if you are running multiple clusters, please note and don't forget to specify --config and cluster config yaml
