### ISSUE TITLE
Reuse generated cluster certificate

### ISSUE THREAD

**Issue by Luke035** [rancher/rke#551]
Hi all,

currently I'm using `rke up` to deploy a k8s cluster and `rke remove` to delete it. When I need to restart the cluster (usually for implement something new in config file), I always need to re-generate p12 certificate for my client browser and re-install it on my pc. 
Is there any way to specify how to reuse already generated certificates?
Thanks in advance

**RKE version:**
v0.15
**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by deniseschannon** [comment]
With RKE v0.2.0, you can bring in your custom certs. 

https://rancher.com/docs/rke/latest/en/cert-mgmt/
