### ISSUE TITLE
Increase the default job retry count / sleep time

### ISSUE THREAD

**Issue by Overv** [rancher/rke#563]
The number of default retries is currently quite low (5):

https://github.com/rancher/rke/blob/e3b9389db4baa5a7b777194de4046e83e6aaa6d3/k8s/k8s.go#L14

It is easily imaginable that depending on network conditions, some containers may take more than 25 seconds to start. Could this be changed to a more reasonably amount or could the sleep time be increased?

On my current setup this low retry count is the cause of `rke up` often thinking that kubedns has failed to deploy.

**Comment by moelsayed** [comment]
This is resolved in https://github.com/rancher/rke/pull/589. This PR implements `addon_job_timeout` which should reflect a similar effect. 

This is included in #583. Closing as a duplicate.
