### ISSUE TITLE
Retrieve NSG from given credentials when generating cloud-config for Azure

### ISSUE THREAD

**Issue by superseb** [rancher/rke#575]
**RKE version:**
v0.1.6

Explore if it's possible to retrieve Network Security Group (NSG) from given credentials instead of supplying it

**Comment by galal-hussein** [comment]
in order to test this issue, you need to run rke with Azure cloud provider on azure nodes, and you need to make sure that network security group is added to the cloud-config file deployed on the hosts

**Comment by bmdepesa** [comment]
RKE v0.1.6:

Ran rke against an azure node w/ cloud provider. 
Did not set NSG in cloud config. 
Once node is active, the cloud-config displays the automatically assigned NSG.
