### ISSUE TITLE
Publish rke release as Docker image

### ISSUE THREAD

**Issue by superseb** [rancher/rke#579]
Publish each release as Docker image `rancher/rke:$TAG` and provide some instructions on how to use it.

gz#6035

**Comment by johnsockwell** [comment]
I'm willing to take a stab at this. I should be able to knock out the Dockerfile no problem. However I'll need a little help to get it worked into your CI pipeline.

Anyone willing to coach me on that aspect?

**Comment by jsduncan2** [comment]
@superseb Why did you close this issue?

**Comment by superseb** [comment]
I actually meant to remove labels to have stalebot remind everyone of this issue to see if there is still interest as it has been a while but not sure why I directly closed it.

**Comment by jsduncan2** [comment]
Gotcha, well I'm at least interested in this still.
