### ISSUE TITLE
Publish rke release as homebrew package

### ISSUE THREAD

**Issue by superseb** [rancher/rke#580]
Make it easy to install/use rke on Mac by publish homebrew package with each release.

**Comment by snics** [comment]
+1

**Comment by perriea** [comment]
+1

**Comment by johnsockwell** [comment]
If someone can point me to OSX build instructions I'd be willing to take a swing at it. This might also a candidate for a HomeBrew Cask.

**Comment by maxkorp** [comment]
Cask is for .app binaries, no? I think this just falls under the purview of brew.

**Comment by HighwayofLife** [comment]
Yes, rke would be a standard brew package, not a cask, as those are for
apps that go into the Applications folder.

**Comment by johnsockwell** [comment]
I thought the same thing, but [according to their documentation](url
https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#we-dont-like-binary-formulae), it looks like prebuilt releases should be in casks.

I'm going to pursue the prebuilt path first since I believe it will be less maintenance in the future.

**Comment by johnsockwell** [comment]
I've issued a [Pull Request](https://github.com/Homebrew/homebrew-cask/pull/52864) for the Homebrew team.

Once it's merged, you will be able to install RKE using `brew cask install rancher-kubernetes-engine`

**Comment by HighwayofLife** [comment]
That makes sense I suppose. Can you do rke as the cask?

**Comment by johnsockwell** [comment]
> That makes sense I suppose. Can you do rke as the cask?

I did, but the pull request was rejected. I've a new [open pull request](https://github.com/Homebrew/homebrew-core/pull/32723) with the hombrew-core team.

**Comment by johnsockwell** [comment]
This [pull request](https://github.com/Homebrew/homebrew-core/pull/32723) resolves #580

rke can now be installed using `brew install rke`

**Comment by CoericK** [comment]
@johnsockwell given that the 0.1.12 version was released, could the homebrew package be updated?

**Comment by johnsockwell** [comment]
Yeah, I’ll update it.

**Comment by alfonmga** [comment]
I think [installation page]( https://rancher.com/docs/rke/v0.1.x/en/installation) should be updated.

**Comment by drpebcak** [comment]
Looks like the recipe has been updated to install the `0.2.0` release, but the docs should probably be updated to point at a `0.2.x` folder, rather than the current `0.1.x` docs.

**Comment by deniseschannon** [comment]
https://rancher.com/docs/rke/latest/en/installation/#alternative-rke-macos-x-install-homebrew

We've moved the docs to `latest` as we aren't going to version the docs specifically.  Anyone want to make a PR to help update the docs in homebrew? 

The docs will redirect to latest, but having it updated is always good. :)
