### ISSUE TITLE
docker.io/rancher/hyperkube 镜像有问题

### ISSUE THREAD

**Issue by wangwj** [rancher/rke#594]
**RKE version: 
rke version v0.1.6
**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64
 Experimental:    false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-693.11.6.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**
---
nodes:
  - address: 192.168.56.201
    user: vagrant
    role:
    - controlplane
    - etcd
    ssh_key_path: ~/.ssh/id_rsa
    port: 22
  - address: 192.168.56.202
    user: vagrant
    role:
    - controlplane
    - etcd
    ssh_key_path: ~/.ssh/id_rsa
    port: 22
  - address: 192.168.56.203
    user: vagrant
    role:
    - controlplane
    - etcd
    ssh_key_path: ~/.ssh/id_rsa
    port: 22
  - address: 192.168.56.204
    user: vagrant
    role:
    - worker
    ssh_key_path: ~/.ssh/id_rsa
    port: 22
 # - address: 192.168.56.204
 #   user: vagrant
 #   role:
 #  - role
 #   internal_address: 192.168.56.204
 #   labels:
 #     app: ingress

services:
  etcd:
    # if external etcd is used
    # path: /etcdcluster
    # external_urls:
    #   - https://etcd-example.com:2379
    # ca_cert: |-
    #   -----BEGIN CERTIFICATE-----
    #   xxxxxxxxxx
    #   -----END CERTIFICATE-----
    # cert: |-
    #   -----BEGIN CERTIFICATE-----
    #   xxxxxxxxxx
    #   -----END CERTIFICATE-----
    # key: |-
    #   -----BEGIN PRIVATE KEY-----
    #   xxxxxxxxxx
    #   -----END PRIVATE KEY-----
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false
    # add additional arguments to the kubernetes component
    # Note that this WILL OVERRIDE existing defaults
    extra_args:
      # Enable audit log to stdout
      audit-log-path: "-"
      # Increase number of delete workers
      delete-collection-workers: 3
      # Set the level of log output to debug-level
      v: 4
  kube-controller:
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
  kubelet:
    cluster_domain: cluster.local
    cluster_dns_server: 10.43.0.10
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
    # Optionally define additional volume binds to a service
    extra_binds:
      - "/host/dev:/dev"
      - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
  kubeproxy:

# supported plugins are:
# flannel
# calico
# canal
# weave
#
# If you are using calico on AWS or GCE, use the network plugin config option:
# 'calico_cloud_provider: aws'
# or
# 'calico_cloud_provider: gce'
# network:
#   plugin: calico
#   options:
#     calico_cloud_provider: aws
#
# To specify flannel interface, you can use the 'flannel_iface' option:
# network:
#   plugin: flannel
#   options:
#     flannel_iface: eth1
# To specify flannel interface for canal plugin, you can use the 'canal_iface' option:
# network:
#   plugin: canal
#   options:
#     canal_iface: eth1

network:
  plugin: flannel
  options:

# At the moment, the only authentication strategy supported is x509.
# You can optionally create additional SANs (hostnames or IPs) to add to
#  the API server PKI certificate. This is useful if you want to use a load balancer
#  for the control plane servers, for example.
authentication:
  strategy: x509
  sans:
  - "10.18.160.10"
#  - "my-loadbalancer-1234567890.us-west-2.elb.amazonaws.com"

# all addon manifests MUST specify a namespace
addons: |-
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: my-nginx
      namespace: default
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
addons_include:
    - https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/rook-operator.yaml
    - https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/rook-cluster.yaml
    - /path/to/manifest

system_images:
  etcd: rancher/etcd:v3.0.17
  kubernetes: rancher/hyperkube:v1.10.1-rancher2
  alpine: rancher/rke-tools:v0.1.4
  nginx_proxy: rancher/rke-tools:v0.1.4
  cert_downloader: rancher/rke-tools:v0.1.4
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.4
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  flannel: rancher/coreos-flannel:v0.9.1
  flannel_cni: rancher/coreos-flannel-cni:v0.2.0

#ssh_key_path: ~/.ssh/test

# Kubernetes authorization mode
# Use `mode: rbac` to enable RBAC
# Use `mode: none` to disable authorization
authorization:
  mode: rbac

# If set to true, rke won't fail when unsupported Docker version is found
ignore_docker_version: false

kubernetes_version: v1.10.1

# If set, this is the cluster name that will be used in the kube config file
# Default value is "local"
cluster_name: cluster-ultra

# List of registry credentials, if you are using a Docker Hub registry,
# you can omit the `url` or set it to `docker.io`
#private_registries:
#  - url: registry.com
#    user: Username
#    password: password

# Currently only nginx ingress provider is supported.
# To disable ingress controller, set `provider: none`
# To enable ingress on specific nodes, use the node_selector, eg:
# nodes:
#   - address: example.com
#     user: ubuntu
#     role:
#     - role
#     hostname_override: node3
#     internal_address: 192.168.1.6
#     labels:
#       app: ingress
#
# ingress:
#   provider: nginx
#   node_selector:
#     app: ingress
#   extra_args:
#     enable-ssl-passthrough: ""

ingress:
  provider: nginx

#cloud_provider:
#  name: aws
**Steps to Reproduce:**
./rke up --config k8s-cluster.yml 
**Results:**
FATA[0331] [workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [192.168.56.203]: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "no such file or directory" 

备注：kubelet的镜像有问题，rancher/hyperkube:v1.10.1 有问题，换成rancher/hyperkube:v1.10.1-rancher2 也有问题

**Comment by moelsayed** [comment]
@wangwj Can you please reformat the issue? It's very hard to read in the current state.

**Comment by wangwj** [comment]
**RKE version:
rke version v0.1.6

Docker version: (docker version,docker info preferred)
Client:
Version: 1.13.1
API version: 1.26
Package version: 
Go version: go1.8.3
Git commit: 774336d/1.13.1
Built: Wed Mar 7 17:06:16 2018
OS/Arch: linux/amd64

Server:
Version: 1.13.1
API version: 1.26 (minimum version 1.12)
Package version: 
Go version: go1.8.3
Git commit: 774336d/1.13.1
Built: Wed Mar 7 17:06:16 2018
OS/Arch: linux/amd64
Experimental: false

Operating system and kernel: (cat /etc/os-release, uname -r preferred)
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-693.11.6.el7.x86_64



nodes:

address: 192.168.56.201
user: vagrant
role:
controlplane
etcd
ssh_key_path: ~/.ssh/id_rsa
port: 22
address: 192.168.56.202
user: vagrant
role:
controlplane
etcd
ssh_key_path: ~/.ssh/id_rsa
port: 22
address: 192.168.56.203
user: vagrant
role:
controlplane
etcd
ssh_key_path: ~/.ssh/id_rsa
port: 22
address: 192.168.56.204
user: vagrant
role:
worker
ssh_key_path: ~/.ssh/id_rsa
port: 22
- address: 192.168.56.204
user: vagrant
role:
- role
internal_address: 192.168.56.204
labels:
app: ingress
services:
etcd:
# if external etcd is used
# path: /etcdcluster
# external_urls:
# - https://etcd-example.com:2379
# ca_cert: |-
# -----BEGIN CERTIFICATE-----
# xxxxxxxxxx
# -----END CERTIFICATE-----
# cert: |-
# -----BEGIN CERTIFICATE-----
# xxxxxxxxxx
# -----END CERTIFICATE-----
# key: |-
# -----BEGIN PRIVATE KEY-----
# xxxxxxxxxx
# -----END PRIVATE KEY-----
kube-api:
service_cluster_ip_range: 10.43.0.0/16
pod_security_policy: false
# add additional arguments to the kubernetes component
# Note that this WILL OVERRIDE existing defaults
extra_args:
# Enable audit log to stdout
audit-log-path: "-"
# Increase number of delete workers
delete-collection-workers: 3
# Set the level of log output to debug-level
v: 4
kube-controller:
cluster_cidr: 10.42.0.0/16
service_cluster_ip_range: 10.43.0.0/16
scheduler:
kubelet:
cluster_domain: cluster.local
cluster_dns_server: 10.43.0.10
infra_container_image: gcr.io/google_containers/pause-amd64:3.0
# Optionally define additional volume binds to a service
extra_binds:
- "/host/dev:/dev"
- "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
kubeproxy:

supported plugins are:
flannel
calico
canal
weave
If you are using calico on AWS or GCE, use the network plugin config option:
'calico_cloud_provider: aws'
or
'calico_cloud_provider: gce'
network:
plugin: calico
options:
calico_cloud_provider: aws
To specify flannel interface, you can use the 'flannel_iface' option:
network:
plugin: flannel
options:
flannel_iface: eth1
To specify flannel interface for canal plugin, you can use the 'canal_iface' option:
network:
plugin: canal
options:
canal_iface: eth1
network:
plugin: flannel
options:

At the moment, the only authentication strategy supported is x509.
You can optionally create additional SANs (hostnames or IPs) to add to
the API server PKI certificate. This is useful if you want to use a load balancer
for the control plane servers, for example.
authentication:
strategy: x509
sans:

"10.18.160.10"
- "my-loadbalancer-1234567890.us-west-2.elb.amazonaws.com"
all addon manifests MUST specify a namespace
addons: |-
---
apiVersion: v1
kind: Pod
metadata:
name: my-nginx
namespace: default
spec:
containers:
- name: my-nginx
image: nginx
ports:
- containerPort: 80
addons_include:
- https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/rook-operator.yaml
- https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/rook-cluster.yaml
- /path/to/manifest

system_images:
etcd: rancher/etcd:v3.0.17
kubernetes: rancher/hyperkube:v1.10.1-rancher2
alpine: rancher/rke-tools:v0.1.4
nginx_proxy: rancher/rke-tools:v0.1.4
cert_downloader: rancher/rke-tools:v0.1.4
kubernetes_services_sidecar: rancher/rke-tools:v0.1.4
kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.5
dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.5
kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.5
kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
flannel: rancher/coreos-flannel:v0.9.1
flannel_cni: rancher/coreos-flannel-cni:v0.2.0

#ssh_key_path: ~/.ssh/test

Kubernetes authorization mode
Use mode: rbac to enable RBAC
Use mode: none to disable authorization
authorization:
mode: rbac

If set to true, rke won't fail when unsupported Docker version is found
ignore_docker_version: false

kubernetes_version: v1.10.1

If set, this is the cluster name that will be used in the kube config file
Default value is "local"
cluster_name: cluster-ultra

List of registry credentials, if you are using a Docker Hub registry,
you can omit the url or set it to docker.io
#private_registries:

- url: registry.com
user: Username
password: password
Currently only nginx ingress provider is supported.
To disable ingress controller, set provider: none
To enable ingress on specific nodes, use the node_selector, eg:
nodes:
- address: example.com
user: ubuntu
role:
- role
hostname_override: node3
internal_address: 192.168.1.6
labels:
app: ingress
ingress:
provider: nginx
node_selector:
app: ingress
extra_args:
enable-ssl-passthrough: ""
ingress:
provider: nginx

#cloud_provider:

name: aws


Steps to Reproduce:
./rke up --config k8s-cluster.yml
Results:
FATA[0331] [workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [192.168.56.203]: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "no such file or directory"

备注：kubelet的镜像有问题，rancher/hyperkube:v1.10.1 有问题，换成rancher/hyperkube:v1.10.1-rancher2 也有问题

**Comment by superseb** [comment]
Please remove this from `cluster.yml` and try again:

```
extra_binds:
- "/host/dev:/dev"
```

**Comment by wangwj** [comment]
原有测试环境不在，应该是和配置的cluster.yml有关，目前我已经通过rancher的HA方式成功部署集群 @moelsayed @superseb ,谢谢关注
