### ISSUE TITLE
Windows: time stamps don't print correctly in RKE command line output

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rke#601]
**RKE version:** 0.1.7-rc1

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Windows 10

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**cluster.yml file:**

**Steps to Reproduce:**
In Windows cmd console
Run `rke up cluster.yml` to bring up cluster

**Results:**
The time stamps don't print correctly because Linux-style terminal control does not work

```
[36mINFO[0m[0051] Kubernetes images pulled successfully
[36mINFO[0m[0051] [etcd] Building up etcd plane..
[36mINFO[0m[0051] [etcd] Pulling image [rancher/coreos-etcd:v3.1.12] on host [18.191.69.209]
[36mINFO[0m[0053] [etcd] Successfully pulled image [rancher/coreos-etcd:v3.1.12] on host [18.191.69.209]
[36mINFO[0m[0053] [etcd] Successfully started [etcd] container on host [18.191.69.209]
[36mINFO[0m[0054] [etcd] Successfully started [rke-log-linker] container on host [18.191.69.209]
[36mINFO[0m[0054] [remove/rke-log-linker] Successfully removed container on host [18.191.69.209]
[36mINFO[0m[0054] [etcd] Pulling image [rancher/coreos-etcd:v3.1.12] on host [18.219.80.138]
[36mINFO[0m[0058] [etcd] Successfully pulled image [rancher/coreos-etcd:v3.1.12] on host [18.219.80.138]
```

**Comment by cjellick** [comment]
@loganhz please assign a dev to validate the isue

**Comment by loganhz** [comment]
Verified in 0.2.0-rc8.
The time stamps print correctly in windows
