### ISSUE TITLE
kubelet 10255 isn't open

### ISSUE THREAD

**Issue by bradyjoestar** [rancher/rke#607]
I am using rke 0.1.7 to bring up the k8s cluster and it succeed.

But when I  want to using the heapster and grafana to monitor the cluster ,I found the kubelet's port 10255 isn't open.How can I solve this problem?

Thanks for your time!

**Comment by superseb** [comment]
This is a potential security risk, be sure to firewall the access to it.


```services:
  # ...
  kubelet:
    extra_args:
      read-only-port: 10255
```

**Comment by zedtux** [comment]
Working perfectly !

> be sure to firewall the access to it

Given master has IP address XX.XX.XXX.XXX and worker YYY.YYY.YY.YY, is the following correct for you ? :

```
$ ssh root@XX.XX.XXX.XXX
$ iptables -A INPUT -p tcp --dport 10255 -s YYY.YYY.YY.YY -j ACCEPT
$ iptables -A INPUT -p tcp --dport 10255 -j DROP
$ logout

$ ssh root@YYY.YYY.YY.YY
$ iptables -A INPUT -p tcp --dport 10255 -s XX.XX.XXX.XXX -j ACCEPT
$ iptables -A INPUT -p tcp --dport 10255 -j DROP
$ logout
```

**Comment by ajatkj** [comment]
> # ... kubelet: extra_args: read-only-port: 10255

Could you tell me where to add this?

**Comment by AaronFeng2014** [comment]
> This is a potential security risk, be sure to firewall the access to it.
> 
> ```
>   # ...
>   kubelet:
>     extra_args:
>       read-only-port: 10255
> ```

where should i add this

**Comment by fanux** [comment]
--read-only-port int32                                                                                      The read-only port for the Kubelet to serve on with no authentication/authorization (set to 0 to disable) (default 10255) (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)

**Comment by MoHD20** [comment]
So I'm facing this problem right now, Anyone can explain how to solve it further? I need to open 10255 for [telegraf's K8S input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kubernetes).

**Comment by fanux** [comment]
@MoHD20 https://sealyun.com/post/heapster-error/  I solved it by change heapster flags

**Comment by zedtux** [comment]
I updated the `--source` from the Kubernetes dashboard and it works, thank you @fanux
