### ISSUE TITLE
service etcd backup/restore does not being to be created in the existing cluster

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rke#619]
Hi,
to enable etcd-backup I’ve added the following lines in my cluster.yaml and re run ./rke up --config …. command on the existing cluster
```
services:
  etcd:
    backup: true
    creation: 5m0s
    retention: 24h
```
but it still doesn’t backup. Also there is no any `etcd-backup` container created after that.

**Comment by curx** [comment]
can you please post your rke version `rke -v`

**Comment by harutyundermenjyan** [comment]
```./rke_linux-amd64 -v```
`rke version v0.1.6`

**Comment by curx** [comment]
this feature is available since the v0.1.7-rc1, so please for using this feature update to the last rke release.

**Comment by harutyundermenjyan** [comment]
seem I understood the issue my etcd instances listens to public and private addresses but not to localhost
How to do that the etcd listen to all interfaces?

**Comment by harutyundermenjyan** [comment]
just I’ve tested it with clean install without selecting internal_address and it started to work properly and listening to all interfaces
but when we already have a cluster installed with internal_address the etcd-backup doesn’t work even if we commenting out internal_address and re run the `rke up --config...` command

**Comment by galal-hussein** [comment]
@harutyundermenjyan that's correct, i was able to reproduce thanks for reporting the bug

**Comment by harutyundermenjyan** [comment]
I've faced to another issue as well, that is after restoring ETCDs I got `502 Bad Gateway` and can’t login to my existing cluster

**Comment by galal-hussein** [comment]
@harutyundermenjyan i am not sure i understand the problem, how many nodes did you have?, and how did you restore the etcd from a snapshot? can you walk me through your steps exactly

**Comment by harutyundermenjyan** [comment]
I've installed the rke recently and started my tests a few days ago the number of my hosts is 7
1. installing rke with HA version 3 workers 2 controlplane 2 etcd (`./rke_linux-amd64 up --config cluster.yaml `
2. creating deployment with replicas 15(for test purposes)
3. creating etcd backup `./rke_linux-amd64 etcd backup --name snapshot --config cluster.yaml `
4. removing my cluster in order to test the restore of etcd `./rke_linux-amd64 remove --config cluster.yaml` and then removing all containers and images from hosts separately: 
```./cleanup.sh ; docker stop `docker ps |awk '{print $1}' |paste -sd' '` ; docker rm `docker ps -a |awk '{print $1}' |paste -sd' '` ; docker rmi `docker images |awk '{print $3}' |paste -sd' '` ; service docker stop && rm -rf /var/lib/docker/ ; umount -l -f /var/lib/rancher/volumes/ ; umount -l -f /var/lib/rancher ; rm -rf /var/lib/rancher ; umount -l -f /var/lib/kubelet ; service docker start && docker ps```
I've downloaded the./cleanup.sh script from @superseb repo (https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d)
4. installing the rke with the same way/config as I've described in the 1st step
5. `./rke_linux-amd64 etcd restore --name snapshot --config cluster.yaml` (after setup has been completed)
and then facing to the issue I've described above.

**Comment by harutyundermenjyan** [comment]
I've sent you the versions of my cluster.yaml by slack

**Comment by galal-hussein** [comment]
@harutyundermenjyan you should restore all etcd from the same snapshot, so you should copy the snapshot to both etcd hosts in /opt/rke/etcdbackup path, and then do the restore, also i would like to see the logs of etcd backup and restore commands

**Comment by harutyundermenjyan** [comment]
also I've noticed that when we restore the etcd from that snapshot with wrong date/time without removing the existing cluster it restores successfully but after removing the cluster and trying to restore, facing to the mentioned issue.

**Comment by harutyundermenjyan** [comment]
now it doesn't works even when we do a fresh install in the clean hosts, so when the part of the etcd-backup service exists in the cluster
```
services:
  etcd:
    backup: true
    creation: 5m0s
    retention: 24h
```
 then the setup exit with the following error
```
FATA[0044] [etcd] Failed to bring up Etcd Plane: Failed to start [etcd-backup] container on host [x.x.x.8]: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: "/opt/rke/rke-etcd-backup": stat /opt/rke/rke-etcd-backup: no such file or directory"
```

**Comment by volatilemolotov12** [comment]
Doing rke etcd restore inrke version v0.1.7-rc2 fails with

FATA[0000] Failed to create Kubernetes Client: stat ./kube_config_cluster.yml: no such file or directory

and cluster goes down (rancher local cluster) and kube-apiserver goes into a loop resulting in 100% CPU usage. Only way to fix is to redeploy the cluster

**Comment by harutyundermenjyan** [comment]
seem the etcd backup issue was solved but the restore issue still exists.
So I'm closing this issue and going to open another one relating to restoration.
Because after restore I got `502 Bad Gateway` and some of pods not in running state.
```kube-system     rke-ingress-controller-deploy-job-mvs9g   0/1       Completed   0          23m       x.x.x.13   ny-vm1-orch1-prod
kube-system     rke-kubedns-addon-deploy-job-p6brd        0/1       Completed   0          23m       x.x.x.13   ny-vm1-orch1-prod
kube-system     rke-network-plugin-deploy-job-js9nf       0/1       Completed   0          23m       x.x.x.13   ny-vm1-orch1-prod
kube-system     rke-user-addon-deploy-job-nn9kc           0/1       Completed   0          23m       x.x.x.13   ny-vm1-orch1-prod
```

**Comment by techcto** [comment]
I think I have a variant of this issue.  I get this from RKE:
FATA[0034] Failed to take etcd snapshot exit code [1]: Error waiting for container [etcd-snapshot-once] on host [*]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

I go to this host and run docker ps:

a51b387f4015        rancher/rke-tools:v0.1.8             "/opt/rke/rke-etcd-bâ¦"   28 minutes ago      Up 8 seconds                            etcd-snapshot-once

Check logs and get this:

time="2018-07-03T13:42:03Z" level=warning msg="Checking member health failed from etcd member" data="*:2379 is unhealthy: failed to connect: grpc: timed out when dialing\n" error=<nil>

**Comment by techcto** [comment]
I got passed the above, but just ended back to this thread. Restore does not seem to work on clean install, backup, restore.

I clean out everything.
I install fresh cluster with RKE
./rke etcd snapshot-save --name etcdsnapshot --config config.yaml
then
./rke etcd snapshot-restore --name etcdsnapshot --config config.yaml
and get:
FATA[0011] [etcd] Failed to restore etcd snapshot: Failed to run etcd restore container, exit status is: 3

Any ideas?

**Comment by thejmazz** [comment]
@techcto Months later but, did you check the snapshot container logs?

I had same issue and it was because I was using the old `/opt/rke/etcdbackups` instead of the new `/opt/rke/etcd-snapshots`:

```
ubuntu@rketest-master:/opt/rke$ docker logs 9cfdfda81cd9
Error:  open /opt/rke/etcd-snapshots/rke_etcd_snapshot_2018-08-05T15:48:17Z: no such file or directory
```

Docs as of right now still reference `/opt/rke/etcdbackups`...

**Comment by techcto** [comment]
@thejmazz I am not sure, I am stuck on something new and on another issue #.  Right now, if I do a clean install and then try backup/restore procedure I get hung on SSL certs.  Have you been successfully running backup and restore yet?

**Comment by Nyximus** [comment]
> [etcd-restore.log](https://github.com/rancher/rke/files/2010465/etcd-restore.log)
> etcd-backup log:
> time="2018-05-16T18:26:09Z" level=info msg="Initializing Rolling Backups" creation=5m0s retention=24h0m0s
> time="2018-05-16T18:31:10Z" level=info msg="Created backup" name="2018-05-16T18:31:09Z_etcd" runtime=105.213763ms
> _time="2018-05-16T18:31:10Z" level=warning msg="Couldn't parse backup" error="parsing time "snapshot" as "2006-01-02T15:04:05Z07:00": cannot parse "snapshot" as "2006"" name=snapshot_
> 
> in the log we see a wrong date and time but the server date and time is configured correctly
> 
> ```
> date ; hwclock 
> Wed May 16 18:52:57 UTC 2018
> Wed 16 May 2018 06:52:57 PM UTC  .010842 seconds
> ```
> 
> from where it takes this wrong date/time?

Was this ever resolved? I'm seeing this on version: rke version v0.1.15

`$ docker logs etcd-rolling-snapshots
time="2019-02-07T18:24:24Z" level=info msg="Initializing Rolling Backups" creation=5m0s retention=24h0m0s 
time="2019-02-07T18:29:25Z" level=info msg="Created backup" name="2019-02-07T18:29:24Z_etcd" runtime=126.929525ms 
time="2019-02-07T18:29:25Z" level=warning msg="Couldn't parse backup" error="parsing time \"pki.bundle.tar.gz\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"pki.bundle.tar.gz\" as \"2006\"" name=pki.bundle.tar.gz 
time="2019-02-07T18:34:24Z" level=info msg="Created backup" name="2019-02-07T18:34:24Z_etcd" runtime=110.422645ms 
time="2019-02-07T18:34:24Z" level=warning msg="Couldn't parse backup" error="parsing time \"pki.bundle.tar.gz\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"pki.bundle.tar.gz\" as \"2006\"" name=pki.bundle.tar.gz 
time="2019-02-07T18:39:24Z" level=info msg="Created backup" name="2019-02-07T18:39:24Z_etcd" runtime=93.485231ms 
time="2019-02-07T18:39:24Z" level=warning msg="Couldn't parse backup" error="parsing time \"pki.bundle.tar.gz\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"pki.bundle.tar.gz\" as \"2006\"" name=pki.bundle.tar.gz 
time="2019-02-07T18:44:24Z" level=info msg="Created backup" name="2019-02-07T18:44:24Z_etcd" runtime=97.065951ms 
time="2019-02-07T18:44:24Z" level=warning msg="Couldn't parse backup" error="parsing time \"pki.bundle.tar.gz\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"pki.bundle.tar.gz\" as \"2006\"" name=pki.bundle.tar.gz 
time="2019-02-07T18:49:24Z" level=info msg="Created backup" name="2019-02-07T18:49:24Z_etcd" runtime=94.237778ms 
time="2019-02-07T18:49:24Z" level=warning msg="Couldn't parse backup" error="parsing time \"pki.bundle.tar.gz\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"pki.bundle.tar.gz\" as \"2006\"" name=pki.bundle.tar.gz `
