### ISSUE TITLE
Apply resource limits to nginx ingress controller elements

### ISSUE THREAD

**Issue by de13** [rancher/rke#621]
**Enhancement**

**RKE version:**
```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

I noticed there is no resource definition in the nginx ingress pod:

```
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
```

Which means that pod (even if it is a daemonset) can be evicted under node pression, oom_killed or be a noisy neighbour. It can be a good practice to set requests and limits to avoid unfair issue with ingress.

**Comment by yuha0** [comment]
It is not just nginx, but also canal and metrics-server.
