### ISSUE TITLE
etcd backup and restore commands are confusing

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#628]
`rke etcd backup` and `rke etcd restore` commands should be changed to become the same as `etcdctl`'s it should become something like:
```
rke etcd snapshot-save
```
and
```
rke etcd snapshot-restore
```

**Comment by soumyalj** [comment]
Tested with rke version v0.1.8-rc1. 
Commands `rke etcd snapshot-save` and `rke etcd snapshot-restore` are functional
