### ISSUE TITLE
make release rke

### ISSUE THREAD

**Issue by yipai** [rancher/rke#647]
**RKE version:**

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**

**Results:**

**Comment by superseb** [comment]
Can you describe your issue?
