### ISSUE TITLE
rke_linux-amd64  up   cause failed info

### ISSUE THREAD

**Issue by yipai** [rancher/rke#651]
**RKE version:**rke version v0.1.7-rc6

**Docker version: (`docker version`,`docker info` preferred)**Docker version 1.13.1, build 092cba3

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Linux ncd5 3.10.0-693.21.1.el7.x86_64 centos7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** aliy

**cluster.yml file:**

**Steps to Reproduce:**

**Results:**
 Fully in accordance with the document of rancher's rke  for  the vm's config  and cluster.yml content  ,
but  rke response failed info:
  ......
  Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial to /var/run/docker.sock: ssh: rejected: administratively prohibited (open failed)

**Comment by curx** [comment]
Can you log in with the user for this vm via ssh-key?

**Comment by junkiebev** [comment]
Having the same issue and yes - I'm able to log in with the user/SSH key. The OS I'm using for the endpoints is ubuntu 17.10 and the user I'm using isn't root - it is a user account which has sudo

**Comment by superseb** [comment]
For CentOS, you can't use the `root` user to connect.

For others, `sudo` is not used, the user needs to have access to the Docker socket `/var/run/docker.sock`. Usually this means adding it to the group the socket belongs to for that OS.

**Comment by superseb** [comment]
Let me know if you need anything else on this.
