### ISSUE TITLE
rke_linux-amd64 up: Failed to set up SSH tunneling for host

### ISSUE THREAD

**Issue by pjmazenot** [rancher/rke#652]
**RKE version:**
v0.1.7

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce and 18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.1 LTS and macOS High Sierra 10.13.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Scaleway(Cloud/Bare-metal)

**cluster.yml file:**
Template from the official Rancher repo: https://raw.githubusercontent.com/rancher/rancher/58e695b51096b1f404188379cea6f6a35aea9e4c/rke-templates/3-node-externalssl-recognizedca.yml

**Steps to Reproduce:**
1. Retrieve cluster.yml file and update it with node and domain info
2. Run `./rke_darwin-amd64 up --config cluster.yml`

**Results:**
CASE 1: If the key has no passphrase
`WARN[0002] Failed to set up SSH tunneling for host [HOST_IP]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial ssh using address [Can't:22]: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

CASE 2: If the key has a passphrase (no prompt)
`WARN[0000] Failed to set up SSH tunneling for host [Can't]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial ssh using address [Can't:22]: Error configuring SSH: ssh: cannot decode encrypted private keys`

In both cases connecting to the nodes using the cli and both keys works. I also tried registering the keys with the ssh-agent to not have to enter the passphrase in the second case but it didn't change anything.

**Comment by marcusianlevine** [comment]
Also experiencing the second bug (regarding key w/ passphrase)

I think it may be related to #192 which was supposedly fixed

Here's my info:

**RKE version:**
```v0.1.7```

**Docker version: (docker version,docker info preferred)**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rexray
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1060-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795GiB
Name: ops-docker-1
ID: 5SY7:V6H3:BJSV:3OIB:7224:BJH6:FLTC:MB6D:A4G4:X53V:CUOF:WEOE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (cat /etc/os-release, uname -r preferred)**
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
Scaleway(Cloud/Bare-metal)**
AWS EC2


**Output:**
```
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [docker-1.***]
WARN[0000] Failed to set up SSH tunneling for host [docker-1.***]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial ssh using address [docker-1.***:22]: Error configuring SSH: ssh: cannot decode encrypted private keys
```

**Comment by tknecht** [comment]
same here

RKE version:
v0.1.7

**Comment by bmenant** [comment]
I confirm the issue with `rke_linux-amd64` version **v0.1.7**.
I can manually _ssh_ the nodes with those keys and `SSH_AUTH_SOCK` environment variable is set up properly. 
However, running `./rke_linux-amd64 up --config rancher-cluster.yml` ends up with a `ssh: cannot decode encrypted private keys` error.

**Comment by tknecht** [comment]
btw same is true for rke version v0.1.8-rc2

**Comment by superseb** [comment]
SSH keys with passphrase are only supported using SSH-agent. When encountering issues, please provide the used `cluster.yml`, OS, SSH version and environment variables key + value set in the environment you are running.

**Comment by tknecht** [comment]
Exdcution error code: https://gist.github.com/tknecht/a9d2914732dcfb5bd1e40449eb5176c4

rancher-cluster.yml: https://gist.github.com/tknecht/4f24edaae7071251c84d45011a205646

OS Version: Darwin host 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

SSH Version: OpenSSH_7.6p1, LibreSSL 2.6.2

**Comment by superseb** [comment]
The prompt for passphrases for private key has been removed, it only works via the SSH-agent now. This can be enabled by adding `ssh_agent_auth: true` to the root of the YAML.

**Comment by bmenant** [comment]
OS and SSH versions, environment variables: https://gist.github.com/bmenant/53579aa1eba3803856f2df46de5dc28b#file-gistfile1-txt

`rancher-cluster.yml`: https://gist.github.com/bmenant/53579aa1eba3803856f2df46de5dc28b#file-rancher-cluster-yml

**Comment by superseb** [comment]
Also added this https://github.com/rancher/rke/pull/706.

@bmenant @tknecht Can you try the suggestion above?

**Comment by bmenant** [comment]
Oops, sorry, I thought it enabled password prompting. So, yes, adding `ssh_agent_auth: true` to the root of `rancher-cluster.yml` works out well for me. Thanks!

**Comment by xu5762173** [comment]
the user rancher should be in group docker!

**Comment by Andrea1105** [comment]
I have the same problem in case 1, I am configuring a cluster with 3 servers. The error occurs when connecting two of them, the third one connects perfectly. What I can do?

**Comment by astenger** [comment]
I had the same problem on Mac OS using a manually launched ssh-agent:
SSH_AUTH_SOCK=file:///var/folders/yk/grm23ycd0qlgpp7y9h7rdj3m0000gn/T//ssh-7ftx6f3HG7IQ/agent.9003
SSH_AGENT_PID=9004

However it does work with the standard Mac OS level agent:
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.lq9uIgF5pE/Listeners
