### ISSUE TITLE
rancher2.0HA issue

### ISSUE THREAD

**Issue by miahwk** [rancher/rke#656]
when I run ./rke up, display info: 
Failed to bring up Control Plane: Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [192.168.0.104]. Response code: [403], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"kube-apiserver\" cannot get path \"/healthz\"","reason":"Forbidden","details":{},"code":403}
I try many suggestions, but failed. Can anyone help me? thx.

**Comment by superseb** [comment]
In most of the topics, the following information is requested:

- `cluster.yml` used
- `docker logs etcd`
- `docker logs kube-apiserver`

**Comment by moelsayed** [comment]
Closed for inactivity, please reopen if you have still having issues.
