### ISSUE TITLE
RKE should not check for port 2380 on etcd nodes to be accessed from control nodes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rke#658]
**RKE version: v0.1.7

**Steps to Reproduce:**

Created a custom cluster using rancher server with following configurations:
3 control nodes
3 etcd nodes
3 worked nodes

Cluster provisioning fails with following error:
```
[network] Port check for ports: [172.31.9.195:2380, 172.31.9.138:2380, 172.31.4.100:2380] failed on host: [172.31.1.214]
```
After allowing  2380 on etcd nodes to be accessed from control nodes, cluster provisioning works.

**Comment by http-teapot** [comment]
@sangeethah could you explain how you allowed `2380` on etcd nodes? It appears I am having the same problem

**Comment by bmdepesa** [comment]
rke v0.1.8-rc2

Port 2380 is not checked from control -> etcd.
