### ISSUE TITLE
Let's Encrypt with RKE

### ISSUE THREAD

**Issue by jaxxstorm** [rancher/rke#661]
There seems to be an option in the rancher docker image to get a lets encrypt certificate for the rancher service using `--acme-domain`

Is this possible with RKE?

**Comment by superseb** [comment]
There is no tight coupling anymore between Rancher and RKE for HA, RKE is used to create the cluster, after Helm is used to optionally install cert-manager and install Rancher, see https://rancher.com/docs/rancher/v2.x/en/installation/ha/
