### ISSUE TITLE
Non-standard location for `/var/log/containers`, `/var/log/pods` in RancherOS and Boot2Docker result in fluentd failed to work

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rke#662]
When deploying a cluster with RancherOS or Boot2docker etc, RKE will deploy kubelet without certain bind-mount of `/var/log/pods` and `/var/log/containers`, creates softlink inside containers like this:
```
/var/log/containers/rke-network-plugin-deploy-job-bwwl4_kube-system_rke-network-plugin-pod-xxxx.log 
-> /var/log/pods/xxx/rke-network-plugin-pod/0.log 
-> /var/lib/docker/containers/xxxx/xxx-json.log
```
https://github.com/rancher/rke/blob/master/cluster/plan.go#L347

In the Rancher OS, the `/opt/rke/var/log/containers` will be bind-mounted to `/var/log/containers` inside kubelet container. The host location is not a location that can be found or used by fluentd.

Furthermore, since the directory was bind-mounted into the kubelet as `/var/log/containers` and `/var/log/pods`, the former will contains soft link to `/var/log/pods`, not `<prefix>/var/log/pods`, make the directory `<prefix>/var/log/containers` useless on the host, when we want to see the log, will get error file not found
![image](https://user-images.githubusercontent.com/5936271/40762228-78e54900-64d2-11e8-990a-1d42a857835f.png)

If we can expose `/var/log/containers` and `/var/log/pods` on the host as soft links, fluentd can use those directory without any modification.

@galal-hussein  @yasker @cloudnautique

**Comment by sangeethah** [comment]
Tested with rke version v0.1.8-rc11

With ROS hosts , able to fetch logs from host from the following locations:
/var/log/containers/ and /var/log/pods/

[root@ip-172-31-4-147 rancher]# ls  /var/log/containers/
canal-5pvws_kube-system_calico-node-938c5587cc3e17182b725fc60cbf0e74a15fd210553b3807aa812d3becacba11.log
canal-5pvws_kube-system_install-cni-4605fc0eedf7d737d437b380d94888540dc6dbe13d07f90fd6db0ce38cedf25c.log
canal-5pvws_kube-system_kube-flannel-4a3c20cb423d30208cba945d188da75aa5089d343df6d348b5e2066e19b36573.log
canal-5pvws_kube-system_kube-flannel-567a92bcb707897fd33e47dac2c6884973b777a07e7b572ff499338c83b58614.log
nginx-ingress-controller-49nph_ingress-nginx_nginx-ingress-controller-1c78f7af3634e05cdc759e7871a398433a2afa857d2ee44151a26ffcbdc31f67.log
nginx-ingress-controller-49nph_ingress-nginx_sysctl-710369a995e86218247ce31bb6997803e76dac51b111855963e75067fd8e9f54.log
[root@ip-172-31-4-147 rancher]# ls  /var/log/pods       
63e5e216-7ee8-11e8-8b57-0248f791a802  6c785b9d-7ee8-11e8-8b57-0248f791a802
[root@ip-172-31-4-147 rancher]# 
With older version of rke , logs we not available in /var/log/containers/ and /var/log/pods/ and instead in /opt/rke/var/log/container and /opt/rke/var/log/pods/

**Comment by sandbox-services** [comment]
Also Tested with rke version v0.1.8-rc11, the cluster built by RKE can ship logs now, but clusters created by the rancher UI are still not able to, specifically in my use case an ec2 powered cluster that rancher provisions is still unable to ship logs.

`[rancher@test-a2 containers]$ ls /var/log/containers`
`[rancher@test-a2 containers]$ ls /opt/rke/var/log/containers
canal-2r4bg_kube-system_calico-node-84033be530553b4843c96cfd1cfb8928e7f7ae7a0312934ada1656522b27d129.log
canal-2r4bg_kube-system_install-cni-965e2472d11ef73cbae56b38a6de577cb82f6dade6f0f057e23209c416814a73.log
canal-2r4bg_kube-system_kube-flannel-b7bac5cfe5ce087861603b9da0e6124d2ce2ef9631d175351c64a709e634e747.log
cattle-node-agent-qbwwb_cattle-system_agent-db5cf78e7e78c63ae85582d17fc187687f4e9d5cc66183228913bff7a93a2856.log
default-http-backend-564b9b6c5b-p8h56_ingress-nginx_default-http-backend-6fb5c149cc9de157307963bbe26d78421706d801c364ac3e305b2029436b762a.log
fluentd-fcjtp_cattle-logging_fluentd-0c330c26511bc338f99db2f29e2cf041684cc07deaad103eda96762d80bd3a0d.log
fluentd-fcjtp_cattle-logging_fluentd-helper-77b6cbeaa517f42b7364af1ac4e2a66cff0408bc916cf95cdbfd73b726528543.log
kube-dns-5ccb66df65-wgl2r_kube-system_dnsmasq-92064ba38336873f46bf6021e6b1816c58957c266564a577984ce4f8fa9cc34e.log
kube-dns-5ccb66df65-wgl2r_kube-system_kubedns-4950a2fff28b8534e71d786080f05f2d675ae372e28fc61d881e0f61d02bb63f.log
kube-dns-5ccb66df65-wgl2r_kube-system_sidecar-68cc92ef1a523357d69269c5778255753fb32bc575e1b718091db30a7907f526.log
log-aggregator-grn4l_cattle-logging_log-aggregator-f3e463e4c0c74d28ba44ebd152bb175b8fce31b6faaf611d5a47273305babd5f.log
mariadb-84bff889f7-khhm6_mariadb_copy-custom-config-bc16239dab21d3119e74db001ab6001407f93c907e2ddf4178e848d0121aa077.log
mariadb-84bff889f7-khhm6_mariadb_mariadb-1eef0cdfbe36d9314741723b8d3d4a102e969a1a7a77500d92955eed23df4560.log
nginx-ingress-controller-qbvwx_ingress-nginx_nginx-ingress-controller-eeaf6a9dd6e975766b78aec4b00d6525cdb86f55f4ce0021d54bdb3f1240d737.log
nginx-ingress-controller-qbvwx_ingress-nginx_sysctl-1f5e10fe8c33976c82b5df59e77b4d3d6fb870051009603fd0a012a2972a8e74.log`
