### ISSUE TITLE
Document how to add a PodSecurityPolicy in the cluster.yml

### ISSUE THREAD

**Issue by saphoooo** [rancher/rke#670]
Enabling PodSecurityPolicy in cluster.yml results in a non functional cluster (network addon install fail), so I wonder where I have to push my PodSecurityPolicy file in cluster.yml. Can you document this part?

**Comment by galal-hussein** [comment]
pod security policy option is mentioned in cluster.yml https://github.com/rancher/rke/blob/master/cluster.yml#L47
