### ISSUE TITLE
Failed to set up SSH tunneling for host,  Error configuring SSH: asn1: structure error: integer not minimally-encoded

### ISSUE THREAD

**Issue by CarstonSchilds** [rancher/rke#671]
**RKE version:**
> `$ ./rke --version`
> rke version v0.1.7

**Docker version: (`docker version`,`docker info` preferred)**
> `$ docker version`
> Client:
>  Version:      17.03.2-ce
>  API version:  1.27
>  Go version:   go1.7.5
>  Git commit:   f5ec1e2
>  Built:        Tue Jun 27 02:21:36 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.03.2-ce
>  API version:  1.27 (minimum version 1.12)
>  Go version:   go1.7.5
>  Git commit:   f5ec1e2
>  Built:        Tue Jun 27 02:21:36 2017
>  OS/Arch:      linux/amd64
>  Experimental: false

> `$ docker info`
> Containers: 0
>  Running: 0
>  Paused: 0
>  Stopped: 0
> Images: 0
> Server Version: 17.03.2-ce
> Storage Driver: btrfs
>  Build Version: Btrfs v4.4.1
>  Library Version: 101
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins: 
>  Volume: local
>  Network: bridge host macvlan null overlay
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
> runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
> init version: 949e6fa
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 3.10.0-862.3.2.el7.x86_64
> Operating System: CentOS Linux 7 (Core)
> OSType: linux
> Architecture: x86_64
> CPUs: 16
> Total Memory: 94.24 GiB
> Name: docker-14
> ID: KBYX:3IB4:KUN6:TGU7:Z56H:65PR:KZFM:ZJQ4:BUJF:5HI6:MPS2:V27F
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
> `$ cat /etc/centos-release`
> CentOS Linux release 7.4.1708 (Core) 

>  `$ uname -r`
> 3.10.0-693.21.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

> Bare-metal

**cluster.yml file:**

> `$ cat cluster.yml`
> ```yaml
> nodes:
> - address: docker-12
>   port: "22"
>   internal_address: ""
>   role:
>   - controlplane
>   - etcd
>   - worker
>   hostname_override: ""
>   user: rancher
>   docker_socket: /var/run/docker.sock
>   ssh_key: ""
>   ssh_key_path: /secrets/rancher_rsa
>   labels: {}
> - address: docker-13
>   port: "22"
>   internal_address: ""
>   role:
>   - controlplane
>   - etcd
>   - worker
>   hostname_override: ""
>   user: rancher
>   docker_socket: /var/run/docker.sock
>   ssh_key: ""
>   ssh_key_path: /secrets/rancher_rsa
>   labels: {}
> - address: docker-14
>   port: "22"
>   internal_address: ""
>   role:
>   - controlplane
>   - etcd
>   - worker
>   hostname_override: ""
>   user: rancher
>   docker_socket: /var/run/docker.sock
>   ssh_key: ""
>   ssh_key_path: /secrets/rancher_rsa
>   labels: {}
> services:
>   etcd:
>     image: rancher/coreos-etcd:v3.1.12
>     extra_args: {}
>     extra_binds: []
>     external_urls: []
>     ca_cert: ""
>     cert: ""
>     key: ""
>     path: ""
>   kube-api:
>     image: rancher/hyperkube:v1.10.1-rancher2
>     extra_args: {}
>     extra_binds: []
>     service_cluster_ip_range: 10.43.0.0/16
>     pod_security_policy: false
>   kube-controller:
>     image: rancher/hyperkube:v1.10.1-rancher2
>     extra_args: {}
>     extra_binds: []
>     cluster_cidr: 10.42.0.0/16
>     service_cluster_ip_range: 10.43.0.0/16
>   scheduler:
>     image: rancher/hyperkube:v1.10.1-rancher2
>     extra_args: {}
>     extra_binds: []
>   kubelet:
>     image: rancher/hyperkube:v1.10.1-rancher2
>     extra_args: {}
>     extra_binds: []
>     cluster_domain: cluster.local
>     infra_container_image: rancher/pause-amd64:3.1
>     cluster_dns_server: 10.43.0.10
>     fail_swap_on: false
>   kubeproxy:
>     image: rancher/hyperkube:v1.10.1-rancher2
>     extra_args: {}
>     extra_binds: []
> network:
>   plugin: flannel
>   options: {}
> authentication:
>   strategy: x509
>   options: {}
>   sans: []
> addons: ""
> addons_include: []
> system_images:
>   etcd: ""
>   alpine: ""
>   nginx_proxy: ""
>   cert_downloader: ""
>   kubernetes_services_sidecar: ""
>   kubedns: ""
>   dnsmasq: ""
>   kubedns_sidecar: ""
>   kubedns_autoscaler: ""
>   kubernetes: ""
>   flannel: ""
>   flannel_cni: ""
>   calico_node: ""
>   calico_cni: ""
>   calico_controllers: ""
>   calico_ctl: ""
>   canal_node: ""
>   canal_cni: ""
>   canal_flannel: ""
>   wave_node: ""
>   weave_cni: ""
>   pod_infra_container: ""
>   ingress: ""
>   ingress_backend: ""
> ssh_key_path: /secrets/rancher_rsa
> ssh_agent_auth: false
> authorization:
>   mode: rbac
>   options: {}
> ignore_docker_version: false
> kubernetes_version: ""
> private_registries: []
> ingress:
>   provider: ""
>   options: {}
>   node_selector: {}
>   extra_args: {}
> cluster_name: ""
> cloud_provider:
>   name: ""
>   cloud_config: {}
> prefix_path: ""
> ```

**Steps to Reproduce:**

> `$ ./rke up`

**Results:**

> ```INFO[0000] Building Kubernetes cluster                  
> INFO[0000] [dialer] Setup tunnel for host [docker-12] 
> WARN[0000] Failed to set up SSH tunneling for host [docker-12]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial ssh using address [docker-12:22]: Error configuring SSH: asn1: structure error: integer not minimally-encoded 
> INFO[0000] [dialer] Setup tunnel for host [docker-13] 
> WARN[0000] Failed to set up SSH tunneling for host [docker-13]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial ssh using address [docker-13:22]: Error configuring SSH: asn1: structure error: integer not minimally-encoded 
> INFO[0000] [dialer] Setup tunnel for host [docker-14] 
> WARN[0000] Failed to set up SSH tunneling for host [docker-14]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial ssh using address [docker-14:22]: Error configuring SSH: asn1: structure error: integer not minimally-encoded 
> WARN[0000] Removing host [docker-12] from node lists 
> WARN[0000] Removing host [docker-13] from node lists 
> WARN[0000] Removing host [docker-14] from node lists 
> FATA[0000] Cluster must have at least one etcd plane host
> ```

**Comment by MoHD20** [comment]
Can you elaborate the problem and how you solved it?

**Comment by CarstonSchilds** [comment]
> Can you elaborate the problem and how you solved it?

The issue ended up being a malformed ssh-key,

I generated a new key with the following, and `rke up` ran without error:

 `ssh-keygen -t rsa -b 4096 -N '' -f rancher_rsa`

**Comment by xu5762173** [comment]
the user rancher should be in the group docker!
