### ISSUE TITLE
Port check should make sure that ports for network plugins are open

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke#677]
Currently port checker only check for ports between k8s components, but doesn't check for network plugin ports:

**Flannel:**

8472/UDP 

**Canal:**

8472/UDP
9099/TCP

**Calico:**

9099/TCP
179/TCP

**Weave:**

6781-6782 TCP
6783-6784 TCP, UDP

**Comment by superseb** [comment]
9099/TCP is a liveness/readiness port, that does not need to be open between nodes.
