### ISSUE TITLE
kube dns deployment scale should be increased to more than 1.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rke#68]
rke version v0.0.7-dev

Currently the kube dns deployment that gets created automatically on K8s clusters deployed with rke has scale of 1.

We should increase this scale to provide more high availability.

**Comment by moelsayed** [comment]
I enabled [kube-dns auto scaling](https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/). To test, you should have more than 4 nodes in the cluster, to be able to see more than 1 kube-dns pod.

**Comment by sangeethah** [comment]
Tested with rke verison - v0.0.8-dev

When new k8s cluster is created , kube-dns-autoscaler get deployed automatically.

When there are > 4 nodes (worker + master ), kube-dns container autoscales.

```
Sangeethas-MBP:~ sangeethahariharan1$ ./kubectl get pods -n kube-system
NAME                                   READY     STATUS    RESTARTS   AGE
kube-dns-778977457c-6rghh              3/3       Running   0          10m
kube-dns-778977457c-vc8l6              3/3       Running   0          1h
kube-dns-autoscaler-5cb4f55974-74w7z   1/1       Running   0          1h
```
