### ISSUE TITLE
Port check for host failed

### ISSUE THREAD

**Issue by mlkmhd** [rancher/rke#683]
Hi there,

I'm using rancher/rancher. after creating cluster and adding a node I'm getting this error:
`[network] Port check for ports: [198.100.101.79:10250] failed on host: [198.100.101.79]`

I opened port 10250 and all needed ports! (rancher server and rancher agent both running on the same server)

RKE version: v2.0.2

Docker version: `17.03.2-ce`

Operating system and kernel: 
Oracle Linux Server 6.8 
4.1.12-37.4.1.el6uek.x86_64

Type/provider of hosts: Bare-metal

stack trace:

 2018/06/10 14:15:16 [ERROR] Cluster c-csdqc previously failed to create
 2018/06/10 14:15:16 [INFO] cluster [c-csdqc] provisioning: Building Kubernetes cluster
 2018/06/10 14:15:16 [INFO] cluster [c-csdqc] provisioning: [dialer] Setup tunnel for host [198.100.101.79]
 2018/06/10 14:15:16 [INFO] cluster [c-csdqc] provisioning: [state] Found local kube config file, trying to get state from cluster
 2018/06/10 14:15:17 [INFO] cluster [c-csdqc] provisioning: [reconcile] Local config is not vaild, rebuilding admin config
 2018/06/10 14:15:17 [INFO] cluster [c-csdqc] provisioning: [reconcile] Rebuilding and updating local kube config
 2018/06/10 14:15:17 [INFO] cluster [c-csdqc] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-181105691/kube_config_cluster.yml]
 2018/06/10 14:15:20 [INFO] cluster [c-csdqc] provisioning: [state] Fetching cluster state from Kubernetes
 2018/06/10 14:15:50 [INFO] cluster [c-csdqc] provisioning: Timed out waiting for kubernetes cluster to get state
 2018/06/10 14:15:50 [INFO] cluster [c-csdqc] provisioning: [network] Deploying port listener containers
 2018/06/10 14:15:50 [INFO] cluster [c-csdqc] provisioning: [network] Port listener containers deployed successfully
 2018/06/10 14:15:50 [INFO] cluster [c-csdqc] provisioning: [network] Running control plane -> etcd port checks
 2018/06/10 14:15:51 [INFO] cluster [c-csdqc] provisioning: [network] Successfully started [rke-port-checker] container on host [198.100.101.79]
 2018/06/10 14:15:51 [INFO] cluster [c-csdqc] provisioning: [network] Running control plane -> worker port checks
 2018/06/10 14:15:51 [INFO] cluster [c-csdqc] provisioning: [network] Successfully started [rke-port-checker] container on host [198.100.101.79]
 2018/06/10 14:15:54 [ERROR] cluster [c-csdqc] provisioning: [network] Port check for ports: [198.100.101.79:10250] failed on host: [198.100.101.79]`

**Comment by superseb** [comment]
This is a Rancher 2.0 issue, please file future issues regarding Rancher in the `rancher/rancher` repository. When using `rke` CLI, it can be filed here. It sounds like you are hitting https://github.com/rancher/rancher/issues/13822, if not, please file a new issue with steps to reproduce in the `rancher/rancher` repository.
