### ISSUE TITLE
it’s not possible to select a container if they are several

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rke#685]
it’s not possible to select a container if they are several, instead it selects one of them automatically. So we can't select another one and execute a shell for instance.
<img width="1271" alt="screen shot 2018-06-12 at 4 39 38 pm" src="https://user-images.githubusercontent.com/16855630/41292157-d3dca526-6e62-11e8-9d1f-5800845c1f5c.png">

**Comment by superseb** [comment]
Please file it under `rancher/rancher` and specify what version you are using.
