### ISSUE TITLE
Wrong Openstack generated cloud config file

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rancher/rke#689]
**RKE version:**

v0.1.8-rc1

Not RKE fault, because the Kubernetes doc is wrong.

The [Router] section doesn't exist and is named the [Route] section when using cloud config file for OpenStack.

When using [Router] section, kubelet just crash:

```
F0613 16:21:17.614260   15147 server.go:233] failed to run Kubelet: could not init cloud provider "openstack": warnings:
can't store data at section "Router"
can't store data at section "Router"
```

See the Goland code in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go

```go
type Config struct {
	Global struct {
		AuthURL    string `gcfg:"auth-url"`
		Username   string
		UserID     string `gcfg:"user-id"`
		Password   string
		TenantID   string `gcfg:"tenant-id"`
		TenantName string `gcfg:"tenant-name"`
		TrustID    string `gcfg:"trust-id"`
		DomainID   string `gcfg:"domain-id"`
		DomainName string `gcfg:"domain-name"`
		Region     string
		CAFile     string `gcfg:"ca-file"`
	}
	LoadBalancer LoadBalancerOpts
	BlockStorage BlockStorageOpts
	Route        RouterOpts
	Metadata     MetadataOpts
}
```

I guess https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/rke_types.go need to be corrected with the right section name.

**Comment by greatbn** [comment]
@sebastien-prudhomme  Could you show me show cloud-provider config in your cluster.yml file?

**Comment by galal-hussein** [comment]
@sebastien-prudhomme the kubernetes documentation mentioned that its name is [router] https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#openstack

**Comment by greatbn** [comment]
@galal-hussein I have same issue with @sebastien-prudhomme

**Comment by greatbn** [comment]
I think this is bug in kubernetes documents, after change Router to Route and restart kubelet container. kubelet can start

**Comment by sebastien-prudhomme** [comment]
As i said the Kubernetes doc is wrong

**Comment by sebastien-prudhomme** [comment]
See this commit comment on Kubernetes: https://github.com/kubernetes/kubernetes/commit/0b57371ffab5b32dc991ff5fe60c3d58f7c2f9cc#diff-694c675fe77b09923cc453e7228f8fa8

**Comment by galal-hussein** [comment]
@sebastien-prudhomme okay thanks for raising the issue, i will add a fix for this problem

**Comment by sebastien-prudhomme** [comment]
I guess using the customCloudProvider as a workaround should work, will test it tommorow.

**Comment by sebastien-prudhomme** [comment]
I confirm using customCloudProvider seems to work (at least kubelet does't crash)

```
cloud_provider:
  name: openstack
  customCloudProvider: |-
    [Global]
    auth-url    = xxxxxxxxx
    username    = xxxxxxxxx
    password    = xxxxxxxxx
    tenant-name = xxxxxxxxx
    domain-name = xxxxxxxxx
    region      = xxxxxxxxx
```

**Comment by sebastien-prudhomme** [comment]
@galal-hussein  I've submitted a patch in rancher/types.

The RKE documentation need to be corrected but i've seen that you have another PR about cloud configuration. Can you add the correction into your PR?

**Comment by deniseschannon** [comment]
@sebastien-prudhomme Thank you for your PR and attempts with openstack. Could you test with v0.1.8-rc3 to ensure that openstack cloud provider is now working as expected?

I am working on switching all RKE docs into our official docs site and will make a PR to change it here: https://github.com/rancher/docs/blob/master/content/rke/v0.1.x/en/config-options/cloud-providers/_index.md#openstack

**Comment by deniseschannon** [comment]
@sebastien-prudhomme it's part of this PR to update docs: https://github.com/rancher/docs/pull/324/files#diff-a620746a00ac2fb7535e7a5a6146939dR175

**Comment by sebastien-prudhomme** [comment]
@deniseschannon No problem with v0.1.8-rc3, at least with the way RKE is generating cloud config file for Kubelet. Kubelet is running fine, no more crash. Thanks a lot.
