### ISSUE TITLE
Role for worker nodes is reported as "none".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rke#69]
rke version v0.0.7-dev

Steps to reproduce the problem:
Create a K8s cluster with nodes in control plane , worker and etcd plane.
Role of worker nodes is reported as "none"

```
Sangeethas-MBP:~ sangeethahariharan1$ ./kubectl get nodes
NAME                                                 STATUS    ROLES     AGE       VERSION
<node-name1>                                        Ready     <none>    15h       v1.8.3-rancher1
<node-name2>                                        Ready     master    15h       v1.8.3-rancher1
<node-name3>                                        Ready     <none>    15h       v1.8.3-rancher1
Sangeethas-MBP:~ sangeethahariharan1$ 
```

**Comment by galal-hussein** [comment]
new release v0.0.8-dev display all roles including: worker, master, and etcd, however a known limitation is that once the node is labeled, this label will not be changed until the node is deleted/readded as kubernetes node

**Comment by sangeethah** [comment]
Tested with rke verison - v0.0.8-dev

When node gets added to the cluster for the first time , roles are reflected as expected.

```
NAME    STATUS    ROLES         AGE       VERSION
<node1>   Ready     etcd,master   2m        v1.8.3-rancher3
<node2>   Ready     master        2m        v1.8.3-rancher3
<node3>     Ready     worker        1m        v1.8.3-rancher3
```

**Comment by GopinathKarthikeyan** [comment]
you can manually label the node, using below command.

kubectl label node <node_name> node-role.kubernetes.io/worker=worker
