### ISSUE TITLE
After removal the worker role from controlplane nodes role list in cluster.yml file and rerun rke up command in order to remove the worker role from the controlplane nodes, the worker role still present in controlplane nodes role.

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rke#693]
Seems it's a bug can't remove the worker role from controlplane nodes.
rke v0.1.8-rc2

**Comment by superseb** [comment]
@moelsayed @galal-hussein Can you confirm/deny support for adding/removing roles currently?

**Comment by galal-hussein** [comment]
@superseb adding and removing roles should be supported normally, @harutyundermenjyan can you describe the bug, what did you mean by the worker role still present, how did you confirm that.. the only thing should be different is that the node will be unschedulable and will contain the NoExecute Taint.

**Comment by harutyundermenjyan** [comment]
I'll try to detail as you asked
First I've run rke with `role: [controlplane,worker]` selected for controlplane nodes, then tried to isolate my workers by removing `worker` role from that list for controlplane nodes and then rerun the `./rke up ....` with `role: [controlplane]` without `worker` for my controlplane nodes but still the worker role present in that controplane nodes.
It works with etcd normally, i.e. if I'm adding worker role for etcd nodes it adds normaly and then if I remove from role list and rerun `rke up ....` it removes normally but with controlplane no.
You can try to remove `worker` role from your existing controlplane nodes and the issue will be more clear for you.

**Comment by harutyundermenjyan** [comment]
seems it shows the worker role wrongly on web UI only, but with kubectl it shows that the role was removed normally from controlplane nodes as well.
see the screenshots, on web interface the worker role is still present for controlplane nodes but with kubectl it's not.
<img width="811" alt="screen shot 2018-06-18 at 5 06 34 pm" src="https://user-images.githubusercontent.com/16855630/41538073-5a35e792-731b-11e8-8d7a-560b1b4eface.png">
<img width="494" alt="screen shot 2018-06-18 at 5 15 09 pm" src="https://user-images.githubusercontent.com/16855630/41538074-5a65d43e-731b-11e8-82eb-35848e71c9db.png">

**Comment by galal-hussein** [comment]
@harutyundermenjyan can you reopen this issue in rancher/rancher repo, it doesn't seem to be a RKE issue, closing this issue.

**Comment by harutyundermenjyan** [comment]
OK thanks,
opened, track here: https://github.com/rancher/rancher/issues/14133
