### ISSUE TITLE
Access etcd cluster from within a pod/ingress

### ISSUE THREAD

**Issue by gaui** [rancher/rke#694]
How can I access the etcd cluster from within a pod/ingress? I have Traefik as an ingress and trying to configure it to use etcd as a backend to store configuration. I don't want to depend on a IP address, instead if I could access the etcd cluster with a hostname via kube-dns, something like `etcd.kube-system.svc.cluster.local` or something like that. Is this possible?

**Comment by superseb** [comment]
You shouldn't use the cluster etcd for anything else than the cluster, it's the most vital part of your cluster and you shouldn't let apps be using that most vital part as it can take your etcd down. 

We run etcd via Docker, and build the connection string dynamically on the presence of hosts with the `etcd` role, and it is using client certificates to access it.
