### ISSUE TITLE
Run RKE on a single node to add to the cluster

### ISSUE THREAD

**Issue by HighwayofLife** [rancher/rke#710]
RKE currently runs against your entire cluster, but when the desire is to add or cleanup (remove) a single node in that cluster, it is unnecessary to run RKE against every node that exists.
Would be nice to have the ability to run rke in a running cluster to add a single node. This might have to apply only to worker nodes if the etcd or control planes all need to be aware of each other.

**Comment by superseb** [comment]
@galal-hussein You added `update-only` for updating workers only, right? 

```
+		cli.BoolFlag{
+			Name:  "update-only",
+			Usage: "Skip idempotent deployment of control and etcd plane",
+		},
```

**Comment by galal-hussein** [comment]
@HighwayofLife @superseb yes using `update-only` will only update the workers and should skip running rke on control or etcd.

**Comment by willmao** [comment]
it is quite useful for rke to add/remove single node to the cluster, if one node is down and unreachable, `rke up --update-only` will fail, in this case, we want to remove the dead node and add other node to replace it.

it is also useful when cluster auto-scaling.
