### ISSUE TITLE
Istio automatic sidecar injection doesn't seem to work

### ISSUE THREAD

**Issue by saphoooo** [rancher/rke#726]
**RKE version:**
rke version v0.1.7
**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-128-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM
**cluster.yml file:**
nodes:
- address: 192.168.1.130
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
- address: 192.168.1.131
  port: "22"
  internal_address: ""
  role:
  - worker
  - etcd
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
- address: 192.168.1.132
  port: "22"
  internal_address: ""
  role:
  - worker
  - etcd
  hostname_override: ""
  user: ubuntu
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
services:
  etcd:
    image: rancher/coreos-etcd:v3.1.12
    extra_args: {}
    extra_binds: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: false
    retention: ""
    creation: ""
  kube-api:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args:
      requestheader-client-ca-file: /etc/kubernetes/ssl/kube-ca.pem
      requestheader-allowed-names:
      requestheader-extra-headers-prefix: X-Remote-Extra-
      requestheader-group-headers: X-Remote-Group
      requestheader-username-headers: X-Remote-User
      proxy-client-cert-file: /etc/kubernetes/ssl/kube-ca.pem
      proxy-client-key-file: /etc/kubernetes/ssl/kube-ca-key.pem
    extra_binds: []
    service_cluster_ip_range: 10.43.0.0/16
    pod_security_policy: false
  kube-controller:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args: {}
    extra_binds: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args: {}
    extra_binds: []
  kubelet:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args:
      authentication-token-webhook: true
      volume-plugin-dir: /var/lib/kubelet/volumeplugins
    extra_binds:
      - /var/lib/kubelet/volumeplugins:/var/lib/kubelet/volumeplugins
      - /dev:/dev
    cluster_domain: cluster.local
    infra_container_image: rancher/pause-amd64:3.1
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args: {}
    extra_binds: []
network:
  plugin: canal
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: ""
  alpine: ""
  nginx_proxy: ""
  cert_downloader: ""
  kubernetes_services_sidecar: ""
  kubedns: ""
  dnsmasq: ""
  kubedns_sidecar: ""
  kubedns_autoscaler: ""
  kubernetes: ""
  flannel: ""
  flannel_cni: ""
  calico_node: ""
  calico_cni: ""
  calico_controllers: ""
  calico_ctl: ""
  canal_node: ""
  canal_cni: ""
  canal_flannel: ""
  wave_node: ""
  weave_cni: ""
  pod_infra_container: ""
  ingress: ""
  ingress_backend: ""
ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: true
kubernetes_version: ""
private_registries: []
ingress:
  provider: "none"
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: ""
cloud_provider:
  name: ""
  cloud_config: {}
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
**Steps to Reproduce:**
Install Istio with automatic sidecar injection, label namespace istio-injection=enabled
**Results:**
When deploying an app, there is no automatic sidecar injection.

**Comment by saphoooo** [comment]
I just figure out that admission-control doesn't contain expected flags:

**current** 

`"--admission-control=ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds"`

**expected**

`"--admission-control=ServiceAccount,NamespaceLifecycle,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds"`

**Comment by superseb** [comment]
Here's an example of creating a cluster in Rancher 2 for that, basically a JSON representation of cluster.yml: https://gist.githubusercontent.com/superseb/0c5e4015985f470853f0a74427c306c7/raw/be7886d49d595bd738d99f4e9b4fdbdbd16db525/istiocluster.sh

**Comment by de13** [comment]
Thanks but I'm not using rancher, only rke. Setting up the proper flags makes the automatic injection working:

```
  kube-api:
    image: rancher/hyperkube:v1.10.1-rancher2
    extra_args:
      admission-control: "ServiceAccount,NamespaceLifecycle,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds"
```

I wonder why these flags are not enabled by default.

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/13162
