### ISSUE TITLE
Log clean up isn't happening after remove/up cycle

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rke#733]
**RKE version:**
v0.1.8-rc6
**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 17.10 
**Steps to Reproduce:**

1. rke up --local --ignore-docker-version
1. rke remove --local --ignore-docker-version
1. rke up --local --ignore-docker-version

**Results:**
The links for the logs of the first RKE cluster are still present after bringing up the second cluster. Really during the `rke remove` it should get cleaned up.

**Comment by adingilloRancher** [comment]
v0.1.8-rc11

Validated logs are removed.
```
root@austinRKE:/var/lib/rancher/rke/log# ls
etcd_0e812a7140c4f12228fb5f2928f40cd4b5698cbe7f42264bcc8c469386de6c30.log
kube-apiserver_4245671fabc336f2bf2df22e22bd4ebab5c6a52cf38f6be026836b89f8c6c824.log
kube-controller-manager_d828f41fe9842ef856cf29750b0de7fa302790e9b41034903200bfade94a4ec1.log
kube-scheduler_538976a11113df16cf88763735b20a1f281b457b3b1694c3ca9955aa24b2269d.log
root@austinRKE:/var/lib/rancher/rke/log# ls
root@austinRKE:/var/lib/rancher/rke/log# 
```
