### ISSUE TITLE
Is it safe to upgrade system_images of cluster.yml?

### ISSUE THREAD

**Issue by arnadusable** [rancher/rke#737]
**RKE version:**
v0.1.5
**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS : 4.4.0-128-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**cluster.yml file:**
...
system_images:
  etcd: rancher/etcd:v3.0.17
  kubernetes: rancher/k8s:v1.8.7-rancher1-1
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:v0.1.1
  cert_downloader: rancher/rke-cert-deployer:v0.1.1
  kubernetes_services_sidecar: rancher/rke-service-sidekick:v0.1.0
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
...
**Steps to Reproduce:**
/

I'm currently running a v1.8.7 kubernetes cluster using the v0.1.5 rke.
Everything is fine and working properly since 3 months now.

I would like to upgrade the version of RKE to 0.1.7 to use the etcd cluster backup feature introduced in that version.
I would also like to upgrade my rancher cluster to 1.10 to benefit from its additionnal features.

However, I'm quite concerned about upgrading the rke CLI. 
When I try  to use the new rke CLI (v1.0.7) by typing:
./rke up

It fails with error messages of the cert-deployer: 
 "Failed to start Certificates deployer container on host"

I think it's because the rke cli expects other kind of system_images, as stated in the doc here: https://rancher.com/docs/rke/v0.1.x/en/config-options/system-images/

`As versions of RKE are released, the tags on these images will no longer be up to date. This list is specific for v1.10.3-rancher2.`

However I'm quite concerned about upgrading all my images. It is a production cluster and I can't afford having a crash for a long period of time. 

Is it safe to upgrade system_images ?

**Comment by moelsayed** [comment]
@arnadusable You can remove the versions you have already in the cluster.yml file. The RKE will fill in with the defaults for the version you will be using.

**Comment by galal-hussein** [comment]
Closing the issue, please reopen if you have any more questions @arnadusable
