### ISSUE TITLE
The heapster component in dashboard cannot access the apiserver

### ISSUE THREAD

**Issue by saiJPlus** [rancher/rke#739]
**RKE version:**
v0.1.5
**Docker version: (`docker version`,`docker info` preferred)**
17.03
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos7.4
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**

this is my heapster config file:
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: heapster
  name: heapster
  namespace: kube-system
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heapster
  labels:
    k8s-app: heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: heapster
    namespace: kube-system
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: registry.cn-hangzhou.aliyuncs.com/magina-k8s/heapster-amd64:v1.3.0
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default?inClusterConfig=false
        - --sink=influxdb:http://monitoring-influxdb:8086
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
**Results:**

E0621 07:52:52.067222       1 reflector.go:190] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *v1.Namespace: Get https://kubernetes.default/api/v1/namespaces?resourceVersion=0: x509: certificate signed by unknown authority

**guess:**

heapster need certificate i dont know  where rke put the certificate

**Comment by superseb** [comment]
This repository (https://github.com/JasonvanBrackel/metrics-server-on-rancher-2.0.2) is used to configure metrics-servers on Rancher 2 custom clusters, and partly uses Heapster as shown here (https://github.com/superseb/metrics-server/commit/96c03399a3dcbbd2ed5feda4a0b8fa061f7a5c04)

If you want to use certificates, they are stored in `/etc/kubernetes/ssl`

**Comment by travisghansen** [comment]
Also ran into this when attempting to deploy https://github.com/kubernetes-incubator/metrics-server into an rke-generated cluster.

**Comment by superseb** [comment]
Let me know if there is anything needed on this.
