### ISSUE TITLE
openstack cloud provider config is empty

### ISSUE THREAD

**Issue by curx** [rancher/rke#741]
**RKE version:**
v0.1.7
**Docker version: (`docker version`,`docker info` preferred)**
 17.09.1-ce, build 19e2cf6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.3.0 / 4.9.80-rancher
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack
**cluster.yml file:**
relevant config, see http://staging.rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/#openstack add to cluster.yml 
**Steps to Reproduce:**
rke up ...
**Results:**
cloud-config.json is empty and services like kubelet are'nt working andkube-controller-manager is in a restarting loop 

$ sudo ls -al /opt/rke/etc/kubernetes/cloud-config.json 
-rw-------    1 root     root             1 Jun 29 16:17 /opt/rke/etc/kubernetes/cloud-config.json
$ sudo cat  /opt/rke/etc/kubernetes/cloud-config.json   
(empty)

docker inspect kubelet | grep cloud
...
       "--cloud-provider=openstack",
       "--cloud-config=/etc/kubernetes/cloud-config.json",
...

rke -d up
...
INFO[0053] [cloud] Deploying cloud config file to node [192.168.122.148] 
DEBU[0053] [remove/cloud-config-deployer] Checking if container is running on host [192.168.122.148] 
DEBU[0053] [remove/cloud-config-deployer] Container doesn't exist on host [192.168.122.148] 
DEBU[0053] [cloud] Checking image [rancher/rke-tools:v0.1.8] on host [192.168.122.148] 
DEBU[0053] Checking if image [rancher/rke-tools:v0.1.8] exists on host [192.168.122.148] 
DEBU[0053] Image [rancher/rke-tools:v0.1.8] exists on host [192.168.122.148] 
DEBU[0053] [cloud] No pull necessary, image [rancher/rke-tools:v0.1.8] exists on host [192.168.122.148] 
INFO[0053] [cloud] Successfully started [cloud-config-deployer] container on host [192.168.122.148] 
DEBU[0053] [remove/cloud-config-deployer] Checking if container is running on host [192.168.122.148] 
DEBU[0053] [remove/cloud-config-deployer] Stopping container on host [192.168.122.148] 
DEBU[0053] [remove/cloud-config-deployer] Removing container on host [192.168.122.148] 
INFO[0053] [remove/cloud-config-deployer] Successfully removed container on host [192.168.122.148] 
DEBU[0053] [cloud] Successfully started cloud config deployer container on node [192.168.122.148] 
INFO[0053] [cloud] Successfully deployed kubernetes cloud config to Cluster nodes 
...

Regards,
Thorsten

**Comment by sebastien-prudhomme** [comment]
Use the 0.18 release candidate, it has all the fixes for OpenStack, and the documentation is for that version.

**Comment by curx** [comment]
Thanks @sebastien-prudhomme , the RC fixed the issues.
