### ISSUE TITLE
Update Etcd default version to 3.3.x to facilitate Prometheus monitoring

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rancher/rke#753]
RKE version: 0.17

Etcd cluster is configured with client cert authentification, which is good for security but prevents  Prometheus from scraping metrics as it has no dedicated client cert for that.

One solution is to use the "--listen-metrics-urls" that enable another port dedicated to monitoring and that is not using client cert authentification.

That option is available starting from Etcd 3.3.x (coreos/etcd#8242) and RKE uses by default Etcd 3.1.12.

**Comment by superseb** [comment]
We follow the validated etcd for a k8s release as stated in their changelog. For 1.10 this is 3.1.12, and for 1.11 this is 3.2.18.

It seems etcd 3.3 will be supported for 1.12, see https://github.com/kubernetes/kubernetes/issues/61326. 

Of course you are free to pick your own etcd version for your cluster.

**Comment by sebastien-prudhomme** [comment]
@superseb Ok, i understand.

**Comment by sebastien-prudhomme** [comment]
For information: i succesfully upgraded to v3.2 and then to v3.3, each time making an etcd snapshot with RKE.

See no regressions yet.

**Comment by estevao90** [comment]
@sebastien-prudhomme, how do you configured RKE to add the extra parameter --listen-metrics-urls in etcd?

Thanks!

**Comment by sebastien-prudhomme** [comment]
@estevao90, in the cluster config:

```
services:
  etcd:
    extra_args:
      listen-metrics-urls: http://0.0.0.0:2381
```
