### ISSUE TITLE
Failed to restore etcd snapshot: Failed to run etcd restore container, exit status is: 3

### ISSUE THREAD

**Issue by techcto** [rancher/rke#768]
rke version v0.1.8

Docker Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.6

4.14.47-64.38.amzn2.x86_64
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

https://s3.amazonaws.com/kub88-rke/config.yaml 

0. Start with 3 instances at AWS
1. ./rke up --config config.yaml (Please feel free to test with my config.  Just let me know so I can stay off. This is a test account, so no sensitive data.)
2. ./rke etcd snapshot-save --name etcdsnapshot --config config.yaml
3. Pick one server, copy etcdsnapshot onto other 2 instances
4. ./rke etcd snapshot-restore --name etcdsnapshot --config config.yaml

Failure:

INFO[0010] [etcd] Restoring [etcdsnapshot] snapshot on etcd host [54.175.184.90]
INFO[0010] [etcd] Successfully started [etcd-restore] container on host [54.175.184.90]
INFO[0011] [etcd] Restoring [etcdsnapshot] snapshot on etcd host [54.174.94.151]
INFO[0011] [etcd] Successfully started [etcd-restore] container on host [54.174.94.151]
FATA[0011] [etcd] Failed to restore etcd snapshot: Failed to run etcd restore container, exit status is: 3

It always stops on second/third server.  I am not sure where the error is.  But this is is a simple backup and restore on 3 existing instances.  Please let me know if I am missing something.

**Comment by galal-hussein** [comment]
can you check the etcd-restore logs on the failed instance:
```
docker logs etcd-restore
```

**Comment by techcto** [comment]
Not sure which server, but I am guessing the second server based on the output.  This is what I get from server 2:

Error:  data-dir "/opt/rke/etcd-snapshots-restore/" exists
Error:  data-dir "/opt/rke/etcd-snapshots-restore/" exists
Error:  data-dir "/opt/rke/etcd-snapshots-restore/" exists
Error:  data-dir "/opt/rke/etcd-snapshots-restore/" exists
Error:  data-dir "/opt/rke/etcd-snapshots-restore/" exists

**Comment by galal-hussein** [comment]
@techcto thanks for sharing the logs, i think this is a bug i will put a fix to it, as a work around for now you can remove this directory on the host:
```
mv /opt/rke/etcd-snapshots-restore /opt/rke/etcd-snapshots-restore-old
```

**Comment by techcto** [comment]
I dont think that works.  I first tried moving, then I tried deleteing, but it still throws the same error:

INFO[0015] [etcd] Restoring [etcdsnapshot] snapshot on etcd host [54.175.184.90]
INFO[0016] [etcd] Successfully started [etcd-restore] container on host [54.175.184.90]
INFO[0017] [etcd] Restoring [etcdsnapshot] snapshot on etcd host [54.174.94.151]
INFO[0018] [etcd] Successfully started [etcd-restore] container on host [54.174.94.151]
FATA[0018] [etcd] Failed to restore etcd snapshot: Failed to run etcd restore container, exit status is: 3
Command '['/tmp/bin/rke', 'etcd', 'snapshot-restore', '--name', 'etcdsnapshot', '--config', '/tmp/config.yaml']' returned non-zero exit status 1
Restore failed!

then I run:
docker logs etcd-restore

and get:
Error:  data-dir "/opt/rke/etcd-snapshots-restore/" exists

and prior to running:

./rke etcd snapshot-restore --name etcdsnapshot --config config.yaml

I made sure to first delete the folder:
rm -Rf /opt/rke/etcd-snapshots-restore

And then upload the same copy of the snapshot to each server

Any ideas for things to try?

**Comment by techcto** [comment]
I was very hopeful.  It keeps stopping on second server for some reason.  Here is what I got.

Everything same as above, but this time I also added:

Connected to 54.86.202.214
Executing rm -Rf /opt/rke/etcd-snapshots-restore
Executing docker rm etcd-restore
Error: No such container: etcd-restore

I got this error on all three servers.  However, I ran this command manually on the second server before updating my script, and it was there for deletion.  I am sure if I ran script again, it would delete on second server.  It seems this container is hanging when the restore dies.  But it does not seem to be the cause.  I have tested a few times and it always seems to be second server.  I can try to delete this server and elect a new second server if you like.

Final error:

INFO[0016] [remove/rke-log-cleaner] Successfully removed container on host [54.86.202.214]
INFO[0016] [hosts] Successfully cleaned up host [54.86.202.214]
INFO[0016] [etcd] Restoring [etcdsnapshot] snapshot on etcd host [54.175.184.90]
INFO[0017] [etcd] Successfully started [etcd-restore] container on host [54.175.184.90]
INFO[0019] [etcd] Restoring [etcdsnapshot] snapshot on etcd host [54.174.94.151]
INFO[0019] [etcd] Successfully started [etcd-restore] container on host [54.174.94.151]
FATA[0020] [etcd] Failed to restore etcd snapshot: Failed to run etcd restore container, exit status is: 3
Command '['/tmp/bin/rke', 'etcd', 'snapshot-restore', '--name', 'etcdsnapshot', '--config', '/tmp/config.yaml']' returned non-zero exit status 1
Restore failed!

**Comment by techcto** [comment]
I built that into my script I am developing to run RKE for AWS.  So before I run restore, I am now:

1. rm /opt/rke/etcd-snapshots-restore/
2. docker rm etcd-restore
3. Upload same etcdsnapshot to each server
4. ./rke etcd snapshot-restore --name etcdsnapshot --config config.yaml

So, yes, I have tried this sequence on all 3 servers and I get this error.  I just decided to terminate that second instance, so a new once is coming up now.  I have everything in place to heal the cluster once this new server comes online, but obviously if restore fails the cluster is corrupted.  So I have to run rke remove / up to get a fresh cluster. Then I can run my script again.  

Do you have any other ideas for me to try in script while I wait for new cluster to come online.  Also, I can get you access if you need to the servers. I am building this on AWS Linux 2.0, so that has presented several odd challenges so far.

**Comment by techcto** [comment]
Maybe some good news, the error changed after I deleted the second instance.  I have moved on to the cert error.  I thought I read about that.  Any command ideas?

INFO[0027] [etcd] Saving snapshot [etcd-rolling-snapshots] on host [34.224.40.87]
INFO[0028] [certificates] Successfully started [rke-bundle-cert] container on host [34.224.40.87]
FATA[0028] [etcd] Failed to bring up Etcd Plane: Failed to run certificate bundle compress, exit status is: 1
Command '['/tmp/bin/rke', 'etcd', 'snapshot-restore', '--name', 'etcdsnapshot', '--config', '/tmp/config.yaml']' returned non-zero exit status 1

**Comment by techcto** [comment]
And to make matters worse, there must be something else going on.  I must have ran rke up / remove 400 times now, and never has it had issues.  Now when I run:

./rke remove --config config.yaml

I get:

INFO[0027] [hosts] Cleaning up host [34.224.40.87]
INFO[0027] [hosts] Cleaning up host [34.224.40.87]
INFO[0027] [hosts] Running cleaner container on host [34.224.40.87]
INFO[0028] [kube-cleaner] Successfully started [kube-cleaner] container on host [34.224.40.87]
INFO[0028] [hosts] Removing cleaner container on host [34.224.40.87]
INFO[0028] [hosts] Removing dead container logs on host [34.224.40.87]
INFO[0029] [cleanup] Successfully started [rke-log-cleaner] container on host [34.224.40.87]
INFO[0029] [remove/rke-log-cleaner] Successfully removed container on host [34.224.40.87]
INFO[0029] [hosts] Successfully cleaned up host [34.224.40.87]
INFO[0029] Removing local admin Kubeconfig: ./kube_config_config.yaml
INFO[0029] Local admin Kubeconfig removed successfully
INFO[0029] Cluster removed successfully

And then

./rke up --config config.yaml

and get

INFO[0032] [etcd] Saving snapshot [etcd-rolling-snapshots] on host [34.224.40.87]
INFO[0033] [certificates] Successfully started [rke-bundle-cert] container on host [34.224.40.87]
FATA[0033] [etcd] Failed to bring up Etcd Plane: Failed to run certificate bundle compress, exit status is: 1

Which is same error on restore now.  Thoughts?

**Comment by galal-hussein** [comment]
@techcto I am investigating the issue, and will try to reproduce the issue.

**Comment by codereflection** [comment]
I was having the same exit status 3 and discovered that the path passed to etcdctl for the restore file is incorrect.  I suspected this might be the case because the container was failing with:
```
Error:  open \opt\rke\etcd-snapshots\upgrade.db: no such file or directory
```

The path is in the format 
```
snapshot restore \\opt\\rke\\etcd-snapshots\\upgrade.db
```

when I believe that it should be
```
snapshot restore /opt/rke/etcd-snapshots/upgrade.db
```

I tested by changing the path in a manually run container and the restore worked as expected.


Here's the command that I ran (copied from inspecting the failed container)

```
/ # /usr/local/bin/etcdctl --endpoints=[server-166:2379] \
>  --cacert /etc/kubernetes/ssl/kube-ca.pem --cert /etc/kubernetes/ssl/kube-etcd-server-166.pem \
>  --key /etc/kubernetes/ssl/kube-etcd-server-166-key.pem snapshot restore /opt/rke/etcd-snapshots/upgrade.db \
>  --data-dir=/opt/rke/etcd-snapshots-restore/ --name=etcd-server-166 \
>  --initial-cluster=etcd-server-166=https://server-166:2380,etcd-server-167=https://server-167:2380,etcd-server-168=https://server-168:2380 \
>  --initial-cluster-token=etcd-cluster-1 --initial-advertise-peer-urls=https://server-166:2380
2018-07-24 22:57:42.222083 I | pkg/netutil: resolving server-166:2380 to 10.44.107.43:2380
2018-07-24 22:57:42.222900 I | pkg/netutil: resolving server-166:2380 to 10.44.107.43:2380
2018-07-24 22:57:42.811312 I | mvcc: restore compact to 22424627
2018-07-24 22:57:42.829321 I | etcdserver/membership: added member 8addf67e7feb7324 [https://server-167:2380] to cluster fc1315e9d5ad5d0c
2018-07-24 22:57:42.829419 I | etcdserver/membership: added member ef2182c18b6f4e8e [https://server-168:2380] to cluster fc1315e9d5ad5d0c
2018-07-24 22:57:42.829488 I | etcdserver/membership: added member f5386993c7a2c881 [https://server-166:2380] to cluster fc1315e9d5ad5d0c
```

**Comment by codereflection** [comment]
I believe the issue is with the filepath.join operation here https://github.com/rancher/rke/blob/b71fd3ba355ba0cccc7bf466274e69f1797ea245/services/etcd.go#L269 where since the path is being created on a windows machine, the formatting is using UNC specification instead of something that the target linux environment is going to understand.

**Comment by techcto** [comment]
Hi all, not ignoring, been building a new cluster.  I hope to have a valid test today. I will share results shortly.

**Comment by techcto** [comment]
I think this issue is resolved, but I did stumble onto the next issue, which only happens after Restore on AWS Linux.  This has to do with 502 error after restore.  It seems AWS DNS gets corrupted.  I will find another ticket to start that conversation.

**Comment by neelshah1617** [comment]
I came across the issue with the hash not matching while restoring the etcd backups, as its not much of importance in my dev cluster, below command was able to restore it with endpoint health, status, and member list showing fine:
`ETCDCTL_API=3 etcdctl endpoint health --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key --cacert=/etc/kubernetes/pki/etcd/ca.crt 
127.0.0.1:2379 is healthy: successfully committed proposal: took = 2.067634ms`
