### ISSUE TITLE
Add IP address in Kubelet certificate

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rancher/rke#773]
**RKE version:**

0.1.8

**New feature**

Trying to use metrics-server with an RKE build Kubernetes cluster.

Using HTTPS port 10250 to collect metrics on Kubelet works fine only if i set "insecure=true" in metrics-server (by the way, no need to open read-only HTTP port 10255 as suggested in other issues, just use "--source=kubernetes.summary_api:?kubeletPort=10250&kubeletHttps=true&useServiceAccount=true")

The IP address of the node in missing in the certificate uses by Kubelet:

```
E0713 12:44:05.036725       1 summary.go:97] error while getting metrics summary from Kubelet kubernetes-ctrl-spr-1-1(192.168.2.247:10250): Get https://192.168.2.247:10250/stats/summary/: x509: cannot validate certificate for 192.168.2.247 because it doesn't contain any IP SANs
```

Can you add that IP address in the certificate?

**Comment by sebastien-prudhomme** [comment]
After investigating how RKE is using certificates for worker nodes, found some issues:
- All nodes use the same client certificate to allow Kubelet to reach the Kubernetes API server, which is not that good for security
- Kubelet uses a self-signed certificate for its HTTPS endpoint, instefad of using a certificated generated by the Kubernetes CA.

After reading "Kubernetes The Hard Way" by Kelsey Hightower:
- It confirms that having one certificate for Kubelet for each worker node is the best practice: https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-kubelet-client-certificates
- Using that certificate and the associated key for Kubelet HTTPS is also what is done (through Kubelet tlsCertFile and tlsPrivateKeyFile options): https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md#configure-the-kubelet

We can also notice that the certificate generated includes the IP address i'm looking for. For RKE, it should correspond to the node "address" and the node "internal_address" defined in the YAML cluster file.

**Comment by alena1108** [comment]
@sebastien-prudhomme a certificate per node request is being tracked in this issue: https://github.com/rancher/rke/issues/266

**Comment by superseb** [comment]
This is solved by using the configuration in https://github.com/rancher/rancher/issues/15793#issuecomment-602049405

Docs: https://rancher.com/docs/rke/latest/en/config-options/services/#kubelet
