### ISSUE TITLE
Update flannel to v0.10.0

### ISSUE THREAD

**Issue by superseb** [rancher/rke#791]
https://github.com/coreos/flannel/releases/tag/v0.10.0

**Comment by galal-hussein** [comment]
steps to validate:

- start cluster with rke v0.1.9
- check flannel image: `rancher/coreos-flannel:v0.9.1`
- run rke v0.1.10-rc4 on the same cluster

I can see the flannel image updated to `rancher/coreos-flannel:v0.10.0`, and the network is working fine
