### ISSUE TITLE
With Windows RKE, etcd-restore fails with: optrkeetcd-snapshotstestSnapshot: no such file or directory

### ISSUE THREAD

**Issue by aococ** [rancher/rke#812]
**RKE version:**
rke version v0.1.8

**Docker version: (`docker version`,`docker info` preferred)**
```
# docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**cluster.yml file:**
N/A

**Steps to Reproduce:**
1. Create a etcd snapshot using Windows version of RKE command: 
```etcd snapshot-save```
2. Use Windows version of RKE to restore etcd snapshot: 
```.\rke_windows-amd64.exe snapshot--restore --name <SOME_NAME> --config rancher-cluster.yml```

**Expected Results:**
Successful etcd restore  with ```INFO[0027] Finished restoring on all etcd hosts```

**Actual Results:**
1. RKE throwing error on etcd restore:

```time="2018-07-23T16:13:12+10:00" level=info msg="[etcd] Successfully started [etcd-restore] container on host [x.y.z.a]"
time="2018-07-23T16:13:12+10:00" level=fatal msg="[etcd] Failed to restore etcd snapshot: Failed to run etcd restore container, exit status is: 3"
```

2. Manually check the etcd-restore container log in x.y.z.a host shows:
```[ec2-user@ip-x-y-z-a ~]$ docker logs etcd-restore
Error:  open optrkeetcd-snapshotstestSnapshot: no such file or directory
```

note that the path etcd-restore is looking for snapshot is missing any slashes to separate paths.

Using Linux version of RKE with same snashot successfully restores the snapshot.

**Comment by codereflection** [comment]
I suspect this is the same issue that I commented on here: https://github.com/rancher/rke/issues/768#issuecomment-407579642 where an incorrect path format to the backup file is causing the problem.

**Comment by moelsayed** [comment]
Tested using v0.1.10-rc4, I was able to successfully restore an etcd snapshot:
![screenshot from 2018-09-19 21 10 52](https://user-images.githubusercontent.com/4588065/45775637-a9faed80-bc50-11e8-8396-74da3677f03e.png)
