### ISSUE TITLE
Add ability to recreate master components without any version changes using rke up

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rke#815]
**rke v0.1.8**
I've deleted `kube-dns` and  `kube-dns-autoscaler` deployments from my k8s cluster and wanted to recreate them again with `rke up` but `rke up` doesn't recreate them until I changed version of the mentioned images.

And maybe other deployments doesn't recreates too I don't tested

**Comment by harutyundermenjyan** [comment]
any update?

**Comment by harutyundermenjyan** [comment]
So I've tested it and can say that it doesn't recreates any of master related components if we delete it in existing cluster deployed with rke. No matter it will be deployment, ds, svc,ingress,configmap or any other type of kind....

**Comment by superseb** [comment]
@galal-hussein Any thoughts?

**Comment by jlamillan** [comment]
I submitted a PR that will fix this by _always_ running the add-on deployment jobs on every `up`. 

It's simplistic, but arguably not a bad way to go since there should be no harm in effectively re-running the (idempotent) `kubectl apply`.
