### ISSUE TITLE
[Question] KubeDNS on dedicated hosts

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rke#816]
**RKE version:** v0.1.8

Hi, Is there any way to define a nodeSelector just like ingress controller to KubeDNS? I want it to be installed on dedicated nodes.

**Comment by sebastien-prudhomme** [comment]
I think this should be done by the "dns provider" i propose in #722

**Comment by superseb** [comment]
This is added and will be in v0.2.0, it was fixed in https://github.com/rancher/rke/issues/1146
