### ISSUE TITLE
kube-apiserver failed to get /healthz with custom etcd cert

### ISSUE THREAD

**Issue by pdhung** [rancher/rke#824]
Deployment works fine without custom etcd cert, but got error with custom cert. However I cannot find the error in the logs as to why it cannot get healthz.

**RKE version:**
0.1.8, 0.1.9-rc4

**Docker version: (`docker version`,`docker info` preferred)**
17.03-2
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Centos 7

**cluster.yml file:**

k8s version: 1.11.1

etcd:
   extra_args:
      client-cert-auth: "true"
      trusted-ca-file: /etc/kubernetes/ssl-aap/ca-etcd.crt
      cert-file: /etc/kubernetes/ssl-aap/etcd-client.crt
      key-file: /etc/kubernetes/ssl-aap/etcd-client.key

kube-api:
  extra_args:
      etcd-cafile: /etc/kubernetes/ssl-aap/ca-etcd.crt
      etcd-certfile: /etc/kubernetes/ssl-aap/etcd-apiserver.crt
      etcd-keyfile: /etc/kubernetes/ssl-aap/etcd-apiserver.key

**Results:**
FATA[0148] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [10.145.237.49]: Get https://localhost:6443/healthz: EOF, log: I0730 17:43:58.308171       6 plugins.go:161] Loaded 3 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,ResourceQuota.

` curl -k https://localhost:6443/healthz
curl: (35) TCP connection reset by peer`

` netstat -tuplen: 
tcp6       0      0 :::6443                 :::*                    LISTEN      0          553372     41995/kube-apiserver`

[etcd.txt](https://github.com/rancher/rke/files/2242266/etcd.txt)
[apiserver.txt](https://github.com/rancher/rke/files/2242270/apiserver.txt)

**Comment by deniseschannon** [comment]
@pdhung With v0.2.0, we support custom certificates, please test it out and open a new issue if you are still having issue:

https://rancher.com/docs/rke/latest/en/installation/certs/
