### ISSUE TITLE
Can't pull from private registry

### ISSUE THREAD

**Issue by BorisDr** [rancher/rke#826]
**RKE version:**
rke version v0.1.8
**Docker version: (`docker version`,`docker info` preferred)**
deploy@rke:~$ docker info 
Containers: 54
 Running: 24
 Paused: 0
 Stopped: 30
Images: 16
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-7-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.71 GiB
Name: rke
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**cluster.yml file:**
nodes:
- address: *.*.*.*
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  - etcd
  hostname_override: rke
  user: deploy
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: false
    retention: ""
    creation: ""
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: rancher/coreos-etcd:v3.1.12
  alpine: rancher/rke-tools:v0.1.10
  nginx_proxy: rancher/rke-tools:v0.1.10
  cert_downloader: rancher/rke-tools:v0.1.10
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.10
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.8
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.8
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.8
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  kubernetes: rancher/hyperkube:v1.10.5-rancher1
  flannel: rancher/coreos-flannel:v0.9.1
  flannel_cni: rancher/coreos-flannel-cni:v0.2.0
  calico_node: rancher/calico-node:v3.1.1
  calico_cni: rancher/calico-cni:v3.1.1
  calico_controllers: ""
  calico_ctl: rancher/calico-ctl:v2.0.0
  canal_node: rancher/calico-node:v3.1.1
  canal_cni: rancher/calico-cni:v3.1.1
  canal_flannel: rancher/coreos-flannel:v0.9.1
  wave_node: weaveworks/weave-kube:2.1.2
  weave_cni: weaveworks/weave-npc:2.1.2
  pod_infra_container: rancher/pause-amd64:3.1
  ingress: rancher/nginx-ingress-controller:0.10.2-rancher3
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.4
ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
private_registries:
    - url: hub.*masked*.com
      user: admin
      password: *masked*
kubernetes_version: ""
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
**Steps to Reproduce:**
I am trying to deploy image from private registry but without any success. 

kubectl -n kube-system describe configmaps cluster-state 
private_registries:
    - url: hub.*masked*.com
      user: admin
      password: *masked*

Containers from cluster can connect to registry
**Results:**
kubectl describe pod jenkins:
Warning  Failed                 2m (x3 over 2m)  kubelet, rke       Failed to pull image "hub.*masked*.com/jenkins/jenkins:6": rpc error: code = Unknown desc = Error response from daemon: repository hub.*masked*.com/jenkins/jenkins not found: does not exist or no pull access
Warning  Failed                 2m (x3 over 2m)  kubelet, rke       Error: ErrImagePull
Normal   BackOff                1m (x6 over 2m)  kubelet, rke       Back-off pulling image "hub.*masked*.com/jenkins/jenkins:6"
Warning  Failed                 1m (x6 over 2m)  kubelet, rke       Error: ImagePullBackOff
Normal   Pulling                1m (x4 over 2m)  kubelet, rke       pulling image "hub.*masked*.com/jenkins/jenkins:6"

**Comment by BorisDr** [comment]
Addition. Just deployed fresh cluster to ubuntu 16.04 with the same config. Same result - "Failed to pull image"

**Comment by sebastien-prudhomme** [comment]
Is this working when you do a "docker pull hub.masked.com/jenkins/jenkins:6" on yours hosts?
Is this working on yours hosts?: ping -c 1 orion-pprd.agriculture hub.masked.com
Is this working on yours hosts?: docker exec kubelet ping -c 1 orion-pprd.agriculture hub.masked.com

**Comment by BorisDr** [comment]
All above is working

**Comment by zzxwill** [comment]
You need to add a private registry to the image name under `system_images`. For example:
```
system_images:
    etcd: hub.masked.com/rancher/coreos-etcd:v3.1.12
```
I also tried to use the private registry refer to the official [doc](https://rancher.com/docs/rke/v0.1.x/en/config-options/system-images/), but I found we have to add the registry as the prefix of the image.
