### ISSUE TITLE
Configure kubelet to use correct resolv.conf when systemd-resolved is detected

### ISSUE THREAD

**Issue by superseb** [rancher/rke#827]
When using nodes with `systemd-resolved` (can be configured on anything, but is default on Ubuntu 18.04), the `/etc/resolv.conf` is a symlink and the linked file contains a loopback address which cannot be reached as upstream for kube-dns which causes malfunctioning clusters.

We can detect the situation and if not configured differently by the user, we can make sure it is configured correctly.

See also: https://github.com/kubernetes/kubernetes/pull/64665/files

**Comment by moelsayed** [comment]
Tested using latest rke master. Using ubuntu 18.04 default systemd-resolved. DNS resolution in the cluster is working as expected.
