### ISSUE TITLE
Upgrade fails if it's done while adding a new node. 

### ISSUE THREAD

**Issue by moelsayed** [rancher/rke#828]
**RKE version:** 0.1.9-rc6

**Steps to Reproduce:**
- Create a cluster with rke 0.1.8
- Add a new node with all roles to cluster.yaml
- run rke up using version 0.1.9-rc6
**Results:**
```
DEBU[0037] [etcd] Container [etcd] is in a restarting loop [1.2.3.4] 
DEBU[0038] [etcd] Container [etcd] is already running on host [1.2.3.4] 
DEBU[0038] [etcd] Checking if container [etcd] is eligible for upgrade on host [1.2.3.4] 
FATA[0039] Failed to reconcile etcd plane: Error: No such image: rancher/coreos-etcd:v3.2.18 
```

**Comment by galal-hussein** [comment]
rke v0.1.8 --> master

I was able to test the following steps:

- Create a cluster with rke 0.1.8
- Add a new node with all roles to cluster.yaml
- run rke up using version master

rke up finished correctly and i was able to see the new nodes in `kubectl get nodes`
