### ISSUE TITLE
Handle Booleans within nginx ingress options

### ISSUE THREAD

**Issue by thejmazz** [rancher/rke#844]
This is probably an edge case and more related to the yaml parser.

**RKE version:**

**Docker version: (`docker version`,`docker info` preferred)**

17.06.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Ubuntu 16.04 4.4.0-130-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

OpenStack

**cluster.yml file:**

The relevant portion:

```yaml
ingress:
  provider: "nginx"
  options:
    use-proxy-protocol: "true"
  node_selector: {}
  extra_args: {}
```

**Steps to Reproduce:**

First deploy with `options: {}`. Then edit the options to add `use-proxy-protocol: "true"` and then `rke up`. Or just deploy with the proxy protocol options in the first place, but then you won't have an empty config map to manually fix.

**Results:**

RKE logs:

```
INFO[0017] [addons] Executing deploy job..
ERRO[0052] Failed to get job complete status: <nil>
WARN[0052] Failed to deploy addon execute job [rke-ingress-controller]: Failed to get job complete status: <nil>
```

Pod logs:

```
namespace "ingress-nginx" configured
configmap "tcp-services" unchanged
configmap "udp-services" unchanged
serviceaccount "nginx-ingress-serviceaccount" unchanged
clusterrole.rbac.authorization.k8s.io "nginx-ingress-clusterrole" configured
role.rbac.authorization.k8s.io "nginx-ingress-role" unchanged
rolebinding.rbac.authorization.k8s.io "nginx-ingress-role-nisa-binding" unchanged
clusterrolebinding.rbac.authorization.k8s.io "nginx-ingress-clusterrole-nisa-binding" configured
daemonset.extensions "nginx-ingress-controller" configured
deployment.extensions "default-http-backend" unchanged
service "default-http-backend" unchanged
Error from server: error when applying patch:
{"data":{"use-proxy-protocol":true},"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"use-proxy-protocol\":true},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"ingress-nginx\"},\"name\":\"nginx-configuration\",\"namespace\":\"ingress-nginx\"}}\n"}}}
to:
&{0xc420c2e900 0xc420c1ff10 ingress-nginx nginx-configuration /etc/config/rke-ingress-controller.yaml 0xc421958d28 25973 false}
for: "/etc/config/rke-ingress-controller.yaml": unrecognized type: string
```

How to fix? Manually edit the config map to have `use-proxy-protocol: "true"` as [here](https://github.com/kubernetes/kubernetes/issues/28321#issuecomment-322044505).

**Comment by willmao** [comment]
same issue

**Comment by gferreux** [comment]
Got the same issue with a nodeSelector

```
      nodeSelector: 
        node-role.kubernetes.io/ingress: true
```

**Comment by gferreux** [comment]
Got the same issue with:

```
ingress:
  provider: nginx
  options:
    use-proxy-protocol: "true"
```

Pod logs:
```
Error from server: error when applying patch:
...
for: "/etc/config/rke-ingress-controller.yaml": unrecognized type: string
```

It break the ingress setup on each deployment.

How to resolve this or disable ingress management ?

**Comment by Symbianx** [comment]
We have this problem as well in a cluster created by Rancher, our ingress deployment is not being upgraded when we upgrade the kubernetes version.

**Comment by ekristen** [comment]
This is a problem for me now too.

**Comment by billjh** [comment]
I have similar problem when adding config in ingress.options section, it failed to deploy

**Comment by Raboo** [comment]
```
ingress:
  provider: "nginx"
  options:
    use-proxy-protocol: true
```

Setting true without quotes work for me.
