### ISSUE TITLE
RKE Restore Kublet error cni config not found

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rke#849]
**RKE version:**
latest
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
container linux

Ran rke restore on new nodes then rke up and now the nodes are not ready. Kublet is saying 
```
W0808 17:33:54.935781    6088 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
E0808 17:33:54.936077    6088 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

It looks like the cni config is not being written. Since no pods are being scheduled the "rke-network-plugin" addon also never runs (which I think is supposed to write the config).

**Comment by galal-hussein** [comment]
@mitchellmaler can you post the output of the `rke up` command and the `kubectl get pods --all-namespaces`

**Comment by deniseschannon** [comment]
also, can you make sure to put what version as `latest` changes?
