### ISSUE TITLE
Doc says hostname_override may not be routable, but it must

### ISSUE THREAD

**Issue by miv** [rancher/rke#861]
**RKE version:** 
 v0.1.9

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare metal

**cluster.yml file:**

```
# new control plane
  - address: 245.221.11.178
    hostname_override: "kube_master_2"
    user: root
    role: [controlplane,etcd]
    ssh_key_path: ../rancher_ssh_key
```

**Steps to Reproduce:**

run rke with hostname_override set to arbitrary non routable name

**Results:**
rke can't connect to host using it's hostname_override as address:

```
INFO[0524] [worker] Successfully started Worker Plane..
INFO[0524] [sync] Syncing nodes Labels and Taints
FATA[0560] Failed to get kubernetes node [kube_master_2]:  "kube_master_2" not found
```

(also FATA instead of FATAL)

--

Documentation https://rancher.com/docs/rke/v0.1.x/en/config-options/nodes/#overriding-the-hostname says: `This hostname doesn’t need to be a routable address` but if it's not routable, rke doesn't work.

**Comment by deniseschannon** [comment]
@moelsayed can you confirm which is true and update the docs if the hosename_override needs to be a routable address?

**Comment by moelsayed** [comment]
@miv @deniseschannon We don't need a routable address for `hostname_override`. The name `kube_master_2` is an invalid [kubernetes resource name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names) and that's why it's breaking.

**Comment by moelsayed** [comment]
I created an issue to validate hostname_override https://github.com/rancher/rke/issues/862

**Comment by deniseschannon** [comment]
@moelsayed can up date the docs with this infomation and then we can close this issue

**Comment by miv** [comment]
@moelsayed Got it. Thank you. Can we add hostname_override to old/existing nodes, will this break anything?

**Comment by moelsayed** [comment]
@miv rke will not complain. But kubernetes will not handle it well. You will be basically removing a node and adding a new one, since the name the node uses to register will change. If you do this, you will have old nodes in `NotReady` state. And you will need to remove them manually using `kubectl delete node`. I wouldn't recommend this.

**Comment by deniseschannon** [comment]
The information about needing it to be a kubernetes resource name is now updated in the docs.

**Comment by insekticid** [comment]
renamed node with this result

![image](https://user-images.githubusercontent.com/177340/44788319-04e17d80-ab9a-11e8-91cd-1f36eab6b54b.png)

**Comment by moelsayed** [comment]
@insekticid Please open a new issue on rancher/rancher and include the logs for the kubelet container on that node.

**Comment by insekticid** [comment]
@moelsayed solved with your solution  `kubectl delete node` so I am ok :)
