### ISSUE TITLE
Ability to Set Flannel Network Provider Back End

### ISSUE THREAD

**Issue by Oats87** [rancher/rke#864]
When using a network provider like Canal or Flannel, it can be desirable to configure the backend of Flannel. Currently we only support setting the backend to VXLAN: https://github.com/rancher/rke/blob/master/templates/flannel.go#L78

It would be desirable to be able to configure the backend of flannel to allow the use of the other backend services like aws-vpc, ipsec, etc.

**Comment by rafal-prasal** [comment]
https://github.com/rancher/rke/pull/1142
