### ISSUE TITLE
CoreDNS not supported by RKE CLI 

### ISSUE THREAD

**Issue by thearifismail** [rancher/rke#874]
**RKE version:**
v0.1.9
**Docker version: (`docker version`,`docker info` preferred)**
[abc@xxxx ~]$ docker info
Containers: 23
 Running: 9
 Paused: 0
 Stopped: 14
Images: 9
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.9.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.701GiB
Name: am-k8s-1.cisco.com
ID: 3J6M:GKS6:7PZO:YYLZ:W5P7:E74T:6ZDI:OOME:CRLJ:LJJX:LPET:KOVS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**
\# If you intened to deploy Kubernetes in an air-gapped environment,
\# please consult the documentation on how to configure custom RKE images.
nodes:
- address: \<fully qualified host name\>
  port: "22"
  internal_address: ""
  role:
  - controlplane
  hostname_override: ""
  user: centos
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ""
  labels: {}
- address: \<fully qualified host name\>
  port: "22"
  internal_address: ""
  role:
  - etcd
  hostname_override: ""
  user: centos
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ""
  labels: {}
- address: \<fully qualified host name\>
  port: "22"
  internal_address: ""
  role:
  - worker
  hostname_override: ""
  user: centos
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ""
  labels: {}
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: false
    retention: ""
    creation: ""
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: <CLUSTER_DOMAIN>
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: weave
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: gcr.io/google-containers/etcd:3.2.18
  kubernetes: gcr.io/google-containers/hyperkube-amd64:v1.11.1
  alpine: rancher/rke-tools:v0.1.13
  nginx_proxy: rancher/rke-tools:v0.1.13
  cert_downloader: rancher/rke-tools:v0.1.13
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.13
  core_dns: gcr.io/google-containers/coredns:1.1.3
  weave_node: weaveworks/weave-kube:2.4.0
  weave_cni: weaveworks/weave-npc:2.4.0
  pod_infra_container: gcr.io/google_containers/pause-amd64:3.1
  ingress: rancher/nginx-ingress-controller:0.16.2-rancher3
  ingress_backend: k8s.gcr.io/defaultbackend:1.4
  metrics_server: gcr.io/google_containers/metrics-server-amd64:v0.2.1  
ssh_key_path: ~/.ssh/my_ssh_key.pem
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
cluster_name: "k8s-cluster-v1.11.1"
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""

**Steps to Reproduce:**
Deploy a Kubernetes cluster with controlplane, etcd, and worker on separate VMs.
use `"rke up --ignore-docker-version --config <my_config_file.yml>`

A kubernetes cluster is created but the CoreDNS is completely ignored and kube-dns is used instead.

**Results:**
Here is the output of "docker -v", "docker images" and "docker ps".  For privacy, the username and host info has been masqueraded.

\==========================
ControlPlan
\----------------------------------------------
[abcd@k8s-vm-1 ~]$ docker -v
Docker version 18.06.0-ce, build 0ffa825
[abcd@k8s-vm-1 ~]$
[abcd@k8s-vm-1 ~]$
[abcd@k8s-vm-1 ~]$
[abcd@k8s-vm-1 ~]$ docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
rancher/rke-tools                          v0.1.13             4618aefd9891        2 weeks ago         125MB
weaveworks/weave-npc                       2.4.0               647ad6d59818        4 weeks ago         49.1MB
gcr.io/google-containers/hyperkube-amd64   v1.11.1             9df9e248fcaf        5 weeks ago         626MB
gcr.io/google_containers/pause-amd64       3.1                 da86e6ba6ca1        8 months ago        742kB
weaveworks/weave-kube                      2.1.2               3890acde01c9        8 months ago        92.6MB
[abcd@k8s-vm-1 ~]$
[abcd@k8s-vm-1 ~]$
[abcd@k8s-vm-1 ~]$
[abcd@k8s-vm-1 ~]$ docker ps
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS               NAMES
06ad24655dbb        4618aefd9891                                       "/opt/rke-tools/weav…"   7 minutes ago       Up 7 minutes                            k8s_weave-loopback_weave-net-9ghvh_kube-system_995c45a8-a64e-11e8-840d-fa163e3037ff_0
3e3e4574a903        weaveworks/weave-npc                               "/usr/bin/weave-npc"     7 minutes ago       Up 7 minutes                            k8s_weave-npc_weave-net-9ghvh_kube-system_995c45a8-a64e-11e8-840d-fa163e3037ff_0
1565e7f8f81e        weaveworks/weave-kube                              "/home/weave/launch.…"   7 minutes ago       Up 7 minutes                            k8s_weave_weave-net-9ghvh_kube-system_995c45a8-a64e-11e8-840d-fa163e3037ff_0
2d6d8a8b292d        gcr.io/google_containers/pause-amd64:3.1           "/pause"                 7 minutes ago       Up 7 minutes                            k8s_POD_weave-net-9ghvh_kube-system_995c45a8-a64e-11e8-840d-fa163e3037ff_0
b5844323c782        gcr.io/google-containers/hyperkube-amd64:v1.11.1   "/opt/rke-tools/entr…"   7 minutes ago       Up 7 minutes                            kube-proxy
f061755e70b3        gcr.io/google-containers/hyperkube-amd64:v1.11.1   "/opt/rke-tools/entr…"   7 minutes ago       Up 7 minutes                            kubelet
a03259f6986d        gcr.io/google-containers/hyperkube-amd64:v1.11.1   "/opt/rke-tools/entr…"   7 minutes ago       Up 7 minutes                            kube-scheduler
b7a2db787d94        gcr.io/google-containers/hyperkube-amd64:v1.11.1   "/opt/rke-tools/entr…"   7 minutes ago       Up 7 minutes                            kube-controller-manager
fbe9a5b0b8c3        gcr.io/google-containers/hyperkube-amd64:v1.11.1   "/opt/rke-tools/entr…"   7 minutes ago       Up 7 minutes                            kube-apiserver
[abcd@k8s-vm-1 ~]$

\==========================
etcd
\----------------------------------------------
[abcd@k8s-vm-2 ~]$ docker -v
Docker version 18.06.0-ce, build 0ffa825
[abcd@k8s-vm-2 ~]$
[abcd@k8s-vm-2 ~]$
[abcd@k8s-vm-2 ~]$
[abcd@k8s-vm-2 ~]$ docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
rancher/rke-tools                          v0.1.13             4618aefd9891        2 weeks ago         125MB
weaveworks/weave-npc                       2.4.0               647ad6d59818        4 weeks ago         49.1MB
gcr.io/google-containers/hyperkube-amd64   v1.11.1             9df9e248fcaf        5 weeks ago         626MB
gcr.io/google-containers/etcd              3.2.18              b8df3b177be2        4 months ago        219MB
gcr.io/google_containers/pause-amd64       3.1                 da86e6ba6ca1        8 months ago        742kB
weaveworks/weave-kube                      2.1.2               3890acde01c9        8 months ago        92.6MB
[abcd@k8s-vm-2 ~]$
[abcd@k8s-vm-2 ~]$
[abcd@k8s-vm-2 ~]$
[abcd@k8s-vm-2 ~]$ docker ps
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS               NAMES
5e4680714bcf        4618aefd9891                                       "/opt/rke-tools/weav…"   9 minutes ago       Up 9 minutes                            k8s_weave-loopback_weave-net-gmhrz_kube-system_995d172b-a64e-11e8-840d-fa163e3037ff_0
2aefd10687b6        weaveworks/weave-npc                               "/usr/bin/weave-npc"     9 minutes ago       Up 9 minutes                            k8s_weave-npc_weave-net-gmhrz_kube-system_995d172b-a64e-11e8-840d-fa163e3037ff_0
e6e174b58e52        weaveworks/weave-kube                              "/home/weave/launch.…"   9 minutes ago       Up 9 minutes                            k8s_weave_weave-net-gmhrz_kube-system_995d172b-a64e-11e8-840d-fa163e3037ff_0
18b13861d6ea        gcr.io/google_containers/pause-amd64:3.1           "/pause"                 9 minutes ago       Up 9 minutes                            k8s_POD_weave-net-gmhrz_kube-system_995d172b-a64e-11e8-840d-fa163e3037ff_0
f49ec76e3cc7        gcr.io/google-containers/hyperkube-amd64:v1.11.1   "/opt/rke-tools/entr…"   9 minutes ago       Up 9 minutes                            kube-proxy
8918bb6e3472        gcr.io/google-containers/hyperkube-amd64:v1.11.1   "/opt/rke-tools/entr…"   9 minutes ago       Up 9 minutes                            kubelet
b0a2b73906b9        rancher/rke-tools:v0.1.13                          "nginx-proxy CP_HOST…"   9 minutes ago       Up 9 minutes                            nginx-proxy
9079a8103a69        gcr.io/google-containers/etcd:3.2.18               "/usr/local/bin/etcd…"   9 minutes ago       Up 9 minutes                            etcd
[abcd@k8s-vm-2 ~]$
[abcd@k8s-vm-2 ~]$
[abcd@k8s-vm-2 ~]$

\==========================
worker
\----------------------------------------------
[abcd@k8s-vm-3 ~]$ docker -v
Docker version 18.06.0-ce, build 0ffa825
[abcd@k8s-vm-3 ~]$
[abcd@k8s-vm-3 ~]$
[abcd@k8s-vm-3 ~]$
[abcd@k8s-vm-3 ~]$ docker images
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
rancher/rke-tools                               v0.1.13             4618aefd9891        2 weeks ago         125MB
weaveworks/weave-npc                            2.4.0               647ad6d59818        4 weeks ago         49.1MB
gcr.io/google-containers/hyperkube-amd64        v1.11.1             9df9e248fcaf        5 weeks ago         626MB
rancher/k8s-dns-dnsmasq-nanny-amd64             1.14.10             6816817d9dce        4 months ago        40.4MB
rancher/k8s-dns-kube-dns-amd64                  1.14.10             55ffe31ac578        4 months ago        49.5MB
rancher/k8s-dns-sidecar-amd64                   1.14.10             8a7739f672b4        4 months ago        41.6MB
gcr.io/google_containers/pause-amd64            3.1                 da86e6ba6ca1        8 months ago        742kB
gcr.io/google_containers/metrics-server-amd64   v0.2.1              9801395070f3        8 months ago        42.5MB
weaveworks/weave-kube                           2.1.2               3890acde01c9        8 months ago        92.6MB
k8s.gcr.io/defaultbackend                       1.4                 846921f0fe0e        10 months ago       4.84MB
rancher/cluster-proportional-autoscaler-amd64   1.0.0               e183460c484d        21 months ago       48.2MB
[abcd@k8s-vm-3 ~]$
[abcd@k8s-vm-3 ~]$
[abcd@k8s-vm-3 ~]$
[abcd@k8s-vm-3 ~]$ docker ps
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS               NAMES
87502db05902        rancher/k8s-dns-sidecar-amd64                      "/sidecar --v=2 --lo…"   10 minutes ago      Up 10 minutes                           k8s_sidecar_kube-dns-66d6589947-29776_kube-system_9bdc44b9-a64e-11e8-840d-fa163e3037ff_0
ef493da90080        k8s.gcr.io/defaultbackend                          "/server"                10 minutes ago      Up 10 minutes                           k8s_default-http-backend_default-http-backend-5b8b67fd74-dnvhp_ingress-nginx_a1c7d827-a64e-11e8-840d-fa163e3037ff_0
a9722af5a3e6        rancher/k8s-dns-dnsmasq-nanny-amd64                "/dnsmasq-nanny -v=2…"   10 minutes ago      Up 10 minutes                           k8s_dnsmasq_kube-dns-66d6589947-29776_kube-system_9bdc44b9-a64e-11e8-840d-fa163e3037ff_0
8a8af603acd8        gcr.io/google_containers/metrics-server-amd64      "/metrics-server --s…"   10 minutes ago      Up 10 minutes                           k8s_metrics-server_metrics-server-6f5c958f9-db4q5_kube-system_9f59f705-a64e-11e8-840d-fa163e3037ff_0
e0d1d300edb9        gcr.io/google_containers/pause-amd64:3.1           "/pause"                 10 minutes ago      Up 10 minutes                           k8s_POD_default-http-backend-5b8b67fd74-dnvhp_ingress-nginx_a1c7d827-a64e-11e8-840d-fa163e3037ff_0
8332a03db0e2        gcr.io/google_containers/pause-amd64:3.1           "/pause"                 10 minutes ago      Up 10 minutes                           k8s_POD_nginx-ingress-controller-7gw5l_ingress-nginx_a1c75fd5-a64e-11e8-840d-fa163e3037ff_0
f827aa247e41        rancher/k8s-dns-kube-dns-amd64                     "/kube-dns --domain=…"   10 minutes ago      Up 10 minutes                           k8s_kubedns_kube-dns-66d6589947-29776_kube-system_9bdc44b9-a64e-11e8-840d-fa163e3037ff_0
75b92edee383        gcr.io/google_containers/pause-amd64:3.1           "/pause"                 10 minutes ago      Up 10 minutes                           k8s_POD_metrics-server-6f5c958f9-db4q5_kube-system_9f59f705-a64e-11e8-840d-fa163e3037ff_0
81635759205b        rancher/cluster-proportional-autoscaler-amd64      "/cluster-proportion…"   10 minutes ago      Up 10 minutes                           k8s_autoscaler_kube-dns-autoscaler-5db9bbb766-9q6pz_kube-system_9c6d0d7d-a64e-11e8-840d-fa163e3037ff_0
3903d32b2f9b        gcr.io/google_containers/pause-amd64:3.1           "/pause"                 10 minutes ago      Up 10 minutes                           k8s_POD_kube-dns-66d6589947-29776_kube-system_9bdc44b9-a64e-11e8-840d-fa163e3037ff_1
519ee645f143        gcr.io/google_containers/pause-amd64:3.1           "/pause"                 10 minutes ago      Up 10 minutes                           k8s_POD_kube-dns-autoscaler-5db9bbb766-9q6pz_kube-system_9c6d0d7d-a64e-11e8-840d-fa163e3037ff_1
26b517a93661        4618aefd9891                                       "/opt/rke-tools/weav…"   10 minutes ago      Up 10 minutes                           k8s_weave-loopback_weave-net-d6mpp_kube-system_995cfa14-a64e-11e8-840d-fa163e3037ff_0
29a0717eaffd        weaveworks/weave-npc                               "/usr/bin/weave-npc"     10 minutes ago      Up 10 minutes                           k8s_weave-npc_weave-net-d6mpp_kube-system_995cfa14-a64e-11e8-840d-fa163e3037ff_0
4ade425483bf        weaveworks/weave-kube                              "/home/weave/launch.…"   10 minutes ago      Up 10 minutes                           k8s_weave_weave-net-d6mpp_kube-system_995cfa14-a64e-11e8-840d-fa163e3037ff_0
ef44291dfcd5        gcr.io/google_containers/pause-amd64:3.1           "/pause"                 10 minutes ago      Up 10 minutes                           k8s_POD_weave-net-d6mpp_kube-system_995cfa14-a64e-11e8-840d-fa163e3037ff_0
609006c07f99        gcr.io/google-containers/hyperkube-amd64:v1.11.1   "/opt/rke-tools/entr…"   10 minutes ago      Up 10 minutes                           kube-proxy
94f27bc041bf        gcr.io/google-containers/hyperkube-amd64:v1.11.1   "/opt/rke-tools/entr…"   10 minutes ago      Up 10 minutes                           kubelet
b0173dae263b        rancher/rke-tools:v0.1.13                          "nginx-proxy CP_HOST…"   10 minutes ago      Up 10 minutes                           nginx-proxy
[abcd@k8s-vm-3 ~]$

**Comment by superseb** [comment]
CoreDNS is not supported yet, see https://github.com/rancher/rke/issues/722
