### ISSUE TITLE
Deploy rancher UI ok rke

### ISSUE THREAD

**Issue by mlkmhd** [rancher/rke#885]
Hi,
I have a question maybe seems silly
How can I deploy rancher UI on rke?
I installed rke on 3 node and then I installed kuberenetes dashboard on it. But kuberenetes dashboard is so hard to work with it and rancher UI is so easy. Is it possible to have rancher UI on rke?

Thanks

**Comment by superseb** [comment]
The HA install docs from Rancher show how to install Rancher as an addon to running RKE. (https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/)

RKE is made for building k8s clusters, Rancher is made to manage them. The Rancher UI displays the API information from Rancher, so cannot be installed standalone a la Kubernetes dashboard project.
