### ISSUE TITLE
[Question] How to add/delete nodes in concurrent situation

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rke#892]
Hi, 

RKE relies on a config file to manage the whole cluster, if we build an API on top of rke, looks like we have the only way to maintain the config file, if there're a large number concurrent requests to add/delete nodes, how can we handle this scenario?

**Comment by leopay** [comment]
@hiscal2015  we have the same problem. It seems RKE is only designed for a command tool?

**Comment by alena1108** [comment]
@hiscal2015 @leopay standalone RKE is only designed for a command line tool, so handling concurrent nodes provisioning is not in its scope. You'd have to build something on top to integrate with it, like we do in `rancher/rancher`. So Rancher uses rke to provision the cluster, and it can handle simultaneous nodes provisioning as well.

**Comment by deniseschannon** [comment]
@hiscal2015 @leopay let me know if you still have any more questions.
