### ISSUE TITLE
Need a yaml snippet showing how to add taint to a node in config yaml for RKE CLI

### ISSUE THREAD

**Issue by thearifismail** [rancher/rke#907]
rke cli version: 0.1.19
Docker version 18.06.0-ce
Centos Linux 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 

**cluster.yml snippet**
nodes:
- address: x.x.x.68
  port: "22"
  internal_address: ""
  role:
  - worker
     hostname_override: ""
      user: charliebrown 
      docker_socket: /var/run/docker.sock
      ssh_key: ""
      ssh_key_path: ""
      labels: {}
...
...
...
system_images:
  etcd: rancher/coreos-etcd:v3.2.18
  alpine: rancher/rke-tools:v0.1.13
  nginx_proxy: rancher/rke-tools:v0.1.13
  cert_downloader: rancher/rke-tools:v0.1.13
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.13
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.10
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.10
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.10
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  kubernetes: rancher/hyperkube:v1.11.1-rancher1
  wave_node: weaveworks/weave-kube:2.4.0
  weave_cni: weaveworks/weave-npc:2.4.0
  pod_infra_container: rancher/pause-amd64:3.1
  metrics_server: rancher/metrics-server-amd64:v0.2.1

**Steps to Reproduce:**
If I have the ability to set taints on nodes in a config yaml, which contains addons also, the with one "rke up..." run I get the whole thing set.  Without it, I will have to execute three steps:
1. deploy k8s cluster using "rke up --config ...:
2. kubectl taint...
3. kubectl apply -f <addon.yaml>

**Results:**
GOAL: with one "rke up ..." command, deploy cluster, set taint, and deploy addons like ambassador and weave-scope

**Comment by thearifismail** [comment]
For new users, it will be very helpful to have a working yaml to deploy a pod with tolerations and matching taints.

**Comment by mickael-alibert** [comment]
Hello, is there any update on this request as I found myself encountering the same issue when trying to apply taints ?

**Comment by thearifismail** [comment]
I don't know if taints support has been added to RKE CLI or not.  I solved the problem by creating a taints file and then adding it to addons in my cluster config file which was used by "rke up...".  Though adding taints is a fairly simple one-line command, I created it to for automation.  Here is the sample.
---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Node
    metadata:
      annotations:
        rke.cattle.io/external-ip: <ip of 1st worker>
        rke.cattle.io/internal-ip: <ip of 1st worker>
      name: <1st worker hostname>
    spec:
      taints:
      - effect: NoSchedule
        key: mykey
        value: somevalue
    status:
      addresses:
      - address: <ip of 1st worker>
        type: InternalIP
      - address: <1st worker hostname>
        type: Hostname
  - apiVersion: v1
    kind: Node
    metadata:
      annotations:
        rke.cattle.io/external-ip: <ip of 2nd worker>
        rke.cattle.io/internal-ip: <ip of 2nd worker>
      name: <2nd worker hostname>
    spec:
      taints:
      - effect: NoSchedule
        key: mykey
        value: somevalue
    status:
      addresses:
      - address: <ip of 2nd worker>
        type: InternalIP
      - address: <2nd worker hostname>
        type: Hostname
---------- end of taints.yml ---------------

This is what I in cluster-config.yml
addons: ""
addons_include:
- ./parent-dir-path/taints.yaml

Hope this helps and good luck

**Comment by deniseschannon** [comment]
Duplicate: https://github.com/rancher/rke/issues/157
