### ISSUE TITLE
Move to publishing archives in release

### ISSUE THREAD

**Issue by superseb** [rancher/rke#911]
* Makes it possible to have archives with $arch names, and just `rke` as binary name in each of them
* Saves data to transfer (~8MB vs ~30MB)

**Comment by cjellick** [comment]
@galal-hussein to validate, right?

**Comment by galal-hussein** [comment]
Verified with `v0.2.0-rc7` tag, rke binary was not released as expected.

**Comment by superseb** [comment]
The goal is to have archives with the binaries, to be the same as how the CLI is released

**Comment by cjellick** [comment]
drone isnt doing what we want, need to move out of the release

**Comment by deniseschannon** [comment]
I believe this specific request is asking that we make specific versioned RKE CLI releases like we do in rancher CLI, where the artifacts are tagged with `-version`

Example: https://github.com/rancher/cli/releases/tag/v2.2.0
