### ISSUE TITLE
I have little confusion about the terminology in Kubernetes cluster set up by rke.

### ISSUE THREAD

**Issue by qasim9641** [rancher/rke#920]
**RKE version: v0.1.9

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file:**

**Steps to Reproduce:**
In kubernetes we use the term master node and worker node. When we set up the cluster through rke we deploy etcd, contoller and worker component on different node.My question is that which component of rke is the equivalent of Kubernetes master node (etcd or controller)

**Results:**

**Comment by superseb** [comment]
The roles are explained here: https://rancher.com/docs/rke/v0.1.x/en/config-options/nodes/#kubernetes-roles

If you want all the master components on a node, you need to apply etcd and controlplane to the node. 
You can read here https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/ why it's a good idea to separate etcd from the rest of the cluster components.
