### ISSUE TITLE
respect kubernetes_version

### ISSUE THREAD

**Issue by travisghansen** [rancher/rke#921]
Per the documentation:
> If a version is defined in kubernetes_version and is not found in this list, the default is used.

This could be pretty detrimental in a production environment where later versions of `rke` do not support the `kubernetes_version` originally installed.  I'm thinking of general maintenance where assets (`cluster.yml`) are maybe stored in git and subsequent maintainers download a newer `rke` binary and run `rke up`.

Alternatively, allow an `rke_version` to be defined in `cluster.yml` and disallow execution unless it's the proper binary version.  Something to lock things down and prevent un-intended upgrades.

Thanks!

**Comment by alena1108** [comment]
Can be tested in `v0.2.0-rc4` rke

**Comment by travisghansen** [comment]
@alena1108 what should I be testing?  What's the new/expected behavior?

**Comment by alena1108** [comment]
@travisghansen The details of expected behavior can be found https://github.com/rancher/rke/pull/1086. Also usually our QA team validates all the issues marked as `to-test`, including the ones filed by the community.

**Comment by soumyalj** [comment]
Tested with rke version v0.2.0-rc5.
Kubernetes version specified in cluster.yml is honored if its supported. 
If an unsupported K8s version is used, an error message will be displayed as below:
```
$$./rke_darwin-amd64 up --config cluster.yml 
WARN[0000] This is not an officially supported version (v0.2.0-rc5) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest 
INFO[0000] Initiating Kubernetes cluster                
FATA[0000] v1.10.3-rancher1-1 is an unsupported Kubernetes version - see 'rke config --system-images --all' for versions supported with this release 
```
Note:
If a K8s cluster exists with an older unsupported version ex:v1.10.3-rancher1-1 and the version is not specified in the cluster.yml, an `rke up --config cluster.yml` will upgrade the existing version as expected.
