### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by johnsockwell** [rancher/rke#929]
###**RKE version:** 1.9

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 Kubernetes:
  Version:          v1.10.3
  StackAPI:         Unknown

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
OSX Mojave, 18.0.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Docker for Mac

I'm looking for instructions to build RKE for OSX on my local machine. Is this possible? I would like to build a Homebrew formula so users can use the package manager to install the application.
#580

**Comment by maxkorp** [comment]
`./scripts/build` In the root of the repo should be sufficient. I don't know that a build is necessary though for homebrew.

**Comment by HighwayofLife** [comment]
Correct. Homebrew uses pre-built packages. You don't need a build script/
steps.

**Comment by johnsockwell** [comment]
I've issued a [Pull Request](url
https://github.com/Homebrew/homebrew-cask/pull/52864) for the Homebrew team.

Once it's merged, you will be able to install RKE using `brew cask install rancher-kubernetes-engine`

**Comment by johnsockwell** [comment]
> I've issued a [Pull Request](https://github.com/Homebrew/homebrew-cask/pull/52864) for the Homebrew team.
> 
> Once it's merged, you will be able to install RKE using `brew cask install rancher-kubernetes-engine`

Homebrew requests a formula that builds from source, not using the provided binary. I'm pretty close to having this working but I could use a little help.

I'm compiling with the following command  `go build -ldflags -w -X main.VERSION=0.1.9 -o /usr/local/Cellar/rke/0.1.9/bin/rke github.com/rancher/rke/`

When I run `rke --version` I get `rke version 0.1.9`
When I run `rke version` I get... 
```
WARN[0000] This is not an officially supported version (0.1.9) of RKE. Please download the latest official release at https://github.com/rancher/rke/releases/latest 
FATA[0000] Failed to create Kubernetes Client: stat ./kube_config_cluster.yml: no such file or directory
```
This appears to be related to #749 but I'm unclear on how to address with a locally built version. @superseb Can you give em a little advice?

**Comment by vincent99** [comment]
Aren't you just missing the `v`?

**Comment by HighwayofLife** [comment]
Why would this be a cask?

**Comment by johnsockwell** [comment]
> Why would this be a cask?

I thought it would be easier to use the precompiled binaries. [Casks are used to install binaries](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#we-dont-like-binary-formulae), apps, fonts, basically anything that isn't compiled locally.

In the end though, the Homebrew team requested this be a formula compiled from source rather than a precompiled binary. [Related Pull Request](https://github.com/Homebrew/homebrew-cask/pull/52864#issuecomment-427196310)

I've an [open pull request for a rke formula.](https://github.com/Homebrew/homebrew-core/pull/32723)
