### ISSUE TITLE
RKE upgrade: lot of "Can't remove Docker container"

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rancher/rke#941]
**RKE version:**

0.1.10 (upgrading from 0.1.9)

Lot of the same problem when launching "rke up":

```
Failed to bring up ****: Can't remove Docker container [old-***] for host [***]: Error response from daemon: Unable to remove filesystem for ***: remove /var/lib/docker/containers/***/shm: device or resource busy
```

Seems that RKE doesn't wait for the stop of the old container, because when i relaunch "rke up", the problem with the old container just gone...but appears for another one container.

**Comment by hadifarnoud** [comment]
I have the same issue. how did you resolve it?

**Comment by sebastien-prudhomme** [comment]
Don't remember...
