### ISSUE TITLE
VMware  hardware version 13 cloud provider problems

### ISSUE THREAD

**Issue by cbarensfeld** [rancher/rke#950]
Problem: 
When deploying clusters via Rancher UI on VMware 6.5, the hardware version is set to version 13 regardless of cluster or datacenter defaults. This results in a mismatch of /sys/class/dmi/id/product_uuid and /sys/class/dmi/id/product_serial on the VM, which causes the VMware storageclass to fail with the error "Unable to find VM by UUID. VM UUID." 

Solution:
The solution is to set the VMs to hardware version 11 in the .vmx file and re-registering the VM. 

It would be nice if we could specify the hardware version during the deployment, otherwise this step needs to be taken for every VM in the cluster.

**Comment by superseb** [comment]
Seems to be an issue with the UUID in older k8s versions, what cluster version are you using?

ref https://github.com/kubernetes/kubernetes/issues/58927

**Comment by vincent99** [comment]
Also there's nothing in the figure-machine code explicitly specifying a version..

**Comment by cbarensfeld** [comment]
Thanks for your quick response. 
v1.11.3-rancher1-1
VMware Version 6.5.0.20000 Build 8667236

**Comment by cbarensfeld** [comment]
I tried fixing it on an existing cluster and it did not work. I think the cloud provider must be set during initial deployment and not after. I will test this and get back to you.

**Comment by cbarensfeld** [comment]
Ok, so it will work on vmware hardware v13, but it has to be set before the nodes are created. I ended up deleting each node and letting it reprovision. Everything is working now.

**Comment by alena1108** [comment]
@cbarensfeld closing the issue for now. If it happens again, please file it for github.com/rancher/rancher as rke only carries k8s provisioning code. Integration with docker-machine is done in rancher repo only
