### ISSUE TITLE
Potential performance bottleneck when syncing node labels and taints on large environments

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#957]
**RKE version:**
0.1.10
**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.1
```
$ uname -r
4.13.0-21-generic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**cluster.yml file:**
Available upon request
**Steps to Reproduce:**
- run rke up on a large environment (700+ nodes)
**Results:**
The step `Syncing nodes Labels and Taints` takes over 15 minutes and appears to be applying labels serially (one node at a time). Ran the command `kubectl get nodes | grep worker | wc -l` several times and saw the number of `worker` labels being applied was increasing gradually.

From the logs:
```
time="2018-10-15T02:52:47Z" level=info msg="[sync] Syncing nodes Labels and Taints"
time="2018-10-15T03:11:37Z" level=info msg="[sync] Successfully synced nodes Labels and Taints"
```

As a performance improvement, consider labeling nodes in parallel.

**Comment by dnoland1** [comment]
Retested on cluster with the fix:
```
time="2018-10-23T03:50:27Z" level=info msg="[sync] Syncing nodes Labels and Taints"
time="2018-10-23T03:56:45Z" level=info msg="[sync] Successfully synced nodes Labels and Taints"
```
Took 6 minutes, 18 seconds.

**Comment by hdnebat** [comment]
i'm getting FATA[0111] "<IP>" [ not found] right after sync] Syncing nodes Labels and Taints
any idea why?
