### ISSUE TITLE
Potential performance bottleneck starting/removing cluster-state-deployer on large environments

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#958]
**RKE version:**
0.1.10
**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.1
$ uname -r
4.13.0-21-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**cluster.yml file:**
Available upon request
**Steps to Reproduce:**
Run `rke up` on 700+ node environment.
**Results:**
In the logs, see this repeated for each host:
```
time="2018-10-14T08:02:04Z" level=info msg="[state] Successfully started [cluster-state-deployer] container on host [10.x.y.z]"
time="2018-10-14T08:02:04Z" level=info msg="[remove/cluster-state-deployer] Successfully removed container on host [10.x.y.z]"
```
Appears to run this on one host at a time. This took about 17 minutes for a 786 node environment.

As a performance improvement, perhaps this step could be run in parallel for each nodes.

**Comment by sangeethah** [comment]
Moving this issue to backlog for testing RKE on 1000 node clusters.
