### ISSUE TITLE
Unsupported Docker version found [18.06.1-ce], but in docker.go mentioned this version is supported.

### ISSUE THREAD

**Issue by kitepad** [rancher/rke#959]
**RKE version:**
0.1.10
**Docker version: (`docker version`,`docker info` preferred)**
18.06.1-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
virtualbox
**cluster.yml file:**
N/A
**Steps to Reproduce:**

**Results:**

**Comment by kitepad** [comment]
Same problem in rke 0.1.11.  Why?

**Comment by superseb** [comment]
It's only supported for K8s 1.12, which is currently experimental: https://github.com/rancher/rke/blob/master/docker/docker.go#L41
