### ISSUE TITLE
Support for choosing a k8s version

### ISSUE THREAD

**Issue by superseb** [rancher/rke#96]
With 1.9 around the corner, we should implement support for choosing which k8s versions will be setup.

**Comment by galal-hussein** [comment]
@superseb the user can use kubernetes 1.9 when it comes out, it just a matter of changing the image for the services

**Comment by superseb** [comment]
I was thinking more in terms of supported Docker versions, etcd versions based on the choice of k8s version.

**Comment by randrewedwards** [comment]
Can you not specify the k8s version in your cluster.yaml file? (Looking at docker version numbers)

**Comment by galal-hussein** [comment]
feature added and verified in https://github.com/rancher/rke/pull/289
