### ISSUE TITLE
Upgrade Kubernetes

### ISSUE THREAD

**Issue by tcheronneau** [rancher/rke#970]
**RKE version: 0.1.11** 

**Docker version: 17.03 (`docker version`,`docker info` preferred)**

**Operating system and kernel: Centos 7. Kernel 3.10.0(`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: VMware(VirtualBox/Bare-metal/AWS/GCE/DO)**

**cluster.yml file: too long**

**Steps to Reproduce:**
rke up 

**Results:**
No upgrade. 

We wanted to upgrade our cluster from 1.10.5 to 1.11.3. 
I've tried everything I could find : 
- Change of kubernetes_version
- Change of system_images: kubernetes to the good one. 
- Change of each image in each component. 

After that I've tried an upgrade of RKE itself (we were at version 0.1.8). 
Then I've done rke up and my cluster went to 1.11.3. 
But since I've changed tag in each component I tried to upgrade to 1.12.1 this time and no way. 

Does RKE let us choose our version or not ?

**Comment by sebastien-prudhomme** [comment]
1.12.1 is not yet available in RKE, use 1.12.0 but be carefull as they said that this is experimental

**Comment by tcheronneau** [comment]
And how/where did you specify the version you want to deploy ?
Because with this doc https://rancher.com/docs/rke/v0.1.x/en/upgrades/ it does not work.

**Comment by sebastien-prudhomme** [comment]
https://rancher.com/docs/rke/v0.1.x/en/config-options/#kubernetes-version

**Comment by galal-hussein** [comment]
@tcheronneau Upgrading depends mainly on the rke version, the latest rke version support k8s versions mentioned in https://rancher.com/docs/rke/v0.1.x/en/config-options/#kubernetes-version.

You still can upgrade to 1.12 by changing the kubernetes image in system images: 
https://rancher.com/docs/rke/v0.1.x/en/upgrades/, if you still having a problem with upgrade can you post the rke logs with debug flag enabled.

**Comment by tcheronneau** [comment]
Thanks guys fully working with https://rancher.com/docs/rke/v0.1.x/en/config-options/#kubernetes-version. 
Do you know if there is a plan to allow downgrade as well with this method ?

**Comment by superseb** [comment]
Not currently, let us know if there is anything else needed on this.
