### ISSUE TITLE
Inconsistent and undocumented components' names

### ISSUE THREAD

**Issue by yasker** [rancher/rke#975]
The service names are random. There is no way to tell that a user should use scheduler instead of kube-scheduler, kubeproxy instead of kube-proxy, kube-controller instead of kube-controller-manager unless they look into the [code](https://github.com/rancher/rke/blob/1f6e254f6698a26751d2948504d915348d6fda0a/vendor/github.com/rancher/types/apis/management.cattle.io/v3/rke_types.go#L150) and found this:

```
type RKEConfigServices struct {
	// Etcd Service
	Etcd ETCDService `yaml:"etcd" json:"etcd,omitempty"`
	// KubeAPI Service
	KubeAPI KubeAPIService `yaml:"kube-api" json:"kubeApi,omitempty"`
	// KubeController Service
	KubeController KubeControllerService `yaml:"kube-controller" json:"kubeController,omitempty"`
	// Scheduler Service
	Scheduler SchedulerService `yaml:"scheduler" json:"scheduler,omitempty"`
	// Kubelet Service
	Kubelet KubeletService `yaml:"kubelet" json:"kubelet,omitempty"`
	// KubeProxy Service
	Kubeproxy KubeproxyService `yaml:"kubeproxy" json:"kubeproxy,omitempty"`
}
```

We should either document those or correct those arbitrary names. Otherwise, there is no way users can know which component name should be used for configuration.

https://github.com/rancher/rke/issues/923

**Comment by deniseschannon** [comment]
@superseb can you see if there is anything missing in this section and should be added:

https://rancher.com/docs/rke/latest/en/config-options/services/

and if you think we should add an example section of these services?

**Comment by soumyalj** [comment]
Verified the docs https://rancher.com/docs/rke/latest/en/config-options/services/
Each of the K8s components and the corresponding names in cluster.yml are specified correctly.
