### ISSUE TITLE
Handling etcd Add/Remove

### ISSUE THREAD

**Issue by JohnDavidLarsen** [rancher/rke#985]
Related to Issue #225

If I start with a 3 node cluster, then I remove a single node and add it back, it doesn't ever restore functionality as a 3 node cluster, it continues to fail, you have to revert to a single node cluster, then ramp up to 3 nodes.  I can manually remove a node using etcdctl  member remove, then add the cluster back and it works, but should this be necessary? Can there be a UI utility for managing the etcd cluster?

**Comment by JohnDavidLarsen** [comment]
Building a 3 node cluster using the UI, using Custom "from my own nodes".  With all 3 being etc,control plane,worker nodes.
Deleted one of the 3 nodes using the UI.
In deleted node  I 
  docker rm -f `docker ps -aq`
  docker volume rm `docker volume ls -q`
 rm -rf /etc/cni /etc/kubenetes /opt/cni /var/run/calico /var/run/kubernetes /var/lib/etcd /var/lib/cni /var/run/flanner /var/run/secrets

then I readded the node as a etc,controlplane,worker node
the etcd kept giving failure error messages (though everything worked just fine).

To fix I removed the nodes and wipes the same files again.
I then went into one of the etcd containers and ran
etcdctl (connection information) member list
seeing the left over node I 
etcdctl (connection information) member remove XYZ..

then readded the node and it readded correctly. 

I repeated these steps again to confirm the bug. It leaves the nodes in the member list an I have to manually remove the node before I can re add the same node with the same IP address.

**Comment by JohnDavidLarsen** [comment]
V2.1.0

**Comment by deniseschannon** [comment]
@JohnDavidLarsen This should be filed in the rancher/rancher repo. 

How rancher launched k8s clusters using RKE is slightly different than when launching In RKE CLI. 

If you are still having issues in Rancher, please file a new issue.
