### ISSUE TITLE
Use RKE to deploy Kubernetes on multi-architecture (AMD + PPC) environment 

### ISSUE THREAD

**Issue by dnoland1** [rancher/rke#988]
This is a feature request to add support in RKE to deploy a multi-architecture cluster that consists of both amd64 and ppc64 nodes.

**Comment by Oats87** [comment]
👍 I don't think this would be that far-fetched to do.

**Comment by eddieparker** [comment]
Just adding that I came here to write up a similar bug.  In case the use case is useful: I'd like to have a series of raspberry pi (rancher os amd64) running with amd64, but trying to use it with rke right now yields an error on rke up:

``` bash
INFO[0108] [network] Port listener containers deployed successfully
INFO[0108] [network] Running control plane -> etcd port checks
INFO[0109] [network] Successfully started [rke-port-checker] container on host [10.0.0.21]
FATA[0110] [network] Host [10.0.0.21] is not able to connect to the following ports: [standard_init_linux.go:190: exec user process caused
"exec format error"]. Please check network policies and firewall rules
```

And the host itself is complaining in it's docker image:

```
tornedron raspberrypi-rancheros # ssh rancher@10.0.0.21
[rancher@pi-node-01 ~]$ sudo docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                      PORTS               NAMES
292b26c78289        rancher/rke-tools:v0.1.16   "nc -kl -p 1337 -e e…"   28 minutes ago      Exited (1) 26 minutes ago                       rke-cp-port-listener
6127cb3913bb        rancher/rke-tools:v0.1.16   "nc -kl -p 1337 -e e…"   28 minutes ago      Exited (1) 26 minutes ago                       rke-etcd-port-listener
[rancher@pi-node-01 ~]$ sudo docker logs -f 6127cb3913bb
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
```

It would be nice to mention in the cluster.yaml the architecture for the node and have it use the appropriate system_image.

Is there a work around in the meantime?  Or should I just make my cluster the ol' fashioned way?

**Comment by MrBr-github** [comment]
Any updates/progress on ppc64le support ?

**Comment by optimuspaul** [comment]
I'd like AMD64 and ARM64. I've tried swapping out images to multi-arch Images but not working.
