### ISSUE TITLE
Rolling Snapshots are not done after docker host reboot

### ISSUE THREAD

**Issue by RedPepper** [rancher/rke#992]
**RKE version:**
`
rke version v0.1.9
`
**Docker version: (`docker version`,`docker info` preferred)**
`
Containers: 48
 Running: 26
 Paused: 0
 Stopped: 22
Images: 17
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 9.743 GiB
Name: node1.k8s.dev.de.esl.systems
ID: KKQ2:DUQ2:IJFN:HFFI:O6G7:EPKW:FHLD:LWJZ:AK7V:RMMR:F2OT:LM77
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

`
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
uname -r
4.9.0-8-amd64

`
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Nutanix VM
**cluster.yml file:**
`
---
ssh_agent_auth: true
nodes:
  - address: node1
    user: root
    role: [controlplane,etcd,worker]

  - address: node2
    user: root
    role: [controlplane,etcd,worker]

  - address: node3
    user: root
    role: [controlplane,etcd,worker]

  - address: node4
    user: root
    role: [worker]

cluster_name: dev

services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge

network:
    plugin: flannel
    options:
      flannel_iface: ens3

kubernetes_version: v1.11.0-rancher1
system_images:
    kubernetes: rancher/hyperkube:v1.11.0-rancher1

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/ssl-redirect: "false"        # Disable redirect to ssl
  spec:
    rules:
    - host: k8s.dev.de.esl.systems
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:stable
          args:
          - --no-cacerts
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
`
**Steps to Reproduce:**
Deploy yaml with rolling snapshots reboot one host
**Results:**
docker container with the name of etcd-rolling-snapshots does not come back

**Comment by galal-hussein** [comment]
@RedPepper Thanks for filing this issue, the rolling snapshot container is missing the restart policy option

**Comment by RedPepper** [comment]
we tried it already and works like a charm thank you !

**Comment by soumyalj** [comment]
Reproduced the issue with rke version v0.1.9.
Tested with rke version v0.2.0-rc5.
1. Created a 3 node cluster( N1, N2, N3 - all roles in each node) with snapshots enabled every 5m 
2. Ensured backups are happening periodically
3. Reboot N2.
4. After reboot, verified that snapshots continue to happen on N2 and other nodes too.
