### ISSUE TITLE
feature: update cluster config file

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rancher/rke#993]
Hi everyone,

One little annoying thing when updating RKE binary is there is no easy way to figure out what new parameters are available in the new version.

The method i use is generating a new cluster.yml with "rke config" and do a diff with my current cluster.yml.

Would it be possible to add a command that take an existing cluster.yml file and update it with the new parameters, the new default system images and even new default values for existing parameters?

Thanks

**Comment by mtchuyen** [comment]
I have the same problem.

```
WARN[0000] This is not an officially supported version (v0.0.12-dev) of RKE. Please download the latest official release at https://$
ithub.com/rancher/rke/releases/latest 
```

**Comment by 631068264** [comment]
So how to update ? @deniseschannon
